### ISSUE TITLE
Request for modifying helm-bibtex behaviour

### ISSUE THREAD

**Issue by jag2** [jkitchin/org-ref#10]
I would like org-ref to run the functions, for example helm-bibtex-open-pdf, just by pressing the corresponding numbers, instead of having to also press the return key. I would also like to be able to modify these keys, and use something like "n" for notes, "p" for pdf and so on, which I think is more intuitive.

**Comment by jkitchin** [comment]
I do not think that is possible with helm. You can press function keys, e.g. f1, f2, f3 to do the first, second or third action, but you have to press C-z to see what these actions are until you have committed them to memory.

You can do something like that with the old mini buffer menu which you can customize in this variable:

(defcustom org-ref-cite-onclick-function
  'org-ref-cite-click-helm
  "Function that runs when you click on a cite link. The function must take no arguments. You may also use `org-ref-cite-onclick-minibuffer-menu' if you do not like helm."
 :type 'function
 :group 'org-ref)

or by using a hydra interface that you would write yourself.
