### ISSUE TITLE
Error during processing bibtex entry from doi

### ISSUE THREAD

**Issue by yujitakenoshita** [jkitchin/org-ref#100]
I just installed org-ref, melpa version.
When I try to drag-n-drop a pdf file containing doi, an error occurs.

Contacting host: dx.doi.org:80
doi-utils-doi-to-bibtex-string: Wrong type argument: integer-or-marker-p, nil

Emacs version is 24.5.2, run on Mac El Capitan.  I installed it via homebrew.

**Comment by jkitchin** [comment]
what doi was it?

**Comment by yujitakenoshita** [comment]
It seemed some of my own settings in .emacs.d/init.el provoke the problem.  When I refreshed my init.el, it goes pretty well.  I am sorry to have disturbed you.
