### ISSUE TITLE
Add back default definitions for some org-ref functions?

### ISSUE THREAD

**Issue by treese** [jkitchin/org-ref#1004]
README.org says for using ivy-bibtex:

> If you prefer ivy-bibtex, you should use this. It requires ivy-bibtex, but this is not currently automatically installed by MELPA.

> 
> (require 'org-ref-ivy)
> 
> (setq org-ref-insert-link-function 'org-ref-insert-link-hydra/body
>       org-ref-insert-cite-function 'org-ref-cite-insert-ivy
>       org-ref-insert-label-function 'org-ref-insert-label-link
>       org-ref-insert-ref-function 'org-ref-insert-ref-link
>       org-ref-cite-onclick-function (lambda (_) (org-ref-citation-hydra/body)))

and for helm-bibtex, this:

> If you prefer helm, you can instead use this. This uses code from helm-bibtex for citation insertion. It requires helm-bibtex, but this is not currently automatically installed by MELPA.
> 
> (require 'org-ref-helm)
> (setq org-ref-insert-link-function 'org-ref-insert-link-hydra/body
>       org-ref-insert-cite-function 'org-ref-cite-insert-helm
>       org-ref-insert-label-function 'org-ref-insert-label-link
>       org-ref-insert-ref-function 'org-ref-insert-ref-link
>       org-ref-cite-onclick-function (lambda (_) (org-ref-citation-hydra/body)))

These are the same except for the `require` call and setting `org-ref-cite-function`. Would it make sense to make the other settings the default values of those variables?

I'd be happy to draft a pull request for this (both code and doc) if it makes sense.

**Comment by jkitchin** [comment]
These are basically already set as defaults in org-ref.el.  I cleaned up the README and set these in the ivy/helm files.
