### ISSUE TITLE
org-ref-bibtex-assoc-pdf

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1006]
Using H-b on a bibtex entry, and then selecting Add pdf, opens local the dirtectory where the bib-file is stored, instead of the path defined by `bibtex-completion-library-path`  (i.e. where I store my pdf files). Is there a way to configure this?

**Comment by uliw** [comment]
Typically, pdf copies of papers are stored in a given directory. That its at least how Zotero and company do it.
Helm-bibtex assumes a similar setup, and in my reading `bibtex-completion-library-path` is used to specify where the pdf files are located.
```
(defcustom bibtex-completion-library-path nil
  "A directory or list of directories in which PDFs are stored.
Bibtex-completion assumes that the names of these PDFs are
composed of the BibTeX-key plus a \".pdf\" suffix."
  :group 'bibtex-completion
  :type '(choice directory (repeat directory)))
```
I somewhat naively assumed that this would intergrate with org-ref. However, even the option to set this manually would be great!

**Comment by jkitchin** [comment]
if they are already stored in `bibtex-completion-library-path` as key.pdf, there is no need to reassociate them. This function is primarily used when you have separately downloaded a pdf that you want to associate. 

If you have entries with a file field, it is also not necessary to use this function, I think bibtex-completion should already find those, or you can setup a find pdf file function that gets the path from the entry.

**Comment by uliw** [comment]
Apologies, I should have provided more context. The problem arises when I use the doi-utils, but the automatic download fails. After manually downloading the pdf I typically have a file called `s0-11111_125467.pdf` etc.. I than move the downloaded file into the pdf-directory I use to store papers, and type `H-b A` to select the downloaded file so that it is renamed to bibkey.pdf. (This avoids doing the renaming manually).

The file selection for `H-b A` starts in the directory where the bibtex files are stored, which requires navigating to the pdf file directory to finish the process. If it were possible to set the directory where `H-b A` starts, the process would be considerably faster.

**Comment by jkitchin** [comment]
I added a feature for this. A pro-tip though is the key for that pdf should be on the clipboard, so once you download it, it is probably faster to click on the filename to select it all, and then just paste the key there. Then, if you move it to your bibtex pdf directory, it is already associated automatically.

**Comment by uliw** [comment]
Neat! I was not aware of the clipboard feature. It does improve the workflow considerably!
