### ISSUE TITLE
show pdf file?

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1007]
Using H-b on a bibtex entry, and then selecting open pdf, results in the hfollowing message

`Searching for program: No such file or directory, open`

**Comment by jkitchin** [comment]
I think that is using `bibtex-completion-open-pdf`, which is probably in turn calling a function in the variable `bibtex-completion-pdf-open-function`. On my machine, that variable points to a lambda function like `(lambda (fpath) (call-process "open" nil 0 nil fpath))`. This is perhaps mac specific.

You could:

    (setq bibtex-completion-pdf-open-function #'find-file) 

which is the default.

**Comment by uliw** [comment]
that does the trick!
