### ISSUE TITLE
doi that trips up doiutils

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1008]
The following doi results in the text below, rather than a bibentry. Could be on the publishers end.

`https://doi.org/10.1002/9781119595007.ch11`

yields:

other not supported yet (:indexed (:date-parts [[2022 4 22]] :date-time "2022-04-22T22:12:38Z" :timestamp 1650665558386) :edition-number "1" :reference-count 72 :publisher "Wiley" :license [(:start (:date-parts [[2022 4 15]] :date-time "2022-04-15T00:00:00Z" :timestamp 1649980800000) :content-version "tdm" :delay-in-days 0 :URL "http://doi.wiley.com/10.1002/tdm_license_1.1") (:start (:date-parts [[2022 4 15]] :date-time "2022-04-15T00:00:00Z" :timestamp 1649980800000) :content-version "tdm" :delay-in-days 0 :URL "http://doi.wiley.com/10.1002/tdm_license_1.1") (:start (:date-parts [[2022 4 15]] :date-time "2022-04-15T00:00:00Z" :timestamp 1649980800000) :content-version "tdm" :delay-in-days 0 :URL "http://doi.wiley.com/10.1002/tdm_license_1.1") (:start (:date-parts [[2022 4 15]] :date-time "2022-04-15T00:00:00Z" :timestamp 1649980800000) :content-version "tdm" :delay-in-days 0 :URL "http://doi.wiley.com/10.1002/tdm_license_1.1")] :content-domain (:domain [] :crossmark-restriction :json-false) :published-print (:date-parts [[2022 4 15]]) :DOI "10.1002/9781119595007.ch11" :type "other" :created (:date-parts [[2022 4 22]] :date-time "2022-04-22T21:28:31Z" :timestamp 1650662911000) :page "271-284" :source "Crossref" :is-referenced-by-count 1 :title "The Effects of Reactive Transport on Sulfur Isotopic Compositions in Natural Environments" :prefix "10.1002" :author [(:given "Alexandra V." :family "Turchyn" :sequence "first" :affiliation []) (:given "Jennifer L." :family "Druhan" :sequence "additional" :affiliation [])] :member "311" :published-online (:date-parts [[2022 4 22]]) :reference [(:key "e_1_2_1_2_1" :doi-asserted-by "publisher" :DOI "10.1016/S0016-7037(99)00292-6") (:key "e_1_2_1_3_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2010.05.008") (:key "e_1_2_1_4_1" :doi-asserted-by "publisher" :DOI "10.3389/feart.2019.00140") (:key "e_1_2_1_5_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2017.01.015") (:key "e_1_2_1_6_1" :doi-asserted-by "publisher" :DOI "10.1016/j.conbuildmat.2018.07.250") (:key "e_1_2_1_7_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2007.04.017") (:key "e_1_2_1_8_1" :doi-asserted-by "publisher" :DOI "10.1016/S0065-2164(09)01202-7") (:key "e_1_2_1_9_1" :doi-asserted-by "publisher" :DOI "10.1016/0016-7037(84)90301-6") (:key "e_1_2_1_10_1" :doi-asserted-by "publisher" :DOI "10.1111/gbi.12149") (:key "e_1_2_1_11_1" :doi-asserted-by "crossref" :unstructured "Brüchert V.(2004).Physiological and ecological aspects of sulfur isotope fractionation during bacterial sulfate reduction.Special Papers – Geological Society of America 1–16." :DOI "10.1130/0-8137-2379-5.1") (:key "e_1_2_1_12_1" :doi-asserted-by "publisher" :DOI "10.1016/S0016-7037(00)00557-3") (:key "e_1_2_1_13_1" :doi-asserted-by "publisher" :DOI "10.3389/feart.2016.00075") (:key "e_1_2_1_14_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2005.04.015") (:key "e_1_2_1_15_1" :doi-asserted-by "publisher" :DOI "10.1016/j.apgeochem.2012.04.013") (:key "e_1_2_1_16_1" :doi-asserted-by "publisher" :DOI "10.4319/lo.1998.43.2.0253") (:key "e_1_2_1_17_1" :doi-asserted-by "publisher" :DOI "10.1139/m75-234") (:key "e_1_2_1_18_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2008.12.015") (:key "e_1_2_1_19_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2007.11.039") (:key "e_1_2_1_20_1" :doi-asserted-by "publisher" :DOI "10.2475/ajs.306.4.246") (:key "e_1_2_1_21_1" :doi-asserted-by "publisher" :DOI "10.1128/AEM.67.2.888-894.2001") (:key "e_1_2_1_22_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2013.08.037") (:key "e_1_2_1_23_1" :doi-asserted-by "publisher" :DOI "10.1021/es302016p") (:key "e_1_2_1_24_1" :volume-title "Isotopic Constraints on Earth System Processes" :author "Druhan J. L." :year "2022") (:key "e_1_2_1_25_1" :doi-asserted-by "publisher" :DOI "10.1146/annurev-earth-060313-054802") (:key "e_1_2_1_26_1" :doi-asserted-by "publisher" :DOI "10.1016/0016-7037(79)90095-4") (:key "e_1_2_1_27_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2019.05.015") (:key "e_1_2_1_28_1" :doi-asserted-by "publisher" :DOI "10.1007/s00253-011-3542-6") (:key "e_1_2_1_29_1" :doi-asserted-by "publisher" :DOI "10.1029/1999WR900013") (:key "e_1_2_1_30_1" :doi-asserted-by "publisher" :DOI "10.3109/15563650.2013.767908") (:key "e_1_2_1_31_1" :doi-asserted-by "publisher" :DOI "10.1038/ismej.2015.50") (:key "e_1_2_1_32_1" :doi-asserted-by "publisher" :DOI "10.1128/AEM.69.12.7063-7072.2003") (:key "e_1_2_1_33_1" :doi-asserted-by "publisher" :DOI "10.1515/9780691220239") (:key "e_1_2_1_34_1" :doi-asserted-by "publisher" :DOI "10.3389/feart.2019.00041") (:key "e_1_2_1_35_1" :doi-asserted-by "publisher" :DOI "10.1021/acs.est.5b03208") (:key "e_1_2_1_36_1" :doi-asserted-by "publisher" :DOI "10.1016/S0006‐3495(02)73945‐3") (:key "e_1_2_1_37_1" :doi-asserted-by "publisher" :DOI "10.1128/AEM.69.4.2340-2348.2003") (:key "e_1_2_1_38_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2004.08.010") (:key "e_1_2_1_39_1" :doi-asserted-by "publisher" :DOI "10.2475/04.2007.01") (:key "e_1_2_1_40_1" :doi-asserted-by "publisher" :DOI "10.2138/gsrmg.55.1.289") (:key "e_1_2_1_41_1" :doi-asserted-by "publisher" :DOI "10.1002/9781119595007.ch10") (:key "e_1_2_1_42_1" :doi-asserted-by "publisher" :DOI "10.1038/nature13698") (:key "e_1_2_1_43_1" :doi-asserted-by "publisher" :DOI "10.1016/j.earscirev.2011.02.003") (:key "e_1_2_1_44_1" :doi-asserted-by "publisher" :DOI "10.1016/0016-7037(79)90201-1") (:key "e_1_2_1_45_1" :doi-asserted-by "publisher" :DOI "10.1007/3-540-32144-6_8") (:issue "2" :key "e_1_2_1_46_1" :first-page "195" :article-title "Microbiological fractionation of Sulphur isotopes" :volume "34" :author "Kaplan I. R." :year "1964" :journal-title "Microbiology") (:key "e_1_2_1_47_1" :doi-asserted-by "publisher" :DOI "10.1007/s00027‐004‐0004‐6") (:key "e_1_2_1_48_1" :doi-asserted-by "publisher" :DOI "10.3389/fmicb.2015.01392") (:key "e_1_2_1_49_1" :doi-asserted-by "publisher" :DOI "10.1073/pnas.1218874110") (:key "e_1_2_1_50_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2013.10.051") (:key "e_1_2_1_51_1" :doi-asserted-by "publisher" :DOI "10.1021/es201111y") (:key "e_1_2_1_52_1" :doi-asserted-by "publisher" :DOI "10.1016/j.jconhyd.2009.10.006") (:key "e_1_2_1_53_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2007.10.027") (:key "e_1_2_1_54_1" :doi-asserted-by "publisher" :DOI "10.1029/2005WR004848") (:key "e_1_2_1_55_1" :doi-asserted-by "publisher" :DOI "10.1016/j.cemconres.2018.03.016") (:key "e_1_2_1_56_1" :doi-asserted-by "publisher" :DOI "10.1016/j.epsl.2016.08.001") (:key "e_1_2_1_57_1" :doi-asserted-by "publisher" :DOI "10.1126/science.11539502") (:key "e_1_2_1_58_1" :doi-asserted-by "publisher" :DOI "10.1088/1742-6596/377/1/012054") (:key "e_1_2_1_59_1" :doi-asserted-by "publisher" :DOI "10.3389/fmicb.2011.00081") (:key "e_1_2_1_60_1" :doi-asserted-by "publisher" :DOI "10.1016/S0009-2541(03)00237-7") (:key "e_1_2_1_61_1" :doi-asserted-by "publisher" :DOI "10.1080/10643389.2010.534029") (:key "e_1_2_1_62_1" :doi-asserted-by "publisher" :DOI "10.1146/annurev.pa.32.040192.000545") (:key "e_1_2_1_63_1" :doi-asserted-by "publisher" :DOI "10.1016/0016-7037(73)90052-5") (:key "e_1_2_1_64_1" :doi-asserted-by "publisher" :DOI "10.1016/S0016-7037(00)00579-2") (:key "e_1_2_1_65_1" :doi-asserted-by "publisher" :DOI "10.1016/S0012‐8252(03)00054‐0") (:key "e_1_2_1_66_1" :doi-asserted-by "publisher" :DOI "10.1126/science.1205103") (:key "e_1_2_1_67_1" :doi-asserted-by "publisher" :DOI "10.1016/j.gca.2010.01.004") (:key "e_1_2_1_68_1" :doi-asserted-by "publisher" :DOI "10.1007/s002489900101") (:key "e_1_2_1_69_1" :doi-asserted-by "publisher" :DOI "10.1128/9781555817589.ch7") (:key "e_1_2_1_70_1" :doi-asserted-by "publisher" :DOI "10.1007/BF00309575") (:key "e_1_2_1_71_1" :doi-asserted-by "publisher" :DOI "10.1126/science.290.5497.1711") (:key "e_1_2_1_72_1" :doi-asserted-by "publisher" :DOI "10.1038/ismej.2017.185") (:key "e_1_2_1_73_1" :doi-asserted-by "publisher" :DOI "10.1073/pnas.1407502111")] :container-title "Isotopic Constraints on Earth System Processes" :original-title [] :link [(:URL "https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781119595007.ch11" :content-type "application/pdf" :content-version "vor" :intended-application "text-mining") (:URL "https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781119595007.ch11" :content-type "unspecified" :content-version "vor" :intended-application "similarity-checking")] :deposited (:date-parts [[2022 4 22]] :date-time "2022-04-22T21:30:23Z" :timestamp 1650663023000) :score 1 :resource (:primary (:URL "https://onlinelibrary.wiley.com/doi/10.1002/9781119595007.ch11")) :subtitle [] :short-title [] :issued (:date-parts [[2022 4 15]]) :references-count 72 :alternative-id ["10.1002/9781119595007.ch11" "10.1002/SERIES5064" "10.1002/9781119595007"] :URL "http://dx.doi.org/10.1002/9781119595007.ch11" :relation nil :ISSN ["2328-8779"] :published (:date-parts [[2022 4 15]])).

**Comment by jkitchin** [comment]
This happens because the publisher marked this as an "other" type.

It is a little tricky to figure out the right thing to do here. This is pretty clearly a book chapter, but it isn't obvious an "other" would always be a book chapter. The challenge is mapping "other" to a bibtex type.

You could add this, which will make it a misc type, and then you could change it to inbook or something.

```
(doi-utils-def-bibtex-type misc ("posted-content" "other")
			   author booktitle series publisher title year doi url)
```

**Comment by uliw** [comment]
thanks!
