### ISSUE TITLE
PDF file produced with warnings: [undefined citation] in org-ref version 3

### ISSUE THREAD

**Issue by simenojensen** [jkitchin/org-ref#1009]
Hi,

I'm encountering some problems when exporting from my org file to pdf when adding org-ref citations and the following at the bottom of my org file. This exact same setup worked in the previous version of **org-ref**:

```
This is a citation [[cite:&yuReviewRecurrentNeural2019]]

bibliographystyle:ieeetr
bibliography:./library.bib

```
The `org-latex-pdf-process` variable is `"latexmk -shell-escape -xelatex -recorder -synctex=1 -bibtex-cond %b"
`
The *\*Org PDF LaTeX Output*\* buffer shows the following information:

```
LaTeX Warning: Citation `&yuReviewRecurrentNeural2019' on page 1 undefined on i
nput line 175.

No file test.bbl.
[1] (./test.aux)

LaTeX Warning: There were undefined references.

```

Would love any pointers to what might be the problem

Thanks!

**Comment by jkitchin** [comment]
Have you updated to the most current version of org-ref? If not, you should leave the & out, and stick with the version 2 syntax. The error suggests you are still using an old version of org-ref.

**Comment by simenojensen** [comment]
Thanks! Removing the ampersand worked.

**Comment by jkitchin** [comment]
I think this means you are still using an old version of org-ref. (I assume you manually added the & right)

There is no reason to update if it works for you. The new version supports a richer syntax for post/pre notes, and has better CSL support. But, also one day it might transition over to the org-cite syntax.

**Comment by simenojensen** [comment]
My fix resulted in changing *org-ref-cite-insert-version* to *2*.

I.e.
```
  (use-package org-ref
    :after org
    :config
    (setq org-ref-cite-insert-version 2)
   ...
```
