### ISSUE TITLE
Role of ox-bibtex

### ISSUE THREAD

**Issue by stvharman** [jkitchin/org-ref#101]
On the most recent Emacs+Org with org-ref installed from MELPA:

Clicking on a bibtex citation doesn not work right unless ox-bibtex is required in the init file. ox-bibtex provides a function called org-bibtex-file. If ox-bibtex is not included, then the following error occurs:

"org-open-at-point: Symbol's value as variable is void: org-bibtex-file"

Subsequently, no menu for the citation opens up.

**Comment by jkitchin** [comment]
I cannot reproduce this. It works for me and I don't have ox-bibtex required anywhere, and org-bibtex-file is not anywhere in the org-ref src as far as I know. Maybe you have something set differently in your init files?

**Comment by stvharman** [comment]
I checked the init file and saw that ox-bibtex was required in one of them.
When  I removed both require statements it worked. With one, it did not.
thanks

**Comment by jkitchin** [comment]
You found ox-bibtex required in an org-ref file?

On Sunday, January 3, 2016, stvharman <notifications@github.com> wrote:

> I checked the init file and saw that ox-bibtex was required in one of them.
> When I removed both require statements it worked. With one, it did not.
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/101#issuecomment-168541031>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by stvharman** [comment]
Yes, it was. THat's what caused the problem. However, I have no idea why requiring it for a second time used to solve the issue. Currently, they are both removed (I really didn't need it).

**Comment by jkitchin** [comment]
where (what file) did you find it? grep ox-bibtex *.el turns up nothing for me in the org-ref directory.

**Comment by jkitchin** [comment]
On looking at ox-bibtex, it might be incompatible with org-ref since it also defines a cite link. So, the order it was loaded would affect what you observed, i.e. if it is loaded after org-ref you would see problems with cite links, but if loaded before probably not.

**Comment by stvharman** [comment]
I think your insight may be right. Thanks. 
Does org-ref work with the publishing framework in Emacs? I am trying to judge if ox-bibtex is still needed anyway or if it can be replaced by org-ref.

**Comment by jkitchin** [comment]
What do mean by works? The links all export in html and latex as far as I know. I don't use the publishing features though so it is not well tested for that.

**Comment by stvharman** [comment]
ox-bibtex uses another program called bibtex2html to produce citations and references according to a particular bib style and produces the html output with them. You can take a quick look at the header comments in the ox-bibtex.el file.

**Comment by jkitchin** [comment]
I don't plan to use bibtex2html in org-ref. It is not easy to install on Windows. The approach org-ref will take is described here http://kitchingroup.cheme.cmu.edu/blog/2015/12/11/Introduction-to-a-citation-processor-in-org-ref/
