### ISSUE TITLE
multiple citation syntax not exporting correctly to LaTeX using org-ref v3 

### ISSUE THREAD

**Issue by whatsreal** [jkitchin/org-ref#1010]
At Professor Kitchin's request I am posting this issue here. (Originally on Stack Exchange and org-mode mailing list.)

I am writing my dissertation in org-mode with org-ref to handle citations. I can not get a multi-source multi-note citation to export correctly.

Here is the org-mode code:

```
[[cite:On Van Tillian apologetics see &frame15_apolog; and
&frame95_cornel_van_til; One example in systematic theology is
&frame13:-system-theol; Finally on christian worship see
&frame97_contem_worsh_music; and &frame96_worsh_spirit_truth]]
```
Which exports to:

`\cite[On Van Tillian apologetics see][]{frame15_apolog,frame95_cornel_van_til,frame13:-system-theol,frame97_contem_worsh_music,frame96_worsh_spirit_truth}}`
Notice that only the first note is exported and then it is just the sources.

I do have the fallback of using multiple `[[cite:source][text::text]]` blocks, but I'd rather use the new syntax if it works.

For testing purposes here is the relevant section of my .bib file:
```
@book{frame95_cornel_van_til,
  Author =	 {John M. Frame},
  Date =	 {1995-11-30},
  EAN =		 9780875522456,
  ISBN =	 0875522459,
  PageTotal =	 {480 Seiten},
  Publisher =	 {P \& R PUB CO},
  Title =	 {Cornelius Van Til: An Analysis of His Thought},
  URL =
  {https://www.ebook.de/de/product/3323519/john_m_frame_cornelius_van_til_an_analysis_of_his_thought.html},
  Year =	 1995,
}

@book{frame15_apolog,
  Author =	 {John M. Frame},
  Date =	 {2015-06-16},
  EAN =		 9781596389380,
  ISBN =	 1596389389,
  PageTotal =	 {384 Seiten},
  Publisher =	 {P \& R PUB CO},
  Title =	 {Apologetics: A Justification of Christian Belief},
  URL =
  {https://www.ebook.de/de/product/24025880/john_m_frame_apologetics_a_justification_of_christian_belief.html},
  Year =	 2015,
}

@book{frame96_worsh_spirit_truth,
  Author =	 {John M. Frame},
  Date =	 {1996-04-30},
  EAN =		 9780875522425,
  ISBN =	 0875522424,
  PageTotal =	 {192 Seiten},
  Publisher =	 {P \& R PUB CO},
  Title =	 {Worship in Spirit and Truth: A Refreshing Study of
  the Principles and Practice of Biblical Worship},
  URL =
  {https://www.ebook.de/de/product/3323518/john_m_frame_worship_in_spirit_and_truth_a_refreshing_study_of_the_principles_and_practice_of_biblical_worship.html},
  Year =	 1996,
}

@book{frame97_contem_worsh_music,
  Author =	 {John M. Frame},
  Date =	 {1997-09-30},
  EAN =		 9780875522128,
  ISBN =	 0875522122,
  PageTotal =	 {224 Seiten},
  Publisher =	 {P \& R PUB CO},
  Title =	 {Contemporary Worship Music: A Biblical Defense},
  URL =
  {https://www.ebook.de/de/product/3323512/john_m_frame_contemporary_worship_music_a_biblical_defense.html},
  Year =	 1997,
}

@Book{frame13:-system-theol,
  author =    {John M. Frame},
  title =        {Systematic Theology: An Introduction to Christian Belief},
  publisher =    {P\&R Publishing},
  year =         2013,
  address =   {Phillipsburg, NJ}}
```

**Comment by jkitchin** [comment]
What output are you expecting? The plain cite command does not support what you imply in the citation, it only allows one prenote, and one post note as far as I know (which is what you have, the first prenote is "On Van Tillian apologetics see", and there is no post note at the end).

Presumably you are expecting something like this?

\cites[On Van Tillian apologetics see ]{frame15_apolog}[ and ]{frame95_cornel_van_til}[ One example in systematic theology is ]{frame13:-system-theol}[ Finally on christian worship see ]{frame97_contem_worsh_music}[ and ]{frame96_worsh_spirit_truth} 

in this case you must use [[cites:...]] instead of [[cite:...] or one of the other multcite versions, and you have to use biblatex. I don't know if this can be supported with natbib/bibtex off the top of my head.

**Comment by whatsreal** [comment]
I really hate it when it is something that simple. I am using biblatex, so cites should work for me. Thanks!
