### ISSUE TITLE
Creating a new bibtex entry in the library.bib 

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#1011]
Wonderful package. 

Is it possible in `org-ref` to add a new bibliography entry to `library.bib` without leaving the buffer we are working in while creating an in-text citation at the same time at point? 

This would be useful when finding references in the moment and adding them as citations in the fly. Thanks!

**Comment by jkitchin** [comment]
have you tried `doi-add-bibtex-entry`? Also see `crossref-add-bibtex-entry`.

This does not insert a citation, but it does copy a key to the clipboard so you can immediately paste it. You still have to write cite:& though. Or after running it, you can do C-c ] (or what you have bound it to) and the last entry should be the first one, so you should be able to just press enter.

If those don't meet your needs, they are the pieces you need to write your own short interactive function for that purpose.

**Comment by AtomicNess123** [comment]
Thanks! Is there a hydra included in the package with all the functions and possibilities that I can call while writing the paper in the buffer? It would be great.

**Comment by jkitchin** [comment]
There are a few hydras.  See org-ref-insert-link-hydra for the insertion hydra.  In a bibtex file there is org-ref-bibtex-hydra.

When you click on a citation you get org-ref-citation-hydra.

**Comment by AtomicNess123** [comment]
One more question: the function `org-ref-url-html-to-bibtex` is not implemented in the hydra 'org-ref-bibtex-hydra/body. Unless I am confused. Thanks.

**Comment by jkitchin** [comment]
that is correct. It is not currently implemented there.
