### ISSUE TITLE
Open from citation does not open

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#1012]
When I hover over a citation, and press `o` (according to the hydra menu), I get the message:

`Position saved to mark ring, go back with 'C-c &'`

Is this correct?

**Comment by jkitchin** [comment]
Your description of the problem doesn't make sense to me. If you hover on a citation you should only see a tooltip.

If you mean you click on the citation, and get a hydra, then pressing `o` should open the bibtex entry.

**Comment by AtomicNess123** [comment]
Ok, after playing around, it seems that if the org buffer where I am writing has a pointed `.bib` file:

` bibliography:~/Dropbox/@article1.bib`

It won't look up the default bibliography.bib that I have set up in my init.
So if that citation is not in article1.bib, when hovering over it won't find it.
When I comment that line above, it works.

**Comment by jkitchin** [comment]
That is expected behavior. When you define a bibliography link it overrides the default settings. That is because when you export, LaTeX has no knowledge of the default settings in Emacs.  The citation should be red though, if it is not found in the bibliography a buffer is using.

**Comment by AtomicNess123** [comment]
Thanks. Regarding how to specify the bibliography, I found elsewhere to do it like this:
`#+bibbliography` instead of `bibliography:`

Do both work?

**Comment by jkitchin** [comment]
I don't think #+bibliography: is supported by org-ref. That is used in org-cite I think.
