### ISSUE TITLE
Is citeproc the default for pdf export?

### ISSUE THREAD

**Issue by wosined** [jkitchin/org-ref#1013]
When I export using the org-ref export menu the bibliography and bibliographystyle links are ignored. Only when I export using the latex export menu do I get the style to work. Is this how it should be?

**Comment by jkitchin** [comment]
org-ref has two styles of export. the regular LaTeX export is supported for  the bibliography and bibliographystyle links. The org-ref export options are for using citeproc instead.

**Comment by wosined** [comment]
Thanks. Clearly, I missed that part somewhere.
