### ISSUE TITLE
Symbol's function definition is void: org-pandoc-export-to-pdf

### ISSUE THREAD

**Issue by opensource-philosophy** [jkitchin/org-ref#1014]
Hello, there!

First of all: Thank you so much for writing and maintaining `org-ref`. I use it everyday and couldn't live without it anymore.

The problem I have is that exporting to `.docx` won't work. I get the error message
```
Symbol’s function definition is void: org-pandoc-export-to-docx
```
At first, I thought I had missed loading a library, but I wouldn't know which.  So I cloned your repo anew and ran 
```
find . -type f -exec grep -il "org-pandoc-export-to-docx" {} \;
```
in it. The output is:
```
./examples/basic-csl.org
./examples/bbl-super.org
./org-ref.org
./org-ref-export.el
```
Since the only `.el` file in which `org-pandoc-export-to-docx` exists is `org-ref-export.el`, I looked into it and only found one occurrence of it in line 468, within the function definition of `org-ref-export-to`. The function itself does not seem to be defined, though. Have you renamed the function, is something else going wrong, or is the error on my part?

**Comment by opensource-philosophy** [comment]
Can correct myself immediatley: `org-pandoc-export-to-docx` is a function defined by `ox-pandoc`, which is a package not required by `org-ref`. Adding 
```
(use-package ox-pandoc :ensure t)
```
made the function available to me.

**Comment by jkitchin** [comment]
I think the commit above adds this dependency.
