### ISSUE TITLE
Use emacs application framework pdf reader by default

### ISSUE THREAD

**Issue by bevsxyz** [jkitchin/org-ref#1015]
Hello,

I use [eaf-pdf-viewer](https://github.com/emacs-eaf/eaf-pdf-viewer) to read pdfs. 

When I call [this](https://github.com/jkitchin/org-ref/blob/2d91eba9274a79f908723a4a215e0f0b5c04ed01/org-ref-utils.el#L247) function to open pdfs at point, it opens with the default pdf reader of the system. I tried changing that to emacs, but it opens a new frame, which is not the behavior I am looking for. I would like it to just open a new buffer instead. Can we have that option?

**Comment by jkitchin** [comment]
You should be able to set `bibtex-completion-pdf-open-function ` to a function of your choice. You could use a function that takes a pdf filepath, and then calls eaf-pdf-viewer.

**Comment by bevsxyz** [comment]
I don't see where [org-ref-open-pdf-at-point](https://github.com/jkitchin/org-ref/blob/2d91eba9274a79f908723a4a215e0f0b5c04ed01/org-ref-utils.el#L247) calls `bibtex-completion-pdf-open-function`. In the two cases it simply is calling `org-open-file` to open the file.

I had used the emacs help for functions to check this, so I don't suppose it to be overwritten elsewhere.

**Comment by bevsxyz** [comment]
Perhaps you meant `org-ref-open-bibtex-pdf` for the BibTeX entries. It works as expected with the following function.

```elisp
(lambda (fpath)
    ('eaf-open fpath)
```

**Comment by jkitchin** [comment]
Fair point, I just pushed a replacement for that function so that your new function should also work.

I am skeptical of your lambda function above, I am pretty sure it should be
```
(lambda (fpath)
    (eaf-open fpath))
```

**Comment by bevsxyz** [comment]
Thanks for the quick fix. It works now. `eaf-open` as you mentioned is the right syntax I guess. Got an error with org-open-file, but not with `bibtex-completion-pdf-open-function` though. Will close this as the issue is solved.
