### ISSUE TITLE
automatically inserting bibliography-link

### ISSUE THREAD

**Issue by Perangelot** [jkitchin/org-ref#1019]
I have two questions concerning `org-ref-insert-bibliography-link`:

1. `org-ref-insert-bibliography-link` inserts `bibliography:path/to/bib-file.bib` at point. If the path contains spaces, though, the bibliography file is not recognized. Wrapping with the org-link syntax "[[...]]" would make it work. Is there any reason this function does not do it?
2. I'm working to make `org-ref` comptabile with `org-msg` such that citations are handled correctly. For that, a bibliography needs to be inserted automatically at the end of the mail (or reply, if there is any). For some reason,  though, running `org-ref-insert-bibliography` with `org-export-before-processing-hook` produces an error: `Wrong type argument: stringp, nil`. I explicitly made sure that the function containing `org-ref-insert-bibliography` evaluates to nil, though. Also, when the function is run, a buffer of the bibliography file I used to cite with is in my buffer list. This is the piece of code I am talking about:

``` emacs-lisp
(defun tlt-add-bibliography (_)
  "Add org-ref bibliography link to the end of the mail."
(goto-char (org-msg-end))
(previous-line)
(org-ref-insert-bibliography-link)
nil)

(add-hook 'org-export-before-processing-hook #'tlt-add-bibliography)
```
Any idea why this could be the case, or what you could do about it?

**Comment by jkitchin** [comment]
I use a function that looks like this to put a bibliography at the end. This will add an ascii bibliography and update the citation links I think. This goes in the `org-export-before-processing-hook`.

```
(lambda (_)
					     (goto-char (point-min))
					     (unless (re-search-forward "bibliography:" nil t)
					       (goto-char (point-max))
					       (insert (format
							"\nbibliography:%s"
							(if (stringp bibtex-completion-bibliography)
							    bibtex-completion-bibliography
							  (string-join
							   bibtex-completion-bibliography ",")))))
					     (org-ref-csl-preprocess-buffer 'ascii))
```

I pushed a commit to wrap the bibliography link in [[]]. I recall spaces are sometimes a problem for LaTeX though.

**Comment by Perangelot** [comment]
Thank you for the quick answer! Everything is working now. While we're at it, do you have a function which opens the bibliography file(s) used for a current `.org` file? I want to write a function which automatically deletes OCLC  and ISSN entries so that they won't appear in LaTeX citations.

**Comment by jkitchin** [comment]
Nothing that opens them, but org-ref-get-bibliography should get a list of the file names for the bib files, and then you can loop over those.

**Comment by Perangelot** [comment]
I assume you mean `org-ref-find-bibliography`? In any case, if I wrote that code, would you be interested in implementing it? I think a variable like `org-ref-remove-OCLC` which handles whether OCLCs should be removed from the bib file or not would fit your package.

**Comment by jkitchin** [comment]
That is probably the function, I wrote that from a phone. It sounds like an add bibtex entry hook function to me. If you write it like one of those functions I think it would be compatible with bibtex-map-entries and could be used one time on an existing file and in the hook for future entries. I probably would not enable it by default though. It seems like it should be up to the bst file to control what is shown.

**Comment by Perangelot** [comment]
``` elisp
(require 'bibtex)

  (defun orcb-remove-OCLC ()
    "Remove all OCLC entries in the annotation field of the current entry.
    If the only entry of that annotation field is the OCLC, remove the
    whole field."
    (let* ((annot (bibtex-autokey-get-field "annotation"))                 ; call the annotation field string "annots"
           (OCLC "\s?O?CLC:[^,}]+"))                                       ; and the OCLC string "OCLC" ("O?" if OCLC first item, see `looking-at')

      (when (string-match OCLC annot)                                      ; if an OCLC is in that annotation string                   
        (setq annot (replace-match "" nil nil annot)))                     ; remove it

      (when (string-match "^,\s?\\|\s?,$" annot)                           ; if there is a comma left at the beginning or end
        (setq annot (replace-match "" nil nil annot)))                     ; remove it, too

      (when (string-match ",," annot)                                      ; and if a comma occurs twice successively
        (setq annot (replace-match "," nil nil annot)))                    ; replace it by a single occurrence

      (bibtex-beginning-of-entry)                                          ; go to the beginning of the entry, e.g. "@book KEY"
      (goto-char (car (cdr (bibtex-search-forward-field "annotation" t)))) ; go right before the annotation field
      (if (looking-at (format "{[^}]%s\s*}" OCLC))                         ; if you're looking at just the OCLC in curly brackets
          (bibtex-kill-field)                                              ; remove the whole field
        (bibtex-kill-field)                                                ; else also remove the whole field
        (bibtex-make-field "annotation")                                   ; but in addition make a new annotation field,
        (backward-char)                                                    ; go inside of the curly brackets
        (insert annot))))                                                  ; and insert the new altered annotations    
                                       
  (add-hook 'org-ref-clean-bibtex-entry-hook #'orcb-remove-OCLC)
```
This should be it. The function is working, as can be seen if `org-ref-clean-bibtex-entry` is called on the `.bib` file. For some reason, though, it does not work when exporting; the OCLC is still shown in the bibliography entry. Anything I am doing wrong, a variable value I am missing?

**Comment by Perangelot** [comment]
> It seems like it should be up to the bst file to control what is shown

This is correct, but AFAIK, the annotation field is not suppressed by any style file. And Zotero exports OCLCs to the annotation field, so it might be of help to some people who use Zotero's `BetterBibTeX` add-on to toggle this functionality on.

**Comment by jkitchin** [comment]
I guess you still have to run it on all the entries to get rid of legacy fields, and probably you have to make sure to save the changes. Otherwise latex/bibtex will still see the old version on disk (which is different than the modified one in memory).

**Comment by Perangelot** [comment]
Just to get things right: 

1. `org-ref-clean-bibtex-entry` seems to operate on single entries, and the functions that have a hook in there, do that too, e.g. `orcb-clean-doi`. As it happens, my function is very similar to `orcb-clean-doi`.  The first works, mine does not. I cannot explain why.
2. So LaTeX does not read an altered bibtex buffer, but the *actual* bibtex-file, so the file itself must be changed and not just a copy for internal use? I tried `orcb-clean-doi` and the actual .bib file was not changed, although obviously, some bibtex file was altered.

**Comment by jkitchin** [comment]
Yes. That function only works on the entry at point. Usually it is run when you insert an entry, although you can run it manually on an entry too. If you write the function with the right signature you can use bibtex-map-entries on all the entries. It is not run during export. You need to make sure to save the bibtex file afterwards to write it to disk. I am traveling at the moment and can't check what might not be working in your code. 

2. Latex works independently of eMacs and org, so it reads the version on disk. That version can be different than what is in a buffer if you have unsaved modifications in a buffer.

**Comment by Perangelot** [comment]
Thank you for the hints! I have managed to get the code running, but it needs a lot more machinery to get running than I thought and does not seem to be too much org-ref-related to me anymore, so I merged it with the package I am working on: `https://github.com/opensource-philosophy/the-logicians-toolbox/blob/main/tlt-remove-OCLC.org`. Take the code you need, if any! Thanks again for your cooperation and the great package. This thread can be closed.
