### ISSUE TITLE
cite links

### ISSUE THREAD

**Issue by dlebrecht** [jkitchin/org-ref#102]
when i put the cursor on a cite link, i get:
Error running timer `org-ref-link-message': (wrong-type-argument stringp nil) [2 times]

when i try to follow(open) a cite link, i get:
org-ref-get-bibtex-key-and-file: Wrong type argument: stringp, nil

**Comment by jkitchin** [comment]
Can you provide a small example that illustrates this?

**Comment by jkitchin** [comment]
Also, please run the command M-x org-ref-debug and paste the contents in your comment.

**Comment by dlebrecht** [comment]
thanks for the prompt response. 

i had  
  (setq org-ref-default-bibliography "~/documents/thesis/doc/library.bib")

instead of
  (setq org-ref-default-bibliography '("~/document/thesis/doc/library.bib"))

either i modified that by mistake or that used to work for me last year
