### ISSUE TITLE
No PDF found

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#1020]
I am having a similar issue to [this](https://github.com/jkitchin/org-ref/issues/730).

I can't however find the variable `org-ref-get-pdf-filename-function`. 
It doesn't seem to exist in my code.
My packages are updated from MELPA.

**Comment by AtomicNess123** [comment]
Thanks. How would this knowledge make me fix the problem at hand?

**Comment by jkitchin** [comment]
see the help string for 

    C- h bibtex-completion-find-pdf

it looks for a file field, or a "key".pdf in some bibtex pdf directories. If your pdf isn't in one of those places, it isn't found. How do you save your PDFs?

**Comment by AtomicNess123** [comment]
Thanks! I have this setting in my init:

```
(setq bibtex-completion-bibliography
        (f-files "~/Dropbox/BibTex" (lambda (f) (f-ext? f "bib"))))
(setq bibtex-completion-library-path '("~/Dropbox/PDF"))
```

And no other bibtex pdf variable. Maybe that is what I am missing?

**Comment by AtomicNess123** [comment]
Ok, got it!

`(setq bibtex-completion-pdf-field "File") ; `

Because then it will look for the path in the File field.
Otherwise it expects the PDF filename to be the `key + .pdf`, which in my case isn't.
