### ISSUE TITLE
C-u to select citation command is not working with helm

### ISSUE THREAD

**Issue by dafxy** [jkitchin/org-ref#1027]
`C-u + <enter>`  on the helm org-ref buffer used to prompt the selection of citation type (cite, citep, citet, etc.). It is not working anymore. Was this feature removed? If so, any idea on how I can enable that again? It used to work either with a single or multiple citation selectoin.

org-ref-version: 3.0
emacs version: 28.1
System: Ubuntu

**Comment by jkitchin** [comment]
It is possible the feature was removed. The v3 code is simpler than the previous one, and only supports helm-bibtex I think. I think if you click on a link, you get a menu and "t" should allow you to change the type. if you do that a lot, you might consider changing the default type.

The previous version is at https://github.com/jkitchin/org-ref/blob/org-ref-2/org-ref-helm-cite.el#L295 which I think supported that option.

**Comment by dafxy** [comment]
C-u to select citation type works with ivy. I set 

```
(define-key ivy-minibuffer-map (kbd "C-<SPC>") 'ivy-mark)
```

I will use ivy instead of helm. That should do. Thanks for the quick reply.
