### ISSUE TITLE
addbibresource needs to go in preamble

### ISSUE THREAD

**Issue by brittAnderson** [jkitchin/org-ref#103]
When I use addbibresource: the \addbibresource{} ends up in the article body, but needs to be in the preamble (above the \begin{document}) line to work properly. The bibliography: link does work just fine though. 

If I export the org file to a latex buffer and manually move the addbibresource line to the preamble all, works fine, so I think the only thing that needs to be changed is to make sure that it gets exported to the preamble. 

Sorry I don't know enough to do it myself. 

Edit: Actually bibliography doesn't work either with biblatex for the same reason - needs to go in the preamble. I had a bbl file hanging around that "tricked" me into thinking it worked.

**Comment by jkitchin** [comment]
can you try:

#+latex_header: \addbibresource{your file}

and let me know if that works?

**Comment by brittAnderson** [comment]
When I add that line to the test.org file the C-c C-e l p (or o) fails with an error message about pdf citation. If I then don't do anything else, but open up the test.tex file produced by the export I can C-c C-c LaTeX and it will prompt for Biber and two more rounds of LaTeX and produce the correct output. So, the addbibresource is getting placed correctly in the header, but the exporter from org is not going through the right number of cycles to use the Biber back end? Maybe not an org-ref problem but an org-export problem?

----- Test Document Follows (test.org) ----- 

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+Title: This is a practice document
#+Author: Britt Anderson
#+SUBTITLE:
#+DATE: \today
#+LATEX_HEADER: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+Latex_header: \addbibresource{~/gitRepos/masterBib/bayatt.bib}



This is my test file for org-ref. Org-ref test 
cite:carrasco_attention_2004

I would now like to add another citation or two cite:jones2012global,gobell2005attention,heilman1993neglect,vossel2014spatial

citep:schneider2008attention


** This is a subsection.
   Let's make a label for this seciton. label:subsec

** Another subsection
   Another label label:subsec-2


** Another subsection, again
   Let's see if we can link to the earlier section ref:subsec



\printbibliography

**Comment by jkitchin** [comment]
you may need to specify how to run latex, e.g. https://github.com/jkitchin/jmax/blob/master/jmax-org.el#L334

that example is commented out but it gives you an idea of what to do.

**Comment by brittAnderson** [comment]
1. test org with:
#+LATEX_HEADER: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
[[addbibresource:~/test.bib]]

Fails, but 

 test.org with:
#+LATEX_HEADER: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+Latex_header: \addbibresource{~/test.bib}

Succeeds. So, things do work when addbibresource gets placed in the header (preamble).

2. Just in case anyone else ends up here via a search:
The export error was because the variable org-latex-to-pdf-process was changed to org-latex-pdf-process

**Comment by jkitchin** [comment]
Also, you probably want to set org-latex-pdf-process to:

`'("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
			      "biber %f"
			      "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
			      "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")`

**Comment by brittAnderson** [comment]
However, I don't think we actually fixed the issue. The problem is not my
pdf export command, it is the fact that the addbibresource link needs to
be formated to include "#+Latex_Header: " *and* moved up into the
preamble.

I tried to accomplish this myself by editing org-ref and recompiling
(and performing org-reload), but I couldn't figure out the right
elisp commands. The pseudocode would seem to be something like:
- save point
- move to top of buffer
- find last occurence of latex_header
- create new line below and move to it
- insert the formatted text for addbibresource there
- move point to saved location and ...

While I can manually add the addbibresource to preamble, the nice thing
about using the link is that I get to use a non-default bib file, and
get all the advantages of clicking which are lost with a manually typed
line in the latex_header.

If you want to give me hints for the elisp commands to do above, I can
take another stab at it. 

Thanks for all the work on org-ref, org-show, etc.

/Britt

**Comment by jkitchin** [comment]
Isn't it just that you need:

#+Latex_header: \addbibresource{~/Dropbox/bibliography/references.bib}

and everything works (except it is not a clickable link)?

**Comment by brittAnderson** [comment]
The main issue comes about when the bib is not the default. If you put
#+Latex_header: \addbibresource{~/Dropbox/bibliography/notdefault.bib}
in the org header than every invocation of C-c ] brings up the
default.bib not notdefault.bib, and that destroys the fluidity of using
org-ref. With many disjoint sets of collaborators one can't always
enforce a huge default bib on all co-authors. 

I can fiddle with the addbibresource function in org-ref.el and get it
to add "#+Latex_header: " as part of the format addbibresource function,
but it doesn't result in the output of "\addbibresource{~/notdefault.bib}"
in the preamble of the latex output. It shows up in the body, and then
biblatex can't find the resource for formatting.

The work around right now is to add both the +Latex_Header line and the
[[addbibresource:]] link (the latter gives you a bit of extra junk in
the output) for writing, so that the C-c ] commands work, and then for
the final output go in and manually delete the [[addbibresource]] link.
But it seems like if the format of the addbibresource link popped its
output into the preamble of the latex output all would be well, but
after a bunch of googling all my attempts to move point to the beginning
of the buffer and insert the formatted text failed to achieve that goal,
most likely because I don't really understand the generic org-export
process very well.

But, the work around isn't that big a deal, so maybe it isn't worth you
wasting any more of your time at this point. -- Thanks.

**Comment by jkitchin** [comment]
I think the addbibresource link won't work, or at least isn't worth the effort you describe. I just pushed a fix to recognize the bibfiles in \addbibresource. Now you just put the #+latex_header line in. It isn't currently clickable, but you can just put your cursor on the filename and C-x C-f will probably open it (if you have ffap loaded).

I think this should make this work they way you want.

**Comment by brittAnderson** [comment]
Works like a charm. Thank you very much. - Britt
