### ISSUE TITLE
Adding a cite eats up a space

### ISSUE THREAD

**Issue by ntrocado** [jkitchin/org-ref#1031]
In a buffer I have:

```
cite:&foo moretext
```

With the point on the cite link, `M-x org-ref-insert-link`, followed by selecting a reference from the minibuffer (I'm using Ivy), produces:

```
cite:&foo;&barmoretext
```

with the space before "moretext" gone. It would be nice to preserve the space.

**Comment by jkitchin** [comment]
I am unable to reproduce this. where exactly is the point?

**Comment by ntrocado** [comment]
Here's a screen grab:
![Recording 2022-09-05 at 19 41 57](https://user-images.githubusercontent.com/10780358/188501595-8b035f5a-c5eb-43ae-acda-3586d451c2a3.gif)
I hope it's clearer...
Emacs version is 28.1.
Org-ref version is 3.0.

**Comment by ntrocado** [comment]
Works great, thank you!
