### ISSUE TITLE
integrating notes with zotero

### ISSUE THREAD

**Issue by arnabkdey** [jkitchin/org-ref#1032]
Org-ref allows us to take notes for a citation in an org-file.  I have the following use-cases:

1. I want to be able to see those notes in Zotero so I can use the notes in other platforms like overleaf. 
2. When I create a notes file for a citation in Emacs, the org file that gets created already includes any notes that I had created in Zotero. 

So basically a bi-directional communication between Emacs and Zotero, specifically for annotations. 

Is it possible to configure org-ref in a way that allows us to achieve this?

**Comment by jkitchin** [comment]
I am not sure we can get org-ref to do this. It sounds like you want https://github.com/egh/zotxt-emacs.
