### ISSUE TITLE
doi-utils-add-bibtex-entry-from-doi returns mathml code in article titles

### ISSUE THREAD

**Issue by nujabse** [jkitchin/org-ref#1033]
Currently, for some articles, `doi-utils-add-bibtex-entry-from-doi` would transform subscipts and superscripts, such as those in chemical formulas, into long mathml codes. Taking [this doi link](https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.18.024064) for example, there are mathml codes in the generated bibtex entry like `<mml:math
                  xmlns:mml="http://www.w3.org/1998/Math/MathML"
                  Display="inline"
                  Overflow="scroll"><mml:msub><mml:mi>mn</mml:mi><mml:mn>3</mml:mn></mml:msub><mml:mi>sn</mml:mi></mml:math>`. Unfortunately, this makes citations using these bibtex entries pretty nasty. Can doi-utils automatically strip those mathml codes and turn them into normal chemical formulas in plain text?

**Comment by jkitchin** [comment]
With the commit above, you can add this to the clean entry hook:

    (add-to-list 'org-ref-clean-bibtex-entry-hook 'orcb-clean-<>-tags)

Then, I think it will strip those out. lightly tested on your example doi.

**Comment by nujabse** [comment]
I just tested the clean entry hook and it worked wonderfully. Thanks for your help!
