### ISSUE TITLE
Feature request: count how many different references

### ISSUE THREAD

**Issue by ntrocado** [jkitchin/org-ref#1034]
As far as I can gather there's no way of getting the number of different cited references in a file or buffer, neither in org or in org-ref.
This would certainly be useful though.
I skimmed over the internals, but couldn't see if the references are collected... I imagine this could be an easy function to implement if they are.
I also thought about approaching this from a regex writing perspective, but it's not trivial with all the possible cite types.

**Comment by jkitchin** [comment]
This is one way to do this:

```
(let* ((cites (org-element-map (org-element-parse-buffer) 'link
		(lambda (lnk)
		  (when (member (org-element-property :type lnk) (mapcar 'car org-ref-cite-types))
		    (cl-loop for ref in (plist-get (org-ref-parse-cite-path
						    (org-element-property :path lnk))
						   :references)
			     collect
			     (plist-get ref :key))))))
       (all-cites (-flatten cites))
       (uniq-cites (-uniq all-cites)))

  (cl-loop for cite in uniq-cites collect (cons cite (cl-count cite all-cites :test 'string=))))
```

**Comment by ntrocado** [comment]
Works perfectly (replacing the last `collect` with `count` directly gave the simpler result that I was looking for). Thank you!
