### ISSUE TITLE
Any workflow for managing paper notes ?

### ISSUE THREAD

**Issue by martinleduc** [jkitchin/org-ref#1036]
Hi,

After migrating to org-ref V3 a few months ago, I realized that the framework for keeping notes was changed, from "stacking every notes in one single org file", say biblio-notes.org, to the V3 system where every paper has its own org note file inside a /notes folder.

At this point I don't see much advantages of the new system since in the old one, I was able to easily:
1. Add Tags (and TODOS) to the papers, so I can filter them using org-agenda. This can be extremely useful, for instance when you tag papers by project.
2. Search for any strings within a single notes file.  

For point 1, the new system would require adding hundreds of note files to the "org-agenda-files" variable. For point 2, we can use grep-find or similar tools to search within the /notes directory.

I would be interested to better understand the philosophy behind the new approach, and if there any known workflow to easily managing/organizing notes, and do simple actions such as searching notes by tags and content ?

Many thanks,
Martin

**Comment by jkitchin** [comment]
if that has changed, it is probably in the way that bibtex-completion does notes. You can set that up for single or multiple files that should be consistent with your old flow. This used to be done by org-ref, but now it uses the external capability, which may have a different default. I don't think I changed this intentionally.

maybe this: https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L132
and
https://github.com/tmalsburg/helm-bibtex/blob/master/bibtex-completion.el#L155

are places to check?

**Comment by martinleduc** [comment]
Looks like changing bibtex-completion-notes-path to a file name rather than a folder will can do the job. Thanks !
