### ISSUE TITLE
font and line space of bibliography in html export

### ISSUE THREAD

**Issue by xin-jin** [jkitchin/org-ref#104]
Hi,

I somehow get it to work for html export. But the caption "bibliography" is too large and the space between the caption and the entries is pretty wide. Is there any way to modify them?

![selection_002](https://cloud.githubusercontent.com/assets/6195346/12131306/3a046a82-b3c6-11e5-8107-73813c5f4c00.png)

**Comment by jkitchin** [comment]
the Bibliography is large because it is set as an <h1> here https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L809

I am not too skilled at html stuff, I guess a better way would be something that can be modified by css?

**Comment by xin-jin** [comment]
Thanks! I think you are right, though I am not familiar with html either :(

**Comment by xin-jin** [comment]
I know little about html/css, but I read the source of the exported html. It seems that the problem is "bibliography" has tag `h1` which is for the title. I guess `h2` is probably more appropriate? Or make that an option?

**Comment by jkitchin** [comment]
I think you can do this yourself already in your org file like this.
#+HTML_HEAD_EXTRA: <style> h1.org-ref-bib-h1 {color:red}; font-size:medium</style>

this will change the bibliography to red, and medium font-size.
