### ISSUE TITLE
Suggestion: automatically edit ref: when changing label:

### ISSUE THREAD

**Issue by drghirlanda** [jkitchin/org-ref#1040]
LyX allows users to change a label and it automatically updates all ref links to that label. I find this very useful as I often start with labels that I later regret. Would this be hard to add to org-ref?

**Comment by jkitchin** [comment]
This would be very difficult to implement. you can instead change the label, and the find and replace all ref:label in your document.

**Comment by drghirlanda** [comment]
Got it, thanks for considering! I thought it wouldn't be that hard given org and Emacs's navigation / text-matching abilities, but I don't know much of what on under the hood...

**Comment by jkitchin** [comment]
I guess if what you had in mind is something like M-x org-ref-rename-label, and then it would prompt you for a new name, and update all refs to the old name, that is pretty easy. If what you meant is you just modify a label by deleting and retyping, with real-time updates that is extremely difficult.

**Comment by drghirlanda** [comment]
Got it! I thought that with other things having as-you-type updates,
like syntax highlighting, this should be similar. but again, I
understand very little of the internals.

On Sat, Oct 15, 2022 at 9:20 AM John Kitchin ***@***.***> wrote:
>
> I guess if what you had in mind is something like M-x org-ref-rename-label, and then it would prompt you for a new name, and update all refs to the old name, that is pretty easy. If what you meant is you just modify a label by deleting and retyping, with real-time updates that is extremely difficult.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>



-- 
Stefano Ghirlanda - www.intercult.su.se/~stefano - drghirlanda.com
Full Professor of Psychology, Biology, and Anthropology, Brooklyn College
Guest Professor, Stockholm University Centre for the Study of Cultural Evolution
