### ISSUE TITLE
bibtex-completion-display-formats 

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1043]
Is it possible to include the bib-file name in the display format? Use case: having the same citation in two different files (say one with special formatting to highlight grad students) it is difficult to decide which is which.

**Comment by jkitchin** [comment]
The candidates come from `bibtex-completion-candidates`. You can modify how they appear like this I think. This looks up the file a key is in (technically, it might just show the first one I suppose. I think if you want the real files, you probably have to advise bibtex-completion to store that in the entry a-list when it parses the files). 

```
#+BEGIN_SRC emacs-lisp
(defun find-bibfile (entry-key)
  (cl-loop for bf in (bibtex-completion-normalize-bibliography 'bibtex)
	   if (with-temp-buffer
		(insert-file-contents bf)
		(goto-char (point-min))
		(re-search-forward (concat "^[ \t]*@\\(" parsebib--bibtex-identifier
					   "\\)[[:space:]]*[\(\{][[:space:]]*"
					   (regexp-quote entry-key) "[[:space:]]*,")
				   nil t))
	   return bf))



(defun my-entry (candidate)
  (let* ((idx (get-text-property 1 'idx candidate))
	 (entry (cdr (nth idx (ivy-state-collection ivy-last)))))
    (concat (find-bibfile (cdr (assoc "=key=" entry))) " " (bibtex-completion-format-entry entry nil))))


(ivy-configure 'org-ref-cite-insert-ivy :display-transformer-fn #'my-entry)
#+END_SRC
```

Maybe an alternative is to construct candidates from `bibtex-completion-cache` which lists entries by file. maybe something like:

```
(ivy-read
 "Cite: "
 (cl-loop for collection in bibtex-completion-cache
	  append
	  (cl-loop for entry in (nthcdr 2 collection)
		   collect
		   (cons
		    (concat (car collection) " " (bibtex-completion-format-entry entry nil))
		    (cdr (assoc "=key=" entry)))))
 :action (lambda (candidate)
	   (insert (format "cite:&%s" (cdr candidate)))))
```

It seems like it would be wiser though to specify what files they come from than to have duplicate keys. I am not sure how well that will work.

**Comment by uliw** [comment]
I tried to adapt this to use it with org-ref-helm, but failed. Would you know how to integrate this?

**Comment by jkitchin** [comment]
I have not used helm in a while. It still gets candidates from `bibtex-completion-candidates`. It is probably doable, eg if you advised that function so that it does something like i did above. That is only partially right though. I don't see an easy way to inject the bibfile name while parsing it in bibtex completion without a lot of advising, or direct modification of the source. you might be better off writing your own insert function that builds candidates for you.

I think the easiest way is to specify the bibfiles.

**Comment by uliw** [comment]
I see, I'll modify the bibtex key in the other file so that I can see where the citation comes from.
