### ISSUE TITLE
Symbol's Function Definition is void: nil for org-ref-insert-link

### ISSUE THREAD

**Issue by ryuiro-kitsune** [jkitchin/org-ref#1044]
Every time I call `org-ref-insert-link` I get the error `funcall: Symbol’s function definition is void: nil`

This is my config section for org-ref
```elisp
;;; Org-ref
(use-package org-ref
  :straight t
  ;; Config
  :init
  (use-package helm-bibtex)
  (require 'org-ref-refproc)
  :config
  (setq bibtex-completion-bibliography '(("~/org/bib/"))
	bibtex-completion-library-path '("~/Documents/pdfs/"))
  (require 'bibtex)
   :bind (:map org-mode-map
	      ("C-c ]" . org-ref-insert-link)))
```

**Comment by jkitchin** [comment]
I guess you have not defined a value for `org-ref-insert-cite-function`. I guess you should also add `(require 'org-ref-helm)` which should do that.

**Comment by ryuiro-kitsune** [comment]
Success! Thank you for your help.
