### ISSUE TITLE
Multiple selection with helm-bibtex does not seem to work

### ISSUE THREAD

**Issue by giveitacatch** [jkitchin/org-ref#1045]
Hi, I have been using `org-ref` and `helm-bibtex` for a while. Everything works perfectly. Calling `helm-bibtex` in emacs bring me the helm menu and all the references in my `bib` file show up. I can search and navigate. Upon pressing `RET` the citation is inserted in my org file. However, selecting multiple entries does not seem to work. I have the impression that it used to work for me but cannot be 100% sure.

### Steps to reproduce:
1. call `helm-bibtex` in emacs
2. in the helm menu, `C-SPC` or `C-@` and observe that an asterisk mark `*` in front of the entry
3. Repeat the step 2. and have multiple references selected
4. Press `RET` and observe that only one citation is inserted, which is the one where my cursor was last

### What I expected:
Multiple citations inserted with one `RET` press.

### What is the current behavior:
It seems like `RET` does not respect the multiple selection/mark in helm at all. It is as if I have not marked anything at all.

### Versions
`org-ref-version`: Version 3.0
`emacs-version`: 27.2
`helm-bibtex`: 2.0.1 (found in `helm-bibtex.el`)

**Comment by jkitchin** [comment]
I am not able to reproduce this.  Something doesn't sound right. `helm-bibtex` isn't actually used by org-ref (although it looks like it).  The `org-ref-cite-insert-helm` should be used for inserting citations, and for me it does insert multiple citations. Usually I bind that command to `C-c ]`.

helm-bibtex doesn't have insert citations as the default action for me. Instead, insert citations is the 3rd action, and it also inserts multiple ebib links for me.

**Comment by giveitacatch** [comment]
Hi John, thanks a lot for the quick response.

It turns out that I had this configuration:
```elisp
 (helm-delete-action-from-source "Insert citation" helm-source-bibtex)
 (helm-add-action-to-source "Insert Citation"  
              'org-ref-insert-cite-key helm-source-bibtex 0)
```
as a workaround to the exact issue that insert citation not being the default action. Please do not ask why I use `org-ref-insert-cite-key` there. Changing this to `org-ref-helm-bibtex-insert-citation` make `helm-bibtex` work properly and insert multiple org-ref citation as expected:
```diff
- 'org-ref-insert-cite-key helm-source-bibtex 0)
+ 'org-ref-helm-bibtex-insert-citation helm-source-bibtex 0)
```

I also do not know why I use `helm-bibtext` in the first place. I think I should have used `org-ref-cite-insert-helm`.

Thanks again. I truly appreciate what you have done with `org-ref`. I use it everyday.

I am closing this.
