### ISSUE TITLE
Config to enable openalex?

### ISSUE THREAD

**Issue by rmosvold** [jkitchin/org-ref#1057]
Hi! I was excited to try the new openalex-functionality that I saw in the youtube-video. I have downloaded the latest version of org-ref, but the openalex-options don't show up in the menu. Anything that needs to be configured, or any prerequisites that are needed? (I have tried this on multiple computers with Linux, Mac and Windows)

**Comment by jkitchin** [comment]
You probably just need to run M-x load-library openalex to try it temporarily.

add this in an init file `(require 'openalex)` to make it permanent

**Comment by rmosvold** [comment]
Thanks a lot, that worked! 
And thanks a lot for all the wonderful work you are doing with org-ref! This way of getting search results directly into Emacs as an org-mode file, with key information as property values, is great :-)
