### ISSUE TITLE
bibliographystyle not working correctly

### ISSUE THREAD

**Issue by bill3000** [jkitchin/org-ref#1059]
Bibliographystyle links are not working for me - even when a valid .bst style is input, the name is displayed in red (i.e., invalid fontification). The `org-ref-bst-styles` variable does not contain any values, despite having numerous bst files installed. When I export an org-file to PDF via org-ref export, the specified bibliographystyle is ignored, and references are displayed in (I believe) Chicago style, which is the default CSL style. I am running Emacs 28.2 on Windows 10, so perhaps it is an issue with org-ref being unable to locate the bst directories?

**Comment by jkitchin** [comment]
org-ref uses `kpsewhich -expand-path '$BSTINPUTS'` to find the styles. If that doesn't work on your computer, then the links will show in red. That should not matter for the export to latex though. You should verify that when you export to latex that the style you indicated is used in the tex file.

CSL is a separate system than latex; the bibliographystyle link is not used for that. Instead you need a #+csl-sytle line to specify which one to use. It is possible to use CSL to export to latex, but it doesn't make a lot of sense to do that; the latex bibliography tools are better IMO.

**Comment by bill3000** [comment]
Thanks for the quick reply. Strangely enough, the bibliography and citations seem to be (more or less) formatted correctly when using the default org LaTeX export command (Export to LaTeX -> as PDF file), but not when I export directly through org-ref (Org-ref export -> to PDF) - which is what I was doing previously. The latter still formats the bibliography in the mystery style I mentioned, regardless of the `bibliographystyle` specified (yes, the `bibliographystyle` is used in the generated TeX file). 

I think this is because org LaTeX export will include a `\bibliography{}` command, whereas org-ref export will not (instead using static `\hypertarget{}` commands). Is this intended behaviour?

**Comment by jkitchin** [comment]
The bibliographystyle link is only for latex export, it is ignored for any CSL export. If you want a PDF, you should use the default org latex->pdf commands. The org-ref to pdf goes through CSL so you have to setup the CSL style you want independent of the bibliography style used for latex. 

see https://github.com/jkitchin/org-ref/blob/master/examples/basic.org for the latex to pdf route

and https://github.com/jkitchin/org-ref/blob/master/examples/basic-csl.org for the org -> csl -> pdf route.

**Comment by bill3000** [comment]
Ah, that makes a lot of sense. Thanks for your help.
