### ISSUE TITLE
bibliography exporting problems

### ISSUE THREAD

**Issue by AdelleBernal** [jkitchin/org-ref#1063]
I'm new to org-ref and Emacs, and I found your package very useful as a researcher.
I am using a basic setup a the end of the org buffer:

```
[[bibliographystyle:ama]]
[[bibliography:/Users/adeller/Desktop/@article243.bib]]

```
I have been trying different exporting possibilities (`C-c C-e`).
I noticed that the bibliography does not get exported/formatted when exporting to ODT or via pandoc.
When I use orf-ref export, some of the items have `NOITEMDATA:citationkey` althought they are correctly included in the bibtex file.

Why is this happening?

**Comment by jkitchin** [comment]
There are two export mechanisms in org-ref. Org-ref natively supports latex export. For other backends, e.g. odt, you have to go through the CSL export with C-c C-e r which has these options:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1610070/222986176-17b362c2-6143-449f-a6c8-1b1897e4526b.png">

For more fine-tuned options see https://github.com/jkitchin/org-ref/blob/master/examples/basic-csl.org.

**Comment by AdelleBernal** [comment]
Thanks, this means that to export correctly I should only use the Org-ref export  `C-c C-e r `or the Latex export `C-c C-e l`, if I got it correctly.

When using Latex, all is good.
When using ODT (`C-c- C-e r o`) there are some `NO_ITEM_DATA:author2021` problems for some bibliography items which seem to be in order.

**Comment by jkitchin** [comment]
You should try the org-ref examples. they seem to work fine for me. if they do, it would indicate something is not completely in order.
