### ISSUE TITLE
org-ref-insert-link vs org-ref-insert-cite-link

### ISSUE THREAD

**Issue by AdelleBernal** [jkitchin/org-ref#1066]
What is the difference between these too?
On my end both comply the same purpose.

**Comment by jkitchin** [comment]
`org-ref-insert-link` is a generic function that has more functionality than `org-ref-insert-cite-link` when you use prefix args. It is also independent of the "backend" you choose, e.g. ivy or helm. It uses funcall on variables that point to the functions you want to use. So, for you, they should appear to do the same thing.
