### ISSUE TITLE
export markdown error when use citations in org-transclusion

### ISSUE THREAD

**Issue by nigo81** [jkitchin/org-ref#1077]
org-translusion can not be modified after embedding, if the embedded text uses the cite reference in org-ref, when exporting markdown will report an error org-ref-process-buffer: Text is read-only, how should this be solved, can export markdown and show the reference Bibliography.

![image](https://user-images.githubusercontent.com/38601513/236689954-068c1d1a-018b-440e-a7c9-c16db03d55e2.png)

In org-roam file, i use org-transclusion to embed some text which contains citations. `C-c C-e r m` to export markdown error.
the log is `org-ref-process-buffer: Text is read-only`

In the org file which is embeded preview, I press  `C-c C-e r m` to export markdown correctly:
![image](https://user-images.githubusercontent.com/38601513/236690157-03f61bca-a3f6-4454-ba96-5b664c069a68.png)

Is any method to solve it? 
Thanks very much.

**Comment by jkitchin** [comment]
you should probably try to make the buffer not read-only at least temporarily. I don't know the best place to do that. You could advise some function, eg org-ref-process-buffer to make the buffer editable before running, and read-only after perhaps.

It might also be possible to do something in one of the hooks like `org-export-before-processing-functions` where you put a function in that makes the buffer not read-only.

**Comment by nigo81** [comment]
> you should probably try to make the buffer not read-only at least temporarily. I don't know the best place to do that. You could advise some function, eg org-ref-process-buffer to make the buffer editable before running, and read-only after perhaps.
> 
> It might also be possible to do something in one of the hooks like `org-export-before-processing-functions` where you put a function in that makes the buffer not read-only.

OK, I will try to solve it ,thanks a lot.

**Comment by nigo81** [comment]
https://github.com/nobiot/org-transclusion/issues/86#issuecomment-872323901

I found the solution from above issue,thanks again for your tips.
