### ISSUE TITLE
org-ref hangs when I am actively adding new citations

### ISSUE THREAD

**Issue by japhir** [jkitchin/org-ref#1078]
Hi John! :)

When I have my emacs daemon open side-by-side with a firefox tab where I'm adding references using the Zetero web plugin, this changes my .bib file quickly and many times (using the Better Bibtex plugin and Zotfile for PDF location).

This results in org-ref `Parsing bibliography file ~/SurfDrive/bibliography/references.bib ...` many many times, which hangs emacs entirely, making it impossible to type out notes as I'm going. This is very frustrating. Is there any way that parsing the bibliography can be postponed/disabled for a while, or have it happen in the background without blocking my entire emacs session?

Kind regards

**Comment by jkitchin** [comment]
I am pretty sure this happens in bibtex-completion. I don't see an easy way to prevent it at the moment. It is an annoying balance of keeping things up to date with performance.

I am surprised it is an issue though, I also do this quite often, and have a quite large set of bibtex files.

How large are yours?

**Comment by japhir** [comment]
I have one giant bib file that's generated from Zotero (via the better-bibtex plugin) with 24892 lines 😮 . Perhaps I should start splitting it per folder in Zotero in stead. I use the Zotero connector app to add them, which may trigger two versions because of better-bibtex which changes keys etc. So while browsing e.g. google scholar with an emacsclient next to it, it will hang on every paper that I add for about 10 seconds, which is very annoying.

I'll try splitting up my bibfile to see if that helps.

**Comment by jkitchin** [comment]
That sounds weird, my main bibfile has 31K+ lines in it. If you are just adding entries, I don't think org-ref is causing it to hang; that should only happen when you go to insert a new citation via org-ref. Do you have some kind of file watch setup that updates bibtex-completion?

**Comment by japhir** [comment]
This happens far less since I've disabled [my save-extremely-often snippet](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#auto-save)

However, it still happened and made my full session hang, so I hunted it down to this section of [my config](https://raw.githubusercontent.com/japhir/ArchConfigs/master/myinit.org):

After disabling it I no longer experience the issue I think.

```org
*** COMMENT bibtex/ivy-bibtex
reference manager I use it in conjunction with zotero, which generates the
.bib files, and org-ref, to insert citations in org files.

#+begin_src emacs-lisp
  (use-package ivy-bibtex
    :after ivy
    :init
    (setq bibtex-completion-bibliography
          '("~/SurfDrive/bibliography/references.bib"
            "~/Documents/References/PhD.bib")
          bibtex-completion-library-path '("~/SurfDrive/bibliography/")
          bibtex-completion-notes-path "~/SurfDrive/bibliography/notes/"
          bibtex-completion-notes-template-multiple-files "* ${author-or-editor}, ${title}, ${journal}, (${year}) :${=type=}: \n\nSee [[cite:&${=key=}]]\n"

          bibtex-completion-additional-search-fields '(keywords)
          bibtex-completion-display-formats
          '((article       . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${journal:40}")
            (inbook        . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
            (incollection  . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
            (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
            (t             . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*}"))
          bibtex-completion-pdf-open-function
          (lambda (fpath)
            (call-process "open" nil 0 nil fpath))))
#+end_src
```

**Comment by jkitchin** [comment]
hm. that makes it seem like it is surely ivy-bibtex choking on a big bibtex file.

**Comment by japhir** [comment]
Maybe it's because I use Zotero with better-bibtex, which changes the bibfile automatically every now and then? But I'm not sure, since the trigger also happend when I wasn't changing anything in Zotero. To test this I guess I could re-enable that piece of code, then turn off Zotero so I'm sure it's not synching in the background and see if the hanging still occurs...

**Comment by jkitchin** [comment]
you should probably raise this with @tmalsburg at https://github.com/tmalsburg/helm-bibtex/issues. This is happening in the ivy-bibtex code.

**Comment by tmalsburg** [comment]
To disable automatic reloading: https://github.com/tmalsburg/helm-bibtex?tab=readme-ov-file#prevent-automatic-reloading-of-bibliography-when-it-was-changed

**Comment by japhir** [comment]
I've recently switched to using thew whole vertico, marginalia, orderless, consult, embark shebang. @tmalsburg Does `bibtex-completion` also support the default emacs completion framework or was it written with helm and ivy in mind?

**Comment by tmalsburg** [comment]
bibtex-completion was factored out from helm-bibtex to allow easy integration with other front-ends.  Should be relatively easy to make it work with the packages that you mention.  Chances are that someone has already done that.  Personally, I only use helm and focus on that.  But I would consider including code for other frameworks.

**Comment by jkitchin** [comment]
bibtex-completion should be compatible with the default completion framework; it uses completing-read and has not code for ivy/helm in it.

org-ref is also compatible with default completing-read in many places, e.g. `org-ref-read-key` uses completing-read. Only the code in `org-ref-ivy` is ivy specific. I guess you can mimic that functionality with that stack, I think it is embark that you use to provide all the extra functionality that ivy provides.
