### ISSUE TITLE
Glossary example

### ISSUE THREAD

**Issue by thaaophz** [jkitchin/org-ref#108]
Hi John,

thanks for org-ref, it's amazing!

I have one question according to the glossary function:
Can you provide a small example how to use this in orgmode?
I'm don't get it to work with just the instructions in the [manual](https://github.com/jkitchin/org-ref/blob/master/org-ref.org).

**Comment by jkitchin** [comment]
Thanks!

I added a little example to the manual. It turns out the newglossaryentry things need to be in the preamble, so the links do not work. I took them out and updated the manual.

`#+latex_header: \usepackage{glossaries}
#+latex_header: \makeglossaries

#+latex_header: \newglossaryentry{computer}{name=computer,description={A machine}}


A gls:computer is good for computing. Gls:computer is capitalized. We can also use a bunch of glspl:computer to make a cluster. Glspl:computer are the wave of the future.

\printglossaries`

**Comment by thaaophz** [comment]
Thanks, works like a charm!

**Comment by thaaophz** [comment]
Wow, thanks for the new stuff. Org-ref is fantastic!!!

**Comment by thaaophz** [comment]
According to e070d43f81820a9048654d098d52bd5a771c8d23 it would be realy nice to have the options `\ac` and `\acs`, too.
`\ac` generate either the “full form” of the acronym when it’s the first time the term is used, or the “short form” when the term and acronym have already been introduced.

**Comment by jkitchin** [comment]
\acs seems to just be a short version of acrshort, and \ac a "short" version of \gls. Is that right?

 do you think it would be better to just use the short versions instead?

**Comment by thaaophz** [comment]
Sorry, you are right. `\acs` ist the short version for `\acrshort`and `\ac` does the same than `\gls`.

But if I do something like:
`#+latex_header: \newacronym{snr}{SNR}{Signal to Noise Ratio}`

and than `org-ref-insert-glossary-link` there is no option to choose `\gls`, just `acrshort`, `acrlong` and `acrfull`.
Maybe its possible to add `ac` (and `acp` for plural)

**Comment by jkitchin** [comment]
I put an option for gls in the acronym menu. I don't think it makes sense to add shortcut commands if you are already using the menu command to insert them. I am not too familiar with this LaTeX package. Does it make sense to separate glossary and acronym entries? should they all have the same link options?

**Comment by thaaophz** [comment]
Thanks for your work.
I read more about glossarys and acronyms [here](https://tex.stackexchange.com/questions/8946/how-to-combine-acronym-and-glossary).

There is a nice workflow, described by `Coxa` which works great in org-ref, too.

#+latex_header: \newglossaryentry{api}{
#+latex_header:                       name={API}, 
#+latex_header:                       description={An Application Programming Interface (API) is a particular set of rules and specifications that a software program can follow to access and make use of the services and resources provided by another particular software program that implements that API},
#+latex_header:                       first={Application Programming Interface (API)},
#+latex_header:                       long={Application Programming Interface}}

and than:
First time: [[Gls:api][API]] secound time: [[Gls:api][API]]
Which results in:
First time: Application Programming Interface (API) secound time: API 


Thanks you very much!

**Comment by mcraveiro** [comment]
Thanks very much for org-ref. Leaving a comment here for anyone who may be trying to use glossaries with possessives, /e.g./ ```TLA's```. My solution is:

```
ac:tla['s]
```
It was taken from this SO question [1].

[1] [Acronym package: Handling possessive case (apostrophe s)](https://tex.stackexchange.com/questions/416466/acronym-package-handling-possessive-case-apostrophe-s)
