### ISSUE TITLE
doi-utils-get-json-metadata should properly decode the data retrieved

### ISSUE THREAD

**Issue by piater** [jkitchin/org-ref#1082]
`doi-utils-get-json-metadata` contains the following code:
```
      (with-current-buffer
          (url-retrieve-synchronously
           ;; (concat "http://dx.doi.org/" doi)
	   url)
	(setq json-data (buffer-substring url-http-end-of-headers (point-max)))
```
For me, these cause two problems:
- `url-retrieve-synchronously` does not decode the buffer but returns the raw bytes. This can cause the retrieved json data to contain garbage.
- The current buffer is used for retrieval. In some use cases, this requires setting up a dedicated buffer beforehand. I suggest making this function robust and self-contained by using its own temp buffer.

Thus, I suggest replacing the above code by the below:
```
      (with-temp-buffer
        (url-insert-buffer-contents (url-retrieve-synchronously url) url)
	(setq json-data (buffer-string))
```
This works for me but I cannot be 100% sure that the current→temp change does not break something somewhere...

**Comment by piater** [comment]
Perhaps so. This is the only place it bit me. As long as you only extract ASCII material it should not matter. I also use your simple pattern in other places, without problems.

Actually, `url-insert` is sufficient (the extra power of `url-insert-buffer-contents` should not be needed) and does not require its own `url` argument.

**Comment by jkitchin** [comment]
any chance you have a doi where the current method fails?

**Comment by jkitchin** [comment]
I think the commit above should resolve this.
