### ISSUE TITLE
Missing require in doi-utils.el

### ISSUE THREAD

**Issue by DavidRConnell** [jkitchin/org-ref#1084]
Hi, I started getting the `Symbol's function definition is void: url-insert` error when using `doi-utils-bibtex-entry-from-doi` and I can reproduce this error using `emacs -q --eval="(require 'org-ref)"`.

The `url-insert` function is in the `url-handlers`package which, is not explicitly required by `doi-utils`. I belive bcd59dc introduced the dependency on this function.

## Solution
Adding a `(require 'url-insert)` to `doi-utils` should fix the problem.

**Comment by jkitchin** [comment]
weird. I wonder why this works fine for me. I can't find anywhere that library is required, I guess something else does it somewhere? I have added it in the commit above. Hopefully that fixes it for you.

**Comment by DavidRConnell** [comment]
Thanks (and for catching the mistake in my require). That is weird. I can consistently reproduce the problem on emacs 29.1. I assumed it wasn't an emacs version issue since I looked at the [url changelog](https://github.com/emacs-mirror/emacs/blob/master/lisp/url/ChangeLog.1) and it hasn't been modified anytime recently. So all I can think of is what you said, maybe another built in file required it and no longer does or something like that
