### ISSUE TITLE
Unable to byte-compile openalex.el

### ISSUE THREAD

**Issue by csantosb** [jkitchin/org-ref#1085]
Using emacs 29.1. After cloning the repository, and using `B` with dired (`dired-do-byte-compile`) with the point on `openalex.el` I get the following error message

    Debugger entered--Lisp error: (error "Key sequence a r starts with non-prefix key a")

This is annoying because in disables byte compilation of the remaining files when installing with melpa, for example.

**Comment by jkitchin** [comment]
This is surely caused by this line: https://github.com/jkitchin/org-ref/blob/master/openalex.el#L345

I don't know what can be done about it though.

If you don't use this library, I suggest either deleting the openalex.el file, or comment out those lines.

**Comment by csantosb** [comment]
Problem is fixed now.
