### ISSUE TITLE
Org-ref export to odt and docx fails

### ISSUE THREAD

**Issue by WouterSpekkink** [jkitchin/org-ref#1089]
I am trying to export an org file with org-ref styled citations to a docx or odt file, ideally with the citations formatted.

If I use org-ref-export with either of these formats, I get the error: wrong-number-of-arguments (0 . 0) 10

Maybe my settings are incorrect? I don't really know where to start looking. I am linking [my config file](https://github.com/WouterSpekkink/dotfiles/blob/master/emacs/init.el) just in case.

Exporting to PDF works fine.

I added the debugger report below.

Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 10)
  org-export-copy-buffer(:to-buffer nil :drop-visibility nil :drop-narrowing nil :drop-contents nil :drop-locals nil)
  org-ref-export-to(docx nil nil nil nil nil)
  org-ref-export-to-docx(nil nil nil nil)
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)

**Comment by jkitchin** [comment]
could you post a minimum working example of your document that shows the error?

**Comment by WouterSpekkink** [comment]
Okay, I feel kinda stupid now, but when I tried to make a minimum working example, I found that the export started working, also with the document where it originally didn't. I have no clue what changed in the meantime, but I guess I can close the issue. Apologies!
