### ISSUE TITLE
Feature request: control of location of added citations to existing cite: based on location of point

### ISSUE THREAD

**Issue by spencerahill** [jkitchin/org-ref#109]
Often, I need to add a citation to an existing `cite:` block.  For example, I have `cite:ref1` in the buffer, and I need to subsequently add `ref2` to the same `cite:`.  As far as I can tell, this always adds the new citation to the end of the list of existing ones, so that the result is `cite:ref1,ref2`.  It would be nice if org-ref enabled placing the new citation at the beginning of the existing `cite:` list if point is located before the existing citation(s).  E.g. in this example if point was located just after the colon of the existing `cite:ref1`, then the output after selecting `ref2` would be `cite:ref2,ref1`.

Would this be feasible?  Thanks!

(My real world use-case is that I generally want to order my citations within a single `cite:` chronologically by publication date.)

**Comment by jkitchin** [comment]
you might like (org-ref-sort-citation-link) then ;) it sorts the cites at point by year.

Also, shift-left or shift-right will reorder the citation at point.

I just pushed a change that does what you want. if you are on the cite part, the : or the first character of the cites now they get inserted at the front, and if you are in the middle cites get inserted after the next comma, and at the end they are appended.

**Comment by spencerahill** [comment]
I hadn't caught either of `org-ref-sort-citation-link` or shift-left/right, which are great.  And your addition is even better!  Thanks a lot, I really appreciate such a fast feature add.  org-ref is great.

**Comment by jkitchin** [comment]
No problem. I liked your idea! Thanks for sharing it.
