### ISSUE TITLE
add journal abbreviations from file

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1096]
I can add new journal abbrevs via
```
(add-to-list 'org-ref-bibtex-journal-abbreviations '("EPSL" "Earth and Planetary Science Letters" "Earth Planet. Sci. Lett."))
```
but this clutters the startup file. How would I read these definitions from a file?

**Comment by jkitchin** [comment]
You can just put them in an elisp file, and either use `load-file`, or if you make it like a library, and it is in your load-path, simply require it. If you call your file myabbrevs.el and it has these contents, and it is on your load-path,

```
;;; myabbrevs.el --- my abbreviations

;;; Commentary:
;; 

(add-to-list 'org-ref-bibtex-journal-abbreviations
	     '("EPSL" "Earth and Planetary Science Letters" "Earth Planet. Sci. Lett."))

(provide 'myabbrevs)

;;; myabbrevs.el ends here
```

then `(require 'myabbrevs)`  or `(load-file "path/to/myabbrevs.el")`

should do it.
