### ISSUE TITLE
A typo in org-ref-citation-links

### ISSUE THREAD

**Issue by 101scholar** [jkitchin/org-ref#1100]
I think it should be `let*` instead of `let` because function `bibtex-completion-find-pdf` will use variable `bibtex-completion-bibliograph`. Otherwise, if org-ref uses a different bib file from bibTeX-completion, a warning of "Bibtex-completion couldn't find entry with key" will occur.

https://github.com/jkitchin/org-ref/blob/195b8d3209aff956ecdd755422700e8517a34d11/org-ref-citation-links.el#L595

**Comment by jkitchin** [comment]
I think you are right. I pushed a fix for this.
