### ISSUE TITLE
citet: produces duplicate author name

### ISSUE THREAD

**Issue by digikar99** [jkitchin/org-ref#1103]
I expect `some text citet:&test_org_ref more text` to be producing a non-parenthetical `some text [non-paren citation] more text`. However, I get the output as `some text author [non-paren citation] more text`. Is this intended? Is there an alternative to prevent duplicate authorname?

For example, the org file below:

```
#+title: Testing org ref

[[citet:&test_org_ref]] wrote the paper in 2023.

bibliographystyle:unsrtnat

bibliography:tmp.bib

[[printbibliography:]]
```

And `tmp.bib` contains:

```
@inproceedings{test_org_ref,
  title={Testing org ref},
  author={Author, Some},
  booktitle={Proceedings},
  volume={},
  number={},
  year={}
}
```

In both pdf and html, I get (`Author, n.d.` is hyperlinked as expected):

```
Author Author, n.d. wrote the paper in 2023.
Author, Some. n.d. "Testing Org Ref." In Proceedings.
```

while I only expect:

```
Author, n.d. wrote the paper in 2023.
Author, Some. n.d. "Testing Org Ref." In Proceedings.
```

**Comment by jkitchin** [comment]
I guess this is almost certainly a citeproc issue. This code shows the issue I think with no org-ref code. I would report it to citeproc (@andras-simonyi at https://github.com/andras-simonyi/citeproc-el/issues).

```
#+BEGIN_SRC bibtex :tangle tmp.bib
@inproceedings{test_org_ref,
  title={Testing org ref},
  author={Author, Some},
  booktitle={Proceedings},
  volume={},
  number={},
  year={2024}
}
#+END_SRC

Render a citation


#+BEGIN_SRC emacs-lisp :var tangled=(org-babel-tangle)
(let ((proc (citeproc-create
	     (expand-file-name org-ref-csl-default-style
			       (f-join
				(file-name-directory
				 (locate-library "org-ref"))
				"citeproc/csl-styles"))
	     (citeproc-itemgetter-from-bibtex "tmp.bib")
	     (citeproc-locale-getter-from-dir (f-join (file-name-directory
						       (locate-library "org-ref"))
						      "citeproc/csl-locales"))
	     "en-US"))
      (cites (list (citeproc-citation-create :cites '(((id . "test_org_ref")))
					     :mode 'textual)))
      (backend 'html))

  (citeproc-append-citations cites proc)

  (citeproc-render-citations proc 'html))
#+END_SRC

#+RESULTS:
| Author (<a href="#citeproc_bib_item_1">2024</a>) |
```

**Comment by digikar99** [comment]
Yes, thanks! I have reported it at https://github.com/andras-simonyi/citeproc-el/issues/151

**Comment by dangom** [comment]
Hi, perhaps we should re-open this issue. The linked discussion suggests there is some sort of interaction with org-ref that is causing the name duplication to appear.

Any suggestions or workarounds would be appreciated!

**Comment by jkitchin** [comment]
I tried taking out the code referenced in t https://github.com/andras-simonyi/citeproc-el/issues/151. It does seem to work as you expected now I think. Can you try it?

**Comment by dangom** [comment]
Hi John, 
I confirm it is working now as expected.

thanks for the prompt response and fix.
