### ISSUE TITLE
Slow editing of sentences with acronym links

### ISSUE THREAD

**Issue by weidtn** [jkitchin/org-ref#1106]
Hello,

im currently writing my thesis in org-mode with org-ref. I added some acronyms and a table on top containing these acronyms. Whenever I try to edit something in a sentence already containing an acronym link, I first have to wait a few seconds until emacs reacts. It is reading something in the background and blocks the whole process. Writing a new sentence or editing something without an acronym link works fine.

I use doom emacs and evil mode. With editing, I mean specifically adding or removing letters inside of insert mode for example.

**Comment by jkitchin** [comment]
It is probably font lock that is slow. Try (setq org-ref-activate-glossary-links nil). This will turn off activation of the links and speed it up a lot probably.

**Comment by weidtn** [comment]
That works. What exactly is it deactivating? I still see the acronyms as links in the text?

**Comment by jkitchin** [comment]
There is a function that is used to find the face for syntax highlighting the links. If `org-ref-activate-glossary-links` is nil it just returns the link face. If it is true though, it re-parses the document (which is slow) and if the link doesn't point to something valid it makes the link red so it is obvious it is wrong.

**Comment by weidtn** [comment]
Thank you for the quick help and the explanation!
