### ISSUE TITLE
OpenAlex: [error] request-default-error-callback

### ISSUE THREAD

**Issue by FilConscious** [jkitchin/org-ref#1114]
Hi,

I've recently seen your video tutorials on how to use org-ref to retrieve data via OpenAlex. Thanks for this, these new functionalities look amazing!

Unfortunately, I'm not able to use them in Doom Emacs (with helm and helm-bibtex).

When I click on a reference, I get the following hydra in which two of the OpenAlex functions are missing (`Related documents` and `Cited by documents`):

![Screenshot from 2024-05-08 22-41-19](https://github.com/jkitchin/org-ref/assets/56924093/fcd46981-57a9-4615-baa4-7efa8e78c1f0)

Then, if I try to use `References from`, the OpenAlex buffer appears but consistently zero results are found, and the following errors are displayed:

```
[error] request--callback: peculiar error: 404
[error] request-default-error-callback: https://api.openalex.org/worksdoi:https://doi.org/10.1016/j.neuron.2018.07.035?mailto=myemail@me.com&api_key=nil&filter=nil error
```
A quick look at the OpenAlex [API](https://docs.openalex.org/api-entities/works/get-a-single-work) makes me think that there should be a `/` between `works` and `doi` , otherwise the call is incorrect, hence the 404 error.

If you could provide any further insight or explanation, to help fix this issue, I would greatly appreciate it.

**Comment by jkitchin** [comment]
I think I fixed some of these issues. I don't know why there is only xf showing initially. If I reload the openalex library then all of them appear. I will keep looking into that.

**Comment by FilConscious** [comment]
Thanks a lot! 

Everything seems to be working now:

- I can see all  the`x-` functions when the hydra is invoked
- each returns a list of related entries in a new buffer

**Comment by jkitchin** [comment]
thanks for reporting it. It was bugging me every once in a while, and I am glad to have fixed it!
