### ISSUE TITLE
Function to open file 

### ISSUE THREAD

**Issue by chatziiola** [jkitchin/org-ref#1124]
Hello, and thank you for this fantastic package! I've been using it for quite some time, and it's been incredibly reliable. As the package has proven its worth, I wanted to suggest a small addition that might benefit other users and could potentially be integrated in future updates.

The proposed feature complements the existing functionality of opening an associated PDF file. However, instead of searching within a preset directory, this function would check the file attribute in the BibTeX entry and open the corresponding file directly.

I believe this could enhance the user experience and provide more flexibility for managing PDF associations.

Once again, thank you for your work ;)

EDIT: It's not much, but it really felt like it was missing, at least on my workflow.

```elisp

(defun chatziiola/open-cite-file () ;; obviously the name should change :P
  (interactive)
  (let* ((key (org-ref-get-bibtex-key-under-cursor))
         (entry (org-ref-get-bibtex-entry key))
         (file-field (when (string-match "file *= *{\\(.*?\\)}" entry)
                       (match-string 1 entry))))
    (if file-field
        (call-process "open" nil 0 nil (expand-file-name file-field))
      (message "No file found for this entry."))))

```

**Comment by jkitchin** [comment]
you  might look at `bibtex-completion-find-pdf-in-field` and `bibtex-completion-find-pdf`. I think you can set it up to do this automatically. Probably by setting `(setq bibtex-completion-pdf-field "file")`.

**Comment by chatziiola** [comment]
For some reason I completely overlooked that functionality. Sorry for your time and thanks for the nudge ;).  

(I'm closing the issue since there is no reason for it to exist)

**Comment by jkitchin** [comment]
no problem. There used to be a feature like this before it switched over to bibtex-completion.
