### ISSUE TITLE
New `parsebib.el` parser.

### ISSUE THREAD

**Issue by joostkremers** [jkitchin/org-ref#1125]
Hi @jkitchin , `org-ref` depends on `parsebib.el`, so I wanted to give you a heads-up: I've ripped out the pretty hairy regexp-based parser code and replaced it with a simple recursive descent parser. The new parser works well, and the tests included in `parsebib` all pass, but with this kind of thing there's always a risk of regressions, of course.

I haven't merged the new code yet, and I don't know to what extent `org-ref` depends on `parsebib.el`, but once I merge the code, you may get bug reports from users that are ultimately caused by `parsebib.el`. If that happens, just send them to me, or key me in on the discussion.

If you have a `.bib` file that you would like to test the new code with before I do the merge, I'd be happy to do that, or if you prefer, you can check out the code [here](https://github.com/joostkremers/parsebib/tree/wip/rdp).

**Comment by jkitchin** [comment]
Thanks for the heads up. The most obvious thing I see is `parsebib-find-bibtex-dialect` in many places. I think `bibtex-completion` is doing most of the work in the bib files. I'd say go for the merge, and we will work out any bugs that arise. My work schedule is a little busy in the next month, and I won't have time to do any testing until probably decemberish.

**Comment by joostkremers** [comment]
I'm closing this issue for now. I'll keep an eye on the issues in this repo, so if anything comes up, I'll be notified.
