### ISSUE TITLE
 Search failed: ";; Version:"

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#1126]
running org-ref inside an org-file to verify the setup, fails with eth following backtrace

```elisp
Debugger entered--Lisp error: (search-failed ";; Version:")
  org-ref-version()
  org-ref()
  funcall-interactively(org-ref)
  command-execute(org-ref record)
  helm-M-x-execute-command(org-ref)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode 0x14bbf3403c03c567>)) (candidates . helm-candidates-in-buffer) (
...
```
executing `org-ref-version()` manually results in the same error.

**Comment by jkitchin** [comment]
huh. it looks like the version gets stripped when installing from MELPA. I think I have pushed a commit to stop that error, and show some useful information anyway.
