### ISSUE TITLE
TODO item not generated by "doi-add-bibtex-entry"

### ISSUE THREAD

**Issue by aydemirfb** [jkitchin/org-ref#113]
For some papers, "doi-add-bibtex-entry" neither generates TODO item in notes.org nor downloads (or asks for) the PDF.
DOIs: 
   * 10.1007/978-3-642-16086-8_2
   * 10.1007/978-3-540-45064-1_2
   * 10.1007/978-3-642-02463-4_20

**Comment by jkitchin** [comment]
Thanks for noting these. I added a new Springer chapter recipe that helps a bit, but it seems Springer might hide these behind some redirects so right now all that happens is the browser should open so you can manually download the pdf. These dois are missing chapter fields I think, so bibtex thinks a mandatory field is missing. I am not familiar with this entry type, so I am not sure what should go there.
