### ISSUE TITLE
Error with doi-utils-add-entry-from-crossref-query

### ISSUE THREAD

**Issue by ericdanan** [jkitchin/org-ref#115]
When I call the function doi-utils-add-entry-from-crossref-query (in library doi-utils) I get a helm buffer to select from a list of references, and when I select one I get the error message "Symbol's function definition is void: loop".

From this page:

http://stackoverflow.com/questions/30847443/emacs-symbols-function-definition-is-void-loop

I understand that this function "loop" belongs to library "cl", and so I guess that either doi-utils should require cl, or (more recommended on the above page), cl-loop should be used instead of loop. Is this correct?

**Comment by jkitchin** [comment]
weird. loop is an alias for ‘cl-loop’. What version of emacs are you using? org-ref should be requiring 24.4 or greater.

**Comment by ericdanan** [comment]
I am using version 24.5, but function loop is not defined. Only once I load library cl I get "loop is an alias for `cl-loop' in `cl.el'." Is this not normal?

**Comment by jkitchin** [comment]
You are probably right. 
(require 'cl)           ;; common-lisp functions
is one of the first things that gets loaded in my init files.

I added this to the doi-utils library.

**Comment by ericdanan** [comment]
Strangely, it doesn't work for me. I can see at the beginning of doi-utils.el the following:
(eval-when-compile
  (require 'cl))
But I still get the same error. On the other hand, if I add (require 'cl) in my init file then it works. So maybe the (eval-when-compile ...) form creates the problem? (or perhaps some problem in my setup...)

**Comment by jkitchin** [comment]
I am not sure. I have (require 'cl) in my init, which may be why it works fine for me.

I have never fully understood the eval-when compile bit.

**Comment by ericdanan** [comment]
I don't understand this bit either, but I tested what is stated in the 
link from my first message: not requiring cl but replacing loop with 
cl-loop, and it works for me (it is stated that this is the right way to 
go starting from emacs 24.3 since cl-loop belongs to library cl-lib 
which is included in emacs). If I keep the cl requirement and replace 
loop with cl-loop it also works, but then the cl requirement is 
apparently redundant because cl simply defines loop as an alias for cl-loop.

**Comment by jkitchin** [comment]
It seems the eval-when compile bit is for making the .elc files. It seems to serve the function of removing the references to cl-macros in the compiled code, but has no effect if you don't compile org-ref. If you don't compile it, I think you need (require 'cl).

**Comment by ericdanan** [comment]
OK. I'm not sure why I was getting the error then, because I was 
installing the package from MELPA and it was automatically compiled 
after being downloaded. But in any case it works out of the box now that 
loop has been replaced with cl-loop.
