### ISSUE TITLE
option not to store date added with doi-utils-insert-bibtex-entry-from-doi

### ISSUE THREAD

**Issue by ericdanan** [jkitchin/org-ref#116]
I did not find a way to add a bibtex entry with doi-utils-insert-bibtex-entry-from-doi without storing the date added in a bibtex field. I tried setting doi-utils-timestamp-field to nil but this didn't work. Would it work to put the form (bibtex-set-field ...) in this function inside (when doi-utils-timestamp-field ...)?

**Comment by jkitchin** [comment]
I just pushed a fix that should let you set doi-utils-timestamp-format-function to nil, and then it should not insert a timestamp or set the field.

**Comment by ericdanan** [comment]
Thank you. I don't see the fix in MELPA yet but I see it on github and will set doi-utils-timestamp-format-function to nil.

**Comment by jkitchin** [comment]
it can take 4-8 hours to show up in MELPA depending on when the commit is in the current build cycle.

**Comment by ericdanan** [comment]
Works fine, thank you!
