### ISSUE TITLE
Make org-ref / doi-utils available on MELPA

### ISSUE THREAD

**Issue by tmalsburg** [jkitchin/org-ref#12]
Thanks for org-ref, fantastic work!  Please consider making it available on MELPA.  It might make sense to orthogonalize doi-utils and org-ref and to provide them as two separate packages.

**Comment by jkitchin** [comment]
This is on my list to do. I think it needs to be converted to an
emacs-lisp package I can edit with lentic. Right now it is not
compatible with melpa I think because it exists as an org-file to be
tangled. The org form has been great, but it is causing some problems
with tangling, so I am slowly working toward the lentic approach which
is kind of the best of both worlds!

Titus von der Malsburg writes:

> Thanks for org-ref, fantastic work!  Please consider making it available on MELPA.  It might make sense to orthogonalize doi-utils and org-ref and to provide them as two separate packages.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/12

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by tmalsburg** [comment]
The lentic approach seems pretty interesting (although I couldn't figure out how to make it work).  Looking forward to see your result.

**Comment by jkitchin** [comment]
It is pretty cool. I have been practicing it on this file:
https://github.com/jkitchin/jmax/blob/master/words.el

What I like about it is the file is just an .el file, but I can write the
documentation/structure in an org-buffer. It works pretty well, but I am
still working out how to get it started, and whether it introduces other
bad things, e.g. the file-local variable in words.el

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by cpaulik** [comment]
Hi 

Should this be closed? I was just going to ask if and when org-ref will be available from MELPA. I would  like to write a [spacemacs](https://github.com/syl20bnr/spacemacs) layer for org-ref but this is not really possible at the moment.

**Comment by jkitchin** [comment]
Probably not closed since it is not in MELPA yet ;) It is not too far off. I won't get back to it before May though.

**Comment by JP-Ellis** [comment]
Any update on making it available through MELPA?

**Comment by jkitchin** [comment]
It is still on my mind. The semester is almost over. Maybe a Christmas miracle ;)?

**Comment by jkitchin** [comment]
I got a pull request into Melpa today: https://github.com/milkypostman/melpa/pull/3391!

**Comment by JP-Ellis** [comment]
Awesome :D

**Comment by jkitchin** [comment]
We aren't on MELPA yet, but you might be able to install with the package manager with these directions: https://github.com/jkitchin/org-ref#package-installation

**Comment by jkitchin** [comment]
Finally on MELPA!!!

**Comment by jschaf** [comment]
Sweet, congrats!

**Comment by cpaulik** [comment]
Great, Thanks
