### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by quasiquasar** [jkitchin/org-ref#126]
Can somebody add info to the README file on how to change the format of bibtex labels? I've tried to figure it out, but no success. Maybe add an example of such configuration.

For example:
The default configuration generates something like:
"@book{kitchin03:_astrop_techn_fifth_edition,"
and I want to change it so the default would be 
"@book{Kitchin:2003,"

**Comment by jkitchin** [comment]
This is controlled by bibtex-autokey variables.

I use something like this:

`(setq bibtex-autokey-year-length 4
      bibtex-autokey-name-year-separator "-"
      bibtex-autokey-year-title-separator "-"
      bibtex-autokey-titleword-separator "-"
      bibtex-autokey-titlewords 2
      bibtex-autokey-titlewords-stretch 1
      bibtex-autokey-titleword-length 5)
`
