### ISSUE TITLE
Drag and drop results in error when dropping in special buffers

### ISSUE THREAD

**Issue by andreaskiermeier** [jkitchin/org-ref#128]
Hi John,
I often drag and drop files into emacs, including immediately after starting emacs. In this case the current buffer is *scratch* and dragging files into it results in the error "file-name-extension: Wrong type argument: stringp, nil".
Calling the debugger on error leads me to believe that the error is coming from org-ref-pdf-dnd-protocol, because there is no extension associated with this buffer. Same happens for other special buffers such as *ESS* or *Messages*.
Thanks
Andreas

**Comment by jkitchin** [comment]
I noticed that recently too. I found the place that was causing it: it is buffers with no filename associated with them that was the problem. I just pushed a fix for that. Let me know if it fixes it for you.

**Comment by andreaskiermeier** [comment]
Thanks for the quick fix, John. Works as expected.

**Comment by jkitchin** [comment]
great. Thanks for reporting it.
