### ISSUE TITLE
No entry found and mangled citations in .tex export

### ISSUE THREAD

**Issue by TuringMachinegun** [jkitchin/org-ref#129]
Hi John,
for some weird reason I can't figure out, org-ref can't find some of the entries in my bibliography; they don't seem different from the others.
When I look at the exported .tex file, I notice that the same entries that couldn't be found by org-ref are mangled, missing the first letter or the last letter.

My configuration is:
emacs 24.5.2
org-ref 0.5.0

with customization:
```lisp
  (require 'org-ref)

  (setq my-bibdir "~/Dropbox/PhD_thesis/bibliography/")
  (setq my-bib-file (expand-file-name (concat my-bibdir "bibliography.bib")))
  (setq my-bib-notes (expand-file-name (concat my-bibdir "notes.org")))
  (setq my-bib-pdfdir (expand-file-name (concat my-bibdir "bibtex-pdfs/")))

  (setq reftex-default-bibliography `(,my-bib-file))

  (setq org-ref-bibliography-notes my-bib-notes
        org-ref-default-bibliography `(,my-bib-file)
        org-ref-pdf-directory my-bib-pdfdir)

  (setq helm-bibtex-bibliography `(,my-bib-file)
        helm-bibtex-library-path my-bib-pdfdir)

  (setq helm-bibtex-notes-path my-bib-notes)
```

Here's a minimal working example, with an .org file (I put a .txt at the end so that github doesn't complain about not recognizing the file):
[example.org.txt](https://github.com/jkitchin/org-ref/files/125241/example.org.txt)

the .bib file:
[bibliography.bib.txt](https://github.com/jkitchin/org-ref/files/125244/bibliography.bib.txt)

and the produced .tex file:
[example.tex.txt](https://github.com/jkitchin/org-ref/files/125245/example.tex.txt)

**Comment by TuringMachinegun** [comment]
For example, the citations
turing1937computable, turing1950computing, tsuda01, tan2007synthetic, tabor00a, tabor02a, tabor09:_dynam_system_persp_relat_between
become:
uring1937computable,uring1950computing,suda01,an2007synthetic,abor00a,abor02a,abor09:_dynam_system_persp_relat_betwee

The last item in particular loses both initial and final letter

**Comment by jkitchin** [comment]
hm. I can't reproduce your errors. I did have problems with the underscores though. latex stops at ! Missing \endcsname inserted.
<to be read again> 
                   \unhbox 
l.37 ...neral-purpose_2003,Kurkova95,TMtoNDsource}

Do you have some package that allows underscores?

**Comment by TuringMachinegun** [comment]
Not that I know of; also, if I run pdflatex example.tex, I only get warnings relative to the missing citations, no problem. Same if I run latex.
I'm on linux mint 17, not sure if that could be a factor.

Just to be sure, I deleted everything in my init.el, leaving basically only the snippets in the first post: I still get the weird behaviour exactly as before

**Comment by jkitchin** [comment]
I figured out it is related to the underscore package, I have to give it a [strings] option to allow underscores in cites. then it works fine as is for me. I can't reproduce your issue. I do get one ? from your file because there is a ,, in the cite link, but it doesn't seem to affect anything else. I can't think of any obvious reason for what you see. it seems significant to me that all your examples lose a t or an n. if somehow they were escaped, e.g. \t or \n they might be mistaken for whitespace, but I can't see how that would be happening.

**Comment by TuringMachinegun** [comment]
OK, I tried this on my windows computer and I still get the error. I left only the packages needed to run org-ref.
I spent some time trying to track it down by using edebug: the t's and n's (and r's!) start to miss from line 1909 of ox.el, inside the function org-export-data at

```lisp
		      (funcall transcoder data
			       (if (not greaterp) contents
				 (org-element-normalize-string contents))
			       info)
```

which is called at some point when I tried running org-latex-export-latex.

Now, given that only n's, t's and r's are missing, and only when at the beginning or at the end of each string, I agree with you that there must be something going on that involves escaped characters; And for some reason the latex export seems to mess that up. What I don't understand is what this has to do with looking up the entries in the .bib file in the case of org-ref. Any ideas about what the common denominator could be?

**Comment by TuringMachinegun** [comment]
So, I went on today and tracked the error down to org-ref-strip-string, if I do
```lisp
  (mapcar 'org-ref-strip-string
           (split-string "turing1950computing,Tsuda01,tan2007synthetic" ","))
```
I get the strings without the initial t's

**Comment by jkitchin** [comment]
Whew! It was a good tip to look at the whitespace chars then ;) Glad to hear it is working again.

**Comment by TuringMachinegun** [comment]
Yes, it was. I don't even remember why I customized it like that! Well, all's well what ends well :)
