### ISSUE TITLE
Ref links without descriptions insert extra brackets by default

### ISSUE THREAD

**Issue by prtkm** [jkitchin/org-ref#13]
Hi John,

I noticed when inserting ref links with C-c C-l or Alt-Esc R the completion  prompt automatically inserts "]]" at the end  of the label we want to refer. The resulting link looks like,

[[ref:orbital-energies%5D%5D][ref:orbital-energies]]]]

Of course, I can get rid of the brackets during the completion and it looks fine. The problem goes away if I add a description to the link.

[[ref:orbital-energies%5D%5D][a description]]

PS. Is there a helm interface for this in jmax?

**Comment by jkitchin** [comment]
Prateek Mehta writes:

> Hi John,
>
> I noticed when inserting ref links with C-c C-l or Alt-Esc R the completion  prompt automatically inserts "]]" at the end  of the label we want to refer. The resulting link looks like,
>
> [[ref:orbital-energies%5D%5D][ref:orbital-energies]]]]

hm. I think this is an org bug. %5D%5D looks like escaped ]] to me. That
does not happen in my org mode.

>
> Of course, I can get rid of the brackets during the completion and it looks fine. The problem goes away if I add a description to the link.
>
> [[ref:orbital-energies%5D%5D][a description]]
>
> PS. Is there a helm interface for this in jmax?
Haha! I thought what a good idea, and then I looked in org-ref and
found: org-ref-helm-insert-label-link

and

org-ref-helm-insert-ref-link

Neither are bound to a key, but you can do it yourself.

>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/13

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Ah, I don't see it happen on my Mac. Looks like I'm using a more recent version of org on my linux machine.

Awesome! I will probably bind them to keys. Not sure if I'll remember what I bind them to during actual use though!

**Comment by jkitchin** [comment]
Check out http://kitchingroup.cheme.cmu.edu/blog/2015/02/20/org-ref-meets-hydra/

**Comment by jkitchin** [comment]
check out
http://kitchingroup.cheme.cmu.edu/blog/2015/02/20/org-ref-meets-hydra/ for
a solution to remembering it.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
That is so cool! I tried out the "ww" key chord for words. Were you already writing the blog post when I  wrote the message? If not that would be the fastest blog post ever written!

**Comment by jkitchin** [comment]
it was the fastest one ever written ;)

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
