### ISSUE TITLE
Add package to Melpa-Stable

### ISSUE THREAD

**Issue by bennati** [jkitchin/org-ref#131]
Hi!

MELPA Stable (http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be super cool if function-args could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the `v...` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

If you're cool with this idea, this should be all you have to do to make it happen:

```sh
$ git tag v$stable-version-number $stable-version-commit-hash
$ git push origin v$stable-version-number
```

Thanks for your time and consideration!

(src https://gist.github.com/camdez/48a4fd2bb3a05572f0a5)

**Comment by jkitchin** [comment]
This is on my list of things to do. org-ref seems pretty stable these days (relative to the past that is ;). I will give it some thought and try to do this sooner than later.

**Comment by jkitchin** [comment]
This is done now.
