### ISSUE TITLE
Org-ref cite: fails if the bibtex entries are tagged with @Conference

### ISSUE THREAD

**Issue by thabr** [jkitchin/org-ref#134]
Org-ref Displays !!No entry found !! if a bibtex entry in the references bib is of the type @Conference instead of @Article. However the same bibtex entry can be found by org-ref, if the @Conference is changed to @Article. Is this on purpose, meaning @Conference is not supposed to be supported or is there another reason?

**Comment by jkitchin** [comment]
I am pretty sure @Conference is not a bibtex or biblatex type, and that bibtex.el can't find it.

In bibtex you get: | Article | InProceedings | InCollection | InBook | Proceedings | Book | Booklet | PhdThesis | MastersThesis | TechReport | Manual | Unpublished | Misc |

in biblatex you get: | Article | Book | MVBook | InBook | BookInBook | SuppBook | Booklet | Collection | MVCollection | InCollection | SuppCollection | Manual | Misc | Online | Patent | Periodical | SuppPeriodical | Proceedings | MVProceedings | InProceedings | Reference | MVReference | InReference | Report | Thesis | Unpublished |

**Comment by thabr** [comment]
Hello, thank you for your response. That explaines why it cant be found, but i looked it up on Wikipedia and there it said conference is a valid type. Also when exporting a bibtex entry for a conference paper from the scopus website it gets tagged using @conference. But thats probably due to insufficient standards.

**Comment by jkitchin** [comment]
The authoritative source in this case is bibtex.el, which is where that
list of entry types came from ;) The wikipedia pages suggests the
conference type is for Scribe compatibility. It might work with
bibtex/Latex, but bibtex.el doesn't seem to recognize it.

**Comment by jkitchin** [comment]
I am not sure if this is a good idea, but if conference is actually a legit entry type that works with LaTeX, I think you can convince org-ref to see it with this in an init file.

#+BEGIN_SRC emacs-lisp
(add-to-list 'bibtex-BibTeX-entry-alist
 (cons "Conference" (cdr (assoc "InProceedings" bibtex-BibTeX-entry-alist))))
#+END_SRC

**Comment by thabr** [comment]
Thank you for that idea, but i already found a workaround for my problem. I looked up the bibtex types you were refering to and @proceedings seems to be the adequate replacement for conference. So I changed my bibtex entry generator to tag the conference papers with @proceedings.

**Comment by jkitchin** [comment]
Sounds good. What do you use for your entry generator?

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by thabr** [comment]
I wrote a little programm that is able to find information from search engines in emacs and store them locally. After this a basic bibtex entry from the information is generated and written into the references.bib. This gives me the chance to try to use org-ref for downloading a pdf and citing the papers.
Thilo

**Comment by jkitchin** [comment]
Have you tried out M-x doi-add-bibtex-entry and M-x
crossref-add-bibtex-entry?

You might also try the pdf and url drag and drop features. If you drag a
pdf or url with a doi in it onto your bib file in emacs, it will try to
download a bibtex entry for you.

Is your program visible anywhere?

thabr writes:

> I wrote a little programm that is able to find information from search engines in emacs and store them locally. After this a basic bibtex entry from the information is generated and written into the references.bib. This gives me the chance to try to use org-ref for downloading a pdf and citing the papers.
> Thilo
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/134#issuecomment-184183870


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by thabr** [comment]
The functions you mentioned are great to get reference entries from the Internet ;) In my program our Focus lies on the reproducibility of the search for Literatur. This means we are downloading results from search engines like scopus und storing the result number, type, etc. Starting from this we export the entries to bibtex and the use org-ref to cite in our paper.

The program is not public yet since we are developing it in a student group. Im not sure wether we're gonna publish it, but if so I can let you know.
