### ISSUE TITLE
doi-utils.org does not tangle properly when loading

### ISSUE THREAD

**Issue by icymist** [jkitchin/org-ref#14]
Steps to reproduce:

1. clone org-ref
1. use [this](https://gist.github.com/icymist/eb40a2ffb21d709c4532#file-orgref-config-el) org-ref setup
1. load emacs

The above produces [this](https://gist.github.com/icymist/45a33d3bf42b700a1256#file-doi-utils_tangled-by-default-el) improperly tangled doi-utils.el.

But, by visiting doi-utils.el and doing org-babel-tangle produces [this](https://gist.github.com/icymist/45a33d3bf42b700a1256#file-doi-utils_tangled-with-org-babel-tangle-el) proper(?) doi-utils.el

**Comment by jkitchin** [comment]
I think I have fixed this. Thanks for reporting it.

**Comment by icymist** [comment]
Work as expected. Thanks!
