### ISSUE TITLE
fallback when no pdf found

### ISSUE THREAD

**Issue by dlebrecht** [jkitchin/org-ref#141]
I think it could be interesting to have a fallback when no pdf is available. There's this website:
sci hub. The two words are joined by -, and the extension is .io. It would solve a lot of the issue of finding dois on websites, but its legality (and not morality) is questionable. Below substitude magicwebsite.ext by the proper website

u can call it 
http://magicwebsite.ext/doinumber 
and it will download the article for you. sometimes it shows captcha though

u can also call it with a website containing the paper:
http://magicwebsite.ext/http://www.ncbi.nlm.nih.gov/pubmed/24151334
or: 
http://magicwebsite.ext/http://www.nature.com/nature/journal/v464/n7292/full/nature08897.html

**Comment by jkitchin** [comment]
I'd say there is no question of that site being illegal! I couldn't support that. You can add your own action like this though: https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L4259
