### ISSUE TITLE
"show entry" does not work when entry has a "file" field

### ISSUE THREAD

**Issue by minkkinen** [jkitchin/org-ref#142]
In org-ref-helm-cite, "show entry" does not work when the entry has a "file" field. As far as I know, this is because org-ref-helm-cite-open-entry calls (cdr (assoc "file" entry)) which points to the wrong place when the entry has a field called "file". Saving PDFs in the "file" field is useful because then you can open PDFs from JabRef or a mobile bibtex app on Android.

**Comment by jkitchin** [comment]
thanks for reporting that. I changed it to bibfile, which should avoid the name collision. unfortunately though you need to run M-x orhc-clear-cache to clear the old cache. it will get regenerated the next time you use it. Let me know if it fixes your issue.

**Comment by minkkinen** [comment]
Works now. Thanks for the quick fix!
