### ISSUE TITLE
Wiley import issue

### ISSUE THREAD

**Issue by brittAnderson** [jkitchin/org-ref#148]
The following doi gives me a json readtable error: 10.1002/hbm.10010
However, this quicky version of a get url function seems to work when added to doi-utils (and the list of functions). Don't know if it is my system, or if Wiley is doing something different.

```
(defun mywiley-pdf-url (*doi-utils-redirect*)
  "Get url to the pdf from *DOI-UTILS-REDIRECT*."
  (when (string-match "^http://onlinelibrary.wiley.com" *doi-utils-redirect*)
    (replace-regexp-in-string "/abstract" "/pdf" *doi-utils-redirect*)))
```

Note this skips the stage of parsing the html to extract the url. Maybe no longer necessary?

**Comment by jkitchin** [comment]
hm. I cannot reproduce this error. I was able to get it with doi-add-bibtex-entry fine. and by dragging the url onto a bibfile. I sometimes wonder if the readtable errors are on the random side...
