### ISSUE TITLE
doi-utils-add-bibtex-entry-from-doi problems

### ISSUE THREAD

**Issue by liuzy** [jkitchin/org-ref#150]
when I use the doi-utlils-add-bibtex-entry-from-doi, I get the messages: "Contacting host: dx.doi.org:80
doi-utils-doi-to-bibtex-string: Wrong type argument: integer-or-marker-p, nil" .  What's the matter?

**Comment by jkitchin** [comment]
I don't know of any problems. What doi are you using?

**Comment by liuzy** [comment]
I have tested many dois, including the doi you give: doi:10.1021/jp511426q.
And they return the same problems.

**Comment by liuzy** [comment]
The org-ref version is melpa's org-ref-20160307.

**Comment by jkitchin** [comment]
Odd. I tried it this morning and it worked ok I think. Can you try toggle debug on error and see if it gives a more helpful traceback?

**Comment by liuzy** [comment]
Sorry, I do not know well emacs, so I don't know what I should do .
Can you tell me more detailed ?

On Wed, Mar 9, 2016 at 8:18 PM, John Kitchin <notifications@github.com>
wrote:

> Odd. I tried it this morning and it worked ok I think. Can you try toggle
> debug on error and see if it gives a more helpful traceback?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/150#issuecomment-194270241>.
>



-- 
祝好！

刘镇洋
Tel:18600589624
Email:liuzy2011@gmail.com

**Comment by jkitchin** [comment]
Type alt-x toggle-debug-on-error

Then try to add a doi and probably you will get a screen full of error
messages that will help me figure out the problem.

On Wednesday, March 9, 2016, Liuzhenyang <notifications@github.com> wrote:

> Sorry, I do not know well emacs, so I don't know what I should do .
> Can you tell me more detailed ?
>
> On Wed, Mar 9, 2016 at 8:18 PM, John Kitchin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Odd. I tried it this morning and it worked ok I think. Can you try toggle
> > debug on error and see if it gives a more helpful traceback?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jkitchin/org-ref/issues/150#issuecomment-194270241>.
> >
>
>
>
> --
> 祝好！
>
> 刘镇洋
> Tel:18600589624
> Email:liuzy2011@gmail.com
> <javascript:_e(%7B%7D,'cvml','Email:liuzy2011@gmail.com');>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/150#issuecomment-194276420>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
You might also try running:
Alt-x org-ref-debug

and paste the results here.

**Comment by liuzy** [comment]
I typed "alt-x toggle-debug-on-error", and tried to add a doi, got the error messages:
"Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  doi-utils-get-json-metadata("10.1021/jp511426q")
  doi-utils-doi-to-bibtex-string("10.1021/jp511426q")
  doi-utils-insert-bibtex-entry-from-doi("10.1021/jp511426q")
  doi-utils-add-bibtex-entry-from-doi("10.1021/jp511426q" "~/Scholar/references.bib")
  call-interactively(doi-utils-add-bibtex-entry-from-doi record nil)
  command-execute(doi-utils-add-bibtex-entry-from-doi record)
  (if helm-M-x-always-save-history nil (command-execute sym-com (quote record)))
  (let ((prefix-arg (or helm-current-prefix-arg arg))) (if helm-M-x-always-save-history nil (command-execute sym-com (quote record))) (setq extended-command-history (cons command-name (delete command-name extended-command-history))) (if helm-M-x-always-save-history (progn (command-execute sym-com (quote record)))))
  (let ((sym-com (and (stringp command-name) (intern-soft command-name)))) (setq this-command sym-com real-this-command sym-com) (let ((prefix-arg (or helm-current-prefix-arg arg))) (if helm-M-x-always-save-history nil (command-execute sym-com (quote record))) (setq extended-command-history (cons command-name (delete command-name extended-command-history))) (if helm-M-x-always-save-history (progn (command-execute sym-com (quote record))))))
  helm-M-x(nil "doi-utils-add-bibtex-entry-from-doi")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)".

**Comment by liuzy** [comment]
And "Alt-x org-ref-debug", results:

#+TITLE: org-ref debug

org-ref: Version 0.7.0 (git-commit c6524d35f552a79104623af4b0970995677bffd1)

* Variables
1. org-ref-bibliography-notes: ~/Scholar/notes.org (exists t)
2. org-ref-default-bibliography: (~/Scholar/references.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: ~/Scholar/bibtex-pdfs/ (exists t)

* System
system-type: System: gnu/linux
system-configuration: x86_64-pc-linux-gnu
window system: Window system: x
Emacs: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu)
 of 2015-12-14 on lzy
org-version: 8.3.2

* about org-ref
org-ref installed in /home/liuzy2014/.emacs.d/elpa/org-ref/org-ref.elc.

** Dependencies
helm-bibtex /home/liuzy2014/.emacs.d/elpa/helm-bibtex/helm-bibtex.elc

* org-ref-pdf (loaded: nil)
system pdftotext: org-ref-pdf not loaded
You set pdftotext-executable to org-ref-pdf not loaded (exists: org-ref-pdf not loaded)

* org-ref-url-utils (loaded: nil)

**Comment by jkitchin** [comment]
Can you try:

M-x doi-utils-debug 10.1021/jp511426q

and check the output?

**Comment by liuzy** [comment]
I have tried that: and the main window shows "doi:10.1021/jp511426q"
the "Message" window shows:
"Contacting host: dx.doi.org:80
call-interactively: Wrong type argument: integer-or-marker-p, nilError during redisplay: (jit-lock-function 1) signaled (args-out-of-range 0 0)"

**Comment by jkitchin** [comment]
very strange. Can you try this in a vanilla emacs with just org-ref? I haven't been able to reproduce the error.

You might also try a new bibtex file. just in case there is something wrong in the file you are adding it to.

**Comment by liuzy** [comment]
Ooo, still has the same problem.

M-x org-ref-debug results:
"#+TITLE: org-ref debug

org-ref: Version 0.7.0 (git-commit fdcabd6dd580694a5b0a62123b298ac885d14dd8)

* Variables
1. org-ref-bibliography-notes: ~/notes.org (exists t)
2. org-ref-default-bibliography: (~/ref.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: ~/bibtex-pdfs/ (exists t)

* System
system-type: System: gnu/linux
system-configuration: x86_64-pc-linux-gnu
window system: Window system: x
Emacs: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu)
 of 2015-12-14 on lzy
org-version: 8.2.10

* about org-ref
org-ref installed in /home/liuzy2014/.emacs.d/org-ref/org-ref.el.

** Dependencies
helm-bibtex /home/liuzy2014/.emacs.d/helm-bibtex/helm-bibtex.elc

* org-ref-pdf (loaded: nil)
system pdftotext: org-ref-pdf not loaded
You set pdftotext-executable to org-ref-pdf not loaded (exists: org-ref-pdf not loaded)

* org-ref-url-utils (loaded: nil)"

M-x toggle-debug-on-error results:
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  buffer-substring(nil 1)
  (setq json-data (buffer-substring url-http-end-of-headers (point-max)))
  (save-current-buffer (set-buffer (url-retrieve-synchronously (concat "http://dx.doi.org/" doi))) (setq json-data (buffer-substring url-http-end-of-headers (point-max))) (if (string-match "Resource not found" json-data) (progn (browse-url (concat "http://dx.doi.org/" doi)) (error "Resource not found.  Opening website")) (json-read-from-string json-data)))
  (let ((url-request-method "GET") (url-mime-accept-string "application/citeproc+json") (json-object-type (quote plist)) (json-data)) (save-current-buffer (set-buffer (url-retrieve-synchronously (concat "http://dx.doi.org/" doi))) (setq json-data (buffer-substring url-http-end-of-headers (point-max))) (if (string-match "Resource not found" json-data) (progn (browse-url (concat "http://dx.doi.org/" doi)) (error "Resource not found.  Opening website")) (json-read-from-string json-data))))
  doi-utils-get-json-metadata("10.1021/jp511426q")
  (let* ((results (doi-utils-get-json-metadata doi)) (type (plist-get results :type))) (or (-some (function (lambda (g) (funcall g type results))) doi-utils-bibtex-type-generators) (message "%s not supported yet\n%S." type results)))
  doi-utils-doi-to-bibtex-string("10.1021/jp511426q")
  (insert (doi-utils-doi-to-bibtex-string doi))
  doi-utils-insert-bibtex-entry-from-doi("10.1021/jp511426q")
  (if (search-forward doi nil t) (message "%s is already in this file" doi) (goto-char (point-max)) (insert "\n\n") (doi-utils-insert-bibtex-entry-from-doi doi) (save-buffer))
  (save-current-buffer (set-buffer (find-file-noselect bibfile)) (goto-char (point-min)) (if (search-forward doi nil t) (message "%s is already in this file" doi) (goto-char (point-max)) (insert "\n\n") (doi-utils-insert-bibtex-entry-from-doi doi) (save-buffer)))
  (progn (save-current-buffer (set-buffer (find-file-noselect bibfile)) (goto-char (point-min)) (if (search-forward doi nil t) (message "%s is already in this file" doi) (goto-char (point-max)) (insert "\n\n") (doi-utils-insert-bibtex-entry-from-doi doi) (save-buffer))))
  (unwind-protect (progn (save-current-buffer (set-buffer (find-file-noselect bibfile)) (goto-char (point-min)) (if (search-forward doi nil t) (message "%s is already in this file" doi) (goto-char (point-max)) (insert "\n\n") (doi-utils-insert-bibtex-entry-from-doi doi) (save-buffer)))) (set-window-configuration wconfig))
  (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer (find-file-noselect bibfile)) (goto-char (point-min)) (if (search-forward doi nil t) (message "%s is already in this file" doi) (goto-char (point-max)) (insert "\n\n") (doi-utils-insert-bibtex-entry-from-doi doi) (save-buffer)))) (set-window-configuration wconfig)))
  doi-utils-add-bibtex-entry-from-doi("10.1021/jp511426q" "/home/liuzy2014/ref.bib")
  call-interactively(doi-utils-add-bibtex-entry-from-doi record nil)
  command-execute(doi-utils-add-bibtex-entry-from-doi record)
  execute-extended-command(nil "doi-utils-add-bibtex-entry-from-doi")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by liuzy** [comment]
the following is my init.el

(add-to-list 'load-path "~/.emacs.d/f")
(add-to-list 'load-path "~/.emacs.d/s")
(add-to-list 'load-path "~/.emacs.d/org-ref")
(add-to-list 'load-path "~/.emacs.d/dash")
(add-to-list 'load-path "~/.emacs.d/hydra")
(add-to-list 'load-path "~/.emacs.d/key-chord")
(add-to-list 'load-path "~/.emacs.d/parsebib")
(add-to-list 'load-path "~/.emacs.d/async")
(add-to-list 'load-path "~/.emacs.d/helm")
(add-to-list 'load-path "~/.emacs.d/helm-core")
(add-to-list 'load-path "~/.emacs.d/helm-bibtex")

(require 'org-ref)
(setq reftex-default-bibliography '("~/ref.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "~/notes.org"
      org-ref-default-bibliography '("~/ref.bib")
      org-ref-pdf-directory "~/bibtex-pdfs/")

**Comment by liuzy** [comment]
When I install org-ref from melpa,there was an error message:
"org-ref-ivy-bibtex.el:26:1:Error: Cannot open load file: no such file or directory, swiper"

Does this matter the result of doi-utils?

Besides, I want to have a try of your emacs configuration, and hope to find the reason.

**Comment by jkitchin** [comment]
I am totally baffled. I have tried fresh installs of jmax and the melpa org-ref in a vanilla emacs, and they all work fine for me. You can fix teh swiper error by adding  (add-to-list 'load-path "~/.emacs.d/swiper") (assuming swiper is installed), but it should not be related to the doi-utils issue.

I wonder if it is related to the dx.doi.org site and what information it is giving you. I see stuff like  (error "Resource not found. Opening website"))  in your traceback which means you aren't getting json data back from the website.

Can you try this code block on a few DOIs:

#+BEGIN_SRC emacs-lisp
(doi-utils-get-json-metadata "10.1007/978-3-642-02463-4_20")
#+END_SRC

change the DOI to some that are causing you problems.

**Comment by jkitchin** [comment]
It looks like you are getting an empty http response buffer:

buffer-substring(nil 1)
  (setq json-data (buffer-substring url-http-end-of-headers (point-max)))

In other words, url-http-end-of-headers is set to nil, and (point-max) is 1, which suggests something is wrong with the http request. I don't know what though. ;(

**Comment by jkitchin** [comment]
Are you still having this issue?

**Comment by liuzy** [comment]
So sorry for the late reply !
I am on a business trip these days, and I will test what you said when I get back.
I doubt that maybe it is something wrong with my computer system, however everything of org-ref goes well except doi-utils. A puzzled problems ^-^

Thank you very much for your patient !

**Comment by liuzy** [comment]
It suddenly works well ^_^ 
But I did nothing on it, I think it was something wrong with the dx.doi.org website.

**Comment by Nibodhika** [comment]
The problem appeared on my machine as well, however it's a little different for me as the debug on doi doesn't point at anything wrong.

```doi-add-bibtex-entry 10.1021/jp511426q``` returns:

```
doi-utils-doi-to-bibtex-string: Wrong type argument: integer-or-marker-p, nil
```

```org-ref-debug``` returns

```
#+TITLE: org-ref debug

org-ref: Version 1.0.0

* Variables
1. org-ref-bibliography-notes: ~/Dropbox/bibliography/notes.org (exists t)
2. org-ref-default-bibliography: (~/Dropbox/bibliography/references.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: ~/Dropbox/bibliography/bibtex-pdfs/ (exists t)

* System
system-type: System: gnu/linux
system-configuration: x86_64-unknown-linux-gnu
window system: Window system: x
Emacs: GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.7)
 of 2017-02-07
org-version: 8.2.10

* about org-ref
org-ref installed in /home/nibodhika/.emacs.d/elpa/org-ref-20170301.722/org-ref.elc.

** Dependencies
helm-bibtex /home/nibodhika/.emacs.d/elpa/helm-bibtex-20170227.608/helm-bibtex.elc

* org-ref-pdf (loaded: t)
system pdftotext: /usr/bin/pdftotext
You set pdftotext-executable to pdftotext (exists: /usr/bin/pdftotext)

* org-ref-url-utils (loaded: nil)

* export variables
org-latex-pdf-process:
("pdflatex -interaction nonstopmode -output-directory %o %f" "bibtex %b" "pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f")
```

```doi-utils-debug 10.1021/jp511426q``` returns:

```
doi:10.1021/jp511426q

* JSON
((indexed
  (date-parts .
              [[2016 11 27]])
  (date-time . "2016-11-27T21:57:21Z")
  (timestamp . 1480283841923))
 (reference-count . 52)
 (publisher . "American Chemical Society (ACS)")
 (issue . "9")
 (funder .
         [((DOI . "10.13039/100000078")
           (name . "Division of Materials Research")
           (doi-asserted-by . "publisher")
           (award .
                  ["DMR 0843934"]))
          ((DOI . "10.13039/100006151")
           (name . "Basic Energy Sciences")
           (doi-asserted-by . "publisher")
           (award .
                  ["DE-SC0004031"]))])
 (content-domain
  (domain .
          [])
  (crossmark-restriction . :json-false))
 (short-container-title .
                        ["J. Phys. Chem. C"])
 (cited-count . 0)
 (published-print
  (date-parts .
              [[2015 3 5]]))
 (DOI . "10.1021/jp511426q")
 (type . "journal-article")
 (created
  (date-parts .
              [[2015 2 10]])
  (date-time . "2015-02-10T03:10:55Z")
  (timestamp . 1423537855000))
 (page . "4827-4833")
 (source . "CrossRef")
 (title . "A Linear Response DFT+UStudy of Trends in the Oxygen Evolution Activity of Transition Metal Rutile Dioxides")
 (prefix . "http://id.crossref.org/prefix/10.1021")
 (volume . "119")
 (author .
         [((given . "Zhongnan")
           (family . "Xu")
           (affiliation .
                        []))
          ((given . "Jan")
           (family . "Rossmeisl")
           (affiliation .
                        []))
          ((given . "John R.")
           (family . "Kitchin")
           (affiliation .
                        []))])
 (member . "http://id.crossref.org/member/316")
 (container-title . "The Journal of Physical Chemistry C")
 (original-title .
                 [])
 (deposited
  (date-parts .
              [[2016 9 1]])
  (date-time . "2016-09-01T17:48:23Z")
  (timestamp . 1472752103000))
 (score . 1.0)
 (subtitle .
           [])
 (short-title .
              [])
 (issued
  (date-parts .
              [[2015 3 5]]))
 (alternative-id .
                 ["10.1021/jp511426q"])
 (URL . "http://dx.doi.org/10.1021/jp511426q")
 (ISSN .
       ["1932-7447" "1932-7455"])
 (citing-count . 52)
 (subject .
          ["Energy(all)" "Physical and Theoretical Chemistry" "Electronic, Optical and Magnetic Materials" "Surfaces, Coatings and Films"]))
```


So it's weird because it seems it's getting the data but something fails afterwards. Also dnd is not working but I didn't expected it to since I'm on linux. Crossref also seems to find the article but gives the same error when trying to import.
