### ISSUE TITLE
Feature Request: Counting words in org manuscripts

### ISSUE THREAD

**Issue by prtkm** [jkitchin/org-ref#151]
Hi John,

Is there a feature (can there be a feature) in org-ref/jmax that can count the number of words in the a manuscript, but not count cite links as words? For now, I have been using M-x count-words on the region I want, but it overestimates the number of words in the document. For example, cite:ertl-2008-react-at-surfac,norskov-2011-densit,sauer-2014-model-catal, is counted as 13 words. I believe that if there was a way to do it, it would come in handy in writing documents with a word limit, like letters.

Prateek

**Comment by jkitchin** [comment]
Nice idea. I added ox-manuscript-texcount to ox-manuscript in jmax. By default it uses tex-count-words in Emacs, and with C-u it uses texcount if it is installed. try it out and let me know if it seems reasonably accurate.

**Comment by prtkm** [comment]
I tried it out. It looks like it is working fine with the prefix argument. 

The default doesn't work though - it counts the header stuff in the tex buffer, and also does not exclude what is in the \cite{}. This means it just ends up being equivalent to running M-x tex-count-words directly on the org file, plus the extra words in the tex header. 

You could probably just make the texcount version the default, and just run tex-count-words directly on the selected region in the org-file as fallback (or just remove the fallback altogether).

**Comment by prtkm** [comment]
How about this:

(defun ox-manuscript-texcount (&optional arg)
  "Use texcount to estimate words in an org-file if it exists.
Fall back to `tex-count-words'"
  (interactive "P")
  (if (executable-find "texcount")
    (let ((f (org-latex-export-to-latex)))
      (shell-command
       (concat "texcount "
	       "-unicode "
	       "-inc "
	       (shell-quote-argument f))))
    (message (concat "Warning: texcount not found. Word estimate does not exclude cite/ref commands. "
	     (tex-count-words (region-beginning) (region-end))))))

**Comment by jkitchin** [comment]
This feature is now in jmax/ox-manuscript https://github.com/jkitchin/jmax/pull/68
