### ISSUE TITLE
How do you cite a page or several pages? 

### ISSUE THREAD

**Issue by paynito** [jkitchin/org-ref#153]
ctrl-c ]   is working well now.  I can insert 

     cite:Twain1884

But how do I reproduce 

    \cite[40-45]{Twain1884}    or
    \cite[This part was funny.][40-45]{Twain1884}

?  Thank you again for a great tool.

**Comment by jkitchin** [comment]
You can use [[cite:Twain1884][40-45]] and [[cite:Twain1884][This part was funny.::40-45]]

**Comment by paynito** [comment]
Thanks, so it's better to type those and not use the helm popup

    ctrl-c ]  twain <return> 

functionality?  i.e. the popup doesn't have a way to easily insert [40] after you have used it to produce a green underlined

    cite:Twain1884

Backspacing changes this to

   cite:Twain188

which is really 

    [[cite:Twain188]]

It would be nice to backspace once and type the [40]] after using the ctrl-c ] insertion.  Thank you for the quick reply.

**Comment by jkitchin** [comment]
You could use org completion. Eg ctrl-c ctrl l   That will prompt for a
type then key then description.

On Sunday, March 13, 2016, paynito <notifications@github.com> wrote:

> Thanks, so it's better to type those and not use the helm popup
>
> ctrl-c ]  twain <return>
>
> functionality? i.e. the popup doesn't have a way to easily insert [40]
> after you have used it to produce a green underlined
>
> cite:Twain1884
>
> Backspacing changes this to
>
> cite:Twain188
>
> which is really
>
> [[cite:Twain188]]
>
> It would be nice to backspace once and type the [40]] after using the
> ctrl-c ] insertion. Thank you for the quick reply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/153#issuecomment-195919009>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
