### ISSUE TITLE
remove package \usepackage{fixltx2e}

### ISSUE THREAD

**Issue by paynito** [jkitchin/org-ref#154]
I get a message if I compile the .tex that is generated by org-ref with

    ctrl-c ctrl-e l o   

It says that the package fixltx2e is now included in the latex kernel and I don't need it.  Where would I tell my .el file not to include this package?  It seems like this is the section.

    (require 'dash)
    (setq org-latex-default-packages-alist
          (-remove-item
           '("" "hyperref" nil)
           org-latex-default-packages-alist))

    ;; Append new packages
    ;;(add-to-list 'org-latex-default-packages-alist '("" "natbib" "") t)

    (add-to-list 'org-latex-default-packages-alist
                  '("linktocpage,pdfstartview=FitH,colorlinks,
    linkcolor=blue,anchorcolor=blue,
    citecolor=blue,filecolor=blue,menucolor=blue,urlcolor=blue
         "hyperref" nil)
           t)`

I have commented out the line 

    ;;(add-to-list 'org-latex-default-packages-alist '("" "natbib" "") t)

because I use Chicago Footnotes called from the .org.  

    #+LATEX_HEADER: \usepackage[notes,backend=biber]{biblatex-chicago}
    #+LATEX_HEADER: \makeatletter
    #+LATEX_HEADER: \def\cms@choose{cms}
    #+LATEX_HEADER: \makeatother

(Lines 2-4 are related to a recent change that broke biblatex-chicago [stackexchange](http://tex.stackexchange.com/questions/298398/impossible-to-build-document-with-biblatex-chicago/298743#298743). Without them the .tex gets doesn't compile.)
How could I move these lines from my .org to my .el?

**Comment by jkitchin** [comment]
Check the value of org-latex-default-packages-alist

If you are using jmax, this is defined on line 348 of jmax-org.el

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by paynito** [comment]
my .emacs.d/elpa has these packages.  Should I install the jmax package for easier org to latex export config?

    org-bullets-20140918.1137
    org-plus-contrib-20160307
    org-pomodoro-20151217.553
    org-present-20141109.1756
    org-ref-20160307.544
    org-ref-readme.txt
    org-repo-todo-20160307.1029

**Comment by jkitchin** [comment]
Probably not (although we use it). You can just put in your init files what
defaults you want.

None of those packages you list should affect the package list I guess.

On Sunday, March 13, 2016, paynito <notifications@github.com> wrote:

> my .emacs.d/elpa has these packages. Should I install the jmax package for
> easier org to latex export config?
>
> org-bullets-20140918.1137
> org-plus-contrib-20160307
> org-pomodoro-20151217.553
> org-present-20141109.1756
> org-ref-20160307.544
> org-ref-readme.txt
> org-repo-todo-20160307.1029
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/154#issuecomment-195916470>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
This isn't really an org-ref issue, so I am closing this one.
