### ISSUE TITLE
org-ref-make-org-link-cite-key-visible and org-agenda: bug?

### ISSUE THREAD

**Issue by miguelazo82** [jkitchin/org-ref#155]
When rebuilding org-mode agenda buffer (e.g. moving forward, backward in it)  
I constantly get this error message: 

org-ref-make-org-link-cite-key-visible: Args out of range: #<buffer *Org Agenda*>, 11775, 11793

As far as I can see the agenda is still functional.  The error is new, and I cannot see how this would have to do with my setup.

**Comment by jkitchin** [comment]
I haven't seen this before. Any chance there is a cite link in your agenda?

**Comment by miguelazo82** [comment]
I took everything out of my diary file now and only and only left 
entries from 2011 (meaning it has not changed since then...). The error 
persists.

No links. I used to have cite links in the agenda (added thesis files 
for todos), and this was never an issue.

(Checking while writing...):  I now found something:  this happens 
(only? I think so) with entries containing time spans
e.g.:    <2011-12-15 Thu>--<2011-12-18 Sun>

What this has to do with org-ref I do not understand at all - but 
org-ref is mentioned in the error message...
No urgency at all; I just found strange that I get the error message 
(plus an emacs screen flash), but apart from that the agenda works fine...

**Comment by jkitchin** [comment]
Hm. There is a function in org ref that advises the org-activate-bracket-links function. I can't reproduce the error on my end though. There haven't been any recent changes I am aware of that would cause this though.

**Comment by jkitchin** [comment]
I can kind of see a possibility for this, but I can't figure out a test or how to fix it. I guess you have a bracket link in your agenda. The org-ref function you mentioned is run after that link is activated. In theory, there is match-data that is looked at, and when it matches a cite regex, the invisible property is removed, and the cite color is added. I guess this is leaky and the function gets to the property change when it shouldn't, and hence the error. I doubt it is the dates, I think this applies to [[type links]].

**Comment by miguelazo82** [comment]
sorry for the late response.

I checked again using only one agenda file, with the following entries:

* Only this one: working fine
  <2016-03-15 Tue>

* Adding this one: bug
<2016-03-16 Wed>--<2016-03-20 Sun>

I cannot say exactly since which update it is like that, because prior 
to updating last week I at least did not update for ten days.

**Comment by jkitchin** [comment]
This looks like an issue org 8.3.4. I don't
I just pushed a klugey fix that probably fixes it (by not running in *Org Agenda*).

**Comment by miguelazo82** [comment]
This fixes it, thank you.  I'll close this...
