### ISSUE TITLE
Warning (emacs): Possible archaic use of (hi-lock-mode)

### ISSUE THREAD

**Issue by icymist** [jkitchin/org-ref#16]
Setup:

- Emacs: 24.4.1/24.3.x
- Org-mode: 8.2.10
- Org-ref: d060f46b4

Issue:
Unnecessary warning message.

```
Warning (emacs): Possible archaic use of (hi-lock-mode).
Use (global-hi-lock-mode 1) in .emacs to enable hi-lock for all buffers,
use (hi-lock-mode 1) for individual buffers.  For compatibility with Emacs
versions before 22 use the following in your init file:

        (if (functionp 'global-hi-lock-mode)
            (global-hi-lock-mode 1)
          (hi-lock-mode 1))
```

Code responsible: in `org-ref.el`
```
(when org-ref-colorize-links
  (highlight-regexp org-ref-cite-re 'org-ref-cite-face)
  (highlight-regexp org-ref-label-re 'org-ref-label-face)
  (highlight-regexp org-ref-ref-re 'org-ref-ref-face))
```

`(global-hi-lock-mode 1)` before the piece of above code does NOT lead to the warning, but same code after the piece of code leads to the error message.

**Comment by jkitchin** [comment]
Thanks for the suggestion! I added (global-hi-lock-mode 1) and it seems to make the warning go away.

**Comment by icymist** [comment]
My intention was not to suggest, but to point out there was an issue. I am not sure if the (global-hi-lock mode 1) option is the best option to follow as obviously it enables it globally. But, anyways ...

**Comment by jkitchin** [comment]
fair enough. I pushed a way to make it buffer local, when colorize links is desired. Does it work for you still?

**Comment by icymist** [comment]
I think it is fixed. No annoying warnings anymore.
