### ISSUE TITLE
Purpose of the org-ref notes file?

### ISSUE THREAD

**Issue by brittAnderson** [jkitchin/org-ref#160]
This isn't an issue so much as a question. What did you envision the purpose of the notes.org file that is created when importing? What are the todo's to remind you of? I realize this may be a matter of personal practice, but I was curious what your design goal was in adding this or how people are making productive use of it? Personally, I am happy to add what notes I have to the bibtex file itself, but wanted to learn what I might be missing.Thanks.

**Comment by jkitchin** [comment]
At one point, the TODOs served the function of reminding me to read the papers, or refile the notes under categories. My notes file is somewhat unwieldy though, and I am stopped using it that way. I kind of prefer the helm-bibtex model of one file per bibtex entry for notes now. But I am even moving away from that, and looking forward to the day where I can just search all my org files for paragraphs that cite an entry ;)
