### ISSUE TITLE
support for arxiv pdfs

### ISSUE THREAD

**Issue by mhlr** [jkitchin/org-ref#161]
The support for journal pdfs is beautiful. However, it does not appear to work for arxiv pdfs. I have a large collection of arxiv pdfs that I would like to import. If it could work like it does for journal papers that would be brilliant.

**Comment by jkitchin** [comment]
Do you know if the pdfs have the arxiv ID in them somewhere? If not it is probably impossible to do.

**Comment by nelson-liu** [comment]
This would be great! I do believe they have an arxivID.
E.g. http://arxiv.org/pdf/1409.7985.pdf has the link http://arxiv.org/abs/1409.7985 on arxiv, using `1409.7985` should work right? The arxiv ID is on the side of the first page.

**Comment by jkitchin** [comment]
It looks possible. Here is the basic framework to get it done:

```
#+BEGIN_SRC emacs-lisp
(with-temp-buffer
  (insert (shell-command-to-string (format "%s %s -"
					   pdftotext-executable
					   "~/Desktop/1409.7985.pdf")))
  (goto-char (point-min))
  (let ((matches '()))
    (while (re-search-forward "arxiv:\\(.*?\\..*?\\)v" nil t)
      ;; I don't know how to avoid a trailing . on some dois with the
      ;; expression above, so if it is there, I chomp it off here.
      (let ((m (match-string 1)))
	(cl-pushnew m matches :test #'equal)
	))
    matches))
#+END_SRC
```

#+RESULTS:
| 1409.7985 |


```
#+BEGIN_SRC emacs-lisp
(arxiv-get-bibtex-entry (arxiv-get-bibliographic-code "1409.7985"))
#+END_SRC
```

#+RESULTS:
#+begin_example

@ARTICLE{2014arXiv1409.7985S,
   author = {{Sim}, Y. and {Routledge}, B. and {Smith}, N.~A.},
    title = "{The Utility of Text: The Case of Amicus Briefs and the Supreme Court}",
  journal = {ArXiv e-prints},
archivePrefix = "arXiv",
   eprint = {1409.7985},
 primaryClass = "cs.CL",
 keywords = {Computer Science - Computation and Language, Computer Science - Artificial Intelligence, Computer Science - Computer Science and Game Theory, Computer Science - Learning},
     year = 2014,
    month = sep,
   adsurl = {http://adsabs.harvard.edu/abs/2014arXiv1409.7985S},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

#+end_example

**Comment by nelson-liu** [comment]
@jkitchin I'm trying to implement this into my version of org ref, but when running `(arxiv-get-bibtex-entry (arxiv-get-bibliographic-code "1409.7985"))`, I get the error `eval-region: Symbol's function definition is void: arxiv-get-bibtex-entry`. Where is arxiv-get-bibtex-entry defined?

Thanks!

**Comment by jkitchin** [comment]
It should be in org-ref-arxiv.el

You might need to require it.

https://github.com/jkitchin/org-ref/blob/master/org-ref-arxiv.el

On Tuesday, June 7, 2016, Nelson Liu <notifications@github.com> wrote:

> @jkitchin <https://github.com/jkitchin> I'm trying to implement this into
> my version of org ref, but when running (arxiv-get-bibtex-entry
> (arxiv-get-bibliographic-code "1409.7985")), I get the error eval-region:
> Symbol's function definition is void: arxiv-get-bibtex-entry. Where is
> arxiv-get-bibtex-entry defined?
>
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/161#issuecomment-224418393>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABiRVlVBZpaZX3RoPb9L1hEznqXbbT0kks5qJeDXgaJpZM4Hxst4>
> .
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by nelson-liu** [comment]
ah ok, thanks! How would I go about adding arxiv as a source for `doi-utils-add-entry-from-crossref-query`? Sorry, I'm quite the elisp neophyte.

**Comment by jkitchin** [comment]
I am not sure that is the place to do that. Does crossref return arxiv results? Can you post an example query here that results in something you want to do?

**Comment by nelson-liu** [comment]
Ah, you're right; I completely (and stupidly) forgot that `doi-utils-add-entry-from-crossref-query` uses crossref to find doi's. I suppose I just want to query arxiv for bibtex similar to how `doi-utils-add-entry-from-crossref-query` does? `doi-utils-add-entry-from-arxiv-query` if you will.

**Comment by jkitchin** [comment]
This package https://github.com/cpitclaudel/biblio.el has quite nice support for search arxiv (and others).

You can set it up to insert entries to your bibliographies like this:

That is what I would do.
```
(define-key biblio-selection-mode-map (kbd "o") #'org-ref-biblio-arxiv)

(defun org-ref-biblio-arxiv (&optional arg)
  (interactive)
  (biblio--selection-copy)
  (with-current-buffer (find-file-noselect (completing-read
					    "Bibfile: "
					    org-ref-bibliography-files
					    nil t
					    (car org-ref-bibliography-files)))
    (goto-char (point-max))
    (yank)
    (insert "\n\n")
    (org-ref-bibtex-previous-entry)
    (org-ref-clean-bibtex-entry)))
```

**Comment by kirk86** [comment]
Hi sorry for jumping in your discussions. I just wanted to ask a question since I'm new to `org-ref` and probably `biblio`. @jkitchin Thank you for the setup to work with `arxiv` really a must for me since most of the papers I use come from there. 

If I may just ask one question. How do I make the `org-ref` rename the pdf file with the citation key.  Do I have to make some kind of special configuration to the `org-ref` or `biblio`?

Thanks again!

**Comment by jkitchin** [comment]
org-ref supports dragging a pdf onto a bib file, and if it finds a doi, it tries to add an entry. I guess arxiv pdfs do not have a doi with them.

Do you download the pdf manually? if so, you should probably manually rename them.

**Comment by kirk86** [comment]
@jkitchin  Thank you for your reply. Yes, usually I download them manually. (How else would you download them, automatically?)

Indeed, as you already mentioned the drag and drop support doesn't work for arxiv because it looks for doi and most arxiv papers have ids not doi. 

just to mention something that I came across is that the above configuration for arxiv returns an error regarding `Symbol's function definition is void:`. Does it work for you guys?

**Comment by mhlr** [comment]
Arxiv pdf urls look like https://arxiv.org/pdf/1308.0010.pdf
