### ISSUE TITLE
error exporting file to pdf 

### ISSUE THREAD

**Issue by vicco** [jkitchin/org-ref#162]
I can't get references and bibliography right when exporting from org-mode to pdf i.e. C-c C-e l p However, the file exports correctly to html
I'm adding a test file so you can reproduce the error (renamed with txt) and, hopefully, put me in the right track

[testbib.pdf](https://github.com/jkitchin/org-ref/files/182312/testbib.pdf)
[bibred1.bib.txt](https://github.com/jkitchin/org-ref/files/182320/bibred1.bib.txt)
[testbib.org.txt](https://github.com/jkitchin/org-ref/files/182322/testbib.org.txt)

I'm using
GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.18.7)
 of 2016-02-03 on buildhw-05.phx2.fedoraproject.org
org-ref: Version 0.7.0

**Comment by jkitchin** [comment]
What do you have org-latex-pdf-process set to? It looks like you are not
running bibtex to me.


vicco writes:

> I can't get references and bibliography right when exporting from org-mode to pdf i.e. C-c C-e l p However, the file exports correctly to html
> I'm adding a test file so you can reproduce the error (renamed with txt) and, hopefully, put me in the right track
>
> [testbib.pdf](https://github.com/jkitchin/org-ref/files/182312/testbib.pdf)
> [bibred1.bib.txt](https://github.com/jkitchin/org-ref/files/182320/bibred1.bib.txt)
> [testbib.org.txt](https://github.com/jkitchin/org-ref/files/182322/testbib.org.txt)
>
> I'm using
> GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.18.7)
>  of 2016-02-03 on buildhw-05.phx2.fedoraproject.org
> org-ref: Version 0.7.0
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/162


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by vicco** [comment]
Thanks for your answer. You're right. I had no definition for it. I corrected the .init file adding
(setq org-latex-pdf-process
      '("pdflatex %f" "bibtex %b" "pdflatex %f" "pdflatex %f"))
