### ISSUE TITLE
M-x org-ref   : two issues  

### ISSUE THREAD

**Issue by miguelazo82** [jkitchin/org-ref#164]
The org-ref command is nice to check for bad cite / ref links. 

One issue (e.g. presence of a bad link):   if I have parts of my org-mode buffer folded and select the link than the folded tree is not opened and the cursor goes to the headline only.  
Maybe it would be good to automatically unfold the whole buffer or at least the trees containing bad links. Of, course, I could also unfold everything first before running org-ref. 

Second issue: (more annoying, maybe MY setup - even though I have not configured anything conciously): 
When I used org-ref to jump to a bad link, than afterwards I cannot go back to the helm-org-ref menu. If I select it in the ibuffer the menu not functional anymore, meaning I have to recall org-ref.  In a long document (and many bad links) this can become annoying. 
Is this normal or is it my configuration?

**Comment by jagrg** [comment]
@miguelazo82 For your second issue, if I understood you correctly, try `M-x helm-resume`.

For the first issue, I think we need to add `(org-show-entry)`.

**Comment by miguelazo82** [comment]
Second issue: helm-resume   does work, thanks.     But would it be 
possible to leave the helm-buffer open and active when clicking a link?  
For example, I have got 20 bad citations in one file alone, resuming 20 
times is still not ideal...

**Comment by jkitchin** [comment]
If you know how to leave helm open we could probably do it. I don't know of a way though. Why so many bad citations?

**Comment by jkitchin** [comment]
For the first issue, I added (widen) and org-cycle  to org-ref, which should address this issue. And hopefully not add new ones.

**Comment by jagrg** [comment]
@jkitchin Instead of widening the entire buffer, why not do what `helm-org-goto-marker` does?

```elisp
(defun org-ref-goto-marker (marker)
  (switch-to-buffer (marker-buffer marker))
  (goto-char (marker-position marker))
  (org-show-entry))
```

**Comment by jkitchin** [comment]
That is also a good idea. I put that in instead of widening and cycling. Let me know if it works for you.

**Comment by miguelazo82** [comment]
causes for many bad citations:
I still use JabRef and the automatic key generation changed at some 
point (no idea when I did that...); now most bibtex keys are different 
from those used in text.
another issue: when I insert multiple citations in helm (C-j) than the 
entries are not separated by comma - another cause for bad cite links (I 
did not notice this for a long time).

but even without that issue I get many bad ref / cite links just messing 
up things by editing ...

Anyways: if the helm menu cannot stay open than I'm still happy with the 
first issue resolved.  I still have to check if the fix works - I'm on a 
very bad internet connection right now...
