### ISSUE TITLE
org-ref-pdf and pdf-tools

### ISSUE THREAD

**Issue by plantarum** [jkitchin/org-ref#167]
Hi,

I use Emacs' pdf-tools to read PDFs in Linux. I'd like to be able to extract a bibtex entry for pdfs I'm reading, but I'm not sure how to do it from within Emacs. org-ref-pdf looks handy for dragging files into an Emacs window, but what if the pdf is already open in Emacs? Is it possible to use org-ref-pdf to lookup the bibtex entry in this case? I can't drag and drop from one Emacs window to another.

Thanks,

Tyler

**Comment by jkitchin** [comment]
If you have the pdf open, I would highlight the doi in the pdf, and use doi-add-bibtex-entry to add it.

**Comment by plantarum** [comment]
That works, thanks!
