### ISSUE TITLE
Support for CUSTOM_ID and NAME

### ISSUE THREAD

**Issue by nxtruong** [jkitchin/org-ref#173]
First, thank you for making public this great package.
I'm using the latest version of org-ref (20160404), but this issue has been persistent since previous versions.

I usually use the standard CUSTOM_ID property or NAME line to specify custom labels, rather than the `label:` link provided by org-ref. However org-ref doesn't fully support these and has the following current issues:

- When I insert a new reference with org-ref, it can list all CUSTOM_ID labels but none NAME labels. So I have to enter the label manually.
- When my cursor is on a reference link to a CUSTOM_ID label, it can display the correct count number (1), but when I click on it, it can't find (and can't jump to) the label.
- When my cursor is on a reference link to a NAME label, it displays an incorrect count number (0), but when I click on it, it can find and jump to the label.

**Comment by jkitchin** [comment]
I pushed some fixes to this. Let me know if it works better for you.

**Comment by nxtruong** [comment]
Thanks!!! It now works properly for all headers with CUSTOM_ID property. For NAME labels, it works for tables but doesn't work for figures (as links to figure files). A workaround, that is acceptable for me, is to use `label:` links for figures.

For special blocks (such as EXAMPLE), `label:` links are recognized by org-ref but are not exported by orgmode, however I place it. The only way it works for me is to explicitly use `\label`, which is both exported by orgmode as LaTeX code and recognized by org-ref. For instance:

> #+ATTR_LATEX: :environment example
> #+BEGIN_EXAMPLE
>   \label{myexample}
>   Example.
> #+END_EXAMPLE

**Comment by jkitchin** [comment]
Can you post a small example of a figure name that doesn't work?

For example blocks I am pretty sure there is no way to get label links in them to get expanded during export. The contents are used verbatim.

**Comment by jkitchin** [comment]
I added names to the list of labels. It will work fine in org-mode, but a name on a figure does not export as a label in latex, so the refs will not work in that case I think.

**Comment by nxtruong** [comment]
An example of a figure is very simple:

> #+ATTR_LATEX: :width 8cm
> #+CAPTION: Model of a node.
> #+NAME: fig:node-model
> [[file:figs/obn_node_model.pdf]]

which is exported to LaTeX as (the label is included automatically by org-mode):

> \begin{figure}[htb]
> \centering
> \includegraphics[width=8cm]{figs/obn_node_model.pdf}
> \caption{\label{fig:node-model}
> Model of a node.}
> \end{figure}

A reference `ref:fig:node-model` to this figure will be exported properly, and the counting and jumping to label work. The only thing that doesn't work is when I run the command `org-ref-helm-insert-ref-link` to insert a reference, the figure label `fig:node-model` does not show up in the list. I have to type it manually without using helm.

**Comment by jkitchin** [comment]
I can't reproduce either of those on org 8.2.10. 

I insert the ref link with C-u C-c ] and with org-ref-helm-insert-ref-link and it works fine.

Can you try with #+name:  instead? I wonder if there is a case-sensitivity issue.

**Comment by nxtruong** [comment]
It works well now, with both lowercase and uppercase name labels. I had to restart Emacs after updating org-ref for it to work correctly.
Thanks for your prompt response and support.

**Comment by jkitchin** [comment]
great! best wishes.
