### ISSUE TITLE
Compiling a .bib file from bibtex entries in an org file?

### ISSUE THREAD

**Issue by zhongnanxu** [jkitchin/org-ref#176]
My references are contained inside of **separate** bibtex code blocks inside an org document. This is probably similar to the notes.org file, and is shown below. 

`* catalysis`
`** adsorption					       :adsorption:catalysis:`
`*** carbide adsorption						   :carbides:`
`#+BEGIN_SRC bibtex`
`A bunch of bibtex entries so I can see the title and authors quickly.`
`#+END_SRC`
`*** oxide adsorption`

etc...

I aim to use it like a reference manager where I can (in addition to tagging) organize subjects, quickly peruse subjects, and also interact with my bibliography through org-mode (TODOs, etc).

However, I would also like all of these references to be inside the global references.bib file to make use org-ref tools. My apologies if this already exists, but does org-ref contain functionality to quickly construct a .bib file from all bibtex entries in bibtex code blocks in an org file?

**Comment by jkitchin** [comment]
not from bibtex entries. You could add :tangle some-name.bib to each block and use org-babel-tangle to extract them. You could use cite links though and hover the mouse over them or put the cursor on them to see that information.

**Comment by jkitchin** [comment]
You could use something like this:

```
#+BEGIN_SRC emacs-lisp
(defun extract-bibtex-blocks (bibfile)
  "Extract all bibtex blocks in buffer to BIBFILE.
If BIBFILE exists, append, unless you use a prefix arg (C-u), which
will clobber the file."
  (interactive
   (list (ido-read-file-name "Bibfile: " nil nil nil
			     (file-name-nondirectory
			      (concat (file-name-sans-extension
				       (buffer-file-name))
				      ".bib")))))

  (let ((contents ""))
    (when (and (file-exists-p bibfile)
	       (not current-prefix-arg))
      (setq contents (with-temp-buffer
		       (insert-file-contents bibfile)
		       (buffer-string))))

    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "#\\+BEGIN_SRC bibtex" nil t)
	(setq contents
	      (concat
	       contents
	       (org-element-property :value (org-element-at-point))))))

    (with-temp-file bibfile
      (insert contents))))
#+END_SRC
```

**Comment by jkitchin** [comment]
See https://github.com/jkitchin/org-ref/commit/42df48b54014b7266c75f3ec8cf96e0b70e5968a for a solution.
