### ISSUE TITLE
Symbol's function definition is void: helm-bibtex-get-value

### ISSUE THREAD

**Issue by jmburgos** [jkitchin/org-ref#180]
Hi John,
I am a happy user of both org-ref and helm-bibtex.  But for the last couple of days when I try to run helm-bibtex, I get the error message above.  If I remove org-ref, then helm-bibtex works as it is supposed to.  Do you know what could be the issue?
Thanks!

**Comment by jkitchin** [comment]
Helm-bibtex recently changed and org-ref has not caught up yet. It will probably take a few days for me to work through it.

**Comment by jmburgos** [comment]
Ok, thanks.  I will wait for the update.

**Comment by jkitchin** [comment]
It should be updated now. Do you still have the error?

**Comment by jabranham** [comment]
It's working for me now, thanks!

**Comment by jmburgos** [comment]
It is working fine now.  Thanks!

John Kitchin writes:

> It should be updated now. Do you still have the error?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub*


-- 
Julian Mariano Burgos, PhD
Hafrannsóknastofnun/Marine Research Institute
Skúlagata 4, 121 Reykjavík, Iceland
Sími/Telephone : +354-5752037
Bréfsími/Telefax:  +354-5752001
Netfang/Email: julian@hafro.is
