### ISSUE TITLE
helm-bibtex-find-pdf-in-library definition void

### ISSUE THREAD

**Issue by ciskakemper** [jkitchin/org-ref#181]
Hello John,

I have installed org-ref and helm-bibtex, and I am able to insert citations into my org-mode files, by selecting from my bibtex file through helm-bibtex, that come out like cite:bibtexkey. I can also see the reference when my cursor is on the link (in the mini-window at the bottom), and when I hover over the link with the mouse, but when I try to click on it to go to the entry again, an error message gets flashed very quickly that the helm-bibtex-find-pdf-in-library definition is void. I have tried finding the answer elsewhere, but to no avail. So, I am sorry to bother you with this, but perhaps you can help? Note that I get this behaviour for any link, regardless of whether a pdf is associated with the entry or not.

Here is how I currently appended my .emacs file:

    (setq org-ref-bibliography-notes "~/org/notes.org"
          org-ref-default-bibliography '("~/Dropbox/Library/ciska.bib")
          org-ref-pdf-directory "~/Dropbox/Library/bib/")

    (setq helm-bibtex-bibliography "~/Dropbox/Library/ciska.bib")
    (setq helm-bibtex-library-path "~/Dropbox/Library/bib")
    (setq helm-bibtex-notes-path "~/Dropbox/Library/notes")

    (require 'org-ref)
    (require 'org-ref-arxiv)

I have tried permutations of this, including commenting out the helm-bibtex stuff, but nothing seems to work. Any ideas?

Thanks!

**Comment by autosquid** [comment]
I think it's out of the same reason in https://github.com/jkitchin/org-ref/issues/180

**Comment by ciskakemper** [comment]
That might be the case indeed. It sounds like I managed to start using this org-ref/helm-bibtex just at the wrong time.

Thanks!

**Comment by jkitchin** [comment]
The fixes for this and #180 should be pushed now. You need to make sure you have helm-bibtex 2.0 or later installed. Let me know if it works now.

**Comment by rytis-paskauskas** [comment]
Hello, 
It seems to be working again, with the latest version of helm-bibtex.
