### ISSUE TITLE
pdf-tools as default option

### ISSUE THREAD

**Issue by rytis-paskauskas** [jkitchin/org-ref#184]
Hello,

with helm-bibtex without org-ref (and pdf-tools enabled) the pdfs are rendered with pdf-tools -- the preferred method. If I load org-ref with minimum, only library path, specifications (hence, still only the default pdf-specific stuff) then evince takes over (on Linux). How do I fix that?

Thanks

**Comment by jagrg** [comment]
If you haven't changed `bibtex-completion-pdf-open-function`, it should open with pdf-tools by default using `find-file`. When opening PDFs from links, org-ref uses `org-open-file` instead. You have a few options. The easiest way is probably to set `org-ref-open-pdf-function` to your own function. See `org-ref-open-pdf-at-point` as an example. Alternatively, you can press `C-o` in the helm buffer, which should take you to the next source. The function you need is there.

**Comment by cryoguy** [comment]
After I update the org-ref to current verison, org-ref failed to open the pdf with pdf-tools. I got following error:   Search failed: "^@\\([^^\"@\\&$#%',={}() 	
]*\\)[[:space:]]*[({][[:space:]]*Yamamoto1966[[:space:]]*,"
any advice to fix this??

Tony

**Comment by jagrg** [comment]
@cryoguy How are you trying to open your PDF? What happens if you evaluate this:

`(find-file (concat org-ref-pdf-directory "Yamamoto1966.pdf"))`

**Comment by cryoguy** [comment]
I am using pdf-tools to render pdf files.  It is working fine with helm-bibtex without org-ref.   I am using Arch Linux with the most recent build.  Also I am using bibtex file generated by Mendeley with following format: 

```
@article{Fujishima1972,
abstract = {, Nature 238 (1972) 37–38.},
archivePrefix = {arXiv},
arxivId = {arXiv:1011.1669v3},
author = {FUJISHIMA, AKIRA and HONDA, KENICHI},
doi = {10.1038/238037a0},
eprint = {arXiv:1011.1669v3},
file = {:mnt/2nd`{\_}`BAY/papers/FUJISHIMA, HONDA - 1972 - Electrochemical Photolysis of Water at a Semiconductor Electrode - Nature.pdf:pdf},
isbn = {0028-0836},
issn = {0028-0836},
journal = {Nature},
keywords = {TiO2},
mendeley-tags = {TiO2},
month = {jul},
number = {5358},
pages = {37--38},
pmid = {12635268},
title = {{Electrochemical Photolysis of Water at a Semiconductor Electrode}},
url = {http://www.nature.com/doifinder/10.1038/238037a0},
volume = {238},
year = {1972}
}
```

Following is what I got when evaluating this: `(find-file (concat org-ref-pdf-directory "Yamamoto1966.pdf"))`

`Debugger entered--Lisp error: (error "epdfinfo: Error opening /mnt/2nd_BAY/papersYamamoto1966.pdf:No such file or directory")
  signal(error ("epdfinfo: Error opening /mnt/2nd_BAY/papersYamamoto1966.pdf:No such file or directory"))
  error("epdfinfo: %s" "Error opening /mnt/2nd_BAY/papersYamamoto1966.pdf:No such file or directory")
  pdf-info-query(number-of-pages "/mnt/2nd_BAY/papersYamamoto1966.pdf")
  pdf-info-number-of-pages()
  pdf-cache-number-of-pages()
  pdf-view-goto-page(1)
  pdf-view-mode()
  set-auto-mode-0(pdf-view-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer papersYamamoto1966.pdf> "/mnt/2nd_BAY/papersYamamoto1966.pdf" nil nil "/mnt/2nd_BAY/papersYamamoto1966.pdf" nil)
  find-file-noselect("/mnt/2nd_BAY/papersYamamoto1966.pdf" nil nil nil)
  find-file("/mnt/2nd_BAY/papersYamamoto1966.pdf")
  eval((find-file (concat org-ref-pdf-directory "Yamamoto1966.pdf")) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)`

**Comment by jagrg** [comment]
I'm not sure if this would help, but I think you are missing a slash. Your path should be set to:

`(setq org-ref-pdf-directory "/mnt/2nd_BAY/papers/")`

**Comment by cryoguy** [comment]
@jagrg helm-bibtex does take care of all this.

**Comment by jagrg** [comment]
Are you trying to open the PDF from helm-bibtex or from an org-ref link? What happens when you evaluate this:

`(funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Yamamoto1966")))`

**Comment by cryoguy** [comment]
from org-ref citation link.  
  `(funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Yamamoto1966")))` opens the pdf nicely (with pdf-tools).

**Comment by jagrg** [comment]
Try this:

```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
         (pdf-file (funcall org-ref-get-pdf-filename-function key)))
    (if (file-exists-p pdf-file)
	(funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf key)))
      (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
```

**Comment by cryoguy** [comment]
when I choose `2. open pdf` after click the citation link, I am still getting `No PDF found for Yamamoto1966` as before.   ?

**Comment by jagrg** [comment]
Try this:

```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results)))
    (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf key)))))
```

**Comment by cryoguy** [comment]
Now it is WORKING.  Thank you so much man!

**Comment by jagrg** [comment]
Great. See if this one works as well. It's a bit more complete.

```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (car (bibtex-completion-find-pdf key))))
    (if (file-exists-p pdf-file)
	(funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf key)))
      (message "No PDF found for %s" key))))
```

**Comment by cryoguy** [comment]
@jagrg Yes, it is working!!

**Comment by rytis-paskauskas** [comment]
@jagrg Thank you for your assistance. I need some more of it please.

On my setup, 

(find-file (concat org-ref-pdf-directory "nature04292.pdf"))
opens a file with in the buffer with pdf-tools.

whereas
(funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "nature04292.pdf")))
yields an error with the message:
find-file-noselect: Wrong type argument: stringp, nil

This,
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
         (pdf-file (car (bibtex-completion-find-pdf key))))
    (if (file-exists-p pdf-file)
        (find-file (concat org-ref-pdf-directory key))
      (message "No PDF found for %s" key))))

opens a file with an external viewer. 

When I press C-o in the helm buffer, I find a "open pdf in emacs" and, if I click it, I get the desired result. But it required two clicks too many... Unfortunately the rest of your initial reply is a riddle... Help please...

**Comment by jagrg** [comment]
> whereas
> (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "nature04292.pdf")))
> yields an error with the message:
> find-file-noselect: Wrong type argument: stringp, nil

You need to remove the `.pdf` extension from the key string.

> This,
> (defun my/org-ref-open-pdf-at-point ()
> "Open the pdf for bibtex key under point if it exists."
> (interactive)
> (let* ((results (org-ref-get-bibtex-key-and-file))
> (key (car results))
> (pdf-file (car (bibtex-completion-find-pdf key))))
> (if (file-exists-p pdf-file)
> (find-file (concat org-ref-pdf-directory key))
> (message "No PDF found for %s" key))))
> 
> opens a file with an external viewer. 

I suspect you forgot to assign the new function to `org-ref-open-pdf-function`. See if this helps: `(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)`.

**Comment by rytis-paskauskas** [comment]
With a small modification, it works. 
Thanks, @jagrg!

(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
         (pdf-file (car (bibtex-completion-find-pdf key))))
    (if (file-exists-p pdf-file)
        (find-file (concat org-ref-pdf-directory key ".pdf"))
      (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)

**Comment by jkitchin** [comment]
@jagrg Thanks for you help on this!

**Comment by cryoguy** [comment]
I do not know when did this stop working for me.   I can not open the pdf from its cite link anymore  When I evaluate  (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Yamamoto1966"))),  I got this "find-file-noselect: Wrong type argument: stringp, nil".   any thoughts or help?   Thanks.

**Comment by jkitchin** [comment]
what happens if you run org-ref in the document?

**Comment by cryoguy** [comment]
No PDF found when I run org-ref in file.  Worked fine before.   Thanks for the help.

**Comment by cryoguy** [comment]
This is strange.  (org-ref-get-mendeley-filename key) can correct file and with its path, and the pdf can be rendered correctly with org-open-file; however, following does not work if I run org-ref in file.  It rolls back to key.pdf file name. ??   Please help!!

(defun my-org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (org-ref-get-mendeley-filename key)))
	(if (file-exists-p pdf-file)
	    (org-open-file pdf-file)
	    (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my-org-ref-open-pdf-at-point)

**Comment by jagrg** [comment]
What happens when you run this:

`(find-file (car (bibtex-completion-find-pdf-in-library "Yamamoto1966")))`

**Comment by jagrg** [comment]
I think I know what the issue is. In `org-ref-cite-candidates`, we need to get the correct Mendeley path first, before sending it to `org-ref-open-pdf-function`. Can you try with this to see if it works?

```
(defun org-ref-cite-candidates ()
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-mendeley (org-ref-get-mendeley-filename key))
	 (candidates `(("Quit" . org-ref-citation-at-point)
                       ("Open bibtex entry" . org-ref-open-citation-at-point))))
    (when (file-exists-p pdf-mendeley)
      (cl-pushnew
       '("Open pdf" . (lambda ()
			(funcall org-ref-open-pdf-function)))
       candidates))))
```

**Comment by cryoguy** [comment]
@jagrg (find-file (car (bibtex-completion-find-pdf "Yamamoto1966")))  got error.   

(defun ...) works

**Comment by cryoguy** [comment]
update, only 3 items listed after this: Open pdf, Quit,　Open bibtex entry.    I like to have the old number list back, esp email with attachment one.

**Comment by jagrg** [comment]
Restart emacs to get the list back. This needs to be fixed in the source code. I won't be able to do this today though.

**Comment by cryoguy** [comment]
@jagrg Thanks a lot for the help.

**Comment by cryoguy** [comment]
@jagrg Did you have a chance to fix the source code? when I set (setq org-ref-open-pdf-function 'org-ref-get-mendeley-filename), it sill fails to open the PDF.  Sorry about all these trouble.

**Comment by cryoguy** [comment]
following does not work either.

(defun my-org-ref-open-pdf-at-point ()
"Open the pdf for bibtex key under point if it exists."
(interactive)
(let* ((results (org-ref-get-bibtex-key-and-file))
(key (car results))
(pdf-file (org-ref-get-mendeley-filename key)))
(if (file-exists-p pdf-file)
(org-open-file pdf-file)
(message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my-org-ref-open-pdf-at-point)

**Comment by jagrg** [comment]
I think we both missed `org-ref-get-pdf-filename-function`. Can you try with this:

`(setq org-ref-get-pdf-filename-function 'org-ref-get-mendeley-filename)`

**Comment by cryoguy** [comment]
The option#2 becomes "Open PDF", but still fails to open with following error:  funcall: Wrong number of arguments: (1 . 1), 0

**Comment by cryoguy** [comment]
The following works ((setq org-ref-open-pdf-function 'org-ref-get-mendeley-filename) does NOT work):

(setq org-ref-get-pdf-filename-function 'org-ref-get-mendeley-filename)
(defun my-org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (org-ref-get-mendeley-filename key)))
	(if (file-exists-p pdf-file)
	    (org-open-file pdf-file)
	    (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my-org-ref-open-pdf-at-point)

**Comment by jagrg** [comment]
I suppose `org-ref-get-mendeley-filename` won't work as a script. Can you open the pdf now?

**Comment by cryoguy** [comment]
@jagrg yean, I can open pdf now.  Thanks.

**Comment by cryoguy** [comment]
A recent git-pull broke the code.  I can not open pdf and I can not insert citation.  Please help or advise.

**Comment by jkitchin** [comment]
this looks like a helm-bibtex issue. The function it is looking for is in s.el. Maybe if you add (require 's) to your init file near the top it would go away. I am pretty sure org-ref itself does not use s-blank-str?.

**Comment by cryoguy** [comment]
add (require 's) did not help.   add more thought?  Thanks.  I am in the middle of paper submission

**Comment by jkitchin** [comment]
I can't reproduce this with a fresh install (or my regular version). I can't see how a git pull on org-ref would cause this. Did you also update helm-bibtex? Can you toggle debug on error and post a full traceback?

**Comment by jagrg** [comment]
@cryoguy Your issue is not related to this thread. None of the code above I think uses `s-blank-str?`. In any case, maybe you can track down which commit gives you the error. You can also switch to a previous commit and use that instead. Also, assuming you have a recent version of s, you could add (require 's) also at the end of your init file just to make sure that nothing is overriding the faulty function. Other than that, you could try with a minimum configuration and work your way from there.

**Comment by cryoguy** [comment]
@jagrg  Thanks for your help.  It was an outdated s.el (https://github.com/tmalsburg/helm-bibtex/issues/16).    but, not org-file fail to open pdf at point,  any thought?  thanks a lot.

**Comment by jkitchin** [comment]
That is not a lot of information to work with. What happens when you try to open a pdf at point? any messages, errors?

**Comment by cryoguy** [comment]
It works fine after I disables helm-bibtex.  Thanks.

**Comment by broncodev** [comment]
Hello everyone. I think that I have a similar problem. If I do:
```
M-x org-ref-bibtex-hydra/body p   ;; Open pdf
```
I get the file in an external application.
I get pdf-tools if I do:
```
M-: (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Aboud11")))
```
Any ideas?
org-ref: Version 1.0.0 (git-commit 87f5dd)
emacs 24.4.1
GNU/Linux

I attach my configuration for org-ref :)
[org-ref.el.txt](https://github.com/jkitchin/org-ref/files/1020859/org-ref.el.txt)

**Comment by jagrg** [comment]
What do you have org-file-apps set to?

**Comment by broncodev** [comment]
Hi! Thanks.
I don't really know how to do this formally:
```
M-: org-file-apps
```
```
org-file-apps is a variable defined in `org.el'.
Its value is ((auto-mode . emacs)
 ("\\.mm\\'" . default)
 ("\\.x?html?\\'" . default)
 ("\\.pdf\\'" . default))
```
I tried by changing the `default` to `emacs`, but that did not help (`if: Wrong type argument: stringp, nil`). I don't dare to change it to pdf-tools, because I don't know what I am doing. Thanks again.

**Comment by jagrg** [comment]
That's what I have too. Not sure what the problem is.

Looking at `org-ref-open-bibtex-pdf`, I wonder if we should replace `(org-open-link-from-string (format "[[file:%s]]" pdf))` with `(funcall org-ref-open-pdf-function pdf)`. I'm assuming (find-file "path/to/pdf") opens the pdf in Emacs for you, and (org-open-file "/path/to/pdf") does not?

**Comment by broncodev** [comment]
Even more strange:
`M-: (org-open-file "./Sources/AlastRodrigCalvo07.pdf")`
has no problem
`M-: (find-file "./Sources/AlastRodrigCalvo07.pdf")`
has a glitch if the document is already [open](https://github.com/jkitchin/org-ref/files/1024214/bt.txt). The file opens normally if it is not already loaded. I am starting to believe that this has to do with helm, hydra or bibtex (?). In any case, it seems safer to open with with `funcal`. If you need anything else from my init file, let me know :) . Thanks!

This works for me (Yaay!):
```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results)))
    (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf key)))))
(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
```

I don't want to hijack this forum: where do I ask how to retrieve abstracts directly into the entries with Org-ref? Thank you again :) .

**Comment by broncodev** [comment]
I restarted my computer, and it's still opening with an external application :S

**Comment by broncodev** [comment]
I tried by replacing the function:
> I wonder if we should replace (org-open-link-from-string (format "[[file:%s]]" pdf)) with (funcall org-ref-open-pdf-function pdf)
I get an error:
```funcall: Wrong number of arguments: ((org-ref-bibliography-entry-format org-ref-notes-function org-ref-get-pdf-filename-function org-ref-cite-types t) nil "Open the pdf for bibtex key under point if it exists." (interactive) (let* ((results (org-ref-get-bibtex-key-and-file)) (key (car results)) (pdf-file (funcall org-ref-get-pdf-filename-function key))) (if (file-exists-p pdf-file) (org-open-file pdf-file) (message "no pdf found for %s" key)))), 1```

**Comment by broncodev** [comment]
I changed `(org-open-link-from-string (format "[[file:%s]]" pdf))` to `(find-file pdf)` in `org-ref-core.el`, and it works now. Any chance that this brakes anything else?

**Comment by jagrg** [comment]
You should add the code to your .emacs/init.el file after org-ref, or wrap it with the with-eval-after-load macro. This prevents future upgrades from changing your modifications.

On 25 May 2017, broncodev <notifications@github.com> wrote:

> I changed (org-open-link-from-string (format "[[file:%s]]" pdf)) to (find-file pdf) in org-ref-core.el, and it works
> now. Any chance that this brakes anything else?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by broncodev** [comment]
So, everything works now.
1. installed org-pdfview
2. added this to my init file (to my org-mode configuration):
  ```
   ;; PDF links for org-mode
   (with-eval-after-load "pdf-tools"
     (use-package org-pdfview
       :config
       ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00169.html
       ;; Before adding, remove it (to avoid clogging)
       (delete '("\\.pdf\\'" . default) org-file-apps)
       ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00176.html
       (add-to-list 'org-file-apps
                    '("\\.pdf\\'" . (lambda (file link)
                                      (org-pdfview-open link))))))
   ```   
3. Undid the customization (I had this, I got rid of it):
>   `(org-open-link-from-string (format "[[file:%s]]" pdf))` to `(find-file pdf)`

All of these work:
`C-c j p`
`M-x org-ref-bibtex-hydra/body p`
`M-: (org-open-file "./Sources/AlastRodrigCalvo07.pdf")`
`M-: (find-file "./Sources/AlastRodrigCalvo07.pdf")`
`M-: (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Aboud11")))`

Bliss

**Comment by jkitchin** [comment]
Great! Thanks for sharing your solution!

**Comment by xiaolaoc** [comment]
I come into the same problem.but i am still org-ref with zotero. 
now when I click on the entry which created by C-c ],and then choose open-pdf, I can only open pdf in external pdf application. 


> So, everything works now.
> 
> 1. installed org-pdfview
> 2. added this to my init file (to my org-mode configuration):
> 
> ```
>  ;; PDF links for org-mode
>  (with-eval-after-load "pdf-tools"
>    (use-package org-pdfview
>      :config
>      ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00169.html
>      ;; Before adding, remove it (to avoid clogging)
>      (delete '("\\.pdf\\'" . default) org-file-apps)
>      ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00176.html
>      (add-to-list 'org-file-apps
>                   '("\\.pdf\\'" . (lambda (file link)
>                                     (org-pdfview-open link))))))
> ```
> 
> 1. Undid the customization (I had this, I got rid of it):
> 
> > `(org-open-link-from-string (format "[[file:%s]]" pdf))` to `(find-file pdf)`
> 
> All of these work:
> `C-c j p`
> `M-x org-ref-bibtex-hydra/body p`
> `M-: (org-open-file "./Sources/AlastRodrigCalvo07.pdf")`
> `M-: (find-file "./Sources/AlastRodrigCalvo07.pdf")`
> `M-: (funcall bibtex-completion-pdf-open-function (car (bibtex-completion-find-pdf "Aboud11")))`
> 
> Bliss

but using org-ref with zotero, I have set this
 
(setq bibtex-completion-pdf-field "file")
  (defun my/org-ref-open-pdf-at-point ()
    "Open the pdf for bibtex key under point if it exists."

    (interactive)
    (let* ((results (org-ref-get-bibtex-key-and-file))
           (key (car results))
           (pdf-file (car (bibtex-completion-find-pdf key))))
      (if (file-exists-p pdf-file)
          (org-open-file pdf-file)
        (message "No PDF found for %s" key))))
 (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
 
I don't how to what to set if I want to open the pdf with pdf-tools but not the external application.
