### ISSUE TITLE
multiple pdf folders

### ISSUE THREAD

**Issue by vcurdia** [jkitchin/org-ref#187]
I just learned that in helm-bibtex it is possible to use multiple folders where to store the pdf for the bib entries. Is it possible to do the same in org-ref?

This is useful if there are many pdf in the folder so that you can break them into multiple folders, such as (for example):
BibPDF_AF
BibPDF_GN
BibPDF_OZ

helm-bibtex manuals states
(setq bibtex-completion-library-path '("/path1/to/pdfs" "/path2/to/pdfs"))

I tried something similar in org-ref settings but it didn't work. Here is what I tried:

;; org-ref
(setq org-ref-bibliography-notes "~/Work/Bibliography/Notes.org"
      org-ref-default-bibliography '("~/Work/Bibliography/References.bib")
      org-ref-pdf-directory '("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/"))

;; Helm-bibtex
(require 'helm-bibtex)
(setq helm-bibtex-bibliography '("~/Work/Bibliography/References.bib"))
(setq helm-bibtex-library-path '("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/"))
(setq bibtex-completion-notes-path "~/Work/Bibliography/Notes.org")

with this the org-ref links break down, while direct access to helm-bibtex works fine.

The error message is:
org-ref-get-pdf-filename: Wrong type argument: stringp, ("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/")

**Comment by jagrg** [comment]
Org-ref can open PDFs in `bibtex-completion-library-path`, where you can add additional directories. Is there something else you are trying to do?

**Comment by vcurdia** [comment]
@jagrg my attempts at using multiple bibpdf folders suggest that some, but not all, org-ref functions recognize bibtex-completion-library-path. See the below description of my attempts (it's a long description but I'm trying to give you all of the information, so please bare with me).

(Note that I've just tried again after updating the packages to makes sure, but without that changing any of the outcomes.)

My current setup is:

```
;; see org-ref for use of these variables
(setq org-ref-default-bibliography '("~/Work/Bibliography/References.bib"))
(setq org-ref-pdf-directory "~/Work/Bibliography/BibPDF/")

;; Helm-bibtex
(require 'helm-bibtex)
(setq bibtex-completion-bibliography '("~/Work/Bibliography/References.bib"))
(setq bibtex-completion-library-path '("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/"))
```

In one of my org files I have:
`cite:Walsh2016Chp11`

If Walsh2016Chp11.pdf is in the folder "~/Work/Bibliography/BibPDF/" then the link allows me to open that file. But if I place that file in "~/Work/Bibliography/BibPDF_1/" then the link doesn't work.
Using M-x helm-bibtex allows me to open the pdf regardless of whether it is in any of those two folders.

My understanding is that I need to set the following two variables separately, the first for org-ref and the second for helm-bibtex:
```
org-ref-pdf-directory
bibtex-completion-library-path
```
the one for org-ref only accepts a string with a single path, while the one for bibtex-completion allows for a list of different strings containing different paths.

When I try to set org-ref-pdf-directory to have a list of paths as in 
`(setq org-ref-pdf-directory '("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/"))`
then whenever I click on any cite link produced by org-ref it yields an error message
`org-ref-get-pdf-filename: Wrong type argument: stringp, ("~/Work/Bibliography/BibPDF/" "~/Work/Bibliography/BibPDF_1/")`

If I use the previous setup, in which org-ref-pdf-directory has a single path but bibtex-completion-library-path has a list of paths then the following happens:
1. org-ref links pointing to files in the org-ref-pdf-directory path work as normal
2. org-ref links pointing to files in the paths in bibtex-completion-library-path seem to give me the option to open the pdf, but when I select that option I get the error message that no pdf is found.
3. using directly helm-bibtex works fine and allows me to open the pdf

So this experimentation tells me that org-ref does indeed recognize paths in bibtex-completion-library-path when it is searching for the options to give me when I click on the cite link, but then the org-ref function that actually opens the pdf file only recognizes the path in org-ref-pdf-directory.

Am I doing something wrong, or is there indeed some inconsistency in different functions of org-ref?

**Comment by jkitchin** [comment]
There could be some inconsistencies. I will take a look, but it will probably take me a week or so to track it down.

**Comment by vcurdia** [comment]
ok, thanks

**Comment by jagrg** [comment]
The problem is you need to use bibtex-completion to find the pdf. With `Walsh2016Chp11.pdf` in `"~/Work/Bibliography/BibPDF_1/"`, try this:

```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (car (bibtex-completion-find-pdf key))))
    (if (file-exists-p pdf-file)
	(org-open-file pdf-file)
      (message "No PDF found for %s" key))))
```

**Comment by vcurdia** [comment]
This works perfectly. Now I actually don't need to specify org-ref-pdf-directory. All that I need to specify is bibtex-completion-library-path.

Thank you!
