### ISSUE TITLE
References and export of subtrees

### ISSUE THREAD

**Issue by kjschmid** [jkitchin/org-ref#191]
I am not sure whether to consider this as a bug, but the LaTeX export of the references is not consistent yet.

For my course, I have a single document that contains all lectures, but I usually export the individual lecture notes separately. 

There are three issues:

1. Each subtree to be exported needs to have the bibliographystyle and bibliography commands at the end of the subtree. Otherwise the latex process will not include the references. It would be more convenient if the exporter finds the bibliographystyle and bibliography commands at the end of the file and uses them also for the subtree.

2. If the last subtree of the file is exported, then the bibliographystyle command is included in the resulting LaTeX file, but not the bibliography command and therefore no bibliography is produced in the latex file because Bibtex does not find the .bib file.

3. If I export the whole org file, I have to comment out the bibliography document in each subtree and leave only the last one to avoid the inclusion of multiple identical bibliographies in the resulting PDF document.

I include a simple example that may be used to reproduce the behaviour:

-----
#+TITLE: Test
#+latex_header: \usepackage{natbib}
* First heading

Blind text

* Second heading

The first reference citep:Tajima83

bibliographystyle:unsrt
bibliography:PGR.bib

* Third heading

Another ref citep:Wright:2005p12204

bibliographystyle:unsrt
bibliography:PGR.bib

-----

**Comment by jagrg** [comment]
For points 1 and 3 you have two options. One, you can add an `:export:` tag specifically to the headings you want to export. Two, you can include bibliography (without the .bib extension) and style as a latex header in the org file:

```
#+LATEX_HEADER: \bibliographystyle{unsrt}
#+LATEX_HEADER: \bibliography{PGR}
```

I'm not sure I understand your second point. I don't see why it wouldn't work. It works fine for me.

**Comment by jkitchin** [comment]
I had previously tried an approach to automatically add bibliographies on export here for a slightly different use case: https://github.com/jkitchin/jmax/blob/master/ox-manuscript.el#L537 but it never did exactly what I wanted, and I disabled it.

You can get what you want (at least approximately) like this:

```
(defun preproc (backend)
  (let (bib bibstyle))
  (save-restriction
    (widen)
    (goto-char (point-min))
    (when  (re-search-forward "bibliography:.*" nil t)
      (setq bib (match-string 0)))
    (goto-char (point-min)) 
    (when  (re-search-forward "bibliographystyle:.*" nil t)
      (setq bibstyle (match-string 0))))
  
  (goto-char (point-min))
  (unless  (re-search-forward "bibliographystyle:.*" nil 'mv)
    (insert "\n" bibstyle))

  (goto-char (point-min))
  (unless  (re-search-forward "bibliography:.*" nil 'mv)
    (insert "\n" bib)))

(add-hook 'org-export-before-processing-hook 'preproc)
```

I only did a little testing of this, and it seemed to do what you wanted. It doesn't have any error handling in it, and assumes a single definition of the bibliography and bibliographystyle links. Does this do what you want?

**Comment by jkitchin** [comment]
The second point has to do with some folding code that I introduced to try making the bibliography not get folded up in the last section. It is causing some other issues for me that are a little annoying, so I may end up reverting that behavior.

**Comment by jkitchin** [comment]
Has this been resolved for you? I removed the folding code a while ago.
