### ISSUE TITLE
doi-utils-timestamp-field converted to lowercase

### ISSUE THREAD

**Issue by plantarum** [jkitchin/org-ref#193]
Hi,

I've set `doi-utils-timestamp-field` to `DateAdded`. However, new entries are created with the value `dateadded`. Can this be configured to respect capitalization?

Not a big issue, but before I started using your package I had used the camel-case format, so I'd like to stick to the same for new entries.

Thanks,

Tyler

**Comment by jagrg** [comment]
A quick fix may be to remove `org-ref-sort-bibtex-entry` from `org-ref-clean-bibtex-entry-hook`. Another solution would be to add the function below (or something similar) to the end of the list (`org-ref-clean-bibtex-entry-hook`). I hope it helps.

```
(defun camel-case-timestamp-field ()
  (save-excursion
    (bibtex-beginning-of-entry)
    (when (re-search-forward "dateadded" nil t)
      (replace-match doi-utils-timestamp-field nil t))))
```

**Comment by jkitchin** [comment]
@jagrg what do you think of removing the downcasing from org-ref-sort-bibtex-entry, and making a separate function for that? That one function doesn't need to do both.

**Comment by jagrg** [comment]
I think it's a good idea.

**Comment by jkitchin** [comment]
should be done now. thanks,
