### ISSUE TITLE
Folding problem of headers after References section caused by org-ref

### ISSUE THREAD

**Issue by rkrug** [jkitchin/org-ref#197]
I have a strange situation with a very simple org file:

```
* Data
** CACHE
Some folding headers

* References
bibliographystyle:plainnat
bibliography:asmOptim.bib

* Appendix
\appendix
```

If I fold on the Data header by using TAB, the whole document unfolds,
and I can not unfold the headers References and Appendix. Also,
References only shows the second line (bibliography:asmOptim.bib).

There is no way that I can fold the References and Appendix sections
again, apart from changing to text-mode and back to org-mode.

I don't get any error messages.

The culprit is somewhere in org-ref, because as soon as I load it

````
(use-package org-ref
  :ensure f
  :load-path "~/.emacs.d/org-ref"
)
````

the problem occurs.

**Comment by jkitchin** [comment]
The culprit is indeed org-ref. I had put some code in to try to not fold the bibliography link so you can always see it. I just pushed a fix that disables this code for now.

Shift-tab usually works for me to open everything back up.

In the mean time, you may run these, and it might fix it for you.

```
(ad-remove-advice 'org-end-of-subtree  'after 'always-show-org-footer)
(remove-hook 'org-cycle-hook 'org-ref-show-biblinks)
(remove-hook 'org-occur-hook 'org-ref-show-biblinks)
```

**Comment by rkrug** [comment]
Thanks. I am using org-ref from github, so U=I just updated it. Working perfectly.

Thanks a lot
