### ISSUE TITLE
Select multiple citations not working

### ISSUE THREAD

**Issue by rudolfochrist** [jkitchin/org-ref#198]
This is related to #4 

Hi there,

firstly thanks for this great package. But currently I have this problem, that I can't insert multiple citations. When I mark several citations in Helm (with <kbd>C-SPC</kbd>) those get completely ignored and only the citation at point (or the current line) gets inserted, after hitting <kbd>RET</kbd>.

I'm not sure if this is a bug or if I am doing something wrong here. 

I've tried to reproduce this behaviour with minimal configuration using [these test files](https://gist.github.com/rudolfochrist/d2010d4f7dc963d7b9c8d4ec0105202a) 
(Perhaps the `load-path` has to be adjusted to work on a different machine) and starting Emacs with `emacs -Q -l org-ref-test.el`. 

Following is a GIF what's happening on my system:
![org-ref-test](https://cloud.githubusercontent.com/assets/70550/14859288/c846a1d0-0ca3-11e6-8a43-11277498b894.gif)

Again, there is very likely the chance that I'm doing it all wrong, but nonetheless I though I report it. 

Thank you very much in advance for looking into this. 

Regards,
Sebastian

Emacs Version:
```
GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, NS apple-appkit-1404.34)
of 2016-01-19 on Homebase.local
```

Org Mode Version:
```
Org-mode version 8.3.4 (8.3.4-42-gae73c7-elpa @ /Users/fyi/.emacs.d/elpa/org-20160425/)
```

Org-Ref Version:
```
org-ref: Version 0.8.0 (git-commit 2df793864a9b174aa75408f12c67bdadc4092c61)
```

**Comment by jkitchin** [comment]
I just pushed a fix for this I think. Let me know if a new pull works now.

**Comment by rudolfochrist** [comment]
Thank you. It is working now.
