### ISSUE TITLE
conflicts with helm-bibtex

### ISSUE THREAD

**Issue by rytis-paskauskas** [jkitchin/org-ref#199]
newest versions of `org-ref` and `helm-bibtex`:

with `org-ref` activated, some of `helm-bibtex`'s functionality seems to become corrupted. This includes but may not be limited to helm-bibtex's multiple citations. The command `C-SPC C-SPC ... TAB f3` (insert multiple citations selected by `C-SPC`) inserts only the citation at the cursor. I checked that it works as intended when `org-ref` switched off. This remains an issue with `f1` replaced for `f3`.

**Comment by tmalsburg** [comment]
Just a sidenote, I think you don't need the TAB.  Just select entries and press `f3`.

**Comment by jagrg** [comment]
I think I know what's happening. The problem is org-ref is using `bibtex-completion-insert-citation` instead of `helm-bibtex-insert-citation`. Only the latter uses `helm-marked-cadidates`, so `org-ref-bibtex-completion-actions` needs to be updated.

**Comment by jkitchin** [comment]
@jagrg you might know org-ref better than I do ;) I updated the function names in org-ref-bibtex-completion-actions and pushed it.

**Comment by tmalsburg** [comment]
Without having looked at org-ref's code, yes, this explanation sounds very plausible.

**Comment by rytis-paskauskas** [comment]
The issue remains, sorry...

**Comment by rytis-paskauskas** [comment]
It works now!
