### ISSUE TITLE
Please provide a compiled PDF version of org-ref.org

### ISSUE THREAD

**Issue by olberger** [jkitchin/org-ref#200]
The distribution (on MELPA) contains org-ref.org but it may not compile out of the box (missing additional wos-search tool, or not yet installed org-ref.

It would be convenient to be able to read the doc as a PDF, though.

Hence my request to ship compiled org-ref.pdf too.

Thanks in advance.

**Comment by jkitchin** [comment]
org-ref.org should compile to pdf out of the box from MELPA. If you haven't installed org-ref, the best thing is probably to read it at https://github.com/jkitchin/org-ref/blob/master/org-ref.org. I think we may have had an org-ref.pdf in there at one time, but it doesn't stay up to date with changes to org-ref.org, so if it was there, I took it out.

**Comment by breisfeld** [comment]
When I try to compile the pdf, I get an error related to ```unsrtnat``` (file not found). 
I may be mistaken, but shouldn't there be a ```unsrtnat.el``` file in the ```citeproc``` directory?

**Comment by jkitchin** [comment]
This should be fixed for you now. Does it work now?

**Comment by jkitchin** [comment]
As far as I can tell the org-ref.org file exports to PDF with a vanilla MELPA install.
