### ISSUE TITLE
org-ref can't find doi in PDF and Emacs freezes after M-x doi-add-bibtex-entry

### ISSUE THREAD

**Issue by FrostedPenguin** [jkitchin/org-ref#201]
Hi. I just installed org-ref and tried to do things that you've done in your nice youtube video.

I'm quite new to emacs and Org-mode. Also English is not my first language so I often misunderstood instructions. So this questions might be silly or wrong.
I hope you understand my situation.

I've tested several PDFs and org-ref works good usually.
But sometimes it couldn't find doi in PDFs. 
Is it related with PDF itself? or my emacs configuration problem?

And I tried to used M-x doi-add-bibtex-entry some of doi returns error in minibuffer as below
`error in process filter: Search failed: "<iframe id=\"pdfDocument\" src=\"\\([^\"*\\)\""`

From my opinion, it looks like it failed because of data repository cause some of them requires credit.. and I'm testing these out of my school IP so I can't use some websites. But I want to make sure.

So do you have any idea on these problems?

These are papers that I've used. Org-ref can't find doi both of PDFs and Emacs freezed when I tried to add both. Maybe you can check it out
[paper1](http://onlinelibrary.wiley.com/doi/10.1111/cgf.12256/abstract)
[paper2](http://onlinelibrary.wiley.com/doi/10.1111/j.1467-8659.2012.02093.x/abstract)

**Comment by jagrg** [comment]
It may be that your university doesn't have access to those articles. Are you able to download the articles manually? Maybe `doi-utils-get-wiley-pdf-url` needs a nicer message for when the search fails.

**Comment by jagrg** [comment]
Apparently not all DOIs are treated the same by wiley:

`(doi-utils-get-pdf-url "10.1111/cgf.12256")`
`(doi-utils-get-pdf-url "10.1111/traa.12055")`

This is probably not the best solution, but I was able to bypass the problem by setting the university library url directly.

```elisp
(defvar doi-utils-uni-lib-url nil
  "The university library URL used to access wiley.")

(defun wiley-alt-pdf-url (*doi-utils-redirect*)
  (when (string-match "^http://onlinelibrary.wiley.com" *doi-utils-redirect*)
    (let ((url (progn (doi-utils-get-wiley-pdf-url
		       (replace-regexp-in-string "/abstract" "/pdf" *doi-utils-redirect*))
		      *doi-utils-pdf-url*)))
      (if url url
	(if doi-utils-uni-lib-url
	    (let ((alt-url (replace-regexp-in-string "http://onlinelibrary.wiley.com"
						     (concat doi-utils-uni-lib-url "/doi")
						     (concat *doi-utils-redirect* "pdf"))))
	      (replace-regexp-in-string "abstract" "" alt-url))
	  (message "PDF not found."))))))

(add-to-list 'doi-utils-pdf-url-functions 'wiley-alt-pdf-url)
```

**Comment by jkitchin** [comment]
Wiley is doing some difficult to handle stuff with javascript and redirections. I am not sure what is the best way to handle these issues.
