### ISSUE TITLE
Make org-ref not require helm packages

### ISSUE THREAD

**Issue by jtecca** [jkitchin/org-ref#202]
First off, thanks for this library.  It fills a wonderful need in my workflow.

When I first installed the library, I didn't realize that org-ref requires helm and helm-bibtex when building from MELPA.  Do you think it is feasible for org-ref to not require helm and helm-bibtex explicitly but use whatever competition framework is available?  Is this something that I could submit a PR for?

**Comment by jkitchin** [comment]
There is an ivy-backend in org-ref.  Unfortunately, for now it means you still have to install helm even if you don't use it.

I would consider a pull request, but I would have to think about it. helm has been the default since the beginning, and the installation was made for users with no preference/knowledge otherwise in mind. I don't want them to have to install separate packages just to use org-ref. I could be convinced otherwise though.

**Comment by ericdanan** [comment]
Perhaps a solution would be to add something like this at the beginning of `org-ref-helm-bibtex`:

```
(unless (require 'helm-bibtex nil t)
  (if (yes-or-no-p "Org-ref is setup to use completion library `helm-bibtex', which is not installed. Install?")
      (package-install 'helm-bibtex)
    (error "Please install `helm-bibtex' or choose an alternative completion library")))
```

and similarly for `org-ref-helm-cite` and `org-ref-ivy-bibtex`.

I can send a PR if you want.

Also, I think you would then need to add `parsebib` as a dependency (it is a dependency of `helm-bibtex` but `org-ref.el` also uses it directly).

**Comment by jtecca** [comment]
@ericdanan that's the type of solution I was thinking of.  I haven't had enough time in the past few days to go through the code, so thanks for providing a quick solution.  It seems reasonable to default to helm and helm-bibtex for those who don't have a preference.

@jkitchin thanks for the response.  I wanted to gauge your feelings about this request before going to the trouble of writing the PR.

**Comment by jkitchin** [comment]
I am open minded to it. I would like as much as possible to preserve the
user experience of install org-ref and have a working default probably with
helm.

On Friday, April 29, 2016, jeff tecca <notifications@github.com> wrote:

> @ericdanan <https://github.com/ericdanan> that's the type of solution I
> was thinking of. I haven't had enough time in the past few days to go
> through the code, so thanks for providing a quick solution. It seems
> reasonable to default to helm and helm-bibtex for those who don't have a
> preference.
>
> @jkitchin <https://github.com/jkitchin> thanks for the response. I wanted
> to gauge your feelings about this request before going to the trouble of
> writing the PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/202#issuecomment-215887161>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment]
Do you mean that you would like to get rid of the user interaction of having to answer yes to install helm? In this case I guess one could simply do:

```
(unless (require 'helm-bibtex nil t)
  (message "Org-ref is installing the `helm-bibtex' completion library...")
  (package-install 'helm-bibtex))
```

**Comment by jkitchin** [comment]
I think this would be fine. We can try it out if you want to submit a
pull request.

ericdanan writes:

> Perhaps a solution would be to add something like this at the beginning of `org-ref-helm-bibtex`:
>
> ```
> (unless (require 'helm-bibtex nil t)
>   (if (yes-or-no-p "Org-ref is setup to use completion library `helm-bibtex', which is not installed. Install?")
>       (package-install 'helm-bibtex)
>     (error "Please install `helm-bibtex' or choose an alternative completion library")))
> ```
>
> and similarly for `org-ref-helm-cite` and `org-ref-ivy-bibtex`.
>
> I can send a PR if you want.
>
> Also, I think you would then need to add `parsebib` as a dependency (it is a dependency of `helm-bibtex` but `org-ref.el` also uses it directly).
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/202#issuecomment-215852383


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by ericdanan** [comment]
Sure, I will do it soon.

**Comment by jkitchin** [comment]
We tried for a couple of weeks to separate out an org-ref-ivy, but it did not succeed. I am tabling this effort and staying with one MELPA package for now. If helm is a deal breaker, I would suggest you run org-ref off the git repo and manage the packages yourself. You could use el-get for that.
