### ISSUE TITLE
org-ref-link-message and org-ref-cite-click-helm can't find bibtex @techreport

### ISSUE THREAD

**Issue by billbrod** [jkitchin/org-ref#205]
I figure this is a problem with what bibtex entry types org-ref looks for, but I have several bibtex entries that are `@techreport`s and while I can find them with `org-ref-helm-insert-cite-link`, when I hover over them or click on them (which I'm pretty sure are `org-ref-link-message` and `org-ref-cite-click-helm`), org-ref cannot find them. Hovering over them shows `!!! No entry found !!!`, while clicking on the link returns `Wrong type argument: stringp, nil`. All other cite links work fine and calling `(org-ref-find-bibliograhy)` in that buffer returns the right file, so I assume this is something to do with the `@techreport` type.

Is there a variable that holds a list of allowed bibtex entry types or something similar?

**Comment by jkitchin** [comment]
Is that a legit bibtex type or a biblatex type?

On Wednesday, May 4, 2016, William F. Broderick <notifications@github.com>
wrote:

> I figure this is a problem with what bibtex entry types org-ref looks for,
> but I have several bibtex entries that are @techreports and while I can
> find them with org-ref-helm-insert-cite-link, when I hover over them or
> click on them (which I'm pretty sure are org-ref-link-message and
> org-ref-cite-click-helm), org-ref cannot find them. Hovering over them
> shows !!! No entry found !!!, while clicking on the link returns Wrong
> type argument: stringp, nil. All other cite links work fine and calling
> (org-ref-find-bibliograhy) in that buffer returns the right file, so I
> assume this is something to do with the @techreport type.
>
> Is there a variable that holds a list of allowed bibtex entry types or
> something similar?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/205>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by billbrod** [comment]
I'm not entirely sure: it was the type returned by [Crossref](search.crossref.org) for a paper posted on bioRXiv: [here](http://search.crossref.org/?q=10.1101%2F039354)'s the citation.

I'm guessing it's a biblatex type? The citation from clicking export and bibtex on the bioRXiv page for the paper itself has a type of `@article`.

**Comment by jkitchin** [comment]
If you put this line as the first line of your bibtex file:
% -*- mode:bibtex; eval: (bibtex-set-dialect 'biblatex); -*-

does it work?

**Comment by billbrod** [comment]
No, adding that doesn't change anything.

**Comment by jkitchin** [comment]
techreport is ok, I have a lot of them in my bibtex file too. I wonder if you have some other syntactical error in your bibtex file. Is this a problem with all techreports or just some?

**Comment by billbrod** [comment]
All of them, though I only have 5 techreport entries (out of 500 total entries). I assume it's not a syntactical error because all of the other entries work fine. I recently updated the version of org-ref and helm-bibtex I was using and I think this problem started after that. Unfortunately, I don't remember which version of helm-bibtex I had been using, but I don't think I had updated either since September 2015.

**Comment by jkitchin** [comment]
hm. There was a major update to helm-bibtex recently, and a corresponding update to org-ref. I think those are all worked out now though if you have the latest versions from melpa for them. Maybe you could send me a small org-file and bib-file that reproduces the problem for you.

**Comment by billbrod** [comment]
I just double-checked, and I have the most up-to-date version of org-ref and helm-bibtex. 

I emailed you a small org-file and bib-file, thanks for looking into it!

**Comment by billbrod** [comment]
So after building my emacs build back up, it looks like the issue was setting the `bibtex-dialect` to `biblatex`. I don't understand why that's the case, since I thought techreport was a biblatex entry type, but removing the line `(setq bibtex-dialect "biblatex")` from my init file solves the issue.
