### ISSUE TITLE
fail to insert multiple marked citations 

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#206]
I can not seem to inert multiple citations after marking, only insert the last one where the point is at.  Anyone has this issue before?

**Comment by jkitchin** [comment]
Do you have the latest Melpa version? This was an issue a few commits ago.

On Wednesday, May 4, 2016, cryoguy <notifications@github.com> wrote:

> I can not seem to inert multiple citations after marking, only insert the
> last one where the point is at. Anyone has this issue before?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/206>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by cryoguy** [comment]
Pulled new version and the problem solved.   Thanks!
