### ISSUE TITLE
question about workflow and creation of entry in org-ref-notes file

### ISSUE THREAD

**Issue by stevenbagley** [jkitchin/org-ref#209]
By default, `doi-utils-make-notes-function` creates a minimal entry in the org-ref-notes file. In contrast, `org-ref-open-bibtex-notes` create a "full" entry (with the cite: link and link to pdf). Is there some reason for these to be separate? I've set the former option to run the latter, but I'm wondering if there is a good reason not to do so. Thanks.

**Comment by jkitchin** [comment]
There is probably no good reason. Notes aren't a feature I use much. I (and others) have experimented with a variety of approaches, and that has left some different approaches in the code.

**Comment by nelson-liu** [comment]
@stevenbagley how did you set the former option to run the latter? Sorry, I'm quite the neophyte at elisp but I'm also running into this issue.

**Comment by nelson-liu** [comment]
(but I'd be in support of using `org-ref-open-bibtex-notes` instead of `doi-utils-make-notes-function` by default; it's really cumbersome to have to manually delete the automatically created entry and use `org-ref-open-bibtex-notes` to make a proper one)

**Comment by nelson-liu** [comment]
@stevenbagley nevermind, I thought I had it figured out, but I'm running into circular require issues. Could you share how you set `doi-utils-make-notes-function` to run `org-ref-open-bibtex-notes`?

**Comment by jagrg** [comment]
Does this work?

`(setq doi-utils-make-notes-function 'org-ref-open-bibtex-notes)`

**Comment by jmburgos** [comment]
We actually have a template in org-ref to change the format of the note headers.  For example, I use this:

(setq org-ref-note-title-format "* [[/home/julian/Documents/Refs/%k.pdf][%k]] - %t\n  :PROPERTIES:\n  :Custom_ID: %k\n  :INTERLEAVE_PDF: /home/julian/Documents/Refs/%k.pdf\n  :END:\n")

With this I get a minimal heading with the bibtex key serving as a link to the pdf, the article title, the needed Custom_ID property, and what I need to run the interleave package on that pdf.  I have something similar in helm-bibtex, so notes produced by both packages look the same.  

The only issue is that notes created in org-ref also get an additional line with a cite command and a link to the pdf, which I need to delete by hand.  These are hard-coded in the org-ref-open-bibtex-notes function.  It would be handy to have a way to get rid of this additional line.

**Comment by jkitchin** [comment]
This is probably fixed in 8c2a4f4. For now I just commented out the lines that add the extra stuff. That probably should not be done, since we have a template now. Does that resolve it for you?

**Comment by jmburgos** [comment]
Yes, it works great. Thanks John!

**Comment by jkitchin** [comment]
Great. One day I will delete those commented out lines ;)

**Comment by jmburgos** [comment]
Hi John, 

Org-ref is again adding the cite command and a link to the pdf when creating notes.  I am using version 20170107.1308.  Would you mind taking them out?  People who want to have them can add them in their template.
Thanks!

**Comment by jkitchin** [comment]
What is your note setup? I don't think org-ref is doing that directly, but helm bibtex might be.

See the variables helm-bibtex-notes-template-multiple-files, helm-bibtex-notes-template-one-file

You may also see if org-ref-create-notes-hook is causing the cite to go in. If it is, set that variable to nil or remove the default function in it.

 I have no idea where the pdf link could be coming from.

**Comment by jmburgos** [comment]
Sorry, my bad.  The pdf link does not get added, only the cite: command.  And you are right, it is coming from org-ref-create-notes-hook, which it is defined in org-ref-core.el as

(org-narrow-to-subtree)
   (insert
    (format "cite:%s\n"
	    (org-entry-get
	     (point)
	     "Custom_ID")))))

Setting it to nil removes the citation.

**Comment by jkitchin** [comment]
No problem.
