### ISSUE TITLE
List of Figures

### ISSUE THREAD

**Issue by jagrg** [jkitchin/org-ref#217]
@jkitchin  what do you think of using a simple org link instead of the nested elisp link (see `org-ref-list-of-figures`)? The following works well for the `#+name` field, but I'm not too sure how to get the label field as well (`org-ref-get-labels` might be able to do the job). The other caveat is we need `org-link-frame-setup` set to `(file . find-file)` (instead of `(file . find-file-other-window)`) to avoid creating a separate window.

```diff
1 file changed, 5 insertions(+), 4 deletions(-)
org-ref.el | 9 +++++----

modified   org-ref.el
@@ -1075,11 +1075,12 @@ Ignore figures in COMMENTED sections."
 			 (name (plist-get parent :name)))
 		    (if caption
 			(format
-			 "[[elisp:(progn (switch-to-buffer \"%s\")(goto-char %s)(org-show-entry))][figure %s: %s]] %s\n"
-			 c-b start counter (or name "") caption)
+			 "[[file:%s::%s][Figure %s:]] %s\n"
+			 c-b name counter caption)
 		      (format
-		       "[[elisp:(progn (switch-to-buffer \"%s\")(goto-char %s)(org-show-entry))][figure %s: %s]]\n"
-		       c-b start counter (or name "")))))))))
+		       "[[file:%s::%s][Figure %s:]] %s\n"
+		       c-b name counter caption)
+		      )))))))
```

**Comment by jkitchin** [comment]
Is there something about the current approach that isn't working well?

**Comment by jagrg** [comment]
Nothing in particular. The proposed method feels a lot smoother. It also won't ask users to execute elisp code (I know there's a variable to change that).

**Comment by jagrg** [comment]
BTW setting `org-confirm-elisp-link-function` to nil makes you more vulnerable to malicious code. Unless you expand the link manually, you will never know if the link will run code. Even the documentation recommends not changing this variable (see below). This is what I do (and would assume other as well).

```
Elisp links can be dangerous: just think about a link

     [[elisp:(shell-command "rm -rf ~/*")][Google Search]]

This link would show up in your Org-mode document as "Google Search",
but really it would remove your entire home directory.
Therefore we advise against setting this variable to nil.
```
