### ISSUE TITLE
Cannot follow cite link

### ISSUE THREAD

**Issue by et2010** [jkitchin/org-ref#220]
When cursor is on a cite link, hitting `Enter` did not follow the link as expected. It shows:

```
bibtex-completion-get-entry1: Search failed: "^@\\([^^\"@\\&$#%',={}() 	
]*\\)[[:space:]]*[({][[:space:]]*zaman2007effec_soil_suction[[:space:]]*,"
```
in the message buffer.

**Comment by jkitchin** [comment]
This isn't enough information to be helpful. This is an issue with bibtex-completion-get-entry1 which is part of helm-bibtex.

can you run M-x org-ref-debug  in your org-file and see if any issues are obvious?

FWIW I have never had good luck with _ in my bibtex keys.

**Comment by et2010** [comment]
Here is the debug info:

#+TITLE: org-ref debug

org-ref: Version 0.8.1 (git-commit c2fc02e900341c300d776c87a4227f9e4118ba72)

* Variables
1. org-ref-bibliography-notes: ~/Dropbox/bibliography/notes.org (exists t)
2. org-ref-default-bibliography: (~/Dropbox/bibliography/references.bib) (exists (t)) (listp t)
3. org-ref-pdf-directory: ~/Dropbox/bibliography/bibtex-pdfs/ (exists t)

* System
system-type: System: gnu/linux
system-configuration: x86_64-unknown-linux-gnu
window system: Window system: x
Emacs: GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.3)
 of 2016-05-06 on arojas
org-version: 8.3.4

* about org-ref
org-ref installed in /home/neoarch/.emacs.d/elpa/org-ref-20160512.1337/org-ref.elc.

** Dependencies
helm-bibtex /home/neoarch/.emacs.d/elpa/helm-bibtex-20160422.1600/helm-bibtex.elc

* org-ref-pdf (loaded: nil)
system pdftotext: org-ref-pdf not loaded
You set pdftotext-executable to org-ref-pdf not loaded (exists: org-ref-pdf not loaded)

* org-ref-url-utils (loaded: nil)

* export variables
org-latex-pdf-process:
("pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f")

**Comment by jkitchin** [comment]
Also try running M-x org-ref in your org-file.

et2010 writes:

> Here is the debug info:
>
> #+TITLE: org-ref debug
>
> org-ref: Version 0.8.1 (git-commit c2fc02e900341c300d776c87a4227f9e4118ba72)
>
> * Variables
> 1. org-ref-bibliography-notes: ~/Dropbox/bibliography/notes.org (exists t)
> 2. org-ref-default-bibliography: (~/Dropbox/bibliography/references.bib) (exists (t)) (listp t)
> 3. org-ref-pdf-directory: ~/Dropbox/bibliography/bibtex-pdfs/ (exists t)
>
> * System
> system-type: System: gnu/linux
> system-configuration: x86_64-unknown-linux-gnu
> window system: Window system: x
> Emacs: GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.3)
>  of 2016-05-06 on arojas
> org-version: 8.3.4
>
> * about org-ref
> org-ref installed in /home/neoarch/.emacs.d/elpa/org-ref-20160512.1337/org-ref.elc.
>
> ** Dependencies
> helm-bibtex /home/neoarch/.emacs.d/elpa/helm-bibtex-20160422.1600/helm-bibtex.elc
>
> * org-ref-pdf (loaded: nil)
> system pdftotext: org-ref-pdf not loaded
> You set pdftotext-executable to org-ref-pdf not loaded (exists: org-ref-pdf not loaded)
>
> * org-ref-url-utils (loaded: nil)
>
> * export variables
> org-latex-pdf-process:
> ("pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f")
>
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/220#issuecomment-218906258


--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by et2010** [comment]
@jkitchin I can run org-ref without an error. Like you said, it's from helm-bibtex. Maybe I should raise an issue there.

**Comment by jkitchin** [comment]
can you try it on a key with no _ in it?

**Comment by et2010** [comment]
I tried but still no good, same error:

```bibtex-completion-get-entry1: Search failed: "^@\\([^^\"@\\&$#%',={}() 	
]*\\)[[:space:]]*[({][[:space:]]*zaman2007effec[[:space:]]*,"```

maybe it's the regex's problem?

**Comment by jkitchin** [comment]
can you send me an org file and bibfile that causes the issue for you?

**Comment by jkitchin** [comment]
This seems to be related to the bibtex-completion-bibliography variable. I am not sure if this is something org-ref should be setting. If you set that variable to the bibliography file you use, does the issue go away?

**Comment by et2010** [comment]
It works. Thanks! 

So I guess I should define this variable buffer-locally for each of my org documents since I use separate bib files.

**Comment by jkitchin** [comment]
hm.. it could also get set in (org-ref-find-bibliography), perhaps only if bibtex-completion is installed? WDYT?
