### ISSUE TITLE
Void variable bibtex-completion-format-citation-functions

### ISSUE THREAD

**Issue by devonwa** [jkitchin/org-ref#221]
Getting the following on load of the latest jmax update:
`let*: Symbol's value as variable is void: bibtex-completion-format-citation-functions`

Traced it back to here: 
[org-ref-helm-bibtex L93](https://github.com/jkitchin/org-ref/blob/master/org-ref-helm-bibtex.el#L93)
```
(setq org-ref-insert-cite-function 'org-ref-helm-insert-cite-link
      org-ref-cite-onclick-function 'org-ref-cite-click-helm)
```

Possibly related to this function:
[org-ref L109](https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L109)
```
(defcustom org-ref-completion-library
  'org-ref-helm-bibtex
  "String for library to define completion functions.
The completion library should provide functions for
`org-ref-insert-link-function', `org-ref-insert-cite-function',
`org-ref-insert-label-function', `org-ref-insert-ref-function',
and `org-ref-cite-onclick-function', and set those variables to
the values of those functions."
  :type 'symbol
  :options '(org-ref-helm-bibtex	; completion with helm + helm-bibtex
	     org-ref-helm-cite		; completion with helm in org-ref
	     org-ref-ivy-bibtex		; completion with ivy
	     org-ref-reftex		; org-completion
	     )
  :group 'org-ref)
```

Not sure if this is an actual bug or just an implementation issue on the cluster or my account.

**Comment by jkitchin** [comment]
This means you need to update helm-bibtex in the Emacs Options-> Manage
packages menu.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by devonwa** [comment]
That worked. Thanks.
