### ISSUE TITLE
Org-ref and helm-bibtex notes format

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#225]
I currently use org-ref and helm-bibtex. Unfortunately, if I call the open-notes function from either package, I end up with differently formatted notes. The helm-bibtex command creates notes as defined in `bibtex-completion-notes-template-one-file` and org-ref creates the notes as defined in `org-ref-open-bibtex-notes`. 

I prefer the org-ref way of doing this - is there an option to override helm-bibtex's behavior? 

Thanks!

**Comment by jagrg** [comment]
Here's one way to do it:

```elisp
(defun my/org-ref-notes-function (candidates)
  (let ((key (helm-marked-candidates)))
    (funcall org-ref-notes-function (car key))))

(helm-delete-action-from-source "Edit notes" helm-source-bibtex)
(helm-add-action-to-source "Edit notes" 'my/org-ref-notes-function helm-source-bibtex 7)
```

**Comment by Cumol** [comment]
Could this be added to the manual? Had to dig to find it!

Thanks @jagrg

**Comment by jkitchin** [comment]
Done!

**Comment by kccai** [comment]
Thanks for the fix for helm-bibtex. Is there any way to bind the action `ivy-bibtex-edit-notes` to `org-ref-notes-function` in ivy-bibtex?

Thanks!

**Comment by kccai** [comment]
After reading some documentations, I have  managed to get `org-ref-notes-function` to work in ivy-bibtex.

```emacs-lisp
(defun my-ivy/org-ref-notes-function (keys)
  (dolist (key keys)
    (funcall org-ref-notes-function key)))

(require 'ivy-bibtex)
(ivy-bibtex-ivify-action my-ivy/org-ref-notes-function ivy-bibtex-edit-notes)
```

Thanks!

**Comment by philohistoria** [comment]
I wish to use `helm-bibtex`'s note instead of `org-ref's note. So I want to override the note creation of `org-orf` with that of `helm-bibtex`, the reverse action of what has been proposed. 

Can anyone instruct me on this issue? I am a newbie to `org-mode`. Thanks a lot!

**Comment by philohistoria** [comment]
follow up on my previous comment: 

[this link offers a solution](https://github.com/jkitchin/org-ref/issues/383)
