### ISSUE TITLE
Export to latex has undefined citations.  Due to \bibstyle?

### ISSUE THREAD

**Issue by TedwardErker** [jkitchin/org-ref#226]
Similarly to [issue 162 ](https://github.com/jkitchin/org-ref/issues/162)when exporting to pdf my citations are "?"'s and no bibliography appears.  The export for html works just fine.  I have defined org-latex-pdf-process as in issue 162 and I just updated org-ref.

Message from emacs states there are undefined citations.

When I run 
`latexmk -pdf -bibtex test.tex
error returned is:
"I found no \bibstyle command"

When I run
`pdflatex -interaction nonstopmode test.tex
I get the undefined reference warning.

[test.tex.txt](https://github.com/jkitchin/org-ref/files/280666/test.tex.txt)

I'm a novice, so I assume a foolish error on my end is causing this.  But after many hours I figured it'd be worth writing about.

**Comment by jkitchin** [comment]
You might just need a bibliographystyle:unsrt link in the file.

On Tuesday, May 24, 2016, TedwardErker <notifications@github.com> wrote:

> Similarly to issue 162 <https://github.com/jkitchin/org-ref/issues/162>when
> exporting to pdf my citations are "?"'s and no bibliography appears. The
> export for html works just fine. I have defined org-latex-pdf-process as in
> issue 162 and I just updated org-ref.
>
> Message from emacs states there are undefined citations.
>
> When I run
> `latexmk -pdf -bibtex test.tex
> error returned is:
> "I found no \bibstyle command"
>
> When I run
> `pdflatex -interaction nonstopmode test.tex
> I get the undefined reference warning.
>
> test.tex.txt
> <https://github.com/jkitchin/org-ref/files/280666/test.tex.txt>
>
> I'm a novice, so I assume a foolish error on my end is causing this. But
> after many hours I figured it'd be worth writing about.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/226>
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by TedwardErker** [comment]
works like a charm.  I simply added bibliographystyle:unsrt to the bottom of my org file and export was happy.  Sorry if I missed that in the documentation.
