### ISSUE TITLE
Specifying ivy-bibtex but still installs helm

### ISSUE THREAD

**Issue by fintelkai** [jkitchin/org-ref#231]
I'm trying to do without the bloat of helm and use ivy instead. I tried to install ivy-bibtex and org-ref via use-package as follows:

```emacs-lisp
(use-package ivy-bibtex
  :config
  (setq bibtex-completion-notes-path "~/Dropbox/Bibliography/biblio-notes.org"
        bibtex-completion-bibliography '("~/Dropbox/Bibliography/kvf-semantics.bib")
        bibtex-completion-library-path '("~/Dropbox/E-Library")
        bibtex-completion-pdf-open-function
         (lambda (fpath)
           (call-process "open" nil 0 nil fpath)))
)

(use-package org-ref
  :init
  (setq reftex-default-bibliography '("~/Dropbox/Bibliography/kvf-semantics.bib"))
  (setq org-ref-bibliography-notes "~/Dropbox/Bibliography/biblio-notes.org"
        org-ref-default-bibliography '("~/Dropbox/Bibliography/kvf-semantics.bib")
        org-ref-pdf-directory "~/Dropbox/E-Library"
        org-ref-completion-library 'org-ref-ivy-bibtex)
)
```

But what happens is that helm gets installed anyway, with this message: "Org-ref is installing 'helm'...". I'm hoping that helm isn't actually loaded at any point, but I'm not sure yet.

[PS: I assume this is the same issue mentioned at https://github.com/jkitchin/org-ref/pull/213#issuecomment-217943584.]

**Comment by ericdanan** [comment]
Yes I guess it is the same issue, I was not able to figure out why this happens. See also #218.

**Comment by jkitchin** [comment]
At the moment, this is expected. hopefully we will fix it in the next week.

**Comment by jkitchin** [comment]
We tried for a couple of weeks to separate out an org-ref-ivy, but it did not succeed. I am tabling this effort and staying with one MELPA package for now. If helm is a deal breaker, I would suggest you run org-ref off the git repo and manage the packages yourself. You could use el-get for that.
