### ISSUE TITLE
What do I do with an isbn?

### ISSUE THREAD

**Issue by paynito** [jkitchin/org-ref#232]
Hi I have a new pdf and an isbn for it. How do I add this to my .bib that I use with org-ref?
isbn 9781462525652
http://www.guilford.com/books/Hypothesis-Testing-Model-Selection-Social-Sciences/David-Weakliem/9781462525652
pdf named as Weakliem2016.pdf     (AuthorYear.pdf   which I'm using as citeKey for everything since that seems to work best with your system)

When I drag pdfs onto my open .bib now in emacs org-ref tells me "No DOI found in file:///dir/Weakliem2016.pdf"

I wish that it would add a new @book or @article with at least a File = field
I can't figure out how to get totally into emacs and org-ref, it seems like I still need Mendeley or BibDesk for initially adding a new reference to the bib.

I guess I can give up drag and drop and just start typing
@book{Author2016,
Year = {2016}}

is that the recommended workflow for pdfs that don't have a DOI on the front page?

**Comment by jkitchin** [comment]
PDF drag and drop doesn't work for isbn.

For that isbn, I was able to use M-x isbn-to-bibtex-lead, enter the isbn in the minibuffer, and get a web page that has a bibtex entry you can copy. The isbn was unknown for M-x isbn-to-bibtex.

If you are in your bibtex file in emacs, you can type C-c C-e b to insert a book entry template (see the Entry-Types menu).
