### ISSUE TITLE
Where is the walk through on Adding "User functions" hooks (for Ebib and gui pdfViewer)?

### ISSUE THREAD

**Issue by paynito** [jkitchin/org-ref#233]
Hi I like that choice 0 is to edit the raw .bib
How do I edit that list to make an option to call Ebib?   [http://joostkremers.github.io/ebib/](url)

Also choices **

    2. Open pdf  **
   ..
   13. ..

    User functions 
Open pdf in emacs **

both do the same thing right now, they open with pdf-tools instead of docView.  How could I make one open with the system viewer (currently set to Skim)  or to open in Acrobat Pro (sometimes you haven't OCR'd yet)  or in Highlights ( I can only find yellow in pdf-tools, I miss my multiple highlighter colors)

I guess I'm looking for the part in the manual about how to add another User function.

**Comment by jkitchin** [comment]
Here is an example for adding a candidate in helm.

```
(defvar org-ref-helm-user-candidates '()
  "List of user-defined candidates to act when clicking on a cite link.
This is a list of cons cells '((\"description\" . action)). The
action function should not take an argument, and should assume
point is on the cite key of interest.")

;; example of adding your own function
(add-to-list
 'org-ref-helm-user-candidates
 '("Open pdf in emacs" . (lambda ()
                           (find-file
                            (concat
                             (file-name-as-directory org-ref-pdf-directory)
                             (car (org-ref-get-bibtex-key-and-file))
                             ".pdf"))))
 t)
```

Otherwise, I think actions are generally stored in the variable org-ref-bibtex-completion-actions as a list of "Cons cells of string and function to set the actions of `helm-bibtex' to.
The car of cons cell is the string describing the function.
The cdr of the the cons cell is the function to use."

You can add to or re-order this list.

**Comment by paynito** [comment]
Thank you, I'll try in about 12 hours. Great program. I haven't quite got it down with p.# is it [footcite:CiteKey][::pageref--20]  ?

**Comment by jkitchin** [comment]
This 
[[footcite:CiteKey][::pageref--20]]  

should export in latex to

exports to \footcite[][pageref--20]{CiteKey}

**Comment by paynito** [comment]
Thank you.  I think all I need then is [[footcite:CiteKey][::20]].   Ok, that worked but it came out before the ISSN and DOI, I expected the page # to be the very last piece of a footcite, but that's probably the BibLaTeX Chicago Style's problem, not yours.
