### ISSUE TITLE
org-ref export cross references for figure to HTML

### ISSUE THREAD

**Issue by heartnheart** [jkitchin/org-ref#234]
I'm using org-ref (0.8.1/org-ref-20160527.1131 from melpa) and org-mode (version 8.3.4 (8.3.4-72-gddd58f-elpaplus), the ref syntax can not export reference to figure correctly to HTML.

Here is an example:
```org
As shown in Figure [[ref:fig:test]].

#+CAPTION: This is a figure
#+NAME: fig:test
[[file:test.png]]

```
Which is exported to HTML as
```
<body>
  <div id="content">
    <p>
      As shown in Figure <a href="#fig:test">fig:test</a>.
    </p>
    <div id="orgparagraph1" class="figure">
      <p><img src="test.png" alt="test.png" />
      </p>
      <p><span class="figure-number">Figure 1:</span> This is a figure</p>
    </div>
  </div>
</body>
```
Note that org-mode does not use the `#+NAME:` property for HTML.
For LaTeX export, user can set `org-latex-prefer-user-labels` to `t` to force org-mode to value the `#+NAME:` property.
For HTML export, user should use the syntax `[[fig:test]]` without the `ref` word specific to org-ref.
For example, the following code export to HTML correctly:
```
As shown in Figure [[fig:test]].

#+CAPTION: This is a figure
#+NAME: fig:test
[[file:test.png]]
```

exports to HTML as:

```
<body>
  <div id="content">
    <p>
      As shown in Figure <a href="#orgparagraph1">1</a>.
    </p>
    <div id="orgparagraph1" class="figure">
      <p><img src="test.png" alt="test.png" />
      </p>
      <p><span class="figure-number">Figure 1:</span> This is a figure</p>
    </div>
  </div>
</body>
```

org-mode does not provide a similar custom variable for HTML export but I hope this can be fixed in the org-fef side. Thank you!

**Comment by jagrg** [comment]
Would a label work for you?

```
#+CAPTION: This is a figure label:test
[[file:test.png]]
```

**Comment by heartnheart** [comment]
@jagrg It works! Thank you so much!
