### ISSUE TITLE
jit-lock error after installing org-ref

### ISSUE THREAD

**Issue by zhangda82** [jkitchin/org-ref#235]
Hello,

I noticed an error during the font locking of newly created org files after installing org-ref using the following configurations:
(use-package org-ref
  :config
  (setq org-ref-completion-library 'org-ref-helm-bibtex
        bibtex-completion-bibliography "C:/Users/Da/Dropbox/Bib/da.bib"
        org-ref-default-bibliography '("C:/Users/Da/Dropbox/Bib/da.bib")
        ))

For a newly created buffer "org.org", the error message says:
Error during redisplay: (jit-lock-function 1) signaled (args-out-of-range #<buffer org.org> 362 388)

Can you please look into that? Thank you!

Da Zhang

**Comment by jagrg** [comment]
I cannot reproduce your error. Does this happen with emacs -Q?

**Comment by jkitchin** [comment]
I also cannot reproduce it.

**Comment by zhangda82** [comment]
After a re-installation of org mode and org-ref from emacs -q, the issue went away. 
Thanks for the help.
