### ISSUE TITLE
`org-ref-helm-insert-ref-link` failed to find correct context for CUSTOM_ID

### ISSUE THREAD

**Issue by heartnheart** [jkitchin/org-ref#241]
Function `org-ref-helm-insert-ref-link` (https://github.com/jkitchin/org-ref/blob/master/org-ref-helm.el#L115) use a temp buffer to find label context as in (https://github.com/jkitchin/org-ref/blob/master/org-ref-helm.el#L124), without setting the buffer's major mode to `org-mode`.

As `org-ref-get-label-context` calls `org-map-entries` when finding context for label in `CUSTOM_ID`, it failed and "!!! NO CONTEXT FOUND !!!" is returned. 

I'm testing it with org-ref 0.8.1 (from melpa) and org-mode 8.3.4 ((org-plus-contrib-201606) from melpa) on the `org-ref.org` file generated by command `org-ref-help`.

I don't understand the need for using a temp buffer here. Thank you.

**Comment by jkitchin** [comment]
Thanks for noticing this. I just pushed a fix for it I think. Please confirm.

**Comment by heartnheart** [comment]
Fix confirmed and thank you!
