### ISSUE TITLE
Dropping 'r' at beginning of bibliography file

### ISSUE THREAD

**Issue by Paethon** [jkitchin/org-ref#243]
Hi

If I specify `bibliography:refereces.bib` in my org-file it actually tries to access `eferences.bib`. So it seems like one or multiple `r`s after `bibliography:` are being dropped.

Maybe some bug?

**Comment by jkitchin** [comment]
I have seen issues like this before, do you by chance have some funny whitespace regexp defined?

**Comment by jkitchin** [comment]
something like https://github.com/jkitchin/org-ref/issues/129

**Comment by Paethon** [comment]
Sorry for the late reply. That actually was the problem. Had exactly the same problem as #129 

Changed the regex so isearch works across line breaks and entered it incorrectly via customize. I am a bit surprised I never had any other problems because of it :)

Thanks :+1:
