### ISSUE TITLE
Error when adding ArXiv entry

### ISSUE THREAD

**Issue by JP-Ellis** [jkitchin/org-ref#246]
It seems like adding arXiv entries isn't working at the moment, though I am not sure why.

Here's the backtrace:
```lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  bibtex-valid-entry(t)
  bibtex-end-of-entry()
  bibtex-text-in-field("author\\|editor" t)
  bibtex-autokey-get-field("author\\|editor" (("\\\\aa" . "a") ("\\\\AA" . "A") ("\\\"a\\|\\\\\\\"a\\|\\\\ae" . "ae") ("\\\"A\\|\\\\\\\"A\\|\\\\AE" . "Ae") ("\\\\i" . "i") ("\\\\j" . "j") ("\\\\l" . "l") ("\\\\L" . "L") ("\\\"o\\|\\\\\\\"o\\|\\\\o\\|\\\\oe" . "oe") ("\\\"O\\|\\\\\\\"O\\|\\\\O\\|\\\\OE" . "Oe") ("\\\"s\\|\\\\\\\"s\\|\\\\3" . "ss") ("\\\"u\\|\\\\\\\"u" . "ue") ("\\\"U\\|\\\\\\\"U" . "Ue") ("\\\\`\\|\\\\'\\|\\\\\\^\\|\\\\~\\|\\\\=\\|\\\\\\.\\|\\\\u\\|\\\\v\\|\\\\H\\|\\\\t\\|\\\\c\\|\\\\d\\|\\\\b" . "") ("[`'\"{}#]" . "") ("\\\\-" . "") ("\\\\?[ 	\n]+\\|~" . " ")))
  bibtex-autokey-get-names()
  bibtex-generate-autokey()
  arxiv-get-bibtex-entry-via-arxiv-api("1605.09401")
  arxiv-add-bibtex-entry("1605.09401" "/tmp/test/references.bib")
  arxiv-get-pdf-add-bibtex-entry("1605.09401" "/tmp/test/references.bib" "/tmp/test/")
  call-interactively(arxiv-get-pdf-add-bibtex-entry nil nil)
  command-execute(arxiv-get-pdf-add-bibtex-entry)
```

Let me know if there's any more information you need.

**Comment by jagrg** [comment]
I cannot reproduce it.

`(arxiv-get-pdf-add-bibtex-entry "1605.09401" "/tmp/test/references.bib" "/tmp/test/")`

Your example works fine for me. Can you try again?

**Comment by JP-Ellis** [comment]
So I've tried to replicate a few times, and in some cases it works and doesn't work.  Turns out, I think it is something to do with the `bibtex-dialect` option.

In particular, if I begin with the following content for `/tmp/test/references.bib`:
```bibtex
% Local Variables:
% bibtex-dialect: biblatex
% End:
```
and then try running the above command, it fails.  On the other hand, if I start with an empty `references.bib` it works; if I start with an empty file and then use `bibtex-set-dialect` to change it to `biblatex` it still works; and if I start with an empty, add the above code and then reload the buffer it also works.

It seems like the `bibtex` dialect loads some functions that the `biblatex` dialect does not.  As for why that might be, I have no idea (yet).

Note that I am using Spacemacs which tries to load packages and functions lazily which might be the issue, though evidently the other functions seem to be working fine so I'm not sure why one function loads correctly whilst some other function is not being loaded.

**Comment by jagrg** [comment]
I see the error now. I'm also not sure what causes it, but I got it to work with the dialect set globally. Would this work for you?

`% -*- eval:(bibtex-set-dialect 'biblatex); -*-`

**Comment by JP-Ellis** [comment]
Finding a temporary fix around this issue isn't really the issue as I have identified that the dialect is the cause of the issue.  I'm just reporting the issue and hopefully that can be fixed and no work around will be required in the future :)

**Comment by jagrg** [comment]
I think the problem is with `arxiv-get-bibtex-entry-via-arxiv-api` when trying to generate a key in the temp buffer. Adding those two lines fixed it.

```diff
modified   org-ref-arxiv.el
@@ -128,6 +128,8 @@ Returns a formatted BibTeX entry."
            (temp-bibtex (format arxiv-entry-format-string "" title names year arxiv-number category abstract url))
            (key (with-temp-buffer
                   (insert temp-bibtex)
+		  (bibtex-mode)
+		  (bibtex-set-dialect (parsebib-find-bibtex-dialect) t)
                   (bibtex-generate-autokey))))
       (format arxiv-entry-format-string key title names year arxiv-number category abstract url))))
```

**Comment by jkitchin** [comment]
Thanks for figuring that out. I just added those two lines.

**Comment by JP-Ellis** [comment]
The latest version of `org-ref` no longer has this issue.  Thanks!
