### ISSUE TITLE
Update to new org-ref version causes problems

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/org-ref#247]
I tried to update org-ref version 20160617.644 to 20160627.455 using Melpa. This is what I obtained initialising emacs with --debug-init:
`Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "nil")
  require(nil)
  eval-buffer(#<buffer  *load*-326570> nil "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-core.el" nil t)  ; Reading at buffer position 5180
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-core.el" "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-core.el" nil t)
  require(org-ref-core)
  eval-buffer(#<buffer  *load*-705957> nil "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-latex.el" nil t)  ; Reading at buffer position 1015
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-latex.el" "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160627.455/org-ref-latex.el" nil t)
  require(org-ref-latex)
  eval-buffer(#<buffer  *load*> nil "/Users/sergiobacelar/.emacs.d/init.el" nil t)  ; Reading at buffer position 7680
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/init.el" "/Users/sergiobacelar/.emacs.d/init.el" t t)
  load("/Users/sergiobacelar/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()`

**Comment by jkitchin** [comment]
Thanks for reporting this. I have pushed a fix that should take care of this. It will take 4-6 hours before it shows up in MELPA.

**Comment by sbacelar** [comment]
Not yet solved with new version 20160628.1917.
`Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "nil")
  require(nil)
  eval-buffer(#<buffer  *load*-976463> nil "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-core.el" nil t)  ; Reading at buffer position 5178
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-core.el" "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-core.el" nil t)
  require(org-ref-core)
  eval-buffer(#<buffer  *load*-937597> nil "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-latex.el" nil t)  ; Reading at buffer position 1015
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-latex.el" "/Users/sergiobacelar/.emacs.d/elpa/org-ref-20160628.1917/org-ref-latex.el" nil t)
  require(org-ref-latex)
  eval-buffer(#<buffer  *load*> nil "/Users/sergiobacelar/.emacs.d/init.el" nil t)  ; Reading at buffer position 7675
  load-with-code-conversion("/Users/sergiobacelar/.emacs.d/init.el" "/Users/sergiobacelar/.emacs.d/init.el" t t)
  load("/Users/sergiobacelar/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
`

**Comment by ericdanan** [comment]
I just installed this version and I don't get errors except the compilation errors mentioned in #133 .
