### ISSUE TITLE
citing space issue

### ISSUE THREAD

**Issue by llcc** [jkitchin/org-ref#25]
Hi @jkitchin 

If I do not insert a space between text and citation, the citation can not be exported to latex properly.
For example:
`magnetizationcite:shilling-1974-magnet-si-fe.` to `magnetizationcite:shilling-1974-magnet-si-fe`

But if I do add that space, the space will also be exported like `magnetization [1]`. The space should be deleted actually.

Thanks if you can fix it.

**Comment by jkitchin** [comment]
You have to use [[cite:key]] for this.

**Comment by llcc** [comment]
@jkitchin thanks, problem solved!
