### ISSUE TITLE
does org-ref-set-bibtex-keywords support completion?

### ISSUE THREAD

**Issue by zeltak** [jkitchin/org-ref#250]
Hi

i just discvoerd today org-ref-set-bibtex-keywords and it seems really cool.
Does org-ref-set-bibtex-keywords support any completion type? it could be either from in buffer (bib file) text or perhaps a pre defined list of keyword?
currently if you have to add 30 times the word Epidemiology it can get a bit tiring ;-) it would be cool to tab complete or use ivy/counsel to quick add keywords

best 

Z

**Comment by jkitchin** [comment]
Have you tried helm-tag-bibtex-entry?

**Comment by jkitchin** [comment]
I did just push a patch that adds ido completion for org-ref-set-bibtex-keywords.

**Comment by jagrg** [comment]
It may be easier to do this from helm-bibtex. It gives you the option to tag multiple entries at once. Just press `C-SPC` on all candidates you wish to tag, type your keyword and select "Add keywords to entries" (`org-ref-helm-tag-entries`).

**Comment by jkitchin** [comment]
I pushed a way to do this with ivy, with C-spc and all ;) It is called org-ref-ivy-set-keywords.
