### ISSUE TITLE
Recent helm update breaks org-ref-helm-insert-label-link

### ISSUE THREAD

**Issue by et2010** [jkitchin/org-ref#257]
I cannot insert label link anymore after recent helm (if I remember correctly) update. When `org-ref-helm-insert-label-link` is called, a helm window  will pop up prompting you to insert a label. But when I'm done inputing a new label and hit enter, nothing happens. Note that there is actually no error message here.

Here is my org-ref debug info:

> #+TITLE: org-ref debug
> 
> org-ref: Version 0.9.0 (git-commit f1247c8d189e5637b6c128f97fe4fb008b718940)
> 
> * Variables
> 1. org-ref-bibliography-notes: ~/Dropbox/bibliography/notes.org (exists t)
> 2. org-ref-default-bibliography: (~/Dropbox/bibliography/references.bib) (exists (t)) (listp t)
> 3. org-ref-pdf-directory: ~/Dropbox/bibliography/bibtex-pdfs/ (exists t)
> 
> * System
> system-type: System: gnu/linux
> system-configuration: x86_64-unknown-linux-gnu
> window system: Window system: x
> Emacs: GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.6)
>  of 2016-06-05 on juergen
> org-version: 8.3.4
> 
> * about org-ref
> org-ref installed in /home/neoarch/.emacs.d/elpa/org-ref-20160708.1222/org-ref.elc.
> 
> ** Dependencies
> helm-bibtex /home/neoarch/.emacs.d/elpa/helm-bibtex-20160422.1600/helm-bibtex.elc
> 
> * org-ref-pdf (loaded: t)
> system pdftotext: /usr/bin/pdftotext
> You set pdftotext-executable to pdftotext (exists: /usr/bin/pdftotext)
> 
> * org-ref-url-utils (loaded: nil)
> 
> * export variables
> org-latex-pdf-process:
> ("pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f")

and here's my package list:

> helm-20160711.1143
> helm-core-20160711.1141
> helm-bibtex-20160422.1600
> org-plus-contrib-20160711
> org-ref-20160708.1222

**Comment by et2010** [comment]
I tried to figure out why it stopped working, but to no avail. Any help will be greatly appreciated.

**Comment by jkitchin** [comment]
I wonder if this is a new bug or a change in helm behavior. the problem seems to be that helm-pattern is "" at the end of org-ref-helm-insert-label-link, so it appears as if nothing is being inserted. That is new behavior, since it worked before I updated helm too.

I would check with the helm developers. A simple example showing the issue is:

```
(helm :sources '((name . "test")
		 (candidates . ("a" "b" "c"))
		 (action . (lambda (label)
			     (insert (or label helm-pattern))))))
```

I would expect this to insert "a" "b" "c" or what ever is typed in the selection buffer, but it doesn't.

**Comment by jagrg** [comment]
Helm changes quickly, but here's one way to do it:

```elisp
(defun org-ref-helm-insert-label-link ()
  (interactive)
  (let ((labels (org-ref-get-labels)))
    (helm :sources `(,(helm-build-sync-source "Existing labels"
			:candidates labels
			:action (lambda (label)
				  (with-helm-current-buffer
				    (org-open-link-from-string
				     (format "ref:%s" label)))))
		     ,(helm-build-dummy-source "Create new label"
			:action (lambda (label)
				  (with-helm-current-buffer
				    (insert (concat "label:" label))))))
	  :buffer "*helm labels*")))
```

See https://github.com/emacs-helm/helm/issues/1559

**Comment by jkitchin** [comment]
That is an annoying change in helm! It appears helm is ignoring the old dummy action for this now too.

Now that I look at this function it seems too complicated for what it is named, and should do. and it might not even do what it claims to, e.g. it does not seem to replace the label if you are on one. 

@jagrg I will merge a PR with the function above if you add a docstring to it. Thanks,
