### ISSUE TITLE
support ~, intead of /home/usrname, for pdf link

### ISSUE THREAD

**Issue by junfx** [jkitchin/org-ref#260]
support ~, intead of /home/usrname,  for pdf link when generates a pdf link with org-ref-open-bibtex-notes.
I search variables and no things can be customized, and this may be not a issue but a feature.
This is useful for sharing with linux/macos user, and even with windows user.

**Comment by jkitchin** [comment]
I think it is supported. What do you have org-ref-pdf-directory set to? Mine is set to 

org-ref-pdf-directory is a variable defined in `org-ref-core.el'.
Its value is "~/Dropbox/bibliography/bibtex-pdfs/"

I don't use notes much though so, I am not sure what you might seeing.

**Comment by junfx** [comment]
Reading org-ref-core.el, I found that the pdf path (contains ~) is expanded to /home/username by function f-join.
And (setq org-ref-pdf-directory "./bibtex-pdf/") is works for me, i.e. use a path **relative** to the bib file. 

Thanks.
