### ISSUE TITLE
doi-utils-add-bibtex-entry-from-doi problem with chinese doi

### ISSUE THREAD

**Issue by liuzy** [jkitchin/org-ref#263]
Hi , jkitchin , I am here again. 

Grateful for your work , I am a Chinese user, and I have used this tool for a period ,which took me a lot of convenience.

But there is a problem: when I try to get the results by using "doi-utils-add-bibtex-entry-from-doi" from a chinese doi such as "10.13334/j.0258-8013.pcsee.2014.01.001" , it comes out failure message "doi-utils-doi-to-bibtex-string: Wrong type argument: integer-or-marker-p, nil". When foreign doi, it works right. I don't known why about this.

Can you have a test and give me some advice ? 
Many thanks !

**Comment by jagrg** [comment]
I'm not sure that crossref indexes chinese dois. Are you able to find any using their website?

https://search.crossref.org/

**Comment by liuzy** [comment]
You are right , I can not find the crossref index information of that doi on "https://search.crossref.org/" either , but I can find the index on "https://dx.doi.org" website . (another doi of chinese : 10.7666/d.y1873784)

**Comment by jagrg** [comment]
None of your dois are converted to json. Do you have other Chinese dois that we can try? You can test them here: http://crosscite.org/citeproc/ or using the command line:

```
curl -LH "Accept: application/citeproc+json" "http://doi.org/10.13334/j.0258-8013.pcsee.2014.01.001"
```

**Comment by jkitchin** [comment]
I added some troubleshooting notes to org-ref.org based on this:

https://github.com/jkitchin/org-ref/blob/master/org-ref.org#troubleshooting-doi-utils

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu


On Wed, Jul 27, 2016 at 10:36 AM, Jonathan Gregory <notifications@github.com

**Comment by liuzy** [comment]
Ok , I see .
Thank you very much ! @jkitchin @jagrg
