### ISSUE TITLE
Opening PDFs

### ISSUE THREAD

**Issue by cpitclaudel** [jkitchin/org-ref#270]
Just came across this in the README:

```
;; open pdf with system pdf viewer (works on mac)
(setq bibtex-completion-pdf-open-function
  (lambda (fpath)
    (start-process "open" "*open*" "open" fpath)))
```

Instead of this, when AucTeX is available, would it work to use `TeX-view-program-selection`?

**Comment by jkitchin** [comment]
It could work. org-ref is flexible enough for you to program that in if you wanted.
