### ISSUE TITLE
Two issues with org-ref-sort-citation-link

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#271]
Hi and thanks for a great package. Two quick issues with `org-ref-sort-citation-link`: 

1. It currently puts forthcoming articles at the beginning of the list rather than at the end
2. It deletes pre/post notes from the link

Thanks again!

**Comment by jkitchin** [comment]
I am not sure what you mean by the first item in your list. I think I fixed number 2.

**Comment by jabranham** [comment]
Thanks! 

For the first one, if I have a key like `authorforthcoming` it puts it before `author1990` for example even though it should go after. My guess (haven't had time to check yet) is that it simply sorts any non-numeric year before numeric years...

**Comment by jkitchin** [comment]
I believe it is sorting by year only, it does not sort by string. For papers in the same year, I guess the order stays the same, but I am not sure if the sort is stable.

**Comment by jabranham** [comment]
Ah, I think I found the issue. When `org-ref-sort-citation-year` calls `string-to-number`, `string-to-number` treats anything that can't be parsed to a number ("forthcoming" in my case) as a 0. So it gets sorted before any publications with a numeric year...

One hackish workaround is to replace any `0`s in `years` to a high number - 3000 or something before running `string-to-number`.
