### ISSUE TITLE
Trouble get org-ref to work

### ISSUE THREAD

**Issue by floli** [jkitchin/org-ref#277]
Hello,

I try to get org-ref working, but having some bumps on that way. My .emacs settings look like that:

```
(use-package reftex
  :commands turn-on-reftex
  :init
  (progn
    (setq reftex-default-bibliography '("~/Mendeley/library.bib"))
    (setq reftex-plug-into-AUCTeX t))
  )

(use-package org-ref
  :ensure t
  :config
  (setq org-ref-default-bibliography reftex-default-bibliography))
```
```
org-ref-default-bibliography is a variable defined in `org-ref-core.el'.
Its value is ("~/Mendeley/library.bib")
Original value was nil
```

```org-ref-helm-insert-cite-link``` works and inserts a link.

However clicking on a link gives these messages
```
No such file:  (ignored) [2 times]
org-ref-cite-candidates: Wrong type argument: stringp, nil
No such file:  (ignored)
!!! No entry found !!!
```

I also tried adding a link ```bibliography:/home/florian/Mendeley/library.bib```, and clicking on it gives
```
No such file:  (ignored) [2 times]
org-ref-cite-candidates: Wrong type argument: stringp, nil
No such file:  (ignored)
!!! No entry found !!!
```

What is wrong with my config?

Emacs 24.5, auctex 11.89.4, bundled org mode (8.2.10)

**Comment by floli** [comment]
I can reproduce that using ```emacs -Q``` and
```
(package-initialize)
(require 'org-ref)
```
and add the bibliography: link

**Comment by jagrg** [comment]
Can you post one of your bibtex entries here.

**Comment by floli** [comment]
```
% cat library.bib
@incollection{Blom2015a,
author = {Blom, David and Lindner, Florian and Mehl, Miriam and Scheufele, Klaudius and van Zuijlen, Alexander},
booktitle = {Advances in Computational Fluid-Structure Interaction},
file = {:home/florian/Mendeley/Blom et al. - 2015 - A Review on Fast Quasi-Newton and Accelerated Fixed Point Iterations for Partitioned Fluid-Structure Interaction Si.pdf:pdf},
keywords = {Preprint},
mendeley-tags = {Preprint},
pages = {1--12},
title = {{A Review on Fast Quasi-Newton and Accelerated Fixed Point Iterations for Partitioned Fluid-Structure Interaction Simulation}},
year = {2015}
}
@unpublished{Beatson1997,
author = {Beatson, Rick and Greengard, Leslie},
file = {:home/florian/Mendeley/Beatson, Greengard - 1997 - A short course on fast multipole methods.pdf:pdf},
isbn = {0 19 850190},
keywords = {fast multipole method},
mendeley-tags = {fast multipole method},
pages = {1--37},
title = {{A short course on fast multipole methods}},
url = {http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.129.7826{\&}rep=rep1{\&}type=pdf},
year = {1997}
}
```

**Comment by jkitchin** [comment]
I can't reproduce this. Can you run M-x org-ref in the org file where you have the problem, and report back what it outputs?

**Comment by floli** [comment]
Of course. I started using ```emacs -Q``` executed the two commands from above, and since I can't copy out of helm buffers, took a screenshot.
![screenshot_20160822_161055](https://cloud.githubusercontent.com/assets/1028028/17857760/4e95e13e-6883-11e6-8094-8608fe7f6cb8.png)

I think this looks fairly ok, however, when I click the Bib link, I get these messages:
```
org-ref-open-bibliography: Invalid search bound (wrong side of point)
Error running timer `org-ref-link-message': (error "Invalid search bound (wrong side of point)")
```

**Comment by jagrg** [comment]
Try again without the link description and see if that works. For example:

```
bibliography:~/Mendeley/library.bib
```

**Comment by jkitchin** [comment]
That could be the issue. I see a similar error. I guess it doesn't work with the link description. I guess I have never used it that way!

**Comment by floli** [comment]
The error has vanished, but I'm not sure if it works correctly.

Using my full configuration, clicking the link open the directory where the org file is in a dired buffer (not the bib file itself, not its directory).
Calling ```org-ref``` looks like above (including the correct bib file displayed), but when selecting ```Insert citation``` I just get the fall back options. ```org-ref--helm-insert-cite-link``` works, but the link does not work, neither hovering, not clicking on it. Moving the point on the link, just displays " exists." in the minibuffer.

Using minimal initialization, I can click the bibliography link and the bib file is opened. However, ```org-ref``` still displays only the fallback options. A link works as expected (hovering, opening).

So it seems like my existing config somehow interferes with org-ref. I got no idea what.

If you want to have a look, I have uploaded the complete config here: http://pastebin.com/ejqiU2An

**Comment by jagrg** [comment]
> Using minimal initialization, I can click the bibliography link and the bib file is opened. However, org-ref still displays only the fallback options. A link works as expected (hovering, opening).

Try this:

`(setq bibtex-completion-bibliography org-ref-default-bibliography)`

**Comment by floli** [comment]
Using ```emacs -Q``` and
```
(package-initialize)
(require 'org-ref)
(setq reftex-default-bibliography '("~/Mendeley/library.bib"))
(setq org-ref-default-bibliography reftex-default-bibliography)
(setq bibtex-completion-bibliography org-ref-default-bibliography)
```
Hovering and opening a citation link works. Opening a bibliography link works too. ```org-ref``` -> Insert a citation displays the content of BibTeX file.

Using my own config:
 ```org-ref``` -> Insert a citation displays the content of BibTeX file. But:
Neither opening a bibliography link, nor a cite link works. Messages still like:
```
!!! No entry found !!!
No such file:  (ignored)
```
So, for me, it does not work :-(

**Comment by floli** [comment]
Could you reproduce it using my config. The config is self-contained, you should be able to just copy it in an alternative .emacs.d and it will fetch all packages needed.

**Comment by jagrg** [comment]
I would suggest bisecting your .emacs file recursively: Comment-out half of the code, restart Emacs and see which half is causing the problem. Then do 1/4, 1/8, 1/16 and so on. It may be easier to do this from your side. Let us know what you find.

**Comment by floli** [comment]
Great idea! And I got the problematic setting. It's
```
;; isearch convenience, space matches anything (non-greedy)
(setq search-whitespace-regexp ".*?")
```
Now I don't expect a setting that I modified for interactive isearch to interfere with non-interactive elisp code. I got no idea, if I'm not supposed to modify that setting (I could live without it, albeit it would be nice to have it) or if org-ref uses some function in a way it's not supposed to....

Anyway, I'm glad to have found it, I hope that it's helpful.

**Comment by jkitchin** [comment]
Others have had a similar problem with setting this variable. It is tricky to change the whitespace-regexp correctly I think. 

Mine is set to "\\s-+". I don't think your expression does what you think, it looks like it would match any character (the dot) zero or more times, and I can't see what the ? which is matching 0 or 1 times would do after that.

**Comment by floli** [comment]
Ok, I copied that somewhere from the Internets. Maybe from [Reddit](https://www.reddit.com/r/emacs/comments/3yxk2x/flexible_isearch_without_a_package/). Actually I got no idea either whats ```?``` at the end does.
```\s-``` matches whitespaces. ```+``` at least once. So your regexp just matches an arbitray number of spaces. I actually wants it to match anything, but ```.*``` also causes org-ref to brake. I will leave it unset, when it causes trouble with org-ref it probably would interfere with other packages as well.

Thanks for help! I'm still having problems exporting to PDF, but I will look into it myself firstly.

**Comment by spluque** [comment]
I just started using org-ref, and am also getting:

`Error running timer `org-ref-link-message': (error "Invalid search bound (wrong side of point)")`

if the `[Description]` part is used for the bibliography link.

**Comment by jkitchin** [comment]
That does happen. That is not easy to fix, because we try to figure out which bibliography file the cursor or point is on. With a description that is not possible since the bibliography files are hidden. There is no reason to have a description, so I recommend you don't use it ;)
