### ISSUE TITLE
PDF drag-n-drop is not working on windows 

### ISSUE THREAD

**Issue by FrostedPenguin** [jkitchin/org-ref#280]
Hello. I have an issue with PDF drag-n-drop.
I'm using emacs on windows 10.

So far, PDF tools is installed and I added it to my excutable path and i required org-ref-pdf and
org-ref-url-utils.
Function doi-add-bibtex-entry is working very well.
So I think DOI parsing from PDF is not the problem.

I think the problem is parsing the file path.

For example, I tired to parse DOI in C:/Users/fpenguin23/Desktop/temp/ISM.pdf
in the message buffer function said like this.
No doi found in file:C%3A/Users/fpenguin23/Desktop/temp/ISM.pdf

I have checked the functions in org-ref-pdf.el but I couldn't find out why it acts like that.
Do you have any idea?

**Comment by jkitchin** [comment]
Maybe there is no DOI to be found in ISM.pdf?

**Comment by FrostedPenguin** [comment]
It has DOI.
The DOI is 10.1109/3DIMPVT.2012.36.
And it is located on the bottom of first paper.

**Comment by jkitchin** [comment]
Sure enough. That is a DOI pattern that isn't currently supported. I added some support for it in 32a1844c58cf4a6c8665e5e1b70b1e534027349b.

**Comment by FrostedPenguin** [comment]
Oh sorry. I didn't know there are different type of DOI.
How can I know types of DOI that org-ref support?
Sorry for bothering you.

And this is completely out of box but I just wonder that
C%3A/Users/fpenguin23/Desktop/temp/ISM.pdf
Is this right path? What is %3A stands for?

**Comment by jkitchin** [comment]
No problem. There is only one kind of doi, but there isn't a good reliable pattern for just a doi, so we match some context around it.

The current regex for a doi is "dx.doi.org/\\(?1:[^]\n} \"]*\\)\\|\\(?:doi\\|DOI\\):?\\s-?\\(?1:[^]}\n \"]*\\)"

which should match these kinds of patterns

1. http://dx.do.org/doi
2. doi: doi, where the colon is optional"

%3A  is an url encoded colon.
