### ISSUE TITLE
Auto complete citations from C-c C-l menu not possible

### ISSUE THREAD

**Issue by Xparx** [jkitchin/org-ref#282]
GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-08-23
Org-mode version 8.3.5 (release_8.3.5-1116-gab21e2)
org-ref: Version 0.9.0 (git-commit 1ddb704f15e03ef9da8379068df60b935fa59dd8)

Hi,
I have for a little while now not been able to auto-complete from the insert link menu `C-c C-l cite: RET`
Before I could insert a citation link with auto complete by doing this.
Maybe I'm missing to require some package but I can't find any indication in the readme file.

Is this still possible to do? and if so, do I need any other config than these:

```
(setq org-ref-bibliography-notes "~/research/bib-notes.org"
      org-ref-default-bibliography '("~/research/bibliography.bib")
      org-ref-pdf-directory "~/research/papers/")
(setq reftex-default-bibliography '("./refs.bib" "./bibliography.bib" "~/research/bibliography.bib"))
```

Helm-bibtex seems to work ok when `C-c ]`

**Comment by jkitchin** [comment]
hm.. The first time I tried it, it did not work as you described (no
apparent completion). The second time I tried it in the same buffer
though, it did work. Have you tried it more than once in the same buffer?

Andreas writes:

> GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-08-23
> Org-mode version 8.3.5 (release_8.3.5-1116-gab21e2)
> org-ref: Version 0.9.0 (git-commit 1ddb704f15e03ef9da8379068df60b935fa59dd8)
>
> Hi,
> I have for a little while now not been able to auto-complete from the insert link menu `C-c C-l cite: RET`
> Before I could insert a citation link with auto complete by doing this.
> Maybe I'm missing to require some package but I can't find any indication in the readme file.
>
> Is this still possible to do? and if so, do I need any other config than these:
>
>     (setq org-ref-bibliography-notes "~/research/bib-notes.org"
>           org-ref-default-bibliography '("~/research/bibliography.bib")
>           org-ref-pdf-directory "~/research/papers/")
>     (setq reftex-default-bibliography '("./refs.bib" "./bibliography.bib" "~/research/bibliography.bib"))
>
> Helm-bibtex seems to work ok when `C-c ]`


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
The first time I tried this it did not do completion as you see, but I tried it again in the same buffer and then did get completion. There should not be any special packages required.

**Comment by Xparx** [comment]
For me it is persisting for several tries.
I can run `org-ref-insert-cite-with-completion` manually and it works but for some reason it does not connect to the main link insert functionality in org-mode

**Comment by jkitchin** [comment]
do you have an org-cite-complete-link function? e.g. if you put (org-cite-complete-link) in an org buffer and type C-x C-e with the cursor right after it, do you get completion offered?

**Comment by Xparx** [comment]
Yes, that will start an auto-complete for my bibliography entries and echoes in the message buffer the result.

**Comment by Xparx** [comment]
I should say that I get completion for the different cite styles such as `cite` or `citet` when doing `C-c C-l` the step after gives no auto-complete for my bib entries.

**Comment by jkitchin** [comment]
This seems to be working now.

**Comment by Xparx** [comment]
Yes, It seems to be working with my version of emacs and the org-ref version I'm using currently.
Thanks for this great package. It's really a cornerstone in my current reproducible research pipeline.

**Comment by jkitchin** [comment]
Great, glad to hear it. It is a cornerstone of my workflow too!
