### ISSUE TITLE
Support for update bibkey to a different scheme

### ISSUE THREAD

**Issue by gongzhitaao** [jkitchin/org-ref#283]
I think this might be a quite useful feature to incorporate into `org-ref` given its current ability.

Suppose currently I'm using `firstnameYYYY` as my BibTex key.  But later I found it insufficient.  So I want to update to `firstnameYYYY-firsttitleword`.

In this case, we need to do the following things:
1. rename linked PDF file, if any.
2. rename linked note file, if any.
3. update the bib database

Assumptions:
1. PDF and note are linked to entry by BibTex key
2. The current bib database is valid.

**Comment by jkitchin** [comment]
That does sound useful. I think this would only be an issue for merging bibtex files though. org-ref should already prompt you to modify the key if it detects an identical key when adding bibtex entries by their doi.

The note file could be tricky. I don't use these, but there are two ways to have notes, in individual files or in one big file I think.

I would consider a pull request for this function if you want to try it.

**Comment by gongzhitaao** [comment]
Yeah, I agree the note part is trickier.
I'd love to contribute a PR but I don't much time during the semester.  If no one else is interested till then, I could probably try during the winter break :smile:

**Comment by jagrg** [comment]
I've tried something similar before. The command only shows you the bad keys. It won't replace old keys with new keys and only works with all notes in a single file.

```elisp
(defun org-ref-doctor ()
  "Check for bad note and pdf keys."
  (interactive)
  (let ((keys '())
	(pkeys (mapcar (lambda (x)
			 (replace-regexp-in-string "\\.pdf$" "" x))
		       (directory-files org-ref-pdf-directory nil "\\.pdf$")))
	(bibkeys (bibtex-completion-candidates)))
    (setq allkeys (mapcar (lambda (x)
			    (cdr (assoc "=key=" x)))
			  bibkeys))
    (setq badkeys (set-difference pkeys allkeys :test 'equal))
    (with-temp-buffer
      (insert-file-contents org-ref-bibliography-notes)
      (save-restriction
	(goto-char (point-min))
	(while (re-search-forward "^[ \t]*:Custom_ID: \\(.+\\)$" nil t)
	  (when (thing-at-point 'symbol)
	    (let ((key (thing-at-point 'symbol t)))
	      (when (not (-contains? allkeys key))
		(push (cons key (point)) keys))))))
      (helm :sources `(,(helm-build-sync-source "Bad pdf keys"
			  :candidates (if badkeys badkeys '("No bad keys"))
			  :action (lambda (candidate)
				    (dired
				     (concat org-ref-pdf-directory "/" candidate "\.pdf"))))
		       ,(helm-build-sync-source "Bad note keys"
			  :candidates (lambda ()
					(if keys keys '("No bad keys")))
			  :action (lambda (marker)
				    (switch-to-buffer
				     (find-file-noselect org-ref-bibliography-notes))
				    (goto-char marker)
				    (org-show-entry))))))))
```

**Comment by jkitchin** [comment]
I think this will be a user specific solution each time. It doesn't sound like something org-ref can generalize.
