### ISSUE TITLE
org-ref inserting invalid link to #+NAME

### ISSUE THREAD

**Issue by floli** [jkitchin/org-ref#285]
Hello,

Sorry for this all too frequent support requests...

I have this org document
```
#+NAME: fig:GaussianExample
#+CAPTION: Gaussian Basis functions with vertex distances marked at $n \cdot \frac{1}{6}$.
#+RESULTS:
[[file:rbf-gaussian-4.pdf]]

Normal link [[fig:GaussianExample]].

Link inserted using org-ref command: ref:fig:GaussianExample
```
org-ref recognized the NAME and offered it to me when I inserted a ref link. However, it the document converts to

```
\begin{document}

\tableofcontents

\begin{figure}[htb]
\centering
\includegraphics[width=.9\linewidth]{rbf-gaussian-4.pdf}
\caption{\label{fig:orgparagraph1}
Gaussian Basis functions with vertex distances marked at \(n \cdot \frac{1}{6}\).}
\end{figure}

Normal link \ref{fig:orgparagraph1}.

Link inserted using org-ref comamnd: \ref{fig:GaussianExample}
\end{document}
```
org-ref refers the the link name, not a internal name org mode uses. Do I need to set ```(setq org-latex-prefer-user-labels t)```?

Thanks!

**Comment by jkitchin** [comment]
(setq org-latex-prefer-user-labels t) does seem to be what you need.

**Comment by floli** [comment]
Alright, I'm a bit surprised that it isn't mentioned in the documentation. Refering an image/table that have been labeled with #+NAME seem to be a pretty standard use case.

**Comment by jkitchin** [comment]
Seems like it, but I always use labels ;) I updated the ref link section of the documentation to note this. Thanks for alerting me to it, and providing the solution!

**Comment by floli** [comment]
Alright then!
