### ISSUE TITLE
doi-utils-add-bibtex-entry doesn't work

### ISSUE THREAD

**Issue by EmperorDali** [jkitchin/org-ref#286]
Attempting to add a bibtex entry by DOI doesn't work.

Steps to reproduce:

`emacs -Q`

execute this minimal configuration (adjusting paths to .bib files/PDF directory):

```
  (add-to-list 'load-path "~/.emacs.d/org-ref")
  (add-to-list 'load-path "~/.emacs.d/elpa/dash-20160820.501")
  (add-to-list 'load-path "~/.emacs.d/elpa/f-20160815.1253") 
  (add-to-list 'load-path "~/.emacs.d/elpa/s-20160711.525")
  (add-to-list 'load-path "~/.emacs.d/elpa/hydra-20160828.154") 
  (add-to-list 'load-path "~/.emacs.d/elpa/parsebib-20151006.232")
  (add-to-list 'load-path "~/.emacs.d/elpa/helm-20160908.17")
  (add-to-list 'load-path "~/.emacs.d/elpa/helm-core-20160908.25")
  (add-to-list 'load-path "~/.emacs.d/elpa/helm-bibtex-20160823.900")
  (add-to-list 'load-path "~/.emacs.d/elpa/biblio-20160901.1115")
  (add-to-list 'load-path "~/.emacs.d/elpa/biblio-core-20160901.1115")
  ;; make sure you have dash, helm, helm-bibtex, ebib, s, f, hydra and key-chord
  ;; in your load-path
  (require 'dash)
  (require 'helm)
  (require 'org-ref)

  (setq reftex-default-bibliography '("~/work/papers/papers.bib"))

  ;; see org-ref for use of these variables
  (setq org-ref-bibliography-notes "~/work/papers/notes.org"
    org-ref-default-bibliography '("~/work/papers/papers.bib")
    org-ref-pdf-directory "~/work/papers/files/")

  ;; open pdf with system pdf viewer (works on mac)
  (setq bibtex-completion-pdf-open-function
    (lambda (fpath)
      (start-process "open" "*open*" "open" fpath)))

  (setq bibtex-completion-bibliography "~/work/papers/papers.bib"
    bibtex-completion-library-path "~/work/papers/files/"
    bibtex-completion-notes-path "~/work/papers/notes.org")

  (require 'doi-utils)
```

Execute

> M-x doi-utils-add-bibtex-entry

Enter

> 10.1038/nmeth992

Emacs prints

>  Contacting host: dx.doi.org:80
>  Making url-mime-accept-string local to  _http dx.doi.org:80_ while let-bound!

and then hangs until `C-g`. No entry is added to the .bib file.

Version Info:

GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G31)) of 2016-08-29
Org-mode version 8.2.10 (release_8.2.10 @ /usr/local/Cellar/emacs/25.1-rc2/share/emacs/25.1/lisp/org/)
org-ref: Version 0.9.0 (git-commit 873337642b9b312803ae743d0d636947e74470b1)
Darwin CIVIC-TV.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**Comment by jkitchin** [comment]
hm.. I can only partially reproduce this. I get a bibtex entry, but I get prompted for a login by nature methods. I am not sure how to handle that.
