### ISSUE TITLE
cite-Links in notes.org file do not find entry

### ISSUE THREAD

**Issue by badkey** [jkitchin/org-ref#287]
Hi all,
the cite org links do not work in my notes.org file. 

Eg, I can create a note where the from an existing citation in another org file, say  cite:oppenheim95:_zeitd_signal (this cite link does see the corresponding key in the bib file). 
This citation was created using org-ref, so the bib file was successfully found.

I can click on it, select 3 for "open notes", then the entry is created/selected. The cite link there does not see the key in the bib file. It looks like another bib file is bound to this lookup.

I also had similar problems for all cite links as I am preferring biblatex. I have overcome that by setting
 (setq bibtex-dialect (quote biblatex)).

 Any hint is appreciated.
Thanks
Jan-Mark

**Comment by jkitchin** [comment]
what do you see if you run M-x org-ref in the notes file? It sounds like there might be another bibliography defined in the file.

**Comment by badkey** [comment]
M-x org-ref says via *helm*:
Bibliography
No bibliographystyle found.
Using these bibtex files: nil
I was not aware of this debugging option, thanks.

Uh! For some reasons I deleted the org-ref-default-bibliography entry. So
(setq  org-ref-default-bibliography reftex-default-bibliography)
helped a lot.
BTW, thanks for this great piece of software.

Jan-Mark

**Comment by jkitchin** [comment]
no problem, glad it is useful!
