### ISSUE TITLE
conflicts with org module org-ctags

### ISSUE THREAD

**Issue by junfx** [jkitchin/org-ref#288]
If org-ctags is enabled, click citation, select "3. open note", the minibuf asks to specify a tag file.
If call command org-ref-open-bibtex-notes on a bib entry in a .bib file, a new note entry, which already exist, created in note file.
I just want to see what org-ctags is (**not a user**), so I disable it, and org-ref works again.

**Comment by jkitchin** [comment]
weird. Do you know what triggers that? What backend are you using (helm, ivy, etc...)
