### ISSUE TITLE
doi-add-bibtex-entry giving "error in process filter message" for a journal in Wiley Online Library

### ISSUE THREAD

**Issue by JoshOBrien** [jkitchin/org-ref#289]
I've just started using org-ref, and am learning my way around it.

When using `doi-add-bibtex-entry` on articles from the journal [Ecology](http://esajournals.onlinelibrary.wiley.com/hub/journal/10.1002/%28ISSN%291939-9170/) (for example) I do succeed in getting a BibTeX entry, but do not get a downloaded pdf. Instead, emacs hangs and I get a message like:

```
error in process filter: invalid date: 04-Oct-2084 20:00:36.00 GMT
```

Here is an example DOI that gives me that error: `10.1002/ecy.1507`

The date and time in the error message have continued to advance as I've retried this over the past few days. Also, DOI's for articles from many other journals do succeed in getting me downloaded pdfs.

Any idea what might be going on? If you can't reproduce this, please let me know what other info might be helpful.

**Comment by jkitchin** [comment]
That is an error on Wiley's side as far as I know. I don't know if it can be fixed on the org-ref side. I would download the pdf manually and name it by the entry key.

**Comment by JoshOBrien** [comment]
You're right --- it seems to be an issue for Wiley's journals more generally. And getting the BibTeX reference is the main thing, so at least that works. I'll just carry on using `doi-add-bibtex-entry` and being ready with `C-g C-g` to unhang when the article happens to be a Wiley product.

Thanks for `org-ref`!

**Comment by jkitchin** [comment]
This is such a weird issue. The doi you suggest above seems to work fine now. I have seen that process filter error before, but it seems to come from deep inside the url code in emacs, and I have neither found where, nor how to handle it.  Probably the fix is to do this asynchronously with a timer to kill it if it takes to long. That will not happen at least this year by me though.
