### ISSUE TITLE
Feature request: customizing the header for org-ref-open-bibtex-notes

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#29]
I'm starting to play with org-ref, and I would like to change the way the header is generated in `org-ref-open-bibtex-notes`. I've looked at the code and it's hard coded at the moment. Would there be a way to customize it, for instance by having a custom function that could be called with an alist containing the values of the fields?

Here is an example of a function I would use:
``` emacs-lisp
(defvar my-org-ref-note-header
  (lambda (f)
    (let
        ((title (cdr (assq 'title f)))
         (author (cdr (assq 'author f)))
         (year (cdr (assq 'year f))))
      (format "\n ** %s (%s, %s)" title author year))))
```

**Comment by jkitchin** [comment]
What is f in your function? the bibtex entry? That is the only thing that makes sense to me is to provide a user option function that will either take a parsed bibtex entry or operate on the entry at point to construct the notes heading.

This is kind of a standalone function in org-ref. You could just write your own version to do what you want. It is used in one place in org-ref, and that one place could be replaced with a user-defined function. This is kind of hacky, but I suggest that after you load org-ref, you just redefine the function  or advise the function.

**Comment by brabalan** [comment]
I've kept looking into this, and I realize you have already implemented what I need in `org-ref-reftex-format-citation`. Would you accept a patch that rewrites `org-ref-open-bibtex-notes` using it?

**Comment by jkitchin** [comment]
sure, this could be a nice solution. I put some comments in the other pull request. I am closing this one.
