### ISSUE TITLE
arxiv-add-bibtex-entry doesn't produce clean bibtex entry (org-ref-clean-bibtex-entry)

### ISSUE THREAD

**Issue by leezu** [jkitchin/org-ref#290]
First thanks for this nice piece of software!

When using `arxiv-add-bibtex-entry` or `arxiv-get-pdf-add-bibtex-entry` the resulting bibtex entry is not clean in regards to `org-ref-clean-bibtex-entry`. Especially the bibtex key created by `arxiv-add-bibtex-entry` changes when running  `org-ref-clean-bibtex-entry` which "unlinks" previous notes.

I wonder why `org-ref-clean-bibtex-entry` is not automatically run when adding the bibtex entry?

**Comment by jkitchin** [comment]
There is no reason it couldn't be run I think. I don't use the arxiv code in org-ref, so if you want to try adding it, and make sure it works as expected, I would take a pull request for it.
