### ISSUE TITLE
Documentation update about ref:xxx with CUSTOM_ID

### ISSUE THREAD

**Issue by gongzhitaao** [jkitchin/org-ref#292]
With the latest version of `org-ref`,  the `ref:sec:one` seems to play well with `CUSTOM_ID`. 

```org
Please see Section ref:sec:one.

* Section One
  :PROPERTIES:
  :CUSTOM_ID: sec:one
  :END:
```

When exported to PDF, the `ref:sec:one` works well.  I think the documentation  in `org-ref.org` about this may need to be updated.  Specifically the following

>  A brief note about references to a section. This only works if you put a label in the org-mode headline. you must use a CUSTOM_ID and a CUSTOM_ID link. For example section #citations has a CUSTOM_ID of citations. Section ref:sec-misc has a label link in the headline. That works, but is not too pretty.

**Comment by jkitchin** [comment]
Thanks. I just pushed an update to the docs for this.
