### ISSUE TITLE
doi-utils-add-bibtex-entry-from-doi returns nil instead of empty

### ISSUE THREAD

**Issue by zeltak** [jkitchin/org-ref#295]
Hi!

i just noticed recently that helm-bibtex was adding many `nil` test entries when i used it to add references. further investigation led me to find that the `doi-utils-add-bibtex-entry-from-doi` function is adding the word 'nil' in areas that its not finding any data such as `number =	 {nil},`. this is an example of a bib entry using the  `doi-utils-add-bibtex-entry-from-doi`  from DOI: 10.1016/j.chemosphere.2015.06.091

```
@article{landau-2015-nitrog-dioxid,
  author =	 {D. Landau and L. Novack and M. Yitshak-Sade and
                  B. Sarov and I. Kloog and R. Hershkovitz and
                  I. Grotto and I. Karakis},
  title =	 {Nitrogen Dioxide Pollution and Hazardous Household
                  Environment: What Impacts More Congenital
                  Malformations},
  journal =	 {Chemosphere},
  volume =	 139,
  number =	 {nil},
  pages =	 {340-348},
  year =	 2015,
  doi =		 {10.1016/j.chemosphere.2015.06.091},
  url =		 {http://dx.doi.org/10.1016/j.chemosphere.2015.06.091},
  DATE_ADDED =	 {Thu Sep 22 15:07:44 2016},
}
```

i was wondering if there was anyway to either have  'doi-utils-add-bibtex-entry-from-doi'  insert an empty {} instead of nil or perhaps have the org-ref clean util get an option to clean all nil values?

best!

z

**Comment by jagrg** [comment]
I'm not sure that org-ref adds nil to empty fields. Maybe @jkitchin would know. Anyway, here's something you could try:

```elisp
(defun org-ref-remove-nil ()
  (save-restriction
    (bibtex-narrow-to-entry)
    (bibtex-beginning-of-entry)
    (while (re-search-forward "\{nil\}" nil t)
      (replace-match "{}"))))

(add-to-list 'org-ref-clean-bibtex-entry-hook 'org-ref-remove-nil)
```

**Comment by jkitchin** [comment]
It sort of is org-ref, since the values it tries to put into the entry are nil in some cases, but it is a "feature" to me, because many just released articles are missing issue/volume/pages and this makes it easy to update them with M-x doi-utils-update-field.

Your case is a minor issue, since it is a reference just missing an issue number, presumably because the journal doesn't use them.

**Comment by zeltak** [comment]
thx john, i see now.
it does actually happens in almost every reference i have in many fields (i guess especially when the paper has just been accepted etc). when i try to create a bibliography list for a paper i have to manually remove all nil entries in many fields. i guess i can just use jagrg neat little solution!

thx guys

Z

**Comment by jkitchin** [comment]
the problem is you don't want to remove them if they belong there and there just isn't data available. it is tedious (my opinion of course ;) to add the fields later, and easier to update existing fields.

**Comment by zeltak** [comment]
yeah i agree. what i would love is just an option to keep the entry yet remove the nil with whitespace. does that make sense? so the entry from above would look like this

```
@article{landau-2015-nitrog-dioxid,
  author =   {D. Landau and L. Novack and M. Yitshak-Sade and
                  B. Sarov and I. Kloog and R. Hershkovitz and
                  I. Grotto and I. Karakis},
  title =    {Nitrogen Dioxide Pollution and Hazardous Household
                  Environment: What Impacts More Congenital
                  Malformations},
  journal =  {Chemosphere},
  volume =   139,
  number =   {},
  pages =    {340-348},
  year =     2015,
  doi =      {10.1016/j.chemosphere.2015.06.091},
  url =      {http://dx.doi.org/10.1016/j.chemosphere.2015.06.091},
  DATE_ADDED =   {Thu Sep 22 15:07:44 2016},
}
```

where the above ``  number =   {nil},`` would be ``  number =   {},``

**Comment by jagrg** [comment]
You can add the function to the end of the list with the append argument:

`(add-to-list 'org-ref-clean-bibtex-entry-hook 'org-ref-remove-nil t)`
