### ISSUE TITLE
doi-add-bibtex-entry says the doi is already in file

### ISSUE THREAD

**Issue by aydemirfb** [jkitchin/org-ref#296]
I want to add a bibtex entry to my .bib file for the doi 10.1007/978-3-319-39696-5_1. However, I get a message that says "10.1007/978-3-319-39696-5_1 is already in this file" even though it is not, there is an entry whose doi is 10.1007/978-3-319-39696-5_1**5**.

**Comment by jkitchin** [comment]
That is what happens ;) I just pushed 608f782 to fix it.

**Comment by aydemirfb** [comment]
thanks!
