### ISSUE TITLE
Easy configuration to work with multiple/different projects?

### ISSUE THREAD

**Issue by boudiccas** [jkitchin/org-ref#297]
Is it possible for 'org-ref' to be easily configured to work with different projects? Currently I have it configured to work on 'death.org' and all the files relating to that project are named after 'death.foo'. 

I also want to work on a project called 'hair.org', and later on in the year i will be working on 'sleep.org', so is it easy for me to set it up so that I can easily swap projects please?

**Comment by jkitchin** [comment]
I switch projects all the time with no issue. If they use different bibliographies, just put bibliography links in each file, e.g. death.bib, hair.bib,... If they all use the same bib file, its even easier, just make it the default one.

**Comment by boudiccas** [comment]
So are you saying that you set up a new instance of org-ref for each new project, and comment out the previous one in your init file please? Or is there some other, better, way of doing it?

**Comment by jkitchin** [comment]
no, that is not what I said at all. There is only one init file, and all it does is specify a default bibliography. If you put a bibliography link in your org file, it has precedence and the default in the init is ignored. so in death.org, put the link bibliography:death.bib, and in hair.org put the link bibliography:hair.bib, and each one will automatically be used in that file.
