### ISSUE TITLE
At first start I get: Symbol's function definition is void: acs-pdf-url

### ISSUE THREAD

**Issue by icymist** [jkitchin/org-ref#3]
Immediately after installation, at first start I get the (error?) message Symbol's function definition is void: acs-pdf-url.

This disappears when I comment out the line
(acs-pdf-url  "http://pubs.acs.org/doi/abs/10.1021/nl500037x")
in doi-utils.el

How essential is this line?

**Comment by jkitchin** [comment]
it is unessential, and should not be in the .el file. I just pushed a fix for that.
