### ISSUE TITLE
No information in the modeline for this entry

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#30]
I have the following entry:

``` bibtex
@Report{HondaYoshidaBerger2014,
  year =         2014,
  type =         {Technical Report},
  institution =  {Imperial College},
  number =       {2014/2},
  title =        {Control in the $\pi$-Calculus},
  author =       {Kohei Honda and Nobuko Yoshida and Martin Berger}
}
```

When I create a link to is (using helm-bibtex) and put my cursor on the entry, I see this in the modeline:
```
, "", , : ()
```

org-ref works for other entries, so I'm wondering if there is something wrong with this one or with org-ref.

Note that I can still jump to the bibtex entry or open the pdf using org-ref, it seems that the problem is in the displaying of the information.

**Comment by jkitchin** [comment]
There probably is not a message for Reports. I guess the other ones it
works for are articles.

Alan Schmitt writes:

> I have the following entry:
>
> ``` bibtex
> @Report{HondaYoshidaBerger2014,
>   year =         2014,
>   type =         {Technical Report},
>   institution =  {Imperial College},
>   number =       {2014/2},
>   title =        {Control in the $\pi$-Calculus},
>   author =       {Kohei Honda and Nobuko Yoshida and Martin Berger}
> }
> ```
>
> When I create a link to is (using helm-bibtex) and put my cursor on the entry, I see this in the modeline:
> ```
> , "", , : ()
> ```
>
> org-ref works for other entries, so I'm wondering if there is something wrong with this one or with org-ref.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/30

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by brabalan** [comment]
I understand. I'll try to see if I can extend `org-ref-bib-citation` to cover more types.

**Comment by jkitchin** [comment]
Are you sure Report is the right type? a @techreport is recognized, but I am not sure about a @report. you might be able to add to org-ref-bibliography-entry-format  to get it to work. see

(defcustom org-ref-bibliography-entry-format
  '(("article" . "%a, %t, <i>%j</i>, <b>%v(%n)</b>, %p (%y). <a href=\"%U\">link</a>. <a href=\"http://dx.doi.org/%D\">doi</a>.")

    ("book" . "%a, %t, %u (%y).")
    ("techreport" . "%a, %t, %i, %u (%y).")
    ("proceedings" . "%e, %t in %S, %u (%y).")
    ("inproceedings" . "%a, %t, %p, in %b, edited by %e, %u (%y)"))
  "String to format an entry.  Just the reference, no numbering at the beginning, etc... see the `org-ref-reftex-format-citation' docstring for the escape codes."
  :type 'string
  :group 'org-ref)

**Comment by brabalan** [comment]
Report is a biblatex entry type (see http://ctan.mines-albi.fr/macros/latex/contrib/biblatex/doc/biblatex.pdf section 2.1.1, page 11).

Customizing this works when I apply https://github.com/jkitchin/org-ref/pull/32. Thanks a lot!

**Comment by jkitchin** [comment]
great! Maybe one day the scientific publishing world will embrace biblatex! best wishes
