### ISSUE TITLE
doi: link does not syntax correctly

### ISSUE THREAD

**Issue by stardiviner** [jkitchin/org-ref#301]
For example:
```org
[fn:1]  T. Winograd (1972). "Understanding natural language". Cognitive
Psychology. 3 (1): 1–191. doi:10.1016/0010-0285(72)90002-3
```
`doi:10.1016/0010-0285(72)90002-3` It only syntax `doi:10.1016/0010-0285(72)` as link because of `(72)`.

**Comment by jkitchin** [comment]
you should try [[doi:10.1016/0010-0285(72)90002-3]]. That is an org-mode syntax, not an org-ref issue.
