### ISSUE TITLE
Some recent change broke "Open PDF file (if present)" on helm action menu

### ISSUE THREAD

**Issue by JoshOBrien** [jkitchin/org-ref#303]
I've recently updated packages from MELPA. When I subsequently did `C-c ]`  (to execute `org-ref-helm-insert-cite-link`), highlighted a reference (for which I've got an appropriately named pdf stored in `org-ref-pdf-directory`,  pressed `<TAB>`, and then `<f2>` to pick the action titled "Open PDF file (if present)", I only got the message `"NO PDF(S) found"`.

I've fixed the problem for myself by adding this line to my `.emacs`, but figure this is worth reporting in case anyone recognizes why this may have recently broken:

    (setq  bibtex-completion-library-path org-ref-pdf-directory)
    ;; On my Windows box, with my current setup, if I don't add this line, the pdf
    ;; will get opened as a text file.
    (setq bibtex-completion-pdf-open-function 'helm-w32-shell-execute-open-file)

**Comment by jkitchin** [comment]
Thanks for reporting it, and the solution!

**Comment by JoshOBrien** [comment]
You bet. I only wish I was better versed in Emacs, so I could've traced the breaking change. Will get there one of these days!

**Comment by sjLambda** [comment]
`C-c ]` followed by `RET` or `C-j` used to insert cite, now it tries to open the ref using the url or the pdf.  Did the `helm-execute-persistent-action` get redefined in helm or org-ref? Or is this a switch that I accidentally turned on/off?

**Comment by jagrg** [comment]
@sjLambda, helm-bibtex changed this recently, but you can still change the default action to something else. See helm-bibtex for instructions.

**Comment by sjLambda** [comment]
@jagrg, thanks for tip. I saw in the git history that the default action changed, but no explanation given for why.

**Comment by JoshOBrien** [comment]
Just for the record, the patch applied in #311 may have fixed the issue reported by @sjLambda but doesn't help with the problems I reported in the OP.

**Comment by JoshOBrien** [comment]
OK, I just updated to most recent versions of all my installed emacs packages, and I no longer see the problems reported in the OP.  Works like a charm. Thanks all!
