### ISSUE TITLE
Opening pdf at a specific page

### ISSUE THREAD

**Issue by nasseralkmim** [jkitchin/org-ref#310]
When writing notes about a book or article, It is very convenient for future reference to have the exact page where it came from.

Is there a way for adding the reference to a specific page in a pdf? And then open it at this exact page later with the open-pdf action?

**Comment by jkitchin** [comment]
I amnot sure there is a reliable, cross-platform way to do this. There is some possibility to do it on a Mac, via the org-mac-link package I think, but some years ago I didn't find it as useful as I hoped. For this to work, you would have to extend the cite link syntax to include the page number I think, and extend the open-pdf action to use that. That isn't something I want to pursue any time soon, but if you do, and find it works well, I would consider a pull request.

**Comment by nasseralkmim** [comment]
@jkitchin True, after a couple of articles reviews I realized that, indeed, not as practical as it sounds. A link to the pdf is plenty. Thanks for this great package, professor.
