### ISSUE TITLE
Adding custom cite types

### ISSUE THREAD

**Issue by jackjackk** [jkitchin/org-ref#314]
I'm using multibib and I would like to define a new cite type called citemet.
In my emacs conf I added
```
  (add-to-list 'org-ref-cite-types "citemet")
```
I now have it in the helm interface (C-u C-c ]), but emacs doesn't color it properly (in green) or treat it as a link. How do I really add a custom cite type?
Thanks

**Comment by jagrg** [comment]
Try this: `(org-ref-define-citation-link "citemet")`

**Comment by jackjackk** [comment]
Thanks, it worked!
