### ISSUE TITLE
Avoiding space between citation and preceding word

### ISSUE THREAD

**Issue by jackjackk** [jkitchin/org-ref#315]
How can I produce the following latex code:
```
text\cite{aaa}
```
using org-ref? If I leave no space before the cite:aaa, the latter joins with the preceding word.

**Comment by jagrg** [comment]
Here's one way to do it:

`(setq org-entities-user '(("nospace" "" nil "")))`

`text\nospace{}cite:aaa` (exports to `text\cite{aaa}`)

Why do you need this?

**Comment by jkitchin** [comment]
I also wonder why you need it. If you use something like natbib, it should be unnecessary.

**Comment by jackjackk** [comment]
Thanks for your answers, from which I assume I'm doing something awfully wrong. I'm using plain bibtex, with naturemag style with nature class, where citations are compiled as numbered exponents. If I leave a space, the exponent looks oddly far from the preceding word. Thanks for the nospace trick.

**Comment by jkitchin** [comment]
You might try using \usepackage[numbers,super,sort&compress]{natbib}, I think it removes those spaces, which keeps your org-file looking nice.
