### ISSUE TITLE
org-ref-note-title-format timestamp support

### ISSUE THREAD

**Issue by leezu** [jkitchin/org-ref#317]
I wonder if it is possible to include a timestamp in the notes-template.

E.g. when having the following template:

```
"** TODO %y - %t
  OPENED: {TIMESTAMP HERE}
  :PROPERTIES:
   :Custom_ID: %k
  :END:"
```

I would like to include a timestamp at position `{TIMESTAMP HERE}`. 

Looking at the documentation of `org-ref-reftex-format-citation` this seems not to be suported?

**Comment by jkitchin** [comment]
It isn't possible in the template. You could adapt org-ref-open-notes-function though to add a property to an entry on opening. You could add something like
(org-entry-put (point) "Opened" (current-time-string)).
