### ISSUE TITLE
citations in html export

### ISSUE THREAD

**Issue by jackjackk** [jkitchin/org-ref#319]
Is it already possible?

Thanks,

Giacomo

**Comment by jkitchin** [comment]
yes. some basic export is already possible. There is not much support for styling the bibliography, but you can customize org-ref-bibliography-entry-format to fine-tune it.

**Comment by jackjackk** [comment]
I'm using
Org-mode version 8.3.6 (8.3.6-7-g4d7d52-elpaplus)
org-ref: Version 0.9.0 (git-commit 9953d022d2113fdce8eab54e7d6e1656058c5323)

still if I export to html cite:XXX, it becomes:
```
<a class="org-ref-reference" href="#XXX">XXX</a>
```
without expanding the reference. it seems that the format in org-ref-bibliography-entry-format is not actually used. what should I do?
thanks
g

**Comment by jagrg** [comment]
You also need to include the bibliography link: `bibliography:xxx.bib`.

**Comment by jackjackk** [comment]
Thanks jagrg.
I added a
```
bibliography:YYY.bib
```
and now the bibliography appears, and the links inside the text work.  still, these links appear as the raw strings referring to each bibitem, and to get to the actual link of the artilce I need first to go to the separate bibliography and then to click "link". Is it possible to have directly the link in the text, perhaps formatted as authoryear?
Thanks,
g

**Comment by gongzhitaao** [comment]
Currently I'm using `bibtex2html` to export citations in HTML.  A demo is available http://gongzhitaao.org/orgcss/.  The disadvantage is the extra dependency on `bibtex2html`.

**Comment by jkitchin** [comment]
@jackjackk I don't understand what it is you want. Is it that the link in the text would say, go directly to the doi or something?

In general html formatting of citations is pretty limited. You might check out http://kitchingroup.cheme.cmu.edu/blog/2015/12/03/Exporting-numbered-citations-in-html-with-unsorted-numbered-bibliography/ for some ways to get more control over the export.

**Comment by jackjackk** [comment]
@gongzhitaao thanks for your css example, very neat. I'll check bibtex2html too.

@jkitchin thanks for your interest and link. Yes, ideally I would imagine a clickable "(Kitchin et al., 2016)" which, if clicked, opens the corresponding journal web page. I guess this would require a deep understanding of the code shown in the post you linked, which in turn would require some serious study of elisp. I'll need to capture these tasks in my agenda w/ a someday keyword.

**Comment by jkitchin** [comment]
If you don't care to have the bibliography at the end, it is not too hard to get what you want for a single citation. you would just have to see if there was a doi in the corresponding bibtex entry, and make a url to http://dx.doi.org/doi in the export functions. It gets a little trickier for books, and other references perhaps.
