### ISSUE TITLE
hyperref support (autoref/nameref)

### ISSUE THREAD

**Issue by x4121** [jkitchin/org-ref#320]
Support for `\autoref{$ref}` and `\nameref{$ref}` instead of just `\ref{$ref}` would be nice.

**Comment by jkitchin** [comment]
I just pushed this addition. Check it out!

**Comment by x4121** [comment]
Thanks, works as a charm

**Comment by cvanelteren** [comment]
@jkitchin  I am running an issue where my refs are not recognized when exporting to pdf. 
i.e. 

```org-mode
#options: :num nil
*  Some section
#+name: sec:intro

ref:sec:intro
```
I have also tried setting `custom_id`, is there a reference in the docs to refer using this context?
