### ISSUE TITLE
how to use default bibliography to export pdfs

### ISSUE THREAD

**Issue by lihebi** [jkitchin/org-ref#321]
Hi,

I have a list of my bib files in my default bibliography(`org-ref-default-bibliography`), and it works to insert citations from all of them. But when exporting pdf, I have to add a `bibliography:xxx.bib,yyy.bib` link for all of the used bib files, to make the citation work on the pdf. That is not very convenient in the case of a lot of bib files and a lot of projects.

Is there a way to export all the defualt bibliography, or the used ones, to the latex? I'm aware that helm-bibtex can [Create a BibTeX file containing only specific entries](https://github.com/tmalsburg/helm-bibtex#create-a-bibtex-file-containing-only-specific-entries), but that seems not to solve this issue.

Any input is appricitated!

Thanks,
Hebi

**Comment by lihebi** [comment]
One more point: if I do use a bibliography:xxx.bib link to generate pdfs, it hides the default bibliography files, so I can no longer access to those files easily.

**Comment by jkitchin** [comment]
There is a command called org-ref-extract-bibtex-entries that almost does what you want. It will extract the entries to a block in the org-file, and then you can tangle or copy the entries to the file of your choice, and put a bibliography link to that.

You can't have it both ways though, you either get the default bibliographies, or the bibliography in the link. I don't see a way around that.

**Comment by lihebi** [comment]
Thanks for the quick reply. I really appriciate it.

I tried it just now. It did the job, but not very clean for this task:

1. It extract entries into the buffer. I have to copy them to a bib file and link to that file.
2. Later if I want to refer to entries inside other bib files, I need to first remove the link, then insert the citation, then redo the extraction, refile them, and get the link back.
3. I made unecessary copy of bib entries.

I have two rough ideas as alternatives:

1. I would rather not to extract the entries, but the files containing those entries. Then I can add those files in the bibliography link
2. Maybe when org mode exporting pdfs, add a hook to check whether a bibliography is present, if not, add the content of the default bibliography variable.

**Comment by jkitchin** [comment]
This commit 357d05f makes what you want do what is needed. org-ref-insert-bibliography-link will find the files in org-ref-default-bibliography and local files and insert a bibliography link. It is lightly tested. Test it out and let me know if it works for you.

I have used a hook before to automatically add bibliography links, and have never been satisfied with it, and always take it out.

**Comment by lihebi** [comment]
Awesome, it works! Thanks.
