### ISSUE TITLE
Small issue when adding new references to an existing cite: command

### ISSUE THREAD

**Issue by jmburgos** [jkitchin/org-ref#323]
Hi John,
I have a small issue that first I thought was caused by helm-bibtex, but the source is actually org-ref (I am using both packages).  It happens when adding a new reference to an existing cite command . Here the underdash (_) indicates the position of the cursor. Let's say you want to cite a couple of references. You do helm-bibtex, and insert the first one, and get something like this.

parencite:Smith2008_

Then you do helm-bibtex again and insert the second one, and you get this:

parencite:Smith2008Smith2009,_

... with the comma that should separate both references placed after the second one. If you remember to insert a blank space after the first reference

parencite:Smith2008 _

...you get the comma in the right place:

parencite:Smith2008,Smith2009.

Would it be possible to make org-ref a bit smarter in this regard, so if you do not insert the space then the comma is placed in the right position?  
Many thanks,

Julian

**Comment by jmburgos** [comment]
Actually, the behaviour is a bit more erratic.  If you add a third citation the comma is inserted after the citation even if you add a space between the second and third citations:
Do helm-bibtex and insert the first citation:

parencite:Smith2008_   

Add an space and do helm-bibtex.  The comma gets in the right place.

parencite:Smith2008,Smith2009

Add an additional space and do helm-bibtex to add the third citation, and the comma appears after the last citation.

parencite:Smith2008,Smith2009Smith2010,

Strangely. if you try to be smarter and add a comma instead of a space, a new comma is placed *before* the new reference.

**Comment by jkitchin** [comment]
Weird. It seems to be an issue in org-ref-bibtex-completion-format-org I guess. I wonder when this started happening; that function hasn't been changed in a while. I pushed e37c69a55 which fixes two small issues in that function, one that you reported, and one when the cursor is on a cite.

**Comment by jmburgos** [comment]
Thanks! Works like a charm.
