### ISSUE TITLE
ref:tab:test in HTML no numbering

### ISSUE THREAD

**Issue by gongzhitaao** [jkitchin/org-ref#327]
Is it possible to export `ref:tab:test` to numbers instead of names during HTML export.  I understand it is tricky, but might be a good feature so that I don't need to change the docs when exporting to HTML.

Demo
```org
This is a table ref:tab:hello.

#+CAPTION: Hello World
#+NAME: tab:hello
| Hello | World |
|-------+-------|
|     1 |     2 |
```

When exported to HTML,  it looks like

```html
This is a table tab:hello <!-- this, I may want it to appear like table [1] -->

Table 1: Hello World
Hello	World
1	2
```

**Comment by jkitchin** [comment]
This does not seem possible with the standard export machinery. It would require using a filter, or some post-processing code, not a regular export.

**Comment by jkitchin** [comment]
I seem to have spoken too early ;) I discovered the ref links don't point to the anchors like they used to, and in the process of fixing that, got numbers it seems! I pushed the code that does it. Give it a try!

**Comment by gongzhitaao** [comment]
Thanks for the quick fix!!  It worked for my test cases. :smile:

**Comment by tdehaeze** [comment]
It seems it is not working for me.
When exporting the exact same org-mode code
```
This is a table ref:tab:hello.

#+CAPTION: Hello World
#+NAME: tab:hello
| Hello | World |
|-------+-------|
|     1 |     2 |
```
The label name is displays instead of the number in the HTML exported file.

Any idea why this is not working for me?

Thanks

**Comment by gongzhitaao** [comment]
@tdehaeze Not sure why, it is not working again :laughing:

**Comment by tdehaeze** [comment]
My current working setup to export both to latex and html is the following:
**For figures and tables**
```
  #+NAME: tab:name
  #+CAPTION: A simple table.
  | x |
  | 1 |
```
And reference with `[[tab:name]]`

**For equations**
```
\begin{equation}
  x(t) = a x + b \label{eq:label}
\end{equation}
```
And reference with `eqref:eq:labelname`

**For sections**
```
  * Section name
    <<sec:label>>
```
and reference with `[[sec:label]]`

Not very convenient... :laughing:

**Comment by jkitchin** [comment]
I can at least confirm that I also see what you are seeing now. I am not sure what changed. Looking back on this thread, I guess it looks like it worked once, and doesn't now. When I look at `org-ref-ref-export` I am not really sure how it could work now (or then) however. @tdehaeze thanks for the examples that do work.  

I can see an approach that uses a preprocessing hook to replace ref links to tables and sections with that org-syntax so that they export to html correctly. WDYT?

**Comment by tdehaeze** [comment]
Indeed, maybe `org-ref-ref-export` has changed since 2016.
Your approach seems good to me. Should it be implemented inside org-ref? (total emacs beginner here)

**Comment by jkitchin** [comment]
You can but a block like this in your org-file for now. This seems to work. It doesn't handle figure labels, which I assume you can do similarly. It also only works for tables with a #+name (i.e. it doesn't work if you put a label in the caption. ).
```
* build                                                            :noexport:

For html only.

#+BEGIN_SRC emacs-lisp
(let ((org-export-before-parsing-hook (lambda (backend)
					(let* ((data (org-element-parse-buffer))
					       (headline-labels (append
								 (org-element-map data 'headline
								   (lambda (hl)
								     (when (org-element-property :CUSTOM_ID hl)
								       (org-element-property :CUSTOM_ID hl))))
								 (org-element-map data 'link
								   (lambda (lnk)
								     (when
									 (and (string= "label" (org-element-property :type lnk))
									      (eq 'headline (car (org-element-property :parent lnk))))
								       (org-element-property :path lnk))))))
					       (table-labels (append
							      (org-element-map data 'table
								(lambda (tbl)
								  (when (org-element-property :name tbl)
								    (org-element-property :name tbl))))
							      (org-element-map data 'link
							      	(lambda (lnk)
							      	  (when (and (string= "label" (org-element-property :type lnk))
							      		     (eq 'table (car (org-element-property :parent lnk))))
							      	    (org-element-property :path lnk)))))))
					  ;; now we need to map over these and replace them
					  (mapc (lambda (label)
						  (goto-char (point-min))
						  (while (re-search-forward (format "ref:%s" label) nil t)
						    (replace-match (format "[[%s]]" label))))
						headline-labels)
					  (mapc (lambda (label)
						  (goto-char (point-min))
						  (while (re-search-forward (format "label:%s" label) nil t)
						    (replace-match (format "<<%s>>" label))))
						headline-labels)
					  (mapc (lambda (label)
					  	  (goto-char (point-min))
					  	  (while (re-search-forward (format "ref:%s" label) nil t)
					  	    (replace-match (format "[[%s]]" label))))
					  	table-labels)))))

  (org-open-file (org-html-export-to-html)))
#+END_SRC

#+RESULTS:
```
