### ISSUE TITLE
Groups for organizing my library

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jkitchin/org-ref#329]
Can I create different groups to organize my library. For example group "Biology" to contain my biology articles, group "Science" to contain my science articles (which my contain as well some of by "biology" articles). This exists in Mendely and Endnote.

Thanks so much for the great packge.

**Comment by jkitchin** [comment]
You can add keywords to a bibtex entry. For example you could consider this entry belongs to 4 groups that correspond to those keywords.

@article{kitchin-2015-examp,
  author =	 {Kitchin, John R.},
  title =	 {Examples of Effective Data Sharing in Scientific Publishing},
  journal =	 {ACS Catalysis},
  volume =	 {5},
  number =	 {6},
  pages =	 {3894-3899},
  year =	 2015,
  doi =		 {10.1021/acscatal.5b00538},
  url =		 { http://dx.doi.org/10.1021/acscatal.5b00538 },
  keywords =	 {DESC0004031, early-career, orgmode, Data sharing },
  eprint =	 { http://dx.doi.org/10.1021/acscatal.5b00538 },
}

If the entry is open, you an use (helm-tag-bibtex-entry) to add a keyword.

**Comment by DrWaleedAYousef** [comment]
Do the already existing keywords populate as available keywords (e.g.,
through helm) to select among them.

**Comment by jkitchin** [comment]
Try it ;) yes.

**Comment by DrWaleedAYousef** [comment]
Wonderful; but what about tree-like (directory-structure-like) groups?
For example:


- Group1
  - Group2
  - Group3
    - Group4
    - Group5


Thanks so much.

**Comment by DrWaleedAYousef** [comment]
Ok; adding several keywords virtually makes the hierarchy. But suppose I
have the following hierarchy (which is created virtually using multiple
keywords)

- Science
  + Pysics
  + Biology
  + Engineering
    * Electrical
    * Civil


My question is how to SEE this hierarchy so that it is easy to add a
paper under "Civil", which is under "Engineering", which is under
"Science". If I do not VISUALLY SEE this hierarchy (specially when it
becomes deeper and larger) it is difficult to add the keywords, even if
I see them populated by helm, as long as they appear as a single-level
list.

**Comment by jkitchin** [comment]
It doesn't make sense to me to think of it in this hierarchy. I guess what you want is to somehow select engineering, then civil, and add both? In helm you just select Engineering and press C-spc, then select civil and press C-spc to mark them, and then press enter to add them at the same time.

With tags it does not matter if you think of it as 

Engineering
  * Civil

or 

Civil
  * Engineering

Other than this, it is not possible to create a hierarchy.
