### ISSUE TITLE
Org-ref incorrectly passing bibliography to helm-bibtex

### ISSUE THREAD

**Issue by reconmaster** [jkitchin/org-ref#33]
Before migrating to helm-bibtex, `C-c ]` would look at the default bibliography when inserting a link.  Now, when using the helm-bibtex functionality `(org-ref-helm-insert-cite-link)`, it complains that:
`
user-error: BibTeX file references.bib could not be found.
`

If `helm-bibtex` is called directly after configuring `(setq helm-bibtex-bibliography "~/dropbox/bibliography/references.bib")`, there is no problem using it to inserting the `cite:reference` in the same org file.  

The code also works as is if the link `bibliography:~/dropbox/bibliography/references.bib` is placed in the file. However, I don't see why this should be necessary if helm-bibtex has no problem finding `references.bib` when the parent directory is in `BIBINPUTS`. With only one reference.bib file, I would prefer not to have to add this additional line to every file.

Adding this line also produces an unwanted inclusion of the reference file path when exporting with biblatex. Currently adding this line and then deleting before export is the workaround I am using.

**Comment by jkitchin** [comment]
This has not changed any time recently. What does this command output in a typical org-file for you:

(org-ref-find-bibliography)

and what do you have the variable org-ref-default-bibliography set to in your init file?

**Comment by jkitchin** [comment]
I think I see the issue, BIBINPUTS is some environment variable you have set? and helm-bibtex does not search it. You should use (setq org-ref-default-bibliography '("file1" "file2")) in your init files to set a default set of these. It might be possible to use something like (getenv "BIBINPUTS") and split it as needed to get that list too.

**Comment by reconmaster** [comment]
I have `org-ref-default-bibliography` set to `("~/dropbox/bibliography/references.bib")` as mentioned on the site. Evaluating `(org-ref-find-bibliography)`returns the same value. The only reason I mentioned BIBINPUTS is when using biblatex, I can do `\addbibresource(references)` and it will find the correcct bib file. I only wondered if the issue is with BIBINPUTS is that the error message I get is the name of the correct file without the proper parent directory information.  Maybe it has to do with the way org-ref passes the default bibliography to helm-bibtex? As I mentioned, none of my init file or the org paper has changed, I only upgraded org-ref to this new version supporting helm (which I like btw, just trying to figure out why this broke the `C-c ]` key).

**Comment by jkitchin** [comment]
Does that file actually exist? If not you should make it be an actual
bibtex file.

On Friday, April 17, 2015, Andrew Davis <notifications@github.com> wrote:

> I have org-ref-default-bibliography set to
> ("~/dropbox/bibliography/references.bib") as mentioned on the site.
> Evaluating (org-ref-find-bibliography)returns the same value. The only
> reason I mentioned BIBINPUTS is when using biblatex, I can do
> \addbibresource(references) and it will find the correcct bib file. I
> only wondered if the issue is with BIBINPUTS is that the error message I
> get is the name of the correct file without the proper parent directory
> information. Maybe it has to do with the way org-ref passes the default
> bibliography to helm-bibtex? As I mentioned, none of my init file or the
> org paper has changed, I only upgraded org-ref to this new version
> supporting helm (which I like btw, just trying to figure out why this broke
> the C-c ] key).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/33#issuecomment-94075046>.
>


-- 
John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by reconmaster** [comment]
It's an actual file. helm-bibtex and org-ref can find it when I use the two work around methods mentioned in the original post. I also mentioned none of my setup has changed since I was using your org-ref that initially used reftex.

**Comment by jkitchin** [comment]
Weird. Yes, I routinely use org ref with no bibliography link. 

The files get passed to helm bibtex here
https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L3211

**Comment by jkitchin** [comment]
This sounds very strange. I have these variables set in my init file

(setq reftex-default-bibliography '("~/Dropbox/bibliography/references.bib"))

;; see  [[org-ref]] for use of these variables
(setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
      org-ref-default-bibliography '("~/Dropbox/bibliography/references.bib")
      org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

(setq helm-bibtex-bibliography "~/Dropbox/bibliography/references.bib")
(setq helm-bibtex-library-path "~/Dropbox/bibliography/bibtex-pdfs")

(setq helm-bibtex-pdf-open-function
  (lambda (fpath)
    (start-process "open" "*open*" "open" fpath)))

(setq helm-bibtex-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")

I am pretty sure these are not all necessary, and that helm-bibtex-bibliography gets temporarily rebound in the org-ref-helm-insert-cite-link function. But, having it set in init.el enables helm-bibtex to work outside of org-ref.

org-ref should not be affected by BIBINPUTS at all.

**Comment by reconmaster** [comment]
Well it seems to be a problem when org-ref tries to pass its bibliography to helm-bibtex.  If I modify the the `org-ref-helm-insert-cite-link`, `C-c ]` works as expected. Not familiar enough with elisp or org-ref to understand why the let function is necessary here. If there is a dependency on helm-bibtex, shouldn't correctly setting the helm bibliography be sufficient?

``` elisp
(defun org-ref-helm-insert-cite-link (arg)
  "org-ref function to use helm-bibtex to insert a citation link.
With one prefix arg, insert a ref link.
With two prefix args, insert a label link."
  (interactive "P")
  (cond
   ((equal arg nil)
     (;let ((helm-bibtex-bibliography (org-ref-find-bibliography)))
       helm-bibtex))
   ((equal arg '(4))
    (org-ref-helm-insert-ref-link))
   ((equal arg '(16))
    (org-ref-helm-insert-label-link))))
```

**Comment by jkitchin** [comment]
I don't understand why it won't for you though. You need the let statement to enable the use of the in document bibliography preferentially, but to fall back on the default if there is no document bibliography. It does that by temporarily redefining the variable. It is not enough to just set the helm bibliography variable for that. And, the variable should take a list of files, which is what it is set to in the let statement.

Can you send me the org file you are having trouble using C-c ] in?

**Comment by reconmaster** [comment]
Thanks for helping me find the problem. I had the following commented out at the end of my *.org file.

```org
# \bibliography{ref}
``` 

Org-ref found this and was searching my local directory for the non-existent file. No changes need to be made in org-ref. This was my fault.  Thanks John!
-A

**Comment by jkitchin** [comment]
no problem!

**Comment by TammoR** [comment]
This is a similar question. I also use ox-bibtex for html export and have 

`#+BIBLIOGRAPHY: ~/Dropbox/library/library plain limit:t option:-nokeywords option:--no-abstract`

at the bottom of my document. Org-ref now tries to use this file and complains. If I change to 
`#+BIBLIOGRAPHY: /Users/tammruka/Dropbox/library/library**.bib**`, org-ref works. But then ox-bibtex does not work anymore.

Any idea how I can get org-ref to use the bibliography file that I provide elsewhere and not get irritated by the 

> #+BIBLIOGRAPHY: 

line?

**Comment by jkitchin** [comment]
The best path is probably for org-ref to not look at the  #+BIBLIOGRAPHY line at all. It is not that helpful for exporting from org-ref I think, and is only a last resort anyway.  I don't know if anyone relies on it though. Maybe I will try removing that and see if anyone complains...
