### ISSUE TITLE
Download from IEEE Xplore not working

### ISSUE THREAD

**Issue by TobiMarg** [jkitchin/org-ref#331]
When I try adding a Paper found on http://ieeexplore.ieee.org using `doi-add-bibtex-entry` the BibTex entry is created successfully, but the download of the pdf fails with the following error:

    ieee-pdf-url: Search failed: "<meta name=\"citation_pdf_url\" content=\"\\([[:ascii:]]*?\\)\">"

I'm not sure if I understand the `ieee-pdf-url` function correctly (found in #170), but it seems to download the article page and search for the above mentioned string. I checked the page and couldn't find a similar meta tag, but the download button links to `/stamp/stamp.jsp?arnumber=somenumber`, which I suppose could be used to get the pdf. So the regexp would need to be modified and `http://ieeexplore.ieee.org` prepended to the relative link.

**Comment by jkitchin** [comment]
What doi were you using?

**Comment by TobiMarg** [comment]
For example: 10.1109/35.667413
but I tried about ten different ones and no one worked.

**Comment by jkitchin** [comment]
It looks like it should be putting the bib entry in. There was an error getting raised about not finding the pdf link, which should be fixed now. It still won't find it, but it should not raise an error now.

**Comment by TobiMarg** [comment]
Yes, the bibtex entry gets created. I found a way to modify the function to get the url for the papers I tried and download the pdf. I'm just not sure if there are some urls which (still) work with the current implementation.
Should I create a pull request with this change? And if yes should I just modify the function or create a new one for this new link variant.

**Comment by jkitchin** [comment]
How about you create a new function, so that if the first one fails, the second one can succeed.
