### ISSUE TITLE
org-ref-open-bibtex-notes no longer inserts cite or pdf links in org notes file

### ISSUE THREAD

**Issue by stevenbagley** [jkitchin/org-ref#335]
I see that the code to insert the cite and pdf links is comment out. Is there another way to get the old behavior? (Maybe I am the only person who used this feature.)

**Comment by jkitchin** [comment]
There is a new feature that might help this:

In the template you can add: cite:%l and [[file:%F][%f]] and it should expand to the cite link and the pdf link.
