### ISSUE TITLE
HTML output using the equivalent of \bibentry and \nobibliography

### ISSUE THREAD

**Issue by spencerahill** [jkitchin/org-ref#336]
Using `bibentry:` and `nobibliography:`, I am able to generate in-text full citations and suppress the end-of-file full bibliography when outputted to LaTeX.  I would like to do the same for HTML output but can't figure out how.  Is that supported?

I can provide a MWE if this isn't clear enough.  Thanks!  (My use case is generating a list of my publications, separated into various categories, for both the PDF and HTML versions of my C.V. from the same .org file.)

**Comment by jkitchin** [comment]
This is not currently supported. You can change how the bibentry link (in org 9) exports like this:

```
#+BEGIN_SRC emacs-lisp :results silent
(org-link-set-parameters
 "bibentry"
 :export (lambda (key desc backend)
	   "Convert KEY to a bibtex entry"
	   (org-ref-get-bibtex-entry-html key)))
#+END_SRC
```

That may be close enough for you. If not, dig into org-ref-get-bibtex-entry-html for clues on how to get what you want.

**Comment by spencerahill** [comment]
Thanks for the fast response.  Yes, the `org-link-set-parameters` mod gets me most of the way there for bibentry...I'll try tweaking it to get exactly what I'm looking for.  But my elisp is pretty bad, so we'll see how that goes.

Do you have any comparable starting ideas for getting `nobibliography` to work for HTML?  Thanks!

**Comment by jkitchin** [comment]
did you try using the nobibliography link? I am not to familiar with this. It uses org-ref-nobibliography-format to generate the bibliography.

**Comment by spencerahill** [comment]
Very sorry for the delay on this...I have not yet made any further progress but will update as soon as I do (not sure when that will be though)
