### ISSUE TITLE
Update DOI links

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#341]
Crossref has issued new guidelines on formatting of doi links. The TL;DR version is that links were formerly: `http://dx.doi.org/DOI` and should now be `https://doi.org/DOI`. Here's their blog post with more information: http://blog.crossref.org/2016/09/new-crossref-doi-display-guidelines.html

**Comment by jkitchin** [comment]
Maybe f0bdf7d will fix this issue.

**Comment by jabranham** [comment]
Thanks. This seems to have fixed most places, though when I add a new entry (e.g. `doi-utils-add-entry-from-crossref-query`) the url in the resulting bib entry is still the old link format.

**Comment by jkitchin** [comment]
That is a feature of the data that crossref sends back I think. I don't think org-ref is constructing that url.

**Comment by jabranham** [comment]
Thanks, I figured it was something like that. I suppose I can add an entry to `org-ref-clean-bibtex-entry-hook` to fix the URLs. Would you like me to submit that as a PR if I do so?

**Comment by jkitchin** [comment]
I would be happy to take a pull request on that.
