### ISSUE TITLE
Note about comment org-ref-clean-bibtex-entry

### ISSUE THREAD

**Issue by treese** [jkitchin/org-ref#342]
There is a comment in `org-ref-clean-bibtex-entry`:

`;; run hooks. each of these operates on the entry with no arguments.`
`;; this did not work like  i thought, it gives a symbolp error.`
`;; (run-hooks org-ref-clean-bibtex-entry-hook)`

I wondered about why the error occurs, and it turns out that
`run-hooks` expects a quoted symbol name for the hook variable as the argument, not a list. Did not expect or remember that myself (if I knew before!).

It's not clear from any documentation that `run-hooks` protects the hooks with `save-excursion` and `save-restriction`, so there's not a good reason to change the code.

**Comment by jkitchin** [comment]
Thanks for the comment!
