### ISSUE TITLE
Undiagnostic response when bad crossref

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#343]
Bibtex entries pulled off the net may have crossrefs that don't make sense when put in a new bib file -- they're referring to some other paper in some other .bib file.  It took me a while to figure this out because the error message I get from org-ref is hard to understand (see attached).

![org-ref-error-message](https://cloud.githubusercontent.com/assets/3851891/20577773/26d6a00e-b1c4-11e6-8708-a539eb6b8ed8.PNG)

This is the error message I got when I clicked on the reference in tmp.org, which cited a bib entry with a bad crossref.

[tmp_example.zip](https://github.com/jkitchin/org-ref/files/609946/tmp_example.zip)

I'm not sure why it's necessary to report this error inside of org-ref (if the citation is there, then that's all that's needed) but if it is for some reason, a more informative error message could save many people a little time.

**Comment by jkitchin** [comment]
This seems to be an error in helm-bibtex, specifically the function bibtex-completion-get-entry leads to the error. @tmalsburg do you know if this is fixable?

**Comment by tmalsburg** [comment]
I just tested, helm-bibtex doesn't throw an error when there is a crossref to an entry that doesn't exist.  The crossref is instead silently ignored.

**Comment by jagrg** [comment]
The error appears with the function `bibtex-completion-apa-format-reference` (used in `org-ref-bib-citation`) when the crossref key is wrong. The problem here is that (1) the entry contains wrong information and (2) bibtex.el doesn't actually point to the actual error, so in this case it's up to the user to identify that the crossref key is wrong.

**Comment by tmalsburg** [comment]
Thanks @jagrg.  I just pushed a fix that generates a warning when a bibtex entry is missing: f8948952c1e43fcd8641defaac3ec70a0a7013c3

**Comment by notuntoward** [comment]
Very fast and it works. Thanks!
