### ISSUE TITLE
Should drag-n-drop work on Windows?

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#347]
Should I expect URL or pdf dragging to work on Windows?  This is on Windows 10, and I'm dragging from Chrome or Firefox to emacs 25.1.1 (from here: http://vgoulet.act.ulaval.ca/en/emacs/windows/).

Dragging in general works, for example, I can drag a file from File Explorer to dired, and the file will be moved to the directory dired is looking at.

But when I drag a URL onto a bibtex window, I see a little "do not enter" symbol, and that's it.

When I drag a pdf which has a DOI in it, the citation is actually added to the bibtex file but at the end, there is a message in the minibuffer that says

Wrong type argument: stringp, nil

Do I need to do setup other than including

  (require 'org-ref-pdf)
  (require 'org-ref-url-utils)

in my .emacs?

**Comment by jkitchin** [comment]
It does not appear to be working correctly for me on  a windows machine at the moment. on my mac it works better, but I also see a nil error. It will be a few weeks til I can track this issue down.

**Comment by notuntoward** [comment]
OK, thanks for looking into it.

**Comment by Yevgnen** [comment]
@jkitchin Can please you tell how to configure to make it work properly work on a mac? When I drag a link, it inserts a link, when I drag a pdf, it alerts `JSON readtable error`... Thanks !

**Comment by jkitchin** [comment]
A JSON readtable error is related to the data provided by dx.doi.org, and probably not something org-ref can fix.

**Comment by jkitchin** [comment]
I can reconfirm the issue on Windows with a url, for some reason Emacs/Windows does not let you drag a url onto a buffer. This http://stackoverflow.com/questions/22085424/gnu-emacs-drag-and-drop-does-not-work-on-window suggests a permissions related issue, but I tried to run emacs as administrator and it did not change. 

It is weird, I can drag a file onto a buffer, but it doesn't seem to do anything. I am not sure where to go from here.

**Comment by jkitchin** [comment]
I will probably remove drag and drop behavior. I don't use it, and it is pretty unreliable across platforms so far.
