### ISSUE TITLE
List of citation entries of .bib file does not show up in helm

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/org-ref#35]
For some reason, the list of my citation entries stop showing up when I run org-ref-helm-insert-cite-link. Everything else is working (open notes, pdf file, ...) after I insert the citation link manually or using org-ref-insert-cite-link, though. Do you know what is going on?
Thanks

**Comment by jkitchin** [comment]
how recent is your helm-bibtex? Does helm-bibtex work on its own? i.e. M-x helm-bibtex

**Comment by DiogoFerrari** [comment]
That was it. Problem solved. I just reinstalled the helm-bibtex package and it worked. The combination org-ref and helm works quite nice. Congrats.

**Comment by prtkm** [comment]
I had this error in the past on my Mac. A reinstall of helm-bibtex fixed it.

On Sat, May 2, 2015 at 6:12 PM, John Kitchin <notifications@github.com>
wrote:

> how recent is your helm-bibtex? Does helm-bibtex work on its own? i.e. M-x
> helm-bibtex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jkitchin/org-ref/issues/35#issuecomment-98408356>.
>



-- 
Prateek Mehta
Chemical Engineering PhD Student
University of Notre Dame
(412) 417-0152

**Comment by jkitchin** [comment]
Thanks. I am glad it worked out.
