### ISSUE TITLE
Dead link in online manual

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#350]
I thought you'd like to know that, in the manual here:

   https://github.com/jkitchin/org-ref/blob/master/org-ref.org

there's this sentence:

   org-ref is _customizable_.

where _customizable_ is a link.  But when I click on it, I get a 404 error.  Same with other _customizable_ links.

**Comment by jagrg** [comment]
These are internal links. Try `M-x org-ref-help`.

**Comment by jkitchin** [comment]
That is an error in how github renders org as html. There is nothing we can fix for it I think.

**Comment by notuntoward** [comment]
OK, thanks.
