### ISSUE TITLE
HTML exporting @misc items - citing online articles

### ISSUE THREAD

**Issue by jmn** [jkitchin/org-ref#356]
The recommended way to [cite Wikipedia](https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=LaTeX&id=413720397#BibTeX_entry) with BibTex is to use this format:

` @misc{ wiki:xxx,
   author = "Wikipedia",
   title = "LaTeX --- Wikipedia{,} The Free Encyclopedia",
   year = "2011",
   url = "https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=413720397",
   note = "[Online; accessed 13-February-2011]"
 }`

However when I cite this using org-ref I get this HTML-export in bibliography:

```
<ul>
<li><a id="wiki:xxx">[wiki:xxx] @misc wiki:xxx,
   author = "Wikipedia",
   title = "LaTeX -- Wikipedia, The Free Encyclopedia",
   year = "2011",
   url = "https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=413720397",
   note = "[Online; accessed 13-February-2011]"
 </a></li>
</ul>

```
Is this working as intended? I suspect not?

**Comment by jkitchin** [comment]
That is what I would expect. You probably need to customize org-ref-bibliography-entry-format and add an entry for @misc types. There isn't one there, so the bibtex entry is used.

**Comment by jmn** [comment]
That works fine, thank you! Maybe you have considered adding a default value here.

**Comment by jkitchin** [comment]
It isn't obvious all misc entries would have all those fields though as they are all optional.

**Comment by jmn** [comment]
I understand. How about the "@online" template, is it usable with org-ref?

```
@online{jkitchin76:online,
title = {jkitchin/org-ref: org-mode modules for citations, cross-references, bibliographies in org-mode and useful bibtex tools to go with it.},
url = {https://github.com/jkitchin/org-ref},
urldate = {12/04/2016}
}
```
http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/biblatex/bibtex/bib/biblatex/biblatex-examples.bib

**Comment by jkitchin** [comment]
I guess that online should work, as long as the biblatex dialect is recognized. You still need to define a template for the format though.

**Comment by mgutekunst** [comment]
Hi, 

sorry for reopening this issue. I tried to add an "@online" entry into `org-ref-bibliography-entry-format` but the export does not work. I'm always ending up with an error during export. 
Do I have to add the "@online" tag somewhere else too?

**Comment by jkitchin** [comment]
Which export?  That is likely to only work for latex export. For latex export, this works for me.

I have org-latex-pdf-process set to ("latexmk -shell-escape --pdf %f")

#+latex_header: \usepackage{biblatex}
#+latex_header: \addbibresource{org-ref.bib}


* 356

cite:jkitchin76:online


\printbibliography

**Comment by mgutekunst** [comment]
That might be the issue then. I want to export to html.

**Comment by jkitchin** [comment]
You many need to do the following:

run (bibtex-set-dialect 'biblatex) to make sure emacs knows about your bibtex dialect. Then, add this link where you want the bibliography to show up.

printbibliography:nil

**Comment by mgutekunst** [comment]
Thanks a lot. Adding `(bibtex-set-dialect 'biblatex)` helped.
