### ISSUE TITLE
org-ref-title-case-article affects wrong words/letters

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#359]
There are a few cases where `org-ref-title-case-article` isn't enthusiastic enough:

```
title = {When we "emphasize a phrase" in a title},
```
becomes 
```
title = {When We "emphasize a Phrase" in a Title},
```

And then other times when it's over-enthusiastic:

```
title = {Let's Talk about the U.S.}
```
becomes
```
title = {Let's Talk about the U.s.}
```

**Comment by jkitchin** [comment]
Thanks for these. I just pushed a fix that works for these two examples.
