### ISSUE TITLE
Error for "Insert citation" link in org-mode property drawer

### ISSUE THREAD

**Issue by namdnguyen** [jkitchin/org-ref#361]
Hi, I am using `org-ref-helm-insert-cite-link` to insert a citation as a property in an org-mode entry. Org-ref citations work for me normally in the body of the entry, but I get an error `org-ref-get-bibtex-key-under-cursor: Wrong type argument: stringp, nil` when I try to interact with the citation link.

It still shows link formatting, but changes colors. I also do not see the reference in the minibuffer.

**Comment by jkitchin** [comment]
Can you provide an example? I can't reproduce this.

**Comment by namdnguyen** [comment]
Here is an example:

    * Test Entry
      :PROPERTIES:
      :BIBTEX: cite:van_riel_platos_2013 
      :CUSTOM_ID: 20161213110914
      :END:
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. cite:van_riel_platos_2013

The cite link in the BIBTEX property is the one returning the error, while the one in the body works as expected. This is probably an unorthodox way of using org-ref citations, but it fits well with my current note taking setup. Having it as a property value let's me use sparse trees, but a workaround could be to put the bibtex key (i.e. without the "cite:" prefix) as a property and the citation in the body of the entry.

- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5 (develop branch)
- Editing style: vim
- Completion: ivy
- org-mode: 8.3.6
- org-ref: 1.0.0 (5d6d548)
- helm-bibtex: 20161202.236 (3193f2a)

**Comment by namdnguyen** [comment]
Ah, ok. I thought that it might be something at the org-mode level. I'll go with my workaround and close the issue. Thanks for your quick response. Thank you also for developing this great tool!

**Comment by jkitchin** [comment]
Glad it is helpful!
