### ISSUE TITLE
Relative bibliography path does not properly convert in LaTeX document

### ISSUE THREAD

**Issue by aceross** [jkitchin/org-ref#362]
When using org-mode, I am able to set up the relative path to a bibtex file that may be in another folder easily:
```
[[bibliography: ../../bibliography/references.bib]]
```

This works perfectly and as intended; all entries are found. However, when this is exported to LaTeX, that relative path is converted to:
```latex
\bibliography{bibliography/references}
```
which means that during compilation, the bibtex file is not found and the citations are unresolved.

**Comment by jkitchin** [comment]
It looks like you have a space in your link and that is the problem. Change [[bibliography: ../../bibliography/references.bib]] to [[bibliography:../../bibliography/references.bib]] and see if it goes away.

**Comment by aceross** [comment]
Yes that was it. My mistake! Thanks for your help and this very excellent package.
