### ISSUE TITLE
Drag and drop does not work in `emacs-mac`

### ISSUE THREAD

**Issue by Yevgnen** [jkitchin/org-ref#363]
The drag and drop of a url into a bibtex file does not work in [emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport). Every time a url is dropped, only the link is inserted into the current buffer.

**Comment by jkitchin** [comment]
I can't reproduce this with the emacs I build from brew. You do need (require 'org-ref-url-utils) in an init file, but after that dragging a url onto a bib file adds an entry for me.

**Comment by Yevgnen** [comment]
@jkitchin Thanks for your reply. The emacs version should be `brew install emacs-mac` not `brew install emacs`. And I confirm I've required all the org-ref-* of the directory manually.

**Comment by jkitchin** [comment]
The way I have been building emacs is described here: https://github.com/jkitchin/scimax#alternative-manual-installation-of-scimax-for-mac-users

It has been a while since I built emacs (since it works ;), has brew changed the recipe from emacs to emacs-mac for some reason?

**Comment by Yevgnen** [comment]
They are two different version emacs. The `emacs-mac` one provides some OSX features including retina support of doc-view. You can see the readme of the [formula](https://github.com/railwaycat/homebrew-emacsmacport) and the emacs [repo](https://bitbucket.org/mituharu/emacs-mac/overview).

**Comment by jkitchin** [comment]
That seems like an emacs-mac problem then, since it works for the other one.

**Comment by Yevgnen** [comment]
That's probably it does. I'm sorry for the wrong place for reporting.
