### ISSUE TITLE
Cannot export ref links to HTML, label links export to unclosed divs

### ISSUE THREAD

**Issue by oantolin** [jkitchin/org-ref#364]
HTML export for label and ref links doesn't seem to work properly when exporting to HTML.

Consider this minimal org mode document:

```org
[[label:a1]] [[ref:a1]]
```

Exporting to LaTeX gives the expected result (I'll omit the preamble):

```latex
\begin{document}

\tableofcontents

\label{a1} \ref{a1}
\end{document}
```

Attempting to export to HTML gives an error message ("user-error: Unable to resolve link: nil") and produces no HTML output at all. My experiments indicate that the presence of  any ref link at all causes the same problem upon HTML export. I'm using Emacs 25.1 (on Windows 10, if that matters), Org 9.0.3, and org-ref 1.0.0 (from MELPA). I ran the export commands in an instance of emacs -Q where I executed the following code to load Org (this was in the scratch buffer, odd lines I typed, even lines Emacs printed):

```elisp
(package-initialize)
nil
(org-version)
"9.0.3"
(require 'org-ref)
org-ref
(org-ref-version)
"org-ref: Version 1.0.0"
```

----

Now, removing the ref link lets HTML export do something, but the result seems malformed. This org document:

```org
[[label:a1]]
```

exports to HTML as (I'll only include the body of the HTML output):

```html
<body>
<div id="content">
<p>
<div id="a1">
</p>
</div>
<div id="postamble" class="status">
<p class="date">Created: 2016-12-27 Tue 18:58</p>
<p class="validation"><a href="http://validator.w3.org/check?uri=referer">Validate</a></p>
</div>
</body>
```

Notice that the `div` containing the label is unclosed.

**Comment by jkitchin** [comment]
That seems to be something that broke with org-9. I had advised a function for ref links that no longer works. I removed the advice, and went back to a simpler export. This loses some functionality to get nice numbers instead of the link path, but export is working again I think.

**Comment by oantolin** [comment]
Great. Thanks!
