### ISSUE TITLE
citing multiple paper from the same year of the same author 

### ISSUE THREAD

**Issue by QikeLi** [jkitchin/org-ref#367]
It seems that org-ref cannot differentiate the years when I cite multiple papers from the same author published in the same year. For example, when I do

        As discussed by Kitchin and his colleagues citeyear:Kitchin-2016-paper1,Kitchin-2016-paper2,Kitchin-2016-paper3, yada yada...

I expect to see

        As discussed by Kitchin and his colleagues (2016a, 2016b, 2016c), yada yada...

But org-ref gives me

        As discussed by Kitchin and his colleagues (2016, 2016, 2016), yada yada...

Moreover, even after I manually changed the years in my bibtex to 2016a, 2016b, 2016c. org-ref still gave me the same format--(2016, 2016, 2016).

Is it the default behavior of org-ref? Any suggestions how to solve this? Thank you!

**Comment by jkitchin** [comment]
citeyear only prints the year of a publication. See http://tex.stackexchange.com/questions/232580/how-to-get-the-lettering-in-citeyear

**Comment by QikeLi** [comment]
Using citeyear* in org-ref results in:

        as termed by Efron (year?)

Here is what I wrote in my .org file:

        as termed by Efron citeyear*:efron-2007-size-power,efron-2007-correl-large,

and the entries in my .bib file:
        
        @article{efron-2007-size-power,
          author =	 {Bradley Efron},
          title =	 {Size, Power and False Discovery Rates},
          journal =	 {The Annals of Statistics},
          volume =	 35,
          number =	 4,
          pages =	 {1351-1377},
          year =	 2007a,
          doi =		 {10.1214/009053606000001460},
          url =		 {https://doi.org/10.1214/009053606000001460},
          DATE_ADDED =	 {Mon Jan 16 14:47:27 2017},
        }
        
        @article{efron-2007-correl-large,
          author =	 {Bradley Efron},
          title =	 {Correlation and Large-Scale Simultaneous
                          Significance Testing},
          journal =	 {Journal of the American Statistical Association},
          volume =	 102,
          number =	 477,
          pages =	 {93-103},
          year =	 2007b,
          doi =		 {10.1198/016214506000001211},
          url =		 {https://doi.org/10.1198/016214506000001211},
          DATE_ADDED =	 {Mon Jan 16 14:48:03 2017},
        }

**Comment by jkitchin** [comment]
I am not sure what you should do for this, but it is a latex issue, not an org-ref one. It seems like you are trying to get (author-year) format without the author.

With a small document like:
#+latex_header: \usepackage{natbib}

test cite:akhade-2011-effec,akhade-2012-effec,alesi-2010-co2-adsor,boes-2015-core-cu,boes-2015-estim-bulk,boes-2015-estim-bulk-si

bibliographystyle:apalike
bibliography:../Dropbox/bibliography/references.bib

I got this:

test Akhade and Kitchin (2011, 2012); Alesi et al. (2010); Boes et al. (2015c,a,b)

and in the references

Boes, J. R., Gumuslu, G., Miller, J. B., Gellman, A. J., and Kitchin, J. R.
(2015a). Estimating bulk-composition-dependent H2 adsorption energies on
CuxPd1􀀀xalloy(111)surfaces:ACSCatalysis; 5 : 1020 􀀀 􀀀1026:
Boes, J. R., Gumuslu, G., Miller, J. B., Gellman, A. J., and Kitchin, J. R.
(2015b). Supporting information: Estimating bulk-composition-dependent
H2 adsorption energies on CuxPd1􀀀xalloy(111)surfaces: ACSCatalysis; 5 :
1020 􀀀 􀀀1026:
Boes, J. R., Kondratyuk, P., Yin, C., Miller, J. B., Gellman, A. J., and Kitchin,
J. R. (2015c). Core level shifts in Cu-Pd alloys as a function of bulk compo-
sition and structure. Surface Science, 640:127{132.

**Comment by QikeLi** [comment]
Hmmm... you are right, it is a latex issue. Thank you!
