### ISSUE TITLE
org-ref-open-pdf-at-point 

### ISSUE THREAD

**Issue by autosquid** [jkitchin/org-ref#37]
Line 1583 of ```org-ref.el``` is to open existing pdf file with ```org-open-file```.
However I noticed there is a customisable function named ```helm-bibtex-pdf-open-function``` in helm-bibtex which is already imported by ```org-ref.el```. 
I am not familiar with Lisp, but is it possible to use ```helm-bibtex-pdf-open-function``` instead of ```org-open-file``` which I think is more friendly.

The original function definition is:
```
(defun org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
	 (key (car results))
         (pdf-file (funcall org-ref-get-pdf-filename-function key)))
    (if (file-exists-p pdf-file)
        (org-open-file pdf-file)
(message "no pdf found for %s" key))))
```

**Comment by jkitchin** [comment]
what is the problem with the current code? It seems to work just fine for me. Do want some other behavior than opening the pdf?

**Comment by autosquid** [comment]
```org-open-file``` opens pdf with system wide pdf viewer ( for me, on mac, it is ```Preview``` since it is fast).
When doing serious reading I prefer to another viewer (```Skim```) for easy pdf annotation and co-operation with latex. 
The ```helm-bibtex-pdf-open-function``` provides a way to choose different viewers other than system wide one.  So I think its better to use this function instead.

**Comment by jkitchin** [comment]
I looked at your suggestion, and it doesn't look that much better to me. I thought you meant you could choose different viewers at different times, but it looks like it is still an either or choice. 

I suggest you add your own function to do this like so:

;; example of adding your own function
(add-to-list
 'org-ref-helm-user-candidates
 '("Open pdf in emacs" . (lambda ()
			   
			   (find-file
			    (concat
			     org-ref-pdf-directory
			     (car (org-ref-get-bibtex-key-and-file))
			     ".pdf"))))
 t)

You can add one for each viewer you want. These will appear at the bottom of the helm buffer.
