### ISSUE TITLE
Bibliography heading in ODT export is broken

### ISSUE THREAD

**Issue by cwittern** [jkitchin/org-ref#372]
The bibliography export for ODT is basically just copied over from the ascii export with added XML escapes.  However, this does not work properly for the "Bibilography" heading, which is just inserted as plain text:

```
    (when keys
      (concat
       "Bibliography
=============
"
       (mapconcat (lambda (x)
		    (xml-escape-string (org-ref-get-bibtex-entry-ascii x)))
		  keys "\n")
       "\n"))))
```

I looked around a bit and found no obvious way to insert a heading for ODT here (maybe one could first create the ORG version of the bibliography and then convert?  On the other hand, hard-coding the heading has the well-known disadvantages for languages other than English, which is why I usually insert the relevant heading in the document myself, without relying on the citation processor.  So for the moment, I propose just to leave out the plain text heading and tell the user to handle the heading herself.  Ideally of course this should be treated the same in all export backends, so  a long-term solution still needs to be worked out.

**Comment by jkitchin** [comment]
I took out the hard coded heading. I don't use this much, and agree a better solution is needed. This mostly here so that it is feasible to get something into an odt document. I don't know much about the odt export to know if it makes sense to do this, or to create the org bibliography and let pandoc do the work?

**Comment by cwittern** [comment]
Great, thanks. Unfortunately I have now idea about the Pandoc side, but for ODT that is fine at least with me. The downside is that this is special for ODT and not compatible with other backend.
