### ISSUE TITLE
BIBINPUTS regression

### ISSUE THREAD

**Issue by malb** [jkitchin/org-ref#375]
I'm experiencing a regression for a use case similar to the one described in #194. 

Assume `abbrev3.bib` and `crypto_crossref.bib` are in a directory listed in `BIBINPUTS`. Putting:
```
bibliographystyle:alpha
bibliography:abbrev3.bib,crypto_crossref.bib
```
in my `.org` file will mean org-ref cannot find these files. However, putting
```
#+BEGIN_EXPORT latex
\bibliographystyle{alpha}
\bibliography{abbrev3.bib,crypto_crossref.bib}
#+END_EXPORT
```
leads to org-ref successfully finding the files in question. I believe this is because `BIBINPUTS` support was dropped in #194 in favour of reftex's built-in support. However, that support only kicks in for LaTeX-style bibliographies.

**Comment by jkitchin** [comment]
I just pushed a commit that I think will add this back in for bibliography links. Let me know if it works for you. Thanks,

**Comment by malb** [comment]
Thank you, this works. 

PS: FWIW, I do get `!!! abbrev3.bib NOT FOUND !!!` in the echo area when the point is over `bibliography:abbrev3.bib,crypto_crossref.bib`

**Comment by jkitchin** [comment]
thanks for noting that, I just pushed a fix that probably fixes that issue too.

**Comment by malb** [comment]
I believe `(split-string (getenv "BIBINPUTS") ";")` should read `(split-string (getenv "BIBINPUTS") ":")` i.e. BIBINPUTS is separated by `:`. But I got this from other people's configs (and it working with LaTeX), I'm having trouble finding the official documentation for it.

**Comment by jkitchin** [comment]
Ok. I changed that, and fixed clicking on the link to open it.

**Comment by malb** [comment]
Great, thank you!
