### ISSUE TITLE
org-ref-url-utils not working on Linux

### ISSUE THREAD

**Issue by brianmcgillion** [jkitchin/org-ref#376]
Thank you! I recently found org-ref and it has been extremely helpful. The issue that I see relates to dragging a URL from the browser to emacs. I have the same emacs configuration on Mac and Linux. On Mac I can drag the URL and it appends the entry to the .bib file, however, on Linux I just see "5 1" shown in  *Messages*. So it seems to see the drag event, when I hover over the .bib file but it does not see the drop (or at least it does not act on it). Have you any idea what could be the cause for this?

**Comment by jkitchin** [comment]
I am glad you like it and that it is helpful. The drag and drop stuff is pretty fragile it seems, and not very cross-platform. For example I am not sure it works at all on windows. It isn't a feature I use much and I don't test on Linux very often, so I don't know what could cause that.

**Comment by DrWaleedAYousef** [comment]
I am using archlinux and awesome WM. If I have a pdf and I want to create an entry for it in the bib file, add the pdf itself to the "file" field: what is the fastest way.

**Comment by jkitchin** [comment]
Type it in by hand, or write a function that uses something like read-file-name to browse to it and insert the field.
