### ISSUE TITLE
json-readtable-error 

### ISSUE THREAD

**Issue by brianmcgillion** [jkitchin/org-ref#377]
Hi,

When dragging a pdf, that is from either acm or ieee into emacs I can see the following:

5 1
Contacting host: dx.doi.org:80
Error: (json-readtable-error)

It happens for all that I have tried. Same effect on both Mac and Linux.

Thanks

**Comment by jkitchin** [comment]
this means the json data from dx.doi.org is not good. There isn't much I can do to help you without an example pdf.

**Comment by novusshu** [comment]
I think this error is common for most management journal pdfs. You can download any open source papers from say Academy of Management Journal, Journal of management, Organization Science, and be able to reproduce the error.
