### ISSUE TITLE
Documentation not good enough

### ISSUE THREAD

**Issue by shersk2** [jkitchin/org-ref#378]
The manual that you are linking to at the bottom of this page is not good enough. For someone who has never used org-ref before, it is not possible to understand how to insert a new citation. 

Please provide a link to a manual that explains to new users how to use org-ref.

From the manual: 

> index:bibliography index:bibliographystyle
> 
> org-ref provides a bibliography link to specify which bibtex files to use in the document. You should use the filename with extension, and separate filenames by commas.

There are no examples here showing to new users how to write a filename. Is the thinking here that the manual is only to be read by already seasoned users -- and the rest of us are expected to use google to find out this?

Reading further... Really, are you guys serious? Is this supposed to be the manual? I have gotten very far in installing various add-on programs to org-mode the last 24 hours, but this package is completely impossible to understand. You have to try to imagine how it's like to read it for someone who doesn't know what you know. Use some teacher's imagination, explain how to use the program.

Compare it to for example the support for footnotes. That took me about five minutes to figure out how to use. Read some of the other manuals of emacs packages and see how they have explained it.

( Remove this dead link: https://github.com/jkitchin/org-ref/blob/master/bibliography%20link )

Here's another bug: the references are not exported at all when the document is exported with LaTeX and when html, looks weird.

And in the installation instructions, it says to do `setq reftex-default-bibliography` but reftex isn't used anymore, is it? I saw it in one of the older instructional videos, but it doesn't seem to be required in the current version. 

Clean it up, please. It feels like I went into a trap when I stumbled upon this package. 

I would actually go as far as to suggest that this package be removed from Emacs. It is not right of the community to expose users to so much technical problems due to poor maintenance. This package might work OK for expert Emacs users who know instinctively how to set all the variables and make it work right, but all Emacs users are not experts and it must be available for a broad user base. Packages like this are a deterrent to new users like me.

**Comment by jkitchin** [comment]
I can see how the video tutorial, the annotated images that show just what to type, the copy and paste configuration example, and then the manual afterwards just aren't sufficient to get you started. That is terrible. I promise to spend all the money you paid for this software to help improve it. It is the least I could do. Thanks anyway, for the note; it's just the kind of helpful feedback we all dream of getting from users.

**Comment by shersk2** [comment]
I found out today that when exporting from emacs, org-ref does not include the two essential lines referring to the bibliography and the bibliographystyle the end of the tex file. I was able to produce a pdf file manually by typing those two lines into the tex files.

It is not rational time use that every new user has to spend 12 hours plus just on understanding what the package can do and how to install it. Most packages have a standard install and basic information about configuration, and I think org-ref should have the same.

**Comment by jkitchin** [comment]
That is probably because you did not type in your org-file:

bibliographystyle:somestyle
bibliography:somefile.bib

Without them, there will be no output. If it isn't obvious you have to replace somestyle with an actual style like unsrt, and replace somefile.bib with your bibliography file name.

**Comment by shersk2** [comment]
I did that.

**Comment by jkitchin** [comment]
So you are saying an org-file containing:

```
bibliographystyle:somestyle
bibliography:somefile.bib
```

doesn't export a latex file containing:

```
\bibliographystyle{somestyle}
\bibliography{somefile}
```

**Comment by shersk2** [comment]
That's right.

**Comment by jkitchin** [comment]
Hm. I just exported that example above and copied what it exported to. It doesn't seem possible for what you say to be the case. 

What did you see in the export? Did you see the `bibliographystyle:somestyle
bibliography:somefile.bib` instead?

How did you install org-ref? The easiest way is from MELPA.

**Comment by shersk2** [comment]
In the exported .tex file, there are no such lines. The last line in the .tex file is 

> \end{document}

. On the lines above, there's only the last few paragraphs of the document.

Yes, I installed it from MELPA.

**Comment by jkitchin** [comment]
but all the other citations were correct? and if you run M-x org-ref when the org-file is open it doesn't show any errors? Can you paste a small org-file that reproduces your observation here. Something like:

test.org
```
A sentence with a reference cite:somekey.

bibliographystyle:somestyle
bibliography:somefile.bib
```

then export it and paste the latex code too.

**Comment by shersk2** [comment]
Your examples succeeded in producing the bibliography lines.

`cat test.org `

> A sentence with a reference cite:aedo16_cultur_exper_techn_gover.
> 
> bibliographystyle:plain
> bibliography:references.bib
> 

`cat test.tex `

> % Created 2017-02-07 Tue 16:44
> % Intended LaTeX compiler: pdflatex
> \documentclass[11pt]{article}
> \usepackage[utf8]{inputenc}
> \usepackage[T1]{fontenc}
> \usepackage{graphicx}
> \usepackage{grffile}
> \usepackage{longtable}
> \usepackage{wrapfig}
> \usepackage{rotating}
> \usepackage[normalem]{ulem}
> \usepackage{amsmath}
> \usepackage{textcomp}
> \usepackage{amssymb}
> \usepackage{capt-of}
> \usepackage{hyperref}
> \author{shersk2}
> \date{\today}
> \title{}
> \hypersetup{
>  pdfauthor={shersk2},
>  pdftitle={},
>  pdfkeywords={},
>  pdfsubject={},
>  pdfcreator={Emacs 24.5.1 (Org mode 9.0.4)}, 
>  pdflang={English}}
> \begin{document}
> 
> \tableofcontents
> 
> A sentence with a reference \cite{aedo16_cultur_exper_techn_gover}.
> 
> \bibliographystyle{plain}
> \bibliography{references}
> \end{document}

**Comment by jkitchin** [comment]
then, it works.

**Comment by shersk2** [comment]
It would seem so. I don't understand why my longer document didn't work. But at least that test file worked. That's a starting point. Thank you for taking the time to look at this. I will try to debug the issue now.

**Comment by jkitchin** [comment]
Try M-x org-ref on your longer document. It will tell you what it sees for the bibliography.

Maybe you put the bibliography links in a section tagged :noexport: or a commented or archived section perhaps.

**Comment by shersk2** [comment]
It shows me the correct bib file.

**Comment by jkitchin** [comment]
That isn't what is needed. If the simple example worked, the longer document should too. Nobody can read your mind though to see what you are actually doing in the document, how you do the export, and what you get from the export. Nobody can tell how you have latex set up, and if it worked correctly.

You do not need a coder to debug this. You can take the simple example that worked and add to it from your longer document until it doesn't work, or take the longer document and cut things out until it does work. either way you will have discovered the problem, and maybe then we find a solution.

**Comment by shersk2** [comment]
The simple example succeeded in including the two lines in the .tex file, but emacs still couldn't produce a pdf file. 

I can still create a pdf file manually by using the command line, by following [this very good manual about LaTeX and bibliography](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Why_won.27t_LaTeX_generate_any_output.3F). 

This seems to me a problem of debugging and having computer programmers look through things and check that all various things are in order. 

Try to look at how other emacs packages are presented, the installation manuals and documentation.

**Comment by jkitchin** [comment]
Your problem is not related to org-ref, but in your org-mode configuration. Most likely it is  because the variable org-latex-pdf-process is not calling bibtex when it builds the pdf. Depending on your system a good option might be this in your init file:

(setq org-latex-pdf-process
      '("latexmk -shell-escape -pdf %f"))

I suggest you take some time, more than 24 hours, to read the org-mode manual and understand what you are doing before you offer criticism like this. Your expectations are not reasonable, and certainly are not respectful.
