### ISSUE TITLE
Bad url on doi-utils-add-bibtex-entry-from-doi

### ISSUE THREAD

**Issue by ary15** [jkitchin/org-ref#379]
PDF download from science direct fails when using doi-utils-add-bibtex-entry-from-doi. 

The bibtex entry is saved correctly, it is just the pdf that doesn't work, emacs returns the following message:

Contacting host: dx.doi.org:80
Title of the article (BibTeX converts it to lowercase)
Searched 1 buffer; 51 matches for "[^[:ascii:]]"
Contacting host: doi.org:443
Contacting host: www.sciencedirect.com:80
url-retrieve-internal: Bad url: www.sciencedirect.com/science/article/pii/S2352484716300075/pdfft?md5=a2bbd95674f1aa43cb7efb54c7637c81&pid=1-s2.0-S2352484716300075-main.pdf

I think the problem is the way the URL is formed by the command for science direct in doi-utils.el. I tried just running the url-copy-file with a few different versions, and this works:

(url-copy-file "http://www.sciencedirect.com/science/article/pii/S2352484716300075/pdfft?md5=a2bbd95674f1aa43cb7efb54c7637c81&pid=1-s2.0-S2352484716300075-main.pdf" file-location)

I think that the code in doi-utils is trying to do this:

(url-copy-file "www.sciencedirect.com/science/article/pii/S2352484716300075/pdfft?md5=a2bbd95674f1aa43cb7efb54c7637c81&pid=1-s2.0-S2352484716300075-main.pdf" file-location)

Which doesn't work.

Is anyone else having this problem? I have played around with the doi-utils.el code a little, and think I have a fix, but perhaps I am missing something.

**Comment by jkitchin** [comment]
I can't reproduce this. That particular doi works fine for me, and downloads the pdf correctly. I don't see anywhere it should be possible to not have an http:// prefix on the url, why do you think that is what is happening?

**Comment by ary15** [comment]
After just observing this for a little while, the fix I installed stopped working too. A clean install seems to have done the trick now. It is possible it was a problem with my internet server --- apparently our campus network was having some problems at the time. Thank you for looking into this.
