### ISSUE TITLE
'eqref' seems to be unexportable via html

### ISSUE THREAD

**Issue by kuangdash** [jkitchin/org-ref#38]
the 1426 row： what's the variable 'path' referred to ?
`(lambda (keyword desc format)
   (cond
    ((eq format 'html) (format "(<eqref>%s</eqref>)" path))
    ((eq format 'latex)
     (format "\\eqref{%s}" keyword)))))`

**Comment by jkitchin** [comment]
That is a bug. I have fixed it just now. A better question is whether the tags make sense, and whether the export makes sense. e.g. it isn't clickable or anything.

**Comment by kuangdash** [comment]
with ‘mathjax’, `·$\ref{eq:?}$` seems to be useful , but I'm not sured yet and may fix it later.(It needs some configure to org-mode's mathjax options)

**Comment by jkitchin** [comment]
That would be nice, but it definitely does not work out of the box.
