### ISSUE TITLE
Problems managing labels with dots on it

### ISSUE THREAD

**Issue by Doxdrum** [jkitchin/org-ref#381]
I started to write a document today, and venture to use a different notation (because it looks strange the notation `eqref:eq:bla`) and label my equations as `eq.bla` (with a single dot).

I notice that neither `helm` nor `ivy` recognized my labels. I think it is worth to point it down... perhaps can even be corrected.

Thank you!

**Comment by jkitchin** [comment]
Is that legal in Latex? I use - instead.

**Comment by Doxdrum** [comment]
Actually, the exported TeX file worked, but I had to manage the labels from memory... so I suppose it is possible in LaTeX.

**Comment by jkitchin** [comment]
ok, I pushed a commit to expand the patterns matched that should fix this.

**Comment by Doxdrum** [comment]
Thank you! I will try it asap.

**Comment by Doxdrum** [comment]
Dear John. The problem managing the labels with a dot on it is gone (Thank you very much)... but it seems that it cannot recognize the dash `-` within the labels.

Can someone confirm this behaviour?

**Comment by jkitchin** [comment]
It does seem to have lost dashes. I just pushed a fix to fix that.
