### ISSUE TITLE
Searching org files for occurrences of citation entry

### ISSUE THREAD

**Issue by chase-dwelle** [jkitchin/org-ref#382]
This is a question, not an issue.

In issue #160, you mentioned wanting the ability to search your org files for instances of a citation entry. This seems like a good idea since it allows you to place a certain citation in much greater context than just an annotated bibliography that may be in the notes entry. Is this a feature that is actively being worked on?

**Comment by jkitchin** [comment]
The most recent work I have done on this is here: http://kitchingroup.cheme.cmu.edu/blog/2017/01/03/Find-stuff-in-org-mode-anywhere/

I still have in mind one more version using MongoDB as the backend database I am working on now. I think it will better support full text search in addition to the more focused search of headlines/tags/properties/links.

**Comment by chase-dwelle** [comment]
Thanks for the response. This can be considered closed.
