### ISSUE TITLE
Create `helm-bibtex` note template when running `org-ref-open-notes-at-point`

### ISSUE THREAD

**Issue by chase-dwelle** [jkitchin/org-ref#383]
If I do not have a note for a certain item in my notes file when I run org-ref-open-notes-at-point, it creates the note template (starting with `** TODO``) . I would like this to instead run my function for `bibtex-completion-notes-template-one-file`, which is currently set to

```
(setq bibtex-completion-notes-template-one-file
      (format
       "\n* ${author} (${year}): ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :Keywords: ${keywords}\n  :Projects: ${groups}\n  :END:\n\n"))
```
I know that I can edit the `org-ref-note-title-format`, but it doesn't appear to have the ability to add `${keywords}` or `${groups}`. Or perhaps I'm wrong and the I can replace the `[????]` below with certain flags.

```
(setq org-ref-note-title-format
      (format
       "\n* %a (%y): %t\n  :PROPERTIES:\n  :Custom_ID: %l\n  :Keywords: [????]\n  :Projects: [????]\n  :END:\n\n"))
```

**Comment by jagrg** [comment]
This is possible. See `org-ref-notes-function` variable.

**Comment by chase-dwelle** [comment]
Thanks for making it easy.  For those that may be coming to this for any reason, the following settings allow me to open the notes file or create a new notes file for any citation with the `C-c 9` key binding:

```
;; Add notes to annotated bibliography (or edit existing notes) with C-c 9
(setq bibtex-completion-notes-template-one-file
      (format
       "\n** ${author} (${year}): ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :Keywords: ${keywords}\n  :Projects: ${groups}\n  :END:\n\n"))
(setq org-ref-notes-function
      (lambda (thekey)
        (let ((bibtex-completion-bibliography (org-ref-find-bibliography)))
          (bibtex-completion-edit-notes
           (list (car (org-ref-get-bibtex-key-and-file thekey)))))))
(add-hook 'org-mode-hook
          (lambda ()
            (define-key org-mode-map  (kbd "C-c 9") 'org-ref-open-notes-at-point)))
```
