### ISSUE TITLE
add-bibtex-entry causes emacs to shutdown since the cookie file is empty

### ISSUE THREAD

**Issue by srasipur** [jkitchin/org-ref#384]
As I add the doi for the paper I want to reference using -> M-x, doi-add-bibtex-entry,
this is the error I get:-
url-cookie-parse-file: Opening stdio stream: no such file or directory, c:/Users/Sriram/scimax/user/url/cookies

My cookie file is currently empty as I open it, would I be able to fix it?

**Comment by jkitchin** [comment]
I have never seen this problem! I suggest you just delete the cookies file and see if it gets recreated correctly. Mine is not empty.

**Comment by srasipur** [comment]
Thank you for your quick reply. if I delete the cookies file and then try the add-bibtex-entry,, emacs crashes reporting "fatal error: The TLS connection was non-properly terminated."

**Comment by jkitchin** [comment]
hm. Is this a new error that suddenly appeared? It seems to be some emacs/gnutls issue that may be fixed by updating emacs.

**Comment by srasipur** [comment]
Yeah. It had been working fine until yesterday. I'll try to update and get back to you

**Comment by jkitchin** [comment]
Odds are good it will just go away then😉

**Comment by srasipur** [comment]
downloaded scimax and MikTex 2.9 again. Problem persists. But interestingly, My CMOS or RTC clock is 5 hours ahead, even though the system clock (bottom right corner on windows) seems fine.
Noticed it when I was sending emails. Not sure if that is the issue...

**Comment by jkitchin** [comment]
This sounds like a TLS/https kind of issue, and probably unrelated to org-ref.

Does this block work for you:

```
#+BEGIN_SRC emacs-lisp
(let ((url-request-method "GET")
        (url-mime-accept-string "application/citeproc+json")
        (json-data))
    (with-current-buffer
        (url-retrieve-synchronously "http://dx.doi.org/10.1016/j.calphad.2017.01.009")
      (setq json-data (buffer-substring url-http-end-of-headers (point-max)))
      (if (string-match "Resource not found" json-data)
          (progn
            (browse-url (concat doi-utils-dx-doi-org-url doi))
            (error "Resource not found.  Opening website"))
	json-data)))
#+END_SRC
```

**Comment by srasipur** [comment]
Thank you for the code block. But upon referring to your youtube video on org-ref, dragging and dropping on pdf works in the .bib file. I'm able to cite this article in .org file. It seems to work now! Thank your help!
