### ISSUE TITLE
Using `doi-utils-add-bibtex-entry-from-doi` via `doi-link-menu` fails

### ISSUE THREAD

**Issue by herbstk** [jkitchin/org-ref#388]
Using `doi-utils-add-bibtex-entry-from-doi` via `doi-link-menu` fails with "Wrong number of arguments" as the further expects DOI and BIBFILE if called noninteractively but the latter only supplies the DOI. I think this is also the reason for #358. Maybe one could make BIBFILE optional and in case its `nil` it should ask the user.

**Comment by jkitchin** [comment]
Thanks for the suggestion. I pushed the fix you suggested.

**Comment by herbstk** [comment]
Thank you for your quick fix, I tried and it worked for me well. Might be a matter of taste but I found it to be an additional improvement to add the result(s) of `org-ref-find-bibliography` to the suggesed list:
```elisp
(unless bibfile
    (setq bibfile (completing-read
                  "Bibfile: "
                  (append (org-ref-find-bibliography)
                                 (f-entries "." (lambda (f)
                                           (and (not (string-match "#" f))
                                                (f-ext? f "bib"))))
                          org-ref-default-bibliography))))
```
For example in my case I have the bib-file in a subdirectory with respect to an org-file. It is referenced in the org-file using a 'bibliography:'-link. By using the above code it pops up as well.

**Comment by jkitchin** [comment]
Thanks for the suggestion. I have added something like this.

**Comment by herbstk** [comment]
Cool, thank you very much.
