### ISSUE TITLE
minibuffer/message overflow 

### ISSUE THREAD

**Issue by timmli** [jkitchin/org-ref#389]
Since lately, org-ref messages internal org-mode representations at every cursor position.

![capture](https://cloud.githubusercontent.com/assets/4593031/23258877/937308da-f9ca-11e6-983a-90b2672aa472.PNG)

When I remove org-ref in my init file, these messages will go away.

**Comment by jkitchin** [comment]
Thanks for reporting that. I just pushed a fix for it, there was a left over message from debugging something.

**Comment by timmli** [comment]
Your fix works for me. Thanks!
