### ISSUE TITLE
figure ref-link does render in pdf

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#393]
Did anybody report this?  The figure/chart ref-link does not render in pdf, display "Figrue ??"  Did I miss some setting?

**Comment by jkitchin** [comment]
I assume you misspelled Figure in your example. Can you run M-x org-ref in your document? This will check for bad ref links. Maybe also check what is in the Latex file to make sure the ref link exported correctly.

**Comment by cryoguy** [comment]
It does not like the file name with an extra period (e.g. Fig.1.png).  Thanks.

I have another question:  If I want refer to a subset of a figure (e.g.  ref:fig-4 A), how do I remove the space between "4" and "A" in output so that it will "4A" instead of "4 A"?  

Thanks for the wonderful work.

**Comment by jkitchin** [comment]
I would solve the second problem like: [[ref:fig-4]]A. I think that works.

**Comment by cryoguy** [comment]
yes, it works.  Thanks again
