### ISSUE TITLE
Alternative citations e.g. citenum:key Undefined Control Sequence Error and not exported to pdf

### ISSUE THREAD

**Issue by NLisa** [jkitchin/org-ref#399]
I am unable to correctly render alternative citations, for example `citenum:test00_ref`, returns malformed (i.e. text following underscore is a subscript) rendering of the key _test00_ref_, when I attempt to export my org document to pdf.

With some direction on how to proceed, I would also like to contribute to the project, by incorporating `citetitle` functionality.

**Comment by jkitchin** [comment]
You may want to try: (setq org-export-with-sub-superscripts '{})

underscores are always problematic in latex for me, so I don't use them.

I am pretty sure that citetitle should be already supported.

**Comment by NLisa** [comment]
Sorry if I wasn't clear.

In the body of document itself (i.e. **not** in the Bibliography / References section), the reference appears as `this_is_an_example_bibtex_entry` instead of [3] or 3 as it should be in the case of citenum.

**Comment by jkitchin** [comment]
In what kind of export?

citenum:akhade-2011-effec

this exports to \citenum{akhade-2011-effec} in latex for me..

There is no support for it to show as a number for html export. The closest you could get to it is described here: http://kitchingroup.cheme.cmu.edu/blog/2015/12/03/Exporting-numbered-citations-in-html-with-unsorted-numbered-bibliography/

**Comment by NLisa** [comment]
When exporting to pdf via LaTeX, `cite:akhade-2011-effec` will be rendered as `[1]` in the pdf document where it is referenced, however any alternative citations eg `citenum:akhade-2011-effe` will appear in the pdf document as `akhade-2011-effec` where it is referenced and will not have a corresponding bibliography entry. i.e. `\citenum{key}` is not recognized in my case, and the LaTeX pdf compile process tries to parse the _key_ as a maths equation.

I thought perhaps `\citenum` and \ or `\citetitle` required biblatex with the biber backend?

But trying:
`#+LATEX_HEADER: \usepackage[backend=bibtex8]{biblatex}`
or
`#+LATEX_HEADER: \usepackage[backend=biber]{biblatex}`

Just seemed to break many other things with my Org-ref setup.

In particular, following your [Introduction to Org-Ref video](https://www.youtube.com/watch?v=2t925KRBbFc) , in my case the exported pdf does not properly generate 

> ...
> Alternate cite 3.
> ...

  `citenum:third_reference` is properly experted in the associated .tex file as `\citenum{third_reference}`, however it does not render properly in the associated pdf, 

> ...
> Alternate cite third_reference
> ...

 and no bibliography entry is generated for it.

Moreover trying to compile the tex file directly leads to an  _Undefined control sequence error_ for the `\citenum` entry.

What should be included in the preamble of the tex file, when exporting to pdf from org-mode, to support `\citenum` and render `\citetitle` correctly. Sorry, this is more a question for tex.stackexchange or ctan forums, than an org-ref issue.

Lastly, what is your `org-latex-pdf-process` set to?

Mine at present is:
`(setq org-latex-pdf-process '("latexmk -pdflatex='%latex -shell-escape -interaction nonstopmode' -pdf -output-directory=%o -f %f"))`
Could this perhaps be the source of the problem?

**Comment by jagrg** [comment]
I'm not too familiar with biblatex, but I believe you need the natbib option enabled. That's probably why the citenum command is not working for you.

**Comment by jkitchin** [comment]
I also think you need to use the natbib package. 

You can do that with 

#+latex_header: \usepackage{natbib}

in your org-file or by modifying org-latex-default-packages-alist.

**Comment by NLisa** [comment]
Thank you very much.

Confirm that with the natbib package imported, citenums are reference correctly and the check for natbib types also very handy, thank you.

Would be interesting to extend that _"natbib checker"_ snippet to biblatex types checks as well. And in the case where biblatex _**is**_ imported, to then: 
- export from (.org) `bibliography:/path/to/ref.bib` to (.tex) as `\addbibresource{/path/to/ref.bib}`
- parse the bibliographystyle:_style_ parameter into the `\usepackage[backend=bibtex, style=_style_]{biblatex}`
- perhaps do something similar with bibliography:_backend_
- automatically append the `\printbibliography` required when using biblatex.

I know you guys don't use biblatex too much, but I'd be happy to look into implementing the above, unless a better solution already exists...?

Thanks again.

**Comment by jkitchin** [comment]
Those are good ideas. If I recall, addbibresource has to be in the header, is that right? If so, I don't see a way to get the export to do that. I also can't see a way to get bibliographystyle into the header. Doing those would require a custom exporter I think, or some intermediate export to a new org-buffer.
