### ISSUE TITLE
Multiple citations with the helm interface?

### ISSUE THREAD

**Issue by prtkm** [jkitchin/org-ref#4]
Hi John,

Is there any way of inserting multiple citations with the helm interface? I could find it in the docs (though I didn't read them very carefully). I have to do C-c ] every time to insert a new citation.

I can still do it with org-ref-insert-cite-link (I have to do Esc-Esc C to use it, M-Esc switches windows on debian), but I think helm is cooler.

Prateek

**Comment by jkitchin** [comment]
yes, you select entries with C-spc in helm. or, if you see everything you
want, M-a will select all. When you press enter, all of them should be
entered.

Helm is much cooler. Type C-z to see all the things you can do on an entry
from helm-bibtex.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Awesome! Works really well.
