### ISSUE TITLE
Unable to add entry from crossref query

### ISSUE THREAD

**Issue by sachdevaprash** [jkitchin/org-ref#400]
Function doi-utils-add-entry-from-crossref-query fails to add the entry to the bibliography.

Throws "while: End of buffer" error. How do I go about debugging this?

**Comment by jkitchin** [comment]
can you post the query you were trying?

**Comment by sachdevaprash** [comment]
After spending some time on it, I have successfully made it work. The bibtex file was not ending in an EOL character.

Maybe we can make a more graceful exit when errors are found in Bibtex format? Bibtex errors can be pretty annoying to have to manually debug without any indication of the error.

**Comment by jkitchin** [comment]
How do you get have a bibtex file that doesn't have an EOL character?

**Comment by sachdevaprash** [comment]
I used crossref-lookup query and copied the bibtex entry to the bibtex file manually. I understand that is not the standard procedure, but I think the command should fail gracefully, to the extent of at least letting me know that there is an error in the format of the bibtex file. I will try to work on this when possible to let the procedure return a better higher-level error statement.
