### ISSUE TITLE
PDF file format/location changes

### ISSUE THREAD

**Issue by sachdevaprash** [jkitchin/org-ref#401]
I would like to be able to change the PDF file name and location irrespective of the key in Bibtex. Is it possible to override the PDF fetch function to use some other function to get the filename?

If you can point me to a strategy to do this, I can try to implement it myself.

**Comment by jkitchin** [comment]
checkout the variable org-ref-get-pdf-filename-function.

**Comment by sachdevaprash** [comment]
I'll try to use that and get any help here if needed. I intend to add an extra property on the paper to be referred to for the PDF file location.
