### ISSUE TITLE
some comments on org-ref

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jkitchin/org-ref#404]
I have two comments on the very helpful og-ref:

1- It seems that adding an entry (e.g., by using doi or isbn) causes a problem, when the option "Bibtex Maintain Sorted Entries" is set or the orcb-key is removed from org-ref-clean-bibtex-entry-hook. 

2- Sometimes (like today!!), the isbn-to-bibtex always give:
funcall-interactively: Wrong type argument: integer-or-marker-p, nil

3- Why the title-case or sentence-case function is restricted only to the type "article"

**Comment by jkitchin** [comment]
1. I haven't seen that one before. It would be tricky to fix, since we would have to use let around all the functions to ignore that setting I guess. that might defeat the purpose of the setting though.

2. Sometimes there are network issues outside of org-ref that cause that. could you provide an isbn that causes it for you?

3. When I wrote that, it wasn't obvious it was right to affect all entry types, e.g. books with special capitalization, etc... also, it is written to be able to map over all the entries in a file, and this limited its scope to just articles in the file.

**Comment by DrWaleedAYousef** [comment]
1- I removed orcb-key (to keep my old keys with no changes, since I recently moved from Mendeley to plain bibtex). This way, when I use doi of org-ref it picks it up but generates an error when generating a key. Anyway, no problem I generate it then by C-c C-c. So, this issue can be considered as almost solved.

2- Any isbn now does not work with me; e.g., 9783540330363. I do not know whether the new setting of my .emacs is the problem (although I tried to remove any setting related to org-ref and bibtex)!!

3- Can you provide a switch (or option) for considering all types? It will be great.

Thanks so much.

**Comment by jkitchin** [comment]
I can't reproduce 2, that results in

@book{chen-2006-handb-data-visual,
  author =	 {Hrsg. Chun-houh Chen ; Hrsg. Wolfgang H{\"a}rdle ; Hrsg.
                  Antony Unwin},
  title =	 {Handbook of Data Visualization},
  year =	 2006,
  publisher =	 {Springer Berlin},
  url =		 {http://www.worldcat.org/oclc/150289486?referer=xid},
  city =	 {Berlin},
  ed =		 {1. Ed.},
  form =	 {BA},
  isbn =	 9783540330363,
  lang =	 {eng},
  lccn =	 2007931825,
  oclcnum =	 {150289486 214357554 232302403 314615038 474712418 494787249
                  645208009 743424036 751135412 76799021 804152581 849253364
                  873514520 612218650},
}

I guess it is an issue somewhere else that is preventing the url-retrieval from working for you.

I have to think about how to do 3. In the meantime, you might make your own based on those functions that does what you want.

**Comment by DrWaleedAYousef** [comment]
2. I found the problem; I kept debugging my .emcas and I found that the
   problem is when I setq the following:

(setq      org-ref-clean-bibtex-entry-hook
      (quote
       (org-ref-bibtex-format-url-if-doi orcb-key-comma org-ref-replace-nonascii orcb-& orcb-% org-ref-title-case-article orcb-clean-year orcb-clean-doi orcb-clean-pages org-ref-sort-bibtex-entry))
)

I do this setting to remove orcb-key so that I do not change my old keys
when I do cleaning for the whole buffer. Unfortunately, it seems that
this conflicts with isbn-to-bibtex somehow; I do not why. Could you
suggest a solution please?

3. I am not excellent in Lisp; I tried changing the .el but no effect
   took place!


Thanks again.

**Comment by DrWaleedAYousef** [comment]
I noticed the new update of org-ref; unfortunately, the same problem if ISBN exist. That is, if I remove orcb-key and set:
(setq      org-ref-clean-bibtex-entry-hook
      (quote
       (org-ref-bibtex-format-url-if-doi orcb-key-comma org-ref-replace-nonascii orcb-& orcb-% org-ref-title-case-article orcb-clean-year orcb-clean-doi orcb-clean-pages org-ref-sort-bibtex-entry))
)

the isbn-to-bibtex throw the error.

**Comment by jkitchin** [comment]
The problem is your entry does not have a key, and it needs one. That is what orcb-key does. You have to add a function that will create a key if there is not one there.

**Comment by DrWaleedAYousef** [comment]
I will clarify more: with the following setting in my emacs

   setq   org-ref-clean-bibtex-entry-hook
      (quote
       (org-ref-bibtex-format-url-if-doi orcb-key-comma org-ref-replace-nonascii orcb-& orcb-% org-ref-title-case-article orcb-clean-year orcb-clean-doi orcb-clean-pages org-ref-sort-bibtex-entry))

I have the following behavior.

When I add a paper using, e.g., doi-utils-add-bibtex-entry-from-doi, it
retrieves the paper and add it appropriately to the bib file but without
adding a key and producing the following message: "bibtex-find-entry:
Wrong type argument: stringp, nil", which is no problem as long as the
paper is retrieved. I can add the key with C-u C-c C-c.

However, with isbn-to-bibtex the same message appears
"bibtex-find-entry: Wrong type argument: stringp, nil" but WITHTOU
retrieving the book info.

**Comment by jkitchin** [comment]
I see what you want. I just pushed some changes that should address it. Still, the best bet is to put something like orcb-key into the hook function in my opinion.

**Comment by DrWaleedAYousef** [comment]
Thanks so much; it really works. I like that, in favor of using
orcb-key, because it does not enforce changing the keys if for some
reason I change the title or so.

Thanks so much.
