### ISSUE TITLE
ref-link broken

### ISSUE THREAD

**Issue by gongzhitaao** [jkitchin/org-ref#405]
The `ref:xxx` always shows `!!! NO CONTEXT FOUND !!!count: 0`

Following is a simple test example.

```org
* Test

  See Table ref:tbl:test0.

  #+CAPTION: Test Table
  #+NAME: tbl:test0
  | Hello | World |
```

Hoover over `ref:tbl:test0` will show the warning message.

**Comment by jkitchin** [comment]
Maybe it is because of the spaces in front of #+NAME.

**Comment by gongzhitaao** [comment]
@jkitchin Yes indeed.  But it worked previously.  And I think it is natural that the `#+NAME` keeps the same indent as the table itself?

**Comment by jkitchin** [comment]
I don't think that is legal org syntax. Keywords are supposed to start at the beginning of the line. I am not sure why it would have worked before.

**Comment by gongzhitaao** [comment]
However I think keywords does not have to start at the beginning.  And for some cases it should not.  For example.

```org
* Test

  1. This is equation source 1.
#+BEGIN_SRC cpp
a = 3
#+END_SRC
  2. this work 2
     #+BEGIN_SRC cpp
a = 4
     #+END_SRC
```

The first source block does *not* belong to the first item.  When export to PDF, the above will be considered as two separate item list.  So if you want to include the source block in the list item, you have to indent the source block.  I think maybe this is similar to the attribute keywords?

```org
* Test

  1. This is equation source 1.
     #+BEGIN_SRC cpp
a = 3
     #+END_SRC
  2. this work 2
     #+BEGIN_SRC cpp
a = 4
     #+END_SRC
```

**Comment by jkitchin** [comment]
hm. that doesn't seem too hard to support. I just pushed a fix for this.
