### ISSUE TITLE
Alternative cites not shown on C-u

### ISSUE THREAD

**Issue by fleimgruber** [jkitchin/org-ref#408]
Actual:
After pressing `C-c ]`, inside the helm citation selection a `C-u` (as mentioned in https://github.com/jkitchin/org-ref/blob/master/org-ref.org) does nothing.

Expected:
https://www.youtube.com/watch?v=2t925KRBbFc&t=3m32s

**Comment by NLisa** [comment]
`C-u RET` on the desired helm-bibtex entry? This should pop-up helm section for alternative citations.

**Comment by fleimgruber** [comment]
Doh.  Thanks and sorry for the noise.

**Comment by jkitchin** [comment]
Thanks @NLisa!
