### ISSUE TITLE
 Symbol's value as variable is void: org-ref-cite-types

### ISSUE THREAD

**Issue by trenkert** [jkitchin/org-ref#41]
When I try to load org-ref via org-babel-load-file, I get this error:

load-with-code-conversion: Symbol's value as variable is void: org-ref-cite-types

Any idea what's causing this?

**Comment by jkitchin** [comment]
org-ref is no longer loaded with org-babel. You can just do (require
'org-ref)

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
