### ISSUE TITLE
Insert reference fails with error: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by andreaskiermeier** [jkitchin/org-ref#410]
When I try to insert a reference, either using C-c ) or from the menu, I now get the following error.
`org-ref-get-label-context: Wrong type argument: stringp, nil`
Doesn't seem to matter whether I have Section or Table just before the cursor when trying to insert the reference.
I'm using org-ref-20170331.648 from Melpa.
Thanks.

**Comment by jkitchin** [comment]
I cannot reproduce this. Can you provide a small example that reproduces this error?

**Comment by andreaskiermeier** [comment]
Darn. Works in a minimal example.
Apparently I've done something wrong somewhere in my org file.
Sorry for the noise.

**Comment by andreaskiermeier** [comment]
OK, so maybe there is a problem. A simple example is as follows.
```
#+STARTUP: content indent hidestars fninline
#+OPTIONS: toc:nil

* Introduction

Here is reference Figure

#+BEGIN_SRC R :results output graphics :exports results :file test.pdf :height 4 :width 8
plot(1:10,1:10)
#+END_SRC

#+CAPTION: A caption to a plot
#+NAME: fig:test
#+RESULTS:
[[file:test.pdf]]
```
I've produce the plot in R (PDF here: [test.pdf](https://github.com/jkitchin/org-ref/files/901323/test.pdf) - you don't need to run R to get the problem) and then manually added the #+CAPTION: and #+NAME: lines above #+RESULTS:. This is what I usually do.
When I try C-c ) I get the error reported above.
Hope you can recreate the issue.
Thanks

**Comment by andreaskiermeier** [comment]
Thanks John.
Yes, it fixes the error occurring, but now org-ref now does not 'find' the label.
That is, in the example above, C-c ) works to the extent that it doesn't give an error, but there are no "labels" I can select to create a reference to.
BTW, same happens in the org-ref help file (e.g. table-1)

**Comment by jkitchin** [comment]
I pushed a fix earlier today that should fix this again.
