### ISSUE TITLE
Link overlay for prettier view in Org buffer

### ISSUE THREAD

**Issue by mankoff** [jkitchin/org-ref#413]
I used to use Org + RefTeX and the links appeared more visually pleasing in the Org buffer. When I used to insert a citation, it would insert `[[citep:BibKey][Author (YYYY)]]`. Is there a way to get this when using org-ref?

**Comment by jkitchin** [comment]
There is not a way. The description in cite links is used for optional pre/post text, not for display like it usually is in org-mode.
