### ISSUE TITLE
bibtex-completion not loaded when using ivy backend?

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#414]
I'm trying to understand why every link returns "!!! No entry found !!!" although they are correct (when I click on the link, I can access the pdf, the entry in the bib file, etc). While debugging it, I found that `bibtex-completion-get-entry` is not loaded. If I manually require it, I can then see the information in the minibuffer.

As I recently switched to the ivy backend, I suspect bibtex-completion is not loaded by default but it should.

**Comment by jkitchin** [comment]
Thanks for reporting this. I just pushed a fix for it I think.

**Comment by brabalan** [comment]
It worked, thanks a lot.
