### ISSUE TITLE
stay in session after insert citation

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#419]
I used to be able to insert citation(s) with RET after selection.  After a recent pull, the RET will bring me to entry in bibtex file.   I have to use f2 to insert citation(s).  Any reason why this is happening?  

Also, how do I stay in session after inserting citation for additional search and insertion?

**Comment by jkitchin** [comment]
I can't think of any change recently that would do that.  I wonder if something changed in helm-bibtex?

If you use helm-bibtex, you might try using multiple selections, e.g. press C-spc to "mark" entries and enter them all at once, or use helm-resume to restart the last helm session.

**Comment by cryoguy** [comment]
looks like helm-bibtex is to blame.  I have another question, the following setting allows me to open PDF with pdf-tools in org-ref.  
`(setq org-ref-get-pdf-filename-function 'org-ref-get-mendeley-filename)
(defun my-org-ref-open-pdf-at-point ()
"Open the pdf for bibtex key under point if it exists."
(interactive)
(let* ((results (org-ref-get-bibtex-key-and-file))
(key (car results))
(pdf-file (org-ref-get-mendeley-filename key)))
(if (file-exists-p pdf-file)
(org-open-file pdf-file)
(message "No PDF found for %s" key))))`
Can I use something similar to achieve the same in helm-bibtex?  I just want to attach the pdfs in emailing mainly. I am getting "no PDF(s) Found".   Sorry, my elisp is too limited even for such task.

`;;(setq bibtex-completion-pdf-field 'org-ref-get-mendeley-filename)
(setq bibtex-completion-find-pdf-in-field 'org-ref-get-mendeley-filename)
;;(setq bibtex-completion-find-pdf 'org-ref-get-mendeley-filename)
`

**Comment by jkitchin** [comment]
Isn't there already an attach pdf to email action in helm-bibtex? For me it is f8.

**Comment by cryoguy** [comment]
It stopped working for me with "No PDF(s) Found" error? sth related to file field in Mendeley generated bibtex.   can not open PDF either.   I can open PDF with above setting in org-ref.  Is it my setting?

**Comment by jkitchin** [comment]
See org-ref-email-bibtex-entry.  I am not sure what you have to do for helm-bibtex. It must need a function to get the filename of the pdf to attach it. I would ask on the helm-bibtex issues page.

**Comment by chxp** [comment]
I have also happen this problem

I am using org 8.2.10 in emacs 24.4.1 under ubuntu 14.04. When I use 'org-ref-helm-insert-cite-link' or 'org-ref-insert-link' to insert citations, RET will also bring me to entry in bibtex file.

Multiple selections will also bring me to the first entry in bibtex file. F2 works well and

**Comment by jkitchin** [comment]
I think this issue (RET will also bring me to entry in bibtex file.) has been fixed. Do you see it in a current version?

**Comment by chxp** [comment]
Haha, the org-ref-20170423.1812 version have already fixed it, Thanks for your kind reply

The helm completion indicate me have no org-ref, So I donnot check whether the org-ref is the newest.
