### ISSUE TITLE
Mandatory field 'journaltitle' is missing // cant get bibtex to auto on biblatex

### ISSUE THREAD

**Issue by zeltak** [jkitchin/org-ref#42]
Hi again, i also get the Mandatory field 'journaltitle' is missing error (as in issue #40)

also i tried your suggestion and the bib file looks like this

```

% -*- mode:bibtex; eval: (bibtex-set-dialect 'biblatex); -*-


@article{ackerman-1998-discr-clear,
  author =	 {Ackerman, {S.A.} and Strabala, {K.I.} and Menzel,
                  {W.P.} and Frey, {R.A.} and Moeller, {C.C.} and
                  Gumley, {L.E.}},
  title =	 {Discriminating Clear Sky From Clouds With Modis},
  journal =	 {Journal of Geophysical Research},
  volume =	 103,
  number =	 {D24},
  pages =	 {32,141--32,157},
  year =	 1998,
  shorttitle =	 {Discriminating clear sky from clouds with {MODIS}},
}
```

yet it dosent come up as biblatex, and when issuing C-x C-e i get the following error

```
Debugger entered--Lisp error: (void-variable %)
  eval(% nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

if this is purely a bibtex issue i can try and look in the biblatex forums (if they have any :))

best

Itau

**Comment by jkitchin** [comment]
zeltak writes:

> Hi again, i also get the Mandatory field 'journaltitle' is missing error (as in issue #40)
>
> also i tried your suggestion and the bib file looks like this
>
> ```
>
> % -*- mode:bibtex; eval: (bibtex-set-dialect 'biblatex); -*-
                                                         ^
Your cursor has to be right after the ) when you run C-x C-e

alternatively, in the bibte file, select the Entry-Types menu, and then
select BibTeX dialect, and try picking biblatex.

This is definitely a bibtex issue. Just try typing C-c C-c to run
bibtex-clean-entry in your bibtex file, and you will get the same
error until you get the dialect right.

>
>
> @article{ackerman-1998-discr-clear,
>   author =     {Ackerman, {S.A.} and Strabala, {K.I.} and Menzel,
>                   {W.P.} and Frey, {R.A.} and Moeller, {C.C.} and
>                   Gumley, {L.E.}},
>   title =      {Discriminating Clear Sky From Clouds With Modis},
>   journal =    {Journal of Geophysical Research},
>   volume =     103,
>   number =     {D24},
>   pages =      {32,141--32,157},
>   year =       1998,
>   shorttitle =         {Discriminating clear sky from clouds with {MODIS}},
> }
> ```
>
> yet it dosent come up as biblatex, and when issuing C-x C-e i get the following error
>
> ```
> Debugger entered--Lisp error: (void-variable %)
>   eval(% nil)
>   eval-last-sexp-1(nil)
>   eval-last-sexp(nil)
>   call-interactively(eval-last-sexp nil nil)
>   command-execute(eval-last-sexp)
> ```
>
> if this is purely a bibtex issue i can try and look in the biblatex forums (if they have any :))
>
> best
>
> Itau
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/42

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
