### ISSUE TITLE
How to use multiple project?

### ISSUE THREAD

**Issue by zhixing2017** [jkitchin/org-ref#420]
Hi, thanks for your job.
I seperated my .bib file into several files. And I created org files for each of them. How can I insert citations from specific .bib file and  into the corresponding org files?
I tried to put` # org-ref-default-bibliography: ("/Users/jkitchin/tmp/org-ref-issue-368/test.bib")` into my org files, but it did not work.

**Comment by yyadavalli** [comment]
Try inserting a bibliography link in your org file

**Comment by jkitchin** [comment]
I wouldn't expect your example to work unless you have a /Users/jkitchin path on your computer!
Put this in a file to use a specific bib-file, as suggested by @yyadavalli.
bibliography:/Users/jkitchin/tmp/org-ref-issue-368/test.bib

**Comment by zhixing2017** [comment]
Yes, I know it is a good and simple method. 
However, when I open .bib files and want to add notes for one reference in the .bib files, I want it find the right one without to open the corresponding org files and add the bibtexkey.

**Comment by jkitchin** [comment]
I don't understand what you want at all. It sounds like you have an unconventional notes setup where you want to open foo.bib, find an entry, then open foo.org to the notes on that entry. You would have to write your own function to do that.

**Comment by zhixing2017** [comment]
I am sorry that I did not make it clear.
Here is the thing. I opened a file `b.bib` , and `M-x org-ref-open-bibtex-notes`. The default org file set in .emacs, `a.org`, was opened. The title of article, some properties and the cite command `cite:bibtexkey` was inserted. How to make it open `b.org` automatically, I want to use different org files for my .bib files. `a.org` for `a.bib`; `b.org` for `b.bib`. 
In addition, I think it will be better that the user can customize the text format inserted by the command `M-x org-ref-open-bibtex-notes`.

**Comment by jkitchin** [comment]
See the variables: org-ref-notes-function, org-ref-open-notes-function, org-ref-create-notes-hook, and org-ref-note-title-format. They are all customizable.

**Comment by zhixing2017** [comment]
oh, thank you very much.

**Comment by jagrg** [comment]
To answer the first part of your question, you could try setting `org-ref-bibliography-notes` as a local variable in your b.bib file. Something like:

```
@Comment Local Variables:
@Comment org-ref-bibliography-notes: "~/path/to/b.org"
@Comment End:
```

**Comment by zhixing2017** [comment]
It does not work. I uncommented the setup about default bibliography.
After `M-x org-ref-open-bibtex-notes`, it says:
```
Org-ref-bib-bibliography-notes is not set to anything
```

**Comment by jagrg** [comment]
No need to uncomment. Just add the code above to your b.bib file with the correct path. Then save b.bib, kill and reopen the buffer. I don't see why it wouldn't work.

**Comment by zhixing2017** [comment]
![default](https://cloud.githubusercontent.com/assets/26316963/25259460/c43480fe-2678-11e7-82f6-f0b2d6fb9dde.png)

Is there something wrong?

**Comment by jagrg** [comment]
There is. The code only works at the end of the file. Try this instead, and place it on the first line:

`@Comment -*- org-ref-bibliography-notes: "d:/b.org" -*-`

**Comment by zhixing2017** [comment]
It worked.
Thanks very much.

**Comment by zhixing2017** [comment]
Sorry for the bothering. 
If I opened a .bib file, and I want to get the pdf files for some bibtex entries.
Which command can `try to get pdf` for the specific entry?

**Comment by zhixing2017** [comment]
A bug in my computer.

I set this in my .bib file:
``` emacs-lisp
@Comment -*- org-ref-bibliography-notes: "research.org" ; org-ref-pdf-directory: "" ; -*-
```
I customize the variable: `org-ref-note-title-format` "%t" in the customize-group. It did not work, and it always insert `article's title cite:nil` when I `M-x org-ref-open-bibtex-notes` in my .bib file.

So I put the below code into my `.emacs`.
``` emacs-lisp
(setq org-ref-note-title-format "%t cite:%k")
```
It worked well. 

I mean, there is something wrong about the customization.
If it is my fault, please ignore this.

**Comment by jagrg** [comment]
> If I opened a .bib file, and I want to get the pdf files for some bibtex entries.
Which command can try to get pdf for the current entry?

You can use `org-ref-open-bibtex-pdf`. When you are unsure if a command exist, try 1. M-x helm-apropos 2. type org-ref pdf 3. read the docstring and see if it does what you want. You might also try `org-ref-bibtex-hydra/body`. See `M-x org-ref-help` for more information.

**Comment by zhixing2017** [comment]
If I have the pdf, I can open it using the command you said. 
Sometimes, I need to download the pdf. How can I download the pdf directly?

**Comment by jagrg** [comment]
See `doi-utils-get-bibtex-entry-pdf`.

**Comment by zhixing2017** [comment]
It worked. Thank you.
