### ISSUE TITLE
Broken org-ref-helm-insert-cite-link

### ISSUE THREAD

**Issue by JP-Ellis** [jkitchin/org-ref#421]
Recently, the `org-ref-helm-insert-cite-link` command has stopped working as intended.  Instead of insert the appropriate citation, it only the BibTeX file at the appropriate entry (see syl20bnr/spacemacs#8739).

The bug has appeared in between the `20170411.736` and `20170413.1111` versions for which the diff is
```diff
diff --git a/org-ref-20170411.736/org-ref-helm-bibtex.el b/org-ref-20170413.1111/org-ref-helm-bibtex.el
index f2fdc3b..72aab36 100644
--- a/org-ref-20170411.736/org-ref-helm-bibtex.el
+++ b/org-ref-20170413.1111/org-ref-helm-bibtex.el
@@ -74,7 +74,7 @@
 						    "\n\n"))))
     ("Attach PDF to email" . helm-bibtex-add-PDF-attachment)
     ("Edit notes" . helm-bibtex-edit-notes)
-    ("Show entry" . helm-bibtex-show-entry)
+    ("Show BibTeX entry" . helm-bibtex-show-entry)
     ("Add keywords to entries" . org-ref-helm-tag-entries)
     ("Copy entry to clipboard" . bibtex-completion-copy-candidate) 
     ("Add PDF to library" . helm-bibtex-add-pdf-to-library))
diff --git a/org-ref-20170411.736/org-ref-helm-bibtex.elc b/org-ref-20170413.1111/org-ref-helm-bibtex.elc
index 1ad4dcb..4750460 100644
Binary files a/org-ref-20170411.736/org-ref-helm-bibtex.elc and b/org-ref-20170413.1111/org-ref-helm-bibtex.elc differ
diff --git a/org-ref-20170411.736/org-ref-pkg.el b/org-ref-20170413.1111/org-ref-pkg.el
index 8ae774c..b2ca495 100644
--- a/org-ref-20170411.736/org-ref-pkg.el
+++ b/org-ref-20170413.1111/org-ref-pkg.el
@@ -1,4 +1,4 @@
-(define-package "org-ref" "20170411.736" "citations, cross-references and bibliographies in org-mode"
+(define-package "org-ref" "20170413.1111" "citations, cross-references and bibliographies in org-mode"
   '((dash "2.11.0")
     (helm "1.5.5")
     (helm-bibtex "2.0.0")
```
so it appears that the cause of the bug was commit 0ae70233.  I'm not sure why renaming an action would cause this issue, but I have verified this by changing the name of the action and it fixes the issue.

Looking a bit deeper into the issue, I believe that this issue is due to a mismatch between the action name in [`helm-bibtex`](https://github.com/tmalsburg/helm-bibtex/blob/2e83867a39bbd4b7cb7901b897a66a131b5635e6/helm-bibtex.el#L194) and [`org-ref`](https://github.com/jkitchin/org-ref/blob/81204eaa39d556b6628b35627e0ccbe2799a8e68/org-ref-helm-bibtex.el#L77).

**Comment by jkitchin** [comment]
You are right! Thanks for tracking that down. The issue results from the way org-ref reorders the messages. I have reverted that and it should be working again now.

**Comment by JP-Ellis** [comment]
Thanks!  The issue is fixed.
