### ISSUE TITLE
HTML export roadmap

### ISSUE THREAD

**Issue by mlinchitstest** [jkitchin/org-ref#422]
Is there any plan to support CSL/styles for html exports?

Out of the box citations are formatted as `bibtexKey`; bibliography entries are just a bunch bibtex fields concatenated together with commas (if you have an empty field, you get `, , `); `@misc` does not seem to be supported at all — it just dumps an array of unformatted bibtex fields. None of the options seem to do anything for html. The bibliography section has a ginormous heading in the export, and I don't see how to make it smaller or eliminate it. So out of the box, every html file practically screams **BIBLIOGRAPHY** at the reader.

Latex/pdf exports are said to work well (I haven't tried them yet). Isn't there some way org-ref could take advantage of that to produce equally good html exports? 

Thanks

**Comment by jkitchin** [comment]
See http://kitchingroup.cheme.cmu.edu/blog/2015/12/11/Introduction-to-a-citation-processor-in-org-ref/

bibliography support is challenging for formats other than Latex. If I knew a good way to leverage latex for this I would do it ;)

**Comment by mlinchitstest** [comment]
Oh I see that you need to add this code:

``` lisp
(require 'org-ref-citeproc)
(require 'unsrt
           'author-year)
```
But the exports are still very messy: `@misc` doesn't work, curly brackets everywhere, `author-year` prints `author-whole-date`.

Are there any other tools one could use to get good html exports?  Any chance such tools could be integrated into the package in the future?
Thanks!

**Comment by jkitchin** [comment]
As noted in the blogpost, this is a hard problem that requires a citation processor. org-ref-citeproc is just a beginning effort. It would be more constructive to show examples of what doesn't work than to just say it doesn't work. The curly brackets are probably because you use bibtex like it was intended for latex for case preservation.

You might try this experimental function https://github.com/jkitchin/scimax/blob/master/ox-word.el#L75 that uses pandoc to export to html via latex. Pandoc is ok, but it has some issues too. There is nothing I know of that works really well. If you know of something, it can probably be integrated to org-ref.

**Comment by Cumol** [comment]
I have tried to use the export to word or html through pandoc using ox-word.el (I copy-pasted the code into my user.el file).

When I run the function  pandoc-html or pandoc-docx I get the error:
`pandoc: Prelude.!!: index too large`

This seems to be a pandoc issue (from short googling around) but I am not able to pinpoint it. The PDF is generated as usual but pandoc seems to choke.

**Comment by mlinchitstest** [comment]
@jkitchin  will you consider using [bibtex2html](https://www.lri.fr/~filliatr/bibtex2html/), like [ox-bibtex](http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=contrib/lisp/ox-bibtex.el;hb=HEAD) used to (no longer maintained)? It's produces some very good and apparently configurable output.

also, do you by chance how to tell emacs to use ox-bibtex instead of org-ref for html exports?

Thanks again!

**Comment by mlinchitstest** [comment]
https://github.com/wyleyr/org-citeproc

May be relevant

**Comment by jkitchin** [comment]
I would be happy to consider pull-requests in these directions.

**Comment by tecosaur** [comment]
@jkitchin this is a bit of a necro (sorry) but I have an idea for handling this, and I'm not sure whether it would be viable.

1. Generate a minimal text file, run `biber`, process `.bbl` file.
2. Some way of `\immediate\write` and LaTeX such that it does the biblio-stuff and write the output to a file in a useful manner.

Just some idle thoughts :smiley:

**Comment by jkitchin** [comment]
I think the way forward for non-latex exports  is via citeproc. That seems more advanced than the effort I tried in this package.

**Comment by tecosaur** [comment]
Indeed. `org-cite` / `citeproc` is the way forward now.
