### ISSUE TITLE
bibliography not produced by org-ref

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jkitchin/org-ref#423]
org-ref is working great, except I cannot produce the bibliography although it sees the citations and does not complain about any missing thing. E.g., this simple file does not produce the bibliography section (even if I use bibliographystyle:unsrt)

cite:Zwiggelaar2004LinearStruc

bibliographystyle:/home/wyousef/MyDocuments/Phd/texmf/bibtex/bst/base/Elsevier/elsart-harv.bst

My .emacs is:

(use-package org-plus-contrib
;;  :defer t
  :init
  (setq
   org-babel-load-languages(quote(
				    (C		.	t)
				    (calc	.	t)
				    (emacs-lisp	.	t)
				    (gnuplot	.	t)
				    (latex	.	t)
				    (matlab	.	t)
				    (python	.	t)
				    (ditaa	.	t)
				    (sh		.	t)))
   calendar-week-start-day 6
   org-src-fontify-natively t
   )
  :config
  (define-key org-mode-map "\M-q" 'toggle-truncate-lines)
  (define-key org-mode-map "\M-q" 'fill-paragraph)
  (setq org-startup-truncated t)
  )

**Comment by jkitchin** [comment]
You need a bibliography link too.

**Comment by DrWaleedAYousef** [comment]
It is not the problem since org-ref uses what is mentioned in the .emacs
file. I already specified one.

**Comment by DrWaleedAYousef** [comment]
So, if I modify it to the following; the same problem exist. It is a
bibtex issue with org-mode I think.

cite:Zwiggelaar2004LinearStruc

bibliography:/home/wyousef/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib
bibliographystyle:/home/wyousef/MyDocuments/Phd/texmf/bibtex/bst/base/Elsevier/elsart-harv.bst

**Comment by jkitchin** [comment]
For export to latex/pdf, there must be a bibliography link in the document.

Do you see any errors when you run M-x org-ref in the document?

I am not sure you can use a path in the bibliographystyle. It might be ok, but I have never done that before.

You may want to try manually building the pdf from the exported tex file. This will often show you more errors than the export does.

**Comment by DrWaleedAYousef** [comment]
org-ref does not show any error. Also, when I use
bibliographystyle:unsrt same problem exist. In addition, running latex
on the generated tex produces the pdf. So, the problem is I think in the
org mode configuration which does the export!

**Comment by jkitchin** [comment]
What is the value of org-latex-pdf-process?

**Comment by DrWaleedAYousef** [comment]
The default did not work; then I changed it to:

("%latex -interaction nonstopmode -output-directory %o %f" "%bib %b"
"%latex -interaction nonstopmode -output-directory %o %f" "%latex
-interaction nonstopmode -output-directory %o %f")

which does not work as well.

**Comment by jkitchin** [comment]
That looks like it should be ok, but you might try setting it to
(require 'ox-manuscript)
(setq org-latex-pdf-process 'ox-manuscript-latex-pdf-process)

**Comment by DrWaleedAYousef** [comment]
Sorry, what should I do with this:

   "ox-manuscript-templates/" starter-kit-dir

**Comment by jkitchin** [comment]
What is that? You should put the two lines i referenced above in an init file and execute them.

**Comment by DrWaleedAYousef** [comment]
but emacs complains:

Symbol's value as variable is void: starter-kit-dir

**Comment by jkitchin** [comment]
That means you aren't using scimax I guess. Try this instead (assuming you have latexmk installed):

(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))

**Comment by DrWaleedAYousef** [comment]
it works this way; but:

the behavior is weird; it shows in the mini-buffer that it keeps
latexing without opening the pdf. But if I interrupt with C-g and look
at the directory I find the pdf compiled correctly.

Thanks
