### ISSUE TITLE
allow doi-utils-add-entry-from-crossref-query to work with multiple selected results

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref#424]
If I do a query with `doi-utils-add-entry-from-crossref-query`, and select a result to add to a bibtex file, it works as expected.

If I select multiple items from the results list, nothing gets added, and I get no error. I expect all of them to be added.

Assuming this is intended behavior, is there any reason why not to allow multiple items?

**Comment by bdarcus** [comment]
Although, I did get JSON parsing error on a couple of the individual results.

**Comment by jkitchin** [comment]
This sounds like an error handling issue. When there are no errors, I am able to add multiple items.

**Comment by jkitchin** [comment]
I tried wrapping the doi retriever in ignore-errors to prevent it from dropping out on an error. It is pushed if you want to give it a try.

**Comment by bdarcus** [comment]
Thanks for the quick response!

I'm using spacemacs dev branch, which updates packages pretty quickly, but
I guess not yet. Will check as soon as it does.

Is it not odd to you that I'm getting JSON errors on some of the results?
Or is the quality and/or consistency of the data from crossref really
variable?

**Comment by jkitchin** [comment]
It doesn't surprise me. The error either comes from crossref or http://dx.doi.org and the quality/consistency varies a lot.

It usually takes 4-8 hours to get changes into MELPA.

**Comment by bdarcus** [comment]
I have updated org-ref, and run the same query. Getting some
strange/inconsistent results. I still need to check if this might be the
fault of the API.

The search results (on my last name) returns 10 results.

First time I ran it, if I select all of them, it inserts 5 of them in the
existing bib file (with two entries), without any errors (other than a "not
inserting duplicate" sort of error). So good.

I then try again, after deleting all entries in the file, but this time get
no bibtex entries inserted, but rather only the below (which I understand
is what I'd call a bug in the conversion code, and perhaps why I was
getting the JSON error, since it seems this should default to misc or
inbook, but I don't understand why the different behavior):

```
reference-entry not supported yet
(:indexed (:date-parts [[2017 3 31]] :date-time "2017-03-31T05:26:41Z"
:timestamp 1490938001913) :publisher-location "2455 Teller Road,  Thousand
Oaks  California  91320  United States " :reference-count 0 :publisher
"SAGE Publications, Inc." :content-domain (:domain []
:crossmark-restriction :json-false) :short-container-title [] :DOI
"10.4135/9781412952422.n244" :type "reference-entry" :created (:date-parts
[[2012 10 5]] :date-time "2012-10-05T19:40:36Z" :timestamp 1349466036000)
:source "Crossref" :is-referenced-by-count 0 :title "Radical Geography"
:prefix "10.4135" :author [(:given "B" :family "D'Arcus" :affiliation [])]
:member "179" :container-title "Encyclopedia of Human Geography"
:original-title [] :deposited (:date-parts [[2015 11 20]] :date-time
"2015-11-20T21:33:10Z" :timestamp 1448055190000) :score 1.0 :subtitle []
:short-title [] :issued (:date-parts [[nil]]) :ISBN ["
http://id.crossref.org/isbn/9780761988588" "
http://id.crossref.org/isbn/9781412952422"] :references-count 0
:alternative-id ["10.4135/9781412952422"] :URL "
http://dx.doi.org/10.4135/9781412952422.n244" :relation nil).
```

Finally, I try a third time, and after selecting the references, it does
not insert anything, and gives me no error (the original report).

I'll check if some of the inconsistency is the API itself.

**Comment by jkitchin** [comment]
I just added reference-entry to the inbook type. That should resolve the not supported issue.
