### ISSUE TITLE
"Copy formatted citation to clipboard" fails

### ISSUE THREAD

**Issue by mhlinder** [jkitchin/org-ref#425]
Like the title says, if I run

```
C-c C-o 10 RET
```

on a citation, I get the error

```
org-element-context: Wrong type argument: stringp, nil
```

I can verify that, eg, "Copy key to clipboard" executes successfully.

**Comment by jkitchin** [comment]
Thanks for reporting this. I think it is fixed now.

**Comment by mhlinder** [comment]
Thank you!

For what it's worth, I also get the same error trying to "Copy citation to keyboard" (`C-c C-o K`)...

Thanks again

**Comment by jkitchin** [comment]
your keybindings and menu items are different than mine.  For example, I had to type 17 in the first example. I don't understand what C-c C-o K should do when you are on a cite link. I also don't have an action "Copy citation to keyboard". If you mean "Copy key to clipboard", that works for me.

**Comment by jagrg** [comment]
I think mhlinder meant the hydra command in org-ref-ivy-cite.el. See `org-ref-copy-entry-as-summary`.

**Comment by mhlinder** [comment]
Thanks, jagrg—I did mean they hydra command.

Is there any way to disable the hydra interface? I actually had it disabled, but when I updated to yesterday's fix, the number-based interface had been replaced with hydra...

**Comment by jkitchin** [comment]
The interface depends on the backend you use for org-ref. If you want the helm interface you should use helm-bibtex or helm-cite as the backend. 

The hydra commands work fine with the fix I pushed as far as I can tell, at least K works for me.

**Comment by jagrg** [comment]
Sorry I missed your push. It's working now.
