### ISSUE TITLE
Org-ref causes Emacs to crash

### ISSUE THREAD

**Issue by JonathanReeve** [jkitchin/org-ref#427]
When inserting a citation into an org file, org-ref parses the file OK, but when I start typing the name of a Bibtex entry, it causes Emacs to completely crash. It's usually after I've typed two or three letters, but it's sometimes after I've only typed one. It usually crashes faster when I type faster. I have no idea what's going on here or how to debug it. 

Since I've been using org-ref via Spacemacs, I've also added this issue here: https://github.com/syl20bnr/spacemacs/issues/8833.

**Comment by jkitchin** [comment]
I am not able to reproduce this. Are you using a helm or ivy backend?

**Comment by JonathanReeve** [comment]
Helm. It looks like the crash only happens on Emacs 25, and seems to be fixed on the current master branch (26).

**Comment by jkitchin** [comment]
Thanks for reporting it.

**Comment by jkitchin** [comment]
What OS was this on?

**Comment by JonathanReeve** [comment]
Here's the info automatically gathered from the Spacemacs bug reporting utility: 

System Info 💻

    OS: gnu/linux
    Emacs: 25.2.1
    Spacemacs: 0.200.9
    Spacemacs branch: master (rev. 8e1af14)
    Graphic display: t
    Distribution: spacemacs
    Editing style: vim
    Completion: helm
    Layers:
