### ISSUE TITLE
Export of org-ref.org fails with: Unable to resolve link: "id:212B487E-CC38-4BDF-9F0E-6993845AF49B"

### ISSUE THREAD

**Issue by lechten** [jkitchin/org-ref#428]
When exporting org-ref.org (to LaTeX as well as to HTML) I get this error: Unable to resolve link: "id:212B487E-CC38-4BDF-9F0E-6993845AF49B"

I'm on Emacs master with Org mode 9.0.6 and org-ref-20170501.940.

**Comment by jkitchin** [comment]
You probably need these libraries loaded to export that file:
(require 'org-id)
(require 'org-ref-wos)
(require 'org-ref-scopus)
(require 'org-ref-pubmed)

**Comment by lechten** [comment]
And this one:
(require 'org-ref)

Many thanks
Jens
