### ISSUE TITLE
org-ref invalid org-store-link in org babel

### ISSUE THREAD

**Issue by stardiviner** [jkitchin/org-ref#433]
When I try to `org-store-link` in an opened org babel src block like this:
```org
#+BEGIN_SRC clojure
(defn ) 
#+END_SRC
```

It should be work like this:

```org
#+BEGIN_SRC clojure
(defn )                                                             (ref:hello)
#+END_SRC
```

But it failed with error:

```
 Debugger entered--Lisp error: (wrong-type-argument stringp nil)
   looking-at(nil)
   org-element-context()
   org-label-store-link()
   org-store-link(nil)
   ...
   funcall-interactively(org-store-link nil)
   call-interactively(org-store-link nil nil)
   command-execute(org-store-link)
```

I tried to edebug this, found related to `org-ref`. Then I confirmed with minimal Emacs config `emacs -q -l minimal-init.el`.

Emacs version: `26.0.50` build from master source code
Org-mode version: `9.0.6` install from MELPA
org-ref version: `1.0.0` `(git-commit 10dc99582ba866fb825443d1bd2132920b9db39f)`

**Comment by jkitchin** [comment]
I can't reproduce the error. (org-store-link) in a code block for me stores a reference to the heading the block is in. Where in org-ref did you find the problem to come from?

**Comment by stardiviner** [comment]
Did you open the src block with `[C-c ']` then `org-store-link`? It will create a code ref like `(ref:<string you input>)`, Then you can `org-inser-link` (`[C-c C-l]`) to insert link to `(ref:<string you input>)`. Instead of the heading that the block is in.

**Comment by stardiviner** [comment]
Have not found where the `org-ref` problem comes from, but I found if I toggle `org-ref`, then the error will occurs.

**Comment by jkitchin** [comment]
yes, that works fine for me. below, i opened the block, ran org-store-link and typed in hello. Then closed the block and used C-c C-l to insert the link.

```
#+BEGIN_SRC python
print(5)                                                            (ref:hello)
#+END_SRC

[[(hello)]]
```

**Comment by jagrg** [comment]
I think it's a bug in `org-store-link`. It works with the change below, but I'm not sure why it works with python, but not clojure. Maybe raise an issue in the Org-mode mailing list.

```patch
modified   lisp/org.el
@@ -9730,7 +9730,7 @@ active region."
 	     (setq sfuns
 		   (delq
 		    nil (mapcar (lambda (f)
-				  (let (fs) (if (funcall f) (push f fs))))
+				  (let (fs) (if (and (stringp f) (funcall f)) (push f fs))))
 				(org-store-link-functions)))
 		   sfunsn (mapcar (lambda (fu) (symbol-name (car fu))) sfuns))
 	     (or (and (cdr sfuns)
```

**Comment by stardiviner** [comment]
Confirmed, this patch works. @jagrg Can you send this patch to Org-mode Mailing List?

**Comment by jagrg** [comment]
I'm not on that list. If you are, please do.

On 08 May 2017, stardiviner <notifications@github.com> wrote:

> Confirmed, this patch works. @jagrg Can you send this patch to Org-mode Mailing List?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by stardiviner** [comment]
Ok, I will send this patch to mailing list. Thanks for this patch.

**Comment by jkitchin** [comment]
It was org-ref after all. I think I have pushed a fix for it.

**Comment by jagrg** [comment]
Problem solved. Thanks. Pretty sure I dug the wrong hole. ;)

On 09 May 2017, John Kitchin <notifications@github.com> wrote:

> It was org-ref after all. I think I have pushed a fix for it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by jkitchin** [comment]
it did eventually confirm org-ref was to blame ;)
