### ISSUE TITLE
drag and drop PDF to add to bibliography / notes

### ISSUE THREAD

**Issue by edgimar** [jkitchin/org-ref#44]
I noticed you were experimenting with drag-and-drop in a blog post you wrote, John.  What would be ideal, I think, is to connect this to org-ref in a way like how Mendeley works, where you can just drag a PDF into it, and it will store it in a central folder, extract/look-up metadata, add a bibtex entry to your default bib file, a note-entry to your bibliography-notes file, and optionally rename the stored PDF based on the metadata.

It would also be great if annotations were automatically extracted from the PDF, and added as a list under an "Annotations" sub-heading of the bibliography-notes entry, where each list-item has a corresponding link to open the PDF/page where the annotation is located.  It would also be good to have the option to set up your own function for opening the PDF that can take a page number as an argument, so that a tool which allows annotating can be used.  If this all were to be implemented, it would probably make sense to have an elisp function that can be used to refresh a note-entry's annotation-list.

**Comment by jkitchin** [comment]
That is a nice idea. Do you know how this information is extracted from the pdf? Could you send me an example of a PDF you know has this metadata in it?

**Comment by edgimar** [comment]
Sometimes I believe metadata can be embedded in the PDF directly, but I'm talking more about tools that read the PDF, and guess (e.g. based on the title, authors, etc.) what paper it is by searching for it.  A nice tool I've used that does renaming in this manner is [gscholar](https://github.com/venthur/gscholar).

There appears to be some elisp code that semi-automates the pulling of google-scholar (and other) source data and constructing a bibtex entry from it -- see [gscholar-bibtex](https://github.com/cute-jumper/gscholar-bibtex).

As for metadata directly embedded in the PDF, there seems to be some older information on this [here](http://musingsaboutlibrarianship.blogspot.com/2010/07/extracting-metadata-from-pdfs-comparing.html) and [here](http://rossmounce.co.uk/2013/01/06/pdf-metadata-using-exiftool/).

**Comment by jkitchin** [comment]
Thanks for these links. I will take a look at them. I actually tried the
python one, and after the third use or so google blocked me! But it
looks like a lot of the work is done in gscholar-bibtex already.

edgimar writes:

> Sometimes I believe metadata can be embedded in the PDF directly, but I'm talking more about tools that read the PDF, and guess (e.g. based on the title, authors, etc.) what paper it is by searching for it.  A nice tool I've used that does renaming in this manner is [gscholar](https://github.com/venthur/gscholar).
>
> There appears to be some elisp code that semi-automates the pulling of google-scholar (and other) source data and constructing a bibtex entry from it -- see [gscholar-bibtex](https://github.com/cute-jumper/gscholar-bibtex).
>
> As for metadata directly embedded in the PDF, there seems to be some older information on this [here](http://musingsaboutlibrarianship.blogspot.com/2010/07/extracting-metadata-from-pdfs-comparing.html) and [here](http://rossmounce.co.uk/2013/01/06/pdf-metadata-using-exiftool/).
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/44#issuecomment-121470621

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
Update on this issue. I added https://github.com/jkitchin/org-ref/blob/master/org-ref-url-utils.el, which provides some support to drag a webpage onto a bibtex file to add a bibtex entry.

**Comment by llcc** [comment]
I implemented a rough method to add an bibtex entry by drag-and-dropping the pdf to emacs if the doi is embedded in the file.

```emacs-lisp
(defun extract-metadata-from-pdf (event)
  (interactive "e")
  (goto-char (nth 1 (event-start event)))
  (x-focus-frame nil)
  (let* ((payload (car (last event)))
	 (pdf-file (abbreviate-file-name (replace-regexp-in-string "\\\\" "/" (car payload))))
	 (text-file (concat (f-no-ext pdf-file)))
	 doi)
    (save-excursion
      (shell-command (format "pdftotext %s %s" pdf-file text-file))
      (find-file-existing text-file)
      (beginning-of-buffer)
      (if (re-search-forward "http://dx.doi.org/\\(10.+$\\)" nil nil)
	  (setq doi (match-string 1))
	(user-error "No doi can be found in the pdf file"))
      (kill-buffer)
      (delete-file text-file)
      (doi-utils-add-bibtex-entry-from-doi doi (car org-ref-default-bibliography)))))

(bind-key "<drag-n-drop>" 'extract-metadata-from-pdf)
``` 
I used a `pdftotext` command from git which can convert a pdf to a text file. If the doi of current file is embedded in this file, we can search and get the doi, then use it to add a bibtex entry for the default bibliography file.

This is just a rough idea. I tried to extract the title from the text file, however, the title is just plain text without any properties. So I think a better solution is to find a new application which can extract the right metadata instead of `pdftotext`.

Any improvement and advice about this is appreciated!

**Comment by jkitchin** [comment]
This is a good start. I will give it some tests this weekend. I think we could think of a series of functions to try. First, if metadata exists we should get it since it is most reliable. Second we could try this approach. The only risk is it takes the first doi link, which we have to assume is for the article. if this failed, then a google/crossref search on some text from the pdf might be the last resort before giving up.

**Comment by llcc** [comment]
`pdftotext` can accept arguments to generate a metadata html file. Then we can use it to get title, even authors and other things. I updated the above function and git it to https://github.com/llcc/org-ref-extraction-metadata-from-pdf, please have a look (sorry, i named it started with org-ref. Please tell me if it is not good).

Still need some fixes, but the basic has been expressed.

**Comment by llcc** [comment]
@jkitchin can you create a file for pdf metadata extraction in the org-ref repository? It will be easier for us to submit? If so, I will merge the function in org-ref. Thanks!

**Comment by jkitchin** [comment]
I committed a draft file here https://github.com/jkitchin/org-ref/blob/master/org-ref-pdf.el

It matches two types of DOIs in pdftotext. If one doi is found, it adds it as a bibtex entry. If two are found, it offers a helm selection menu for which one you want.

I like your idea of getting more structured metadata, but on some tests of about 100 pdfs, I didn't find any useful information in them. This still needs a lot of testing, so PRs are welcome for improvements!

**Comment by jkitchin** [comment]
I am going to close this. Most of the functionality described above has been implemented now. Thanks for the idea! The second idea about extracting annotations is outside the scope of org-ref for now I think. The only other thing not done is renaming the pdf. That might be a good idea to do some time.
