### ISSUE TITLE
Org-ref can't open PDFs from BibTeX file attributes

### ISSUE THREAD

**Issue by JonathanReeve** [jkitchin/org-ref#441]
Here's an example of one of my BibTeX entries, created automatically from Zotero (with the Better BibTeX plugin):  

```
@article{whittaker_joyce_1987,
  title = {Joyce and {{Skeat}}},
  volume = {24},
  timestamp = {2015-06-06T18:02:59Z},
  number = {2},
  journaltitle = {James Joyce Quarterly},
  author = {Whittaker, Stephen},
  date = {1987},
  pages = {177--192},
  file = {//James Joyce/Portrait of the Artist as a Young Man/Whittaker_1987_Joyce and Skeat.pdf},
  groups = {Portrait of the Artist as a Young Man,Portrait of the Artist as a Young Man}
}
```
The path here is actually a relative path to `~/Dropbox/Papers/James Joyce/`, etc. I have `org-ref-pdf-directory` set to  `"~/Dropbox/Papers/"` and `bibtex-completion-pdf-field` to `"file"`. Am I doing something wrong, or can org-ref not handle these types of paths?

**Comment by jkitchin** [comment]
org-ref normally just looks for a pdf of {bibtex-key}.pdf in org-ref-pdf-directory. You can customize the variable org-ref-get-pdf-filename-function to get different behavior. See the documentation for that variable. There are a few example functions that might get you what you want.

**Comment by JonathanReeve** [comment]
Ok cool, thanks. I eventually got it to work with this: 

```lisp
  (defun org-ref-get-zotero-pdf-filename (key)
    "Return the pdf filename indicated by zotero file field.
Argument KEY is the bibtex key."
    (let* ((results (org-ref-get-bibtex-key-and-file key))
           (bibfile (cdr results))
           entry)
      (with-temp-buffer
        (insert-file-contents bibfile)
        (bibtex-set-dialect (parsebib-find-bibtex-dialect) t)
        (bibtex-search-entry key nil 0)
        (setq entry (bibtex-parse-entry))
        (let ((e (org-ref-reftex-get-bib-field "file" entry)))
          (if (> (length e) 4)
              (let ((clean-field (replace-regexp-in-string "/+" "/" e)))
                (let ((first-file (car (split-string clean-field ";" t))))
                  (concat org-ref-pdf-directory first-file)))
            (message "PDF filename not found.")
            )))))
```

**Comment by dalanicolai** [comment]
Just for documentation: to open files from the `file` attributes (e.g. for bibtex files exported from Zotero), set the `org-ref-get-pdf-filename-function` to `org-ref-get-mendeley-filename`.
