### ISSUE TITLE
ref, cite, and bibliography links go uncompiled in latex export

### ISSUE THREAD

**Issue by dcalacci** [jkitchin/org-ref#442]
Hi, thank you for the wonderful work and useful package!

I am trying to configure org-ref for my machine and I consistently cannot get latex exporting to compile the org-ref links (ref:XXX, cite:XXXX) to latex citations or refs. It's not clear to me if it's a straight org-ref issue, or if I am lacking some extra package or configuration. I've followed the configuration instructions on the readme and have browsed through issues to no avail!

inserting reference links using the normal org-mode [[fig-name]] works properly.

## Input
Create any org-mode file with the following pattern:

```
See figure ref:myimg for details.

#+caption: an image label:myimg
[[./img.png]]
```

Where both the label and the reference are input using the helm autocompletion in org-ref.

Then, export to latex using `C-e l l`

## Expected behavior
I expect the ref link to be compiled into a \ref{...} expression in latex, like so:

```
See figure \ref{compiled-img} for details
```

## Actual behavior

Instead, it remains uninterpreted:

```
See figure ref:myimg for details
```

The image and its label seem to be compiled correctly, with the label being compiled to a unique ID:

```
\begin{figure}[htbp]
\centering
\includegraphics[width=.9\linewidth]{img.png}
\caption{\label{fig:org1c085f6}
an image}
\end{figure}
```

I of course am experiencing the same issue with bibliography and cite links as well. 

using \cite{...} directly in the org buffer works perfectly when exporting to latex or a PDF.

## Configuration
I have org-ref installed, and include the following packages in my init:

```
  (require 'org-ref)
  (require 'ox-latex)
  (require 'doi-utils)
  (require 'org-ref-isbn)
  (require 'org-ref-pubmed)
  (require 'org-ref-arxiv)
  (require 'org-ref-bibtex)
  (require 'org-ref-pdf)
  (require 'org-ref-url-utils)
```

Thanks for any help!

**Comment by dcalacci** [comment]
Discovered this afternoon that using the org-ref menu:
```
M-x org-ref RET
```
and selecting `Export to pdf and open` resolves references and citations correctly. (hooray :tada: !)

Is there a way to have this functionality in the normal org export menu?

**Comment by jkitchin** [comment]
That should be about the same as C-c C-e l o. All it does is run (org-open-file                                                                    (org-latex-export-to-pdf)).

**Comment by jkitchin** [comment]
How are you doing your export?

**Comment by dcalacci** [comment]
I am/was doing my export using C-c C-e l o. Only calling the org-ref menu item seems to work properly. I might spend some time soon to debug myself, but maybe until then the issue can be closed? seems like most others are not having this issue, it may just be a idiosyncrasy of my configuration.
