### ISSUE TITLE
Configure org-ref to work with multiple notes.org files?

### ISSUE THREAD

**Issue by adam52** [jkitchin/org-ref#443]
I have `Helm-Bibtex` setup to work with a `~/notes` directory (one note per reference). But `org-ref` wants to point to a single notes.org file... How can I get `rg-ref` to point to the `~/notes` directory, to match `helm-bibtex`?

Thanks!

**Comment by jkitchin** [comment]
See the documentation for the variable org-ref-notes-function. (C-h v org-ref-notes-function) I think it explains how to get what you want.

**Comment by adam52** [comment]
Thanks John, that worked! Hey, you might think about adding this to the readme on Github. I was totally confused about whether I had to specify `org-ref-bibliography-notes` because it was setup in the Configuration section. Turns out, I didn't.

Here is the relevant except from my final configuration:

    ;; Setup org-ref
       (setq reftex-default-bibliography '("~/org/catalog.bib"))
        (setq org-ref-default-bibliography '("~/org/catalog.bib")
              org-ref-pdf-directory "~/Papers/")
    
     ;; Tell org-ref to let helm-bibtex find notes for it
        (setq org-ref-notes-function
           (lambda (thekey)
             (let ((bibtex-completion-bibliography (org-ref-find-bibliography)))
               (bibtex-completion-edit-notes
                (list (car (org-ref-get-bibtex-key-and-file thekey)))))))

**Comment by jkitchin** [comment]
Thanks. I will add something like this to the manual.
