### ISSUE TITLE
An idea: using bracket links to enable seeing the citation links as they are.

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#445]
I am new to both org-ref and lisp and so contributing actual code is still a challenge. However, I would like to contribute what seems to me a great idea.
The idea is to change the link format **from**: `cite:<key>` **to**: `[[cite:<key>][<the citation the way it will look in the paper>]]`
These links are as easy to find as the links in the current format. However, they provide for a much clearer `.org` document.

**Comment by jkitchin** [comment]
Thanks for the suggestion. This would make it a lot more like using Endnote with Word. I don't think it is feasible though for a few reasons. The description is already used for pre/post text in LaTeX export. I don't see a reasonable path to keep that and enable what you describe. There are also too many citation formats to try to support, e.g. brackets, superscripts, author-year, unsorted, alphabetical, ... It might be possible in the future to superscript the citations in a smaller font, but I don't think the org file will ever be formatted like using Endnote/Word is.

**Comment by timmli** [comment]
Following up on what @mgoldenbe proposed, how can I just add the brackets around the link (not the description)? So instead of `cite:<key>` have `[[cite:<key>]]`? I usually add the brackets by hand because it looks more uniform and I can better identify them. Moreover, sometimes there shouldn't be a space between a cite link and the preceding word, e.g. with `supercite`, which is not easy to achieve without brackets.

**Comment by jkitchin** [comment]
I pushed an option that would let you specify bracketed links by default. You should be able to (setq org-ref-prefer-bracket-links t) and cite links will then be bracketed. It doesn't work for ref or label links yet.

**Comment by mgoldenbe** [comment]
Sorry for my ignorance. Does "pushed" mean that it is available through
Melpa?

**Comment by jkitchin** [comment]
It will be on Melpa in 6-8 hours I guess.

**Comment by timmli** [comment]
@jkitchin Thanks! I've updated `org-ref` and set `org-ref-prefer-bracket-links`, but no brackets are inserted with a citation when using `C-c ]` (i.e. `org-ref-helm-insert-cite-link`).  Hm.

**Comment by jkitchin** [comment]
I can confirm that for helm-bibtex. I just pushed two small fixes for that. Will probably be available on MELPA by tomorrow.

**Comment by timmli** [comment]
Looks better! But now, cite links have the appearance of common links, which means that brackets are hidden and the color in `org-ref-cite-color` is not used any more. Is this intended?

**Comment by jagrg** [comment]
I'm having the same issue. Link :face and :display parameters stopped working, and the strange thing is it still fails without org-ref.

**Comment by jkitchin** [comment]
That makes it sound like an orgmode issue.

**Comment by jkitchin** [comment]
@jagrg what backend for org-ref are you using?

**Comment by jagrg** [comment]
As in ivy or helm? I'm using helm.

On 20 Jun 2017, John Kitchin <notifications@github.com> wrote:

> @jagrg what backend for org-ref are you using?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by jkitchin** [comment]
helm-bibtex or helm-cite?

**Comment by jagrg** [comment]
helm-bibtex

On 20 Jun 2017, John Kitchin <notifications@github.com> wrote:

> helm-bibtex or helm-cite?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by jkitchin** [comment]
hm. I saw an issue with link fontification with helm-cite because the fontification code uses features from helm-bibtex. but if you are using helm-bibtex that shouldn't be an issue. Are there any messages in *Messages* indicating font-lock issues? Also, is it just org-ref links that are problematic?

**Comment by jagrg** [comment]
Thanks for the feedback. TBH I have no idea why it stopped working
(there are no font-lock issues in the Messages buffer), and I'm pretty
sure I don't have a mixed installation of Org. With emacs -Q and the
code below, I get a normal link in the Org buffer (no full display and
no green face either). Everything else is working fine. Very strange.

```
(org-link-set-parameters
 "green"
 :display 'full
 :follow (lambda (_) (message "I am green."))
 :face '(:foreground "green"))
```

On 20 Jun 2017, John Kitchin <notifications@github.com> wrote:

> hm. I saw an issue with link fontification with helm-cite because the fontification code uses features from helm-bibtex. but if you are using helm-bibtex that shouldn't be an issue. Are there any messages in *Messages* indicating font-lock issues? Also, is it just org-ref links that are problematic?


--
Jonathan

**Comment by stardiviner** [comment]
Maybe because the `org-activate-bracket-links` is not valid in `org-mode` `9.0.8` (I'm using Org-mode source code branch `master`).
So the source code:
```
(when org-ref-colorize-links
    (add-hook
     'org-mode-hook
     (lambda ()
       (advice-add 'org-activate-bracket-links :after #'org-ref-make-org-link-cite-key-visible)
       (font-lock-add-keywords
	nil
	'((org-ref-match-next-cite-link (0  'org-ref-cite-face t))
	  (org-ref-match-next-label-link (0  'org-ref-label-face t))
	  (org-ref-match-next-ref-link (0  'org-ref-ref-face t))
	  (org-ref-match-next-bibliography-link (0  'org-link t))
	  (org-ref-match-next-bibliographystyle-link (0  'org-link t)))
	t))))
```

Does not work.
Even I evaluate (without upper advice):
```
(add-hook 'org-mode-hook (lambda () (font-lock-add-keywords
	                               nil
	                               '((org-ref-match-next-cite-link (0  'org-ref-cite-face t))
	                                 (org-ref-match-next-label-link (0  'org-ref-label-face t))
	                                 (org-ref-match-next-ref-link (0  'org-ref-ref-face t))
	                                 (org-ref-match-next-bibliography-link (0  'org-link t))
	                                 (org-ref-match-next-bibliographystyle-link (0  'org-link t)))
	                               t)))
```
Then `[M-x org-mode]` again. Still does not work.

**Comment by jkitchin** [comment]
It is an org 9.0.8 issue. I don't think it is related to org-activate-bracket-links though. That code is only executed in org-8 installations. The problem is there is a bug in the new org-activate-links. I have reported it. I would recommend reverting to 9.0.7 if the fontification is important.

**Comment by timmli** [comment]
I can confirm that, after upgrading to org 9.0.9, cite links are displayed with brackets and `org-ref-cite-color`. I think the issue can be closed.

**Comment by stardiviner** [comment]
I'm using Org-mode source code repository, I'm curious which branch (`master` and `maint`) is newer?

**Comment by stardiviner** [comment]
I tried both `master` and `maint` branches, neither of them works.

**Comment by jkitchin** [comment]
you should not be evaluating that code in org9. The links are natively fontified. I guess that master is the "newest" one of those branches.

**Comment by jagrg** [comment]
Links are back to normal now. @jkitchin thanks for reporting the issue.

@stardiviner indeed, the code you're trying to evaluate is only needed when `org-link-set-parameters` is void, which I would assume is not your case (see line 677 in org-ref-core.el).

On 23 Jun 2017, John Kitchin <notifications@github.com> wrote:

> you should not be evaluating that code in org9. The links are natively fontified. I guess that master is the "newest" one of those branches.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan

**Comment by stardiviner** [comment]
@jkitchin @jagrg Even I don't evaluate those code manually, I load `org-ref` with the following config:
```elisp
(use-package org-ref
  :ensure t
  :config
  ;; https://github.com/jkitchin/org-ref/issues/184
  (setq bibtex-completion-pdf-open-function 'org-open-file)
  ;; (setq org-ref-open-pdf-function )
  (setq org-latex-prefer-user-labels t)
  (setq org-ref-default-ref-type "ref") ; choose the default ref type for `org-ref'.
  (setq org-ref-show-broken-links nil) ; very poor performance.
  (setq org-ref-prefer-bracket-links t) ; wrap org-ref links with brackets.
  (setq org-ref-colorize-links t) ; colorize org-ref links.

  ;; Let org-mode auto process the LaTeX export to PDF process.
  (setq org-latex-pdf-process
        '("pdflatex -interaction nonstopmode -output-directory %o %f"
          "bibtex %b"
          "pdflatex -interaction nonstopmode -output-directory %o %f"
          "pdflatex -interaction nonstopmode -output-directory %o %f"))

  ;; setup org-ref keybindings
  (setq org-ref-bibtex-hydra-key-binding (kbd "C-c ]"))

  (define-key bibliograph-prefix (kbd "C-]") 'org-ref)
  (define-key bibliograph-prefix (kbd "C-l") 'org-ref-insert-link)
  (define-key bibliograph-prefix (kbd "r") 'org-ref-helm-insert-ref-link)
  (define-key bibliograph-prefix (kbd "c") 'org-ref-helm-insert-cite-link)
  (define-key bibliograph-prefix (kbd "l") 'org-ref-helm-insert-label-link)

  ;; specify `org-ref' bibliography sources
  (require 'f)
  (setq org-ref-notes-directory "~/Org/Bibliography/"
        org-ref-bibliography-notes "~/Org/Bibliography/index.org"
        org-ref-default-bibliography (f-files "~/Org/Bibliography/"
                                              (lambda (f)
                                                (f-ext? f "bib")))
        org-ref-bibliography-notes "~/Org/Bibliography/notes/"
        org-ref-pdf-directory "~/Org/Bibliography/lib/")
  )
```
It still does not colored. I even use `customize-font` to check out the font at `org-ref` link under the point. It does not have associated face.

**Comment by jagrg** [comment]
I'm not sure why it's not working for you. Try with emacs -Q and see if `org-link-set-parameters` works. Also check if you are using version 9.0.9 (http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=521734d51fa2695257793886cb62d16851185d63) and that you don't have a mixed installation of Org (http://orgmode.org/worg/org-faq.html#mixed-install).

@jkitchin Emacs slows down when org-ref-show-broken-links is set to t. It gets worse with larger files.

On 23 Jun 2017, stardiviner <notifications@github.com> wrote:

> @jkitchin @jagrg Even I don't evaluate those code manually, I load `org-ref` with the following config:
> ```elisp
> (use-package org-ref
>   :ensure t
>   :config
>   ;; https://github.com/jkitchin/org-ref/issues/184
>   (setq bibtex-completion-pdf-open-function 'org-open-file)
>   ;; (setq org-ref-open-pdf-function )
>   (setq org-latex-prefer-user-labels t)
>   (setq org-ref-default-ref-type "ref") ; choose the default ref type for `org-ref'.
>   (setq org-ref-show-broken-links nil) ; very poor performance.
>   (setq org-ref-prefer-bracket-links t) ; wrap org-ref links with brackets.
>   (setq org-ref-colorize-links t) ; colorize org-ref links.
>
>   ;; Let org-mode auto process the LaTeX export to PDF process.
>   (setq org-latex-pdf-process
>         '("pdflatex -interaction nonstopmode -output-directory %o %f"
>           "bibtex %b"
>           "pdflatex -interaction nonstopmode -output-directory %o %f"
>           "pdflatex -interaction nonstopmode -output-directory %o %f"))
>
>   ;; setup org-ref keybindings
>   (setq org-ref-bibtex-hydra-key-binding (kbd "C-c ]"))
>
>   (define-key bibliograph-prefix (kbd "C-]") 'org-ref)
>   (define-key bibliograph-prefix (kbd "C-l") 'org-ref-insert-link)
>   (define-key bibliograph-prefix (kbd "r") 'org-ref-helm-insert-ref-link)
>   (define-key bibliograph-prefix (kbd "c") 'org-ref-helm-insert-cite-link)
>   (define-key bibliograph-prefix (kbd "l") 'org-ref-helm-insert-label-link)
>
>   ;; specify `org-ref' bibliography sources
>   (require 'f)
>   (setq org-ref-notes-directory "~/Org/Bibliography/"
>         org-ref-bibliography-notes "~/Org/Bibliography/index.org"
>         org-ref-default-bibliography (f-files "~/Org/Bibliography/"
>                                               (lambda (f)
>                                                 (f-ext? f "bib")))
>         org-ref-bibliography-notes "~/Org/Bibliography/notes/"
>         org-ref-pdf-directory "~/Org/Bibliography/lib/")
>   )
> ```
> It still does not colored. I even use `customize-font` to check out the font at `org-ref` link under the point. It does not have associated face.


-- 
Jonathan

**Comment by stardiviner** [comment]
@jagrg I checked, I don't have mixed install of org-mode. And I check out source code of `org.el`, it has this fixed commit. But my `org-version` is `Org mode version 9.0.8 (9.0.8-elpaplus @ /home/stardiviner/Code/Emacs/org-mode/lisp/)` Not `org 9.0.9`.

**Comment by jchkoch** [comment]
I am fairly new to emacs-lisp so contributing code is still somewhat challenging. I am thoroughly enjoying the ease with which to use org-ref so thank you very much for this project @jkitchin . 

To build off the idea of using bracket links to see the citation links that @mgoldenbe proposed, the idea would be to change the link format **from** `cite:<key>` **to** [[`cite:<key>`][(Author /et al./ Year)]] so that when the org file is exported to LaTeX the `cite:<key>` is used and when exported to ODT the text "(Author /et al./ Year)" would be used. The main idea would be to make the ODT file be simple text without the "\cite{...}" tag. I agree with @jkitchin that formatted citations in a **org file** will probably never be formatted like using Endnote/Word; however, clean export without the "\cite" tag in ODT would be nice.

Attached is the link to this being implemented using RefTeX (https://www.reddit.com/r/orgmode/comments/41osyw/export_org_file_to_odt_with_bibtex_references/).

Is this possible to implement with org-ref? As I understand if this is possible, only the citations would be exported into ODT not the reference list. This leads me to another question, is it possible to then export the reference list to ODT? I know that `org-ref-find-bibliography` can be used to find the bibliography but can this then be exported as simple text to ODT?

Any thoughts on this would be most appreciated?

**Comment by jagrg** [comment]
For your last point, here's an idea. It uses bibtex-completion-apa-format-reference to insert the bibliography.

```
(defun org-ref-odt-insert-bibliography (backend)
  (when (org-export-derived-backend-p backend 'odt)
    (let ((keys (org-ref-get-bibtex-keys t)))
      (goto-char (point-max))
      (insert
       (concat "\nBibliography\n\n"
	       (mapconcat (lambda (x)
			    (bibtex-completion-apa-format-reference x))
			  keys "\n\n"))))))
(add-to-list 'org-export-before-processing-hook 'org-ref-odt-insert-bibliography)
```

On 05 Jul 2017, jchkoch <notifications@github.com> wrote:

> I am fairly new to emacs-lisp so contributing code is still somewhat challenging. I am thoroughly enjoying the ease with which to use org-ref so thank you very much for this project @jkitchin . 
>
> To build off the idea of using bracket links to see the citation links that @mgoldenbe proposed, the idea would be to change the link format **from** `cite:<key>` **to** [[`cite:<key>`][(Author /et al./ Year)]] so that when the org file is exported to LaTeX the `cite:<key>` is used and when exported to ODT the text "(Author /et al./ Year)" would be used. The main idea would be to make the ODT file be simple text without the "\cite{...}" tag. I agree with @jkitchin that formatted citations in a **org file** will probably never be formatted like using Endnote/Word; however, clean export without the "\cite" tag in ODT would be nice.
>
> Attached is the link to this being implemented using RefTeX (https://www.reddit.com/r/orgmode/comments/41osyw/export_org_file_to_odt_with_bibtex_references/).
>
> Is this possible to implement with org-ref? As I understand if this is possible, only the citations would be exported into ODT not the reference list. This leads me to another question, is it possible to then export the reference list to ODT? I know that `org-ref-find-bibliography` can be used to find the bibliography but can this then be exported as simple text to ODT?
>
> Any thoughts on this would be most appreciated?


-- 
Jonathan

**Comment by jagrg** [comment]
And here's an idea for getting pre/post citations using the harvard style. The org-ref-make-format-function macro would need to be modified.

```
(defun org-ref-odt-formatter (key &optional desc)
  (let ((s (mapconcat
	    (lambda (key)
	      (let* ((key key)
		     (entry (bibtex-completion-get-entry key))
		     ;; last name
		     (author (car (last
				   (s-split " " (orhc-bibtex-field-formatter "author" entry)))))
		     (year (orhc-bibtex-field-formatter "year" entry)))
		(format "%s %s" author year)))
	    (org-ref-split-and-strip-string key) "; ")))
    (if desc
	(if (string-match "::" desc)
	    (let* ((text (split-string desc "::"))
		   (pre (car text))
		   (post (cadr text)))
	      (cond ((and pre (and post (not (string= "" post))))
		     (format "[%s %s, %s]" pre s post))
		    (pre
		     (format "[%s %s]" pre s))
		    (post
		     (format "[%s, %s]" s post))))
	  (format "[%s, %s]" s desc))
      (format "[%s]" s))))

(org-ref-odf-formatter "key1")
(org-ref-odf-formatter "key1" "p.12")
(org-ref-odf-formatter "key1" "see::")
(org-ref-odf-formatter "key1" "see::p.12")
(org-ref-odf-formatter "key1,key2")
(org-ref-odf-formatter "key1,key2" "p.12")
(org-ref-odf-formatter "key1,key2" "see::")
(org-ref-odf-formatter "key1,key2" "see::p.12")
```

On 05 Jul 2017, jchkoch <notifications@github.com> wrote:

> I am fairly new to emacs-lisp so contributing code is still somewhat challenging. I am thoroughly enjoying the ease with which to use org-ref so thank you very much for this project @jkitchin . 
>
> To build off the idea of using bracket links to see the citation links that @mgoldenbe proposed, the idea would be to change the link format **from** `cite:<key>` **to** [[`cite:<key>`][(Author /et al./ Year)]] so that when the org file is exported to LaTeX the `cite:<key>` is used and when exported to ODT the text "(Author /et al./ Year)" would be used. The main idea would be to make the ODT file be simple text without the "\cite{...}" tag. I agree with @jkitchin that formatted citations in a **org file** will probably never be formatted like using Endnote/Word; however, clean export without the "\cite" tag in ODT would be nice.
>
> Attached is the link to this being implemented using RefTeX (https://www.reddit.com/r/orgmode/comments/41osyw/export_org_file_to_odt_with_bibtex_references/).
>
> Is this possible to implement with org-ref? As I understand if this is possible, only the citations would be exported into ODT not the reference list. This leads me to another question, is it possible to then export the reference list to ODT? I know that `org-ref-find-bibliography` can be used to find the bibliography but can this then be exported as simple text to ODT?
>
> Any thoughts on this would be most appreciated?


-- 
Jonathan

**Comment by jkitchin** [comment]
I think I am going to introduce a new cite link syntax that will make harvard style easy.  An alternative might be the new org-cite syntax.
