### ISSUE TITLE
Support for a separate notes file for each paper?

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#446]
I am new to `org-ref`. I store my papers on disk as follows. There is a separate folder for each paper (the name of the folder is like the bibtex key). Each folder for a single paper contains the files: paper.bib, paper.pdf, paper.org (for notes about the paper).

I realize that it is quite easy to make all the `.bib` files sources for `org-ref`. However, how (if at all) can I make it go to the correct notes file for the selected paper? Also, can I make going to the notes file a default action when clicking on the citation instead of going to the `.bib` file?

**Comment by jkitchin** [comment]
See https://github.com/jkitchin/org-ref/issues/443. I think it is what you want.
