### ISSUE TITLE
Scalability to thousands of .bib files   

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#449]
Suppose that one uses a separate `.bib` file for each paper. Does org-mode have to perform a linear scan of all the `.bib` files to follow a citation link? (in which case following a link may become noticeably slow when thousands of .bib files are used). Is there a mechanism in place to guarantee scalability for this usage case? Thank you for clarification.

P.S. Note that the function specified by `org-ref-cite-onclick-function` receives a path as its argument. This seems to imply that I cannot configure the way `org-ref` searches for the `.bib` file. (I could use such configuration to compute the path based on the entry key, which can be done very efficiently in the way my files are organized).

**Comment by jkitchin** [comment]
I wouldn't guarantee scalability, but I use it with thousands of entries regularly. There is a cache mechanism and asynchronous loading mechanism that help. Helm and ivy are pretty fast even with thousands of entries.

**Comment by mgoldenbe** [comment]
I realized that. My question was about thousands of distinct **files**.
Could this be a lot slower? Also, is there a way I can tell org-ref how to
find the entry based on key?

**Comment by mgoldenbe** [comment]
I realized that. My question was about thousands of **distinct files**. Could this be a lot slower? Also, is there a way to tell org-ref how to find the entry based on key?

**Comment by jkitchin** [comment]
That may not be a good idea. The cache is built from all the files but it checks if each file has been modified since the cache was built. I don't know how it would scale for 1000s of files, eg if if you have one entry per file.

**Comment by jkitchin** [comment]
Orgref already finds entries by key but it does that by searching files. This also might be slow for 1000s of files.

**Comment by mgoldenbe** [comment]
So, can I change this behavior? That is, if I know that the bib entry of
the key <key> is in the file <key>/paper.bib, then can I tell org-ref to
look there? If so, what would be the least intrusive way to do it?

**Comment by jkitchin** [comment]
You can probably redefine a few core functions for that. I am traveling and don't have easy access to them now. There is one like org-ref-get-key-file or something. I am not sure if there is more than one function like that to replace though.
