### ISSUE TITLE
File mode specification error

### ISSUE THREAD

**Issue by jmburgos** [jkitchin/org-ref#45]
Hi John,

I am having an issue with a few items in my bibliography. I insert a citation, using either the helm-bibtex or the org-ref-insert-cite-link functions, but when I click on the link (to open the pdf, for example) I get the following in the message buffer:

File mode specification error: (invalid-function dbus-ignore-errors)
(No changes need to be saved)
File mode specification error: (invalid-function dbus-ignore-errors)
progn: Wrong type argument: stringp, nil
(No changes need to be saved)
File mode specification error: (invalid-function dbus-ignore-errors)
!!! No entry found !!!

This happens only with some references. Here is the bibtex entry for one of them, in case it is of any use:

@Techreport{Cameron2011,
Title = {EUSeaMap - Preparatory Action for development and assessment of a European broad-scale seabed habitat map final report},
Author = {Cameron, A., and Askew, N.},
Year = {2011},
Note = {Available at http://jncc.gov.uk/euseamap},
File = {:Cameron2011.pdf:PDF},
Timestamp = {2013.09.09}
}

I am using both helm-bibtext and org-ref.  Let me know if you need any other information.

**Comment by jmburgos** [comment]
I just realized that all the problematic citations were of the type "Techreport".  If I change them to "Report", the problem is solved.

**Comment by jkitchin** [comment]
I wonder if this is related to the bibtex/biblatex dialect. It could be that Techreport is not a valid bibtex type, so it does not find anything, but it is a valid biblatex type, and if you  specify that as the dialect in the bibtex file it might work for you.
