### ISSUE TITLE
Misleading definition of org-ref-cite-onclick-function

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#450]
There are two things related to the variable `org-ref-cite-onclick-function` that I found very misleading and it took me a while to get over confusion:

1. In `ref-org-core.el`, the value of this variable is set to `nil`, which does not make sense. One has to know that it is also defined in `ref-org-helm-bibtex.el` to be `'org-ref-cite-click-helm`. Furthermore, in the former place it is defined with `defcustom`, while in the latter with `setq`.

2. In `org-ref-define-citation-link`, the `:follow` attribute of the new link is a lambda with the argument called `path`, which seems to imply that a path to the file is going to be passed to the function assigned to `org-ref-cite-onclick-function`. This is not the case and the argument should be renamed. The argument of `org-ref-cite-click-helm` is `_key`, which is better, but is also misleading, since a key does not seem to be passed to it; rather, the function uses org-ref-get-bibtex-key-under-cursor to get the key.

These things may seem trivial and inconsequential to the original author, but they are a major stumbling block for prospective new contributors. (Of course, this constructive criticism is not to diminish in any way the fact that I am very much impressed with org-ref overall!)

**Comment by jkitchin** [comment]
Thanks for the feedback. I added to the documentation regarding point 1. On point two, I changed the argument to _. The leading _ indicates that the argument is required to be there in the definition but ignored in the body.
