### ISSUE TITLE
invalid-function org-ref-link-set-parameters

### ISSUE THREAD

**Issue by inglada** [jkitchin/org-ref#451]
I am using org-ref from melpa (20170526.1519) with emacs built from source (GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2017-06-01)

emacs -Q

(package-initialize)
(require 'org-ref)

yields

`Debugger entered--Lisp error: (invalid-function org-ref-link-set-parameters)
  org-ref-link-set-parameters("gls" :follow or-follow-glossary :face org-ref-glossary-face :help-echo or-glossary-tooltip :export #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\gls{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"])
  byte-code("\301\302\303\304\305\306\307\310\311\312&	\210\301\313\303\304\305\306\307\310\311\314&	\210\301\315\303\304\305\306\307\310\311\316&	\210\301\317\303\304\305\306\307\310\311\320&	\210\301\321\303\304\305\306\307\310\311\322&	\210\301\323\303\304\305\306\307\310\311\324&	\210\301\325\303\304\305\306\307\310\311\326&	\210\327\306\330\331\332\333FDC\334#\207" [org-ref-glossary-color org-ref-link-set-parameters "gls" :follow or-follow-glossary :face org-ref-glossary-face :help-echo or-glossary-tooltip :export #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\gls{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"] "glspl" #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\glspl{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"] "Gls" #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\Gls{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"] "Glspl" #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\Glspl{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"] "glslink" #[771 "\211\300=\203\f^ @\301\302#\207\301\303\"\207" [latex format "\\glslink{%s}{%s}" "%s"] 7 "\n\n(fn PATH DESC FORMAT)"] "glssymbol" #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\glssymbol{%s}" "%s"] 6 "\n\n(fn PATH DESC FORMAT)"] "glsdesc" #[771 "\211\300=\203^ K^ @\301\302\"\207\301\303\"\207" [latex format "\\glsdesc{%s}" "%s"] 6 "\n\n(fn PATH _ FORMAT)"] custom-declare-face t :inherit org-link :foreground "Face for glossary links."] 10)
  require(org-ref-glossary)
  byte-code("\304\305!\210\304\306!\210\304\307!\210\304\310!\210\311\312\313\314\315\206^ @\316 !\"\"\210\311\312\313\317\315\206*^ @\316 !\"\"\210\304\320!\210\304\321!\210\304\322!\210\304\323!\210\304\324!\210\304\325!\210\304\326!\210\304\327!\210\330\331\332\333\334\335\336\323&\210\337\340\332\341\342\343\336\331&\210\337\344\332\345\342\346\336\331&\210\337\347\332\350\342\351\336\331&\210\337\352\332\353\342\354\336\331&\210\337\355\356\357\342\360\336\331&\210\337\302\361\362\342\360\336\331&\210\337\363\364\365\342\366\367\370\336\331&	\210\337\303\332\371\342\372\336\331&\210\337\373\332\374\342\372\336\331&\210\337\375\332\376\342\372\336\331&\210\337\377\332\201@^ @\342\372\336\331&\210\337\201A^ @\332\201B^ @\342\372\336\331&\210\337\201C^ @\332\201D^ @\342\372\336\331&\210\201E^ @	\201F^ @\n!^ K#\210\337\201G^ @\201H^ @\201I^ @\336\331%\210\337\201J^ @\201K^ @\201L^ @\342\360\336\331&\210\337\201M^ @\201N^ @\201O^ @\342\360\336\331&\210\337\201P^ @\201Q^ @\201R^ @\342\360\336\331&\210\337\201S^ @\201T^ @\201U^ @\342\372\336\331&\210\337\201V^ @\201W^ @\201X^ @\342\372\336\331&\210\337\201Y^ @\201Z^ @\201[^ @#\210\337\201\\^ @\201]^ @\201^^ @\342\372\336\331&\210\337\201_^ @\201`^ @\201a^ @\342\372\336\331&\210\337\201b^ @\201c^ @\201d^ @\342\372\336\331&\210\337\201e^ @\201f^ @\201g^ @\342\201h^ @\336\331&\210\337\201i^ @\201j^ @\201k^ @\342\201l^ @\336\331&\210\337\201m^ @\201n^ @\201o^ @\342\201p^ @\336\331&\210\337\201q^ @\201r^ @\201s^ @\342\201t^ @\336\331&\210\337\201u^ @\201v^ @\201w^ @\336\331\342\201x^ @&\210\337\201y^ @\201z^ @\201{^ @\342\201|^ @\336\331&\207" [load-file-name org-mode-map org-ref-insert-cite-key org-ref-insert-link-function require dash f s doi-utils add-to-list load-path expand-file-name "citeproc" file-name-directory buffer-file-name "citeproc/csl" org-ref-bibtex org-ref-utils org-ref-glossary org org-element ox parsebib reftex-cite custom-declare-group org-ref nil "Customization group for org-ref." :tag "Org Ref" :group custom-declare-variable org-ref-bibliography-notes "Filename where you will put all your notes about an entry in the default bibliography.\nUsed by backends that append all notes as entries in a single file." :type file org-ref-notes-directory "Directory where you will put all your notes about an entry in the default bibliography.\nUsed for backends that create a single file of notes per entry." directory org-ref-default-bibliography "List of bibtex files to search for.\nYou should use full-paths for each file." (repeat :tag "List of bibtex files" file) org-ref-pdf-directory "Directory where pdfs are stored by key.\nPut a trailing / in the name." (choice directory (repeat directory)) org-ref-default-citation-link "cite" "The default type of citation link to use." string "C-c ]" ...] 10)
  require(org-ref-core)
  byte-code("\301\302!\210\301!\210\303\304!\207" [org-ref-completion-library require org-ref-core provide org-ref] 2)
  require(org-ref)
  eval((require (quote org-ref)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
`

**Comment by jkitchin** [comment]
This probably means you are using org 8. It shoud work but there is probably a new link definition that doesn't check for the org version. Try installing a more recent org 9.

**Comment by inglada** [comment]
I am using the most recent version of org available as package : Org mode version 9.0.7 (9.0.7-elpa @ /home/inglada/.emacs.d/elpa/org-20170515/)

**Comment by jkitchin** [comment]
You probably need to require it before loading org-ref.

**Comment by inglada** [comment]
Same behaviour with

(package-initialize)
(require 'org)
(require 'org-ref)

Am I missing something?

Thank you.

**Comment by jkitchin** [comment]
I can't reproduce that. Here is a minimal init.el file that works for me:

```
(require 'package)

(setq package-archives
      '(("org" . "http://orgmode.org/elpa/")
	("gnu" . "http://elpa.gnu.org/packages/")
	("melpa" . "http://melpa.org/packages/")))

(package-initialize)
(package-refresh-contents)

(package-install 'org-ref)

(require 'org-ref)
```

**Comment by inglada** [comment]
Thanks. Here is an interesting thing. If I do

emacs --debug-init -Q -l test-init.el

the degugger is not triggered, but I get this in the *Messages* buffer:
For information about GNU Emacs and the GNU system, type C-h C-a.
Importing package-keyring.gpg...done
ad-handle-definition: ‘ido-completing-read’ got redefined
Contacting host: orgmode.org:80
Contacting host: elpa.gnu.org:80
Contacting host: melpa.org:80
Package refresh done
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
‘org-ref’ is already installed
byte-code: Invalid function: org-ref-link-set-parameters

**Comment by jkitchin** [comment]
That makes me think you have a ~/.emacs.d folder that has stuff in it that is messing you up. You should look in there and delete it if you don't use it.

**Comment by inglada** [comment]
You are right. With an empty .emacs.d directory there is no problem. I guess that my 15 year old configuration needs some clean up ;)

Thanks for this great package!

**Comment by cryoguy** [comment]
I had the same issue. I delete org-ref, git-clone and byte-recompile the new folder.  Error goes away.
