### ISSUE TITLE
org-ref-open-bibtex-pdf is not customizable

### ISSUE THREAD

**Issue by JonathanReeve** [jkitchin/org-ref#454]
org-ref-get-pdf-filename-function is customizable, and allows a user to change how org-ref opens a pdf from a citation link (e.g. by getting the file attribute from bibtex), but org-ref-open-bibtex-pdf is only hard-coded to look for a pdf in the form key.pdf. Not all of us have PDFs in that form, and instead use the `file={}` field in Bibtex. Thus, org-ref-open-bibtex-pdf should really call org-ref-get-pdf-filename-function instead of looking for a key.pdf.

**Comment by jkitchin** [comment]
I pushed this fix. Could you check it out and let me know if it works for you? Thanks.

**Comment by JonathanReeve** [comment]
I don't really know how to use emacs packages from git (I'm a novice at this), but the code looks good to me. Thanks!
