### ISSUE TITLE
How to change the format "org-ref-note-title-format"?

### ISSUE THREAD

**Issue by zhixing2017** [jkitchin/org-ref#455]
I changed the format of `org-ref-note-title-format` by setting the `customize-group`, but it only worked before I restart the Emacs.

"I only keeped the %t, and it insert: `title cite:bibtexkey`."

After restarted the Emacs, the setting did not work and it inserted `cite:nil`. I do not know the reason. 

If I set org-ref-note-title-format to "%t cite:%k", it inserted `title cite:bibtexkeycite:nil`, whick lead to the error.

emacs-version: 25.2; org-version:9.0.2

**Comment by yuchen-lea** [comment]
Maybe you also need to change the varaible `org-ref-create-notes-hook`. Its default value is
```
 ((lambda nil
   (org-narrow-to-subtree)
   (insert
    (format "cite:%s\n"
	    (org-entry-get
	     (point)
	     "Custom_ID")))))
```

Since you set your `org-ref-note-title-format` to "%t cite:%k", it cannot find the "Custom_ID" property, thus returns "nil".

**Comment by jkitchin** [comment]
To be more specific, if you get rid of Custom_ID, you should do this:

(setq org-ref-create-notes-hook nil)

**Comment by zhixing2017** [comment]
Thank you very much. @yuchen-lea  @jkitchin

**Comment by tdehaeze** [comment]
Hi,
First of all, thank you for this amazing software.
I'm also trying to customize "org-ref-note-title-format".

On my bibtex file I have a `file` field that contains the path to my .pdf file. I would like to add that to my note properties so that I can use it for Interleave or org-noter.
I'm able to do that with helm-bibtex using something like:
```
  (setq bibtex-completion-notes-template-one-file
        "\n* ${year} - ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :NOTER_DOCUMENT: ./pdfs_done/${=file=}\n  :END:\ncite:${=key=}\n\n")
```

But I could not do that for org-ref.
I don't think it is possible to do that using `org-ref-note-title-format`, maybe with `org-ref-create-notes-hook`?
I have created a function that returns the pdf file (I'm totally new to elisp, so I am sure it is badly written), maybe that could be useful?
```
  (defun my/get-pdf-filename (key)
    "Return the pdf filename indicated by file field.
       Falls back to `org-ref-get-pdf-filename' if file field does not exist.
       Argument KEY is the bibtex key."
    (let* ((results (org-ref-get-bibtex-key-and-file key))
           (bibfile (cdr results))
           entry)
      (with-temp-buffer
        (insert-file-contents bibfile)
        (bibtex-set-dialect (parsebib-find-bibtex-dialect) t)
        (bibtex-search-entry key nil 0)
        (setq entry (bibtex-parse-entry))
        (if (tdehaeze/bibtex-has-file-entry key) 
            (let ((e (org-ref-reftex-get-bib-field "file" entry)))
              (format (concat (file-name-as-directory org-ref-pdf-directory) "%s") e)
            )
          (org-ref-get-pdf-filename key))
        )))
```

**Comment by jkitchin** [comment]
You can do this with org-ref-create-notes-hook. There is an example function in the definition. You need to add another function to it that inserts the property that you want, with the result from your filename function. Assuming your function always returns a string, it might be something like

```

(lambda ()
  (org-entry-put
   nil
   "NOTER_DOCUMENT"
   (my/get-pdf-filename (org-entry-get
			 (point) "Custom_ID"))))
```

**Comment by tdehaeze** [comment]
Thanks, it's working fine

**Comment by atfornes** [comment]
A simpler version of `my/get-pdf-filename`,  using `bibtex-completion-find-pdf` is:

```emacsLisp
;; set the bibtex field containing the pdf path
(setq bibtex-completion-pdf-field "file")

(defun my/get-pdf-filename (key)
  (car (bibtex-completion-find-pdf key))
  )
```

then, you can use it as explained in  https://github.com/jkitchin/org-ref/issues/455#issuecomment-414325765
