### ISSUE TITLE
Export does not work with citations from default bibliography

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#456]
I specified the default bibliography files (in my case, there are many of them, since I use a separate `.bib` file for each paper) in  `org-ref-default-bibliography`. This works fine while in `Emacs`. However, exporting to `latex/pdf` produces a warning of undefined citations.

**Comment by jkitchin** [comment]
You have to specify a bibliography and bibliography style link for latex export. It isn't possible to automatically insert these without creating a custom exporter, which isn't something I want for org-ref.

**Comment by mgoldenbe** [comment]
But then what is the motivation for having the variable `org-ref-default-bibliography`?

**Comment by jkitchin** [comment]
The vast majority of my org files are never exported to latex. They are research notes, or other things where I want the convenience of being able to easily cite things. 

There is some overlap between org-ref-default-bibliography and bibtex-completion-bibliography. The second of those is for helm-bibtex. The first one predates the helm-bibtex variable, and is also used in the other backends like ivy.

**Comment by mgoldenbe** [comment]
"It isn't possible to automatically insert these without creating a custom exporter"

I don't think you need a custom exporter. All you need is add (i.e. insert) the files from `org-ref-default-bibliography` into `bibliography` before the export begins and undo this change when it finishes. Of course, this would also require handling the case when the exporter is stopped in the middle, in which case you would still want to undo the change.

**Comment by jkitchin** [comment]
There are two things you have to do on a copy of the org-file before it is exported, insert a bibliographystyle and bibliography link/latex. The only place that makes sense to do this is at the end of the document, but that might not always be right either.

In any case, you have to define at least a new export command, and either run that, or add an option to the latex exporter with a new quick key, e.g. C-c C-e l r or something.

If you want to submit a pull request for this feature, I would be willing to consider it. it would have to work for bibtex and biblatex though, and they are pretty different beasts.
