### ISSUE TITLE
Unable to get latex export to work with citations and bibliography.

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#457]
I am trying to export the file with the following simple contents:

```
cite:VemulaMO2016c-Path-Plann

bibliographystyle:unsrt
bibliography:/home/meir/LiteRef/papers/VemulaMO2016c-Path-Plann/paper.bib
```
I get a warning about the citation not being found. I verified that `org-ref` finds both the bibliography file the citation key. To understand what is happening, I looked at the produced latex file. To my surprise, it has the following line:

` \bibliography{../../../../../LiteRef/papers/VemulaMO2016c-Path-Plann/paper}`

Why is it trying to go five levels up? No surprise it's not finding any bibliography file there...

**Comment by jkitchin** [comment]
In the export the bibfiles are converted to relative file names which are relative to the variable default-directory. My guess is your org-file is in a directory 5 levels deep relative to home, or the value of default-directory is not reflecting the actual working directory your file is in.

**Comment by mgoldenbe** [comment]
Actually, it is five levels deep from root. I still was not able to fix the problem. I tried using a relative path:
`bibliography:../papers/VemulaMO2016c-Path-Plann/paper.bib`

Again, `org-ref` finds the bibliography file just fine, but the same warning results. The contents of the `.tex` file are now correct:
`\bibliography{../papers/VemulaMO2016c-Path-Plann/paper}`, but to no avail. I would like to see the actual output of `bibtex`, but do not know how to do that. I don't even know whether `bibtex` was run...

**Comment by jkitchin** [comment]
You may need to setup this:

#+BEGIN_SRC emacs-lisp
(setq org-latex-pdf-process
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	"bibtex %b"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
#+END_SRC

I have also had success with this setup:

#+BEGIN_SRC emacs-lisp
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
#+END_SRC

**Comment by mgoldenbe** [comment]
This worked. Thanks!
