### ISSUE TITLE
How to generate a parenthetical output?

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#458]
How to generate a parenthetical format as the following with elsarticle:
(Wettig & Brown, 1996), NOT Wettig & Brown (1996).

Thanks again for the wonderful work.

**Comment by jkitchin** [comment]
https://www.elsevier.com/__data/assets/pdf_file/0008/56843/elsdoc-1.pdf suggests you should use citep as the link type, e.g. citep:some-key.
