### ISSUE TITLE
can not get pdfs automatically on sciencedirect

### ISSUE THREAD

**Issue by zhixing2017** [jkitchin/org-ref#459]
Thanks for your work. 

And now I have got a problem.

I cannot get pdfs automatically from **ScienceDirect**, such as **10.1016/j.bios.2015.07.016**.

Can you help me resolve it?

**Comment by jkitchin** [comment]
Getting pdfs are tricky. Can you got to that website and download the pdf from it? If you can't there is nothing org-ref can do for you, as you don't have permission to get that pdf. If you can, then probably the url is not recognized in doi-utils.el. you have to create a function that tells org-ref how to get the pdf in that case, and add the function to doi-utils-pdf-url-functions. You can find lots of examples of these functions in doi-utils.el.

**Comment by zhixing2017** [comment]
Yes, I have the permission to **ScienceDirect**. 
And I can download pdfs before. I think this phenomena is duo to the revision of **ScienceDirect**. The old rule is not appropriate now.
I am not good at the lisp lang. Can you test the formor DOI and help me solve it?

**Comment by jkitchin** [comment]
I had a look at this, and it doesn't look that easy to resolve. Another reason to dislike Elsevier, they make it unusually difficult to get the pdf.

**Comment by ary15** [comment]
I had the same or similar problem: trying to download the pdf from elsevier/science direct just takes me to a linkhub error screen. I then have to find the paper URL, navigate to it and download manually. I don't have a complete solution, but a small improvement, which al least opens the pdf in my browser, which is a small improvement. 

This involves changing the functions:
- linkinghub-elsevier-pdf-url  (change http to https & include a doi-utils-get-science-direct-pdf-url in the redirect)
- doi-utils-get-science-direct-pdf-url (change the re-search-forward, as science-direct seems to have changed the text around the pdf_url)

I have implemented this as advice to the function on my own system, but could try and set it up here too.

**Comment by zhixing2017** [comment]
Has this problem been solved? 

An same error occurred when trying to get pdf from Science Direct.

**Comment by zhixing2017** [comment]
I think you can try this one: 10.1016/j.molimm.2018.03.030

I think if it is hard to get the pdf from Science Direct, opening the doi may be a good idea. Every time I cannot get the pdf, I click the doi to open the correct page to download it manually.

And BTW, **recently** I cannot get the pdf from ACS website, like the Analytical Chemistry, such as this doi: 10.1021/acs.analchem.7b05005.
