### ISSUE TITLE
Citation won't export to LaTeX when placed inside LaTeX code

### ISSUE THREAD

**Issue by kewnapse** [jkitchin/org-ref#46]
If I write the following in org-mode,

    \begin{definition}
    [cite:dawid1982well]
    \end{definition}

I get cite:dawid1982well in my LaTeX/pdf export, instead of a real citation...
Is there a way to make this work ?

**Comment by jkitchin** [comment]
How about:


#+begin_definition
[cite:dawid1982well]
#+end_definition

**Comment by kewnapse** [comment]
Works great. Thanks!
