### ISSUE TITLE
check whether journal is in org-ref-bibtex-journal-abbreviations

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#460]
I've written a function and added it to `org-ref-clean-bibtex-entry-hook` that checks whether the journal is in `org-ref-bibtex-journal-abbreviations` and issues a message if it isn't. This is useful for me because I'm not in the same field as you and so most of the journals I use aren't in there by default.

If you're interested, I can submit a PR to add this to org-ref. If not, feel free to close this issue.

**Comment by jkitchin** [comment]
That could be useful. I would be interested to see it. Does it just warn you or prompt you to add an entry that is saved persistently?
