### ISSUE TITLE
org-ref-cite gets confused by directory with same name as bibtex key

### ISSUE THREAD

**Issue by drghirlanda** [jkitchin/org-ref#462]
Hi,
I noticed that if a directory (or file?) named X exists in the same directory as the .org file, then trying to insert cite:X with C-c ] actually inserts the file's full path, like cite:/home/user/.../X. I am using helm search and I just updated org-ref and org to the latest melpa versions.

Thanks for org-ref, it's great!

**Comment by jkitchin** [comment]
This sounds strange. I can not reproduce it with helm-bibtex. Can you give a little more information about your org-ref setup? Maybe paste the results of M-x org-ref-debug here? and the org-ref backend you have set?

**Comment by drghirlanda** [comment]
Hi John,

Thanks for your time. Running M-x org-ref-debug returns "Wrong type argument: stringp, 126" which I guess points to something messed up with my configuration. I have deleted all old org and orf-ref files I could find, even the system org folder, and restarted Emacs, but both errors persist. I am using helm-bibtex. I attach the relevant bits of my init.el, but since it's really a fringe case and might be particular to just me, don't waste time on this if it's not immediately obvious.

Best,
S
[init-org.txt](https://github.com/jkitchin/org-ref/files/1089074/init-org.txt)

**Comment by jkitchin** [comment]
I can confirm it with your setup! I am not totally sure, but that seems to be coming from helm-bibtex.

Out of curiosity why do you have a file named X that is the same as a key in your bibliography?

**Comment by drghirlanda** [comment]
Good to know I am not crazy :)

To answer your question, I am writing a review paper and there is some data analysis for each reviewed paper. So for the BibTeX entry Smith2010 I have a directory Smith2010 with the relevant data analysis.

**Comment by jkitchin** [comment]
An easy fix is probably to put them all in a subdirectory.

**Comment by drghirlanda** [comment]
Yes, that's what I ended up doing, it's also neater. I have a couple of questions regarding configuring org-ref, should I open "issues" or email you directly?

**Comment by jkitchin** [comment]
I would go with issues. It is easier to share solutions that way.
