### ISSUE TITLE
configuring the ref command

### ISSUE THREAD

**Issue by drghirlanda** [jkitchin/org-ref#463]
Hi,
I have two small configuration questions:

1. I would like to use cleveref for LaTeX export, is there a way of changing \ref to \cref by configuring an org-ref variable?

2. My lisp is very poor, how do I bind the org-ref insert ref and insert label commands to keys?

**Comment by jkitchin** [comment]
1. It doesn't currently look possible to change that by a variable. You can however change how a ref link is exported. For latex only, and assuming all refs are crefs:

```
(org-link-set-parameters "ref" :export
			 (lambda (label desc format)
			   (format "\\cref{%s}" label)))

```

This seems like something that should be customizable, but it will take some work to do. So leave this issue open :)

2. C-u C-c ] should insert a ref link
C-u C-u C-c ] should insert a label link.

You can define another key, eg to use f7 and f8:

#+BEGIN_SRC emacs-lisp
(define-key org-mode-map (kbd "<f7>") org-ref-insert-ref-function)
(define-key org-mode-map (kbd "<f8>") org-ref-insert-label-function)
#+END_SRC

**Comment by drghirlanda** [comment]
They all work, thanks a lot!

**Comment by jkitchin** [comment]
I think it is possible to customize this now. The variable org-ref-default-ref-type now controls the default type, and I added cref and Cref links as ref types.

**Comment by drghirlanda** [comment]
That's great thanks! I will try once I get the chance to update org-ref

**Comment by drghirlanda** [comment]
I can confirm that they both work: cref and Cref are at the bottom of the ref type list, and I can (setq org-ref-default-type "cref") to get cref: links without going through the list. Thank you very, very much!

**Comment by stefan2904** [comment]
In https://github.com/jkitchin/org-ref/issues/463#issuecomment-309864135:

>  For latex only

stupid question, how does one restrict this override to latex exports? since otherwise this destroys exports to other formats ...

thanks!

**Comment by jkitchin** [comment]
you could try something like:

(org-link-set-parameters "ref" :export
			 (lambda (label desc format)
			   (cond ((eq 'latex format)
				  (format "\\cref{%s}" label))
				 (t
				  (some-other-export-function)))))
