### ISSUE TITLE
Customization/Broken links in org-ref manual

### ISSUE THREAD

**Issue by mhaffner** [jkitchin/org-ref#464]
I want to customize citations so that I could have all of the following citation styles in one document:

Smith et al. (2017) said the quick brown fox jumped.
The quick brown fox jumped (Smith et al. 2017). 
Smith, Johnson, and Stephens (2017) showed that the quick brown fox jumped.

The manual mentions that citations can be customized, but both links to [customization](https://github.com/jkitchin/org-ref/blob/master/*Customizing%20org-ref) are broken. This is, of course, possible with `natbib` as pointed out in the manual.

**Comment by jkitchin** [comment]
Those links only work in the org-file. I don't know if they can be made to work in the github page if that is what you mean.

What you want just requires the right cite link type and the right bibliography style.

**Comment by mhaffner** [comment]
Thanks for the quick response. I see what you mean. After cloning the repo, I see all of the cite types in a `#+RESULTS` block under the `org-ref-cite-types` command.  This doesn't appear online though, so based upon this (and the fact that I misunderstood the link behavior), am I right in thinking that the manual is intended to be read in Emacs but not online?

**Comment by jkitchin** [comment]
yes, I recommend you read it with M-x org-ref-help

github does not do a great job rendering org-mode in my opinion; it does the easy stuff but not the hard stuff.
