### ISSUE TITLE
bibfilename error

### ISSUE THREAD

**Issue by sjLambda** [jkitchin/org-ref#465]
When I run org-ref-helm-insert-cite-link  with the usual C-c ], I get this error instead of a helm window:

cond: bibfilename stylename optional-options does not seem to exist

Did I miss some recent changes to the bibliography line? It is currently:

#+BIBLIOGRAPHY: references plain option:-d

and can confirm references.bib there and manually entering cite:entry works.

I'm currently on:
org-ref: Version 1.1.1 (git-commit 6edc2d70874fd8f7da3fe1035f1148a890682962)

**Comment by jkitchin** [comment]
That isn't an org-ref style bibliography link, but it is confusing org-ref because it kind of looks like one. You should use something like:

bibliography:references.bib

and use a bibliographystyle:plain

Is that syntax something you use for pandoc or something?

**Comment by jkitchin** [comment]
I have pushed a fix that should make this work. It is limited in the following way: it splits the text after the : by a space, and assumes the bibfile is the first word with no extension. It ignores the options after that.

**Comment by sjLambda** [comment]
Yes, I was testing pandoc with advice from [here](http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=contrib/lisp/ox-bibtex.el;hb=HEAD). After I removed the line:
 
#+BIBLIOGRAPHY: references plain option:-d

Everything parses now. Good catch.

bibliographystyle:unsrt
bibliography:references.bib

I forgot that I already had the above two org-ref style lines at the end of the same org document. So no more tweaks were needed.

The real problem I was tackling was getting multilingual bibtex and org files. (To have latin and greek characters in the same file). The usual AMS fonts for math symbols wasn't appropriate for large blocks of greek text. I had to install babel-greek in texlive and enable it through latex_header in the org file. 

Now I can continue to use org-ref with both greek text and latin text blocks in an org file.  Separating the text blocks also forces the PDF engine to honor different font and character sets while printing.
