### ISSUE TITLE
org-ref-default-bibliography not recognized?

### ISSUE THREAD

**Issue by ecbrown** [jkitchin/org-ref#47]
I have `(setq org-ref-default-bibliography "/home/ecbrown/bibliography/references.bib")`, as well as the other variables including reftex.   I have verified with `C-h v`.

But it seems that I must always specify the file in my current org file:

`bibliography:/home/ecbrown/bibliography/references.bib`

before the subsequent `cite:key` statements will work, i.e. getting the list of six or so tasks that can be done with a PDF.

Otherwise, I get `!!! No entry found !!!`

Am I missing something?

Emacs 25.0 devel (and Emacs 24.5) GNU/Linux
org-ref: e0f7e2bad93a535898fb99a12dfbd4a54fb2f462

**Comment by ecbrown** [comment]
Oh, I think this must be a list: `(setq org-ref-default-bibliography '("/home/ecbrown/bibliography/references.bib"))`

I think I had found some old instructions.

**Comment by jkitchin** [comment]
that is right, it does need to be a list.
