### ISSUE TITLE
Is it possible to add customize function in Ivy completion mode?

### ISSUE THREAD

**Issue by fuxialexander** [jkitchin/org-ref#470]
In the manual there are instruction on doing this in Helm mode, however for Ivy completion mode seems there are no "user-candicate-function" counterpart. `ivy-bibtex` do provide some customization, while I'm not quite sure how to do this with org-ref.

**Comment by jkitchin** [comment]
Try something like this:


```
(setf (cdr (assoc "p" org-ref-ivy-cite-actions))
 '((lambda (entry) (message "you picked %s" entry)) "My open pdf"))
```

where you replace the lambda func with your own function.

**Comment by fuxialexander** [comment]
Thank you for your reply!

Tried but didn't make it work. But I'm worried that it could be a problem with my setup: as shown below, the format of Ivy's display for org-ref seems a bit weird. ivy-bibtex works well for me though.

org-ref-ivy:
<img width="1084" alt="screen shot 2017-07-13 at 8 07 33 pm" src="https://user-images.githubusercontent.com/8258908/28165581-f8366c4e-6806-11e7-9e29-378140820878.png">

ivy-bibtex:
<img width="1084" alt="screen shot 2017-07-13 at 8 09 52 pm" src="https://user-images.githubusercontent.com/8258908/28165635-3df588c8-6807-11e7-8f8b-fe68e62c6d65.png">

**Comment by fuxialexander** [comment]
Ah, I actually got it work by borrowing my custom function for ivy-bibtex:

```emacs-lisp
    (defun bibtex-completion-open-uri (keys)
      "Open the associated URL or DOI in a browser."
      (dolist (key keys)
        (let* ((entry (bibtex-completion-get-entry key))
               (uri (bibtex-completion-get-value "uri" entry))
               (uri (s-replace "\\url{" "" uri))
               (uri (s-replace "}" "" uri))
               )
          (start-process "open papers" nil "/usr/bin/open" uri)
          )))
    (ivy-bibtex-ivify-action bibtex-completion-open-uri ivy-bibtex-open-papers)
    (setf (cdr (assoc "p" org-ref-ivy-cite-actions)) '(ivy-bibtex-open-papers "Open in Papers"))
```

This is for open entry in Papers 3, using the bibtex file exported from Papers 3 which have a somehow non-standard format...

Besides that, I wonder why my org-ref-ivy entry is multi-line and seems not formatted... Is that the current behavior?

**Comment by jkitchin** [comment]
The ivy interface in org-ref does not use ivy-bibtex. It uses its own ivy backend for it that may have been written before ivy-bibtex was around. I haven't looked into what it would take to get an ivy-bibtex backend for org-ref, but it probably is not difficult.

**Comment by fuxialexander** [comment]
Thank you for your explanation! I'll close this issue for now (as the issue in the title is solved). Looking forward to your ivy-bibtex integration ;-)
