### ISSUE TITLE
org-ref-title-case-article downcases parens

### ISSUE THREAD

**Issue by jabranham** [jkitchin/org-ref#471]
`org-ref-title-case-article` downcases all words in or near parens, when it maybe shouldn't. 

`title = {(Mis)Perceptions},`

becomes 

`title = {(mis)perceptions},`

And similarly, `title={(How) Does this Work},` becomes `title = {(how) Does this Work},`

**Comment by jkitchin** [comment]
I think I pushed a small fix that partially addresses this. The general case is difficult since this works by splitting on spaces. So, `(How does it) work` will turn into `(How Does it) Work`. What do you think?

**Comment by jabranham** [comment]
Thanks. Not changing words inside parens seems like a decent solution for now. 

Another solution would be to apply the function separately to the word(s) inside the parens, but I'm not sure if that would fix the issue.

**Comment by jkitchin** [comment]
That is a tricky solution. You would have to test for words inside of parens, or parse the title more intelligently than splitting on words.
