### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Saeedir2013** [jkitchin/org-ref#475]
I installed org-ref through Melpa. Org-ref can not connect to required websites to get pdfs and other information. I use Emacs version 24.5.1 on Mac. I get the following message for example:

Opening TLS connection to `doi.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 doi.org'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 doi.org --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect doi.org:443 -no_ssl2 -ign_eof'...failed
Opening TLS connection to `doi.org'...failed
url-http: Could not create connection to doi.org:443

Update: I updated my Emacs from 24.5.1 to 25.2.1, but now Emacs exits when I execute org-ref commands.

**Comment by jkitchin** [comment]
I don't think this is an org-ref problem, but one in emacs where it cannot connect to https sites. This suggests gnutls or something equivalent is not installed correctly. I install emacs from homebrew with these directions: https://github.com/jkitchin/scimax#mac-users
