### ISSUE TITLE
[question] citation of item from local library

### ISSUE THREAD

**Issue by seblemaguer** [jkitchin/org-ref#476]
Hello,

I have a tiny question about "local library". 

Here is my configuration for org-ref:

```lisp

  (use-package org-ref
    :after org
    :init
    (setq org-ref-completion-library 'org-ref-ivy-cite
          org-ref-notes-directory "~/Dropbox/org/work/biblio"
          org-ref-bibliography-notes "~/Dropbox/org/work/biblio/index.org"
          org-ref-default-bibliography '("~/Dropbox/org/work/biblio/index.bib")
          org-ref-pdf-directory "~/Dropbox/org/work/biblio/lib/"))

    :config
    (key-chord-define-global "uu" 'org-ref-cite-hydra/body)
    ;; variables that control bibtex key format for auto-generation
    ;; I want firstauthor-year-title-words
    ;; this usually makes a legitimate filename to store pdfs under.
    (setq bibtex-autokey-year-length 4
          bibtex-autokey-name-year-separator "-"
          bibtex-autokey-year-title-separator "-"
          bibtex-autokey-titleword-separator "-"
          bibtex-autokey-titlewords 2
          bibtex-autokey-titlewords-stretch 1
          bibtex-autokey-titleword-length 5)

```

However, for one presentation I want to use my local bibliography stored in "mybib.bib". Therefore, I added that at the **end** of my org-source

```org
* References
** References
[[bibliographystyle:plain]]
[[bibliography:mybib.bib]]
```
The problem is that when I want to cite one item I have this message:

```
Schoenle1987 not found in /home/slemaguer/Dropbox/org/work/biblio/index.bib
org-ref-get-bibtex-entry-citation: Wrong type argument: stringp, nil
```

From which I conclude it does not use the file mybib.bib.

What do I miss?

Thanks

**Comment by jkitchin** [comment]
What does M-x org-ref tell you about the org-file. It should indicate which bib file is being used.

Have you verified that mybib.bib is syntactically correct?

**Comment by seblemaguer** [comment]
- org-ref indicates "/home/slemaguer/Dropbox/org/work/biblio/index.bib" as library used and that all my citations are bad (which I think it's normal as they are not in the index.bib)
- I double checked it seems correct. bibtex is processing it without errors or warnings

I can try to debug it but I just don't see where to start

**Comment by seblemaguer** [comment]
I debugged a little bit and it seems that when I change the regexp in  org-ref-find-bibliography from

```lisp
"^\\<\\(bibliography\\|addbibresource\\):\\([^\]\|\n]+\\)\\>"
```

to

```lisp
"^[\[]\\{2\\}\\(bibliography\\|addbibresource\\):\\([^\]\|\n]+\\)"
```
it works. I think that it is the beginning [[ which causes the failure.

**Comment by jkitchin** [comment]
That is it indeed. I just pushed a similar fix that makes the brackets optional.
