### ISSUE TITLE
How to copy "title & bibtexkey" together at the point?

### ISSUE THREAD

**Issue by zhixing2017** [jkitchin/org-ref#479]
Hello,

I want to use some hotkey, such as `, h n`, to copy `{title} cite"{bibtexkey}` in order to take notes for the article at the point easily.  

I do not have an idea how lisp works. Can you help me write a func to realize it?

Thanks.

**Comment by jkitchin** [comment]
This looks roughly like what you want:

```
(defun copy-note ()
  (interactive)
  (save-excursion
    (bibtex-beginning-of-entry)
    (kill-new
     (org-ref-reftex-format-citation (bibtex-parse-entry t) "%t cite:%k"))))


```

You are on your own for the hotkey :)

**Comment by zhixing2017** [comment]
It works. Thank you.
