### ISSUE TITLE
Some helm options don't seem to work

### ISSUE THREAD

**Issue by prtkm** [jkitchin/org-ref#48]
Hi John,

I am trying to use C-c ] to open up my bibtex library in helm, use the incremental search to narrow down to all articles written by a particular author, then do C-z to open the actions and I noticed some of the options give me this error,

f-absolute?: Wrong type argument: stringp, nil

For example, two common operations [f2] Open pdf and [f8] open notes give me the error while [f3] open url and [f9] show entry work as expected. Do you know what can be going wrong?

**Comment by jkitchin** [comment]
strange these work for me. I wonder if it is an issue with f.el, was that updated recently?

**Comment by prtkm** [comment]
f.el was last changed 2 months ago https://github.com/rejeep/f.el, but updating it does not fix the problem for me. 

I also tried doing a fresh build of jmax from scratch to test if that gets rid of the error, but the build breaks now, probably due to updates in some packages.

Loading /Users/prateekm/jmax/jmax-org.el (source)...
defconst: Symbol's value as variable is void: org-babel-safe-header-args

**Comment by jkitchin** [comment]
I could reproduce this, and it seems to be a common issue on the
org-mode mailing list.

I ran M-x byte-compile-file ob-R.el and it seemed to go away when I
restarted.

you have to navigate to where ob-R.el is in the elpa directory.


Prateek Mehta writes:

> f.el was last changed 2 months ago https://github.com/rejeep/f.el, but updating it does not fix the problem for me.
>
> I also tried doing a fresh build of jmax from scratch to test if that gets rid of the error, but the build breaks now, probably due to updates in some packages.
>
> Loading /Users/prateekm/jmax/jmax-org.el (source)...
> defconst: Symbol's value as variable is void: org-babel-safe-header-args
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/48#issuecomment-128144202

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Thanks, one of the problem seems to be solved now, with a fresh load of jmax working. 

The other issue is due to a conflict with helm-bibtex and org-ref. If I do C-c ], C-z on a particular entry and press [f2] to open a pdf, it says no PDF(s) found. If I try to open notes it gives me an f-absolute?: Wrong type argument: stringp, nil. This is because helm-bibtex uses different variables than org-ref to store pdfs, and handles notes by making a separate file for each entry. 

If I put (setq helm-bibtex-library-path '("~/Dropbox/bibliography/bibtex-pdfs/")) in an init file, then the pdfs open as desired, though in DocView. You have to further customize helm-bibtex to use org-open-pdf to open the pdf file instead of find-file to get org-ref like behavior.

(defcustom helm-bibtex-pdf-open-function 'org-open-file
  "The function used for opening PDF files.  This can be an
arbitrary function that takes one argument: the path to the PDF
file.  The default is `find-file' which opens the PDF in
Emacs (either with docview or, if installed, the much superior
pdf-tools.  When set to `helm-open-file-with-default-tool', the
systems default viewer for PDFs is used."
  :group 'helm-bibtex
  :type 'function)

Probably something similar has to be done for the [f8] Edit notes option to look up the bibtex-key and search for it in the org-ref notes file.

It is probably redudant and a little confusing that we need to set two variables for the notes and the pdfs. I prefer to use the helm-bibtex options while reading articles, because it allows me to search my library for a particular author or title, and then open the pdf and notes instead of actually inserting the entry in the org file and then clicking on it, then removing it later. I think this approach is more convenient for reading than searching my notes file using C-s.

**Comment by jkitchin** [comment]
True enough, I have these in my init files:

;; *** helm-bibtex

(setq helm-bibtex-bibliography "~/Dropbox/bibliography/references.bib")
(setq helm-bibtex-library-path "~/Dropbox/bibliography/bibtex-pdfs")

(setq helm-bibtex-pdf-open-function
  (lambda (fpath)
    (start-process "open" "*open*" "open" fpath)))

(setq helm-bibtex-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")

i added this as documentation to the README.
