### ISSUE TITLE
Creating citation notes using a unique system 

### ISSUE THREAD

**Issue by martinleduc** [jkitchin/org-ref#480]
Hello,

According to org-ref documentation, we can define the citation note file as:

- org-ref-bibliography-notes -> notes.org

or as :
- bibtex-completion-notes-path -> helm-bibtex-notes

I chose to use the first system when I began with org-ref some times ago. 

These two note systems appear to have different note title formats and can be accessed from different menus. I also realized that the second system might be more convenient, as I can add a note from two different menus:

- from an entry within a bibtex file (using "n" in the hydra menu)
- from helm bibtex (when adding a new reference within an org file and hence pressing "F9")

while the first note system (note.org) can be accessed only (to my very limited knowledge) when selecting the 3rd choice in the helm menu popping after pressing enter on a citation link from within an org file.

So my question: is it possible to add/create a note using the first system (note.org) from other menus, that is 1) from within a bibtex file and 2) from the helm bibtex citing command ? 

Thanks for helping, I'm quite confused with the helm/hydra stuff...

**Comment by jkitchin** [comment]
I think I understand what you are asking: how do you add new functions to the helm-bibtex command and the bibtex hydra?

For helm-bibtex, you should be able to add functions to  org-ref-bibtex-completion-actions, e.g. something like this:

(add-to-list ' org-ref-bibtex-completion-actions '("some string" . some-function)) 

and they should appear in the helm command then.

I don't see a way to change the hydra though. I can see the hydra is hard coded to use helm-bibtex notes. I will look into seeing if it is easy to change that to use the user option.

**Comment by jkitchin** [comment]
It doesnt look that easy to fix the hydra right now. I will be traveling for the rest of August, so I won't get a chance to work on it until September most likely. I think we will have to either redesign the notes customization or add more customization. Alternatively, a helm command might also be ok for it.

**Comment by martinleduc** [comment]
I agree there is a potential to better organize all of these menus and that it would require a lot of work. To solve my own issue, I don't think we would need to change the hydra menu but maybe to add a new function to the helm. 

Just for clarity, here are the three menus I was asking about. If I understand correctly, these are accessible from different situations:

A) when calling function org-ref-helm-insert-cite-link to insert an org-ref link in an org file, then pressing Tab to open the following menu (defined in org-ref-helm-bibtex.el) :

[f1] Insert citation
[f2] PDF, URL or DOI
[f3] Open URL or DOI in browser
[f4] Insert reference
[f5] Insert BibTeX key
[f6] Insert BibTeX entry
[f7] Insert formatted citation(s)
[f8] Attach PDF to email
[f9] Edit notes
[f10] Show entry
[f11] Add keywords to entries
[f12] Copy entry to clipboard
[???] Add PDF to library

Where [f9] calls helm-bibtex-edit-notes, which leads to the second note system as described in my first post, the one I'm not using.


B) Once a citation is inserted, just click on it or press Enter to get the following menu (defined in org-ref-helm-cite.el): 

 0. Open bibtex entry
 1. Quit
 2. Open pdf
 3. Add/Open notes
 4. Open in browser
 5. WOS
 6. Related articles in WOS
 7. Citing articles in WOS
 8. Google Scholar
 9. Pubmed
10. Crossref
11. Insert new citation
12. Delete key at point
13. Replace key at point
14. Delete citation at point
15. Update pre/post text
16. Sort keys by year
17. Copy formatted citation to clipboard
18. Copy key to clipboard
19. Copy bibtex entry to file
20. Email bibtex entry and pdf

Where the 3rd entry calls org-ref-open-notes-at-point, the first note system described above, and the one I prefer to use.


C) When in a bibtex file, pointing to an entry and calling org-ref-bibtex-hydra/body to open the hard-coded Hydra menu for bibtex entries:

`_p_: Open pdf     _y_: Copy key               _N_: New entry            _w_: WOS
_b_: Open url     _f_: Copy formatted entry   _o_: Copy entry           _c_: WOS citing
_r_: Refile entry _k_: Add keywords           _d_: delete entry         _a_: WOS related
_e_: Email entry  _K_: Edit keywords          _L_: clean entry          _P_: Pubmed
_U_: Update entry _N_: New entry              _R_: Crossref             _g_: Google Scholar
_s_: Sort entry   _a_: Remove nonascii        _h_: helm-bibtex          _q_: quit
_u_: Update field _F_: file funcs             _A_: Assoc pdf with entry
_n_: Open notes                               _T_: Title case
                                              _S_: Sentence case`
(sorry if it doesn't appear correctly)


Where `_n_` calls bibtex-completion-edit-notes, corresponding to the second note system described above (the one I'm not using).


So the simplest solution to my own issue would be to be able to call:

1. org-ref-open-notes-at-point when pointing at an entry in a bibtex file. Currently if I try it I get the error "Wrong type argument: stringp, nil". In other words, I would like to call menu B (or only the 3rd entry in it) from situation C.

2. org-ref-open-notes-at-point when inserting a link and press Tab (situation A). This could be a pleasant option in case you want to add a note to a specific paper on the fly but don't necessarily want to insert the related citation beforehand. In other words, being able to use org-ref-helm-insert-cite-link, typing to select a reference, pressing Tab on it and then having a new entry in the helm action menu to add a note with org-ref-open-notes-at-point rather than with [f9] which actually calls helm-bibtex-edit-notes.


Thanks !

**Comment by martinleduc** [comment]
Actually if I specify the following inside the function org-ref-bibtex-completion-actions (from org-ref-helm-bibtex.el):

+    ("Edit helm notes" . helm-bibtex-edit-notes)
+    ("Edit org-ref notes" . org-ref-open-notes-at-point)    

It does the trick for taking a note on the fly (when citing) by allowing the user to choose which note system he prefers.

**Comment by AtomicNess123** [comment]
Hi, did you manage to solve this by adding the relevant piece of code in the config init file? I encountered the same issue of wanting to unify my notes (I use the org-ref note-taking method and would like to access it always).
