### ISSUE TITLE
Links to custom entry types do not work

### ISSUE THREAD

**Issue by BenFeld** [jkitchin/org-ref#482]
I have a .bib-file with custom entry types supported by the OSCOLA style. The style, for example, provides entries for legal cases:

> @jurisdiction{GreenhalghvArderneCinemasLtd1951,
> 	Date = {1951},
> 	Journaltitle = {Ch},
> 	Options = {year-essential=true},
> 	Pages = {286},
> 	Pagination = {[]},
> 	Shorttitle = {Greenhalgh v Arderne},
> 	Title = {Greenhalgh v Arderne Cinemas Ltd}}
> 

In my .org-file I cite the case above for instance like this:

> This was also held in cite:GreenhalghvArderneCinemasLtd1951

Org-ref identifies this as a link, but when moving the cursor to this link and pressing RET does
not open the helm-menu and triggers an error message

>progn: Wrong type argument: stringp, nil
>, /Greenhalgh v arderne/ ().

GNU Emacs 25.2.1 (x86_64-apple-darwin16.7.0, Carbon Version 157 AppKit 1504.83)
 of 2017-08-05

Org mode version 9.0.9 (9.0.9-58-g808089-elpaplus

org-ref: Version 1.1.1 (git-commit 8e1af145480d53e8d32cdff2c83291889903164b)

**Comment by jkitchin** [comment]
That works for me. can you post a small org file that has this error?

**Comment by BenFeld** [comment]
Here a mininal non-working example:

> #+LATEX_HEADER: \usepackage[style=oscola]{biblatex}
> #+Latex_header: \addbibresource{~/Dropbox/bibliography/legal.bib}
> 
> This is a citation of a case, which does not work.footcite:GreenhalghvArderneCinemasLtd1951
> And this is a citation of a book, which does work.footcite:Kershaw2012
> 

Here relevant parts of my org-ref configuration (using spacemacs):

> ;; org-ref
>   (setq reftex-default-bibliography '("~/Dropbox/bibliography/legal.bib"))
> 
>   ;; see org-ref for use of these variables
>   (setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
>         org-ref-default-bibliography '("~/Dropbox/bibliography/legal.bib")
>         org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")
> 
>   (setq bibtex-completion-bibliography "~/Dropbox/bibliography/legal.bib"
>         bibtex-completion-library-path "~/Dropbox/bibliography/bibtex-pdfs"
>         bibtex-completion-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")
> 
>   ;; open pdf with system pdf viewer (works on mac)
>   (setq bibtex-completion-pdf-open-function
>         (lambda (fpath)
>           (start-process "open" "*open*" "open" fpath)))
> 
> (require 'org-ref)
> 
> ;; org-ref

**Comment by BenFeld** [comment]
Here a mininal non-working example:

#+LATEX_HEADER: \usepackage[style=oscola]{biblatex}
#+Latex_header: \addbibresource{~/Dropbox/bibliography/legal.bib}

This is a citation of a case, which does not work.footcite:GreenhalghvArderneCinemasLtd1951
And this is a citation of a book, which does work.footcite:Kershaw2012
Here relevant parts of my org-ref configuration (using spacemacs):

;; org-ref
(setq reftex-default-bibliography '("~/Dropbox/bibliography/legal.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "/Dropbox/bibliography/notes.org"
org-ref-default-bibliography '("/Dropbox/bibliography/legal.bib")
org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

(setq bibtex-completion-bibliography "/Dropbox/bibliography/legal.bib"
bibtex-completion-library-path "/Dropbox/bibliography/bibtex-pdfs"
bibtex-completion-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")

;; open pdf with system pdf viewer (works on mac)
(setq bibtex-completion-pdf-open-function
(lambda (fpath)
(start-process "open" "open" "open" fpath)))

(require 'org-ref)

;; org-ref

**Comment by jkitchin** [comment]
These both work for me. You might try running M-x org-ref to see if it is picking up the right bibliography or any other issues.

**Comment by BenFeld** [comment]
This is the result of `M-x org-ref`: 

<img width="1438" alt="bildschirmfoto 2017-08-05 um 18 28 19" src="https://user-images.githubusercontent.com/19946958/28997027-f1d990d0-7a0b-11e7-92ba-2cdcd1cf407a.png">

**Comment by jkitchin** [comment]
The only thing that stands out is the bibtex dialect does not match biblatex. But I have the same setting, and it works anyway. Does helm-bibtex work with your bibliography?

**Comment by BenFeld** [comment]
`helm-bibtex`shows this:

<img width="1435" alt="bildschirmfoto 2017-08-05 um 20 41 36" src="https://user-images.githubusercontent.com/19946958/28997833-8f5fc3e4-7a1e-11e7-9d09-4ac61bddf117.png">

**Comment by BenFeld** [comment]
The issue must have to do with custom entry types. I created a new .bib-file `clean.bib`. The `jurisdiction` entry does not work. Both the `article` as well as the `manual` entries, both standard entry types, do work. A custom `org-ref` entry type, however, does not:

`mwe2.org`:

> This sentence makes a reference to a case.cite:XeTeXLaTeX1970
> 
> Reference to an article.cite:Doe1980
> 
> Reference to a manual.cite:Doe1989
> 
> Reference to a custom org-ref entry.cite:Doe1991
> 
> 
> 
> bibliography:~/Dropbox/bibliography/clean.bib

And here the new .bib-file `clean.bib`, created with JabRef:

> % Encoding: ISO-8859-1
> 
> @Jurisdiction{XeTeXLaTeX1970,
>   title        = {XeTeX v LaTeX},
>   volume       = {1},
>   date         = {1970},
>   journaltitle = {EWCA},
>   shorttitle   = {XeTeX v LaTeX},
>   pages        = {12},
>   institution  = {Court of Appeal},
>   number       = {2},
>   options      = {year-essential=true},
>   keywords     = {None},
>   pagination   = {[]},
> }
> 
> @Article{Doe1980,
>   author       = {John Doe},
>   title        = {Doe or not to doe},
>   journal      = {Journal of Doe},
>   journaltitle = {JoD},
>   year         = {1980},
>   date         = {1980-03-03},
> }
> 
> @Manual{Doe1989,
>   author = {John Doe},
>   editor = {John Doe},
>   title  = {Manual on Doe},
>   year   = {1989},
>   date   = {1989-12-02},
> }
> 
> @Org-ref{Doe1991,
>   author = {John Doe},
>   title  = {John Doe does Org-ref},
>   year   = {1991},
> }
> 
> @Comment{jabref-meta: databaseType:biblatex;}
> 
> @Comment{jabref-entrytype: Jurisdiction: req[title;volume;date;journaltitle;shorttitle;pages;institution;number;options;keywords;pagination] opt[]}
> 
> @Comment{jabref-entrytype: Org-ref: req[author;title;year] opt[]}
> 
[clean.bib.zip](https://github.com/jkitchin/org-ref/files/1202982/clean.bib.zip)

**Comment by BenFeld** [comment]
Just to prove my point: when I change the entry type from `jurisdiction` to `article` (without modifying the entry in any other way), I can click on it.

**Comment by jkitchin** [comment]
I see the problem. Emacs does not recognize custom entries that are not listed in bibtex-biblatex-entry-alist as valid. You have add the Jurisdiction (and any other custom types) type to that alist and then (bibtex-set-dialect 'biblatex) to get those entries to be recognized. I would do that in an init file so they are set all the time.

**Comment by BenFeld** [comment]
That seems to do the trick, John. Thank you!

**Comment by petemcd18** [comment]
Hi, just to update this for anyone who is trying to achieve the same the variable has changed from bibtex-set-dialect to just bibtex-dialect to set it permanently you can add (setq bibtex-dialect 'biblatex) to your init file.

I'm new to emacs having recently converted, I have edited the custom entries in bibtex-biblatex-entry-alist through the easy customisation wizard within emacs. 
I am aware of the add-to-list command but have never used it 
How would one add for example the following using the add-to-list command.

Custom entry
Legislation

required fields
title
date
keywords
pagination
entrysubtype

optional fields
shorttitle
number
userb
language

any help would be greatly appreciated as I would prefer to add them using code rather than the wizard.

**Comment by jkitchin** [comment]
I think you do something like this (adapted for the fields you have above) in your init files:
```

#+BEGIN_SRC emacs-lisp :results silent
(add-to-list 'bibtex-biblatex-entry-alist
	     '("Jurisdiction" "A jurisdiction"
	       ("title" "volume" "date" "journaltitle" "shorttitle" "pages" "institution" "number" "options" "pagination")
	       nil
	       "keywords"))

(bibtex-set-dialect 'biblatex)
#+END_SRC
```
Then you should be able to use the

**Comment by adam52** [comment]
Hi John - in this example, how about if you also wanted to add custom fields to the entry type? For example, if you wanted to use “Judge” instead of “Author”? Thanks!

**Comment by jkitchin** [comment]
I don't see any issue with that? Did you try it and it didn't work?

Depending on the type, there could be mandatory fields though, e.g. it would not surprise me if author was required. I don't know if it would cause an error though.

**Comment by adam52** [comment]
Hi John,

Thank you for your response! Following your template, I am able to create the new field and entry as follows:



    ;; Create fields for Film type
    (add-to-list 'bibtex-biblatex-field-alist
                 '(("judge" "Presiding judge over the case")))

    (add-to-list 'bibtex-biblatex-entry-alist
	     '("Jurisdiction" "A jurisdiction"
	       ("judge", "title" "volume" "date" "journaltitle" "shorttitle" "pages" "institution" "number" "options" "pagination")
	       nil
	       "keywords"))

    (bibtex-set-dialect 'biblatex)

I guess my question is, when it comes time to format the bibliography entry, how does BibTeX (or BibLaTeX) know that "Judge" should be treated as an alias for "author" and placed accordingly?

Thanks,
-Adam

**Comment by adam52** [comment]
Following advice from the BibLaTeX manual, I tried adding this LaTeX header to my org file. But it doesn't seem to have effect, either with org-ref or on export to LaTeX:

    #+latex_header: \DeclareLabelname[jurisdiction]{\field{judge}}

**Comment by jkitchin** [comment]
This isn't really an org-ref problem I think. The best strategy here would be to figure out what to add to the latex file that works, and then work backwards to get that in org-mode. These are latex/biblatex issues, and org-ref doesn't do the citation generation for latex export.

**Comment by adam52** [comment]
When I mouse over a `cite:` link, org-ref produces a preview of the citation, both as a tooltip and in the minibuffer. For citations with custom field types (e.g., "judge" instead of "author), the author field is missing in the citation.

Does org-ref pull these citations from the user's latex package? Or does it create these previews internally?

Thanks,

**Comment by jkitchin** [comment]
those previews are created internally. See `org-ref-format-bibtex-entry` and in particular the variable `org-ref-formatted-citation-formats`. I think you can customize this by adding your custom type to it.

Something like this:
```
(push
 '("jurisdiction" . "${judge}. ${title}") 
 (cdr (assoc "text" org-ref-formatted-citation-formats)))
```

I would have thought "text" should be "org" but "text" worked for me.

**Comment by adam52** [comment]
Thanks John! The tooltips and the mode line display works great now. However, clicking on the `cite:` link does not pull up the helm menu (I'm using `org-ref` with `helm-bibtex`). Instead, I get an error:

    org-ref-cite-candidates: Wrong type argument: stringp, nil

Is there another variable I need to customize to finish this off?

Thanks,

**Comment by jkitchin** [comment]
Sounds like it. I am traveling this week away from my computer. I will try looking into it when I get back.

**Comment by jkitchin** [comment]
I haven't been able to reproduce this. If I had to guess, the biblatex dialect is not getting set correctly in the bibtex file. There are two test files in commit 9ab7427 that work for me. Can you try those and see if they work for you?

**Comment by adam52** [comment]
Ah, thanks John. No idea why I couldn't get things going before. But your two test files work perfectly!

**Comment by adam52** [comment]
Hmm... looks like I spoke too soon. While your test files work perfectly, when I actually add this code to my init.el file, clicking the cite: link returns

    org-ref-cite-candidates: Wrong type argument: stringp, nil

I suspect that the code is simply loading too early and needs to wait for org-ref or helm to get setup first? Is there an org-ref hook that could work for this?

Thanks again,

**Comment by jkitchin** [comment]
You get that error on the same files that worked before? Or in some new file?

**Comment by adam52** [comment]
Same files. They only work if I run the babel code block from issue-428.org. But if I move the code to my init.el file, it fails.

**Comment by adam52** [comment]
I think I figured it out. `(require 'bibtex)` needs to go right before `(bibtex-set-dialect biblatex)`. So adding this to my init file works:

    (add-to-list 'org-latex-packages-alist
                 '("style=oscola" "biblatex" t))

    (add-to-list 'bibtex-biblatex-field-alist
                 '(("judge" "Presiding judge over the case")))

    (add-to-list 'bibtex-biblatex-entry-alist
                 '("Jurisdiction" "A jurisdiction"
                   ("judge", "title" "volume" "date" "journaltitle"
                    "shorttitle" "pages" "institution" "number"
                    "options" "pagination")
                   nil
                   "keywords"))

    (push
     '("jurisdiction" . "${judge}. ${title}")
     (cdr (assoc "text" org-ref-formatted-citation-formats)))

    (require 'bibtex) ;; this needs to go right before the next line
    (bibtex-set-dialect 'biblatex)

**Comment by jkitchin** [comment]
oh, that makes sense I guess. That confirms to me the issue is related to the dialect. I guess it was silently failing before?

**Comment by adam52** [comment]
Yeah, no error messages on loading emacs. But all good now. Thanks John!
