### ISSUE TITLE
Citation link in org-ref-note-title-format not clickable:  Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by BenFeld** [jkitchin/org-ref#484]
I modified `org-ref-note-title-format` as follows:

```
** %t
:PROPERTIES:
:Custom_ID:  cite:%k
:END:
```

An example `notes.org` looks like this:

```
** Murray v Bush
 :PROPERTIES:
  :Custom_ID: cite:MurrayvBush1873
 :END:

cite:MurrayvBush1873

** Greenhalgh v Arderne Cinemas Ltd
 :PROPERTIES:
  :Custom_ID: cite:GreenhalghvArderneCinemasLtd1951
 :END:

cite:GreenhalghvArderneCinemasLtd1951

```
Both `cite` links are recognized as links, but the one in `Custom_ID` throws an error message
**Wrong type argument: stringp, nil**, while the other works as it should.

**Comment by jkitchin** [comment]
It probably doesn't make sense to put a link in an ID like that. I am pretty sure org-mode will parse it asa node-property, not a link. so org-ref will probably not work since it won't think it is on a link. I would just use the key as the custom_id.
