### ISSUE TITLE
Cannot open pdfs in Zotero default folders

### ISSUE THREAD

**Issue by novusshu** [jkitchin/org-ref#485]
Hello,
I've found org-ref tremendously helpful for my study and research. For all the citations and bibliography, it works smoothly. However, I have a little problem with zotero pdfs.
I have a .bib file with references exported from zotero. I include it in my `bibliography:` line and can cite references with no issue. 
Now,  I also hope to open the pdfs stored in zotero folders when clicking the a citation and choose the "open pdf" option. I have set up my emacs as instructed in org-ref and helm-bibtex manual: 
```
(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
	 (pdf-file (car (bibtex-completion-find-pdf key))))
    (if (file-exists-p pdf-file)
	(org-open-file pdf-file)
      (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
```
The field is also set: 
`(setq bibtex-completion-pdf-field "file")`

However, when I click any citations, emacs only tries to open a file of `org-ref-pdf-directory/<key>.pdf` (`bibtex-completion-library-path` is set with the same path). It seems to me that this `my/org-ref-open-pdf-at-point` function completely ignored the order specified in `bibtex-completion-find-pdf` function ("If `bibtex-completion-pdf-field` is non-nil, bibtex-completion will first try to retrieve the file specified in this field."). I have tried to change the name and the content in the `file` field of the .bib file to `<key>.pdf`, but it still doesn't work. 

I am using MacOS sierra, emacs 25.2, the recent versions of org-ref (08/05/2017, 08/08/2017), also very recent versions of helm-bibtex (08/08/2017).  My zotero bib file is generated by zotero 4.0.29. An example of a reference is as below (I know the path format in `file=` is not following what helm-bibtex specifies, but even after I changed it manually, there is still no effect) :

```
@article{edwards_concepts_2011,
  title = {Concepts of {{Community}}: {{A Framework}} for {{Contextualizing Distributed Leadership}}: {{Distributed Leadership}} and {{Concepts}} of {{Community}}},
  volume = {13},
  issn = {14608545},
  shorttitle = {Concepts of {{Community}}},
  doi = {10.1111/j.1468-2370.2011.00309.x},
  language = {en},
  timestamp = {2017-08-10T03:09:32Z},
  number = {3},
  urldate = {2017-08-10},
  journal = {International Journal of Management Reviews},
  author = {Edwards, Gareth},
  month = sep,
  year = {2011},
  pages = {301--312},
  file = {Edwards-2011-International_Journal_of_Management_Reviews.pdf:/Users/Book/Library/Application Support/Zotero/Profiles/q5rng4mj.default/zotero/storage/MKFE2XJ7/Edwards-2011-International_Journal_of_Management_Reviews.pdf:application/pdf}
}

```

Could you help me with this issue? Thank you very much!

**Comment by jagrg** [comment]
In the my/org-ref-open-pdf-at-point function, change (org-open-file pdf-file) to (bibtex-completion-open-any (list key)) and see if that helps.

On 10 Aug 2017, novusshu <notifications@github.com> wrote:

> Hello,
> I've found org-ref tremendously helpful for my study and research. For all the citations and bibliography, it works smoothly. However, I have a little problem with zotero pdfs.
> I have a .bib file with references exported from zotero. I include it in my `bibliography:` line and can cite references with no issue. 
> Now,  I also hope to open the pdfs stored in zotero folders when clicking the a citation and choose the "open pdf" option. I have set up my emacs as instructed in org-ref and helm-bibtex manual: 
> ```
> (defun my/org-ref-open-pdf-at-point ()
>   "Open the pdf for bibtex key under point if it exists."
>   (interactive)
>   (let* ((results (org-ref-get-bibtex-key-and-file))
>          (key (car results))
> 	 (pdf-file (car (bibtex-completion-find-pdf key))))
>     (if (file-exists-p pdf-file)
> 	(org-open-file pdf-file)
>       (message "No PDF found for %s" key))))
>
> (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
> ```
> The field is also set: 
> `(setq bibtex-completion-pdf-field "file")`
>
> However, when I click any citations, emacs only tries to open a file of `org-ref-pdf-directory/<key>.pdf` (`bibtex-completion-library-path` is set with the same path). It seems to me that this `my/org-ref-open-pdf-at-point` function completely ignored the order specified in `bibtex-completion-find-pdf` function ("If `bibtex-completion-pdf-field` is non-nil, bibtex-completion will first try to retrieve the file specified in this field."). I have tried to change the name and the content in the `file` field of the .bib file to `<key>.pdf`, but it still doesn't work. 
>
> I am using MacOS sierra, emacs 25.2, the recent versions of org-ref (08/05/2017, 08/08/2017), also very recent versions of helm-bibtex (08/08/2017).  My zotero bib file is generated by zotero 4.0.29. An example of a reference is as below (I know the path format in `file=` is not following what helm-bibtex specifies, but even after I changed it manually, there is still no effect) :
>
> ```
> @article{edwards_concepts_2011,
>   title = {Concepts of {{Community}}: {{A Framework}} for {{Contextualizing Distributed Leadership}}: {{Distributed Leadership}} and {{Concepts}} of {{Community}}},
>   volume = {13},
>   issn = {14608545},
>   shorttitle = {Concepts of {{Community}}},
>   doi = {10.1111/j.1468-2370.2011.00309.x},
>   language = {en},
>   timestamp = {2017-08-10T03:09:32Z},
>   number = {3},
>   urldate = {2017-08-10},
>   journal = {International Journal of Management Reviews},
>   author = {Edwards, Gareth},
>   month = sep,
>   year = {2011},
>   pages = {301--312},
>   file = {Edwards-2011-International_Journal_of_Management_Reviews.pdf:/Users/Book/Library/Application Support/Zotero/Profiles/q5rng4mj.default/zotero/storage/MKFE2XJ7/Edwards-2011-International_Journal_of_Management_Reviews.pdf:application/pdf}
> }
>
> ```
>
> Could you help me with this issue? Thank you very much!


-- 
Jonathan

**Comment by jagrg** [comment]
The original function should work, but you need to wrap it with

(with-eval-after-load "org-ref"
  (defun my/org-ref-open-pdf-at-point ()
    ...
    )
  )

On 10 Aug 2017, novusshu <notifications@github.com> wrote:

> Hello,
> I've found org-ref tremendously helpful for my study and research. For all the citations and bibliography, it works smoothly. However, I have a little problem with zotero pdfs.
> I have a .bib file with references exported from zotero. I include it in my `bibliography:` line and can cite references with no issue. 
> Now,  I also hope to open the pdfs stored in zotero folders when clicking the a citation and choose the "open pdf" option. I have set up my emacs as instructed in org-ref and helm-bibtex manual: 
> ```
> (defun my/org-ref-open-pdf-at-point ()
>   "Open the pdf for bibtex key under point if it exists."
>   (interactive)
>   (let* ((results (org-ref-get-bibtex-key-and-file))
>          (key (car results))
> 	 (pdf-file (car (bibtex-completion-find-pdf key))))
>     (if (file-exists-p pdf-file)
> 	(org-open-file pdf-file)
>       (message "No PDF found for %s" key))))
>
> (setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
> ```
> The field is also set: 
> `(setq bibtex-completion-pdf-field "file")`
>
> However, when I click any citations, emacs only tries to open a file of `org-ref-pdf-directory/<key>.pdf` (`bibtex-completion-library-path` is set with the same path). It seems to me that this `my/org-ref-open-pdf-at-point` function completely ignored the order specified in `bibtex-completion-find-pdf` function ("If `bibtex-completion-pdf-field` is non-nil, bibtex-completion will first try to retrieve the file specified in this field."). I have tried to change the name and the content in the `file` field of the .bib file to `<key>.pdf`, but it still doesn't work. 
>
> I am using MacOS sierra, emacs 25.2, the recent versions of org-ref (08/05/2017, 08/08/2017), also very recent versions of helm-bibtex (08/08/2017).  My zotero bib file is generated by zotero 4.0.29. An example of a reference is as below (I know the path format in `file=` is not following what helm-bibtex specifies, but even after I changed it manually, there is still no effect) :
>
> ```
> @article{edwards_concepts_2011,
>   title = {Concepts of {{Community}}: {{A Framework}} for {{Contextualizing Distributed Leadership}}: {{Distributed Leadership}} and {{Concepts}} of {{Community}}},
>   volume = {13},
>   issn = {14608545},
>   shorttitle = {Concepts of {{Community}}},
>   doi = {10.1111/j.1468-2370.2011.00309.x},
>   language = {en},
>   timestamp = {2017-08-10T03:09:32Z},
>   number = {3},
>   urldate = {2017-08-10},
>   journal = {International Journal of Management Reviews},
>   author = {Edwards, Gareth},
>   month = sep,
>   year = {2011},
>   pages = {301--312},
>   file = {Edwards-2011-International_Journal_of_Management_Reviews.pdf:/Users/Book/Library/Application Support/Zotero/Profiles/q5rng4mj.default/zotero/storage/MKFE2XJ7/Edwards-2011-International_Journal_of_Management_Reviews.pdf:application/pdf}
> }
>
> ```
>
> Could you help me with this issue? Thank you very much!


-- 
Jonathan

**Comment by novusshu** [comment]
Thanks for your reply. But it still doesn't work after either change you suggested...

**Comment by novusshu** [comment]
Oh I just realized I made a stupid mistake... I forgot to add the .bib file generated by zotero to the `bibtex-completion-bibliography` list. The original function does work. Sorry for the trouble. 
Thanks!
