### ISSUE TITLE
HTML export issue with images

### ISSUE THREAD

**Issue by darknmt** [jkitchin/org-ref#487]
Hello,

Puting label in the #+CAPTION header of an image makes the html export work improperly. For example the following text in org
``` 
#+CAPTION: Homotopy operator \( \varepsilon \). label:homotopy-operator
file:../img/2017-08-13-homotopy-operator.png
```
is exported to 

``` html
<div class="figure">
<p><img src="../img/2017-08-13-homotopy-operator.png" alt="2017-08-13-homotopy-operator.png" />
</p>
<p><span class="figure-number">Figure 1: </span>Homotopy operator \( \varepsilon \). <div id="homotopy-operator"></p>
</div>
</div>
</div>
```
which has the text following that image centered.

**Comment by jkitchin** [comment]
That is an org-mode issue. Why do you think that is improper?

**Comment by darknmt** [comment]
The `</div>` and `</p>` tags are misplaced, so if I have text following that image, it is also included in the same `div` and gets justified.

**Comment by jkitchin** [comment]
That is probably an org-mode issue unless you can confirm it does not happen with org-ref not loaded. You should ask about it on the org-mode mailing list.
