### ISSUE TITLE
Rename all files in the file field of a Bibtex exported from Mendely

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jkitchin/org-ref#489]
The bibtex exported from Mendely is terrible, especially the "file" field. I want to write a lisp function the scans the bibtex, and rename all PDFs of an entry to be KEYa, KEYb, .... However, I am not that good in LISP. Any help?

**Comment by jkitchin** [comment]
Check out the functions in the variable org-ref-clean-bibtex-entry-hook. They all modify bibtex entries. You might also checkout the function org-ref-title-case-article, it may provide some inspiration on how to change a field.
