### ISSUE TITLE
Problem exporting to HTML

### ISSUE THREAD

**Issue by kevinsullivan** [jkitchin/org-ref#49]
Hi, Thanks for this nice work. Following your instructions, I've mostly got it working on my site. I'm using emacs24. It looks like that might be a newer version that you're assuming? In particular, I don't see the f or s packages in the repos. I downloaded them from GitHub and pointed emacs at them, but I don't know if they're being used. That's the background.

At this point, I can export your org-ref.org file to LaTeX/PDF. However, when I try to export to HTML, I get an error. The error is occurring right here:

#+BEGIN_SRC emacs-lisp
org-ref-cite-types
#+END_SRC

The message is: Wrong type argument, characterp, nil. I've provided a stack trace below (and am seeing a lot of suspicious nils).

Thanks, again!
Kevin 

Debugger entered--Lisp error: (wrong-type-argument characterp nil)
  pretty-font-lock-compose-symbol((("sqrt" . 8730) ("nil" . 8709) ("=>" . 8658) ("->>" . 8608) ("->" . 8594) ("<-" . 8592) ("lambda" . 955) ("or" . 8744) ("and" . 8743) ("not" . 172) (">=" . 8805) ("<=" . 8804)))
  eval((pretty-font-lock-compose-symbol (quote (("sqrt" . 8730) ("nil" . 8709) ("=>" . 8658) ("->>" . 8608) ("->" . 8594) ("<-" . 8592) ("lambda" . 955) ("or" . 8744) ("and" . 8743) ("not" . 172) (">=" . 8805) ("<=" . 8804)))))
  font-lock-fontify-keywords-region(1 20 nil)
  font-lock-default-fontify-region(1 20 nil)
  font-lock-fontify-region(1 20 nil)
  byte-code("\212\303 \304\216\305ed	#\210\306 \210\307\211+\207" [save-match-data-internal verbose font-lock-fontified match-data ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) font-lock-fontify-region font-lock-after-fontify-buffer t] 4)
  font-lock-default-fontify-buffer()
  font-lock-fontify-buffer()
  org-html-fontify-code("org-ref-cite-types\n" "emacs-lisp")
  org-html-do-format-code("org-ref-cite-types\n" "emacs-lisp" nil t nil)
  org-html-format-code((src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #2)) #0))) (:export-options nil :input-file "/home/cs1/System/el/org-ref/org-ref.org" :input-buffer "org-ref.org" :html-extension "html" :html-link-org-as-html t :html-doctype "xhtml-strict" :html-container "div" :html-html5-fancy nil :html-link-use-abs-url nil :html-link-home "" :html-link-up "" :html-mathjax "" :html-postamble auto :html-preamble t :html-head "" :html-head-extra "" :html-head-include-default-style t :html-head-include-scripts t :html-table-attributes (:border "2" :cellspacing "0" :cellpadding "6" :rules "groups" :frame "hsides") :html-table-row-tags ("<tr>" . "</tr>") :html-xml-declaration (("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>")) :html-inline-images t :infojs-opt nil :creator "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a> 24.4.1 (<a href=\"http://orgmode.org\">Org</a> mode 8.2.10)" :with-latex t ...))
  org-html-src-block((src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #2)) #0))) nil (:export-options nil :input-file "/home/cs1/System/el/org-ref/org-ref.org" :input-buffer "org-ref.org" :html-extension "html" :html-link-org-as-html t :html-doctype "xhtml-strict" :html-container "div" :html-html5-fancy nil :html-link-use-abs-url nil :html-link-home "" :html-link-up "" :html-mathjax "" :html-postamble auto :html-preamble t :html-head "" :html-head-extra "" :html-head-include-default-style t :html-head-include-scripts t :html-table-attributes (:border "2" :cellspacing "0" :cellpadding "6" :rules "groups" :frame "hsides") :html-table-row-tags ("<tr>" . "</tr>") :html-xml-declaration (("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>")) :html-inline-images t :infojs-opt nil :creator "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a> 24.4.1 (<a href=\"http://orgmode.org\">Org</a> mode 8.2.10)" :with-latex t ...))
  org-export-data((src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #2)) #0))) (:export-options nil :input-file "/home/cs1/System/el/org-ref/org-ref.org" :input-buffer "org-ref.org" :html-extension "html" :html-link-org-as-html t :html-doctype "xhtml-strict" :html-container "div" :html-html5-fancy nil :html-link-use-abs-url nil :html-link-home "" :html-link-up "" :html-mathjax "" :html-postamble auto :html-preamble t :html-head "" :html-head-extra "" :html-head-include-default-style t :html-head-include-scripts t :html-table-attributes (:border "2" :cellspacing "0" :cellpadding "6" :rules "groups" :frame "hsides") :html-table-row-tags ("<tr>" . "</tr>") :html-xml-declaration (("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>")) :html-inline-images t :infojs-opt nil :creator "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a> 24.4.1 (<a href=\"http://orgmode.org\">Org</a> mode 8.2.10)" :with-latex t ...))
  #[(element) "\302	\"\207" [element info org-export-data] 3]((src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #2)) #0))))
  mapconcat(#[(element) "\302	\"\207" [element info org-export-data] 3] ((src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #3)) #1)))) "")
  org-export-data((section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #0)) (src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent #0))) (:export-options nil :input-file "/home/cs1/System/el/org-ref/org-ref.org" :input-buffer "org-ref.org" :html-extension "html" :html-link-org-as-html t :html-doctype "xhtml-strict" :html-container "div" :html-html5-fancy nil :html-link-use-abs-url nil :html-link-home "" :html-link-up "" :html-mathjax "" :html-postamble auto :html-preamble t :html-head "" :html-head-extra "" :html-head-include-default-style t :html-head-include-scripts t :html-table-attributes (:border "2" :cellspacing "0" :cellpadding "6" :rules "groups" :frame "hsides") :html-table-row-tags ("<tr>" . "</tr>") :html-xml-declaration (("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>")) :html-inline-images t :infojs-opt nil :creator "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a> 24.4.1 (<a href=\"http://orgmode.org\">Org</a> mode 8.2.10)" :with-latex t ...))
  #[(element) "\302	\"\207" [element info org-export-data] 3]((section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #0)) (src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent #0))))
  mapconcat(#[(element) "\302	\"\207" [element info org-export-data] 3] ((section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent (org-data nil #1)) (src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent #1)))) "")
  org-export-data((org-data nil (section (:begin 5731 :end 5783 :contents-begin 5731 :contents-end 5783 :post-blank 0 :parent #0) (src-block (:language "emacs-lisp" :switches nil :parameters nil :begin 5731 :end 5783 :number-lines nil :preserve-indent nil :retain-labels t :use-labels t :label-fmt nil :hiddenp nil :value "org-ref-cite-types\n" :post-blank 0 :post-affiliated 5731 :parent #1)))) (:export-options nil :input-file "/home/cs1/System/el/org-ref/org-ref.org" :input-buffer "org-ref.org" :html-extension "html" :html-link-org-as-html t :html-doctype "xhtml-strict" :html-container "div" :html-html5-fancy nil :html-link-use-abs-url nil :html-link-home "" :html-link-up "" :html-mathjax "" :html-postamble auto :html-preamble t :html-head "" :html-head-extra "" :html-head-include-default-style t :html-head-include-scripts t :html-table-attributes (:border "2" :cellspacing "0" :cellpadding "6" :rules "groups" :frame "hsides") :html-table-row-tags ("<tr>" . "</tr>") :html-xml-declaration (("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>")) :html-inline-images t :infojs-opt nil :creator "<a href=\"http://www.gnu.org/software/emacs/\">Emacs</a> 24.4.1 (<a href=\"http://orgmode.org\">Org</a> mode 8.2.10)" :with-latex t ...))
  org-export-as(html nil nil nil (:output-file "./org-ref.html"))
  org-export-to-file(html "./org-ref.html" nil nil nil nil nil)
  org-html-export-to-html(nil nil nil nil)
  (org-open-file (org-html-export-to-html nil s v b))
  (if a (org-html-export-to-html t s v b) (org-open-file (org-html-export-to-html nil s v b)))
  (lambda (a s v b) (if a (org-html-export-to-html t s v b) (org-open-file (org-html-export-to-html nil s v b))))(nil nil nil nil)
  org-export-dispatch(nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)

**Comment by jkitchin** [comment]
Is this still an issue for you? If so, can you send me a minimal org file that has the problem?
