### ISSUE TITLE
helm-cite handles commas that separate between citations incorrectly

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#490]
Here is the result I got in the buffer when pressing `C-j` on three candidates when using `helm-cite` backend:

`cite:AbrahamDGW2011c-Hub-BasedAkibaIY2013c-Fast-Exact,,AldingerN2017c-Inter-Based`

That is, there is no comma between the first (`AbrahamDGW2011c-Hub-Based`) and the second (`AkibaIY2013c-Fast-Exact`) citations, while there are two commas between the second and the third citations. The same behavior happens when simply appending citations to an existing one without the use of `C-j`.

**Comment by jkitchin** [comment]
I can reproduce this. It looks like a bug. I will be traveling for the next 4 days. I will try to fix this next week.

**Comment by jkitchin** [comment]
sorry this took so long. hopefully this fixed it.
