### ISSUE TITLE
A bug in org-ref-show-link-messages

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#494]
The following function should have no effect:

```
(defun test()
  (interactive)
  (org-ref-cancel-link-messages)
  (org-ref-show-link-messages))
```
However, after evaluating `(test)`, the help echo of citation links is not displayed anymore. It looks like `(setq org-ref-show-citation-on-enter t)` is missing in `org-ref-show-link-messages`.

**Comment by jkitchin** [comment]
I couldn't reproduce this exactly, but it does seem like that variable should get reset, so I added it and pushed. Thanks for reporting it.

**Comment by mgoldenbe** [comment]
I think that there is a new bug now: the line `org-ref-message-timer t` is extra.

**Comment by jkitchin** [comment]
indeed it does. Thanks for pointing it out.
