### ISSUE TITLE
Adding bibtex entry from doi not working

### ISSUE THREAD

**Issue by samhaney** [jkitchin/org-ref#495]
I'm having an issue adding bibtex entries using the doi utils functions. I'm running doi-utils-add-bibtex-entry-from-doi and using the doi 10.1109/re.2014.6912247 (found in the IEEE section of doi-utils.el) . If I point it to an empty bibtex file, the following output is inserted into the file:

paper-conference not supported yet
(:indexed (:date-parts [[2017 8 16]] :date-time "2017-08-16T16:03:04Z" :timestamp 1502899384337) :reference-count 32 :publisher "IEEE" :content-domain (:domain [] :crossmark-restriction :json-false) :published-print (:date-parts [[2014 8]]) :DOI "10.1109/re.2014.6912247" :type "paper-conference" :created (:date-parts [[2014 9 30]] :date-time "2014-09-30T20:37:18Z" :timestamp 1412109438000) :source "Crossref" :is-referenced-by-count 8 :title "Protos: Foundations for engineering innovative sociotechnical systems" :prefix "10.1109" :author [(:given "Amit K." :family "Chopra" :affiliation []) (:given "Fabiano" :family "Dalpiaz" :affiliation []) (:given "F. Basak" :family "Aydemir" :affiliation []) (:given "Paolo" :family "Giorgini" :affiliation []) (:given "John" :family "Mylopoulos" :affiliation []) (:given "Munindar P." :family "Singh" :affiliation [])] :member "263" :event "2014 IEEE 22nd International Requirements Engineering Conference (RE)" :container-title "2014 IEEE 22nd International Requirements Engineering Conference (RE)" :original-title [] :link [(:URL "http://xplorestaging.ieee.org/ielx7/6903646/6912234/06912247.pdf?arnumber=6912247" :content-type "unspecified" :content-version "vor" :intended-application "similarity-checking")] :deposited (:date-parts [[2017 6 22]] :date-time "2017-06-22T21:31:43Z" :timestamp 1498167103000) :score 1.0 :subtitle [] :short-title [] :issued (:date-parts [[2014 8]]) :ISBN ["9781479930333" "9781479930319"] :references-count 32 :URL "http://dx.doi.org/10.1109/re.2014.6912247" :relation nil).

If I run this on a non-empty bibtex file, it changes the last entry of the bibtex file so the DATE_ADDED field is the current time and date.

Relevant debug info:

doi:10.1109/re.2014.6912247

* JSON
((indexed
  (date-parts .
              [[2017 8 16]])
  (date-time . "2017-08-16T16:03:04Z")
  (timestamp . 1502899384337))
 (reference-count . 32)
 (publisher . "IEEE")
 (content-domain
  (domain .
          [])
  (crossmark-restriction . :json-false))
 (published-print
  (date-parts .
              [[2014 8]]))
 (DOI . "10.1109/re.2014.6912247")
 (type . "paper-conference")
 (created
  (date-parts .
              [[2014 9 30]])
  (date-time . "2014-09-30T20:37:18Z")
  (timestamp . 1412109438000))
 (source . "Crossref")
 (is-referenced-by-count . 8)
 (title . "Protos: Foundations for engineering innovative sociotechnical systems")
 (prefix . "10.1109")
 (author .
         [((given . "Amit K.")
           (family . "Chopra")
           (affiliation .
                        []))
          ((given . "Fabiano")
           (family . "Dalpiaz")
           (affiliation .
                        []))
          ((given . "F. Basak")
           (family . "Aydemir")
           (affiliation .
                        []))
          ((given . "Paolo")
           (family . "Giorgini")
           (affiliation .
                        []))
          ((given . "John")
           (family . "Mylopoulos")
           (affiliation .
                        []))
          ((given . "Munindar P.")
           (family . "Singh")
           (affiliation .
                        []))])
 (member . "263")
 (event . "2014 IEEE 22nd International Requirements Engineering Conference (RE)")
 (container-title . "2014 IEEE 22nd International Requirements Engineering Conference (RE)")
 (original-title .
                 [])
 (link .
       [((URL . "http://xplorestaging.ieee.org/ielx7/6903646/6912234/06912247.pdf?arnumber=6912247")
         (content-type . "unspecified")
         (content-version . "vor")
         (intended-application . "similarity-checking"))])
 (deposited
  (date-parts .
              [[2017 6 22]])
  (date-time . "2017-06-22T21:31:43Z")
  (timestamp . 1498167103000))
 (score . 1.0)
 (subtitle .
           [])
 (short-title .
              [])
 (issued
  (date-parts .
              [[2014 8]]))
 (ISBN .
       ["9781479930333" "9781479930319"])
 (references-count . 32)
 (URL . "http://dx.doi.org/10.1109/re.2014.6912247")
 (relation))

#+TITLE: org-ref debug

org-ref: Version 1.1.1 (git-commit 8e1af145480d53e8d32cdff2c83291889903164b)

* Variables
1. org-ref-completion-library: org-ref-helm-bibtex
2. org-ref-bibliography-notes: ~/Dropbox/r/notebook/ref.org (exists t)
3. org-ref-default-bibliography: (~/Dropbox/r/notebook/ref.bib) (exists (t)) (listp t)
4. org-ref-pdf-directory: ~/Dropbox/r/notebook/ref-pdfs/ (exists t)

* System
system-type: System: darwin
system-configuration: x86_64-apple-darwin14.5.0
window system: Window system: ns
Emacs: GNU Emacs 25.1.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2109))
 of 2017-04-17
org-version: 9.1

* about org-ref
org-ref installed in /Users/shaney/.emacs.d/elpa/org-ref-20170808.625/org-ref.el.

** Dependencies
helm-bibtex /Users/shaney/.emacs.d/elpa/helm-bibtex-20170808.1124/helm-bibtex.elc

* org-ref-pdf (loaded: t)
system pdftotext: /usr/local/bin/pdftotext
You set pdftotext-executable to pdftotext (exists: /usr/local/bin/pdftotext)

* org-ref-url-utils (loaded: nil)

* export variables
org-latex-pdf-process:
("%latex -interaction nonstopmode -output-directory %o %f" "%latex -interaction nonstopmode -output-directory %o %f" "%latex -interaction nonstopmode -output-directory %o %f")

**Comment by jkitchin** [comment]
The first problem is due to "paper-conference not supported yet". You need to look add this type using
doi-utils-def-bibtex-type. For example the article is defined as:

(doi-utils-def-bibtex-type article ("journal-article" "article-journal")
                           author title journal year volume number pages doi url).

The second issue is the same as the first, except it is probably a bug to update the date added field.

**Comment by tompre** [comment]
This should be solved and can be closed.
