### ISSUE TITLE
Question about org-ref-replace-nonascii

### ISSUE THREAD

**Issue by treese** [jkitchin/org-ref#498]
In using `org-ref-replace-nonascii`, I have noticed that it pops up an *Occur* buffer with all the remaining non-ascii characters in the buffer after cleaning the ones in a single entry. When I use this in a hook to clean a single entry, this pop-up is distracting in showing other problems in the buffer that I'm not ready to deal with.

Removing the call to `occur` would solve this problem, but I'm not sure if the current behavior is popular with others using org-ref.

What is the most appropriate behavior here?

**Comment by jkitchin** [comment]
I don't know if it is popular or not either. It used to be a big deal to have nonascii characters present, but these days it doesn't seem to be a problem. I used to have it pop up especially to remind me of other problems in the buffer though :) I would be happy to take a pull request to remove the occur line.

**Comment by treese** [comment]
Just submitted the pull request. Thanks for org-ref--it's fantastic.

**Comment by jkitchin** [comment]
Thanks!
