### ISSUE TITLE
can not use doi-utils-add-bibtex-entry-from-doi

### ISSUE THREAD

**Issue by liuzy** [jkitchin/org-ref#502]
Hi, jkitchin, I have met a new problem these days when I use doi-utils-add-bibtex-entry-from-doi to get a pdf file.

As an example, the doi selected is "10.1016/j.ijggc.2017.05.013", and the output of the "curl -LH 'Accept: application/citeproc+json' 'http://doi.org/10.1016/j.ijggc.2017.05.013'" is as follows:

{"indexed":{"date-parts":[[2017,8,11]],"date-time":"2017-08-11T15:09:34Z","timestamp":1502464174612},"reference-count":50,"publisher":"Elsevier BV","license":[{"URL":"http:\/\/www.elsevier.com\/tdm\/userlicense\/1.0\/","start":{"date-parts":[[2017,8,1]],"date-time":"2017-08-01T00:00:00Z","timestamp":1501545600000},"delay-in-days":0,"content-version":"tdm"}],"funder":[{"DOI":"10.13039\/501100007519","name":"Shiraz University of Technology","doi-asserted-by":"publisher","award":[]}],"content-domain":{"domain":["elsevier.com","sciencedirect.com"],"crossmark-restriction":true},"published-print":{"date-parts":[[2017,8]]},"DOI":"10.1016\/j.ijggc.2017.05.013","type":"article-journal","created":{"date-parts":[[2017,5,23]],"date-time":"2017-05-23T20:09:53Z","timestamp":1495570193000},"page":"95-106","update-policy":"http:\/\/dx.doi.org\/10.1016\/elsevier_cm_policy","source":"Crossref","is-referenced-by-count":0,"title":"Prediction of CO 2  sorption in poly(ionic liquid)s using ANN-GC and ANFIS-GC models","prefix":"10.1016","volume":"63","author":[{"given":"Farshad","family":"Gholizadeh","affiliation":[]},{"given":"Fatemeh","family":"Sabzi","affiliation":[]}],"member":"78","container-title":"International Journal of Greenhouse Gas Control","original-title":[],"link":[{"URL":"http:\/\/api.elsevier.com\/content\/article\/PII:S1750583616308751?httpAccept=text\/xml","content-type":"text\/xml","content-version":"vor","intended-application":"text-mining"},{"URL":"http:\/\/api.elsevier.com\/content\/article\/PII:S1750583616308751?httpAccept=text\/plain","content-type":"text\/plain","content-version":"vor","intended-application":"text-mining"}],"deposited":{"date-parts":[[2017,7,12]],"date-time":"2017-07-12T02:01:19Z","timestamp":1499824879000},"score":1.0,"subtitle":[],"short-title":[],"issued":{"date-parts":[[2017,8]]},"references-count":50,"alternative-id":["S1750583616308751"],"URL":"http:\/\/dx.doi.org\/10.1016\/j.ijggc.2017.05.013","relation":{},"ISSN":["1750-5836"],"subject":["General Energy","Industrial and Manufacturing Engineering","Pollution","Management, Monitoring, Policy and Law"],"container-title-short":"International Journal of Greenhouse Gas Control","assertion":[{"value":"Elsevier","name":"publisher","label":"This article is maintained by"},{"value":"Prediction of CO2 sorption in poly(ionic liquid)s using ANN-GC and ANFIS-GC models","name":"articletitle","label":"Article Title"},{"value":"International Journal of Greenhouse Gas Control","name":"journaltitle","label":"Journal Title"},{"value":"http:\/\/dx.doi.org\/10.1016\/j.ijggc.2017.05.013","name":"articlelink","label":"CrossRef DOI link to publisher maintained version"},{"value":"article","name":"content_type","label":"Content Type"},{"value":"\u00a9 2017 Elsevier Ltd. All rights reserved.","name":"copyright","label":"Copyright"}]}%

When I run "doi-utils-add-bibtex-entry-from-doi" on this doi, I got "f-exists?: Wrong type argument: stringp, nil", and the program tried to open a web page which is showed by the attachment.

The tool once worked well for me . 

Please help me finding what is the matter, many thanks !

![error](https://user-images.githubusercontent.com/1491241/30597166-cb633230-9d88-11e7-8619-e0cff2243a75.png)

**Comment by jkitchin** [comment]
I get a different error than you:  url-retrieve-internal: Bad url: 8, although it does add an entry to my bib-file. I guess maybe they have changed the url to the pdf file?
