### ISSUE TITLE
Not getting a clickable link

### ISSUE THREAD

**Issue by jmburgos** [jkitchin/org-ref#503]
Hi John,

Not sure why, but I am not getting "clickable" links from org-ref any more.  Until a recent upgrade, when selecting a reference from my bibtex file (I'm using ivy-bibtex), I would get a citation like this:
cite:Burgos2007
Now I only get the bibtex label, which is the default that I set in ivy-bibtex for org files.  If I change that default to, say, insert a link to the pdf file, I get that.  Org-ref is not modifying the citation.
Strangely, if I add "cite:" to the bibtex label, the link becomes functional and all org-ref's options are available.

I am using org-ref: Version 1.1.1 (git-commit 200afb7afe3014226e0c9fe46fe1bd126a8dd304) 
on emacs 25.2.1

Thanks for the help!

**Comment by jkitchin** [comment]
I don't know what could be the cause of that. I guess that some defaults in ivy-bibtex have changed. I don't understand what you are doing though. Is it that you run ivy-bibtex, select a candidate, press enter and you no longer get a cite link? If so, that surely means somehow the default action in ivy-bibtex has changed.

Can you paste the output of M-x org-ref-debug here?

**Comment by jmburgos** [comment]
Sorry posting such a vague question.  Yes, I guess you are right.  Although I always though that org-ref modified the type of links inserted by ivy- (or helm-) bibtext.  For example, in an org mode buffer, ivy-bibtex inserts by default a link to the pdf., but after installing org-ref that changed to a citation of the format "cite: Burgos2007".   Also if I changed the value of org-ref-default-citation-link to "parencite", I got a cite like "parencite:Burgos2007".  But perhaps I do not understand very well how both packages interact.

I have solved by now by adding my own function to bibtex-completion-format-citation-functions to be used in org-mode buffers, to add the correct tipe of citation so they work with org-ref.  I'm pasting the output of org-ref-debug in case you see anything obvious.  Otherwise feel free to close this issue.  
 

org-ref: Version 1.1.1 (git-commit 200afb7afe3014226e0c9fe46fe1bd126a8dd304)

* Variables
1. org-ref-completion-library: org-ref-ivy-cite
2. org-ref-bibliography-notes: /home/julian/Documents/org_files/notes.org (exists t)
3. org-ref-default-bibliography: (/home/julian/Documents/org_files/references.bib) (exists (t)) (listp t)
4. org-ref-pdf-directory: /home/julian/Documents/Refs/ (exists t)

* System
system-type: System: gnu/linux
system-configuration: x86_64-unknown-linux-gnu
window system: Window system: x
Emacs: GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.13)
 of 2017-05-12
org-version: 9.1.1

* about org-ref
org-ref installed in /home/julian/.emacs.d/elpa/org-ref-20170927.2056/org-ref.elc.

** Dependencies
helm-bibtex /home/julian/.emacs.d/elpa/helm-bibtex-20170922.627/helm-bibtex.elc

* org-ref-pdf (loaded: t)
system pdftotext: /usr/bin/pdftotext
You set pdftotext-executable to pdftotext (exists: /usr/bin/pdftotext)

* org-ref-url-utils (loaded: nil)

* export variables
org-latex-pdf-process:
("latexmk -f -pdf -verbose -bibtex %f")

**Comment by jkitchin** [comment]
org-ref does have its own insert link code. It also should change the default actions for helm/ivy-bibtex. Out of the box, the default for those is not to insert a link, so org-ref should make that the default. In any case, glad to hear it is working for you now!
