### ISSUE TITLE
org-ref-helm-cite opens the bibtex files in non-temporary buffers.

### ISSUE THREAD

**Issue by mgoldenbe** [jkitchin/org-ref#505]
`org-ref-helm-cite` opens the bibtex files in *non-temporary* buffers. Having all these buffers open is a problem for me, since I keep each paper's bibtex entry in a separate file, which means that hundreds of buffers are open. If this problem is low priority, then I would appreciate if you can please point me to the place in the code that opens the bibtex files. Thanks!

**Comment by jkitchin** [comment]
I pushed one fix that was in a function checking the cache. There could be other places where bibfiles get opened though.

**Comment by mgoldenbe** [comment]
There obviously are, since I still observe the behavior described in the original post...

**Comment by mgoldenbe** [comment]
I see that bibtex files are opened in `orhc-update-bibfile-cache`. If this is what you fixed, then may be your latest push have not made it to melpa yet. Please let me know.

**Comment by jkitchin** [comment]
Has this all been fixed now?

**Comment by mgoldenbe** [comment]
Difficult to say, since I do not understand the last fix well. Why didn't you simply use  `(with-temp-buffer (insert-file-contents bibfile)` there as well?

**Comment by jkitchin** [comment]
I think that needs to be in bibtex-mode to parse right, so it should check if the file is open, then find-file-noselect it to do what it needs, and if the file was not open after that, it gets closed. That way files that start open stay open, and get closed otherwise.

**Comment by mgoldenbe** [comment]
This seems to complicated. Using a temporary buffer avoids the need for checking whether the file was open or not. You can put a temporary buffer into bibtex mode.
