### ISSUE TITLE
cannot add this article to my .bib file

### ISSUE THREAD

**Issue by zhixing2017** [jkitchin/org-ref#508]
J. Phys. Chem. B, 2005, 109 (10), pp 4481–4484
DOI: 10.1021/jp044511+

`wrong-type-argument stringp nil`

**Comment by jkitchin** [comment]
It looks like there is bad json data for this doi:

component not supported yet
(:indexed (:date-parts [[2017 8 12]] :date-time "2017-08-12T18:48:04Z" :timestamp 1502563684071) :reference-count 0 :publisher "American Chemical Society (ACS)" :content-domain (:domain [] :crossmark-restriction :json-false) :DOI "10.1021/jp044511" :type "component" :created (:date-parts [[2008 7 8]] :date-time "2008-07-08T19:33:47Z" :timestamp 1215545627000) :source "Crossref" :is-referenced-by-count 0 :title [] :prefix "10.1021" :member "316" :container-title [] :original-title [] :deposited (:date-parts [[2017 3 3]] :date-time "2017-03-03T03:27:40Z" :timestamp 1488511660000) :score 1.0 :subtitle [] :short-title [] :issued (:date-parts [[nil]]) :references-count 0 :URL "http://dx.doi.org/10.1021/jp044511" :relation nil).

There is nothing org-ref can do about that.

**Comment by zhixing2017** [comment]
org-ref cannot support `+`, these is no way to work it out?

**Comment by jagrg** [comment]
I agree with John. The json data is bad for this doi. Even if you were
to add "component" as a bibtex type, the data is still missing basic
information to create a proper entry.

On 12 Oct 2017, Zhixing <notifications@github.com> wrote:

> org-ref cannot support +, these is no way to work it out?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Jonathan
Monthly Atmospheric CO₂: September 2017: 403.38, September 2016: 401.03

**Comment by jkitchin** [comment]
The + is not the issue at all. org-ref gets the doi data just fine, it is the data from dx.doi.org that is the problem. ACS is the problem on this article.

**Comment by zhixing2017** [comment]
OK, I know. Thanks.
