### ISSUE TITLE
org-ref-bibtex-hydra binding not working

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#510]
I really like the hydra in org-ref-bibtex, but it has recently stopped working.  Before, the default binding to C-j brought it up when in a .bib file, but now in a .bib file, C-j is bound to bibtex-next-field, which comes from emacs's bibtex.el.

I can see that org-ref-bibtex has been loaded, for example, I can manually run the hydra with:

`  M-x org-ref-bibtex-hydra/body`

And I can see the C-j customization in my .emacs file:

` '(org-ref-bibtex-hydra-key-binding "j")`

It's just that the binding's not taking effect.

Can you reproduce this?  If not, any advice?

**Comment by jkitchin** [comment]
I can't reproduce it. Do you define the variable binding before org-ref is loaded?

If you run this:
    (when org-ref-bibtex-hydra-key-binding
      (define-key bibtex-mode-map org-ref-bibtex-hydra-key-binding 'org-ref-bibtex-hydra/body))

does your binding work again?

**Comment by notuntoward** [comment]
Nope, the hydra binding still didn't work, but it does now, due to brute force.  

I reorganized my .emacs file around `use-package` (see org-ref part below), and although the hydra binding customization still had no effect, I was able to force it by putting:

 `(define-key bibtex-mode-map "\C-cj" 'org-ref-bibtex-hydra/body)`

in the `:config` section.   There must be some package interaction that I'm unable to find.

My .emacs reorg may have also sped up `org-ref`, both on emacs startup and when I add my first `cite`: link (#468).  It's dramatically faster, either because of the reorg or because of some emacs package update.

**Using use-package...**
```
(use-package org-ref
  :after org
  :init
  (let ((default-directory docDir))
    (setq org-ref-bibliography-notes (expand-file-name "notes.org")
          org-ref-default-bibliography (expand-file-name "energy.bib")
          org-ref-pdf-directory (expand-file-name "papers")
          reftex-default-bibliography org-ref-default-bibliography
          bibtex-completion-bibliography org-ref-default-bibliography
          bibtex-completion-library-path org-ref-pdf-directory
          bibtex-completion-notes-path org-ref-bibliography-notes))
  ;; showing broken links slowed down energytop.org (but much less in Oct. 2017)
  ;; https://github.com/jkitchin/org-ref/issues/468
  (setq org-ref-show-broken-links nil) ;still need to prohibit broken link show?
  :config
  (define-key bibtex-mode-map "\C-cj" 'org-ref-bibtex-hydra/body)
  ;; bibtex-key generator: firstauthor-year-title-words (from bixuanzju)
  (setq bibtex-autokey-year-length 4
        bibtex-autokey-name-year-separator "-"
        bibtex-autokey-year-title-separator "-"
        bibtex-autokey-titleword-separator "-"
        bibtex-autokey-titlewords 2
        bibtex-autokey-titlewords-stretch 1
        bibtex-autokey-titleword-length 5)
      ;; Make the org-ref bibtex link folded.  This will make them not export as good latex (bummer) :
      ;; https://github.com/jkitchin/org-ref/issues/345#issuecomment-262646855
  (org-link-set-parameters "cite" :display nil)
)
```

**Comment by jkitchin** [comment]
Great, I am glad to hear it works. I use use-package pretty extensively. I don't understand how it could speed up org-ref, but glad to hear that too.
