### ISSUE TITLE
org-ref-open-bibtex-pdf doesn't work, although emacs can open pdfs otherwise

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#511]
In a BibTex file, if I put the emacs cursor on an entry containing a pdf refererence, and then type: 

`M-x org-ref-open-bibtex-pdf`

then the pdf does not open.  There are no warning messages.

However, in an org file, when I make a file link to the same pdf, and then type `C-c C-o`, then the pdf does open.  I can also open it in `dired` by putting the cursor on it and typing `&`.

This is on Windows 10 with Org mode version 9.1.2, org-ref Version 1.1.1, and GNU Emacs 25.2.1.  Oddly, `M-x org-ref-open-bibtex-pdf` does work on another computer with the same software configuration, except that it's running Windows 7.

**Comment by jkitchin** [comment]
It works fine for me on a Mac. This function just constructs a link and then tries to open it. I don't know why it would fail on one machine and work on another.

**Comment by notuntoward** [comment]
What was really hard to understand is why _on the same machine_, `org-mode` can open a pdf but `org-ref-bibtex `cannot.  

But it seems to have something to do with spaces in a path.  On my Win10 machine, I have my pdfs in a directory named:

     c:/Users/scotto/Tempo Box/ref/papers/

so, in my test case, `org-ref-open-bibtex-pdf` was trying to open

     c:/Users/scotto/Tempo Box/ref/papers/Garcke17dimRedWindTurb.pdf

I can see that `org-ref-open-bibtex-pdf` uses this path literally when it calls the org function `org-open-link-from-string`.   If I try to run that function as `org-ref-open-bibtex-pdf` does it:

```
(setq pdf "c:/Users/scotto/Tempo Box/ref/papers/Garcke17dimRedWindTurb.pdf")
(org-open-link-from-string (format "[[file:%s]]" pdf))
```

Then the pdf doesn't open, but it will open if I move the pdf:

`(setq pdf "c:/Users/scotto/tmp/Garcke17dimRedWindTurb.pdf")`

The lack of a space in the path is also the difference between my Win10 and Win7 machines.

So it looks like emacs dired, and the emacs org-mode code that handles file links, do something special with path spaces.

**Comment by jkitchin** [comment]
Spaces usually do cause some problem, I have seen similar issues with Google Drive. I wonder if it works if you escape them, e.g. 

(org-open-link-from-string (format "[[file:%s]]" (org-link-escape pdf)))
