### ISSUE TITLE
C-u for selecting citation format doesn't work

### ISSUE THREAD

**Issue by zuo-zuo** [jkitchin/org-ref#512]
Hi, John,

Thanks very much for org-ref.

I followed org-ref manual and the default citation works fine: I can generate nice pdf with the citations I need. But I would like to change the citation format to something like Kitchin (2017) or (kitchin, 2017). I tried to use C-u before pressing enter in the helm bibtex buffer but nothing happened. Could you please tell me how to change the citation format?

Any help will be appreciated.

**Comment by jkitchin** [comment]
How are you opening helm-bibtex? I think what you have have to do is type C-c ] to open the citation selection buffer. If you just type M-x helm-bibtex it will not work.

**Comment by drliangjin** [comment]
Thanks for your reply.

Yes, I type C-c ] to open the citation selection buffer. Is the C-u here calling universal-argument function? Sorry I am very new to Emacs.

I am using spacemacs which binds C-u to vim-like scroll-up. I tried to set 'universal-argument to other keys, but it is still not working.

Are there other ways to change the format types in org? Many thanks again.

**Comment by jkitchin** [comment]
C-u means the prefix arg. If spacemacs changes that, you have to figure out what the equivalent key is. You can change the default cite type, but there is no other way I know of to select different types.

**Comment by drliangjin** [comment]
Thanks!

I will have a closer look into spacemacs. Meanwhile, can I use Scimax out of the box to do what I want using those default keys (C-c ] and C-u), if spacemacs doesn't work out. Of course, I will setup bib file for org-ref.

**Comment by zuo-zuo** [comment]
problem solved...thanks, John.

**Comment by 00krishna** [comment]
I just wanted to close the loop on this issue. Looks like this issue was resolved in the Spacemacs issues list:

https://github.com/syl20bnr/spacemacs/issues/9783

The solution was to use `C-u Enter` as an alternative to `C-u ] C-c`
