### ISSUE TITLE
How can I use apalike bibliographstyle?

### ISSUE THREAD

**Issue by Yevgnen** [jkitchin/org-ref#513]
Hi,

May I ask a question? How can I use apalike bibliographstyle? `bibliographystyle:apalike` seems not working.

**Comment by jkitchin** [comment]
You have to have an apalike bibliography style installed in LaTeX. See https://tex.stackexchange.com/questions/35809/how-do-i-use-apa-style-citations-with-bibtex maybe.

**Comment by Yevgnen** [comment]
It seems that I should manually define something like `org-ref-20171019.724/citeproc/csl/unsrt.el`. Shouldn't I?

**Comment by jkitchin** [comment]
What are you really trying to do? If you want html export then you may have to try to use citeproc. It isn't well supported though.

**Comment by Yevgnen** [comment]
I mainly export my notes to html blogs. When I try to do that, it tell me that file (citeproc/csl/apalike.el) not found.

**Comment by jkitchin** [comment]
There is indeed no file by that name. You would have to make one of your own. I don't know how easy that would be for apalike.

**Comment by sangjeedondrub** [comment]
`bibliographystyle:apacite` works for me.
