### ISSUE TITLE
Equation reference, no completion support.

### ISSUE THREAD

**Issue by dineshadepu** [jkitchin/org-ref#514]
Hi,

I am trying to refer an equation using org-ref. So, I did, 'C-c C-l', which prompted many option of 
referring. In which I selected eqref.

Generally it has to show all the equations available to refer. But It doesn't show any references. 
And it shows

`Link (no completion support): eqref: `

My configuration is 

```

(use-package org-ref
  :after org
  :init
  (setq reftex-default-bibliography '("~/Dropbox/Research/references.bib"))
  (setq org-ref-bibliography-notes "~/Dropbox/Research/notes/notes.org"
        org-ref-default-bibliography '("~/Dropbox/Research/references.bib")
        org-ref-pdf-directory "~/Dropbox/papers/")

  (setq helm-bibtex-bibliography "~/Dropbox/Research/references.bib")
  (setq helm-bibtex-library-path "~/Dropbox/papers/")

  (setq helm-bibtex-pdf-open-function
        (lambda (fpath)
          (start-process "open" "*open*" "open" fpath)))

  (setq helm-bibtex-notes-path "~/Dropbox/Research/notes/notes.org")
  :config
  ;; variables that control bibtex key format for auto-generation
  ;; I want firstauthor-year-title-words
  ;; this usually makes a legitimate filename to store pdfs under.
  (setq bibtex-autokey-year-length 4
        bibtex-autokey-name-year-separator "-"
        bibtex-autokey-year-title-separator "-"
        bibtex-autokey-titleword-separator "-"
        bibtex-autokey-titlewords 2
        bibtex-autokey-titlewords-stretch 1
        bibtex-autokey-titleword-length 5))

(use-package org-autolist
  :after org
  :config
  (org-autolist-mode +1))

(use-package doi-utils
  :after org)

(use-package org-ref-bibtex
  :after org)

```

**Comment by jkitchin** [comment]
The best way to refer to an equation is to type C-u C-c ]. I don't think that C-c C-l should work.

**Comment by dineshadepu** [comment]
Thanks for the quick reply. That works. 
But that fives me 

`ref:eq:delta`

But I need 
`eqref:eq:delta`

Which was an available option when I do `C-c C-l`. Many useful reference options were popped up and I could choose one among them. As you say that `C-c C-l` may not work. 
Is there any way to change `eq:` to `eqref`.

Thanks.

**Comment by jkitchin** [comment]
I believe if you type C-u before pressing return on the label you will get to choose which prefix is put in. 

If you use eqref all the time, you might try:

(setq org-ref-default-ref-type "eqref"). But note that will use eqref for figures and tables then.

**Comment by dineshadepu** [comment]
Now I get eqref in referencing. But I don't see other labels, as such figures, sections.

I have figure like this

`
  #+CAPTION: Dinesh
  #+ATTR_LaTeX: scale=0.75
  #+LABEL: fig:label
  [[file:./images/spline_W.png]]

`
And when I invoke refer command i don't see  figure label.

`  #+NAME: sec:kl_derivative_approximation
* Derivative approximation
  Similar to function approximation eqref:eq:kl_function_approximation
  <<line_2>>derivative of a function can be written as
`
When I refer to equation, I can see section's to refer, but after compiling I get `??`.

By bibiliographic style is

`
bibliography:~/Dropbox/Research/references.bib
bibliographystyle:plain
`
