### ISSUE TITLE
Patents not supported

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#516]
When I do a C-c l on the bibtex entry below, and then C-c C-l in an org file, I get a blank line.  The bibtex entry comes from JabRef, which I would guess uses the standard format for patents.

@Patent{Wegerich13predCondMonSmartSigPtnt,
  nationality = {European Union},
  number      = {EP 2 015 186 B1},
  year        = {2013},
  yearfiled   = {2002},
  author      = {Wegerich, Stephan W. and Wolosewicz, Andre and Pipke, R. M.},
  title       = {Diagnostic systems and methods for predictive condition monitoring},
  language    = {English},
  assignee    = {Smartsignal Corporation},
  address     = {Lisle, IL 60532 (US)},
  type        = {patenteu},
  day         = {13},
  dayfiled    = {11},
  month       = mar,
  monthfiled  = {#jan#},
  abstract    = {The present invention relates generally to the field of early detection and diagnosis of incipient machine failure
or process upset. More particularly, the invention is directed to model-based monitoring of processes and machines,
and experience-based diagnostics.},
  file        = {:Wegerich13predCondMonSmartSigPtnt.pdf:PDF},
}

**Comment by jkitchin** [comment]
I think the problem is that patent is not a bibtex entry type that emacs recognizes. See bibtex-entry-alist. Maybe you should have something like:

(bibtex-set-dialect 'biblatex)

to make sure the dialect in the bib file is correct.

**Comment by notuntoward** [comment]
Ah, not org-ref at all.  Thanks!
