### ISSUE TITLE
crossref multiple figures/tables/equations

### ISSUE THREAD

**Issue by et2010** [jkitchin/org-ref#522]
Hi, John

How can I ref multiple figures? e.g. `ref:fig:1,fig:2` will refer to figure labled `fig:1` and `fig:2` respectively. After export, it should become some thing like this:

![default](https://user-images.githubusercontent.com/11584902/33322193-6bee8304-d483-11e7-9542-d0fc41f5b0bc.png)

This screenshot is from pandoc-crossref. Since I use orgmode heavily, it would be great to have this in emacs. I'd like to implement this myself, but I'm not familiar with org-ref code base. Where should I start?

**Comment by jkitchin** [comment]
I do that with code like:  see figs. ref:fig2-ref:fig4. I don't know a way to collapse refs, eg. to turn ref:fig1,ref:fig2,ref:fig3 into 1-3. If there is, it would be some latex package that would do it for you. Did I understand your question correctly?

**Comment by et2010** [comment]
Maybe we can leave the translation job to various backends? I noticed that the cite link has the desired behavior, maybe we can borrow the idea for other ref links?

Still take pandoc for example:
```md
This is a demo file for pandoc-crossref. With this filter, you can cross-reference figures (see 
[@fig:figure1;@fig:figure2;@fig:figure3]), display equations (see @eq:eqn1), tables (see [@tbl:table1]) and
 sections ([@sec:sec1; @sec:sec2; @sec:caption-attr; @sec:table-capts; @sec:wrapping-div])
```
which will be rendered as above screenshot. But if I wrote `ref:fig:1,fig:2` in orgmode, there would be a warning in minibuffer saying "NO CONTEXT FOUND".

**Comment by jkitchin** [comment]
This seems like a very hard thing to get right. For example, should ref:fig:2,fig:1 somehow get turned into 1-2? If you move the figures, then it would take more than one pass to figure out which one goes first. What about ref:fig:1,fig:2,fig:4? should that be 1-2,4?

You might be better off creating new ref links that do what you want. Even in latex, there are custom ref commands: 

https://tex.stackexchange.com/questions/371622/how-to-get-cross-references-to-multiple-figures

**Comment by sdycjsj** [comment]
Can ref links be handled the same way as citation links, i.e., `cite:key1,key2,key3`?
Currently, `ref:label1,label2` is recognized as one ref to the label `label1,label2` (thus usually not existing) rather than two refs to labels `label1` and `label2`.

I understand that this may be related to the fact that in Latex the vanilla `\ref{}` does not handle multiple labels. One possible solution is to use the `cleveref` package for latex exportation.
