### ISSUE TITLE
Is it possible to generate a .bib file of only the cited works in a .org file?

### ISSUE THREAD

**Issue by mhaffner** [jkitchin/org-ref#523]
Let's say I have a `references.bib` file with 10 works. I cite 3 of them in `my-paper.org`. I want to create a .bib file to share with colleague that only consists of the 3 works I cited. Is there a command in org-ref for this? 

If not, I'd be happy to develop one and contribute it as it would be helpful for me, but of, course, I'd like to avoid duplicate work if this has been done already. It looks like this is possible in .tex (see [here](https://tex.stackexchange.com/questions/41821/creating-bib-file-containing-only-the-cited-references-of-a-bigger-bib-file)), but I'd rather not generate a .tex just to create this sliced .bib.

**Comment by jagrg** [comment]
See org-ref-extract-bibtex-entries.

On 04 Dec 2017, Matt Haffner <notifications@github.com> wrote:

> Let's say I have a `references.bib` file with 10 works. I cite 3 of them in `my-paper.org`. I want to create a .bib file to share with colleague that only consists of the 3 works I cited. Is there a command in org-ref for this? 
>
> If not, I'd be happy to develop one and contribute it as it would be helpful for me, but of, course, I'd like to avoid duplicate work if this has been done already. It looks like this is possible in .tex (see [here](https://tex.stackexchange.com/questions/41821/creating-bib-file-containing-only-the-cited-references-of-a-bigger-bib-file)), but I'd rather not generate a .tex just to create this sliced .bib.  


-- 
Jonathan
Monthly Atmospheric CO₂: October 2017: 403.64, October 2016: 401.57
