### ISSUE TITLE
Make percent escapes in org-ref-reftex-format-citation more customizable

### ISSUE THREAD

**Issue by yuchen-lea** [jkitchin/org-ref#524]
It's great that people can customize the note style via `org-ref-note-title-format`. There are many percent escapes defined in `org-ref-reftex-format-citation`, but limited still. 

There are some fields not defined, especially if you export a calibre or zotero library to bib, for example: 'tags', 'series', 'keywords'. Is there a way to add values of these fields when adding new note?

**Comment by jkitchin** [comment]
It is possible to add more %-escapes, but so far that is not customizable. You might see if it is possible to use org-ref-create-notes-hook to add the things you want. You could add a function to it that gets the information you want and modifies the note.

**Comment by yuchen-lea** [comment]
Thanks for your project and solution! I'm new to elisp but I'll try it out.

BTW, can I set different note style for different bib files? How about setting `org-ref-reftex-format-citation` as local variable?

**Comment by jkitchin** [comment]
I am not sure if a local variable would work. It would depend on what buffer is active when the create notes hook is called. It is worth a shot trying, it might just work.
