### ISSUE TITLE
pull year from `date` field for biblatex-formatted .bib files

### ISSUE THREAD

**Issue by ssfrr** [jkitchin/org-ref#526]
When I create a new note from org-ref (press `RET` on a `cite:...` link and select `Open notes`), the year field (`%y` in the template) is blank. I think it's because my bibliography is using BibLaTeX formatting, which uses a `date` field rather than a `year` field. Is there some setting that would resolve this, or is it a more complex change to parse the BibLaTeX `date` field and pull out the year?

This is also happening in @tmalsburg 's `helm-bibtex` package (creating notes from the `helm-bibtex` menu) but I believe that's an independent code path.

It's also very possible I'm misunderstanding the root cause, as there are many pieces involved that I have a pretty tenuous grasp on.

**Comment by jkitchin** [comment]
I am not aware of any simple setting for this.  See https://tex.stackexchange.com/questions/41257/how-to-include-date-for-each-item-in-reftex-select for a possible solution.

**Comment by tmalsburg** [comment]
We had recently added support for the date field in helm-bibtex but forgot to update the function for creating notes.  Should be fixed now.

**Comment by ssfrr** [comment]
fantastic, thanks both.

Is there a way for me to redirect `org-ref`'s note creation function to use `helm-bibtex`'s?

**Comment by jkitchin** [comment]
See the variable: org-ref-notes-function. You should be able to use that to do it.

**Comment by ssfrr** [comment]
That's just what I was looking for, and there's even an example of doing it in the documentation! Thanks a lot.
