### ISSUE TITLE
All actions from helm menu insert citation rather than open pdfs etc

### ISSUE THREAD

**Issue by jdtonkin** [jkitchin/org-ref#527]
I asked this at helm-bibtex repo, but now i realised this is the correct place for it. 

No matter what I press (i.e. Return, C-j, F1, Tab) in the org-ref helm menu when called from C-c ] or M-x helm-bibtex, the result is an inserted citation. Tab doesn't bring up the options either. I want to be able to get the pdf, go to associated notes etc. from there. Any ideas why this is happening? I'm on a mac, with latest melpa version of org-ref and helm-bibtex as a dependency. 

I should note that when I click on the citation that is inserted, it brings up all the helm-bibtex/org-ref options and I can open the pdf from there. It's just the options in the main helm menu when I call it from C-c ].

This is the relevant stuff in my init:

(setq reftex-default-bibliography '("~/gdrive/Research/org/references/articles.bib"))

(setq org-ref-bibliography-notes "/gdrive/Research/org/references/articles.org"
org-ref-default-bibliography '("/gdrive/Research/org/references/articles.bib")
org-ref-pdf-directory "~/gdrive/Research/org/references/pdfs/")

  (setq bibtex-completion-bibliography '("~/gdrive/Research/org/references/articles.bib")
    bibtex-completion-library-path '("~/gdrive/Research/org/references/pdfs")
)

;; open pdf with system pdf viewer (works on mac)
(setq bibtex-completion-pdf-open-function
(lambda (fpath)
(start-process "open" "open" "open" fpath)))

**Comment by jdtonkin** [comment]
Got it! Sorry about this. My issue. I forgot that when I set up helm a long time ago, I remapped tab as follows: (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action). So now tab works as it should in the helm-bibtex menu.

**Comment by jdtonkin** [comment]
By the way, I wanted to say a quick thanks for such an amazing resource! This has completely changed the way I work with the literature. So, thanks a lot!

**Comment by jkitchin** [comment]
That is great to hear! Thanks!
