### ISSUE TITLE
Changing the display of a citation to show the article title

### ISSUE THREAD

**Issue by 00krishna** [jkitchin/org-ref#528]
Hello Prof. Kitchin. Thanks so much for developing the `org-ref` package. The package is great. 

So my question was whether there was a way to change how a citation link is displayed in an org file so that the article/book title is displayed instead of just the citation bibtex label. 

Right now when I add a citation it looks like in the org file:
```
cite:Short2010
citetitle:Nicolis2015
```

But what I would to have the article title displayed either instead of the bibtex label or in addition to it. So perhaps something like:

```
cite:Dissipation and displacement of hotspots in reaction-diffusion models of crime.
```
 
or
```
cite:Short2010:Dissipation and displacement of hotspots in reaction-diffusion models of crime.
```

I was looking at the `org-ref-cite-types` but that did not seem to be what I needed. Any suggestions?

**Comment by jkitchin** [comment]
That is not possible with org-ref.  you could do [[cite:Short2010][Dissipation and displacement of hotspots in reaction-diffusion models of crime]], but you may run into export issues since that format is used for pre/post text in citations.

Why do you want the title? you can see the reference in the minibuffer if your cursor is on a link, or as a tooltip if you hover your mouse over it.

**Comment by 00krishna** [comment]
Oh right, I see the issue. The idea I was going for was this. I have been using orgmode to track project and [tasks](http://doc.norang.ca/org-mode.html). So I was trying to setup a workflow for tracking research project in orgmode. 

So I saw a really nice picture of what a decent org project structure would look like. 
![image_thumb](https://user-images.githubusercontent.com/2063593/34016412-a5495930-e0d6-11e7-8583-5998ea8b431b.png)

The idea is that I could create a citation like a TODO. The title would just give me a way to identify the article I am working on instead of just the short bibtex label. But the advantage is that by using the bibtex citation in the TODO, I could link to the actual bibtex citation and to the notes file as well. 

I think the alternative would be just to use an org-capture template to pull the title of the article into a TODO, which is fine. I suppose I would just need to include the actual article org-ref citation in the TODO to get the connections to the bibtex and notes files.

**Comment by jkitchin** [comment]
Depending on how often you do this, you could put the cite link in, and make the headline a TODO with shift-rightarrow. then click on the cite link (or if you have C-o bound to open the link type that) and you can copy a formatted string (for me I press f, but in the helm backend you might press tab and see what action it corresponds to). you can paste right after it. That is pretty close to what I do for the application you describe.

**Comment by 00krishna** [comment]
Great. I can follow what you suggested. Should work just fine. Thanks for your help on this. And thanks again for developing the package. It really does make so many things easier.

**Comment by jkitchin** [comment]
No problem. I always appreciate hearing org-ref is helpful!
