### ISSUE TITLE
Make this work with accented letters, for all export options

### ISSUE THREAD

**Issue by cpaulik** [jkitchin/org-ref#53]
I don't know if this is even possible, but a Bibtex entry like this:

```
@article{hornavcek2012potential,
  title={Potential for high resolution systematic global surface soil moisture retrieval via change detection using Sentinel-1},
  author={Horn{\'a}{\v{c}}ek, Michael and Wagner, Wolfgang and Sabel, Daniel and Truong, Hong-Linh and Snoeij, Paul and Hahmann, Thomas and Diedrich, Erhard and Doubkov{\'a}, Marcela},
  journal={Selected Topics in Applied Earth Observations and Remote Sensing, IEEE Journal of},
  volume={5},
  number={4},
  pages={1303--1311},
  year={2012},
  publisher={IEEE}
}
```

formats to:

```
- Horn\'a\vcek, Michael, Wagner, W., Sabel, D., Truong, H., Snoeij, P., Hahmann,
  T., Diedrich, E., Doubkov\'a, Marcela, .. (2012). Potential for high
  resolution systematic global surface soil moisture retrieval via change
  detection using sentinel-1. Selected Topics in Applied Earth Observations and
  Remote Sensing, IEEE Journal of, 5(4), 1303–1311.
```
when exporting to html, or inserting a formatted reference into the buffer.
It works for export to PDF.

It should look like 

```
Hornáček, M., W. Wagner, D. Sabel, H.-L. Truong, P. Snoeij, T. Hahmann, E. Diedrich, and M. Doubková
2012. Potential for high resolution systematic global surface soil moisture retrieval via change detection
using sentinel-1. Selected Topics in Applied Earth Observations and Remote Sensing, IEEE Journal of,
5(4):1303–1311.
```

**Comment by cpaulik** [comment]
Or should this rather be a helm-bibtex issue?

**Comment by jkitchin** [comment]
I am not sure which package this falls into, if you are selecting that from helm-bibtex it is probably a helm-bibtex issue. This would be tricky to fix I think, and would require a large lookup table of regular expressions for the latex representations and replacement texts. Although that is nearly the inverse of this table https://github.com/jkitchin/org-ref/blob/master/jmax-bibtex.el#L285.

On the other hand, we could create a function in org-ref for this, and add it as an action for helm-bibtex easily enough. I won't have time for that until probably December though :(

**Comment by jkitchin** [comment]
by the way it works for pdf because you have latex code that is converted to the right characters.

**Comment by tmalsburg** [comment]
Yeah, this is difficult to fix this one because helm-bibtex would basically need to interpret LaTeX.  However, in your case there is a trivial fix: instead of `Horn{\'a}{\v{c}}ek` you can simply write `Hornáček` because recent LaTeX versions understand Unicode.  Just tested it with TeXLive.  :-)

**Comment by jkitchin** [comment]
That's true, I still have old habits from times that didnt undertand unicode ;) I have made it a habit to remove non-ascii characters from my bibtex files.

**Comment by tmalsburg** [comment]
To my knowledge, the only place where you can't use Unicode are BibTeX keys but that's not really a problem.

**Comment by cpaulik** [comment]
Ok, thanks. Now I just have to go through my bibtex files and fix all the names :expressionless:

**Comment by tmalsburg** [comment]
@cpaulik If you want to attempt a pull request for helm-bibtex, I'm happy to provide guidance and feedback.  Alternatively, you can of course automatize the conversion of your BibTeX files using search and replace.  Shouldn't be that much work.
