### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dieter-wilhelm** [jkitchin/org-ref#531]
I cloned the org-ref added the directory to the load-path but after evaluating
(require 'org-ref) I'm getting the backtrace below:

Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "f")
  require(f)
  eval-buffer(#<buffer  *load*-797413> nil "/appl/tools/org-ref/org-ref/org-ref-core.el" nil t)  ; Reading at buffer position 1250
  load-with-code-conversion("/appl/tools/org-ref/org-ref/org-ref-core.el" "/appl/tools/org-ref/org-ref/org-ref-core.el" nil t)
  require(org-ref-core)
  eval-buffer(#<buffer  *load*> nil "/appl/tools/org-ref/org-ref/org-ref.el" nil t)  ; Reading at buffer position 1582
  load-with-code-conversion("/appl/tools/org-ref/org-ref/org-ref.el" "/appl/tools/org-ref/org-ref/org-ref.el" nil t)
  require(org-ref)
  eval((require (quote org-ref)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by jkitchin** [comment]
You should probably install it from MELPA which will take care of all the dependencies. You are missing the f.el library here, and probably some others that org-ref depends on. If you don't want to do that, you may be able to install the dependencies manually. See https://melpa.org/#/org-ref for the list.

**Comment by dieter-wilhelm** [comment]
Thank you for the quick response!
Fair enough, I guess it's best to give Melpa a try.

Well, in your installation instructions and in the README you're telling about two ways of installing org-ref without any hint of missing dependencies, so  I was somehow mislead to believe that installing from GitHub is a self contained alternative to Melpa. And probably because of using DuckDuckGo I couldn't see any hints about the usage of (require 'f), sorry for the noise.

**Comment by jkitchin** [comment]
I can see how you might find that misleading, but if you install packages manually you have to read the source to see what is required usually. In the main package file the requirements are listed in the standard place for elisp libraries, e.g. https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L9 which lists those requirements. I have updated the README to be more explicit about that. Thanks for letting me know about the issue.

**Comment by dieter-wilhelm** [comment]
org-ref is working now for me, installed it via Melpa.

And thank you very much for mentioning the dependencies in the README.org
