### ISSUE TITLE
Reference code displayed when exporting to LibreOffice

### ISSUE THREAD

**Issue by ghost** [jkitchin/org-ref#532]
Hi there... my first attempt to use bibtex in a LibreOffice document exported through org...

For example, I'm seeing this citation in the footnote:

```
[openu.00001129119920101], יחידה 5, עמ׳ 14 
```

The comment is in Hebrew.

The bibtex entry I have there is:

```
@book{openu.00001129119920101,
  Author =       {ארליך, חגי and ישראלי, עמיחי},
  ISBN =         9650600736,
  Publisher =    {תל אביב :האוניברסיטה הפתוחה,תשנ"ב 1992 -תשס"ג 2003},
  Title =        {המזרח התיכון בין מלחמות העולם.},
  URL =
                  {http://ezproxy.openu.ac.il.elib.openu.ac.il/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=cat00397a&AN=openu.000011291&site=eds-live},
  Year =         1992,
}
```

**Comment by jkitchin** [comment]
I don't understand what you are trying to do. Can you put a minimal org file that you are using, and how you get from it to the result?

Support for odt export is pretty limited. It is basically a plain ascii export, and the only formatting control there is is through the org-ref-bibliography-entry-format variable.

 I don't get the same thing you do. What I see is:

![screen shot 2017-12-29 at 7 15 13 am](https://user-images.githubusercontent.com/1610070/34440158-10f5271c-ec68-11e7-8833-652fc15cf8d5.png)

from this org file and a refs.bib file containing your entry:

```
* odt test

  citeme cite:openu.00001129119920101

bibliography:refs.bib
```
