### ISSUE TITLE
is org-ref compatible with markdown mode?

### ISSUE THREAD

**Issue by mlinchitstest** [jkitchin/org-ref#535]
Markdown mode allows you to use markdown in org mode. Citations are prefixed with @ instead of cite:.

What functionality can you get out of org-ref when writing markdown?

**Comment by jkitchin** [comment]
There is probably not much functionality that can be gotten out of org-ref. It relies on the org machinery a lot to handle links, and that isn't available in markdown mode. It is possible to setup helm-bibtex to insert the @citations in markdown format, but they won't be functional links like they are in org-mode.
