### ISSUE TITLE
change citations to bracketed instead of superscripted

### ISSUE THREAD

**Issue by tarihatari** [jkitchin/org-ref#537]
Hi,
in my Latex export, I'm trying to make my standard citations look like the ones in your [Introduction to org-ref](https://www.youtube.com/watch?v=2t925KRBbFc) video on Youtube, (in square brackets, [1],[2] etc.), but I only get them like those in your [article](http://kitchingroup.cheme.cmu.edu/blog/category/citations/), as a superscript.

How can I fix this? I found nothing about it in the documentation... I already tried the different citation styles like citep and so on, but it has no effect.

I would be very thankful for a hint!

**Comment by jkitchin** [comment]
If you exporting to LaTex,  then this is controlled by the bibliographystyle (not the citation types). You could try:

bibliographystyle:unsrt

for example. It could depend on the specifics of your bibtex setup, e.g. if you use bibtex, and natbib (https://www.sharelatex.com/learn/Natbib_bibliography_styles), and if you specified options to those in a latex_header or if you use biblatex.

I would need more details on your document setup to say more.

**Comment by tarihatari** [comment]
Thanks a lot, that helped!
In my scimax-org.el, ("numbers,super,sort&compress" "natbib" nil), are set as default options and package to use. Changing "super" to "squares" in the user.el, fixed it.
