### ISSUE TITLE
Replace helm with ido while referring equations.

### ISSUE THREAD

**Issue by dineshadepu** [jkitchin/org-ref#547]
Hi,

While I try to refer equations, I invoke org-ref-refer, which pops up a buffer with all the available 
equations, figures and labels. But It uses helm for matching. As helm doesn't have fuzzy match, it is a 
little difficult to type names in order. Is there a way to replace this search with ido.

Thanks.

**Comment by jkitchin** [comment]
I don't think so. What command are you using for this? I don't know an org-ref-refer.

See https://github.com/emacs-helm/helm/wiki/Fuzzy-matching though. helm should definitely have fuzzy matching.
