### ISSUE TITLE
Please remove debugging line 1517 in org-ref-core.el introduced with commit 388d178

### ISSUE THREAD

**Issue by myshevchuk** [jkitchin/org-ref#548]
In the very last commit on line 1517, `(message "%s - %s" label (org-ref-get-labels)) ` causes significant slowdown when opening large files; it also spams the `*Messages*` buffer. As it was  introduced for debugging purposes obviously, I believe it can be safely removed.

**Comment by johnrkitchin** [comment]
Oops. Sorry for leaving that in. I am traveling now and will remove it on Saturday.

**Comment by myshevchuk** [comment]
Thank you!
