### ISSUE TITLE
Emacs hangs after org-ref looks for pdf

### ISSUE THREAD

**Issue by jdtonkin** [jkitchin/org-ref#549]
Hi John,
Just started having trouble with emacs hanging when org-ref looks for a pdf online. I just updated all my emacs packages. This is the first time it has happened and seems to be happening for elsevier journals only, I think. It fetches the bib file fine and then hangs when trying to fetch the pdf. Happens when using both doi search and crossref search. 
Not sure what the error message is as I have to force quit emacs...
Cheers,
Jono

**Comment by johnrkitchin** [comment]
Can you just C-g out of the pdf lookup? That is what I usually do.

**Comment by jdtonkin** [comment]
Now I feel silly! Yes! Thanks for being so efficient. 
The message is simply: error in process filter: Could not create connection to linkinghub.elsevier.com:443

**Comment by johnrkitchin** [comment]
No worries. That sometimes happens if it can’t authenticate. One of these days I want to make that process asynchronous with a time out to avoid that issue.
