### ISSUE TITLE
modifying org-ref-extract-bibtex-entries behavior

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/org-ref#554]
I have two suggestions. I will write it here instead of open a pull request.

Te first is about the function `org-ref-extract-bibtex-entries`. Maybe there is a reason for this, but currently it extracts the citations in the current buffer and put it in a block inside the same current buffer wrapped in a text block. I think it should wrap it in a bibtex block. That is, it can be modified from 
```
#+BEGIN_SRC text
...
#+END_SRC"
```
to 
```
#+BEGIN_SRC bibtex
...
#+END_SRC
```

The second is to extract the current citations directly to a new file. Here it is:

```
;; new function modified to put the bibtex citations in a new .bib 
(defun org-ref-extract-bibtex-to-file (bibfile)
  "Extract all bibtex blocks in buffer to BIBFILE.
If BIBFILE exists, append, unless you use a prefix arg (C-u), which will clobber the file."
  (interactive
   (list (read-file-name "Bibfile: " nil nil nil
			 (file-name-nondirectory
			  (concat (file-name-sans-extension
				   (buffer-file-name))
				  ".bib")))))

  (let* ((bibtex-files (org-ref-find-bibliography))
	 (keys (reverse (org-ref-get-bibtex-keys)))
	 (bibtex-entry-kill-ring-max (length keys))
	 (bibtex-entry-kill-ring '()))

    (save-window-excursion
      (cl-loop for key in keys
	       do
	       (bibtex-search-entry key t)
	       (bibtex-kill-entry t)))

    (with-temp-file bibfile
      (insert (mapconcat
		     'identity
		     bibtex-entry-kill-ring
		     "\n\n"))))
)
```

**Comment by jkitchin** [comment]
Sounds reasonable. Thanks for the suggestion and suggested code. I have pushed an adaptation of it that does what you want I think.

**Comment by DiogoFerrari** [comment]
Great ! Thanks.
