### ISSUE TITLE
Emacs becomes unresponsive when installing org-ref

### ISSUE THREAD

**Issue by alecshaw** [jkitchin/org-ref#555]
While installing org-ref through MELPA, Emacs becomes unresponsive altogether. The minibuffer simply reads `Compiling .../org-ref-20180310.1908/doi-utils.el...`. Trying to install a day before, the minibuffer would read an identical line, except the end: `.../pdf-tools.el...`.

`top` shows `Emacs-x86_64` using 98%~ of the CPU, and 17M/16G free physical memory.

I can't figure out if I've done something wrong.

Possibly related issues: https://github.com/jkitchin/org-ref/issues/552, https://github.com/jkitchin/org-ref/issues/468.

macOS 10.13.3
GNU Emacs 25.3.1

**Comment by jkitchin** [comment]
I haven't been able to reproduce this on Mac or Linux today.

**Comment by alecshaw** [comment]
Alright. Interestingly, `org-ref` is now listed as `installed` under the package list. I'm going to try and get it working. I'll close this for now and come back to it if I discover anything meaningful. Thanks for your reply.

**Comment by alecshaw** [comment]
Just an update. Tried updating `org-ref` today to `20180321.724`, and Emacs hangs again, just showing `.../doi-utils.el...`.

**Comment by jkitchin** [comment]
I still can't reproduce this on any of my machines or in the Travis CI tests.
