### ISSUE TITLE
`org-ref-key-in-file-p` returns `nil` if entry type is "report"

### ISSUE THREAD

**Issue by ssfrr** [jkitchin/org-ref#556]
I was digging into an issue where pressing `RET` on some entries gave an error, and got far enough to realize the issue is that `org-ref-key-in-file-p` wasn't finding the key properly if the entry type is `@report`. Apparently when I export from Zotero using the "better-biblatex" exporter it creates these `@report` entries. For now I'm just working around it by using the "better-bibtex" exporter instead, which creates `@techreport` entries instead (which seem to work fine).

Here's a MWE - bibfile contents:

```bibtex
@inproceedings{prusa_phase_2017,
  title = {Phase {{Vocoder Done Right}}},
  url = {http://www.eurasip.org/Proceedings/Eusipco/Eusipco2017/papers/1570343436.pdf},
  booktitle = {Proc. 25th {{European Signal Processing Conference}} ({{EUSIPCO}}–2017)},
  date = {2017},
  author = {Průša, Zdeněk and Holighaus, Nicki},
  file = {/home/sfr/.zotero/zotero/0nphbwj9.default/zotero/storage/V5U59GPR/Pruša_Holighaus_2017_Phase Vocoder Done Right.pdf}
}

@report{van_velthoven_primer_2014,
  title = {A Primer on the Theory of Frames},
  url = {https://pdfs.semanticscholar.org/2052/67ba00fe6b1c845e88fc9e038c89167ccee2.pdf},
  date = {2014},
  type = {primer},
  author = {van Velthoven, Jordy},
  options = {useprefix=true},
  file = {/home/sfr/.zotero/zotero/0nphbwj9.default/zotero/storage/F8GHFXEC/van Velthoven_A primer on the theory of frames.pdf}
}
```

```elisp
; this returns `1`, the correct position
(org-ref-key-in-file-p "prusa_phase_2017" "~/Desktop/test.bib")
; this returns `nil`
(org-ref-key-in-file-p "van_velthoven_primer_2014" "~/Desktop/test.bib")
```

**Comment by jkitchin** [comment]
@report is not a valid bibtex type, which is why it doesn't get found. @techreport is a valid bibtex type. It might be a biblatex type, and if that is the case you might need to check the bibtex-dialect is getting set correctly for biblatex.
