### ISSUE TITLE
org-ref should require htmlize

### ISSUE THREAD

**Issue by kaushalmodi** [jkitchin/org-ref#557]
Hello,

It looks like the `org-ref-format-cite` function requires the `htmlize` package to be installed and loaded. Even if the package is installed, an Org export would fail if org-ref is triggered without first requiring htmlize. 

I don't use this package, but someone using org-ref, when exporting using ox-hugo faced this issue (because unlike ox-html, ox-hugo does not call any htmlize-auto-loading functions); details: https://github.com/kaushalmodi/ox-hugo/issues/145#comment-373978101.

Proposed solution:

1. Add `htmlize` to the `;; Package-Requires:` line.
2. Require `htmlize` explicitly in the beginning of `org-ref.el`. If only that one function needs `htmlize`, then require it just there, within that function in the very beginning. 

Thanks. 

/cc @emacsun

**Comment by jkitchin** [comment]
Hopefully this is fixed. Thanks for the solution.
