### ISSUE TITLE
org-ref-get-bibtex-entry-md need to add info as its argument

### ISSUE THREAD

**Issue by kaushalmodi** [jkitchin/org-ref#558]
Hello,

When exporting an Org document with `ox-md` or one of the derived exporters like `ox-hugo`, it fails, because `org-ref-get-bibtex-entry-md` is trying to access `info` variable, which is not passed to it as an argument.

Org 9.x does not have `info` as a global variable, so it would not work.. that var needs to be explicitly passed in as an arg to the calling function.

See https://github.com/kaushalmodi/ox-hugo/issues/145#issuecomment-374000252 for details.

/cc @emacsun I will close this issue on ox-hugo repo, as the reported issues are localized to org-ref.

**Comment by kaushalmodi** [comment]
@emacsun I haven't tested, but you should be able to recreate this issue even if you export that Org document containing `cite:` link using **`ox-md`** (and not `ox-hugo`).

**Comment by jkitchin** [comment]
I think I have disabled that code. it is strange, it worked fine for me. I am traveling now, when I return I will try looking into a better solution.
