### ISSUE TITLE
org-latex-prefer-user-labels is void in org-mode from emacs 25.3.2

### ISSUE THREAD

**Issue by unhammer** [jkitchin/org-ref#560]
https://code.orgmode.org/bzg/org-mode/commit/4bbc054bd252b975f483a29515495a9af9329c71 seems to have come in 8.3, while 25.3.2 under Ubuntu 17.10 has 8.2.

Maybe org-ref should `(unless (boundp 'org-latex-prefer-user-labels) (setq org-latex-prefer-user-labels nil))` or something.

**Comment by jkitchin** [comment]
does commit 0376cb0 solve this for you?

**Comment by unhammer** [comment]
Seems to work! I'll close then :)
