### ISSUE TITLE
Symbol's function definition is void: org-link-set-parameters

### ISSUE THREAD

**Issue by afarah1** [jkitchin/org-ref#561]
First that Melpa install thingy doesn't work, IIRC it's obsolete, I couldn't find the SO question on it. You should use: https://melpa.org/#/getting-started

Then, after installing through Melpa and adding `(require 'org-ref)` to my init file I get:

````
Symbol's function definition is void: org-link-set-parameters
````

Removing that `require` "solves" it, i.e. not using org-ref "solves" it.

GNU Emacs 25.3.1

**Comment by jkitchin** [comment]
I am not aware of MELPA being obsolete. We use it every day.

It sounds like you are using org 8, and org-link-set-parameters is defined in org 9.

**Comment by ZzAntares** [comment]
Just for the record, I think this is not an issue, just today I had this error but because I use `straight.el` it turns out `org-ref` was loaded before org 9 itself. This only happened on a fresh startup, once I restarted emacs the error went away.
