### ISSUE TITLE
org-ref should list helm-bibtex as a dependency

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#562]
I just updated my emacs packages and then said "yes" when emacs asked if I wanted to run package-autoremove.   The result was that emacs restart failed, with the following error message:

```
error: Unable to activate package ‘org-ref’.
Required package ‘helm-bibtex-2.0.0’ is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
After I manually installed helm-bibtex, then I got a new and similar error about pdf-tools.

It seems that org-ref must somehow declare that it requires helm-bibtex and pdf-tools

**Comment by jkitchin** [comment]
It does declare that here: https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L9

**Comment by notuntoward** [comment]
I guess I don't understand how the emacs package-autoremove feature works.  I thought that it would be tracking requires, and noting the dependency.  Is there anyway that org-ref can prevent package-autoremove from removing needed packages?

**Comment by notuntoward** [comment]
Whoops, I didn't mean to close the issue, just to leave comment.

**Comment by jkitchin** [comment]
I don't know anything about package-autoremove. AFAIK org-ref uses the standard method for noting dependencies.

**Comment by jabranham** [comment]
I think the standard method for multi-file packages would be to have a file `org-ref-pkg.el`

more info: `(info "(elisp) Multi-file Packages")`

**Comment by jkitchin** [comment]
I tried to add this file, let me know if it works and/or causes a problem. There is duplicated information in the header of org-ref.el now. I am not sure I can delete that or not.

**Comment by notuntoward** [comment]
After updating to this version of org-ref, I no longer get the "unused packages" message, and even if I manually do M-x package-autoremove, neither helm-bibtex nor pdf-tools are on the remove list.

There are still auto-remove problems coming from other packages, but for org-ref, it looks like the problem is fixed.

Thanks!

**Comment by jkitchin** [comment]
That sounds like good news. I am going to mark this closed.
