### ISSUE TITLE
Org-ref breaks Helm-Bibtex entries search view

### ISSUE THREAD

**Issue by adam52** [jkitchin/org-ref#563]
Here is a screenshot of the Helm-Bibtex entries search view without org-ref installed:

![wout-org-ref](https://user-images.githubusercontent.com/1281353/37874677-ad79f5a2-302b-11e8-80b3-604e3c9d21d3.jpg)

and here is a screenshot after installing org-ref and including `(require 'org-ref)` in my `init.el` file:

![worg-ref](https://user-images.githubusercontent.com/1281353/37874684-cca3d006-302b-11e8-912d-c25a5e2a0d8d.jpg)

Both packages and dependencies are installed through the Emacs packaging system... any ideas?

Thanks!

**Comment by adam52** [comment]
Okay, I fixed it! All I had to do was require and configure org-ref in my init.el file **before** I loaded and configure helm-bibtex :)

**Comment by jagrg** [comment]
You can try tweaking bibtex-completion-display-formats.

On 25 Mar 2018, adam52 <notifications@github.com> wrote:

> Here is a screenshot of the Helm-Bibtex entries search view without org-ref installed:
>
> ![wout-org-ref](https://user-images.githubusercontent.com/1281353/37874677-ad79f5a2-302b-11e8-80b3-604e3c9d21d3.jpg)
>
> and here is a screenshot after installing org-ref and including `(require 'org-ref)` in my `init.el` file:
>
> ![worg-ref](https://user-images.githubusercontent.com/1281353/37874684-cca3d006-302b-11e8-912d-c25a5e2a0d8d.jpg)
>
> Both packages and dependencies are installed through the Emacs packaging system... any ideas?
>
> Thanks!


-- 
Jonathan
Monthly Atmospheric CO₂: February 2018: 408.35, February 2017: 406.42
