### ISSUE TITLE
Getting references work inside 'begin{align*}'

### ISSUE THREAD

**Issue by arjunsanjeev7** [jkitchin/org-ref#565]
The references I make inside a `\begin{align*}` environment are not working.
For example, `eqref:<equation-name>`, or `ref:<lemma-name>`
How can I get them working?

**Comment by jkitchin** [comment]
Can you provide a small example org snippet that doesn't work?

**Comment by arjunsanjeev7** [comment]
Lemma definition:
`#+name: lemma1`
`#+begin_lemma`
`Sample lemma.`
`#+end_lemma`

Making reference to the lemma:
`\begin{align*}`
`a+b=c (From ref:lemma1)`
`\end{align*}`

**Comment by jagrg** [comment]
You are mixing org-mode and latex. To solve your problem, you could either change ref:lemma1 to \ref{lemma1}, like this:

```
#+begin_src latex
\begin{align*}
a+b=c (From \ref{lemma1})
\end{align*}
#+end_src
```

or use plain org-mode, and keep ref:lemma1 as you had before, like this:

```
#+begin_align*
a+b=c (From ref:lemma1)
#+end_align*
```

I would go for the second option. This way you are not limited to latex. In any case, if you are working with source code, I would recommend wrapping the code inside a source code block, as I did in the first example.
