### ISSUE TITLE
Closing a tag missing in org-ref-get-bibtex-entry-html

### ISSUE THREAD

**Issue by lechten** [jkitchin/org-ref#566]
In commit 82f2860 you added an opening `a` tag with `name` attribute but no closing tag. Thus, HTML is malformed. What is that element good for, where should it end? (Note that the bib entry may contain a URL, and nesting of `a` elements is forbidden.)

Personally, I don't need that additional element. What about making it customizable?

**Comment by jkitchin** [comment]
That is a named anchor, so you can jump to it from somewhere in a document. I don't think it is possible to get a nested <a> element from this. Do you have a suggestion for a defcustom? It could be tricky, since it will affect how cite links are exported too.

**Comment by lechten** [comment]
I export URL fields of BibTeX files to HTML. So the named anchor needs to be closed before the URL starts. But where?
Note that the key is surrounded by an anchor with id, which can be used as link target. What do you gain by the additional named anchor?

**Comment by jkitchin** [comment]
I think the tag is closed, which hopefully is a bandaid to your issue. I will have to study it a little more to see if it makes sense to remove this anchor here. It might be redundant as you point out, but I am traveling at the moment and don't have time to track down the whole picture today.

**Comment by lechten** [comment]
Thanks for the quick fix! 
Please feel free to close this after your return.

**Comment by lechten** [comment]
I just saw that https://validator.w3.org/ reports this for name attributes on anchors: 
"The name attribute is obsolete. Consider putting an id attribute on the nearest container instead."

**Comment by jkitchin** [comment]
That is true, but this isn't reflected across all browsers yet. At the moment, this works for me, and it is a low priority to change it. Once Chrome/Safari stop working, it will become a higher priority :)
