### ISSUE TITLE
Export to LaTeX and HTML with umlauts in bib files

### ISSUE THREAD

**Issue by lechten** [jkitchin/org-ref#569]
Hi, I export org files to HTML and to LaTeX. When author names contain umlauts (e.g., Özsu), I can either use unicode umlauts in the bib file or TeX sequences. Umlauts are exported properly to HTML but LaTeX export fails (for names starting with umlauts as the example above). TeX sequences work with LaTeX export but are exported as-is to HTML.

Is there a simple fix, which I'm overlooking? Alternatively, one could add replacement code to `org-ref-get-bibtex-entry-html` (generalizing the replacement of escaped "&"). I'm thinking about using `org-entities` somehow, but I am not sure. What do you think?

**Comment by jagrg** [comment]
It fails for me only if KEY contains umlauts. IOW, if I remove the accent from KEY, it works. Is this also the case for you?

**Comment by jkitchin** [comment]
What is the failure? Using unicode in latex is somewhat tricky. Do you have \usepackage[utf8]{inputenc} in the header?

**Comment by lechten** [comment]
@jagrg I removed the umlaut from the key, but the generated `bbl` file contains messed up umlauts.
@jkitchin Yes, that usepackage is there.

Here is a minimal working example:

Org file:
```
see cite:OV11
bibliographystyle:alphadin
bibliography:minimal.bib
```

`minimal.bib`:
```
@book{OV11,
  author    = {Özsu, M. Tamer and Valduriez, Patrick},
  title     = {Principles of Distributed Database Systems, Third Edition},
  publisher = {Springer},
  year      = {2011},
}
```

Run `emacs -q`, eval that:
```
(package-initialize)
(require 'org-ref)
(setq org-latex-pdf-process ; use pdflatex and bibtex for PDF
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	"bibtex %b"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
```

Press `C-c C-e l p`.  This produces the following error:

```
! Package inputenc Error: Unicode char \u 8:\GenericError {(inputenc)          
      }{Package inputenc Error: Unicode char \u8:\303V not set up for use with LaT
eX}{See the inputenc package documentation for explanation.}{Your command was i
gnored.
(inputenc) Type  I <command> <return>  to replace it with another command,
(inputenc) or  <return>  to continue without it.} not set up for use with LaTeX
.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.30 see \cite{OV11}
                    
(.//minimal.bbl

! Package inputenc Error: Unicode char \u8:\303V not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 \begin{thebibliography}{\303V11}
```

**Comment by jagrg** [comment]
I would suggest adding `#+LATEX_HEADER: \usepackage[utf8]{inputenc}` to the Org document and deleting the corresponding `.bbl` and `.aux` files before running the export dispatcher.

**Comment by jagrg** [comment]
I see the error now. It works if I use `bibliographystyle:agsm` and `\usepackage{natbib}`. I'm not sure why though. Sorry I can't think of any solution.

**Comment by jagrg** [comment]
I don't have a simple fix, but assuming `{\"O}zsu` works with latex, you can advice `org-ref-get-bibtex-entry-html` to replace the escaped character. If you have [citeproc-el](https://github.com/andras-simonyi/citeproc-el) installed, you can use `citeproc-bt--to-csl` to make the conversions for you.

```elisp
(advice-add 'org-ref-get-bibtex-entry-html :filter-return
	    (lambda (formatted-bib)
	      (citeproc-bt--to-csl formatted-bib)))
```

Another option is to play with `org-ref-nonascii-latex-replacements` to do the conversions. This is what worked for me:

```elisp
(add-to-list 'org-ref-nonascii-latex-replacements '("Ö" . "{\\\\\"O}"))

(defun my/org-ref-get-bibtex-entry-html (html-bib)
  (with-temp-buffer
    (insert html-bib)
    (goto-char (point-min))
    (while (re-search-forward "\\(\\\\['\"][a-zA-Z]\\)" nil t)
      (replace-match (car (rassoc (regexp-quote (s-wrap (match-string-no-properties 1) "{" "}"))
				  org-ref-nonascii-latex-replacements))))
    (buffer-substring-no-properties (point-min) (point-max))))

(advice-add 'org-ref-get-bibtex-entry-html :filter-return
	    (lambda (formatted-bib)
	      (my/org-ref-get-bibtex-entry-html formatted-bib)))
```

**Comment by jkitchin** [comment]
I can't reproduce your error. Your example worked fine for me with my setup. The only difference in packages I see is I use \usepackage{lmodern}.

I seem to recall that keys have to be ascii only I think. unicode in the bibtex entries seems to be fine these days, but it was not always that way. What versions of latex/bibtex are you using?

**Comment by lechten** [comment]
@jagrg Yes, agsm with natbib works for me as well. Also the `advice-add` works. Many thanks for your help! Is there any reason that this should not happen by default? (With capital letters added to `org-ref-nonascii-latex-replacements`?)

@jkitchin Inclusion of `\usepackage{lmodern}` does not make a difference for me.
My versions:
```
$ pdflatex --version
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).

$ bibtex --version
BibTeX 0.99d (TeX Live 2015/Debian)
kpathsea version 6.2.1
Copyright 2015 Oren Patashnik.
```

**Comment by jkitchin** [comment]
I don't know why the bibtex style would matter. My pdflatex/bibtex versions only differ by one version I think, I used 6.2.2 from Texlive 2016. Maybe there has been a bugfix in that.

**Comment by jagrg** [comment]
> Is there any reason that this should not happen by default? (With capital letters added to org-ref-nonascii-latex-replacements?)

This was never added to the list. In any case, I think John is right in that these replacements are becoming obsolete. Maybe we should consider upgrading to a newer version ;)

**Comment by jkitchin** [comment]
This is not consistent with what I see. I am pretty sure I only use bibtex, and it works just fine with the unicode characters with alpha and numeric bibstyles. Here are the contents of my bbl file from your example:

\begin{thebibliography}{1}

\bibitem{OV11}
M.~Tamer Özsu and Patrick Valduriez.
\newblock {\em Principles of Distributed Database Systems, Third Edition}.
\newblock Springer, 2011.
\end{thebibliography}

maybe it is a platform issue? I haven't tried any of this on windows for a while. The example above is on a Mac. I am not sure, but I think it also works like that on Ubuntu. This seems like some latex issue somewhere.

**Comment by lechten** [comment]
"\begin{thebibliography}{1}" works for me as well (but is not my example). What happens in case of the `alpha` style (or `alphadin`)?

**Comment by jkitchin** [comment]
I see the issue now. It does work fine for numeric, but I see some mangling as you report with alpha styles. So I guess is makes sense to continue replacing non-ascii chars for bibtex users. Otherwise switching to biber/biblatex. I am glad you finally found a solution in any case!
