### ISSUE TITLE
links not working on file open

### ISSUE THREAD

**Issue by mclearc** [jkitchin/org-ref#57]
I'm seeing an odd bug (at least, I think it is a bug) where the `cite:xyz` won't show as a link on newly opening the file. However, if I insert another citation next to the original one, it *will* then show as a link. I've also found that sometimes adding an extra `[` to the beginning of a `cite:xyz` entry will turn it back into a link. The extra `[` can then be deleted. Any ideas what might be causing this? Unfortunately I'm new to emacs, so this may be user error. 

I'm using GNU Emacs 24.5.1, org 8.3.1, and the  [spacemacs](https://github.com/syl20bnr/spacemacs) starter kit.

**Comment by jkitchin** [comment]
this sounds like an error related to font-lock. I don't think it is an error in org-ref. Occasionally I see this with other kinds of links, and even typing an extra space after the link and deleting it is sometimes enough to "relink" it. I am not sure what causes it or how to fix it. It is pretty rare to see for me.

**Comment by mclearc** [comment]
Thanks. It may be related to how spacemacs is handling font-lock. I'll check with them as well. If I track it down I'll let you know. Thanks for org-ref!

**Comment by jkitchin** [comment]
No problem. I doubt it has anything to do with spacemacs. I suspect it is in emacs and the jit-font lock engine.

**Comment by autosquid** [comment]
@mclearc  I think I met the same problem. Have you found out what the problem is?

**Comment by jkitchin** [comment]
what version of Emacs are you using?

**Comment by mclearc** [comment]
@autosquid I never figured this out and ended up using  [helm-bibtex](https://github.com/tmalsburg/helm-bibtex) instead.

**Comment by autosquid** [comment]
@mclearc  @jkitchin   I was using `use-package`, and the problem disappears after adding `(require org-ref)` to `:init`.  Sorry for wrong reporting.
