### ISSUE TITLE
cite inside PROPERTIES

### ISSUE THREAD

**Issue by MarkoSchuetz** [jkitchin/org-ref#570]
I'd like to use a citation inside the :PROPERTIES: where I have a :Source: 

It seems that :PROPERTIES: is skipped?!?

**Comment by jkitchin** [comment]
i am not sure what you are trying to do here. What is the issue?

**Comment by timmli** [comment]
Maybe the same issue here: I want to use org-ref citations insides the `:PROPERTIES:` drawer, but the citation is not found, that is the tooltip prints "!!! No entry found !!!". Normal links work fine.

Here is a minimal example:

    * Session 4
    :PROPERTIES:
    :SESSION_LITERATURE: [[cite:Schmidt:Wiegand:17]]
    :SESSION_PRESENTER: John Doe
    :END:

    # This link works; the one above does not.
    [[cite:Schmidt:Wiegand:17]]  

I'm using org-ref v2.

**Comment by jkitchin** [comment]
I don't think links are parsed in properties by org-mode, so that is not going to work. If you switch to v3,  it works better, as a different mechanism is used for tooltips.

**Comment by timmli** [comment]
No, it seems that links are parsed. The links in the following example work normally:

    * Session 4
    :PROPERTIES:
    :SESSION_LITERATURE: [[cite:Schmidt:Wiegand:17]]
    :SESSION_PRESENTER: John Doe
    :NEXT_SESSIONS: [[Session 5]] [[id:52ee7a2a-6551-4012-a194-0e68544dde70][Section 6]]
    :END:
    
    # This link works; the one above does not.
    [[cite:Schmidt:Wiegand:17]]   
    
    * Session 5
    
    * Session 6
    :PROPERTIES:
    :ID:       52ee7a2a-6551-4012-a194-0e68544dde70
    :END:

**Comment by jkitchin** [comment]
if you run org-element-context on the link though, it is not recognized as a link, it is some kind of node-property. that is the actual issue. They might be partially fontified, but that is not the same as them being parsed by org-mode.
