### ISSUE TITLE
Not exporting org file preamble to pdf

### ISSUE THREAD

**Issue by sbacelar** [jkitchin/org-ref#573]
When using org-ref (scimax) I can not export the preamble of my org file (e.g. title, author, date) to pdf. Note: body-only is off.

**Comment by jkitchin** [comment]
you have to add \maketitle in the place that you want the title page to appear.

**Comment by sbacelar** [comment]
Yes, now it works, but the "table of contents” comes before everything, inclusive before the title. I tried other package (based on Kieran Healy) and even without using \maketitle the preamble appears first and then the “Contents” before the body. Is it possible to obtain the same result in org-ref?

**Comment by jkitchin** [comment]
You can control that with:

#+options: toc:nil

\maketitle
\tableofcontents


that turns off the table of contents, and then allows you to put it where you want it. leave the \tableofcontents out if you don't want one at all.
