### ISSUE TITLE
bibliography not produced by org-ref unless the bibtex file is in the same directory as the org file

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#574]
It used to work with the following:
bibliography:/home/wyousef/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib
but now I have to copy the bibtex to the same folder in order to produce bibliography.  
bibliography:publications.bib

Do you guys have the same issue?

**Comment by jkitchin** [comment]
That should not be happening. Is your bibliography link regularly colored (i.e. it is not red), and if you mouse over it, does it say the file exists?

What is the output of this block in that file?:

#+BEGIN_SRC emacs-lisp
(org-ref-find-bibliography)
#+END_SRC

**Comment by jdtonkin** [comment]
I don't have a problem with the bibliography, but I do with the bibliographystyle. That is, if I want to use 'Science.bst', it has to be in the same folder as the org file. I can't link to it in a separate directory, which I can do for the .bib file. This is what the resulting tex file looks like:

\bibliographystyle{~/gdrive/Research/org/references/bst/Science.bst}
\bibliography{../../../../../org/references/articles}

So the link is working for the .bib file, but not the .bst file. Any ideas?

**Comment by johnrkitchin** [comment]
I am currently traveling away from a computer. I think this means the bst file is not installed in a place Latex can find it, so you have to have it in the current directory. This is a latex issue, not an org-ref one.

**Comment by jdtonkin** [comment]
Thanks, John. Appreciate the continuing support for this amazing resource.

**Comment by jkitchin** [comment]
You may find these helpful:

https://tex.stackexchange.com/questions/184410/add-new-bibliography-style
https://faculty.math.illinois.edu/~hildebr/tex/tips-customstyles.html
