### ISSUE TITLE
Add my own filed to org-ref-note-title-format?

### ISSUE THREAD

**Issue by yanghaoxie** [jkitchin/org-ref#578]
When using zotero to export bibtex file, we can export a filed called `file` whose content is the absolute path of the attached file. I want to add this field to my note-title, since this filed can be used to integer with `interleave`. 
I read some source code of org-ref, it seems like that `org-ref-reftex-format-citation` does not contain `file` filed.
BTW, `bibtex-completion-notes-template-one-file` support this filed, however helm-bibtex does not insert the cite part which is at the end of the title, I need this to open attached file in the note file.
Therefore, I think there are two work around:
1. insert `file` filed using org-ref
2. insert `cite` part using helm-bibtex

But, I kind of do not know how to implement this.

**Comment by jkitchin** [comment]
You can add a function to org-ref-create-notes-hook that does what you want I think. See the example in that variable that adds the cite link. You will have to get the key in the entry, then load the bibtex entry to get the file field, and then construct and insert the file link.

You might want to customize org-ref-get-pdf-filename-function instead though, so you can just click on the link and open the pdf from there.

**Comment by yanghaoxie** [comment]
Thank you very much, it turns out I can insert the `cite:${=key=}` along the title using `helm-bibtex`, which works great. I prefer `helm-bibtex`, since `org-ref` seems have some problem import title that have brace in it, e.g., {This is a {title}}, where `org-ref` will insert `This is a {title}` and `helm-bibtex` will insert `This is a title`.

**Comment by philohistoria** [comment]
@yanghaoxie just curious, have you figure out a way to let `org-ref` remove the brace? or we have to use `helm-bibtex` to achieve this? Thanks!

**Comment by yanghaoxie** [comment]
@philohistoria 
I am sorry, I did not follow what you mean. Could you please give an exmaple?

**Comment by jkitchin** [comment]
Removing braces is tricky, especially nested braces. You can always add a hook function to remove them all, but in my experience it isn't always desirable (so it isn't a default action). YMMV though, and you can add if if you want.
