### ISSUE TITLE
Does org-ref consider using CUSTOM_ID?

### ISSUE THREAD

**Issue by Compro-Prasad** [jkitchin/org-ref#581]
https://github.com/syl20bnr/spacemacs/issues/10731

**Comment by Compro-Prasad** [comment]
No comments?

**Comment by Compro-Prasad** [comment]
Mine has:
```
\section{First chapter}
\label{sec:org7002a20}
```
Any guesses what is the problem here?

**Comment by Compro-Prasad** [comment]
Ok. I think its solved.

**Comment by jkitchin** [comment]
@dangom  provided the solution in the issue you linked to. It is:

`(setq org-latex-prefer-user-labels t)`
