### ISSUE TITLE
Integration with emacs prelude

### ISSUE THREAD

**Issue by paulbrodersen** [jkitchin/org-ref#583]
[Prelude](https://github.com/bbatsov/prelude) is an enhanced emacs
distribution that is fairly popular (3k stars, half as many forks) and
that I like to use. I had some trouble integrating org-ref with it but
now everything seems to be working fine, and hence I thought it might
be good to document the necessary steps for posterity. Maybe you could
add the following to your manual and/or the installation instructions?

If you are using prelude, org-ref needs to be loaded **before**
prelude. To that end, add a file `preload.el` to the
`.emacs.d/personal/preload/` folder with your org-ref configuration,
for example:

``` emacs-lisp
(package-initialize)

(setq reftex-default-bibliography '("~/bibliography/references.bib"))
(setq org-ref-bibliography-notes "~/bibliography/notes.org"
      org-ref-default-bibliography '("~/bibliography/references.bib")
      org-ref-pdf-directory "~/bibliography/bibtex-pdfs/")

(require 'org-ref)

(provide 'preload)

;;; preload.el ends here
```

Tested with the current version of of prelude (commit b4721bf) and
org-ref (installed via MELPA) and all personal modifications disabled.

Thanks for the fantastic package!

**Comment by jkitchin** [comment]
Do you know what the issue with prelude is and why it has to be loaded before prelude? The only thing that comes to mind is related to when is org loaded.

**Comment by paulbrodersen** [comment]
Short answer: I don't know what the issue is but I also haven't looked very hard. 

The behaviour when org-ref is loaded after prelude is initialised is weird. Some org-ref functionality works: for example, it correctly recognizes my bib file ("abc.bib exists"). However, the mouse-over for existing citations only displays "!!! No entry found !!!" and the shortcut to insert a new reference doesn't work. 

The weirdest thing to my mind is that everything works just fine once I manually insert a new citation with ``org-ref-helm-insert-cite-link`: citations are found, mouse-over works, shortcut works. 

Maybe this makes more sense to you than it does to me.

**Comment by paulbrodersen** [comment]
FYI: there is an [open issue/feature request on prelude's github regarding to integrate org-ref](https://github.com/bbatsov/prelude/issues/950). Maybe you can get bbatsov (the maintainer) to chime in? The issue is pretty old though... 

I am happy to help finding the root cause but it seems to me that this is something that would take me hours whereas the two of you could probably figure it out in a minute or two.

**Comment by jkitchin** [comment]
That does sound weird, I wonder if it is due to some autoloads perhaps. I haven't seen anything like that, and it doesn't seem like it should be related to prelude.

**Comment by jkitchin** [comment]
I have added a note to the manual about this.
