### ISSUE TITLE
Can't import references 

### ISSUE THREAD

**Issue by atzbacher** [jkitchin/org-ref#589]
Hi, just started out with org-ref. Unfortunately I can't import any reference at all. 
Dragging pdf into a bibtex file results in .org/10.*/read error.
Dragging URLs displays "5 1" in Minibuffer.
And searching via pubmed-insert-bibtex-from-pmid results in a read error too. 
Emacs 26.1 on Manjaro

**Comment by jkitchin** [comment]
The drag and drop functions are not that reliable. I don't recommend them. 

What pmid did you try to use? I usually use doi-insert-bibtex-entry with a doi.

**Comment by atzbacher** [comment]
I tried pubmed-insert-bibtex-from-pmid which gave me "No conversion for type: Journal Article" despite the pmid referring to a Journal Article. I guess the string= type "JOURNAL ARTICLE" in org-ref-pubmed.el is case sensitive so I changed it to "Journal Article" which did the trick.

**Comment by jkitchin** [comment]
I see. I just pushed a fix for this. thanks for reporting it.
