### ISSUE TITLE
void-function nil error when inserting a citation

### ISSUE THREAD

**Issue by Spauldo** [jkitchin/org-ref#59]
I'm running into an issue inserting citations.

I have a bibtex file with one citation in it.  I can do 'helm-bibtex' and it finds it fine and inserts the string "cite:futurebuildings" at point, which tells me helm-bibtex is finding the citation OK.

Unfortunately, when doing C-c ] it goes through the same process as helm-bibtex but then tries to run nil as a function.

The backtrace leads to helm-bibtex-insert-citation("futurebuildings"), then runs nil(("futurebuildings")).  

Once again, I get the "Something went really wrong, and we can’t process that file.  Try again." message when I try to attach the backtrace, so I've put it at http://sarnet.mooo.com/org-error/ along with my init file for org mode.  All the files and paths for the relevant variables exist.

I'm no elisp expert, but from what I can tell, in helm-bibtex-insert-citation, format function should be set to "helm-bibtex-format-org-ref."  That's the value I get when I eval the following from my document:

(cdr (assoc major-mode helm-bibtex-format-citation-functions))

I've also tried the entire cdr expression as written in the function, in case my understanding of 'or' was mistaken.  I got the same result.

Unless I misunderstand the backtrace, the next function to be called would be (funcall format-function keys).

helm-bibtex-format-org-ref does exist as a function (I get help for it when I C-h f it anyway).

Let me know if there is any more information you need.

**Comment by Spauldo** [comment]
For clarity: I'm doing this from an org mode buffer, not a bibtex buffer.  I left that a bit ambiguous in the text above.

I should preview my comments.

**Comment by jkitchin** [comment]
Is this a recent problem that used to work? I have never seen this, and can't reproduce it on my end.

**Comment by Spauldo** [comment]
No, I first tried to use org-ref two days ago.  This is the first time I've tried to add a cite with it.

I think I'll try nuking my config and trying org-ref by itself, just in case there's something else in my config that's causing the problem.  I'll let you know the results.

Oh, and I'm on 24.4.1, 64bit Debian.

**Comment by Spauldo** [comment]
OK, nuked my config, installed el-get, then installed org-ref with basically just the configuration mentioned in the install instructions (plus some necessary load-path and el-get sync).  Same thing.

Tried installing org mode with el-get, so that I had the latest version rather than the one that comes with my version of emacs.  Still the same.

So, I tried nuking it all again, cloning dash, emacs-async, f, helm, helm-bibtex, hydra, key-chord, org-mode, org-ref, parsebib, and s, and installing them manually.  I've saved that config in that same directory as above as "nuked-init.el."  Still the same thing.  Tried with --no-site-file, just in case Debian's site file was messing it up.  Same thing.

I'm at a loss...  The only thing this configuration has in common is the org-ref and helm-bibtex config options I put in there and emacs itself.  I'll go over those options later tonight.

**Comment by jkitchin** [comment]
I am also baffled. All that C-c ] does is actually call helm-bibtex with a temporary value of helm-bibtex-bibliography. 

what function is C-c ] actually bound to?

**Comment by prtkm** [comment]
Hi John,
I seem to be having a possibly related issue after updating to the latest couple of commits. While trying to  insert a citation I get,
helm-bibtex-insert-citation: Symbol*some weird non-ascii characters*s function definition is void: nil

It seems to be working fine if I checkout the version from sept 27...

**Comment by Spauldo** [comment]
C-c ] runs the command org-ref-helm-insert-cite-link, which is an
interactive autoloaded compiled Lisp function in `org-ref.el'.

It is bound to C-c ], <menu-bar> <Org> <org-ref> <Insert citation>.

(org-ref-helm-insert-cite-link ARG)

org-ref function to use helm-bibtex to insert a citation link.
With one prefix arg, insert a ref link.
With two prefix args, insert a label link.

**Comment by jkitchin** [comment]
Thanks for the pointer Prateek. I just pushed a minor fix I think to that commit. I think the issue was arising because I was looping through buffers to find .bib files and save them, but that was changing the current buffer. that should be fixed now. let me know if it works for you now.

**Comment by Spauldo** [comment]
I pulled down the changes and gave it a shot, with both my regular config and the no-el-get config with just org-ref related stuff.

It does insert a cite now, but it's just "cite:futurebuildings" without the link formatting.  In the message area I get the message "!!! No entry found !!!"

The citation doesn't get added at the bottom, just the text above.

**Comment by Spauldo** [comment]
For clarity: cite:futurebuildings is the exact literal text in the file (I checked with less) - no brackets or anything.  Syntax highlighting runs it together with the following word.

**Comment by jkitchin** [comment]
cite:futurebuildings is the only text that should be inserted. You have to export to latex or html to get actual entries.

Maybe you could send me a minimal example org and bib file you are using.

**Comment by Spauldo** [comment]
I've put references.bib and pendulum.org at http://sarnet.mooo.com/org-error/

I'm running emacs using the nuked-init.el also located in that directory.

references.bib is the file referred to in helm-bibtex-bibliography, reftex-default-bibliography, and org-ref-default-bibliography.

I was under the impression that the literal text inserted was something like [[cite:blah]blah] (not exactly that, but similar).  If that's not the case, then disregard that bit.

**Comment by jkitchin** [comment]
You also need a space to separate cite:futurebuildings from the first word. Normally I would put citations at the end of a sentence on the left side of punctuation. You need a space before cite links also, e.g.

democracycite:futurebuildings.  should be "democracy cite:futurebuildings". bibtex/natbib does the right thing for me in removing this space if you are using superscript styles.

If you prefer to do it this way, i.e. like \cite commands in latex, you need to customize the function for citation formats so they have the [[]] link syntax around them. see https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L3287 to see what the function is, and how you might customize it.

That link syntax is a little harder to manage for adding new cites I think, and it isn't used right now in org-ref.

**Comment by Spauldo** [comment]
Sorry for the delay.  It's been a busy few days.

The update seems to have fixed things for me.  Thanks for the help.
