### ISSUE TITLE
Changing the key of ALL entries

### ISSUE THREAD

**Issue by DrWaleedAYousef** [jkitchin/org-ref#592]
When I do C-c C-c or (C-u C-c C-c) it both cleans and create/change the key of AN entry. However, `clean-entries` ONLY cleans all entries without changing the key. Is there an option (like C-u C-c C-c) that enforces the key to be changed in ALL entries at once. Thanks so much

**Comment by jkitchin** [comment]
I typically put a line like this in my bib file:

`% (bibtex-map-entries (lambda (key start end) (org-ref-clean-bibtex-entry t)))`

Then put my cursor at the end of the line and type C-x C-e.

**Comment by DrWaleedAYousef** [comment]
Thanks so much; I tried it by it gave me compilation error:

Debugger entered--Lisp error: (wrong-number-of-arguments #f(compiled-function () (interactive nil) #<bytecode 0x12f3b11>) 1)
  org-ref-clean-bibtex-entry(t)
  (lambda (key start end) (org-ref-clean-bibtex-entry t))("Wang2018BreastMass" 1 #<marker (moves after insertion) at 398 in tmp.bib>)
  bibtex-map-entries((lambda (key start end) (org-ref-clean-bibtex-entry t)))
  eval((bibtex-map-entries (function (lambda (key start end) (org-ref-clean-bibtex-entry t)))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)


However, I changed the function to bibtex-clean-entry it worked
nicely. Moreover, it gives me a confirmation before changing each key.

BTW, how can I use this function mapping to, e.g., read the file field
then rename the pdf?

Thanks so much.

**Comment by jkitchin** [comment]
I also see that, I see there was a mistake in that line, it should be:

`% (bibtex-map-entries (lambda (key start end) (org-ref-clean-bibtex-entry)))`

You would have to parse (bibtex-parse-entry) the entry inside the lambda function, then read the file field. Once you do that, you can change the file name, etc.

**Comment by Gahamelas** [comment]
I am trying to clean my bibtex entries, and I stumbled upon this page. Is "bibtex-map-entries" used to this purpose? Where can I find a detailed documentation of which fields to omite? Thanks.

**Comment by jkitchin** [comment]
I don't understand your question. `bibtex-map-entries` can be used to run a function on every bibtex entry. you can make the function do what you want.

**Comment by Gahamelas** [comment]
Actually, fields can be dropped by setting bibtex-completion-no-export-fields!
