### ISSUE TITLE
org-ref-bibtex-pdf serves no purpose

### ISSUE THREAD

**Issue by weirdNox** [jkitchin/org-ref#594]
Hello there! 

While trying this package out, I found that `org-ref-bibtex-pdf` is basically an alias for `org-ref-open-bibtex-pdf` which does not work because it has `(interactive)`, however it needs an argument which isn't even used.

This is something very minor, just to try to clean up a bit :)

**Comment by jkitchin** [comment]
Thanks for noting this. The argument is now optional.

**Comment by weirdNox** [comment]
Thanks :) 

Just curious, does that function have any purpose right now?

**Comment by jkitchin** [comment]
It is used in a deprecated menu command, org-ref-bibtex. It is a precursor to ivy, where it would show you some hot keys in the minibuffer, and you press one to open the pdf, for example. All the commands in this old function are required to take a doi, but some don't need it, like org-ref-bibtex-pdf, so it has an optional, unused argument.

**Comment by weirdNox** [comment]
Oh ok, thanks for taking the time to explain :)
