### ISSUE TITLE
pdfgrep after narrowing C-c ] search

### ISSUE THREAD

**Issue by dangom** [jkitchin/org-ref#597]
A trick I love from Helm is the ability to `C-x C-f` for `helm-find-files`, then go to a folder full of pdfs, narrow the search by typing in a pattern, then `M-a`to select all and `M-g p`to pdfgrep selected files.

The issue I have is that sometimes there is not enough information in the pdf filenames to do a proper narrowing, and sometimes (for example in Mendeley), all pdfs in a library are in a single folder, such that pdfgrep either takes too long, or returns way too many false positives.

What I would like to know is, what would it take to have `helm-ff-run-pdfgrep`run only on the files narrowed after typing a pattern in the `org-ref-helm-insert-cite-link` window? Could it be that this functionality is already implemented in the `org-ref` library?

Again, many thanks for this wonderful project. Can't even describe how helpful and convenient it is.

**Comment by jkitchin** [comment]
This is probably doable if you get the list of keys from the entries selected, use those to get the corresponding pdfs with (org-ref-get-pdf-filename-helm-bibtex KEY), and then pass those to helm-do-pdfgrep-1. It should not be too hard to add that as a function to the helm actions.

**Comment by jagrg** [comment]
Based on John's suggestion:

```elisp
(defun org-ref-grep-pdf (_candidate)
  "Search pdf files of marked CANDIDATEs."
  (let ((keys (helm-marked-candidates)))
    (helm-do-pdfgrep-1
     (mapcar (lambda (key)
	       (org-ref-get-pdf-filename-helm-bibtex key))
	     keys))))

(helm-add-action-to-source "Grep PDF" 'org-ref-grep-pdf helm-source-bibtex 1)
```

**Comment by jagrg** [comment]
Version 2. Only consider candidates with pdfs.

```elisp
(defun org-ref-grep-pdf (_candidate)
  "Search pdf files of marked CANDIDATEs."
  (let ((keys (helm-marked-candidates)))
    (helm-do-pdfgrep-1
     (-remove (lambda (pdf)
		(string= pdf ""))
	      (mapcar (lambda (key)
			(org-ref-get-pdf-filename-helm-bibtex key))
		      keys)))))
```

**Comment by jkitchin** [comment]
Surprisingly, there was no map for helm-bibtex. This works for me.

```
(defun org-ref-grep-pdf (&optional _candidate)
  "Search pdf files of marked CANDIDATEs."
  (interactive)
  (let ((keys (helm-marked-candidates))
        (get-pdf-function org-ref-get-pdf-filename-function))
    (helm-do-pdfgrep-1
     (-remove (lambda (pdf)
		(string= pdf ""))
	      (mapcar (lambda (key)
		        (funcall get-pdf-function key))
		      keys)))))

(helm-add-action-to-source "Grep PDF" 'org-ref-grep-pdf helm-source-bibtex 1)

(setq helm-bibtex-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map helm-map)
    (define-key map (kbd "C-s") (lambda () (interactive)
				  (helm-run-after-exit 'org-ref-grep-pdf)))
    map))

(push `(keymap . ,helm-bibtex-map) helm-source-bibtex)
```

**Comment by dangom** [comment]
Thanks again. This works perfectly! I'm closing the issue as the question has been answered.

**Comment by darcamo** [comment]
I just found this issue while searching for something else. Any reason why this was not added to org-ref? It's such a nice feature and the code from @jkitchin already works as it is. Ideally this could have the same keybinds as helm-find-files described by @dangom.

I'm adding the code to my Emacs configuration any way. Thanks.

**Comment by jkitchin** [comment]
there isn't a specific reason it wasn't added. I don't use helm myself, and it feels like something that might be user defined.

**Comment by darcamo** [comment]
I agree with the keybinding being user defined, but there is no drawback to add the `org-ref-grep-pdf` function along with the helm action, as far as I could see. In fact, the `org-ref-helm-bibtex.el` file seems to add a bunch of actions to helm-bibtex (also mentioned in the **org-ref customization of helm-bibtex** section of orf-ref manual). This would just be another one.
