### ISSUE TITLE
Installing org doesn't install the manual

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jkitchin/org-ref#598]
I am learning `org-mode` for the purpose of using it for Reprouctible Research (and a bit of Litterate Programming). For this activity, bibliography management is a *sine qua non*.

`Apparently, the way to go seems to be `org-ref` ; so be it. No problem at installation but ... the manual, which [exists](https://github.com/jkitchin/org-ref/blob/master/org-ref.org) is not installed !

Is that supposed to happen ?

**Comment by jkitchin** [comment]
How did you install org-ref? and how are you trying to access org-ref.org (the manual)?  If you install it from MELPA it looks like it does get installed. 

If you type M-x org-ref-help

the manual should open in emacs.

**Comment by EmmanuelCharpentier** [comment]
> How did you install org-ref?

Via MELPA.

> and how are you trying to access org-ref.org (the manual)

[Help menu] --> [More manuals] -- > [All other manuals (info)] : no "Ref-Org" entry, which I expected.

> If you install it from MELPA it looks like it does get installed.

I can access its (org) source, but the Texinfo manual is not installed.

**Comment by EmmanuelCharpentier** [comment]
And, BTW, I fail to compile the org source to latex : from my `*Messages*` buffer :
```
org-babel-exp process emacs-lisp at position 7008...
org-babel-exp process emacs-lisp at position 7883...
org-babel-exp process emacs-lisp at position 10002...
org-babel-exp process emacs-lisp at position 11836...
org-babel-exp process emacs-lisp at position 14426...
org-babel-exp process emacs-lisp at position 14743...
org-babel-exp process emacs-lisp at position 16767...
org-babel-exp process emacs-lisp at position 17314...
org-babel-exp process emacs-lisp at position 17623...
org-babel-exp process emacs-lisp at position 18400...
org-babel-exp process emacs-lisp at position 19750...
org-babel-exp process emacs-lisp at position 20829...
org-babel-exp process sh at position 21346...
org-babel-exp process emacs-lisp at position 21640...
org-babel-exp process emacs-lisp at position 21761...
org-babel-exp process emacs-lisp at position 22247...
org-babel-exp process emacs-lisp at position 23608...
org-babel-exp process emacs-lisp at position 23859...
org-babel-exp process emacs-lisp at position 24733...
org-babel-exp process emacs-lisp at position 24847...
org-babel-exp process emacs-lisp at position 26266...
org-babel-exp process emacs-lisp at position 26791...
org-babel-exp process emacs-lisp at position 27889...
org-babel-exp process emacs-lisp at position 28657...
org-babel-exp process emacs-lisp at position 29686...
org-babel-exp process emacs-lisp at position 29922...
org-babel-exp process emacs-lisp at position 30201...
org-babel-exp process emacs-lisp at position 32045...
org-babel-exp process emacs-lisp at position 32786...
org-babel-exp process emacs-lisp at position 33436...
org-babel-exp process emacs-lisp at position 34070...
org-babel-exp process emacs-lisp at position 34799...
org-babel-exp process emacs-lisp at position 35273...
org-babel-exp process emacs-lisp at position 35554...
org-babel-exp process emacs-lisp at position 36291...
org-babel-exp process emacs-lisp at position 40676...
org-babel-exp process emacs-lisp at position 40952...
org-babel-exp process emacs-lisp at position 41472...
org-babel-exp process emacs-lisp at position 42081...
org-babel-exp process emacs-lisp at position 42329...
org-babel-exp process emacs-lisp at position 42627...
user-error: Unable to resolve link: "id:212B487E-CC38-4BDF-9F0E-6993845AF49B"
```

**Comment by jkitchin** [comment]
The manual only exists in org form. There is not a texinfo manual for org-ref.

I don't know what the user-error you see is from. That id is located on line 850 in the org file.

It is a little tricky to build other formats, you need to load a few org-ref libraries that are not enabled by default, but none of them have anything to do with id links I think. See

https://github.com/jkitchin/org-ref/blob/master/org-ref.org#other-forms-of-this-document

I just built the pdf on a Mac and Windows using the code blocks in that section.

**Comment by EmmanuelCharpentier** [comment]
Okay. I didn't saw these "Build notes". I executed the recommended steps and the PDF built almost fine. Two problems, however : 

* Exporting (as recommended) by `(org-open-file (org-latex-export-to-pdf))` gives me a dicument where the various bibliographic reverences are printing as `[?]`, and the `References` section is empty.

* Exporting to a LaTeX file, then trying to compile it (with AUCTeX) fails with : 
```
ERROR: Undefined control sequence.

--- TeX said ---
l.1037 \printindex
                  
--- HELP ---
TeX encountered an unknown command name. You probably misspelled the
name. If this message occurs when a LaTeX command is being processed,
the command is probably in the wrong place---for example, the error
can be produced by an \item command that's not inside a list-making
environment. The error can also be caused by a missing \documentclass
command.
```

A bit of a showstopper : 4 want to use `org-ref` *in order to be able to `\cite`*. This trial doesn't make me very optimistic...

> There is not a texinfo manual for org-ref

That's real bad : The ability to export to various formats is one of the strong points of `org-mode`. Being unable to export (part of) its own manual is a bit ... disparaging.

Do you plan to add/fix that? IMHO, it is a necessity...

**Comment by jkitchin** [comment]
It sounds like these are latex problems, not org-ref problems. I guess you are not running bibtex in the compile process, so the references are not getting defined. 

I would call your attention to this part of the manual: https://github.com/jkitchin/org-ref/blob/master/org-ref.org#latex-export

printindex is defined in the makeidx package, and you have to include that in the build process. if you plan to use an index. See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#indexes.

org-ref is primarily used for writing scientific manuscripts in that are compiled from Latex, and works extremely well for that. It has some support for export to html and markdown. You can make it work for texinfo if you want, but it isn't a need for me, and I have no plans to make it work. The manual is written in org-mode, for use in org-mode.
