### ISSUE TITLE
Org-ref-helm-insert-cite-link doesn't work if the text `bibliography:` appears in the org file

### ISSUE THREAD

**Issue by JonathanReeve** [jkitchin/org-ref#599]
If I have the text `bibliography:` somewhere in my org file, org-ref-helm-insert-cite-link will fail. For instance, I have a file which contains the text: `The bibliography, in particular, should be a working bibliography: these are the texts that you have made use of in formulating your ideas.`. When I run org-ref-helm-insert-cite-link, it says: `user-error: Bibliography file fish: Unknown command 'kpsewhich these are the texts that you have made use of in formulating your ideas.`. I'm no elisp expert, but is it just looking for the text `bibliography:` anywhere? And then just parsing the rest of that string? Seems like there should be a better solution, like maybe looking for `#+BIBLIOGRAPHY:` at the top of the file, instead.

**Comment by jkitchin** [comment]
I think we used to support #+BIBLIOGRAPHY:, but may have stopped. The bibliography link serves another purpose, which is to place the bibliography where you want it in the latex file.  Somewhere that is needed if you ever export to latex.

I think I have pushed a fix that addresses this issue.

**Comment by JonathanReeve** [comment]
Awesome. Fix works for me. Thanks for looking into this!
