### ISSUE TITLE
Unable to drag/drop pdf files using org-ref-pdf

### ISSUE THREAD

**Issue by petemcd18** [jkitchin/org-ref#602]
Hi,

I have tried to drag and drop the attached files into testbib.bib without success. 

[3432.full.pdf](https://github.com/jkitchin/org-ref/files/2428184/3432.full.pdf)
Source file downloaded from: http://www.pnas.org/content/96/7/3432.short

[2015 Renal Control of Calcium Phosphate and Magnesium Homeostasis Levi.pdf](https://github.com/jkitchin/org-ref/files/2428195/2015.Renal.Control.of.Calcium.Phosphate.and.Magnesium.Homeostasis.Levi.pdf)
Source file downloaded from: https://www.karger.com/Article/FullText/440972

[61D291B8-05C7-4ACA-B46D-7B0FA6310F6A.pdf](https://github.com/jkitchin/org-ref/files/2428199/61D291B8-05C7-4ACA-B46D-7B0FA6310F6A.pdf)
Source file downloaded from: https://www.tandfonline.com/doi/full/10.5235/17521440.7.3.159

and finally 
[F30F4C21-B8B4-422F-9F84-C58BEB784F5E.pdf](https://github.com/jkitchin/org-ref/files/2428203/F30F4C21-B8B4-422F-9F84-C58BEB784F5E.pdf)
source file downloaded from: http://journals.sagepub.com/doi/10.1177/1461452914563217

Each time i get the error: No doi found in {path}

Am I doing something wrong?

I have attached my .emacs as emacs.txt

[emacs.txt](https://github.com/jkitchin/org-ref/files/2428181/emacs.txt)

Your online video at https://www.youtube.com/watch?v=2t925KRBbFc makes it look incredibly simple but for some reason I am struggling to get my head around it.

Thanks in advance,
Pete

**Comment by petemcd18** [comment]
Hi, apologies, I think I have partially resolved this issue. 
It may have been that after I had installed the packages I hadnt specifically called pdf-tools-install.
I have now done this and retested. 
2 out of the 4 now work.

The two remaining files that do not work are:

F30F4C21-B8B4-422F-9F84-C58BEB784F5E.pdf
source file downloaded from: http://journals.sagepub.com/doi/10.1177/1461452914563217

and 

3432.full.pdf
Source file downloaded from: http://www.pnas.org/content/96/7/3432.short

both have DOI's present in the PDF but i am assuming that the way the PDF-meta has been encoded that org-ref simply is unable to process it?

There is a work-around which I have used which simply when to the DOI URL and added them that way rather than dragging them into as PDF but it would be interesting to know what the issue is.

Thanks

Pete

**Comment by jkitchin** [comment]
The drag and drop capability is pretty fragile. It tries to find dois by regular expressions in the text, not from dedicated metadata. It could be the dois get mangled when the pdf is converted to text, or that the regexp doesn't find it. I exclusively use doi-add-bibtex-entry and don't use drag and drop anymore.
