### ISSUE TITLE
cite:key results in \cite[cite:key]{key} upon latex export

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#605]
Hi there,

just discovered your awesome package. But I am stumped by the following behavior

If I write citep:ziegler88 in my org file, and then export to latex, the latex code will read

\citep[cite:ziegler88a]{ziegler88a}

which compiles to

(Ziegler et al ., 1988, citep:ziegler88)

the expected result is, however  (Ziegler at al. 1988).

I could not find reference to this problem elsewhere, so I believe it is local bug. Any pointers on how to debug this are much appreciated

Cheers

Uli

**Comment by jkitchin** [comment]
Can you paste exactly how you put the link in? If you have put in 
 [[citep:ziegler88 ][citep:ziegler88]]

it is not correct, just use citep:ziegler88. If not, I don't know why you would get that output.

**Comment by uliw** [comment]
Definitively a config issue. Running this on my laptop works like a charm. I'll post once I find out what is causing this

**Comment by uliw** [comment]
Hi John,

so this took some digging since the problem persisted on my computer, even so, I used the same startup files I was using on my laptop (where it worked flawlessly). Or so I thought. I am unable to pin point where things went south, but it appears that some old distribution supplied startup files caused this.  The remedy was to delete all local .emacs* and .gnu-emacs* files, only keeping .gnu-emacs-custom and my private startup file. It is now working like a charm. Thanks for this great piece of code!

Uli

**Comment by jkitchin** [comment]
Thanks for the update. Glad to hear it is working. I also had some issue recently where I had to delete all those files to get rid of some old packages. Sometimes you can avoid them with emacs -q -l "yourinit.el".
