### ISSUE TITLE
org-ref-helm-insert-cite link fails with bibtex string definitions

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#606]
Hi there,

if I use the following in org mode:  
bibliography:agu.bib,manuscript.bib

and agu.bib contains string definitions for journal names like: @string(AAA="Arct. Antarct. Alp. Res.")
inserting a citation will fail (See below for backtrace).

I do this since it provides a simple and robust way to switch between full and abbreviated journal names simply by exchanging the file with the string definitions as needed by the respective journal. (Note I am aware that org-ref has a mechanism to achieve this as well).

I've added the stripped down files which will produce this error on my system.

Let me know if I can help otherwise

Cheers

Uli

[images.org.zip](https://github.com/jkitchin/org-ref/files/2474097/images.org.zip)

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  bibtex-valid-entry(t)
  bibtex-end-of-entry()
  parsebib--match-paren-forward()
  parsebib-read-string(8 #<hash-table equal 0/65 0x11c4c35>)
  bibtex-completion-parse-strings(#<hash-table equal 0/65 0x11c4c35>)
  bibtex-completion-candidates()
  helm-bibtex()
  org-ref-helm-insert-cite-link(nil)
  funcall-interactively(org-ref-helm-insert-cite-link nil)
  #<subr call-interactively>(org-ref-helm-insert-cite-link nil nil)
  apply(#<subr call-interactively> org-ref-helm-insert-cite-link (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> org-ref-helm-insert-cite-link nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (org-ref-helm-insert-cite-link nil nil))
  call-interactively(org-ref-helm-insert-cite-link nil nil)
  command-execute(org-ref-helm-insert-cite-link)

**Comment by jkitchin** [comment]
These work fine for me with both org-ref-helm-insert-cite-link  and org-ref-ivy-insert-cite-link. I can't see why the strings make it fail. I assume this works if you don't put the agu.bib into the bibliography link?

**Comment by uliw** [comment]
I noticed that if I change my string definition from using regular braces to using curly braces, the problem goes away. This is at least a workaround. I.e., 
@string{AAA="Arct. Antarct. Alp. Res."} will work, whereas
@string(AAA="Arct. Antarct. Alp. Res.")

won't

Cheers

Uli

**Comment by jkitchin** [comment]
The first one seems like valid syntax, and the second one isn't as far as I know. At least, I have never seen syntax with parentheses before.
