### ISSUE TITLE
org-ref citation links could follow crossref keys to find PDFs

### ISSUE THREAD

**Issue by hdevalence** [jkitchin/org-ref#607]
Suppose there's a bibtex `@inproceedings` entry `foo` with `crossref = {bar}`, and a `@proceedings` entry `bar` with `bar.pdf` in the PDF directory.

It would be nice if opening a citation link to `foo` presented the option to open the PDF for `bar`, which contains `foo`.  Currently, `org-ref` can't see that a PDF containing `foo` exists already.

**Comment by jkitchin** [comment]
This could be solved  with a custom org-ref-get-pdf-filename-function. It would have to go to the bibtex entry, check for a pdf, if none, check for a crossref and follow it, check for a pdf, etc. The default function is org-ref-get-pdf-filename, which is not that smart (it doesn't look at the bibtex entry at all). There are two others: org-ref-get-mendeley-filename and org-ref-get-pdf-filename-helm-bibtex that might provide inspiration for a more complex version that can follow crossrefs. If you come up with something that works, I would be happy to add it as an option to org-ref.
