### ISSUE TITLE
bibtex entry from pdf not working even when doi is present

### ISSUE THREAD

**Issue by kirk86** [jkitchin/org-ref#608]
Dear Prof. Kitchin,
thank you for creating `org-ref` and for sharing it with us.
While I was experimenting with it I found that it was impossible to properly add a bibtex entry to `.bib` file by dragging a pdf in the emacs buffer.
The pdf contains the doi and using `doi-insert-bibtex` works perfectly fine if you provide the doi.

Here's and example of what I get when dragging-n-dropping the file in emacs buffer:
![image](https://user-images.githubusercontent.com/2902390/46963043-318f1d00-d094-11e8-9bdf-aaf85e572a10.png)

Any suggestion would be appreciated.

**Comment by jkitchin** [comment]
Drag and drop is not always reliable because it uses pattern matching to find dois, and sometimes it finds the wrong pattern. I recommend you just use doi-insert-bibtex which is reliable.

Drag and drop seemed like a nice idea, but in practice it isn't what I use.

**Comment by kirk86** [comment]
@jkitchin thank you for your prompt response.
I haven't looked inside in `org-ref` code but I think tools such as mendeley and zotero utilize `pdfinfo` and `pdftotext` to extract metadata. If you were to use the same approach maybe it would be more robust/reliable?

> Drag and drop seemed like a nice idea, but in practice it isn't what I use.

May I ask what do you use to manage pdfs. For instance for renaming them according to bibtex key and storing them in predefined directories?

**Comment by jkitchin** [comment]
pdftotext is what I use. The problem is that DOIs do not have a regular pattern that is easy to match for all DOIs, and sometimes a pdf has more than one doi in it. Sometimes they are in urls, sometimes in metadata, etc. The PDFs don't reliably have DOIs in the metadata either. 

When I use doi-insert-bibtex, it usually automatically downloads the pdf for me into the pdf directory and named by the bibtex key.  When I want to open a pdf, I just fire up org-ref, narrow to the reference I want and choose Open PDF from the menu. Or I click on a citation and press p.

**Comment by kirk86** [comment]
@jkitchin thank you for the clarification. 

> The PDFs don't reliably have DOIs in the metadata either.

I would also add that some pdf don't even have dois at all, any suggestion on this case? or just do it the old fashion way, manually?

BTW, using `doi-insert-bibtex` inside the `.bib` file it inserts bibtex entry but it never fetches the pdf. I also tied the `arxiv-get-pdf-add-bibtex-entry` and this one also doesn't fetch any pdfs.

Any ideas on what I might be doing wrong?

For the installation of the `org-ref` I followed the manual on github.

**Comment by jkitchin** [comment]
Nearly every paper I need to reference has a doi, and doi-insert-bibtex is usually able to get a bibtex entry for them. org-ref can only download pdfs for journals where a "recipe" exists to get the pdf, which means it can compute a url to get it from *and* for articles where you have permission (based on your current ip address) to access the pdfs. 

I don't know why arxiv would be failing to get the pdf, that should work I think.

**Comment by kirk86** [comment]
@jkitchin 

> which means it can compute a url to get it from _and_ for articles where you have permission to access the pdfs

I can access most of the papers I've tried since I'm visiting them from a uni address and the uni has subscription to a large amount of services and journals. Bust still `org-ref` is not able to download any of them even if they are from journals.

May I ask for a favour? Could you test on your setting if you can download the following paper based on the doi `10.1016/j.dsp.2017.10.007`.
Thank you and apologies if I'm asking for too much but I'm trying to understand what am I doing wrong or if there's a bug somewhere.

Plus, the fact that arxiv is failing to download the pdf could indicate a bug, probably on my side?

**Comment by jkitchin** [comment]
That particular doi doesn't automatically download a pdf for me, but it does open a url to the pdf. Elsevier makes it especially difficult to download pdfs automatically, so in this case I would manually save the pdf. The key is on the clipboard, so you usually just have to paste it in for the file name.

For arxiv, it looks like I was mistaken, arxiv-add-bibtex-entry does not appear to download pdfs. It looks like arxiv-get-pdf-add-bibtex-entry is the command to do that.

**Comment by kirk86** [comment]
@jkitchin

> It looks like arxiv-get-pdf-add-bibtex-entry is the command to do that

That is absolutely correct and that is what I am using but I keep getting the following error:
```
Invalid date: nil
```
Every time that I execute the command.

**Comment by jkitchin** [comment]
hm. That may be a problem with the arxiv metadata. It worked fine for me on 1810.05489.

**Comment by kirk86** [comment]
@jkitchin Ah, I see, now I understand my error, I was using the article name but apparently it seems that it only works with arxiv id, am I assuming this correct? It would be nice have those examples in the doc page here at github so that we won't bother you asking the same questions over and over.

Thank you for your patience! I'm closing this in order to keep things clear.
