### ISSUE TITLE
org-ref-sort-bibtex-entry deletes comments following an entry

### ISSUE THREAD

**Issue by treese** [jkitchin/org-ref#611]
Suppose we have a BibTeX file like this (the extension on it is .txt so GitHub would attach it):[test.bib.txt](https://github.com/jkitchin/org-ref/files/2513100/test.bib.txt)

It has the format:

<bibtex entry>
<comments>
<bibtex entry>

If we run` org-ref-clean-bibtex-entry` on it, one of the standard cleaning functions to call is `org-ref-sort-bibtex-entry`. That function uses `bibtex-kill-entry` before rewriting the entry, and it widens the buffer just before doing that, with a comment that the widen is needed so that it can delete blank lines following the entry. 

Unfortunately, it also deletes the comments in this example, and, in general, anything in the file up to the next bibtex entry.

This seems surprising, since one might often have comments before the entry being commented upon.

Arguably, it's this is strange behavior of `bibtex-kill-entry`, but org-ref could also do things differently regardless of what the bibtex-mode maintainers want to do.

Or I am missing something about this behavior?

**Comment by jkitchin** [comment]
I think this was fixed in issue #612 right?
