### ISSUE TITLE
[feature proposal] Associate supplementary information with bibtex entries

### ISSUE THREAD

**Issue by yantar92** [jkitchin/org-ref#614]
Currently, it is possible to associate a single pdf file with a bibtex entry. 
However, some papers have very useful supplementary information, like in depth discussion of theory, videos, data, etc.
It would be great to be able to associate these additional files with the bibtex entry and access them via the existing org-ref interface.

**Comment by jkitchin** [comment]
How would you do this? Do you know if there is a way to put multiple PDF files in a bibtex entry? Maybe if you use a , separated file field, then you could split that. It could clutter up the bibtex file though.

Maybe an alternative is to use the bibtex key as a prefix for file names, e.g. the main pdf is key.pdf, and the SI is key-si.pdf, etc.. Then you could get a list of all files with the prefix to open. What do you think?

**Comment by yantar92** [comment]
Technically, it is possible to use any arbitrary custom field type in bibtex. For example, JabRef uses the following format:
`  File                     = {:articles\\Budiman\\Budiman_2014_SolMat.pdf:PDF;:articles\\Budiman\\Budiman et al., SolMat 130 (2014) p.303-308-1.pdf:PDF},
`

However, I believe that specifying file format is excessive - it is either clear from the file extension and can be found with `file`. The same can be said about the exact folder where the additional files are located - it depends on the specific folder structure, which is unrelated to the bibtex entry itself. 

I think that it would make senes to have file names for the SI, as they are defined in the publication itself. 
As for the implementation details, the SI files could be stored as you suggested `{key}-{SI file name}[.{SI file extension}]`.

**Comment by jkitchin** [comment]
You can write your own function to do this, and set `org-ref-get-pdf-filename` to that function. It could for example, find all files matching key* in some directory, and let you choose them with completion, maybe defaulting to just opening if there is only one match.

**Comment by jkitchin** [comment]
I have modified the default behavior to support this a little better. Now if you have your pdfs named as key*.pdf, and there are more than one file by that pattern, you will be prompted for which pdf to open.
