### ISSUE TITLE
sort new entries in doi-utils-add-bibtex-entry-from-doi

### ISSUE THREAD

**Issue by plantarum** [jkitchin/org-ref#621]
The comment above doi-utils-add-bibtex-entry-from-doi includes "You can sort it later." I wonder if it would be ok to include the option to sort it automatically, since that's what I'll want to do in almost every case.

I tried adding `(bibtex-clean-entry)` before the final ([save-buffer](https://github.com/jkitchin/org-ref/blob/1b5cf239d2abe203b9c64000c9010bbb6bf18fb4/doi-utils.el#L976)), and it appears to work just fine. Will that break anything else?

**Comment by jkitchin** [comment]
That should be fine. The sorting is done automatically I think in org-ref-clean-bibtex-entry (which is called in that function) where all the hook functions are called. By default, one of those hooks is org-ref-sort-bibtex-entry.

**Comment by plantarum** [comment]
`org-ref-sort-bibtex-entry` sorts the fields within an entry, I want to sort the entire entry in the .bib file (e.g., move `aalbers_2016` to the beginning of my .bib file, rather than move the title field to the first line in `aalbers_2016`). I see that `org-ref-clean-bibtex-entry` narrows to the selected entry prior to running the hooks, so there's no way to relocate the entry to another position in the file at that point. 

Is there another hook I can use that is called after the narrowing is removed? Or maybe I should advice `doi-utils-insert-bibtex-entry-from-doi`?

**Comment by jkitchin** [comment]
At the moment advice is the best thing to do. There is not a post widen hook available. 

Are you sure you can't add a hook function that calls widen though? It is possible that doesn't work, or causes some issue, I haven't tried it.

**Comment by plantarum** [comment]
I'll take a look when I have more time. I'm nervous about nested saved-restrictions: i.e., a `widen` inside a `narrow-to-entry`, which will include moving the entry and then re-establishing the correct narrowing afterwards. That sounds like it could get tricky.

**Comment by jkitchin** [comment]
That would concern me too. advice is easier that way. I guess 1% of bibtex entry insertion fails, and i have some memory of sorting doing weird things in the past, which is why I have not automated this. I tend to do it manually, after a git commit of the bibtex file so it is easy to revert. YMMV.

**Comment by treese** [comment]
If your goal is to keep the buffer sorted by citation key, would running `bibtex-sort-buffer` do the job? By default it's not bound to a key, but if. you have the menus turned on, it's on BibTex-Edit->Operating on Buffer or Region->Sort Entries

**Comment by jkitchin** [comment]
`bibtex-sort-buffer` does the job just fine. I usually either M-x it or call it from one of the menus. You could put is as an after advice, but my experience is inserting entries occasionally fails often enough and then you don't want to sort. Sometimes weird things happen that can go undetected long enough to be hard to undo. I have 1000s of entries in some files, and it isn't feasible to check them by hand, so I have mostly given up on having them sorted.

**Comment by plantarum** [comment]
@treese There are several functions that sort the entries as I want, that's not the problem. What I'm trying to do is get the new entry created by `doi-utils-add-bibtex-entry-from-doi` to be sorted into place after it is created automatically. The problem is getting that to happen at the correct time, and the worry is that it may fail in ways that do unexpected things to the entire file. So calling a sorting function manually is currently the best option to avoid messing up a huge file of entries.
