### ISSUE TITLE
org-ref format in html (odt): should be like pain in bibtex (latex)

### ISSUE THREAD

**Issue by ouboub** [jkitchin/org-ref#623]
Hi

I am using the following function (I think provided generously by John
Kitchin)

org-ref-get-bibtex-entry-html (key)

(defun org-ref-get-bibtex-entry-html (key)
  "Return an html string for the bibliography entry corresponding to KEY."
  (let ((output))
    (setq output (org-ref-get-bibtex-entry-citation key))
    ;; unescape the &
    (setq output (replace-regexp-in-string "\\\\&" "&" output))
    ;; hack to replace {} around text
    (setq output (replace-regexp-in-string "{" "" output))
    (setq output (replace-regexp-in-string "}" "" output))
    ;; get rid of empty parens
    (setq output (replace-regexp-in-string "()" "" output))
    ;; get rid of empty link and doi
    (setq output (replace-regexp-in-string " <a href=\"\">link</a>\\." "" output))
    ;; change double dash to single dash
    (setq output (replace-regexp-in-string "--" "-" output))
    (setq output (replace-regexp-in-string " <a href=\"http://dx\\.doi\\.org/\">doi</a>\\." "" output))
    (format "<li><a id=\"%s\">%s</a></li>"
            key output)))

I also use ox-clip-formatted-copy to copy for example: the following
lines into a libreoffice document or 

The first who achieved a result by regularizing the equations was
Makino, see cite:makino86:_local_exist_theor_evolut_equat_gaseous_stars. 
bibliographystyle:plain
bibliography:/home/oub/texmf/bibtex/bib/bibgraf.bib

But I obtain (HTML removed)

The first who achieved a result by regularizing the equations was
Makino, see makino86:_local_exist_theor_evolut_equat_gaseous_stars.

Bibliography

1. Makino, On a Local Existence Theorem for the Evolution Equation of
       Gaseous Stars, 459-479, in in: Patterns and Waves, edited by
       Nishida, Mimura & Fujii, North-Holland (1986)

And I would like to see 

The first who achieved a result by regularizing the equations was
Makino, see [1]

Bibliography

[1.] Makino, On a Local Existence Theorem for the Evolution Equation of
       Gaseous Stars, 459-479, in in: Patterns and Waves, edited by
       Nishida, Mimura & Fujii, North-Holland (1986)

I looked for appropriate variables but could not find anything.

Any help would be strongly appreciated.

Uwe Brauer

**Comment by jkitchin** [comment]
That function is outputting an item in a list. If you are trying to get 1. turned into [1.] in the bibliography you would have to either write a new function that does the numbering for you, or try to figure out how to use css to style the numbered list.

If you are also trying to get [1] in the text, your options are limited. This requires preprocessing. you might look at https://github.com/wyleyr/org-citeproc.

**Comment by ouboub** [comment]
I am only thinking about getting [1] (as a link) in the text because this is usually standard while
makino86:_local_exist_theor_evolut_equat_gaseous_stars. in the text is rather unusual.

**Comment by ouboub** [comment]
I just realized that setting 
org-ref-default-citation-link at least results in makino93 which is a bit better and more standard, 
so it seems to me rather natural to have [1] as alternative?

**Comment by jkitchin** [comment]
I would probably prefer [1] too but that cannot be done easily in the current export framework without first doing some preprocessing. You have to accumulate a list of all the references in order, then go through and replace them, then do the export. On the other hand many would prefer (author, year) or a superscript, etc, and this is all in the citeproc realm. You can see some possibilities at http://kitchingroup.cheme.cmu.edu/blog/2015/12/11/Introduction-to-a-citation-processor-in-org-ref/, but I think the org-citeproc is more mature than this older work.

**Comment by jkitchin** [comment]
citeproc is certainly the path forward for this kind of think.
