### ISSUE TITLE
As of Dec 14, 2018, the PDF version of the manual doesn't build.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jkitchin/org-ref#626]
Probably related to [my previous issue](https://github.com/jkitchin/org-ref/issues/598) but slightly worse : I can't recompile the manual **at all**. Hitting `C-c C-c` in the relevant `emacs-lisp` block of the manual gets a compilation stopping with : 
```
executing Emacs-Lisp code block...
org-babel-exp process emacs-lisp at position 8032...
org-babel-exp process emacs-lisp at position 8907...
org-babel-exp process emacs-lisp at position 11026...
org-babel-exp process emacs-lisp at position 12860...
org-babel-exp process emacs-lisp at position 15450...
org-babel-exp process emacs-lisp at position 15767...
org-babel-exp process emacs-lisp at position 17791...
org-babel-exp process emacs-lisp at position 18338...
org-babel-exp process emacs-lisp at position 18647...
org-babel-exp process emacs-lisp at position 19814...
org-babel-exp process emacs-lisp at position 20090...
org-babel-exp process emacs-lisp at position 20979...
org-babel-exp process emacs-lisp at position 22329...
org-babel-exp process emacs-lisp at position 23408...
org-babel-exp process sh at position 23925...
org-babel-exp process emacs-lisp at position 24219...
org-babel-exp process emacs-lisp at position 24340...
org-babel-exp process emacs-lisp at position 24826...
org-babel-exp process emacs-lisp at position 26187...
org-babel-exp process emacs-lisp at position 26438...
org-babel-exp process emacs-lisp at position 27312...
org-babel-exp process emacs-lisp at position 27426...
org-babel-exp process emacs-lisp at position 28845...
org-babel-exp process emacs-lisp at position 29370...
org-babel-exp process emacs-lisp at position 30468...
org-babel-exp process emacs-lisp at position 31236...
org-babel-exp process emacs-lisp at position 32265...
org-babel-exp process emacs-lisp at position 32501...
org-babel-exp process emacs-lisp at position 32780...
org-babel-exp process emacs-lisp at position 34624...
org-babel-exp process emacs-lisp at position 35365...
org-babel-exp process emacs-lisp at position 36015...
org-babel-exp process emacs-lisp at position 36649...
org-babel-exp process emacs-lisp at position 37378...
org-babel-exp process emacs-lisp at position 37852...
org-babel-exp process emacs-lisp at position 38133...
org-babel-exp process emacs-lisp at position 38870...
org-babel-exp process emacs-lisp at position 42958...
org-babel-exp process emacs-lisp at position 43567...
org-babel-exp process emacs-lisp at position 43815...
org-babel-exp process emacs-lisp at position 44371...
user-error: Unable to resolve link: "id:212B487E-CC38-4BDF-9F0E-6993845AF49B"
```
You remarked on Sep 12 that : 
> It is a little tricky to build other formats, you need to load a few org-ref libraries that are not enabled by default, but none of them have anything to do with id links I think. 

Might this issue be related to that ? In that case, it might be easy enough to `require` these libraries in the "compile me" `emacs-lisp` sorce block you're kind enough to include.

It's probably a minor booboo, but should be fixed : reading the manual in source for is a (large) bit annoying...

**Comment by jkitchin** [comment]
I think the commit above (and the one after it) will make it possible to export to a pdf. I did not combine the (require..) block with the PDF. You should run that one, then either (or both) of the PDF and html blocks.

**Comment by EmmanuelCharpentier** [comment]
as ot ELPA version `org-ref-20190102.1510` this fails with the message : 
```
user-error: Unable to resolve link: "bibliographystyle link"
```

I have tried to copy my `unsrt.bst` file in the directory where I (try to) build the PDF, where I copied `org-ref.org` and`org-ref.bib`.

*NOTE :* I have also other (probably unrelated) errors when I try to compile all blocks (C-c C-v b) : 
```
You can check if a url for the PDF can be found like this:
#+BEGIN_SRC emacs-lisp
(doi-utils-get-pdf-url "10.1021/jp511426q")
#+END_SRC
```
fails with : `doi-utils-get-pdf-url: No redirect found for 10.1021/jp511426q`

after disabling this block with an `:eval never` header option, a second attempt fails at : 
```
#+BEGIN_SRC emacs-lisp
(bibtex-map-entries 'org-ref-title-case-article)
#+END_SRC
```
(this one might be more serious...).

After deactivation, a third failure occurs at : 
```
Add this to your init file:
#+BEGIN_SRC emacs-lisp
;; PDF links for org-mode
(with-eval-after-load "pdf-tools"
  (use-package org-pdfview
    :config
    ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00169.html
    ;; Before adding, remove it (to avoid clogging)
    (delete '("\\.pdf\\'" . default) org-file-apps)
    ;; https://lists.gnu.org/archive/html/emacs-orgmode/2016-11/msg00176.html
    (add-to-list 'org-file-apps
		 '("\\.pdf\\'" . (lambda (file link)
				   (org-pdfview-open link))))))
#+END_SRC
```

(shouldn't this one be an EXAMPLE block ?)

A fourth attempt after deactivation fails on the `bibliogtaphystyle link` error reported *supra*.

HTH,

**Comment by jkitchin** [comment]
That is probably expected.  The tableofcontents option is set to nil, and only the latex command is given. html export is not as well supported as latex is.

**Comment by asvcc** [comment]
When I try to export the `org-ref.org` file to a `pdf` file, I also get an error:

```
Unable to resolve link: "bibliographystyle link"
```

I don't know why.

**Comment by jkitchin** [comment]
I have not been able to reproduce this.

**Comment by jacquesdurden** [comment]
> When I try to export the `org-ref.org` file to a `pdf` file, I also get an error:
> 
> ```
> Unable to resolve link: "bibliographystyle link"
> ```
> 
> I don't know why.

Same bug for me.

**Comment by jkitchin** [comment]
Are you following the directions to build it at https://github.com/jkitchin/org-ref/blob/master/org-ref.org#build-notes?

**Comment by jacquesdurden** [comment]
Thanks for the answer. I loaded all required libraries, i.e.,   

```
(require 'org-id)
(require 'org-ref-wos)
(require 'org-ref-scopus)
(require 'org-ref-pubmed)
```
But from them, the normal org-mode PDF exportation provides the error message I mentioned. 

However, by having a closer look to the section you point me, I localized this lisp code snippet in org-ref.org 

```
#+begin_src emacs-lisp
(let ((org-export-with-broken-links t)
      (org-latex-pdf-process
       '("pdflatex -interaction nonstopmode -shell-escape -output-directory %o %f"
	 "bibtex %b"
	 "makeindex %b"
	 "pdflatex -interaction nonstopmode -shell-escape -output-directory %o %f"
	 "pdflatex -interaction nonstopmode -shell-escape -output-directory %o %f")))
  (org-open-file (org-latex-export-to-pdf)))
#+end_src
```
and run it with C-c C-c. It works like a charm. Thank you.

**Comment by jkitchin** [comment]
The key is (org-export-with-broken-links t).  In the org-ref.org document there was a missing target that was causing that error, and the export with broken links lets the build keep going. I just found the missing target and fixed that, and now I think with that fix you can export with C-c C-e lo. Thanks for reporting it!
