### ISSUE TITLE
Nothing found on call to isbn-to-bibtex

### ISSUE THREAD

**Issue by non-Jedi** [jkitchin/org-ref#628]
Called `isbn-to-bibtex` with `(isbn-to-bibtex "9780071422949" "/home/adam/org/references.bib")` and got the "Nothing found" message despite everything on https://www.ottobib.com/isbn/9780071422949/bibtex looking perfectly valid.

Need to do more digging, but it seems like something on that page must be confounding the regex here: https://github.com/jkitchin/org-ref/blob/01d2fd7777563f78a5094209cfdf5918e7e45a3c/org-ref-isbn.el#L174

**Comment by treese** [comment]
Quick guess: the single quote in the citation key, which is just weird.

**Comment by jkitchin** [comment]
I am pretty sure this is fixed in 1f88739. Thanks for reporting it. A chemical engineering book at that!

**Comment by non-Jedi** [comment]
Thanks! :)
