### ISSUE TITLE
org-ref does not look inside #+INCLUDE files

### ISSUE THREAD

**Issue by modsoul42454** [jkitchin/org-ref#629]
Hi All.
First off, let me say org-ref is incredible. But, i've been trying to write my dissertation in org-mode with org-ref and recently decided to p0ut different chapters into separate files using #+INCLUDE: filename.org.

Org-ref doesn't see inside these files for auto-completion or list of figures etc. It work on export, but not during writing. 
Thanks so much

**Comment by jkitchin** [comment]
Could you make a small set of files that have include files, that illustrate what you want to support? 

I think there are some challenges to implementing this smoothly. I can see  when you are in the master file that it could be feasible to get a list of labels from all the includes, but when you are in an include file, it might not be feasible to get the labels from another file without some kind of local file variable that says what the master file it is associated with is. In other words, to reference a figure from chapter one, when you are in chapter two where both of them are includes in master.org.

**Comment by badkey** [comment]
I encountered a very similar problem - org ref fails if a figure is referenced. Here is a org file including all necessary information (I hope).
---begin---
#+title: Test Include
#+PROPERTY: eval yes

* Info
Test the include-keyword
: #+include:
by exporting to tex.

See also [[info:org#Include%20Files][info:org#Include Files]].

* COMMENT Create org file without references

Create a file we include some text from.

#+BEGIN_SRC org :tangle includedfile.org :exports code
,* Included file header
  :PROPERTIES:
  :CUSTOM_ID: firstheader
  :END:
Line 1
Line 2
Line 3

,* Next section include
  :PROPERTIES:
  :CUSTOM_ID: secondheader
  :END:
Next line 1
Next line 2
Next line 3
#+END_SRC

* Test org file without references

So we need
: #+include: "./includedfile.org"
to get the content:

#+include: "./includedfile.org"

Works.

* COMMENT Org file with references
** File creation
Let us have
#+BEGIN_SRC org :tangle includedrefs.org :exports code
,* Included file header
  :PROPERTIES:
  :CUSTOM_ID: firstheader
  :END:
Line 1
Line 2
Line 3 with reference to a table ref:tab:Table 

,#+name: tab:Table
,#+caption: Table caption.
|1|

,* Next section include
  :PROPERTIES:
  :CUSTOM_ID: secondheader
  :END:
Next line 1
Next line 2
Next line 3 with reference to figure ref:asy

,#+NAME: Asymptote
,#+BEGIN_SRC asym ptote :file ./asyexa.png :exports both
  filldraw(circle(0, 22), green);
  label("Hurz");
,#+END_SRC

,#+caption: Image label:asy
,#+RESULTS: Asymptote
[[file:./asyexa.png]]


#+END_SRC

** Image creation
#+NAME: Asymptote
#+BEGIN_SRC asymptote :file ./asyexa.png :exports both
  filldraw(circle(0, 22), green);
  label("Hurz");
#+END_SRC

#+RESULTS: Asymptote
[[file:./asyexa.png]]


* Test org file with references
** Inclusion test with tables
Include the first header with table ref:
#+include: "./includedrefs.org::#firstheader"
works
** Inclusion test with figures
Include the second header with figure ref:
#+include: "./includedrefs.org::#secondheader"

yields error
: org-ref-delete-labels: Args out of range: 192, 192

---end---

**Comment by badkey** [comment]
Very cool - the issues are gone, however sometimes org seems to struggle with some custom ids (while others do work). I did not manage to isolate the problem so far.
Anyway, thanks for the quick fix.

**Comment by jkitchin** [comment]
I haven't seen any custom id issues, but I don't use them much either. I am going to close this. If you isolate a custom_id problem in org-ref, feel free to post a new issue. The only thing that comes to mind is custom_id vs CUSTOM_ID (i.e. the casing).

**Comment by jkitchin** [comment]
On second thought, I am going to reopen this. org-ref still doesn't look in the INCLUDE files, and it would probably be nice if it did.

**Comment by Cumol** [comment]
Yeah, having that problem right now writing a thesis that is spread across multiple files.

Any workaround?

**Comment by jkitchin** [comment]
There is still no solution for this.

**Comment by japhir** [comment]
I also encountered this issue when I defined glossary/acronym tables that are relevant to all the chapters in my thesis in one external file that I included, but this means that autocomplete, hover info, and nice formatting all don't work.
Would be a nice feature indeed :).

**Comment by jkitchin** [comment]
Have you tried the approach referenced above?

**Comment by japhir** [comment]
I don't understand the approach. I've now tried copying over the org file that should tangle some smaller files to be included but I don't understand what the goal here is O:). The src blocks are not tangling to includefile.org when I C-c C-c or org-babel-tangle so they cannot be included.

**Comment by jkitchin** [comment]
The approach is if you have definitions in an include file they are used for lookup. That is not the same as a file that is tangled. 

you can also put them in an external file like glossary.tex and include them with

#+latex_header: \loadglsentries[main]{glossary}
