### ISSUE TITLE
bug in org-ref-make-format-function?

### ISSUE THREAD

**Issue by ustcscgy** [jkitchin/org-ref#63]
In (current master branch) https://github.com/jkitchin/org-ref/blob/d0cf2d1a6cff0f10a528e65849ef01f338911c40/org-ref.el#L1913 , shouldn't we unquote 'type'?

````
(if (string= (substring type -1) "s") 
==>
(if (string= (substring ,type -1) "s")
````

**Comment by jkitchin** [comment]
it looks like that should be done. I just pushed it. Thanks for reporting it!
