### ISSUE TITLE
[feature-request] org-ref for citing websites

### ISSUE THREAD

**Issue by jethrokuan** [jkitchin/org-ref#630]
Is there support for citing websites with org-ref? I'd love to use org-ref to cite websites for my personal notes, although I understand that the main purpose of org-ref is for academic papers/journals.

**Comment by jkitchin** [comment]
You can create @misc bibtex entries, e.g.:

```
@misc{scimax,
  Title =	 {scimax},
  Howpublished = {http://github.com/jkitchin/scimax},
  note =	 {scimax is an Emacs starter kit that customizes it for scientific
                  publishing.}
}
```
and then use org-ref to insert references.

Alternatively, you could use biblatex (see http://nschloe.blogspot.com/2009/06/bibtex-how-to-cite-website_21.html).

**Comment by jethrokuan** [comment]
Sorry for being unclear. What I meant was, similar to how org-ref is able to populate bibtex entries for academic papers, would it be possible for org-ref to do the same for website entries?

One could fetch the title and description from the website, and populate a bibtex entry. 
[org-cliplink](https://github.com/rexim/org-cliplink) fetches the title of the page. 

Let me know if it's out of the scope of org-ref.

**Comment by jagrg** [comment]
I don't think there's an easy way of getting the author and year of publication without some guessing. Are you thinking of this in the general sense (blog posts etc.), or is there a specific website you are wanting to cite?

**Comment by jethrokuan** [comment]
Some websites provide author and publication date information via meta tags, and where this is not available I think it's acceptable to leave it blank, or have a bibtex entry similar to misc entry just a few posts above.

I'm thinking of it in the general sense: I come across anything interesting and make a short note of it, and want to cite the original source in my compiled notes. I already do this for papers, and having website support included would be amazing.

**Comment by jkitchin** [comment]
Here is a basic outline of how to do what you want:

```
#+BEGIN_SRC emacs-lisp
(require 'org-cliplink)
(defun org-ref-insert-url-bibtex-entry (bibfile)
  (interactive (list (completing-read "Bibtex file: " (org-ref-find-bibliography))))
  (with-current-buffer (find-file-noselect bibfile)
    (goto-char (point-max))
    (unless (looking-at "^")
      (insert "\n"))
    (insert (format "@misc{,
  title =	 {%s},
  howpublished = {%s},
}"
		    (org-cliplink-retrieve-title-synchronously (org-cliplink-clipboard-content))
		    (org-cliplink-clipboard-content)))
    (bibtex-beginning-of-entry)
    (bibtex-clean-entry)))
#+END_SRC
```

If you copy this to the clipboard:
https://github.com/jkitchin/org-ref/issues/630

that function creates this entry in the bibfile you select:

@misc{issue,
  title =	 {{feature-request} org-ref for citing websites · Issue #630 · jkitchin/org-ref...},
  howpublished = {https://github.com/jkitchin/org-ref/issues/630},
}

**Comment by jagrg** [comment]
I tried implementing a first sketch of what you suggest (without org-cliplink) and it works in some cases.

;; finds title, author, and year
(html-to-bibtex-read "http://kitchingroup.cheme.cmu.edu/blog/2018/11/16/Line-integrals-in-Python-with-autograd/")
;; finds title and author
(html-to-bibtex-read "https://economics.utoronto.ca/osborne/latex/BIBTEX.HTM")
;; finds title and year
(html-to-bibtex-read "http://pragmaticemacs.com/emacs/write-code-comments-in-org-mode-with-poporg/")
;; finds title only
(html-to-bibtex-read "https://github.com/jkitchin/org-ref/issues/630#issuecomment-451346180")

(defun html-to-bibtex-read (url)
  "Read URL content and return title, author, and year fields."
  (let (fields)
    (with-current-buffer
	(url-retrieve-synchronously url t t)
      (goto-char (point-min))
      (when (re-search-forward "<span class=\"\\(.+?date.+?\\)>\\(.+\\)</span>" nil t)
	(let ((string (match-string-no-properties 2)))
	  (when (string-match "\\([0-9]\\{4\\}\\)" string)
	    (push (cons :year (match-string 1 string)) fields))))
      (goto-char (point-min))
      (when (re-search-forward "<meta name=\"author\" content=\"\\(.+\\)\">" nil t)
	(push (cons :author (match-string-no-properties 1)) fields))
      (goto-char (point-min))
      (when (re-search-forward "<title>\\(.+\\)</title>" nil t)
	(push (cons :title (match-string-no-properties 1)) fields)))
    fields))

(defun html-to-bibtex (bibfile)
  "Convert URL to bibtex entry."
  (interactive (list (completing-read "Bibtex file: " (org-ref-find-bibliography))))
  (let* ((url (if (s-match "^http" (car kill-ring))
		  (format "%s" (car kill-ring))
		(read-from-minibuffer "URL: ")))
	 (alist (html-to-bibtex-read url))
	 (title (assoc-default :title alist))
	 (author (assoc-default :author alist))
	 (year (assoc-default :year alist))
	 (urldate (format-time-string "%d %B %Y")))
    (with-current-buffer
	(find-file-noselect bibfile)
      (goto-char (point-max))
      (if (looking-at "^") (insert "\n") (insert "\n\n"))
      (insert (format "@misc{key,
  title =	 {%s},
  author =	 {%s},
  howpublished = {%s},
  year =	 {%s},
  note =	 {Online; accessed %s}
}" title author url year urldate))
      (bibtex-beginning-of-entry)
      (org-ref-clean-bibtex-entry))))

BTW I found this browser plugin (https://dmstern.github.io/html2biblatex/) that does something similar.

**Comment by jagrg** [comment]
I tried implementing a first sketch of what you suggest (without org-cliplink) and it works in some cases.

```elisp
;; finds title, author, and year
(html-to-bibtex-read "http://kitchingroup.cheme.cmu.edu/blog/2018/11/16/Line-integrals-in-Python-with-autograd/")
;; finds title and author
(html-to-bibtex-read "https://economics.utoronto.ca/osborne/latex/BIBTEX.HTM")
;; finds title and year
(html-to-bibtex-read "http://pragmaticemacs.com/emacs/write-code-comments-in-org-mode-with-poporg/")
;; finds title only
(html-to-bibtex-read "https://github.com/jkitchin/org-ref/issues/630#issuecomment-451346180")
```

```elisp
(defun html-to-bibtex-read (url)
  "Read URL content and return title, author, and year fields."
  (let (fields)
    (with-current-buffer
	(url-retrieve-synchronously url t t)
      (goto-char (point-min))
      (when (re-search-forward "<span class=\"\\(.+?date.+?\\)>\\(.+\\)</span>" nil t)
	(let ((string (match-string-no-properties 2)))
	  (when (string-match "\\([0-9]\\{4\\}\\)" string)
	    (push (cons :year (match-string 1 string)) fields))))
      (goto-char (point-min))
      (when (re-search-forward "<meta name=\"author\" content=\"\\(.+\\)\">" nil t)
	(push (cons :author (match-string-no-properties 1)) fields))
      (goto-char (point-min))
      (when (re-search-forward "<title>\\(.+\\)</title>" nil t)
	(push (cons :title (match-string-no-properties 1)) fields)))
    fields))

(defun html-to-bibtex (bibfile)
  "Convert URL to bibtex entry."
  (interactive (list (completing-read "Bibtex file: " (org-ref-find-bibliography))))
  (let* ((url (if (s-match "^http" (car kill-ring))
		  (format "%s" (car kill-ring))
		(read-from-minibuffer "URL: ")))
	 (alist (html-to-bibtex-read url))
	 (title (assoc-default :title alist))
	 (author (assoc-default :author alist))
	 (year (assoc-default :year alist))
	 (urldate (format-time-string "%d %B %Y")))
    (with-current-buffer
	(find-file-noselect bibfile)
      (goto-char (point-max))
      (if (looking-at "^") (insert "\n") (insert "\n\n"))
      (insert (format "@misc{key,
  title =	 {%s},
  author =	 {%s},
  howpublished = {%s},
  year =	 {%s},
  note =	 {Online; accessed %s}
}" title author url year urldate))
      (bibtex-beginning-of-entry)
      (org-ref-clean-bibtex-entry))))
```

BTW I found this browser plugin (https://dmstern.github.io/html2biblatex/) that does something similar.

**Comment by jethrokuan** [comment]
awesome! this definitely works well enough for my use. Thanks for the help. I'll leave this issue open, for you to determine if similar functionality should be checked into the org-ref repo.

**Comment by jagrg** [comment]
This is certainly useful, even with nil values it's easier to add the missing fields manually than it is to add the entire entry from scratch. The only problem I see with adding this to the source code is I don't think we can tweak things enough to make it reliable. Some functions are better off outside the source code (but easy enough for people to find). This one I think is somewhere in the middle so I'll let John decide.

**Comment by jkitchin** [comment]
This seems like a useful addition to org-ref, maybe in org-ref-url-utils.el. @jagrg do you want to make this into a pull request? I can also copy the code above in there, but a PR would make it easier to see who wrote it. 

I would suggest some changes to  html-to-bibtex:

1. Consider making an optional url argument, and use the clipboard if it is nil. It kind of looks like it should be that way since you interactively request the url anyway.
2. if not, note in the docstring that it uses the most recent kill for the url, and then prompts you for it.

**Comment by jagrg** [comment]
Done. Let me know if I missed something, or if there's anything else to address.

**Comment by andreas-h** [comment]
a PR for this was submitted by @jagrg at #635

**Comment by jkitchin** [comment]
> a PR for this was submitted by @jagrg at #635

I think there are some unresolved review comments in that PR that are keeping it from being merged.

**Comment by jagrg** [comment]
> I think there are some unresolved review comments in that PR that are keeping it from being
> merged.

I don't see any reviews. Is it something I need to do?

**Comment by jkitchin** [comment]
doh. There was a submit button I had not pressed. For many months. Talk about persistent state! Can you see it now?

**Comment by iris-garcia** [comment]
Is this really working? when I drag an drop a website url, I get for example:
- https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37
```
@misc{opencv_blur,
    url = {https://docs.opencv.org/4.3.0/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37},
    note = {Last accessed Mon Aug 17 14:06:58 2020}
  }
```
Then of course the cite shows the content of **note**, which is not very useful.

**Comment by treese** [comment]
It seems like it would make sense now for `org-ref-url-html-to-bibtex` to be called by default when drag-n-dropping a URL that doesn't refer to a DOI, so I submitted a pull request #850 to do that.
