### ISSUE TITLE
Follow cite links fails if two pdf exist with same beggining.

### ISSUE THREAD

**Issue by Xparx** [jkitchin/org-ref#633]
I came across an issue where if I have two files e.g. `AuthorYear.pdf` and `AuthorYearSupl.pdf` org-ref fails to follow the citation link.
My bibtex entry would be `AuthorYear`,

Doing a link `cite:AuthorYear` and then trying to follow it with `C-c C-o` would result in emacs telling me `org-ref-cite-candidates: Wrong type argument: stringp, nil`

**Comment by jkitchin** [comment]
Confirmed. Should be fixed in commit e43f3a9. Thanks for reporting that.

**Comment by Xparx** [comment]
After upgrading org-ref I now get q query on what pdf I want to follow. I'm assuming this is intended. If so it is working now!
Thanks.

**Comment by jkitchin** [comment]
yes, the default is if there is more than one matching pdf to ask you which one you want. That is defined in org-ref-get-pdf-filename. You can customize this in the variable org-ref-get-pdf-filename-function if you want to do something else.
