### ISSUE TITLE
C-left C-right behaviour around cite: jumps randomly. (Not really)

### ISSUE THREAD

**Issue by Xparx** [jkitchin/org-ref#636]
### NOTE: 
I just realized that `M-left` and `M-right` in the org document performs a similar operation within text as `C-left` and does not suffer from this behaviour below and that org-ref actually jumps between cite keywords with `C-left right`. So this might not be an issue after all.

### Original issue (I leave it here):
When I traverse my document I usually use key shortcuts like `C-left` `C-right` bound to `left-word` and `right-word` respectively.

When I use this within a citation key, specifically after the `cite:` using `C-left` this key makes the cursor jump whole documents or to the next cite key or randomly jump.

### Q (still have a question :-)
Is there a way to control this behaviour what `C-left right` does in a citation,  with a variable setting t or nil? I'm not sure I want to rely on `M-left right` as it does other actions when on markup text like headings.

**Comment by jkitchin** [comment]
There is a keymap defined on the links that does jump from link to link.

These are defined in `org-ref-cite-keymap`. You can probably use something like 

`(define-key org-ref-cite-keymap (kbd "C-<left>") nil)`

To undefine it in that map.

**Comment by Xparx** [comment]
Great! Thank you I will try that.

**Comment by Xparx** [comment]
That seemed to do it.
Thanks!
