### ISSUE TITLE
Can I have an absolute path for the bibliography when exporting to latex?

### ISSUE THREAD

**Issue by brabalan** [jkitchin/org-ref#638]
I use a system that does the export in a centralized place. Unfortunately it does not work with org-ref because a link like this
```
bibliography:/home/schmitta/projets/bib/alan.bib
```
is translated to this
```
\bibliography{../../projets/bib/alan}
```
and since the tex file is in a different directory that the org file, the bibliography is not found.

Is there a way to export an absolute path for the bibliography?

**Comment by jkitchin** [comment]
The easiest way to do this is to just redefine this function:

```
(defun org-ref-bibliography-format (keyword desc format)
  "Formatting function for bibliography links."
  (cond
   ((eq format 'org) (org-ref-get-org-bibliography))
   ((eq format 'ascii) (org-ref-get-ascii-bibliography))
   ((eq format 'md) (org-ref-get-md-bibliography))
   ((eq format 'odt) (org-ref-get-odt-bibliography))
   ((eq format 'html) (org-ref-get-html-bibliography))
   ((eq format 'latex)
    ;; write out the latex bibliography command
    (format "\\bibliography{%s}"
	    (replace-regexp-in-string
	     "\\.bib" ""
	     (mapconcat
	      'identity
	      (mapcar 'file-relative-name
		      (split-string keyword ","))
	      ","))))))
```

To do what you want. If you do this all the time, put the redefined function in your init files. If it is once in a while, you can do something like cl-flet in a build block in the org-file.

**Comment by brabalan** [comment]
Here is what I propose:
```emacs-lisp
  (defun org-ref-bibliography-format (keyword desc format)
    "Formatting function for bibliography links."
    (cond
     ((eq format 'org) (org-ref-get-org-bibliography))
     ((eq format 'ascii) (org-ref-get-ascii-bibliography))
     ((eq format 'md) (org-ref-get-md-bibliography))
     ((eq format 'odt) (org-ref-get-odt-bibliography))
     ((eq format 'html) (org-ref-get-html-bibliography))
     ((eq format 'latex)
      ;; write out the latex bibliography command
      (format "\\bibliography{%s}"
              (replace-regexp-in-string
               "\\.bib" ""
               (mapconcat
                'identity
                (mapcar (lambda (f)
                          (expand-file-name
                           f
                           (file-name-directory (org-export-output-file-name ".tex"))))
                        (split-string keyword ","))
                ","))))))
```

I tried using a relative file name, but `latexmk` did not like it when called from a directory different from where the tex file was. I think this is the most robust approach. One part I do not support is when this is called in a subtree with `EXPORT_FILE_NAME` set, but I'm not sure it would work in you original function either.

**Comment by philohistoria** [comment]
I encountered the same problem raised by @brabalan . I found his solution is working well for exporting subtree case, and with a `EXPORT_FILE_NAME` property. Thanks for the work!
