### ISSUE TITLE
The bibliography is not generated

### ISSUE THREAD

**Issue by juacq97** [jkitchin/org-ref#639]
Hi! I am writing a text, but when I export to latex with 'C-c C-e l o' all appointments are shown, but the bibliography at the end is not generated.
![Captura-2019-03-09_1](https://user-images.githubusercontent.com/7623047/54080068-99453f00-42a5-11e9-93c3-c1737ed7844d.png)
Cite shown.
![Captura-2019-03-09_2](https://user-images.githubusercontent.com/7623047/54080069-99453f00-42a5-11e9-9849-e8e7c40c1b8b.png)
No bibliography

Here's a copy of the header of the document:
```
#+title: Documento
#+author: Juan Adrián Castro Quintana
#+todo: REVISIÓN | LISTO 
#+todo: INCOMPLETO | COMPLETO
#+OPTIONS: toc:nil date:nil todo:nil
#+options: tags:nil
#+latex_class: koma-article
#+latex_header: \usepackage[margin=1in]{geometry}
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage{natbib}
#+CSL_STYLE: ~/.emacs.d/apa.csl
#+language: es
```
Of couse at the end I have

```
 bibliography:ref.bib
 bibliographystyle:apalike
```

And my config is
```
;;==== Org-ref ====
(use-package org-ref
  :ensure t)
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
```
Any idea why this happens? Thanks!

**Comment by jkitchin** [comment]
No idea. Usually it is a good idea to try compiling it at the command line to see if there are some errors that might be getting ignored by the emacs build process.
