### ISSUE TITLE
my bib file keeps popping out whenever I move curve to a cite:xxx. 

### ISSUE THREAD

**Issue by autosquid** [jkitchin/org-ref#64]
my bib file keeps popping out whenever I move curve to a field of cite:xxx.

**Comment by jkitchin** [comment]
Is this new? Are you using an up to date org-ref?

**Comment by autosquid** [comment]
I am using an up to date org-ref, the head version.

I noticed the problems weeks ago, so it not something new.

I used to get around the problem by removing or adding: `bibliography:xxx` in my org file.  It used to work. But not anymore.

I hope I could provide more information, but the message buffer says nothing..

**Comment by autosquid** [comment]
More info: I set  `org-ref-show-citation-on-enter` to nil, and the bib file window is not popping any more, but the info of citation is not shown in minibuffer too at the same time.

**Comment by jkitchin** [comment]
That is pretty baffling. that shouldn't be happening. org-ref-show-citation-on-enter controls whether a timer function is run which gives you some context about org-ref links when the point is on them. when was the last time you pulled? the message "no changes need to be saved" should have disappeared pretty recently.

**Comment by autosquid** [comment]
My last pull is : 20151115   Is it possible some package else opens the bib buffer? for example, helm-bibtex?

**Comment by jkitchin** [comment]
This bib file does get visited when you put the point on the link to construct the message. But, as far as I can see it is always visited in a temp buffer to avoid exactly what you are describing. I haven't been able to reproduce this so far. I don't think helm-bibtex is doing anything during this visit, but maybe reftex is.

**Comment by autosquid** [comment]
@jkitchin  thx, I'll search more about reftex.

**Comment by jkitchin** [comment]
what do you have this variable set to: org-ref-cite-onclick-function

**Comment by autosquid** [comment]
Its value is org-ref-cite-click-helm

**Comment by jkitchin** [comment]
what is your emacs version?

uuplusu writes:

> Its value is org-ref-cite-click-helm
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/64#issuecomment-157689384

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by autosquid** [comment]
@jkitchin  The problem disappears like a miracle after a package-update with `paradox`. I don't known which package updated removes the problem... However I believe it's fault  of some package else. Probably `helm-bibtex` or `cdlatex` as far as I can see from the update history.

By the way, I am using emacs 24.5.1.

Thanks for your kind help and your patience.

**Comment by jkitchin** [comment]
Thanks for letting me know! I am glad to hear it is finally working for you. Best wishes,
