### ISSUE TITLE
Best install method for doi-utils; org-ref-bibtex

### ISSUE THREAD

**Issue by borgauf** [jkitchin/org-ref#643]
I've got this code in my init:

(use-package doi-utils
  :ensure t
  :after org)

(use-package org-ref-bibtex
  :after org
  :init
  (setq org-ref-bibtex-hydra-key-binding "\C-cj"))

I'm not sure where I got this code, but it errors out. There is no ELPA for these, correct? What's the best way to install these? So if I've got org-ref from an ELPA repo (it shows up as a "dependency"), do doi-utils and org-ref-bibtex need to be separately installed? If so, what's the best way?

**Comment by jkitchin** [comment]
See https://github.com/jkitchin/org-ref#package-installation-via-melpa.

If you have the repositories already setup, I think this is the use-package incantation that you want:

```
(use-package org-ref 
  :init (setq org-ref-bibtex-hydra-key-binding (kbd "C-c j")))
```
