### ISSUE TITLE
how to rename pdf file names and cite links after clean-entries?

### ISSUE THREAD

**Issue by wztdream** [jkitchin/org-ref#644]
Dear sir,
After run clean-entries, the key of the entry may be changed.  As the link between a bib item and the pdf file, and the link between bib item and the notes item are both the key of the bib entry. If we run clean-entries and there may be huge mounts of pdf file names or notes entries need to update.  So it seem the link is not robust. Is it possible to add a function to clean-entries that rename the pdf file name and the notes entry name automatically in order to keep the link between them safe?

**Comment by jkitchin** [comment]
There is nothing build in for this, but you can write your own function and add it to one of the hooks, e.g. org-ref-clean-bibtex-entry-hook. You could, for example replace the call to orcb-key with one that checks if there is a pdf, and renames it before changing the key.

**Comment by wztdream** [comment]
Thank you, I am learning elisp now, I will try when I am ready.

**Comment by wztdream** [comment]
Dear sir,
I follow your suggestion to replace orcb-key with a new function my-orcb-key, and add the function to update pdf file name and notes items(custom id and cite link in the notes file). Following are the code.
The method I used is simple, just search the old key and replace it with new key.
It can work, but for the function "my-update-notes-item (old-key new-key)". There is some bug I do not know why. After clean-entry, the cite link in notes shows "not found link", but the the link is “literally" correct.　How ever after a few minutes or by insert new cite link in the notes buffer,  the abnormal cite link works fine. I think this is due to I just update the cite link by changing the word, not consider the format of the link. Also seems the notes buffer need to "refresh" after change. I have no idea how to do these. Any suggestions how to solve this bug? Another question,  if I want to update all the cite links of .org files, how should I do? Just search each file and update it? Any better method?

`;; a function that rename the pdf file when update the bib entry key, in order to keep the link save.
(defun my-orcb-key ()
  
  "Replace the key in the entry, also change the pdf file name if it exites."
  (let ((key (funcall org-ref-clean-bibtex-key-function
		      (bibtex-generate-autokey))))
    ;; first we delete the existing key
    (bibtex-beginning-of-entry)
    (re-search-forward bibtex-entry-maybe-empty-head)

    (setq old-key (match-string 2));;store old key

    (if (match-beginning bibtex-key-in-head)
	(delete-region (match-beginning bibtex-key-in-head)
		       (match-end bibtex-key-in-head)))
    ;; check if the key is in the buffer
    (when (save-excursion
	    (bibtex-search-entry key))
      (save-excursion
	(bibtex-search-entry key)
	(bibtex-copy-entry-as-kill)
	(switch-to-buffer-other-window "*duplicate entry*")
	(bibtex-yank))
      (setq key (bibtex-read-key "Duplicate Key found, edit: " key)))
    (insert key)
    (kill-new key)

    (save-excursion
      "update pdf names and notes items"
      ;; rename the pdf after change the bib item key
      (my-update-pdf-names old-key key)
      ;; renmae the notes item after change the bib item key
      (my-update-notes-item old-key key))))


;; define a function that update the pdf file names before change the key of a bib entry

(defun my-update-pdf-names (old-key new-key)
  
  (setq old-filename (concat org-ref-pdf-directory old-key ".pdf"))
  (setq new-filename (concat org-ref-pdf-directory new-key ".pdf" ))
  (if (file-exists-p old-filename)
      (rename-file old-filename new-filename))


  )
;; define a function that update the notes items before change the key of bib entry

(defun my-update-notes-item (old-key new-key)
  "update a notes item of a old-key by a new-key in case the bib item is changed"
  (find-file-literally org-ref-bibliography-notes)
  
  ;; move to the beginning of the buffer

  (goto-char (point-min))
  ;; find the string and replace it

  (setq newcite new-key)
  (setq regstr old-key)

    (while (re-search-forward regstr nil t)

      (setq str (match-string 0))

      (delete-region (match-beginning 0)
		     (match-end 0))
      (insert newcite)

      )
    
    ;; save the buffer

    (save-buffer)

  )
`

**Comment by wztdream** [comment]
> There is nothing build in for this, but you can write your own function and add it to one of the hooks, e.g. org-ref-clean-bibtex-entry-hook. You could, for example replace the call to orcb-key with one that checks if there is a pdf, and renames it before changing the key.

Dear sir,
Ｉ am stuck here, have no idea how to update the cite link correctly instead of replacing the word of the link directly. Hope you can give some guidance. Many thanks! Org-ref is a great work!

**Comment by jkitchin** [comment]
There could be a few reasons for what you see. One is the the tooltip will use the version on disk I think, not the version in the buffer, so you need to make sure the bib file has been saved after you modify it. Another might be related to fontification, that is, you might need to call font-lock-fontify-buffer at the end of the function that does this in the bib-file.

I don't know of a better way to update all the citations in an org-file other than find and replace.

**Comment by wztdream** [comment]
@jkitchin Thank you sir, you are right, it is due to I **did not save the bib file**, now the function works fine!
Following are the code for other people to reference:

You need to replace "orcb-key" with "my-orcb-key" , as shown below, in "org-ref-clean-bibtex-entry-hook"

```
;; a function that rename the pdf file when update the bib entry key, in order to keep the link safe.
(defun my-orcb-key ()
  
 "Replace the key in the entry, also change the pdf file name if it exites."

(let ((key (funcall org-ref-clean-bibtex-key-function
		      (bibtex-generate-autokey))))
    ;; first we delete the existing key
    (bibtex-beginning-of-entry)
    (re-search-forward bibtex-entry-maybe-empty-head)

    (setq old-key (match-string 2));;store old key

    (if (match-beginning bibtex-key-in-head)
	(delete-region (match-beginning bibtex-key-in-head)
		       (match-end bibtex-key-in-head)))
    ;; check if the key is in the buffer
    (when (save-excursion
	    (bibtex-search-entry key))
      (save-excursion
	(bibtex-search-entry key)
	(bibtex-copy-entry-as-kill)
	(switch-to-buffer-other-window "*duplicate entry*")
	(bibtex-yank))
      (setq key (bibtex-read-key "Duplicate Key found, edit: " key)))
    (insert key)
    (kill-new key)

    (save-excursion 
      "update pdf names and notes items"
      ;; rename the pdf after change the bib item key
      (my-update-pdf-names old-key key)
      ;; renmae the notes item after change the bib item key
      (my-update-notes-item old-key key))
    
    ;; save the buffer
    (setq require-final-newline t)
    (save-buffer)))


;; define a function that update the pdf file names before change the key of a bib entry

(defun my-update-pdf-names (old-key new-key)
  (let ((old-filename (concat org-ref-pdf-directory old-key ".pdf"))
	(new-filename (concat org-ref-pdf-directory new-key ".pdf" )))
    (if (file-exists-p old-filename)
	(rename-file old-filename new-filename))))


;; define a function that update the notes items before change the key of bib entry

(defun my-update-notes-item (old-key new-key)
  "update a notes item of a old-key by a new-key in case the bib item is changed"

  (set-buffer (find-file-noselect org-ref-bibliography-notes))	
  ;; move to the beginning of the buffer
  (goto-char (point-min))
  ;; find the string and replace it
  (let ((newcite new-key)
	(regstr old-key))

    (while (re-search-forward regstr nil t)

      (delete-region (match-beginning 0)
		     (match-end 0))
      (insert newcite))

      ;; save the buffer
    (setq require-final-newline t)
    (save-buffer)
    (kill-buffer)))
