### ISSUE TITLE
make note before trying to download pdf

### ISSUE THREAD

**Issue by feng823** [jkitchin/org-ref#648]
Hi,
I think it may be better that make note before downloading the pdf file because the pdf downloading operation is often blocked due to different reasons. When I cancelled the operation, the note making operation is also cancelled. So my suggestion is making note before pdf downloading.

`(defun doi-utils-insert-bibtex-entry-from-doi (doi)
  "Insert bibtex entry from a DOI.
Also cleans entry using ‘org-ref’, and tries to download the corresponding pdf."
  (insert (doi-utils-doi-to-bibtex-string doi))
  (backward-char)
  ;; set date added for the record
  (let ((ts (funcall doi-utils-timestamp-format-function)))
    (when ts
      (bibtex-set-field doi-utils-timestamp-field
			ts)))
  (org-ref-clean-bibtex-entry)
  (save-buffer)

  (when (and doi-utils-make-notes org-ref-bibliography-notes)
    (save-excursion
      (when (f-file? org-ref-bibliography-notes)
	(find-file-noselect org-ref-bibliography-notes)
	(save-buffer))
      (let ((bibtex-completion-bibliography (list (buffer-file-name))))
	(funcall doi-utils-make-notes-function))))
  ;; try to get pdf
  (when doi-utils-download-pdf
    (doi-utils-get-bibtex-entry-pdf))
  )
`

**Comment by jkitchin** [comment]
Thanks for the suggestion. fixed.
