### ISSUE TITLE
Depend on ol-bibtex instead of org-bibtex

### ISSUE THREAD

**Issue by tarsius** [jkitchin/org-ref#649]
`org-bibtex.el` has been renamed to `ol-bibtex.el`, see https://code.orgmode.org/bzg/org-mode/commit/499c0a50cc4b11e37b91374af23cb27ab8fc20d2, so you should depend on `ol-bibtex`. Because the change to Org has not made it into a release yet, you might want to soft depend on both features for the time being.

**Comment by jkitchin** [comment]
Thanks. I think e1fb697 should fix this.

**Comment by jkitchin** [comment]
Got it, thanks for the solution too!
