### ISSUE TITLE
BibTeX for arXiv articles

### ISSUE THREAD

**Issue by tmalsburg** [jkitchin/org-ref#65]
I saw that you use an third-party service to retrieve BibTeX for asXiv articles.  I have code for generating BibTeX for arXiv entries.  It uses arXiv's API to retrieve an XML record and then formats a BibTeX entry.  

``` elisp
(defvar arxiv-entry-format-string "@article{%s,
  title = {%s},
  author = {%s},
  archivePrefix = {arXiv},
  year = {%s},
  eprint = {%s},
  primaryClass = {%s},
  abstract = {%s},
  url = {%s},
}")

(defun retrieve-bibtex-from-arxiv (id)
  "Given an arXiv id, this function retrieves the metadata of the
article from arXiv and returns a string containing a BibTeX entry."
  (let ((url-buffer (url-retrieve-synchronously (format "http://export.arxiv.org/api/query?id_list=%s" id) t)))
    (with-current-buffer url-buffer
      (let* ((parse-tree (libxml-parse-xml-region
                         (progn (goto-char 0)
                                (search-forward "<?xml ")
                                (match-beginning 0))
                         (point-max)))
             (entry (assq 'entry parse-tree))
             (authors (--map (nth 2 (nth 2 it))
                             (--filter (and (listp it) (eq (car it) 'author)) entry)))
             (year (format-time-string "%Y" (date-to-time (nth 2 (assq 'published entry)))))
             (key (make-bibtex-key authors year))
             (title (nth 2 (assq 'title entry)))
             (names (bibtexify-authors authors))
             (id (-last-item (s-split "/" (nth 2 (assq 'id entry)))))
             (category (cdar (nth 1 (assq 'primary_category entry))))
             (abstract (s-trim (nth 2 (assq 'summary entry))))
             (url (nth 2 (assq 'id entry))))
        (format arxiv-entry-format-string key title names year id category abstract url)))))

;; Demo:
(retrieve-bibtex-from-arxiv "1506.04967v1")
```

If you are interested, I can make a PR for arxiv.el.

**Comment by jkitchin** [comment]
I would welcome a PR.

Titus von der Malsburg writes:

> I saw that you use an third-party service to retrieve BibTeX for asXiv articles.  I have code for generating BibTeX for arXiv entries.  It uses arXiv's API to retrieve an XML record and then formats a BibTeX entry.
>
> ``` elisp
> (defun retrieve-bibtex-from-arxiv (id)
>   "Given an arXiv id, this function retrieves the metadata of the
> article from arXiv and returns a string containing a BibTeX entry."
>   (let ((url-buffer (url-retrieve-synchronously (format "http://export.arxiv.org/api/query?id_list=%s" id) t)))
>     (with-current-buffer url-buffer
>       (let* ((parse-tree (libxml-parse-xml-region
>                          (progn (goto-char 0)
>                                 (search-forward "<?xml ")
>                                 (match-beginning 0))
>                          (point-max)))
>              (entry (assq 'entry parse-tree))
>              (authors (--map (nth 2 (nth 2 it))
>                              (--filter (and (listp it) (eq (car it) 'author)) entry)))
>              (year (format-time-string "%Y" (date-to-time (nth 2 (assq 'published entry)))))
>              (key (make-bibtex-key authors year))
>              (title (nth 2 (assq 'title entry)))
>              (names (bibtexify-authors authors))
>              (id (-last-item (s-split "/" (nth 2 (assq 'id entry)))))
>              (category (cdar (nth 1 (assq 'primary_category entry))))
>              (abstract (s-trim (nth 2 (assq 'summary entry))))
>              (url (nth 2 (assq 'id entry))))
>         (format arxiv-entry-format-string key title names year id category abstract url)))))
>
> ;; Demo:
> (retrieve-bibtex-from-arxiv "1506.04967v1")
> ```
>
> If you are interested, I can make a PR for arxiv.el.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/65

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
