### ISSUE TITLE
Suggestion: Give/document a way to set .bib files independent of the [[bibliography... link.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jkitchin/org-ref#650]
I need to be able to export to both PDFs and `.docx` files with as little of manual configuration as possible. Exporting citations and cross-references is a *sine qua non*.

I came to the following  tentative conclusions:

- `org-ref` labels and references do not export currently to anything else than the built-in LaTeX exporter. `Org`'s `#+NAME:`s and `#+CAPTION`s are normally exported.
- The built-in exporter to `.odt` can be used to convert to `.docx`, but the citations (either LaTeX `\cile` or org's `cite:` links) do not export to.odt/.docx.
- The `ox-pandoc` exporter correctly exports org's native cross-references (#+NAME:`s and `#+CAPTION`s), Latex `\cite` citations and `otrg-ref`'s `cite:` links ; **BUT**
- this exporter dumps the references fporatted as titles, otr dumps them *twice*, the second one being correctly formatted.

I found a workaround allowing to use `org-ref` for this double-export duty, by creating a small function returning either the `[[bibliography...` link or the relevant `#+BIBLIOGRAPHY:` option as needed by the current exporter. See the attached `Minimal-bib-bis.*` in the attached archive (only format tolerated by Github...).

[Minimal-bib-bis.zip](https://github.com/jkitchin/org-ref/files/3123923/Minimal-bib-bis.zip)

This workaround has one weak point : `org-ref-helm-insert-cite-link` does not know the `.bib` file(s) used in the text ; I can insert references with `org-reftex-citation`, which gives me a LaTeX `\cite` field, which I can manually edit as an `org-ref` `cite:` link (this is not really necessary).

My suggestion is to create/document a way to give `org-ref-helm-insert-cite-link` the information relative to the `.bib` file(s) used in the document.

**Comment by jkitchin** [comment]
The easiest way might be to use local file variables. org-ref-helm-insert-cite-link falls back to org-ref-default-bibliography if it doesn't find anything in the file. So you can set this variable as a file-local-variable to point to whatever you want, and you should be able to use the insert cite link function with that bibfile.

There isn't much that can be done about the labels/ref exports that will work with vanilla exporters. There might be some hope in converting them to an org syntax in a preprocessing step, and then exporting that. That would, for example, fix the issue of getting numbered cross-references in html export. 

I can't test ox-pandoc right now, it seems I have a version incompatibility at the moment.

**Comment by EmmanuelCharpentier** [comment]
Ddear John,

Thank you for this prompt answer.

I have to read and understand `org-mode` and `org-ref` code to understand what happens. This will be long (I'm not much of a programmer), and I'll refrain from pursuing this issue before understanding what `org-ref` and the exporters do.

I have a quite different suggestion, which I'll file separately.

Thanks again !
