### ISSUE TITLE
Empty @article when using pubmed-insert

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#651]
When I use pubmed-insert-bibtex-from-pmid the `@article{,` field of the retrieved entry is empty.

If I remember correctly there is a way to auto-generate these fields, but I can't remember which command that was exactly. Could anyone please point me to the right command?

**Comment by jkitchin** [comment]
There is a function like doi-utils-update-field and doi-utils-update-bibtex-entry-from-doi but it should only work if there is a doi in the entry. It will also only work if the data exists in the doi data that gets retrieved.
