### ISSUE TITLE
Void functions with ivy

### ISSUE THREAD

**Issue by alexDarcy** [jkitchin/org-ref#653]
Hi, 

I'm using ivy and I have found that some functions are not defined when I call them for the first time. Here is what I 've found : 

`doi-utils-add-bibtex-entry-from-doi` does not work the first time (called with `M-x`) : 

    Debugger entered--Lisp error: (void-function org-ref-possible-bibfiles)
      org-ref-possible-bibfiles()
      doi-utils-add-bibtex-entry-from-doi("10.2307/j.ctt7sd01")
      funcall-interactively(doi-utils-add-bibtex-entry-from-doi "10.2307/j.ctt7sd01")
      call-interactively(doi-utils-add-bibtex-entry-from-doi record nil)
      command-execute(doi-utils-add-bibtex-entry-from-doi record)
      #f(compiled-function (cmd) #<bytecode 0x2e8a061>)("doi-utils-add-bibtex-entry-from-doi")
      ivy-call()
      ivy-read("M-x " ("doi-utils-add-bibtex-entry-from-doi" "org-ref-bibtex-entry-doi" "server-force-delete" "mu4e" "counsel-org-agenda-headlines" "set-variable" "eshell" "eval-buffer" "server-start" "server-mode" "ag" "grep" "load-file" "comment-dwim" "list-packages" "load-theme" "ivy-recentf" "package-install" "dired" "rgrep" "mentor" "org-goto" "counsel-ag" "org-set-tags" "avy-goto-char" "revert-buffer" "bundle-console" "comment-region" "customize-group" "pdf-tools-install" "evil-avy-goto-line" "find-file-at-point" "evil-avy-goto-word-0" "evil-avy-goto-word-1" "keychain-refresh-environment" "evilnc-copy-and-comment-lines" "color-theme-sanityinc-solarized-dark" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" ...) :predicate nil :require-match t :history counsel-M-x-history :action #f(compiled-function (cmd) #<bytecode 0x2e8a061>) :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
      counsel-M-x()
      funcall-interactively(counsel-M-x)
      call-interactively(counsel-M-x nil nil)
      command-execute(counsel-M-x)

`org-ref-ivy-cite-completion` does not work (called with `M-x`too)

    Debugger entered--Lisp error: (void-variable org-ref-insert-cite-key)
      byte-code("\303 \210\304\010\305\011!\n#\207" [org-mode-map org-ref-insert-cite-key org-ref-insert-link-function org-ref-ivy-cite-completion define-key kbd] 4)
      autoload-do-load((autoload "org-ref-ivy-cite" "Use ivy for completion.\n\n(fn)" t nil) org-ref-ivy-cite-completion)
      command-execute(org-ref-ivy-cite-completion record)
      #f(compiled-function (cmd) #<bytecode 0x2fa4825>)("org-ref-ivy-cite-completion")
      ivy-call()
      ivy-read("M-x " ("doi-utils-add-bibtex-entry-from-doi" "org-ref-helm-insert-cite-link" "org-ref-helm-insert-ref-link" "mu4e" "org-ref-bibtex-entry-doi" "server-force-delete" "eval-buffer" "server-start" "server-mode" "crossref-add-bibtex-entry" "set-variable" "ag" "grep" "eshell" "load-file" "comment-dwim" "list-packages" "doi-add-bibtex-entry" "counsel-org-agenda-headlines" "load-theme" "ivy-recentf" "package-install" "dired" "rgrep" "mentor" "org-goto" "counsel-ag" "org-set-tags" "avy-goto-char" "revert-buffer" "bundle-console" "comment-region" "customize-group" "pdf-tools-install" "evil-avy-goto-line" "find-file-at-point" "evil-avy-goto-word-0" "evil-avy-goto-word-1" "keychain-refresh-environment" "evilnc-copy-and-comment-lines" "color-theme-sanityinc-solarized-dark" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" ...) :predicate nil :require-match t :history counsel-M-x-history :action #f(compiled-function (cmd) #<bytecode 0x2fa4825>) :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
      counsel-M-x()
      funcall-interactively(counsel-M-x)
      call-interactively(counsel-M-x nil nil)
      command-execute(counsel-M-x)

However, once I've called `org-ref-helm-insert-cite-link` : 
- `doi-utils-add-bibtex-entry-from-doi` runs OK
- `org-ref-ivy-cite-completion` raises no errors but returns no result

It may be a configuration issue but I don't know how to proceed. Thanks !

**Comment by jkitchin** [comment]
hm. This sounds like some kind of autoload issue. I don't see it myself. What is your configuration?

**Comment by alexDarcy** [comment]
Hi,

Here is a minimal working configuration file reproducing the issue (I use a fork from Purcell's config initially) : 

    ;; Produce backtraces when errors occur
    (setq debug-on-error t)
    
    (require 'package)
    
    ;;; Install into separate package dirs for each Emacs version, to prevent bytecode incompatibility
    (let ((versioned-package-dir
           (expand-file-name (format "elpa-%s.%s" emacs-major-version emacs-minor-version)
                             user-emacs-directory)))
      (setq package-user-dir versioned-package-dir))
    
    ;;; On-demand installation of packages  
    (defun require-package (package &optional min-version no-refresh)
      "Install given PACKAGE, optionally requiring MIN-VERSION.
    If NO-REFRESH is non-nil, the available package lists will not be
    re-downloaded in order to locate PACKAGE."
      (or (package-installed-p package min-version)
          (let* ((known (cdr (assoc package package-archive-contents)))
                 (versions (mapcar #'package-desc-version known)))
            (if (cl-find-if (lambda (v) (version-list-<= min-version v)) versions)
                (package-install package)
              (if no-refresh
                  (error "No version of %s >= %S is available" package min-version)
                (package-refresh-contents)
                (require-package package min-version t))))))
    
    ;;; Fire up package.el
    (setq package-enable-at-startup nil)
    (package-initialize)
    
    ;; Org-ref
    (require-package 'org-ref)
    
    (setq reftex-default-bibliography '("~/projects/library/references.bib"))
    
    ;; see org-ref for use of these variables
    (setq org-ref-bibliography-notes "~/projects/library/reading-list.org"
          org-ref-default-bibliography '("~/projects/library/references.bib")
          org-ref-pdf-directory "~/projects/library/bibtex-pdfs/")
    
    (provide 'init)

Emacs is started with 

    emacs --load .emacs.d/debug-org.el -q --debug-init

**Comment by jkitchin** [comment]
Can you try adding this and see if it alleviates the problem:

```
(setq org-ref-completion-library 'org-ref-ivy-cite)
(require 'org-ref-ivy-cite)
```

**Comment by alexDarcy** [comment]
Thanks for the quick answer. If I use `(require 'org-ref)` it works !

```
(require 'org-ref)
(setq org-ref-completion-library 'org-ref-ivy-cite)
(require 'org-ref-ivy-cite)
```

Using  `(require-package 'org-ref)` gives an error while starting up Emacs : 

```
Debugger entered--Lisp error: (void-variable org-ref-insert-cite-key)
  byte-code("\303 \210\304\010\305\011!\n#\207" [org-mode-map org-ref-insert-cite-key org-ref-insert-link-function org-ref-ivy-cite-completion define-key kbd] 4)
  require(org-ref-ivy-cite)
  eval-buffer(#<buffer  *load*> nil "/home/alex/.emacs.d/debug-org.el" nil t)  ; Reading at buffer position 1346
  load-with-code-conversion("/home/alex/.emacs.d/debug-org.el" "/home/alex/.emacs.d/debug-org.el" nil t)
  load("/home/alex/.emacs.d/debug-org.el" nil t)
  command-line-1(("--load" ".emacs.d/debug-org.el"))
  command-line()
  normal-top-level()
```
