### ISSUE TITLE
Move instead of copy when using org-ref-pdf-to-bibtex 

### ISSUE THREAD

**Issue by Horsevad** [jkitchin/org-ref#656]
Hi

I often use org-ref-pdf-to-bibtex  to add already downloaded pdf-s to my bibliography and notes, and this function does not have any option to move the file instead of copying it, and therefore I end up manually deleting the duplicates.

Is it possible to make some adjustment so this could be customized, to move the file instead of copying ?

Thanks

**Comment by jkitchin** [comment]
Let me know if e95f343 resolves this for you.

**Comment by Horsevad** [comment]
Thanks for the quick fix, Might I suggest to add something like the following function to the package. 

When it moves the file, it changes the buffers file and name to the new file where org-ref has stored it. Such that you don't have to manually re-open the .pdf 

;; Basically a modified version of move-buffer-file from Steve Yeggs .emacs
(defun my/org-ref-move-buffer-file (oldname newname)
  "moves both current buffer and file it's visiting to DIR."
  (interactive "DNew directory: ")
  (progn 
    (copy-file oldname newname 1)
    (delete-file oldname)
    (set-visited-file-name newname)
    (set-buffer-modified-p nil)
    t))

(setq org-ref-pdf-to-bibtex-function 'my/org-ref-move-buffer-file)
