### ISSUE TITLE
doi-utils-get-bibtex-entry-pdf does not download the pdf

### ISSUE THREAD

**Issue by asikstel** [jkitchin/org-ref#657]
Hi,

`doi-utils-get-bibtex-entry-pdf` says `No pdf was downloaded.` , however opens the correct pdf in browser. 

Emacs 27.1 from git, Mac OS X with Opera, fresh org ref from Melpa.

Furthermore, it would be real nice, if `org-ref-bibtex-assoc-pdf-with-entry` would add a file entry with the path to the pdf it just has associated (i.e. put the pdf into the default folder, then add file field to the .bib entry pointing to the pdf in the default folder).

**Comment by jkitchin** [comment]
I don't think that is an error. Some websites do not make it easy to download a pdf, even when you can open a pdf in the browser. Probably org-ref did not download the pdf, although you can do that manually from the open page.

**Comment by averter** [comment]
Big plus one on adding a file field on the created bibtex entry with the path to the pdf that was just downloaded (if it was downloaded).
