### ISSUE TITLE
adding note causes emacs to lock-up with 100% CPU

### ISSUE THREAD

**Issue by mirkov** [jkitchin/org-ref#658]
Hello,

This is on Windows, Emacs 26.1, org 9.1.2, and org-ref e95f343 of June 6, 2019. I just started using org-ref.

When on citation I try to create a note, Emacs will lock up.  I have to kill it from the task manager.  I have been unable to debug it, since I get no traceback error.  

Can someone give me a pointer what functions to edebug, so that I try to narrow-down the cause of the problem?

(In issue 160, it was mentioned that the notes model may be obsolete - so should I even be trying to use notes?)

Thank you,

Mirko

**Comment by jkitchin** [comment]
Can you tell me exactly what sequence of keystrokes/mouse clicks leads to this? preferrably with a small example org file and bibtex entry that causes it for you?

**Comment by mirkov** [comment]
I isolated the problem to a short startup file and a short org file (attached the with extension ".txt" because github did not like the .el extension)

After removing the ".txt" extensions start emacs like so:  `emacs -q --no-splash -l startup.el`.  Emacs opens with the notes.org buffer.

startup.el defines the load-path as it is on my laptop, initializes org-ref, and reads notes.org (see the file for comments)

It turns out that defining the three bibtex-completion-... variables causes Emacs to lock up.  See startup.el for comment and how to turn that on or off.

Note that while my org-ref is recent, I use melpa-provided libraries it depends on.  

[notes.org.txt](https://github.com/jkitchin/org-ref/files/3288657/notes.org.txt)
[startup.el.txt](https://github.com/jkitchin/org-ref/files/3288658/startup.el.txt)

**Comment by jkitchin** [comment]
I still don't totally understand when is emacs locking up, is just from opening the notes file? or when you click on a cite link to add a note? I have all of those bibtex-completion variables unset (or nil). Do you set them for something else? 

i haven't been able to reproduce what you describe from those two files.

**Comment by mirkov** [comment]
Thank you for looking into this.  

When I set the bibtex-completion variables to files or directories, Emacs locks up.  If I set them to NIL, or just don't touch them, Emacs loads notes.org fine.

The first of the attached files will cause Emacs to lock up when started as `emacs -q -l startup....`

[startup-with-bibtex-completion-set-to-files-and-directories.el.txt](https://github.com/jkitchin/org-ref/files/3299482/startup-with-bibtex-completion-set-to-files-and-directories.el.txt)
[startup-with-bibtex-completion-set-to-nil.el.txt](https://github.com/jkitchin/org-ref/files/3299483/startup-with-bibtex-completion-set-to-nil.el.txt)
[startup-without-bibtex-completion-setting.el.txt](https://github.com/jkitchin/org-ref/files/3299484/startup-without-bibtex-completion-setting.el.txt)

**Comment by jkitchin** [comment]
If you leave the org-ref out of this, does it still lock up with the bibtex-completion variables set?  i.e. comment out the (require 'org-ref) line and does it still lock up? If it does then this seems like a helm-bibtex issue. If it doesn't then something is happening in org-ref. Since it happens on opening, I guess it is in font-lock maybe. It is weird though, I would think that every org file should be freezing, not just the notes.org file. Do other org files open fine?

Another thing to try while it is locked up is from a shell (like a git bash shell) see if you can run

`ps aux | grep | Emacs` to get the pid for Emacs, and then see if you can run `kill -USR2 {pid}`. I am not sure if that works in windows, but it sometimes will interrupt whatever is hanging and enter the debugger so you can see what it was doing when it froze. sometimes I have to send several kill commands before it gets to the debugger, and it doesn't always work.

I guess you could also try something like this:

```
(let ((org-mode-hook '()))
  (find-file org-ref-bibliography-notes))
```

with the bibtex-completion-* defined. Here I guess the problem is in an org-mode-hook. some of those functions are org-ref related. If that also freezes then that would rule those out.

**Comment by mirkov** [comment]
Experiment results:

- killing emacs process does not drop me into debugger (What is the `-USR2` switch?  On Windows' MSYS2, kill does not have the U, S, R, 2 switches)
- If I skip loading `org-ref`, emacs does not lock up
- If I set `org-mode-hook` to '(), emacs does lock up
- emacs does not lock up if I load a different org file, `not-notes.org`

Observation:  When I load a not-notes.org file, I get a message 
`~/documents/the-works/bibliographies/notes.org and c:/Users/977315/Documents/the-works/BiBliographies/notes.org are the same file`

I don't know where that message comes from.

**Comment by jkitchin** [comment]
That sure sounds like some strange interaction with org-ref. Does the not-notes.org have any citation links in it?

If you delete the cite links in your notes file does it still lock up?

-USR2 sends a USR2 signal to a process. For emacs it means try to interrupt whatever is going on. It works on Macs and Linux, but not apparently in the shell you are using. It is less severe than -9 which is a kill.

**Comment by mirkov** [comment]
A brief update: I was able to create a case that allows me to trace the elisp code before emacs freezes.  I will post an update in a day or so - busy at work right now.

**Comment by jkitchin** [comment]
👍 I will be traveling for the next 10 days or so. When I am back I look forward to taking a look at it. Thanks for the debugging effort!

**Comment by mirkov** [comment]
The problem has gone away and I am closing the issue.

I think the problem was solved by updating *everything*:
- I brought my Emacs to version 26.2.  
- I downloaded and ran `org-ref-melpa.el` from [https://kitchingroup.cheme.cmu.edu/blog/category/orgref/](url).  

I now have a comfortable referencing environment on Windows 10, MSYS2's Emacs 26.2, org-mode, org-ref.

Thank you for your help so far.
