### ISSUE TITLE
prescript in apacite format support?

### ISSUE THREAD

**Issue by japhir** [jkitchin/org-ref#659]
Apacite uses the format `\cite<prescript>[postscript]{citekey}`. The journal I'm writing a paper for uses this and the `\citeA` version of the command for in-text citations. I've managed to add the second to org-ref with the following code:
```
  (org-ref-define-citation-link "citeA" ?A)
```
but the prescript calls I can only implement with the suggested `[[cite:Defliese2015,Murray2016,Muller2017][<e.g.,>]]` format, then after exporting to latex doing a manual regex `s/\[<\(.*\)>\]/<\1>/g`.

Is there a way to define an alternative pre-postscript format for latex export? Or if not, is there a dirty hack with a post-export hook to latex that I can use?

Thanks for the amazing package! :)

**Comment by jkitchin** [comment]
You can use a :: to separate prescript and postcript in the description like this:

[[cite:Defliese2015,Murray2016,Muller2017][e.g.::,]]

**Comment by japhir** [comment]
Thanks for the fast response! I've done that before, but since the syntax of bibtex normally is `\cite[pre][post]{citekey}` I was wondering how I could export it to apacite syntax, with `\cite<pre>[post]{citekey}`. Do you know if that's possible?

**Comment by jkitchin** [comment]
You can redefine the format function like this:

```
#+BEGIN_SRC emacs-lisp
(defun org-ref-format-citeA (keyword desc format)
  (concat "\\" "citeA"
	  (when desc
	    (cond
	     ((string-match "::" desc)
	      (let ((results (split-string desc "::")))
		(format "<%s>[%s]" (nth 0 results) (nth 1 results))))
	     (t (format "[%s]" desc)))) 
	  "{"
	  (mapconcat
	   (lambda (key) key)
	   (org-ref-split-and-strip-string keyword) ",")
	  "}"))
#+END_SRC

```

for me that exports your cite like this:

\citeA<e.g.>[,]{Defliese2015,Murray2016,Muller2017}

Is that what you want?

**Comment by japhir** [comment]
Perfect, it works great! I copied the function to also redefine the cite format. The only minor issue that remains is that it always outputs postscript brackets, which are usually empty in my case. This doesn't matter though, since the empty brackets don't output anything.

I guess I should just put these settings in local variables to my org file so that it is reproducible for reviewers. Thanks again!

**Comment by jkitchin** [comment]
you could modify the function to not put these in when they are empty. maybe like this:

```
#+BEGIN_SRC emacs-lisp
(defun org-ref-format-citeA (keyword desc format)
  (concat "\\" "citeA"
	  (when desc
	    (cond
	     ((string-match "::" desc)
	      (let ((results (split-string desc "::")))
		(format "%s%s" 
			(if (nth 0 results)
			    (concat "<" (nth 0 results) ">")
			  "")
			(if (nth 1 results)
			    (concat "[" (nth 1 results) "]")
			  ""))))
	     (t (format "[%s]" desc))))
	  "{"
	  (mapconcat
	   (lambda (key) key)
	   (org-ref-split-and-strip-string keyword) ",")
	  "}"))
#+END_SRC
```

**Comment by japhir** [comment]
Thanks again! It looks like I was overeager there, the template latex file actually does suggest using the empty square brackets in the case of only a prescript:
```
  %... \cite <i.e.>[]{lewin76,carson86,bartoldy02,rinaldi03}.
```
So I'll stick to the first version now.

**Comment by jkitchin** [comment]
Sounds good. Closing this for now.

**Comment by japhir** [comment]
Hi John, I have another paper to submit to the same journal that uses apacite. I tried the above solution again but with the changes in org-ref it no longer works, and there's probably a more clever solution to dealing with this now. Any help would be appreciated!

**Comment by jkitchin** [comment]
hm. It looks a lot harder to do this now. I think some kind of pre-processor is probably the answer in the short term. it could be tricky though, I have to think about it. you would have to iterate over the cite links, and replace them with the Latex syntax you want.

in your earlier example what is the utility of putting i.e. in the cite via <i.e.> instead of simply in front of the cite?

**Comment by japhir** [comment]
> in your earlier example what is the utility of putting i.e. in the cite via <i.e.> instead of simply in front of the cite?

It's mostly for citations with parentheses: in this case `citeA` (but normally I like to use biblatex, so `parencite`) this would allow you to include the i.e. within the parentheses: `\citeA<i.e.,>[]{Einstein1900}` -> ` (i.e., Einstein 1900)`.
I was hoping that the new `[[cite:pre;&citekey;post]]` syntax would make this easier :(. I guess I can just do search and replace on the latex file just before submission.
