### ISSUE TITLE
How to manually add PDF file then link to the bib and notes

### ISSUE THREAD

**Issue by LifeWorks** [jkitchin/org-ref#660]
I did not find any solutions online.

And is it possible to import PDF files then rename and organize them in the pdfs folder?

Just curious is it possible to do such thing.

**Comment by jkitchin** [comment]
This isn't generally an easy thing to do in bulk.  you might see if `org-ref-pdf-dir-to-bibtex` is close. It should try to get a doi out of each pdf in a directory, and then make bibtex entries for them. Not all pdfs are readable this way though, and you are likely to be doing some manual work for some. That function is not used a lot, so it might not do what you want, but it might give you some ideas of what can be done.
