### ISSUE TITLE
`orcp-citeproc` causes exporting to HTML failed when including another org file

### ISSUE THREAD

**Issue by Yevgnen** [jkitchin/org-ref#662]
Give `a.org`

    * Level 1

    #+include: "b.org::*English"

and `b.org`

    * English

    English words.

    * 中文

    中文字．

exporting `a.org` to HTML works quite well. However if changing the including line of `a.org` to `#+include: "b.org::*中文"`, error happened

    Debugger entered--Lisp error: (args-out-of-range 27 27)
      get-text-property(27 org-ref-label)
      org-ref-delete-labels(28 28)
      #f(compiled-function () #<bytecode 0x56cc62e1>)()
      org-scan-tags(#f(compiled-function () #<bytecode 0x56cc62e1>) t nil nil)
      org-map-entries(#f(compiled-function () #<bytecode 0x56cc62e1>))
      org-export--prepare-file-contents("/Users/user/Downloads/a.org" "5-8" 0 2 1 #<hash-table equal 0/65 0x56ca565d> "/Users/user/Downloads/b.org")
      org-export-expand-include-keyword()
      org-export-as(html nil nil nil (:output-file "a.html"))
      org-export-to-file(html "a.html" nil nil nil nil nil)
      org-html-export-to-html(nil nil nil nil)
      (org-open-file (org-html-export-to-html nil s v b))
      (if a (org-html-export-to-html t s v b) (org-open-file (org-html-export-to-html nil s v b)))
      (lambda (a s v b) (if a (org-html-export-to-html t s v b) (org-open-file (org-html-export-to-html nil s v b))))(nil nil nil nil)
      org-export-dispatch(nil)
      funcall-interactively(org-export-dispatch nil)
      call-interactively(org-export-dispatch nil nil)
      command-execute(org-export-dispatch)

Tested in a `emacs -q -l` session with the following settings:

    (package-initialize)
    (require 'org-ref)
    (add-hook 'org-export-before-parsing-hook #'orcp-citeproc)

Version info:

- Emacs: `GNU Emacs 26.2.90 (build 1, x86_64-apple-darwin18.6.0, Carbon Version 158 AppKit 1671.5) of 2019-06-19`
- Org: `Org mode version 9.2.4 (release_9.2.4-379-g1b74ae @ /Users/user/.emacs.d/straight/build/org/)`

**Comment by Kitanizerosan** [comment]
Same issue here with Emacs 27.

**Comment by jkitchin** [comment]
The citeproc code in org-ref is not under current development. Pull requests are welcome but I think there are probably better approaches than what is here, e.g. https://github.com/andras-simonyi/citeproc-org

**Comment by Yevgnen** [comment]
Now I notice that even setting `org-export-before-parsing-hook`  to `nil` and disabling `citeproc`, the issue is still there, I don't know but maybe it's not a citeproc issue.

**Comment by jkitchin** [comment]
This could be an issue in org-ref. It only looks for labels in the current file I think. Can you post a MWE that I can use for testing?

**Comment by Yevgnen** [comment]
The original post is. I tests one more time in an `Emacs -Q` session one more time just now, with the following config 

```
(package-initialize)
(require 'org-ref)
```

I guess it's something related to string width of unicode chars.

**Comment by jkitchin** [comment]
I can confirm there is something weird happening. I think it has to do with org-ref trying to get a text property at the end of the buffer. I have pushed a fix for it I think. Let me know if it helps your problem.

**Comment by Yevgnen** [comment]
It does! Thank you very much.

**Comment by namdnguyen** [comment]
Thanks, @jkitchin! Worked for me, too.

**Comment by jkitchin** [comment]
Thanks for the confirmation. Let me know if it pops up again. I don't totally understand why the fix works, or why the issue is there...
