### ISSUE TITLE
Fallback if pdf download fails

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#665]
Hi John,

1) What an awesome tool!

2) For most of my journals, the automatic pdf download fails (not sure why)

3) Would it be difficult to add a fallback solution, e.g., adding a user prompt to enter a link to the file location?

Happy to help to look in #2, but my gut feeling is that #3 is a more universal approach. Org-ref-version is 1.1.1

Cheers

Uli

**Comment by jkitchin** [comment]
What usually happens should be that the url to the reference is opened in a browser, and from there you can download the pdf. The key should be copied to the clipboard, so it is easier to rename the pdf, and then move it to the pdf directory.

A lot of journals hide the pdfs behind javascript things, so their isn't always a url to get them.  If there is a url, it should be easy to update/add recipes for downloading them.
