### ISSUE TITLE
melpa installation: pdf-tools not found

### ISSUE THREAD

**Issue by zenny** [jkitchin/org-ref#666]
Hi @jkitchin 

Thanks for creating such a wonderful tool for researchers.

However, when trying to install from melpa, it fails to install with the message that pdf-tools were not found:

```
https://melpa.org/packages/pdf-tools-20190413.2018.tar: Not found
```

Cheers,
/z

**Comment by jkitchin** [comment]
This probably means you have to run M-x package-refresh-contents. This kind of thing usually happens when your local package archive is not up to data with what is on melpa.

**Comment by zenny** [comment]
@jkitchin Thanks. The process was a bit different in doom-emacs. However, your suggestion worked. :D
