### ISSUE TITLE
org-ref-open-bibtex-notes doesn't use org-ref-open-notes-at-point

### ISSUE THREAD

**Issue by plantarum** [jkitchin/org-ref#669]
org-ref-open-bibtex-notes uses find-file to open the note associated with a reference, which breaks if you use a separate file for each reference (i.e., org-ref-notes-function is 'org-ref-notes-function-many-files):

https://github.com/jkitchin/org-ref/blob/9ab74270c1543e4743ca0436de567d8205403b43/org-ref-core.el#L2749

I think this should be something along the lines of:

``` elisp
(if  (or org-ref-notes-directory org-ref-bibliography-notes)
    (org-ref-open-notes-at-point key)
  (error
   "Org-ref-bib-bibliography-notes and org-ref-notes-directory are not set to anything"))
```

**Comment by jkitchin** [comment]
It looks like this isn't an issue any more. Closing.
