### ISSUE TITLE
possible improvements to automatically downloading pdfs...

### ISSUE THREAD

**Issue by prtkm** [jkitchin/org-ref#67]
Hi John,

Is it possible to extend the function in doi-utils to include a library proxy when trying to get pdfs. This is a problem I face when working from home where I have to append a library proxy to the page address in order to get past the paywall.

So this,
http://pubs.acs.org/doi/10.1021/acscatal.5b01755
would become this,
http://pubs.acs.org.proxy.library.nd.edu/doi/10.1021/acscatal.5b01755

I think this should only involve adding a variable that stores the proxy and appending it to the pdf webpage when the function is called. I think many other institutions work this way too.

This does require me to login the first time I use it, so ideally it should open the browser if no pdf can be found.  

I also think that it is probably more natural that the browser should open to the given bibtex entry if no pdf is found, so I can manually save it (e.g. from journals like PRB and PRL, which require a captcha).

**Comment by jkitchin** [comment]
It doesn't look that easy. you might just try advising the function here https://github.com/jkitchin/org-ref/blob/master/doi-utils.el#L71

It looks like you could split the url, transform the root, and then rejoin the url to get the redirect.

I guess you don't have a vpn?

**Comment by prtkm** [comment]
I think our library resources are separate from the vpn, requiring a proxy. I'll play around with that function to see if I can make it work. I guess I'll need a prompt for username and password as well, which might be complicated.

I noticed emacs does this now while downloading Phys Rev articles. I made an an aps account and activated it so I can now access articles from my browser without the captcha or the proxy, but it doesn't seem to work for me while trying to get a pdf from within emacs. It just asks me for the username and password twice, then exits silently.

**Comment by andreaskiermeier** [comment]
The library proxy applies for me, too.
Though I generally prefer to manually download files and safe them in subject specific folders.
Maybe it would be possible to have an option to disable PDF download?

**Comment by jkitchin** [comment]
I added an option (default true) doi-utils-download-pdf that you can set to nil and it should avoid downloading pdf files.

I think you want to advise this function: doi-utils-get-pdf-url

Just run it, get the url it returns, and munge it to get your proxy address. Something like this seems approximately right:

(defun my-pdf-proxy (orig-fun &rest args)
  (let* ((pdf-url (apply orig-fun args))
	 (url-struct (url-generic-parse-url pdf-url)))
    (setf (url-host url-struct)
	  (concat (url-host url-struct) ".proxy.library.nd.edu"))
    (url-recreate-url url-struct)))

(advice-add 'doi-utils-get-pdf-url :around #'my-pdf-proxy)

;remove it like this.
;(advice-remove 'doi-utils-get-pdf-url #'my-pdf-proxy)

(doi-utils-get-pdf-url "10.1021/acscatal.5b00538")

I don't see a way to generalize this.

**Comment by prtkm** [comment]
The function works fine for me in terms of getting the url, but there is still the issue of getting authenticated, which I don't think has an easy/general fix.

**Comment by andreaskiermeier** [comment]
Disabling PDF download works. Personally I can live without the automatic download functionality ... though the more I use org-ref, the more I like everything it's got to offer!

**Comment by jkitchin** [comment]
You might look into url-basic-auth and other related functions, and maybe
http://www.emacswiki.org/emacs/UrlPackage#toc5.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
