### ISSUE TITLE
Customizing format of citation when using insert formatted citation

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/org-ref#670]
I am trying to format the formatted citation. My goal is to insert the formatted citation in the buffer (or copy it to clipboard), but follow the standard format:

Author. (year). Title, joournal.

I am tying to modify this function accordingly from

```
(defcustom org-ref-formatted-citation-formats
  '(("text"  . (("article"  . "${author}, ${title}, ${journal}, ${volume}(${number}), ${pages} (${year}). ${doi}")
...
    ("org"  . (("article"  . "${author}, /${title}/, ${journal}, *${volume}(${number})*, ${pages} (${year}). ${doi}")
 ....
```

to 

```
(defcustom org-ref-formatted-citation-formats
  '(("text"  . (("article"  . "${author}.  (${year}). ${title}, ${journal}, ${volume}(${number}), ${pages}. ${doi}")
...
    ("org"  . (("article"  . "${author}.  (${year}). /${title}/, ${journal}, *${volume}(${number})*, ${pages}. ${doi}")
...
```

Nothing happens, though. Any idea how I can achieve that?

**Comment by jkitchin** [comment]
This works for me:

```
#+BEGIN_SRC emacs-lisp
(setf 
 (cdr (assoc "article" (cdr (assoc "text" org-ref-formatted-citation-formats))))
 "${author}.  (${year}). ${title}, ${journal}, ${volume}(${number}), ${pages}. ${doi}")
#+END_SRC
```

I guess if you are modifying a defcustom, you might have to restart emacs, or do some fanciness to get it to reload the defcustom values. Your are better off using setq than redefining the defcustom.

**Comment by DiogoFerrari** [comment]
I tried to restart and reload the defcustom settings, but it didn't work. Your solution worked great. Thanks!
