### ISSUE TITLE
Single bibliography and file for both html and pdf export

### ISSUE THREAD

**Issue by jellelicht** [jkitchin/org-ref#671]
I currently have to use 
`#+LATEX_HEADER: \addbibresource{refs.bib}` i.c.w. a `\printbibliography` in order to have a bibliography show up in my pdf.

On the other hand, I have to have a `bibliography:refs.bib` in my document to have a bibliography show up in html exports. This breaks my latex export though (`! LaTeX Error: Can be used only in preamble.
`)

How can I have one notation that will result in a bibliography in both types of export?

**Comment by jkitchin** [comment]
you probably have to put the bibliography link in a heading tagged :html: or something, and then make a build heading tagged :noexport: that has code blocks to build the latex or html versions using tags to select/exclude the relevant headings.

**Comment by jellelicht** [comment]
What precisely is a build heading?

**Comment by jkitchin** [comment]
It is something like this, where you run the relevant code block to get what you want.

```

* build                                                            :noexport:

** html

#+BEGIN_SRC emacs-lisp
(org-open-file (org-html-export-to-html))
#+END_SRC

** pdf

#+BEGIN_SRC emacs-lisp
(let ((org-export-exclude-tags '("noexport" "html")))
  (org-open-file (org-latex-export-to-pdf)))
#+END_SRC

```

**Comment by jellelicht** [comment]
In the end, I went with the admittedly very hacky
```
#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
[[bibliography:refs.bib]]

#+BEGIN_EXPORT latex
\fi
#+END_EXPORT

@@latex: \printbibliography@@
```

It's not pretty, but it works
