### ISSUE TITLE
unable to load org-ref mode

### ISSUE THREAD

**Issue by termlen0** [jkitchin/org-ref#674]
https://pasteboard.co/IxxHu0y.png

When I try to load the mode, it gets stuck at checking for duplicate keys. Image pasted above.

The data in Messages buffer is as follows:

```
/usr/share/texlive/texmf-dist/bibtex/bst/apacite/apacite.bst
Checking syntactical structure (9%)
Checking syntactical structure (14%)
Checking syntactical structure (22%)
Checking syntactical structure (40%)
Checking syntactical structure (54%)
Checking syntactical structure (60%)
Checking syntactical structure (74%)
Checking syntactical structure (82%)
Checking syntactical structure (93%)
Checking syntactical structure (done)
Checking for duplicate keys (9%)
Checking for duplicate keys (14%)
Checking for duplicate keys (22%)
Checking for duplicate keys (40%)
Checking for duplicate keys (54%)
Checking for duplicate keys (60%)
Checking for duplicate keys (74%)
Checking for duplicate keys (82%)
Checking for duplicate keys (93%)
```
Appreciate any pointers on how to troubleshoot.

**Comment by termlen0** [comment]
Figured it out. I had a syntax error in my bib file. Leaving this comment in here, in case someone else runs into it in the future.

**Comment by AtomicNess123** [comment]
I am getting a bunch of lines with "Syntax error (check esp. commas, braces, and quotes)". However, the bibtex entries seem fine as I can tell. Is there a way to check with an external tool my bibtex files for the error?

**Comment by jkitchin** [comment]
you can use `M-x bibtex-validate` in your bibtex file. It will usually tell you where the errors are. The places are usually close to the issue.
