### ISSUE TITLE
clean bibtex entry - keys with special characters

### ISSUE THREAD

**Issue by clwgg** [jkitchin/org-ref#675]
Hi,
thank you for this great package, I have found myself using it more and more. Recently, I've run into a problem with the formatting of clean bibtex entries through `org-ref-clean-bibtex-entry`: If the surname of a first author carries certain special characters, specifically the `ß` or `{\ss}` character, the key of the bibtex entry will end up malformed. A working example:
Original entry
```
@article{Wei2011,
  doi = {10.1002/ijc.25438},
  url = {https://doi.org/10.1002/ijc.25438},
  year = {2011},
  month = jan,
  publisher = {Wiley},
  volume = {128},
  number = {6},
  pages = {1384--1392},
  author = {Jakob V. Wei{\ss} and Susanne Klein-Scory and Salwa K\"{u}bler and Anke Reinacher-Schick and Ingo Stricker and Wolff Schmiegel and Irmgard Schwarte-Waldhoff},
  title = {Soluble E-cadherin as a serum biomarker candidate: Elevated levels in patients with late-stage colorectal carcinoma and {FAP}},
  journal = {International Journal of Cancer}
}
```
after running `org-ref-clean-bibtex-entry` on it:
```
@article{wei\ss11_solub_e_cadher_as_serum_biomar_candid,
  doi =          {10.1002/ijc.25438},
  url =          {https://doi.org/10.1002/ijc.25438},
  year =         {2011},
  month =        jan,
  publisher =    {Wiley},
  volume =       {128},
  number =       {6},
  pages =        {1384--1392},
  author =       {Jakob V. Wei{\ss} and Susanne Klein-Scory and Salwa K\"{u}bler
                  and Anke Reinacher-Schick and Ingo Stricker and Wolff
                  Schmiegel and Irmgard Schwarte-Waldhoff},
  title =        {Soluble E-Cadherin As a Serum Biomarker Candidate: Elevated
                  Levels in Patients With Late-Stage Colorectal Carcinoma and
                  {FAP}},
  journal =      {International Journal of Cancer}
}
```

Having the `\ss` string in the key will interfere with citing this reference, as well as running programs such as `biber` on the bibtex file.

Unfortunately, my knowledge of this package doesn't go far enough to propose a pull request for this issue. However, if pointed in the right direction, I would be happy to give it a shot. Thank you for your help!

**Comment by jkitchin** [comment]
Thanks for reporting this. It has also periodically interfered for me to. I have pushed a simple fix for now. I don't know if there is a better way, I just remove the \ from the generated key. Let me know if it solves the problem for you.

**Comment by clwgg** [comment]
This is great, thanks for the quick reply!
