### ISSUE TITLE
How to change face and coloe for ref:figure?

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#676]
The cite and ref:figure default to foreground-color after a recent git-pull.  I figured out the cite link setting.   Where and how do I change the face of ref:figure?

**Comment by jkitchin** [comment]
This sounds pretty odd. I am not able to reproduce it. Do you see anything in the messages that would indicate a problem? Also, what did you did you do to fix the cite link issue?

**Comment by cryoguy** [comment]
I just upgrade it with git pull and bye-compiled it.  The following is what I did to fix cite link.  I thought the 2nd line would have fixed the ref:figure part, but it did not.
`'(org-ref-cite-face ((t (:foreground "deep sky blue" :underline "blue"))))
 '(org-ref-label-face ((t (:foreground "orange red" :underline "orange"))))
 `

**Comment by jkitchin** [comment]
huh. weird. I don't know why you have to do that. If it works go for it I guess. You haven't changed the ref link face though, just the cite and label links. The ref link face is in `org-ref-ref-face`.

**Comment by cryoguy** [comment]
I do not need to do anything either before.  The default says THEMED.  I upgraded my system to Emacs 26 recently, too many confounding elements.  The `org-ref-ref-face` works fine.
