### ISSUE TITLE
Helm-bibtex support for org-ref-style notes file is imminent.

### ISSUE THREAD

**Issue by tmalsburg** [jkitchin/org-ref#68]
Just a heads up that I will soon add support for an org-ref-style notes file (all notes in one org-file) to helm-bibtex.  See the feature-branch [note-files](https://github.com/tmalsburg/helm-bibtex/tree/note-files). The default template for notes does not duplicate the information from the BibTeX file (see example below), the property drawer only includes the BibTeX key.  However, it's easy to extend the template via the variable `helm-bibtex-notes-template-one-file`.

```
* Gigerenzer, G. (1998): We need statistical thinking, not statistical rituals
  :PROPERTIES:
  :Custom_ID: Gigerenzer1998
  :END:

Deep thoughts go here: …
```

The default behaviour in helm-bibtex will not change (one file per article) so you can probably ignore this if you want.  However, this feature perhaps allows you to simplify things on your side?  Not sure.

**Comment by jkitchin** [comment]
Thanks for the heads up. I don't use notes too often, but if anything comes up I will keep this in mind.

**Comment by jagrg** [comment]
@jkitchin we are unable to fully change the notes title template because drawer and links are inserted automatically. The changes in https://github.com/jagrg/org-ref/commit/a18abde4b744c1e1942beb12d2346080568f2653 gives more flexibility but keeps the original format, except for the pdf, which can be accessed via the cite link anyway. What do you think?

**Comment by tmalsburg** [comment]
I may not understand org-ref well enough, but I assumed that the new code in helm-bibtex could handle notes such that this doesn't need to be duplicated in org-ref.

**Comment by jagrg** [comment]
@tmalsburg this is needed for opening notes via cite links.

**Comment by tmalsburg** [comment]
Why can't you simply call `helm-bibtex-edit-notes` in `org-ref-open-bibtex-notes` after the key is copied to the clipboard?

**Comment by jagrg** [comment]
You are probably right. Maybe John can comment.

**Comment by jkitchin** [comment]
@jagrg your suggestion looks fine. I made that change. I am ambivalent on one file per note or all notes in one file. I decided to create a new customization for org-ref-notes-function that allows users to specify how they want to open notes at point, either a function that does the old way (Default) or helm-bibtex-edit-notes. I think that covers everyone.

**Comment by tmalsburg** [comment]
Misunderstanding: Helm-bibtex allows to use both kinds of notes.  This means that helm-bibtex-edit-notes could be used to implement the org-ref way of handling notes.  I was not proposing that org-ref switches to one file per note.

**Comment by jkitchin** [comment]
I see. So it should be fine to have helm-bibtex-edit-notes do the work, and leave the configuration on helm-bibtex then. Can you point me to the relevant configuration variables?

**Comment by tmalsburg** [comment]
To get org-ref style notes, you have to set `helm-bibtex-notes-path` to point to the notes file and you have to set the template for new notes using `helm-bibtex-notes-template-one-file`.  Another relevant variable is `helm-bibtex-notes-key-pattern` but I think you don't have to change it because its current default is consistent with org-ref format.
