### ISSUE TITLE
org-ref-get-pdf-filename is too hardcoded for my use case

### ISSUE THREAD

**Issue by NinKenDo64** [jkitchin/org-ref#680]
I recently started using JabRef. I'm quite enjoying its way of handling BibTeX in a way that feels sufficient standards compliant, while still being extensible. Previous to that I was using Zotero which definitely is a great package, but required I constantly export my library to BibTeX if I wanted it to work with org-ref.

One nice thing about JabRef is it allows you to store file links in the format of a field called "file" with a custom filename followed by a filetype definition.

e.g.,

`@Article{Norris2016Languageprogramevaluation,
  author    = {John M. Norris},
  title     = {Language program evaluation},
  journal   = {The Modern Language Journal},
  year      = {2016},
  volume    = {100},
  number    = {S1},
  pages     = {169--189},
  month     = jan,
  abstract  = {Language program evaluation is a pragmatic mode of inquiry that illuminates the complex nature of language‐related interventions of various kinds, the factors that foster or constrain them, and the consequences that ensue. Program evaluation enables a variety of evidence‐based decisions and actions, from designing programs and implementing practices to judging effectiveness and improving outcomes. Though often narrowly construed as an external accountability requirement only, evaluation may provide a heuristic for generating new knowledge; raising awareness; and transforming the educational, social, and economic circumstances of individuals and communities. In this article, I review the origins and interdisciplinary nature of program evaluation, and I trace its development within applied linguistics and language education in particular. I then consider the current contributions of language program evaluation, and I point to likely future trends. In particular, I highlight how changing global circumstances, technological affordances, and contexts and purposes for language learning and language use are both impacting the nature of evaluation and presenting challenges for which evaluation is uniquely suited to respond. I also emphasize the potential—versus as yet realized—contribution of program evaluation as a way of ameliorating gaps in current language research and practice, and I point to implications for training, dissemination, and integration of this mode of inquiry as an important part of the future intellectual core of applied linguistics.},
  doi       = {10.1111/modl.12307},
  file      = {:Norris (2016) Language program evaluation.pdf:PDF},
  keywords  = {{program evaluation} and {accountability testing} and {outcomes assessment} and {curricular innovation} and {formative} and {participatory}},
  publisher = {Wiley},
}`

However when I tried to use org-ref-open-pdf-at-point, it tries to open the filename based purely on the key + ".pdf" extension, which obviously doesn't work given the way I'm storing my files.

I tracked down where this hardcoded pattern is, and it's in org-ref-get-pdf-filename:

`(defun org-ref-get-pdf-filename (key)
  "Return the pdf filename associated with a bibtex KEY.
This searches for the pattern KEY*.pdf. If one result is found it
is returned, but if multiple results are found, e.g. there are
related files to the KEY you are prompted for which one you want."
  (if org-ref-pdf-directory
      (let ((pdfs (-flatten (--map (file-expand-wildcards
				    (f-join it (format "%s*.pdf" key)))
				   (-flatten (list org-ref-pdf-directory))))))
	(cond
	 ((= 0 (length pdfs))
	  (expand-file-name (format "%s.pdf" key) org-ref-pdf-directory))
	 ((= 1 (length pdfs))
	  (car pdfs))
	 ((> (length pdfs) 1)
	  (completing-read "Choose: " pdfs))))
    ;; No org-ref-pdf-directory defined so return just a file name.
    (format "%s.pdf" key)))`

which literally takes the key, appends ".pdf" and calls it a day.

I'd love it if org-ref were aware of the "file" field that JabRef generates and could use that.

I had a swim through some of the bibtex-mode functions and was surprised there was nothing in there directly for parsing bibtex entries. My emacs-lisp is pretty hacky, but I'd be happy to work on this on my own if someone can point me in the right direction on how I might go about parsing the entries without opening them in the visible buffer.

My idea is to rewrite the function so that it can be aware of the file field, or perhaps a user defined field if this is non-standard bibtex, and then use the current method as a fallback if the field doesn't exist or no file is found there. BUt I need a little help on where to look when it comes to accessing fields in a bibtex entry by key.

**Comment by NinKenDo64** [comment]
Okay, just spotted 'org-ref-get-mendeley-filename
which has the description "Return the pdf filename indicated by mendeley file field.
Falls back to `org-ref-get-pdf-filename' if file field does not exist.
Contributed by https://github.com/autosquid.
Argument KEY is the bibtex key."

I figured if I did `(setq org-ref-get-pdf-filename-function 'org-ref-get-meneley-filename)` then it might work. Alas, alack, it seems to fallback to org-ref-get-pdf-filename, which of course, fails to find a file.

**Comment by jagrg** [comment]
Try org-ref-get-pdf-filename-helm-bibtex. It should work with JabRef.

**Comment by NinKenDo64** [comment]
Weirdly if I set `org-ref-get-pdf-filename-function` to that and call `org-ref-open-pdf-at-point` while point is over the cite: link, that just splits the frame into two windows horizontally.

**Comment by jkitchin** [comment]
I don't think you can open a pdf from anywhere in the line (what if there was more than one citation in the line?). You can click on a cite link, and then open the pdf from the menu. There are some key shortcuts on the links to, H-p should also open the pdf for the cite at point.
