### ISSUE TITLE
ref-labels are not updated

### ISSUE THREAD

**Issue by TMueller83** [jkitchin/org-ref#684]
It seems that there is some kind of problem with updating the ref-labels. For example, if I open a new org-file and enter
```
#+caption: A figure. label:fig:1
```
then by using `org-ref-helm-insert-ref-link` the list of available links contains `fig:1`, which is the expected behavior. However, If I now add a second line
```
#+caption: Another figure. label:fig:2
```
and run `org-ref-helm-insert-ref-link` again, then the label `fig:2` does not appear in the helm-list. Running `org-ref` it tells me: Labels with no ref links: `fig:1`, `fig:2` so org-ref seems to be aware of `fig:2` but it is not shown in the helm-buffer. Furthermore, adding a line like
```
Ref. ref:fig:1, Ref. ref:fig:2.
```
and running `org-ref` again, it displays: Bad ref links: `fig:2`. If I now close Emacs and open the org-file again everything is like its supposed to be: `org-ref-helm-insert-ref-link` offers me `fig:1` and `fig:2` and `org-ref` reports no problems. However the trouble starts again if new labels are added.

**Some notes:** I am using the following versions Emacs: 24.5.1, org-mode: 9.2.6, org-ref: 1.1.1. In my `.init` file I have put `(require 'org-ref)` to the `org-mode-hook` and it seems that this might have some kind of influence on the problem described. Putting `(require 'org-ref)` at the top of the `.init` file seems to cause that the labels are updated correctly but upon closing and reopening the org-file all labels are duplicated in the helm-buffer and also `org-ref` reports that all labels are duplicate.

**Comment by jkitchin** [comment]
You should definitely not have `(require 'org-ref)` in the org-mode hook. Requiring it once should be all that is necessary.

I have pushed a fix for the duplicate label issue I think. 

The first issue I am not sure is fixed or not. The way the label finding works now is through font-lock.  Maybe there is some unusual thing happening when you put two labels close together with overlapping font-lock regions? 

Can you try the new push and see if it resolves at least some problems?

**Comment by TMueller83** [comment]
Thank you very much for the fix! I will try it soon. The reason why I have put `(require 'org-ref)` in the `org-mode-hook` is, that it very much slows down the start of Emacs if it is put at the top of the `.init` file. Is there a way to only `(require 'org-ref)` if one visits an org-file for the 1st time, such that the start of Emacs is not delayed?

**Comment by jkitchin** [comment]
There isn't a good way to avoid the slowdown right now. I am pretty sure the issue is related to pdf-tools, but i have not figured out how to make that optional yet.

Maybe try not closing emacs :) ?

**Comment by TMueller83** [comment]
> Maybe try not closing emacs :) ?

Actually not a bad idea! :smile: 

I have tried the fix and it is true, after closing and reopening the org-file there are no duplicate labels anymore in the `org-ref-helm-insert-ref-link` buffer, however, `org-ref` still reports duplicate labels. And there is another strange behavior: After reopening the file and checking, that `org-ref-helm-insert-ref-link` does not have duplicate labels, I add another line like
```
#+caption: Yet another figure. label:fig:3
```
to the org-file. Then running `org-ref-helm-insert-ref-link` *only* shows the label `fig:3` and the other ones are gone.

**Comment by jkitchin** [comment]
weird. I can't figure out how to reproduce that. I did add an option that might fix it for you. If you add this to your init file does it resolve the issue:

`(setq org-ref-label-use-font-lock nil)`

The downside of that is it will search the whole buffer for labels. In small buffers it is probably fast. I am not sure about big buffers. It is all regex search, so it is probably fast.

**Comment by TMueller83** [comment]
Thank you very much for the new fix with the added option! This seems to very much fix all the problems. Only the minor issue that `org-ref` insists to permanently report that all labels are duplicate (Multiply defined). This actually happens right from the start as I have noticed. That does however not bother me much, but maybe it indicates that there is still something going on.

**Comment by jkitchin** [comment]
That is also a bug. I think it is also fixed now. Thanks for reporting that!

**Comment by TMueller83** [comment]
Thank you very much for fixing things so fast!! This last commit fixes all issues, even without using the `(setq org-ref-label-use-font-lock nil)` option. Perfect work!
