### ISSUE TITLE
[feature-request] deactivating pdf download?

### ISSUE THREAD

**Issue by jacquesdurden** [jkitchin/org-ref#685]
Is it possible to deactivate by default the automatic download of PDF for certain org-ref methods? (e.g., doi-utils-add-entry-from-crossref-query) 

I don't need this, and moreover any pdf download seems to freeze my emacs.

Thanks.

**Comment by jkitchin** [comment]
`(setq doi-utils-download-pdf  nil)` should disable the download.

**Comment by jacquesdurden** [comment]
Great! This works perfectly, and it avoids emacs to freeze in my config.

**Comment by averter** [comment]
Hi, Sorry for the random comment but what is the point of the function `doi-utils-toggle-pdf-download` then? Isn't it to set the `doi-utils-download-pdf` nil? I am looking at the org-ref project and interested in doing some personal customization. Great package by the way.

**Comment by jkitchin** [comment]
sometimes I want to toggle it off to get a bunch of entries where I don't care about the pdf, and don't want to wait for the pdf download to fail. so I can just run this command to toggle it off, and then toggle it back on later.
