### ISSUE TITLE
org-ref-strip-string relies on search-whitespace-regexp

### ISSUE THREAD

**Issue by fpiper** [jkitchin/org-ref#687]
I just ran into this issue and found that others had similar problems
in the past (see issues #140 and #277). The function `org-ref-strip-string`
in `org-ref-utils.el` relies on the value of `search-whitespace-regexp`,
which is originally defined in `isearch.el`, to find leading and
trailing whitespace.

In my opinion, the function should not depend on variables of other
packages. Even though `isearch` is an Emacs internal package and the
variable will therefore always be defined, this needlessly limits the
possible customization of isearch. I also do not see a case, where the
global setting of search-whitespace-regexp is useful for
`org-ref-strip-string`. If you agree, I would propose to either

-   hardcode a useful value instead of `search-whitespace-regexp`.
    For example the default `\\s-+` should be fine.

Or
-    define a new org-ref specific customizable variable
    `org-ref-search-whitespace-regexp`. If unset this can default to the
    value of `search-whitespace-regexp` if necessary.

**Comment by jkitchin** [comment]
That sounds reasonable. I added a defcustom with the default of "\\s-+" in the commit above. That should make it independent of isearch, and allow customization if there is some reason to do it.

**Comment by fpiper** [comment]
Thanks for the quick fix and for all the work you do on this package!
