### ISSUE TITLE
Generating citation network based on entries in the bibliography

### ISSUE THREAD

**Issue by ahmed-shariff** [jkitchin/org-ref#688]
Any suggestions on how I can go about generating a citation network based on the entries I have on my bib files?

**Comment by jkitchin** [comment]
You might be able to do something like in this paper: https://github.com/pybliometrics-dev/pybliometrics/blob/master/meta/1-s2.0-S2352711019300573-main.pdf

I am pretty sure what you will have to do is get a list of citing articles, e.g. from Scopus (which is not free), and then construct the graph yourself. 

Alternatively, maybe you can use something like https://clarivate.libguides.com/woscc/citationnetwork (probably also not free, and I have not used it before). 

https://www.citnetexplorer.nl/download looks free, and might also help.

**Comment by ahmed-shariff** [comment]
Nice. Will go through them and see what I can do. 

> I am pretty sure what you will have to do is get a list of citing articles
I agree, I was wondering of org-ref had anything (maybe planned) to help with this.

I was looking at something like https://github.com/OrganicIrradiation/scholarly
Will see what I can come up with.
