### ISSUE TITLE
Implementing heading-local bibliography for `org-ref-cite-insert-link`?

### ISSUE THREAD

**Issue by dangom** [jkitchin/org-ref#689]
I have a huge bibtex file which takes a while to parse.
I was wondering whether I could have heading local bibliography files (perhaps set with a property value), such that `org-ref-cite-insert-link` only displays a subset of results relevant for the section I'm working on.
Would this be easy to implement, and if so, where should I start?

Alternatively, perhaps there is a better workflow out there to deal with large bibliography files?

**Comment by jkitchin** [comment]
I use the ivy backend for this because it caches my large bunted file so it is fast. It only updates the cache when you change the bibtex file. 

I don’t know how you would implement your idea. How would it work when you just start a section? What would determine relevance?

You can easily extract the bibtex entries to a new local file which would be fast. See something like org-ref-extract-bibtex*

**Comment by dangom** [comment]
I suppose it'd look for a property first (maybe org-ref-section-bibliography), then bibliography file, then `org-ref-default-bibliography`. If a new section doesn't have a property then it looks for `#+bibliography` and then for the default value, just like other org-mode properties.

I'm using the helm interface. It's not slow to the point that I can't use it, but there's an annoying latency when starting and narrowing.

I also have a smaller bibtex files, but my question was more about switching between multiple local files within the same Org document.

**Comment by jkitchin** [comment]
There isn't an easy way to do that I think. There is a hierarchy, but it is at the document level, then default bibliography. The difficult part is how to get to references that are outside your scope. Within a document I don't know how you would switch. You could use #+include files maybe and have local bibliography definitions in them.

**Comment by dangom** [comment]
I'll close this issue for now and just create smaller bib files.
