### ISSUE TITLE
Deactivate TAB when at the citation link

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/org-ref#693]
This is more of a request: pressing TAB at an org-ref citation link activates insert citation. I use citation links in headings, so I can't use TAB to unfold the content of the heading (org-cycle) on org-mode when at the org-ref link. I have another keybinding to insert another citation when at the org-ref link with citation.

Any plan to deactivate that? How can I deactivate that keybinding?

**Comment by jkitchin** [comment]
You can deactivate it with:

`(define-key org-ref-cite-keymap (kbd "<tab>") nil)`

**Comment by DiogoFerrari** [comment]
Thanks!
