### ISSUE TITLE
org-ref citations can't work in table.el tables

### ISSUE THREAD

**Issue by kprojiang** [jkitchin/org-ref#694]
When trying to add the citations in table.el tables, I came across some wierd things.
This is the trouble I'm in:
```
+------+----------------------------------------------------------------+
| year | categories                                                     |
+------+----------------------------------+-----------------------------+
|      | de-anonymization                 | alignment                   |
+------+----------------------------------+-----------------------------+
| 2014 | cite:2016-Sharad-deanonymize-SNS |                             |
+------+----------------------------------+-----------------------------+
| 2018 |                                  | cite:2018_Heimann_HashAlign |
+------+----------------------------------+-----------------------------+
```

the typical key binding such as `C-c C-o` will not prompt the helm buffer to select the bibtex entry or add notes, reporting "wrong type of argument: stringp, nil"

![image](https://user-images.githubusercontent.com/20916211/71561333-0e416980-2ab0-11ea-88d9-19625c27a3c5.png)

I wonder what causes this bug. My guess is something in table.el prevent the org-ref from parsing the string, such as cite:2018_heimann_hashalign, but I'm not sure.

Thanks ahead for looking into it. PS: org-ref really makes the citation in org-mode a lot easier. I love it.

**Comment by jkitchin** [comment]
I can confirm this behavior. There is an issue indeed that prevents org-ref from recognizing cite links in these tables. The issue seems to be that the parser only sees the cursor as being at a table, and does not appear to see the cite link, so none of the code that runs when you click, or mouse over can work.

I sent a note to the org-mailing list to see if this is a bug in org, or expected behavior. 

I don't see an easy fix at the moment.

**Comment by kprojiang** [comment]
It's definitely a pity that table.el tables are opaque, however I'll just do with it. Maybe to manualy  modify the tex code in the table after converting from org to tex, before converting to pdf.


> I sent a note to the org-mailing list to see if this is a bug in org, or expected behavior.
> [update]: This is expected behavior, table.el tables are "opaque" to org-mode. That means org-ref cannot currently work inside a table.el table.
> 
> I don't see an easy fix at the moment.
