### ISSUE TITLE
 Symbol’s function definition is void: parsebib-find-bibtex-dialect

### ISSUE THREAD

**Issue by li012589** [jkitchin/org-ref#697]
Hi, thanks for providing us such a wonderful tool.

I'm new to org-ref. After a basic set-up, I met the error message `arxiv-get-bibtex-entry-via-arxiv-api: Symbol’s function definition is void: parsebib-find-bibtex-dialect` when try to run `arxiv-add-bibtex-entry`. Any idea what may cause it?

**Comment by jkitchin** [comment]
hm. That function is defined in the parsebib package, maybe it is not installed for some reason?

**Comment by li012589** [comment]
I think it's installed, I checked`list-package` and it's there(version 2.3.3). 

Also, it's marked required by both ivy-bibtex and helm-bibtex(I originally only use ivy, no idea why helm-bibtex got installed. Is there a way I can only use ivy-bibtex?).

**Comment by jkitchin** [comment]
that is weird. If it is loaded it should be there. I don't know of anything extra to do.  Maybe you could try using edebug on `arxiv-get-bibtex-entry-via-arxiv-api` to see if something odd is happening.

I don't think there is a way to only use ivy-bibtex, helm-bibtex probably gets installed in the beginning, in case you want to use it.

**Comment by li012589** [comment]
Thanks for the reply.

The error went away after I added `(require 'parsebib)` in the setting files. I didn't see doc mentioning this. Maybe I missed it?

**Comment by jkitchin** [comment]
That makes sense. I thought parsebib would always be loaded from org-ref-core, but it appears it is not. I pushed a fix for this for this library. thanks for reporting it.
