### ISSUE TITLE
What are the different existing variables?

### ISSUE THREAD

**Issue by Ypot** [jkitchin/org-ref#698]
I would like to know which ones are the different variables. I can't find them. 
For example, why "%9a" is the default for author, and **what would be the variable for ISBN**?
I think it could be useful for several tasks, like customizing the Notes Format:

> Org Ref Note Title Format: * %a - %t (%y)
>  :PROPERTIES:
>   :Custom_ID: %k
>   :AUTHOR: %9a
>   :JOURNAL: %j
>   :YEAR: %y
>   :VOLUME: %v
>   :PAGES: %p
>   :DOI: %D
>   :URL: %U
>  :END:

Thanks for your help

**Comment by jkitchin** [comment]
Those are described in the docstring for `org-ref-reftex-format-citation` as described in the docstring for `org-ref-note-title-format`. They are roughly based on the corresponding reftex format codes, with some extra ones I added. It does not look like there is one for ISBN.

See https://www.gnu.org/software/emacs/manual/html_mono/reftex.html#Options-_002d-Creating-Citations. %9a means abbreviate the authors if there are more than 9 of them.
