### ISSUE TITLE
Accented characters on org-mode

### ISSUE THREAD

**Issue by Ypot** [jkitchin/org-ref#699]
Is there any configuration in .emacs and Bibtex to show accentuated characters on org-mode?

When a note from a cite is created, for example:

>  El M{\'e}todo bullet journal
> vs
>  El Método bullet journal

https://github.com/jkitchin/org-ref/issues/474

**Comment by jkitchin** [comment]
There is not currently a way to do that. In the tooltips, we strip out the brackets so it is a little more readable. In orgmode there are the "pretty-entities" , but these are not the same as the latex representations, and I am not sure how to do something similar in the tooltips.

**Comment by Ypot** [comment]
My config. to workaround it:

I added to my .emacs:
> (prefer-coding-system       'utf-8)
> (set-default-coding-systems 'utf-8)
> (set-terminal-coding-system 'utf-8)
> (set-keyboard-coding-system 'utf-8)
> (setq default-buffer-file-coding-system 'utf-8)

In Zotero-Preferences-BetterBibTeX-Export-BibTeX:
Unchecked "Export unicode as plan-tex latex commands (recommended)."
