### ISSUE TITLE
small inconsistency when creating notes author property

### ISSUE THREAD

**Issue by benneti** [jkitchin/org-ref#700]
Hi,

It seems to me that when the first names are abbreviated or formatted like Last, First in the bib file the first names are dropped but for First Last they are kept.
Is it possible to change that to always drop the first name?
Thanks for org-ref!

Best,
Benedikt

**Comment by jkitchin** [comment]
I don't know if you can change that. The template for notes is in `org-ref-note-title-format`, and it uses `org-ref-reftex-format-citation` to fill it. you would have to make a much more complicated function to replace that I think, one that would have to handle the author formatting the way you want, including handling all the variants of the names.

**Comment by benneti** [comment]
Thanks, I'll take a look at it.

**Comment by benneti** [comment]
Thanks for your pointer. In case anyone stumbles upon this, too:
the following should fix the inconsistency for anyone interested:
``` emacs-lisp
(advice-add 'reftex-get-bib-names :filter-return
            (lambda (names)
              (let (newnames)
                (dolist (name names)
                  (while (string-match "^[\\.a-zA-Z\\-]+[ \t]+" name)
                    (setq name (replace-match "" nil t name)))
                  (setq newnames (append newnames (list name))))
                newnames)))
```
I think I will ask the reftex maintainers whether they want to include the regexp in the official verions.
