### ISSUE TITLE
How do you add page numbers or chapters to the bibliography? 

### ISSUE THREAD

**Issue by Ypot** [jkitchin/org-ref#702]
Hi 
Do you add page numbers to your bibliography? 
What do you think it would be the most efficient way? 

Ex (APA style):
Hall, L.S. 1999. Assessing the Impact of Title I. In J. Dobbs (Ed.), Federal Education Policy in Perspective **(pp. 90-120)**. New York: Education Policy Analysts Association.

**Comment by jkitchin** [comment]
I am not sure I follow your question. Pages for articles are usually automatically added. For books or chapters, you probably have to do it manually for the bibliography entries. In the text you can use something like [[cite:hall-1999][pp. 90-120]], but that will only get rendered in the text, not in the bibliography.
