### ISSUE TITLE
Issue with crossref and querying information

### ISSUE THREAD

**Issue by kehoen** [jkitchin/org-ref#703]
Hello,

I am having issues pulling information from crossref. For example, if I run the "crossref-add-bibtex-entry" and use your paper ("Examples of Effective Data Sharing in Scientific Publishing"), I am able to see details on your paper. When I select your paper to add an entry, I get the following:

```
Contacting host: search.crossref.org:80
json-read: JSON readtable error: 60

```
Similar errors occur trying other papers and other crossref-related functions.

Any ideas on what I can try or what I am doing incorrectly?

Thanks.

**Comment by jkitchin** [comment]
This is probably a problem with https://doi.org sending bad responses back to you. It is usually intermittent, and it usually goes away at a later time. I don't know if there is anything you can do.

The issue may be related to using a url with http instead of https inside this library. I pushed a small fix that may address this. 

Sometimes you can use `doi-utils-debug` to see more details about what is done, but in this particular error I am not sure it is helpful either.

**Comment by kehoen** [comment]
Thank you for the quick reply and attempted fix! With the update I am getting something slightly different, but still no luck. As you said, maybe it is intermittent so I will keep trying. The log I get now when running the same commands is:
```
Contacting host: doi.org:443
doi-utils-get-json-metadata: Something went wrong.  Opening https://doi.org/10.1021/acscatal.5b0053
```
And it opens a browser window to the DOI link.

When I run the ``` doi-utils-debug ``` I get:

```
Contacting host: doi.org:443
json-read: JSON readtable error: 60
```

I appreciate your help and all of the work you have done putting this together.

**Comment by jkitchin** [comment]
I added another bit of information that should show what data was returned in 
9afc804. That should make it more clear what is happening.

**Comment by jkitchin** [comment]
I should point out that your example seems to use an incorrect DOI in the url reported in the debug statement. I think you are missing an 8 at the end of it. The correct doi is 10.1021/acscatal.5b00538

**Comment by kehoen** [comment]
Thanks. I did use the correct DOI, but I must not have copied the whole thing out. Trying again, I get the following with ``` crossref-add-bibtex-entry ```:

```
Contacting host: doi.org:443
apply: Invalid format operation %a
```

Using ``` doi-utils-debug ``` I still get:

```
Contacting host: doi.org:443
json-read: JSON readtable error: 60
```

**Comment by jkitchin** [comment]
my bad. there was a typo in that commit. I just pushed a fix that should work better.

**Comment by kehoen** [comment]
Thanks again. This time, I do receive output related to HTTP vs HTTPS:

```
Contacting host: doi.org:443
doi-utils-get-json-metadata: Something went wrong.  We got this response:

<html>

<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>

<body>

<center><h1>400 Bad Request</h1></center>

<center>The plain HTTP request was sent to HTTPS port</center>

<hr><center>cloudflare</center>

</body>

</html>



Opening https://doi.org/10.1021/acscatal.5b00538
```
Again, the browser does open to the correct URL. Let me know how else I can help.

**Comment by jkitchin** [comment]
That is the error I have seen before. I don't know what causes it though. I don't think we use any http urls related to doi.org anymore in doi-utils. Some web searches suggest this is a web server configuration on the other end (e.g. https://www.linode.com/community/questions/17826/400-bad-request-the-plain-http-request-was-sent-to-https-port-nginx).

**Comment by kehoen** [comment]
Okay. Though, do you/others receive the same error? 

If not, perhaps it is an issue on my end I can continue to investigate. If so, I will leave it alone.

**Comment by jkitchin** [comment]
I have seen it, and others have seen it intermittently. For example, right now I don't see it, but you do. The only thing you might try doing, if you are skilled at this, is run edebug on the functions in doi-utils.el to see if there is some residual http request being sent via http:// instead of https://, which is what would trigger this issue I believe. You should only need to do this in functions that call `url-retrieve-synchronously`.

**Comment by kehoen** [comment]
Hey John -- I wanted to close the loop. I gave up trying to resolve this a little while ago, but then it came up again when I was exploring helm bibtex more closely. Per this [link](https://github.com/cpitclaudel/biblio.el/issues/17), I updated my Emacs version from 26.1 to 26.3 and the function works properly now. Thanks much for the help and for developing this tool.

**Comment by jkitchin** [comment]
that is great news. Thanks for the update, and link to the information about the cause.
