### ISSUE TITLE
"Wrong argument type: stringp, nil" when trying to open notes or entry from cite link

### ISSUE THREAD

**Issue by PhDyellow** [jkitchin/org-ref#705]
I was having trouble with using `org-ref-open-notes-at-point`.
With a bit of poking around, I found that  `cl-loop` was not being entered inside `org-ref-get-bibtex-key-and-file`. It expects a list, and `org-ref-find-bibliography` returns a `stringp` type for me.

I could get it to work in my case by replacing `(org-ref-find-bibliography)`  with `(list (org-ref-find-bibliography))` here:

https://github.com/jkitchin/org-ref/blob/0412de1aa542ebe94941b67817243ffc3a2e5a26/org-ref-core.el#L2220

Is the issue with  `org-ref-get-bibtex-key-and-file`, or should `org-ref-find-bibliography` be returning a list even if it only uses the fallback `org-ref-default-bibliography`?

I am using emacs version 27.0.50, cl-lib 1.0 and org-ref 1.1.1 (git commit 3d39b98e923e84e685ead45fb1df06df601a1c8c)

**Comment by jkitchin** [comment]
I think `org-ref-find-bibliography` should be returning a list. `org-ref-default-bibliography` should also be defined as a list. Do you have your defined as a string (e.g. a single bib file)?

**Comment by PhDyellow** [comment]
Yes, I did have it defined as a single string. Looking closer at the documentation and examples, it is a list there, I missed that the first time.

**Comment by PhDyellow** [comment]
I have renamed the issue to reflect my original problem, if someone has the same issue in the future.
