### ISSUE TITLE
Adding with org-ref-url-html-to-bibtex overwrites last inserted entry

### ISSUE THREAD

**Issue by pablobc-mx** [jkitchin/org-ref#708]
When using org-ref-url-html-to-bibtex twice in a row, it overwrites the entry that was added before it. It also doesn't save the bib file after insertion. I did a quick fix by inserting a newline after it inserts the new bib entry but I don't know if there's a proper fix to it.
```emacs-lisp
            (insert (if (require 'org-cliplink nil 'noerror)
                        ;; Sanitize values by replacing html entities
                        (org-ref-url-html-replace entry)
                      entry))
            ;; Added this (insert "\n")
            (bibtex-beginning-of-entry)
            (org-ref-clean-bibtex-entry)
            ;; And this (save-buffer))))))
```

**Comment by jkitchin** [comment]
thanks, I pushed a fix for this. Can you confirm the new \n is in the right place?

**Comment by pablobc-mx** [comment]
It is. But you should probably save the bibtex file after insertion. Otherwise you can't insert the citation you just added.

**Comment by jkitchin** [comment]
Ok, I pushed that. I am going to close this.
