### ISSUE TITLE
org-ref overrides helm-bibtex

### ISSUE THREAD

**Issue by jagrg** [jkitchin/org-ref#71]
There were a few changes in the way helm-bibtex inserts citation (see https://github.com/tmalsburg/helm-bibtex/issues/68), but org-ref overrides those changes. Is there something I can do to use helm-bibtex as a standalone application?

I noticed that If I eval my [init file](https://github.com/jagrg/.emacs.d/blob/master/init.el#L671) then helm-bibtex overrides org-ref. I'm not sure why. Maybe @tmalsburg would know.

**Comment by jkitchin** [comment]
What exactly does org-ref override? Probably you can just reset a variable after org-ref is loaded to get it back to what you want.

**Comment by jkitchin** [comment]
I just pushed a change that I think will fix this.

set org-ref-helm-bibtex-format-org to the function you want and see if that fixes it.

(defcustom org-ref-helm-bibtex-format-org
  'org-ref-helm-bibtex-format-org
  "Function for how helm-bibtex inserts citations."
  :type 'function
  :group 'org-ref)

(setf (cdr (assoc 'org-mode helm-bibtex-format-citation-functions))
      org-ref-helm-bibtex-format-org)

**Comment by tmalsburg** [comment]
@jagrg, I can only speculate about what's going when you reevaluate your init file because I don't know its content and because I don't know how org-ref modifies helm-bibtex' behavior.  Does John's change address your problem?

**Comment by jagrg** [comment]
> What exactly does org-ref override?

@jkitchin I think it overrides everything. For example, changing the default action doesn't seem to do anything.

```
(helm-delete-action-from-source "Open PDF file (if present)" helm-source-bibtex)
(helm-add-action-to-source "Open PDF file (if present)" 'helm-bibtex-open-pdf helm-source-bibtex 0)
```

With the example above, insert citation continues to be the default action. Changing `helm-bibtex-format-citation-functions` also doesn't do anything unless I reevaluate my init file.

> Probably you can just reset a variable after org-ref is loaded to get it back to what you want.

Can you elaborate.

**Comment by jagrg** [comment]
It turns out I needed to load helm-bibtex after org-ref:

```emacs-lisp
(use-package org-ref
  :load-path "~/Documents/git/org-ref"
  :load-path "~/Documents/git/helm-bibtex"
```

Problem fixed. Thanks for the help.

**Comment by jkitchin** [comment]
It is true that org-ref makes insert citation the default action.

I decided to make this overall configurable in a new variable org-ref-helm-bibtex-actions. You can set the order any way you want, and more easily add new functions.
