### ISSUE TITLE
Compatibility with Emacs 24.4?

### ISSUE THREAD

**Issue by lechten** [jkitchin/org-ref#711]
Hi,

do you plan to keep org-ref runnable on older Emacsen?  The officially required version is 24.4, which will stop working in the foreseeable future as Helm will stop supporting Emacs 24: https://github.com/emacs-helm/helm/issues/2282

Currently, upon `(require 'org-ref)`, Helm gets loaded, which may fail on Emacs 24.4 (before any function is executed).  To keep my own code, which depends on org-ref but does not need Helm, runnable on Emacs 24.4, I now assign `org-ref-reftex` to `org-ref-completion-library` to avoid loading of Helm.  This works, but is a hack: As I do not use any completion functionality, I'm wondering why I need to change it to use the remainder of org-ref.  Maybe there is a way to load Helm lazily when necessary?

Thanks for your work!

**Comment by jkitchin** [comment]
I don't have a strong commitment to keeping it running on older emacs. That requirement probably indicates how old org-ref is getting. At that time, 24.4 was probably close to state of the art! Most of our emacs these days are 25 (windows)/26(mac).

I don't think what you are doing is a hack. You have to pick some backend for org-ref, and you are picking a non-helm one. If you aren't using completion though, what are you doing with org-ref?

If you know a way to make helm load lazily, feel free to make a pull request implementing it.  Maybe this is as simple as adding a lot of autoload cookies to org-ref? I am not sure though.

I wouldn't mind eliminating helm, but it is still the default backend, and I guess many people still use it. I personally only use the ivy backend. There is only one helm command left in that as far as I know, `org-ref`, which I have not gotten around to replacing yet.

This is a low urgency for me, and probably won't happen before the summer.

**Comment by lechten** [comment]
Emacs 24.5 is shipped with Debian 9, whose 5-year life goes on [until June 2022](https://wiki.debian.org/LTS).

> If you aren't using completion though, what are you doing with org-ref?

Actually, I'm using Helm in my day-to-day environment, but the issue arose in a Docker build environment, where I use org-ref to create HTML bibliographies in reveal.js presentations: https://gitlab.com/oer/emacs-reveal

It would be simple to switch from Debian 9 but I like to have that "old" environment to test for the compatibility that I promise. The question is: When should I stop making that promise? Do you aim for Emacs 24 compatibility in your own code, say until 2022?

**Comment by jkitchin** [comment]
I think it should be fine to bump this to (emacs "25") now.  That is what I use on all my Windows machines. WDYT?

**Comment by lechten** [comment]
I won't object. The Helm maintainer mentioned "25.1", so I suggest not to go below that. Thanks for clarifying this.

**Comment by jkitchin** [comment]
What is the current version of helm that requires that?

**Comment by lechten** [comment]
I don't see it yet. The "next version" should have it: https://github.com/emacs-helm/helm/issues/2282#issuecomment-595789210

Maybe wait for that?

**Comment by jkitchin** [comment]
ok. I have gone ahead and pushed some updates on package versions. It turns out we are not even testing org-ref on anything less than 25.1 now anyway.
