### ISSUE TITLE
Retrieve references from numbers in articles?

### ISSUE THREAD

**Issue by Ziip-dev** [jkitchin/org-ref#712]
Hello John,
I am not sure this is just about org-ref, but do you have any idea about the feasibility of retrieving a citation in an article from its citation number?
For instance, while I am taking notes on a article: "_The author says that some studies [2, 5, 12]..._" I would like to run a function which retrieves the citations corresponding to these numbers from the references section of the article, and insert a cite link instead of the numbers. Actually the aim is to ease and speed up the process of going down to the reference section, copying the wanted citation, adding it to bib file via crossref or doi-utils, and finally inserting the cite link.

I guess something with `regexp + crossref or doi-utils + insert-cite-link` would do the trick, but I am not good enough (yet) in elisp and regexp to figure it out :/ Maybe I am utterly wrong though.

**Comment by jkitchin** [comment]
I can't think of a good way to do that. I usually copy the numbered ref and use a cross-ref function to get it. I wouldn't say it is reliable enough to automate though. You probably can't write a clever enough regexp, e.g. what to do about [2, 4-7], which is common.

**Comment by Ziip-dev** [comment]
Thanks for your quick answer and feedback.
Regarding your example I am imagining something like conditional regexp, but let's close this for now :) I must improve with regexp and elisp in order to attempt anything about this.
