### ISSUE TITLE
Org ref hangs on "Contacting host: arxiv.org:80"

### ISSUE THREAD

**Issue by Rareform** [jkitchin/org-ref#713]
I am trying to fetch some file from ArXiv to my laptop. I am using emacs through WSL2 on windows (I have Ubuntu 18.04 distribution and have emacs installed on it).  `doi-add-bibtex-entry` seems to be executed until the end. But if I try to fetch any arxiv file, emacs just hangs on `Contacting host: arxiv.org:80` message, which I have to cancel with `C-g`. What could be the reason?

**Comment by jkitchin** [comment]
I don't know why that would happen. Does it still happen today? Maybe an internet glitch?

**Comment by hughwilliams94** [comment]
I am seeing this behaviour too, I have just upgraded to emacs 27.0.91, not sure whether that could be the cause. Is there something I can do to debug?

**Comment by hughwilliams94** [comment]
Interestingly, using the `doi-utils-add-entry-from-crossref-query` command works up to the point that it returns the list of results, but when I select a result from that list the doi.org:443 request hangs.

**Comment by jkitchin** [comment]
This is probably some internet issue. maybe the doi server is having issues.

**Comment by hughwilliams94** [comment]
Yep seems to be back today
