### ISSUE TITLE
org-ref-possible-bib-files delivers weird output

### ISSUE THREAD

**Issue by hwesterholt** [jkitchin/org-ref#714]
Dear John,

I'm trying to use `org-ref-pdf-to-bibtex` on a few papers that I have downloaded (as it just so happens, one of them was written by some of your colleagues at CMU :). Unfortunately, this fails with `Wrong type argument: listp, "~/org/references/references.bib"`.

Some details: I only use my default bibliography file (namely `~/org/references/references.bib`), so I'd expect `org-ref` to fall back to using that.

Using edebug, I have narrowed my problem down to some unexpected behaviour in `org-ref-possible-bibfiles` which returns:
`(126 47 111 114 103 47 114 101 102 101 114 101 110 99 101 115 47 114 101 102 101 114 101 110 99 101 115 46 98 105 98 . "~/org/references/references.bib")`, i.e. the path to my bibliography file AND its ASCII representation. Unsurprisingly, this crashes.

Any help with this issue or just pointers in the right direction would be highly appreciated.

Thanks in advance,
Hermann

**Comment by jkitchin** [comment]
you need to set your default bibliography to '("~/org/references/references.bib"), i.e. it has to be a list, and not a string.

**Comment by hwesterholt** [comment]
Wow, that is slightly embarassing. I completely overlooked that part in my settings and will have to get much better at elisp. Thank you so much and stay safe!
