### ISSUE TITLE
Search and copy entry from default bibliography if not present in the local one 

### ISSUE THREAD

**Issue by tobiasBora** [jkitchin/org-ref#719]
Hello,

First, thanks a lot for this great tool. However, in order to be perfect, I'd love to be able to let `org-ref-helm-insert-cite-link` search in both the local and default bibliography file, and if by any chance the entry I want is not in the local bibliography file but in the global bibliography, then `org-ref` should  copy the BibTeX entry from the default bibliography file and insert it to the local file, and then insert in the org/tex file the citation as usual.

Do you think it's possible to implement? If needed, I can eventually try to do a PR. If not, do you know any other tool that does something like that?

Thanks!

PS: actually, I'd love to have a even more powerful function when, if the entry is not present at all and if I search online a BibTeX entry using for example the CrossRef Fallback, then `org-ref` would insert (if I press a specific shortcut) the entry in both the global library and the local library, before inserting the citation in the org/tex file.

**Comment by jkitchin** [comment]
I guess it is all possible. Probably the way to do it is to just write your own function and then set `org-ref-insert-cite-function ` to use that function. There isn't a need to modify the org-ref code that way. I don't know how easy it is to do what you want, it is probably better to just combine the entries from the beginning, maybe remove duplicates, and then check if the local has it or not, and insert if needed.

**Comment by tobiasBora** [comment]
What do you mean by "write your own function"? You mean from scratch or I just need to edit one or two functions in org-ref? If I do it, would you like some PR? I guess this function could be quite useful to anybody (it's quite annoying to move bibtex entries back and forth several bibliography files).

**Comment by jkitchin** [comment]
I mean you would write a function in your init file, e.g.
`(defun that-function (arg) (do it your way))`

and then `(setq org-ref-insert-cite-function 'that-function)` in your init file.

You do not need to modify org-ref at all, it was designed to make this kind of thing possible. 

You can make your function do what ever you want, the one you use just calls helm-bibtex because it is easy.

**Comment by tobiasBora** [comment]
Ok I see thanks.
