### ISSUE TITLE
Invalid Search Bound - Wrong side of point

### ISSUE THREAD

**Issue by jschaf** [jkitchin/org-ref#72]
This looks pretty much identical to https://github.com/jkitchin/org-ref/issues/55

Minimal Example, org-ref-bug.el

```
[[cite:Whatever]]
```

If I place my cursor on the second to last bracket, I get the error.

Here's the entire stack-trace:

```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  search-forward("," 16 t 1)
  (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))
  (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end)))
  (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key))
  (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))
  (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key))))
  (if (not (org-element-property :contents-begin object)) (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- ... 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ ... 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string ...))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))) link-string)
  (let* ((object (org-element-context)) (link-string (org-element-property :path object))) (let ((cp (point))) (goto-char (org-element-property :begin object)) (search-forward link-string (org-element-property :end object)) (goto-char (match-beginning 0)) (if (< cp (point)) nil (goto-char cp))) (if (not (org-element-property :contents-begin object)) (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end ...) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning ...) (setq key-beginning link-string-beginning))) (let ((bibtex-key ...)) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))) link-string))
  org-ref-get-bibtex-key-under-cursor()
  (setq key (org-ref-get-bibtex-key-under-cursor))
  (if key nil (setq key (org-ref-get-bibtex-key-under-cursor)))
  (let ((org-ref-bibliography-files (org-ref-find-bibliography)) (file)) (if key nil (setq key (org-ref-get-bibtex-key-under-cursor))) (setq file (catch (quote result) (let* ((--cl-var-- org-ref-bibliography-files) (file nil)) (while (consp --cl-var--) (setq file (car --cl-var--)) (if (org-ref-key-in-file-p key (file-truename file)) (throw (quote result) file)) (setq --cl-var-- (cdr --cl-var--))) nil))) (cons key file))
  org-ref-get-bibtex-key-and-file()
  (let* ((results (org-ref-get-bibtex-key-and-file)) (key (car results)) (bibfile (cdr results))) (if bibfile (save-excursion (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents bibfile) (bibtex-set-dialect ... t) (bibtex-search-entry key) (org-ref-bib-citation)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) "!!! No entry found !!!"))
  org-ref-get-citation-string-at-point()
  (message (org-ref-get-citation-string-at-point))
  (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels (org-element-property :path object)))) (message (concat (number-to-string count) " occurence" (if (or (= count 0) (> count 1)) (progn "s")))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning) (link-string-end)) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- ... 1)) (setq key-end (point)))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ ... 1)) (setq key-beginning (point)))) (setq bibfile (org-ref-strip-string (buffer-substring key-beginning key-end))) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile))))))
  (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels (org-element-property :path object)))) (message (concat (number-to-string count) " occurence" (if (or ... ...) (progn "s")))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning) (link-string-end)) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end ...) (setq key-end ...))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning ...) (setq key-beginning ...))) (setq bibfile (org-ref-strip-string (buffer-substring key-beginning key-end))) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile)))))))
  (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels ...))) (message (concat (number-to-string count) " occurence" (if ... ...))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning) (link-string-end)) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if ... ... ...)) (save-excursion (if ... ... ...)) (setq bibfile (org-ref-strip-string ...)) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile))))))))
  (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count ...)) (message (concat ... " occurence" ...)))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" ...)) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object ...) (link-string ...) (link-string-beginning) (link-string-end)) (save-excursion (goto-char ...) (search-forward link-string nil nil 1) (setq link-string-beginning ...) (setq link-string-end ...)) (if (> link-string-beginning ...) (progn ...)) (let (key-beginning key-end) (save-excursion ...) (save-excursion ...) (setq bibfile ...) (if ... ... ...))))))))
  (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context ...) (org-ref-count-labels ...))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context ...) (org-ref-count-labels ...))) ((string= type "label") (let (...) (message ...))) ((string= type "custom-id") (save-excursion (org-open-link-from-string ...) (message "%s" ...))) ((string= type "bibliography") (let* (... ... ... ... ...) (save-excursion ... ... ... ...) (if ... ...) (let ... ... ... ... ...))))))))
  (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message ...)) ((string= type "ref") (message "%scount: %s" ... ...)) ((string= type "eqref") (message "%scount: %s" ... ...)) ((string= type "label") (let ... ...)) ((string= type "custom-id") (save-excursion ... ...)) ((string= type "bibliography") (let* ... ... ... ...))))))))
  (progn (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond (... ...) (... ...) (... ...) (... ...) (... ...) (... ...))))))))
  (if (not (looking-at " ")) (progn (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object ...) (type ...)) (save-excursion (cond ... ... ... ... ... ...))))))))
  org-ref-link-message()
  apply(org-ref-link-message nil)
  timer-event-handler([t 0 0 500000 t org-ref-link-message nil idle 0])
```

I tried the noerror parameter in search-forward to `t` but it didn't seem to make a difference.  The `search-forward` docs states:

> Optional third argument [NOERROR], if t, means if fail just return nil (no error).

It says it has to be `t` rather than just `non-nil`.

I'm on the latest org-ref master on Emacs 25.0.51

**Comment by jkitchin** [comment]
I can confirm this partially.

I guess you have literal links on? i.e. you see the [[ ]] in the link?

With descriptive links this is not an issue for me. I also don't use
[[ ]] around citations unless it is up against text.


Joe Schafer writes:

> This looks pretty much identical to https://github.com/jkitchin/org-ref/issues/55
>
> Minimal Example, org-ref-bug.el
>
> ```
> [[cite:Whatever]]
> ```
>
> If I place my cursor on the second to last bracket, I get the error.
>
> Here's the entire stack-trace:
>
> ```
> Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
>   search-forward("," 16 t 1)
>   (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))
>   (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end)))
>   (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key))
>   (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))
>   (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- (match-end 0) 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ (match-beginning 0) 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string (buffer-substring key-beginning key-end)))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key))))
>   (if (not (org-element-property :contents-begin object)) (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- ... 1)) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ ... 1)) (setq key-beginning link-string-beginning))) (let ((bibtex-key (org-ref-strip-string ...))) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))) link-string)
>   (let* ((object (org-element-context)) (link-string (org-element-property :path object))) (let ((cp (point))) (goto-char (org-element-property :begin object)) (search-forward link-string (org-element-property :end object)) (goto-char (match-beginning 0)) (if (< cp (point)) nil (goto-char cp))) (if (not (org-element-property :contents-begin object)) (progn (let (link-string-beginning link-string-end) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end ...) (setq key-end link-string-end))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning ...) (setq key-beginning link-string-beginning))) (let ((bibtex-key ...)) (set-text-properties 0 (length bibtex-key) nil bibtex-key) bibtex-key)))) link-string))
>   org-ref-get-bibtex-key-under-cursor()
>   (setq key (org-ref-get-bibtex-key-under-cursor))
>   (if key nil (setq key (org-ref-get-bibtex-key-under-cursor)))
>   (let ((org-ref-bibliography-files (org-ref-find-bibliography)) (file)) (if key nil (setq key (org-ref-get-bibtex-key-under-cursor))) (setq file (catch (quote result) (let* ((--cl-var-- org-ref-bibliography-files) (file nil)) (while (consp --cl-var--) (setq file (car --cl-var--)) (if (org-ref-key-in-file-p key (file-truename file)) (throw (quote result) file)) (setq --cl-var-- (cdr --cl-var--))) nil))) (cons key file))
>   org-ref-get-bibtex-key-and-file()
>   (let* ((results (org-ref-get-bibtex-key-and-file)) (key (car results)) (bibfile (cdr results))) (if bibfile (save-excursion (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents bibfile) (bibtex-set-dialect ... t) (bibtex-search-entry key) (org-ref-bib-citation)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) "!!! No entry found !!!"))
>   org-ref-get-citation-string-at-point()
>   (message (org-ref-get-citation-string-at-point))
>   (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels (org-element-property :path object)))) (message (concat (number-to-string count) " occurence" (if (or (= count 0) (> count 1)) (progn "s")))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning) (link-string-end)) (save-excursio
>  n (goto-
>  char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end (- ... 1)) (setq key-end (point)))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning (+ ... 1)) (setq key-beginning (point)))) (setq bibfile (org-ref-strip-string (buffer-substring key-beginning key-end))) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile))))))
>   (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels (org-element-property :path object)))) (message (concat (number-to-string count) " occurence" (if (or ... ...) (progn "s")))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning) (link-string-end)) (save-excursio
>  n (goto-
>  char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if (search-forward "," link-string-end t 1) (setq key-end ...) (setq key-end ...))) (save-excursion (if (search-backward "," link-string-beginning 1 1) (setq key-beginning ...) (setq key-beginning ...))) (setq bibfile (org-ref-strip-string (buffer-substring key-beginning key-end))) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile)))))))
>   (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count (org-ref-count-labels ...))) (message (concat (number-to-string count) " occurence" (if ... ...))))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" (org-element-property :path object))) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object (org-element-context)) (link-string (org-element-property :path object)) (link-string-beginning)
>  (link-st
>  ring-end)) (save-excursion (goto-char (org-element-property :begin object)) (search-forward link-string nil nil 1) (setq link-string-beginning (match-beginning 0)) (setq link-string-end (match-end 0))) (if (> link-string-beginning (point)) (progn (goto-char link-string-beginning))) (let (key-beginning key-end) (save-excursion (if ... ... ...)) (save-excursion (if ... ... ...)) (setq bibfile (org-ref-strip-string ...)) (if (file-exists-p bibfile) (message "%s exists." bibfile) (message "!!! %s NOT FOUND !!!" bibfile))))))))
>   (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context (org-element-property :path object)) (org-ref-count-labels (org-element-property :path object)))) ((string= type "label") (let ((count ...)) (message (concat ... " occurence" ...)))) ((string= type "custom-id") (save-excursion (org-open-link-from-string (format "[[#%s]]" ...)) (message "%s" (org-get-heading)))) ((string= type "bibliography") (let* ((bibfile) (object ...) (link-string ...) (link-string-beginning) (link-string-end)) (save-excursion (goto-char ...) (search-forward link-string nil nil 1) (setq link-string-beginning ...) (setq
>   link-st
>  ring-end ...)) (if (> link-string-beginning ...) (progn ...)) (let (key-beginning key-end) (save-excursion ...) (save-excursion ...) (setq bibfile ...) (if ... ... ...))))))))
>   (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message (org-ref-get-citation-string-at-point))) ((string= type "ref") (message "%scount: %s" (org-ref-get-label-context ...) (org-ref-count-labels ...))) ((string= type "eqref") (message "%scount: %s" (org-ref-get-label-context ...) (org-ref-count-labels ...))) ((string= type "label") (let (...) (message ...))) ((string= type "custom-id") (save-excursion (org-open-link-from-string ...) (message "%s" ...))) ((string= type "bibliography") (let* (... ... ... ... ...) (save-excursion ... ... ... ...) (if ... ...) (let ... ... ... ... ...))))))))
>   (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond ((-contains\? org-ref-cite-types type) (message ...)) ((string= type "ref") (message "%scount: %s" ... ...)) ((string= type "eqref") (message "%scount: %s" ... ...)) ((string= type "label") (let ... ...)) ((string= type "custom-id") (save-excursion ... ...)) ((string= type "bibliography") (let* ... ... ... ...))))))))
>   (progn (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object (org-element-context)) (type (org-element-property :type object))) (save-excursion (cond (... ...) (... ...) (... ...) (... ...) (... ...) (... ...))))))))
>   (if (not (looking-at " ")) (progn (save-restriction (widen) (if (eq major-mode (quote org-mode)) (progn (let* ((object ...) (type ...)) (save-excursion (cond ... ... ... ... ... ...))))))))
>   org-ref-link-message()
>   apply(org-ref-link-message nil)
>   timer-event-handler([t 0 0 500000 t org-ref-link-message nil idle 0])
> ```
>
> I tried the noerror parameter in search-forward to `t` but it didn't seem to make a difference.  The `search-forward` docs states:
>
>> Optional third argument [NOERROR], if t, means if fail just return nil (no error).
>
> It says it has to be `t` rather than just `non-nil`.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/72

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
I pushed a little change to fix this I think.

**Comment by jschaf** [comment]
Thanks, that fixed it.  Yes, I had literal links on, mostly because it was hard to tell what "pg. 2" referred to if I had [[cite:my-key][pg. 2]].

**Comment by jkitchin** [comment]
You can get a link tooltip (not an org-ref one unfortunately) if you
mouse over it which will show my-key. and if you move your cursor in it
you should get a message in the minibuffer for the citation.

Joe Schafer writes:

> Thanks, that fixed it.  Yes, I had literal links on, mostly because it was hard to tell what "pg. 2" referred to if I had [[cite:my-key][pg. 2]].
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/org-ref/issues/72#issuecomment-163675888

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
