### ISSUE TITLE
Split ivy and helm completion into two packages?

### ISSUE THREAD

**Issue by xiangsheng** [jkitchin/org-ref#721]
Would you consider split completion method using ivy and helm respectively into two packages? If so, when people only use the ivy completion for org-ref, they can avoid install the heavy helm dependency.

**Comment by jkitchin** [comment]
I tried to do this a long time ago, and it is not practical to do it. I don't have any plans to try doing it again. Maybe some future new version of org-ref will not have this dependency, but that is a long way in the future and depends on the features of the not yet developed citation syntax for org-mode.
