### ISSUE TITLE
Support for acronyms in org-beamer-export

### ISSUE THREAD

**Issue by rpls** [jkitchin/org-ref#723]
I can't seem to get `[[gls:XX]]` or any other type of glossary/acronym link to work when I try to export with the export functions for beamer. It will simply output the acronym label (i.e. `XX`) to the latex output. `[[cite:XX]]` links seem to work just fine. When I export the document with org-latex export, the output is also correct. From what I understood, the beamer export is based upon the latex export. Where can I start to look for a workaround?

Minimal example: 
```org-mode
#+STARTUP: beamer
#+TITLE: Beamer org-ref test
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [aspectratio=1610,compact,11pt]
#+BEAMER_HEADER: \usepackage[acronyms]{glossaries}
#+BEAMER_HEADER: \makeglossaries

* Test
This is a cite link: [[cite:this]].

* Test2
- This is a gls link: [[gls:this]].
- This is an an link: [[ac:this]].
```
`org-beamer-export-as-latex` output (abbreviated some irrelevant stuff):
```latex
\documentclass[aspectratio=1610,compact,11pt]{beamer}
% [...]
\usepackage[acronyms]{glossaries}
\makeglossaries
% [...]
\begin{document}

\maketitle
\begin{frame}{Outline}
\tableofcontents
\end{frame}


\begin{frame}[label={sec:orgb808d69}]{Test}
This is a cite link: \cite{this}.
\end{frame}

\begin{frame}[label={sec:org48948e3}]{Test2}
\begin{itemize}
\item This is a gls link: this.
\item This is an an link: THIS.
\end{itemize}
\end{frame}
\end{document}
```

There seems to be some form of processing, since the `[[ac:this]]` gets output as `THIS`.

`org-latex-export-as-latex` output:
```latex
\documentclass[aspectratio=1610,compact,11pt]{beamer}
% [...]
\begin{document}

\maketitle
\tableofcontents


\section{Test}
\label{sec:orge9f8dae}
This is a cite link: \cite{this}.

\section{Test2}
\label{sec:org37b07a3}
\begin{itemize}
\item This is a gls link: \gls{this}.
\item This is an an link: \gls{this}.
\end{itemize}
\end{document}
```
The output is as intended, and the `[[ac:this]]` is translated to `\gls{this}` instead of `THIS`.

**Comment by jkitchin** [comment]
The problem here is that beamer has its own backend and the acronym/glossary links are only defined for the 'latex backend. It defaults to just the link path for other backends.

I added the beamer backend so they will export for that too.


```

**Comment by rpls** [comment]
Nice, thanks! I see how the code works now. And I think you missed one of the backends (the `glslink` feature as far es i can tell).

**Comment by jkitchin** [comment]
Thanks. I just pushed that.
