### ISSUE TITLE
`org-ref-pdf-to-bibtex'  in a pdf-tools mode buffer is broken but doi-insert-bibtex work

### ISSUE THREAD

**Issue by pRot0ta1p** [jkitchin/org-ref#724]
calling **org-ref-pdf-to-bibtex** in a pdf-tools buffer, then choose a DOI will give a **wrong-type-argument: stringp, nil** error. 
It's wired, it just stop working all of sudden, and **doi-insert-bibtex** still work.
Any way here is the backtrace and my config:
```Emacs-lisp
  (use-package org-ref
    :init
    (setq org-ref-completion-library 'org-ref-ivy-cite
          org-ref-prefer-bracket-links t)
    :after org
    :config
    (setq bibtex-autokey-year-length 4
      bibtex-autokey-name-year-separator "-"
      bibtex-autokey-year-title-separator "-"
      bibtex-autokey-titleword-separator "-"
      bibtex-autokey-titlewords 2
      bibtex-autokey-titlewords-stretch 1
      bibtex-autokey-titleword-length 5))
  (use-package doi-utils
    :after org)
  (use-package org-ref-isbn
    :after org)
  (use-package org-ref-pubmed
    :after org)
  (use-package org-ref-arxiv
    :after org)
  (use-package org-ref-sci-id
    :after org)
````

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  org-ref-bibtex-key-from-doi("10.1088/0957-4484/22/31/315302")
  org-ref-pdf-to-bibtex()
  funcall-interactively(org-ref-pdf-to-bibtex)
  call-interactively(org-ref-pdf-to-bibtex nil nil)
  command-execute(org-ref-pdf-to-bibtex)

```
Any suggestion for debugging?

**Comment by pRot0ta1p** [comment]
After some testing, I figured out that this is because I have a duplicated in my bib file...

So its a feature, not a bug :smile: , although it will nice to have org-ref print a error message that tells
user why org-ref refuse to add bib entry.

**Comment by jkitchin** [comment]
org-ref usually puts in a message that the doi already exists. That isn't the error you described, which is a nil in expand-file-name. I haven't been able to reproduce this.

**Comment by pRot0ta1p** [comment]
I found the reason, I forgot to set the variable org-ref-default-bibliography, org-ref just call the right bib file because it happens to be put in the same folder of my org file. 
Dumb mistake by me.....
