### ISSUE TITLE
Getting an error after installing org-ref

### ISSUE THREAD

**Issue by ram535** [jkitchin/org-ref#725]
I am getting this error after installing org-ref.

```
Error (use-package): org-ref/:catch: Cannot open load file: No such file or directory, biblio
```
I use straight.el and this is what I used to install org-ref:
`(use-package org-ref)`

**Comment by jkitchin** [comment]
I guess there are some errors in the Messages that indicate biblio was not installed for some reason.

**Comment by ram535** [comment]
Okay, That solved the problem. Installing `biblio` but also making sure `org-ref` is load after `biblio`.
Thanks.

```
(use-package biblio)  

(use-package org-ref
  :after (biblio))
```
