### ISSUE TITLE
Customize reference to equations export format?

### ISSUE THREAD

**Issue by tdehaeze** [jkitchin/org-ref#727]
Hi guys,

I would like to customize a little bit the markdown export of `eqref` links.
Instead of exporting to `(format "[%s](#%s)" keyword keyword)`, I would like to export it to `(format "\\eqref{%s}" keyword)` and let mathjax deals with it.
The corresponding lines in the code are [here](https://github.com/jkitchin/org-ref/blob/5bb9be2232db72b04754d7e4c02a3976ad422f6f/org-ref-core.el#L1960).

I guess I could add the following to my config file:
```
    (defun org-ref-eqref-export (keyword desc format)
      (cond
       ((eq format 'latex) (format "\\eqref{%s}" keyword))
       ((eq format 'html) (format "\\eqref{%s}" keyword))
       ((eq format 'md) (format "\\eqref{%s}" keyword))))
```
Is there any other better ways to do it?
Thanks

**Comment by jkitchin** [comment]
That is the only way to do it that I know of. The only other option would be to define an advice around that function for what you want it to do. The benefit of that is it is easy to remove the advice if you don't want it later.

**Comment by tdehaeze** [comment]
Thanks a lot @jkitchin !

I'll read some emacs lisp documentation to see how advice works :smile:

**Comment by jkitchin** [comment]
I have been using advice more in scimax, with toggle functions to turn it on and off. See https://github.com/jkitchin/scimax/blob/master/scimax-org-latex.el#L289 for an example of an around advice.
