### ISSUE TITLE
setting org-ref-open-pdf-function doesn't change what happens when I hit `p` on an open entry

### ISSUE THREAD

**Issue by japhir** [jkitchin/org-ref#730]
After struggling to follow [the manual to get my zotero file links in my bib file to link to the pdf's](https://github.com/jkitchin/org-ref/blob/master/org-ref.org#a-note-for-mendeley-jabref-and-zotero-users), I'm almost there but in the last step I run into a problem.

I've changed the following settings, and now `my/org-ref-open-pdf-at-point` works when I call it directly when the point is on a citation.

But when I `<RET>` or `C-c C-o` on the citation and click `p` for `Open pdf` this results in a message telling me "no pdf found for `<citekey>`" (with the correct citation key). I've double-checked that `org-ref-open-pdf-function` is set correctly. 

Any ideas on how to get the last step configured correctly?

```emacs-lisp

(setq bibtex-completion-bibliography
      '("/home/japhir/SurfDrive/bibliography/references.bib"
        "/home/japhir/Documents/References/PhD.bib")))

(setq bibtex-completion-pdf-field "file")

(defun my/org-ref-open-pdf-at-point ()
  "Open the pdf for bibtex key under point if it exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
    (key (car results))
    (pdf-file (car (bibtex-completion-find-pdf-in-field key))))
    (if (file-exists-p pdf-file)
       (org-open-file pdf-file)
      (message "No PDF found for %s" key))))

(setq org-ref-open-pdf-function 'my/org-ref-open-pdf-at-point)
```

By the way, I had to tweak the function a little to work with the `field` key in stead of looking for a directory. This may be useful to mention in the docs? Thanks in advance!

**Comment by jkitchin** [comment]
I need some more information to help you figure this out. What is your `org-ref-cite-onclick-function` variable set to?

C-h v org-ref-cite-onclick-function

**Comment by japhir** [comment]
Hmm ok here is the output, which I don't fully understand, to be honest:

```
org-ref-cite-onclick-function is a variable defined in ‘org-ref-core.el’.
Its value is #f(compiled-function (_) #<bytecode 0x1d21059>)
Original value was nil

  This variable may be risky if used as a file-local variable.

Documentation:
Function that runs when you click on a cite link.
The function must take one argument which is the path of the link
that was clicked on. This function is normally set by the
function in ‘org-ref-completion-library’.

You can customize this variable.
```

**Comment by japhir** [comment]
Oh and my customisations for org-ref are in [this line of my config file](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#org-ref). By now I've commented out the `org-ref-pdf-directory` and `bibtex-completion-pdf-open` and JIR lines.

**Comment by jkitchin** [comment]
I think what you need to customize is `org-ref-get-pdf-filename-function`

It doesn't look like org-ref-open-pdf-function is getting used in ivy-cite right now.

**Comment by japhir** [comment]
Great! The newest version works with the previous custom `my/org-ref-open-pdf-at-point`, there was no need to overwrite the `org-ref-get-pdf-filename-function` (probably because my `my/org-ref-open-pdf-at-point` circumvents this piece of code that's in org-ref?)

When I don't use `my/org-ref-open-pdf-at-point` but only specify 

```
(setq org-ref-get-pdf-filename-function 'bibtex-completion-find-pdf-in-field)
```

it gives me the following error:

```
org-ref-open-pdf-at-point: Wrong type argument: stringp, ("/home/japhir/Zotero/storage/8KDWAK4W/Eiler2007EPSL.pdf")
```

So it gets the right path, but as a string which is probably not the correct type?

**Comment by jkitchin** [comment]
That message suggests you are getting a list containing the string. I guess `bibtex-completion-find-pdf-in-field` is returning a list, not a string.

**Comment by japhir** [comment]
Thanks, I'm not very knowledgable with elisp (yet), my config is mostly pasted together. 
I've had a quick look at [how to convert a list to a string](https://stackoverflow.com/questions/18979300/how-to-convert-list-to-string-in-emacs-lisp), but I couldn't figure it out for now, so I'll just keep using the custom function for now as opposed to rewriting it to simply return a string.

Perhaps the last step to resolve this issue would be to update the docs accordingly?

Kind regards

**Comment by jkitchin** [comment]
This seems to be an issue with bibtex-completion-find-pdf-in-field returning a list, which I suppose is reasonable if that field contains multiple pdfs, but it is not compatible with org-ref-open-pdf-at-point which expects one pdf filename as a string, and not a list containing one filename.
