### ISSUE TITLE
bibliography file is exported to \bibliography{../../../../biblio}

### ISSUE THREAD

**Issue by santiagomejia** [jkitchin/org-ref#732]
Thanks so much for putting creating org-ref.  Looks very promising.

I've been trying to make it work for a couple of hours with no luck.  The bibliography file gets exported wrongly.  I suspect it is a simple mistake.

The org file containing
```
cite:hallenbeck-2013-effec
bibliography:/home/myhome/dropbox/papers/biblioNatbib.bib
```
Gets exported as

```
\cite{hallenbeck-2013-effec}
\bibliography{../../../../papers/biblioNatbib}
```
(in case it is useful, each of the folders gets replaced by a "..")

Any help would be much appreciated.

**Comment by jkitchin** [comment]
I think that is what I would expect it to export as, that is a relative path to the bibliography from where the org file is I think. The only other option is an absolute path, but then the document is not as portable. 

Are you having some problem compiling it?

**Comment by santiagomejia** [comment]
Thanks for getting back so quickly. 

Except for the bibliography file, the document seems to be exporting well.  But the LaTeX document compiles all references as question marks.

Do you know how can I use an absolute path?  (or get the relative path to compile in LaTeX)?

In the org-file I am using `bibliography:/home/myhome/Dropbox/papers/biblioNatbib.bib` (I would have thought that this is an absolute path).  But this gets exported as: `\bibliography{../../../../papers/biblioNatbib}`

**Comment by jkitchin** [comment]
maybe you are missing a bibliography style or something, or your process does not call bibtex.

your link does have an absolute path, but org-ref makes it a relative path. I don't remember why it does that, but I guess it is for a good reason.

**Comment by mohkale** [comment]
@jkitchin I'm having a similar issue. I tried compiling the produced tex file manually using auctex. [Here's](
https://github.com/jkitchin/org-ref/files/4859283/a.txt) the compilation output for the file:

```org
#+TITLE: Notes on: Gregory, J. (2009): Game engine architecture

hello world. can you believe it. $x + y = 10$, I mean, yeah. cite:86cohen-introduction, yep.

$y+z = x^5$

bibliographystyle:unsrt
bibliography:~/Dropbox/org/bibliography/index.bib
```

NOTE the important part of the output is:

```
Latexmk: Failed to find one or more bibliography files:
    '../../../../../Dropbox/org/bibliography/index.bib'
```

I've found a [stackoverflow post](https://tex.stackexchange.com/questions/203369/citation-not-found-if-bib-file-in-parent-directory) about someone facing similair issues and evidently some versions of bibtex don't support relative paths to bibliography files :cry:.

I agree making the paths absolute would hurt portability, but I also would like to suggest there be a user option to determine this for those whose tex install seems to be failing to find the bib file.

**Comment by jkitchin** [comment]
Another way to do this that doesn't require modifying the code is:

```
(org-link-set-parameters
 "bibliography"
 :export (lambda (bibfiles desc format)
	   (format "\\bibliography{%s}"
		   (replace-regexp-in-string
		    "\\.bib" "" bibfiles))))
```

I am sort of hesitant to add just a binary variable for relative and absolute paths, it might be worth considering making a variable that is a function that can do either of those, or some other fancy thing someone might imagine. WDYT?

**Comment by mohkale** [comment]
Hmmm... I would like something builtin to the package so if others face this issue they can just apropos through the packages customize options and find something relevent to this issue. 

I also like your suggestion of using a variable pointing to a function determining what to do. That would lead to a cleaner codebase and the docstring of it could include a mention why users may want to switch it to `expand-file-name`.

Would you like me to implement that and send over a pull request?

**Comment by jkitchin** [comment]
I would be happy to take a pull request on this.
