### ISSUE TITLE
Changes to org-ref-notes-functions to fix #706 removed org-ref-create-notes-hook

### ISSUE THREAD

**Issue by Horsevad** [jkitchin/org-ref#733]
Hi, with some of the recent commits to change the way notes are made:

https://github.com/jkitchin/org-ref/commit/875371a63430544e446db7a76b44b33c7e20a8bd
https://github.com/jkitchin/org-ref/commit/caca18f8eeae213c2719e628949df70910f7d3c7

the org-ref-creates-notes-hook dissapeared, is there a good reason for this ?

It looks like the code was just moved over from org-ref-open-bibtex-notes to org-ref-notes-function, with the exception of the hook. 
Unless there is a good reason, why not keep it ? 

I don't know how to make the pull request, but changing the function to the following, reintroduces the hook (just copied form the old code)

(defun org-ref-notes-function-one-file (key)
  "Function to open note belonging to KEY.
 Set `org-ref-notes-function' to this function if you use one
long file with headlines for each entry."
  ;; save key to clipboard to make saving pdf later easier by pasting.
  (with-temp-buffer
    (insert key)
    (kill-ring-save (point-min) (point-max)))
  (let ((entry (with-temp-buffer
		 (insert (org-ref-get-bibtex-entry key))
		 (bibtex-mode)
		 (bibtex-beginning-of-entry)
		 (bibtex-parse-entry)) ))

    (save-restriction
      (if  org-ref-bibliography-notes
	  (find-file-other-window org-ref-bibliography-notes)
	(error "org-ref-bibliography-notes is not set to anything"))

      (widen)
      (goto-char (point-min))
      (let* ((headlines (org-element-map
			    (org-ref-parse-buffer)
			    'headline 'identity))
	     (keys (mapcar
		    (lambda (hl) (org-element-property :CUSTOM_ID hl))
		    headlines)))
	(if (-contains? keys key)
	    ;; we have it so we go to it.
	    (progn
	      (org-open-link-from-string (format "[[#%s]]" key))
	      (funcall org-ref-open-notes-function))
	  ;; no entry found, so add one
	  (goto-char (point-max))
	  (insert (org-ref-reftex-format-citation
		   entry (concat "\n" org-ref-note-title-format)))
	  (mapc (lambda (x)
		  (save-restriction
		    (save-excursion
		      (funcall x))))
		org-ref-create-notes-hook)
	  (save-buffer))))))

**Comment by guoqinglei** [comment]
Yes, I have also found this event. Personally, I prefer the older one with org-ref-create-notes-hook.

**Comment by guoqinglei** [comment]
refer to issue "No "[[cite:key]]" following the note When run M-x org-ref-open-bibtex-notes #736". Only modify the org-ref-note-tittle-format is ok.
