### ISSUE TITLE
No "[[cite:key]]" following the note When run M-x org-ref-open-bibtex-notes

### ISSUE THREAD

**Issue by guoqinglei** [jkitchin/org-ref#736]
I have just updated org-ref and org and when I run M-x org-ref-open-bibtex-notes on a bibtex entry, 
There should be [[cite:key]] following the note, i.e.:

 ```
** TODO 2015 - Selecting most profitable instruction-set extensions using ant colony heuristic
 :PROPERTIES:
  :Custom_ID: 7367250
  :AUTHOR: Wang, Xiao, Liu, Casseau \& Yang
  :JOURNAL: 
  :YEAR: 2015
  :VOLUME: 
  :PAGES: 1-7
  :DOI: 
  :URL: 
 :END:

 cite:7367250

```

But now, the "cite:7367250" has been gone when I run M-x org-ref-open-bibtex-notes.

Anyone can give me some advice ?

**Comment by jkitchin** [comment]
This is controlled by the variable `org-ref-note-title-format`. You can probably get what you want by adding this your init.el file:
```
(setq org-ref-note-title-format "** TODO %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :AUTHOR: %9a\n  :JOURNAL:
%j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n
:END:\n\n [[cite:%k]]")
```

**Comment by guoqinglei** [comment]
> This is controlled by the variable `org-ref-note-title-format`. You can probably get what you want by adding this your init.el file:
> 
> ```
> (setq org-ref-note-title-format "** TODO %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :AUTHOR: %9a\n  :JOURNAL:
> %j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n
> :END:\n\n [[cite:%k]]")
> ```

Thanks for your response. I'll have a try.
