### ISSUE TITLE
org-ref-notes-function-many-files duplicates #+TITLE property 

### ISSUE THREAD

**Issue by umbromancer** [jkitchin/org-ref#737]
Hi,
Thank you for org-ref!

(setq org-ref-notes-function 'org-ref-notes-function-many-files)

Works as expected, except that it duplicates the #+TITLE property when creating a new notes file. An example is:

#+TITLE: #+TITLE: Notes on: Boes, J. R., Gumuslu, G., Miller, J. B., Gellman, A. J., & Kitchin, J. R. (2015): Estimating bulk-composition-dependent H2 adsorption energies on Cu_xpd_1-x alloy (111) surfaces

**Comment by jkitchin** [comment]
This is probably happening outside of org-ref in `bibtex-completion-edit-notes`.

What is `bibtex-completion-notes-template-multiple-files` set to?

**Comment by umbromancer** [comment]
I have not messed with it. It is default to `"#+TITLE: Notes on: ${author-or-editor} (${year}): ${title}\n\n"` as expected.

Using org-ref from MELPA `"org-ref: Version 1.1.1 (git-commit 9788b1235ce4a74d303074ac88036715ac71de28)"`

**Comment by jkitchin** [comment]
If you run a command like:

(bibtex-completion-edit-notes '("doerscher-2019-dynam-decoup"))` with a key in your bib file, does it put two titles?

**Comment by umbromancer** [comment]
Yes, it does. I suppose this means the bug is in helm-bibtex.

**Comment by jkitchin** [comment]
That is my guess. My version (helm-bibtex-20191028.1313) doesn't do that, so if yours does, I guess it is new.

**Comment by umbromancer** [comment]
Thnak you. I opened an issue in helm-bibtex
