### ISSUE TITLE
No menu of actions while click on the cite link

### ISSUE THREAD

**Issue by guoqinglei** [jkitchin/org-ref#738]
When I click on a cite link, there should be a menu of actions. But now, there isn't. 
I don't know why.  After I restart the emacs, it works well again.
I am a little worried that maybe sometime it will happen again.
So in this case, are there any method to debug this problem if no menu of actions while click on the cite link?

Thanks a lot.

**Comment by jkitchin** [comment]
I don't know why that would happen. It suggests the library wasn't fully loaded, and if it wasn't there should be some message in the Messages buffer that might indicate some kind of error.

**Comment by guoqinglei** [comment]
For example, when I click on a cite link, it shows something in mini buffer as follows:

```
Panitanarak, T., Distributed single-source shortest path algorithms with two-dimensional graph layout, In M. W. Berry, A. Mohamed, & B. W. Yap (Eds.), Supervised and Unsupervised Learning for Data Science  (pp. 39–58) (2020). Cham: Springer International Publishing.
[o]pen [p]df [n]otes [u]rl [w]os [c]iting [r]elated [g]oogle scholar [P]ubmed [C]rossref [y]Copy entry to file [s]Copy summary [q]uit 
```

Then the cursor was stuck on the clicked position. I expect the action menu of helm buffer to appear, but it doesn't.
The problem happens after I have used org-roam utilities.
I wonder if is there some conflicts with org-roam and org-ref ?

**Comment by jkitchin** [comment]
Hm. That does sound like org-roam could be redefining some completion mechanisms. but that seems unusual. maybe it is turning off helm-mode? or redefining what is used for ido-completion?

**Comment by fleimgruber** [comment]
@guoqinglei If you could provide the steps to reproduce this I would also have a look as I use org-roam as well.

**Comment by jkitchin** [comment]
@guoqinglei can you run `M-x org-ref` and paste the output here?

**Comment by guoqinglei** [comment]
> @guoqinglei If you could provide the steps to reproduce this I would also have a look as I use org-roam as well.

Unfortunately, I cannot reproduce this now. The possible reason may be that  I've update org-ref version or done something else without any intention. It works well now after I've tried to execute M-x org-roam-open-file and some other org-roam functions.
