### ISSUE TITLE
Unable to use citeyear:

### ISSUE THREAD

**Issue by sunnyhasija** [jkitchin/org-ref#740]
How to cite by supressing the author? 
Expected use: 
Smith citeyear: smith_2019 states that citing by year is easy.

Expected output: 
Smith (2019) states that citing by year is easy. 

Current output: 
Smith (Smith 2019) states that citing by year is easy. 

Moreover  ```C-u``` does not show the option to citeyear or citeauthor. 

Could you please provide some guidance?

**Comment by jkitchin** [comment]
I am unable to reproduce this. There is definitely a citeyear and citeauthor defined in `org-ref-natbib-types` which should be included in `org-ref-cite-types`.

How that gets formatted in LaTeX is up to the bibliography style you select, org-ref doesn't do that. If you are outputting to HTML, there are many limitations on what is possible.

Regarding C-u, it depends on the backed you are using, for ivy-cite, usually I do C-c ] then choose a reference, then C-u enter to choose the cite type.

**Comment by sunnyhasija** [comment]
Thanks for making it clear Dr. Kitchin. 
I am using ox-pandoc to output to docx so that might be the issue. I was able to use C-u after selecting the citation and chnage the cite type. 

I am closing this issue. Once again, thank you for your help.

**Comment by jkitchin** [comment]
docx is still a hard export target. I have tried a lot of things:

https://kitchingroup.cheme.cmu.edu/blog/2015/01/29/Export-org-mode-to-docx-with-citations-via-pandoc/
- https://kitchingroup.cheme.cmu.edu/blog/2015/06/11/ox-pandoc-org-mode-+-org-ref-to-docx-with-bibliographies/
- https://github.com/jkitchin/scimax/blob/master/ox-word.el

and some others, with mixed success.
