### ISSUE TITLE
Increase the height of the cite menu popup

### ISSUE THREAD

**Issue by murning** [jkitchin/org-ref#742]
When I click on a citation to open the popup menu, the menu height is too small. I can only see options 0 and 1. I'd like to increase the height of the popup menu. 

Is this possible? If so how? I'm new to elisp and still learning, I've spent some time looking for the correct variable to modify but I can't seem to come right. 

Thank you for this amazing package!

**Comment by jkitchin** [comment]
I guess you are using helm. 

According to https://github.com/emacs-helm/helm/wiki/helm-autoresize this may do the trick for you: `(helm-autoresize-mode 1)` 

There are some variables for that mode that you can adjust I think.

**Comment by murning** [comment]
I am using helm! Thanks for the help. I'm using doom emacs and I've resolved the issue by setting 

```
(after! helm
  (set-popup-rule! "^\\*helm" :size 0.5)) 
```
I've realised this has nothing to do with org-ref, so I'm closing this issue.
