### ISSUE TITLE
doi-add-bibtex-entry fails

### ISSUE THREAD

**Issue by LarryLegend33** [jkitchin/org-ref#744]
Any call that results in doi-add-bibtex-entry getting called seems to fail for me. The website of the doi I enter is visited in my browser, but the following error is thrown:

doi-utils-get-json-metadata: Something went wrong.  We got this response:

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

This happens using any possible import method described in the youtube video (i.e. pdf import, url import). I'm on emacs 26.1, osx 10.14.6. 

using debug, get the following error message:

Debugger entered--Lisp error: (error "Something went wrong.  We got this response:\n\n<html>\015\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\015\n<body>\015\n<center><h1>400 Bad Request</h1></center>\015\n<center>The plain HTTP request was sent to HTTPS port</center>\015\n<hr><center>cloudflare</center>\015\n</body>\015\n</html>\015\n\n\nOpening https://doi.org/10.1016/j.tics.2016.10.003 ")
  signal(error ("Something went wrong.  We got this response:\n\n<html>\015\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\015\n<body>\015\n<center><h1>400 Bad Request</h1></center>\015\n<center>The plain HTTP request was sent to HTTPS port</center>\015\n<hr><center>cloudflare</center>\015\n</body>\015\n</html>\015\n\n\nOpening https://doi.org/10.1016/j.tics.2016.10.003 "))
  error("Something went wrong.  We got this response:\n%s\n\nOpening %s" "\n<html>\015\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\015\n<body>\015\n<center><h1>400 Bad Request</h1></center>\015\n<center>The plain HTTP request was sent to HTTPS port</center>\015\n<hr><center>cloudflare</center>\015\n</body>\015\n</html>\015\n" "https://doi.org/10.1016/j.tics.2016.10.003 ")
  doi-utils-get-json-metadata("10.1016/j.tics.2016.10.003 ")
  doi-utils-doi-to-bibtex-string("10.1016/j.tics.2016.10.003 ")
  doi-utils-insert-bibtex-entry-from-doi("10.1016/j.tics.2016.10.003 ")
  doi-add-bibtex-entry("10.1016/j.tics.2016.10.003 ")
  funcall-interactively(doi-add-bibtex-entry "10.1016/j.tics.2016.10.003 ")
  call-interactively(doi-add-bibtex-entry record nil)
  command-execute(doi-add-bibtex-entry record)
  execute-extended-command(nil "doi-add-bibtex-entry" "doi-ad")
  funcall-interactively(execute-extended-command nil "doi-add-bibtex-entry" "doi-ad")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by LarryLegend33** [comment]
I did a little more digging on this and found that the default behavior of the doi-utils-get-json-metadata function takes into account that the metadata aquisition might fail. But even though the browser does open the correct site for any given DOI I add, the metadata still isn't found, and it is also never found if I drag that article as a PDF into the bib file. Lastly, if I directly use helm-bibtex to try to add to the bibtex file, the same thing occurs. No matter what article I choose to import a bibtex from, there is a failure to import the bibtex.

**Comment by jkitchin** [comment]
This is probably some internet service/server issue. There is nothing we can do on the org-ref side about it.

**Comment by LarryLegend33** [comment]
OK thanks for looking into this! Other than that my org-ref use has been awesome.
