### ISSUE TITLE
Suggestion: Remove helm and ivy dependencies on MELPA

### ISSUE THREAD

**Issue by Vonfry** [jkitchin/org-ref#745]
Normally, A person may only use one or none of them. But package manage will download both of them if putting both of them as dependencies on melpa. I think this should be installed by user manually.

**Comment by Vonfry** [comment]
All right, I find `org-ref` is implemented by helm.

**Comment by ethancedwards8** [comment]
I'd be interested in getting these removed as hard deps. I certainly don't like this package pulling down helm when I'm an ido user. It's the only thing stopping me from using it sadly.
