### ISSUE TITLE
Wrong type argument: stringp, nil, Human Nutrition ()

### ISSUE THREAD

**Issue by xianwenchen** [jkitchin/org-ref#746]
I try to create a new note by clicking on the reference, and got the following error:
```
Wrong type argument: stringp, nil
, Human Nutrition ()
```

Here is the org-roam file:

```
#+TITLE: MVI291 Diet and Health

- Textbook: cite:GeisslerPowers-2017--HumanNutrition
```

Here is the bibtex file, which is automatically generated by Zotero:
```
@collection{GeisslerPowers-2017--HumanNutrition,
  title = {Human {{Nutrition}}},
  editor = {Geissler, Catherine and Powers, Hilary},
  date = {2017-04-27},
  edition = {Thirteenth Edition},
  publisher = {{Oxford University Press}},
  location = {{Oxford, New York}},
  abstract = {The field of human nutrition has expanded hugely in recent years, to now encompass topics as diverse as nutritional genomics and food security. As appreciation for the importance of nutrition to human health and well-being grows, an understanding of the many aspects of the subject has never been more important. Written by a renowned team of international experts,  Human Nutrition  provides an authoritative, comprehensive resource for students of human nutrition and other health sciences, and a valuable source of information for everybody working in nutrition and related fields. The text opens with an exploration of the chemical characteristics of foods and nutrients, before moving on to discuss the physiology of food nutrition, micronutrients, and dietary requirements for different sections of the population. The text concludes with an assessment of the evidence base for a link between nutrient intake and disease risk, and a review of the broad discipline of public health nutrition.Online Resource Centre:The Online Resource Centre to accompany  Human Nutrition  features:Student Resources: Auto-marked multiple choice questions to accompany each chapterCurated links to online sources of further information'In depth' panels: extended coverage of topics included in the bookLecturer Resources: Figures from the book: available to download for use in lectures},
  file = {C\:\\Users\\c\\Zotero\\storage\\R2I7SMWP\\human-nutrition-9780198768029.html},
  isbn = {978-0-19-876802-9},
  pagetotal = {784}
}
```

**Comment by 9309** [comment]
I have the same issue, with `org-ref-notes-function-one-file`. 
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  bibtex-parse-entry()
  (progn (insert (org-ref-get-bibtex-entry key)) (bibtex-mode) (bibtex-beginning-of-entry) (bibtex-parse-entry))
  (unwind-protect (progn (insert (org-ref-get-bibtex-entry key)) (bibtex-mode) (bibtex-beginning-of-entry) (bibtex-parse-entry)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert (org-ref-get-bibtex-entry key)) (bibtex-mode) (bibtex-beginning-of-entry) (bibtex-parse-entry)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert (org-ref-get-bibtex-entry key)) (bibtex-mode) (bibtex-beginning-of-entry) (bibtex-parse-entry)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
  (let ((entry (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert ...) (bibtex-mode) (bibtex-beginning-of-entry) (bibtex-parse-entry)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))) (save-restriction (if org-ref-bibliography-notes (find-file-other-window org-ref-bibliography-notes) (error "org-ref-bibliography-notes is not set to anything")) (widen) (goto-char (point-min)) (let* ((headlines (org-element-map (org-ref-parse-buffer) 'headline 'identity)) (keys (mapcar #'(lambda ... ...) headlines))) (if (-contains\? keys key) (progn (org-open-link-from-string (format "[[#%s]]" key)) (funcall org-ref-open-notes-function)) (goto-char (point-max)) (insert (org-ref-reftex-format-citation entry (concat "\n" org-ref-note-title-format))) (save-buffer)))))
  org-ref-notes-function-one-file("2020-progr-algor")

``` 
This is fixed after I run `(bibtex-set-dialect)`. Maybe that will work for you.

**Comment by mirkov** [comment]
I also get this error when I call `org-ref-create-bibtex-note` from a bibtex entry. Running `bibtex-set-dialect` had no effect.

After setting `debug-on-error` to `t`, the trace shows the call sequence to the following three functions:

1.  `org-ref-open-bibtex-notes`
2.  `org-ref-notes-function-one-file`
3.  `org-ref-get-bibtex-entry`

Inside the last one the code calls `org-ref-find-bibliography` which returns `nil`. I think that is the `nil` the error message refers to. `org-ref-find-bibliography` tests the current buffer for pointers to bibliography files. If it does not find any, it uses the value of `org-ref-default-bibliography`.

I have set that variable as a file-local variable to "test.bib", but that definition does not make it to this function. Inside that function, `current-buffer` is a temporary one: `#<buffer *temp*>`. I was expecting it to be the .bib buffer.

I am using org-ref from Spacemacs' development branch and the BiBTeX layer. This error showed up sometimes between March and June (dates when I updated Spacemacs and packages).

**Comment by jkitchin** [comment]
`org-ref-default-bibliography` should be a list, so something like '("test.bib") would be correct for that value. I have not tested this with file-local variables. I think it should probably work, but why not use a bibliography link instead? That is also file-local.

**Comment by mirkov** [comment]
Here is a minimal example. I attached a short bib file (you will need to strip the txt extension). 
[test.bib.txt](https://github.com/jkitchin/org-ref/files/5036966/test.bib.txt)

The first line defines the target file for notes. I use a separate note-taking file for each bib file.

Issuing `org-ref-open-bibtex-notes` on the entry returns the error. Setting org-ref-default-bibliography

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  insert-file-contents(nil)
  org-ref-get-bibtex-entry("zhang00PhD")
  org-ref-notes-function-one-file("zhang00PhD")
  org-ref-open-bibtex-notes()
  funcall-interactively(org-ref-open-bibtex-notes)
  call-interactively(org-ref-open-bibtex-notes nil nil)
  command-execute(org-ref-open-bibtex-notes)
```

Thank you.

**Comment by jkitchin** [comment]
I see, I am not sure this can work. It looks like the problem may be in `org-ref-get-bibtex-entry("zhang00PhD")` where it is not finding an entry with that key. That may be because in the note file, the bibtex file is not part of `org-ref-default-bibliography. I guess you do not get this error in the attached file though, and if you doo it means something else is wrong. In the file you sent me there is no entry with a key of "zhang00PhD".

**Comment by mirkov** [comment]
First, apology for posting the previous message with inconsistent contents.
Second, I resolved my issue by advising `org-ref-open-bibtex-notes` to add current bibliography file to `org-ref-default-bibliography`.

Here is the story:

I use multiple .bib files, each with it's own `org-ref-bibliography-notes` file. This file is specified in the first line of a bib file liko so
```
% -*- org-ref-bibliography-notes: "~/Documents/the-works/bibliographies/test-reference-notes2.org" -*-
```
In the past, _I did _not__ include the .bib file in `org-ref-default-bibliography` list. It was set to `nil`.

And my setup still worked: I would go to an entry in the bib file, open the note, and end up in the corresponding org file. The only thing I need to make sure is for the org file to include a `bibliography:...` link to the bib file. Typically, I would have a section in the org file
```
* Bibliography
   - bibliography:~/path-to-bib-file
```

This worked until I recently updated spacemacs, and all packages: `org-ref-open-bibtex-notes` would end up with the `stringp, nil` error. After some trial and error, I narrowed down the cause that `org-ref-default-bibliography` contained, or did not contain the path to the bib file.

To continue using my setup, I now added _advice_ to `org-ref-open-bibtex-notes` that addes the filepath to `org-ref-defeault-bibliography`. This is now my setup:

```
(defun mv/org-ref-update-org-ref-default-bibliography (&rest args)
  "Push the buffer's file name to `org-ref-default-bibliography'
if it is not already there."
  (pushnew (buffer-file-name (current-buffer)) org-ref-default-bibliography))

(advice-add 'org-ref-open-bibtex-notes :before #'mv/org-ref-update-org-ref-default-bibliography)
```

**Comment by jkitchin** [comment]
I think I have partially fixed this in the commit above. you still have to manually put the bib file in the notes file. that has to be fixed elsewhere, e.g you could add a hook function to org-ref-create-notes-hook that might automate setting that for you.
