### ISSUE TITLE
export bibtex reference to Endnote format?

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#747]
Is there any way to export the references in a manuscript to Endnote format?

**Comment by jkitchin** [comment]
I am not sure what Endnote format is. If you mean can we make word document with Endnote (the proprietary reference manager), the answer is no, I don't know how one could do that.

**Comment by cryoguy** [comment]
There are a couple of ways of conversion. I put them together in a [blog post](http://tech.memoryimprintstudio.com/conversion-of-reference-database/).

**Comment by jkitchin** [comment]
I did not understand this is what you wanted. check out org-ref/x2bib.el (https://github.com/jkitchin/org-ref/blob/master/x2bib.el). 

What I don't know how to do is export org to MS Word format, with Endnote style citations.
