### ISSUE TITLE
org-ref alters my default helm-bibtex action

### ISSUE THREAD

**Issue by WorldsEndless** [jkitchin/org-ref#748]
Default was, and should be, to open the PDF of the entry under point when I call helm-bibtex. However, org-ref seems to change this to inserting the citation at point -- which is never what I want. I looked for options to change the default back again but, not finding them, could only solve this by uninstalling org-ref.

**Comment by jkitchin** [comment]
That is certainly your prerogative.  If you want to keep the defaults, I think you can do this:
```
(setq org-ref-bibtex-completion-actions '())
```
Put that somewhere before you load org-ref in your init file.

**Comment by WorldsEndless** [comment]
Thanks. I've made this my invocation, and it seems to be working:

--8<---------------cut here---------------start------------->8---
    (use-package org-ref :ensure t
      :custom (org-ref-bibtex-completion-actions nil))
--8<---------------cut here---------------end--------------->8---

**Comment by jkitchin** [comment]
Glad to hear it.
