### ISSUE TITLE
lists of of .bib files and pdf directories, use bibfile metadata?

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#749]
I have two .bib files, each of which have their own pdf directories.  It would be useful if org-ref could find entries and pdfs in all of these.

**Use Case**
When I have a big collection of new pdfs to winnow, I like to put them in a totally separate staging pdf directory, with its own .bib file.  I flip through them, and then transfer the promising ones to my permanent .bib file and permanent .pdf directory.  While doing this, it's nice to be able also look at my permanent collection, and compare with papers I have already read.

**Current situation**
Both `org-ref-default-bibliography` and  `org-ref-pdf-directory`  can accept lists, but org-ref uses only at the first elements in them.

This is different than helm-bibtex, which will look in multiple .bib files and .pdf directories when its bibtex-`completion-bibliography` and `bibtex-completion-library-path` contain lists.

helm-bibtex also can also detect the pdf directory associated with a .bib file by looking at JabRef/Zotero style metadata (if you do `(setq bibtex-completion-pdf-field "File")`)

**Comment by jkitchin** [comment]
> I have two .bib files, each of which have their own pdf directories. It would be useful if org-ref could find entries and pdfs in all of these.
> 
> **Use Case**
> When I have a big collection of new pdfs to winnow, I like to put them in a totally separate staging pdf directory, with its own .bib file. I flip through them, and then transfer the promising ones to my permanent .bib file and permanent .pdf directory. While doing this, it's nice to be able also look at my permanent collection, and compare with papers I have already read.
> 
> **Current situation**
> Both `org-ref-default-bibliography` and `org-ref-pdf-directory` can accept lists, but org-ref uses only at the first elements in them.

I am not sure what you mean here. org-ref should list all the references from all the files in `org-ref-default-bibliography`, even duplicates. 

getting pdf filenames for an entry is admittedly a little messy in org-ref. There are a bunch of ways that it tries to support, and customization is done through the variable `org-ref-get-pdf-filename-function`. Perhaps you can create a function that works for you and use this variable to get what you want?

> 
> This is different than helm-bibtex, which will look in multiple .bib files and .pdf directories when its bibtex-`completion-bibliography` and `bibtex-completion-library-path` contain lists.
> 
> helm-bibtex also can also detect the pdf directory associated with a .bib file by looking at JabRef/Zotero style metadata (if you do `(setq bibtex-completion-pdf-field "File")`)
