### ISSUE TITLE
Generate the figure list without containing the figures in the comment headline

### ISSUE THREAD

**Issue by llcc** [jkitchin/org-ref#75]
I think it's more useful to skip the figure file links when using the `org-ref-list-of-figures` to navigate figures. How do you think? I wanted to implement it by my self, but i found that it's not easy to deal with the comment conditions of headlines as followed:

```
* COMMENT headline 1
** COMMENT subheadline 1
*** COMMENT subheadline 2
    [[file:image.png]]
* headline 2
   [[file:image.png]]
** COMMENT subheadline 1
    [[file:image.png]]
* headline 3
   [[file:image.png]]
```

Do you have any idea about this?

**Comment by jkitchin** [comment]
I pushed two changes that ignore figures and tables in commented sections for that function and the tables function. Does that work for you?
