### ISSUE TITLE
Cannot generate any notes (stringp, nil)

### ISSUE THREAD

**Issue by MichaelDavidJohnson** [jkitchin/org-ref#752]
Hello all. I'm running org-ref through the bibtex layer in spacemacs. Adding to a bib file has proven to be fine. However, the problem comes with trying to generate a notes field for the bibliography entries. I have set up the file locations by the following;
` (setq org-ref-default-bibliography '("~/Documents/Resources/master.bib")
      org-ref-pdf-directory "~/Documents/Resources/"
      org-ref-bibliography-notes "~/Documents/Resources/masterNotes.org") `

Now, if I go to any bibtex entry in my bib file and try to create a note for masterNotes.org by passing open note I end up with a stringp, nill error.

How do I make it so it generates the note file for me?

**Comment by jellelicht** [comment]
@MichaelDavidJohnson does evaluating the following mitigate your issue?
```
      (defun org-ref-notes-function-one-file (key)
        "Function to open note belonging to KEY.
     Set `org-ref-notes-function' to this function if you use one
    long file with headlines for each entry."
        ;; save key to clipboard to make saving pdf later easier by pasting.
        (with-temp-buffer
          (insert key)
          (kill-ring-save (point-min) (point-max)))
        (let* ((pre-entry (org-ref-get-bibtex-entry key))
               (entry (with-temp-buffer
                        (insert pre-entry)
                        (bibtex-mode)
                        (bibtex-beginning-of-entry)
                        (bibtex-parse-entry)) ))

          (save-restriction
            (if  org-ref-bibliography-notes
                (find-file-other-window org-ref-bibliography-notes)
              (error "org-ref-bibliography-notes is not set to anything"))
            (widen)
            (goto-char (point-min))
            (let* ((headlines (org-element-map
                                  (org-ref-parse-buffer)
                                  'headline 'identity))
                   (keys (mapcar
                          (lambda (hl) (org-element-property :CUSTOM_ID hl))
                          headlines)))
              (if (-contains? keys key)
                  ;; we have it so we go to it.
                  (progn
                    (org-open-link-from-string (format "[[#%s]]" key))
                    (funcall org-ref-open-notes-function))
                ;; no entry found, so add one
                (goto-char (point-max))
                (insert (org-ref-reftex-format-citation
                         entry (concat "\n" org-ref-note-title-format)))
                (save-buffer))))))
```

I added the pre-entry `let*` binding, as for me the call to `org-ref-get-bibtex-entry` would not working wrapped in the `with-temp-buffer`.

**Comment by MichaelDavidJohnson** [comment]
Interesting, I've put this in my init.el and yet I can't access this through M-x... 
I'm definitely doing something wrong here

**Comment by jkitchin** [comment]
That function isn't an interactive function, so you won't be able to use M-x on it. You need to also have `(setq org-ref-notes-function 'org-ref-notes-function-one-file)` in the init file so that this is the function that org-ref will use.

**Comment by MichaelDavidJohnson** [comment]
ah yes, now when i run `org-ref-open-bibtex-notes` I can populate the notes file with that one field. It's a shame that the whole buffer doesn't generate as it's own function. But mashing `, n` a couple hundred times is better than me populating it all myself. Thank you very much!
