### ISSUE TITLE
org-ref-pdf-crossref-lookup references external macro

### ISSUE THREAD

**Issue by jellelicht** [jkitchin/org-ref#755]
In org-ref-pdf.el, there is a reference to the following macro:
https://github.com/jkitchin/org-ref/blob/4f26ac56db785b4bff05e75ae7decc44be2ba89e/org-ref-pdf.el#L275

If pdf-view has not been required when byte-compiling this file, the emacs byte compiler treats it as a function instead, leading to:
```
org-ref-pdf-crossref-lookup: Invalid function: pdf-view-assert-active-region
```

**Comment by jkitchin** [comment]
Do you know if the solution to this is to add `(declare-function pdf-view-assert-active-region "pdf-view.el")` to org-ref-pdf.el? I have pushed this. I am not sure it will work since that is a macro and not a function.

**Comment by jellelicht** [comment]
I'm afraid not, but it used to work for sure because you `require`'d pdf-tools before. I am not able to reproduce the issue if I change the commented-out `require` to the following:
```
;; [2019-10-13 Sun] I am commenting this out for now. I added it for some
;; reason, but I cannot figure out why. It is pretty slow to load, so since I
;; don't know why it is here, I am commenting it out until it is obvious again.
(eval-when-compile
  (require 'pdf-tools))
```

**Comment by jkitchin** [comment]
I think you would need `(require 'pdf-view)` instead.

**Comment by jellelicht** [comment]
That is of course what I meant, oops!
Either `(require 'pdf-view)` or `(eval-when-compile (require 'pdf-view))` work though.
