### ISSUE TITLE
Undefined citations when I chage bibstyle

### ISSUE THREAD

**Issue by gpetrini** [jkitchin/org-ref#758]
I am a really new user of emacs and org-ref. My setup is: spacemacs + pop!os 20.04

Here is my init file config:

`(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %b"
        "bibtex %b"
        "makeindex %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %b"))
`

It runs just fine when I use `bibliographystyle:unsrt`. However, when I change to apa, author-year, unsrt-footnote and others, It gives the undefined citations message.

The exported .tex file runs normaly on texstudio. I tried to change `bibtex %b` by both  `biber %b` and `biber` but it remains with undefined citations problems. I also added `natbib`package and had the same errors.

Thanks a lot

**Comment by jkitchin** [comment]
That probably means the error is in LaTeX. Maybe you don't have those styles installed, or they are not on the LaTeX paths. What happens when you manually run those commands in a shell?

**Comment by gpetrini** [comment]
Thank you a lot for your quick answer

Running the following command in a shell
`pdflatex Housing.tex --shell-escape -interaction nonstopmode -output-directory %o %b`

I get the following error message:

`! Package biblatex Error: File 'Housing.bbl' not created by biblatex.`

**Comment by jkitchin** [comment]
I don't think that command should work. You should try something like `latexmk -shell-escape -pdf -bibtex -f Housing.tex`

**Comment by gpetrini** [comment]
I just run `latexmk -shell-escape -pdf -bibtex -f Housing.tex` and got the same error message:

`! Package biblatex Error: File 'Housing.bbl' not created by biblatex`

But when I run again, 

`Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: All targets (Housing.pdf) are up-to-date`

**Comment by jkitchin** [comment]
can you post all the output?

**Comment by gpetrini** [comment]
When I run `pdflatex Housing.tex --shell-escape -interaction nonstopmode -output-directory %o %b`, the output is:

`pdflatex Housing.tex --shell-escape -interaction nonstopmode -output-directory %o %b
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./Housing.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-05-15>
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/size11.clo))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/inputenc.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/fontenc.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics/trig.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/grffile/grffile.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/tools/longtable.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/graphics/rotating.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/ifthen.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/ulem/ulem.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsmath/amstext.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/textcomp.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/capt-of/capt-of.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/hyperref/hyperref.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/iftex/iftex.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/url/url.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/bitset/bitset.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/atbegshi/atbegshi.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/hyperref/hpdftex.def
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/atveryend/atveryend.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty

(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty
))) (/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/fontenc.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/float/float.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/iftex/ifvtex.sty))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/biblatex.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/logreq/logreq.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/logreq/logreq.def))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/blx-dm.def)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/blx-compat.def)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/biblatex.def)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/blx-natbib.def)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/abnt.bbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/l3kernel/expl3.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def))

(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.
tex)) (/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/xpatch/xpatch.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/bbx/standard.bbx))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/abnt.cbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/cbx/authoryear-comp.cbx)
) (/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/biblatex.cfg))

LaTeX Warning: Unused global option(s):
    [times].

(./Housing.aux)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/hyperref/nameref.sty
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/refcount/refcount.sty)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/generic/gettitlestring/gettitlestring.s
ty)) (./Housing.out) (./Housing.out)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazil-abnt.lbx

Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found!
(biblatex)                Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-
abnt'.

(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazilian-abnt.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazilian-abnt.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx)))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazilian-abnt.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazilian-abnt.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazil.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx)))
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazil.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex-abnt/brazilian-abnt.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazil.lbx
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/biblatex/lbx/brazilian.lbx))))))

! Package biblatex Error: File 'Housing.bbl' not created by biblatex.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.36 \begin{document}
                     ^^M
? 
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/amsfonts/umsb.fd) (./Housing.toc
(/home/gpetrini/.TinyTeX/texmf-dist/tex/latex/base/t1cmss.fd))

LaTeX Warning: Citation 'kajuthgerman2020' on page 1 undefined on input line 46
.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\cite' on input line 46.


LaTeX Warning: Citation 'dipasquale_housing_1994' on page 1 undefined on input 
line 51.


LaTeX Warning: Citation 'davis_price_2007' on page 1 undefined on input line 52
.

[1{/home/gpetrini/.TinyTeX/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]

LaTeX Warning: Citation 'Ozdemir2020' on page 2 undefined on input line 61.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\textcite' on input line 61.

[2] (./Housing.aux)

LaTeX Warning: There were undefined references.


Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                Housing
(biblatex)                and rerun LaTeX afterwards.

 ) </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/tcrm1095.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecsx1200.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecbx1200.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecsx1095.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecrm1095.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecbx1095.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecbx1440.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecrm1200.600p
k> </home/gpetrini/.TinyTeX/texmf-var/fonts/pk/ljfour/jknappen/ec/ecrm1728.600p
k></home/gpetrini/.TinyTeX/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on Housing.pdf (2 pages, 69177 bytes).
Transcript written on Housing.log.`
(Sorry for the messy format)

And when I run `latexmk -shell-escape -pdf -bibtex -f Housing.tex`, the output is:

`Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
Latexmk: All targets (Housing.pdf) are up-to-date`

I got the same message whatever command I run first.

**Comment by jkitchin** [comment]
maybe you don't have the right setup in the org file for biblatex. See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#biblatex-users.

**Comment by gpetrini** [comment]
I've already tried your suggestion. Here is my org file preambule:

`#+LATEX_CLASS_OPTIONS: [times,11pt]
#+LATEX_HEADER: \usepackage[style=abnt, backend=biber, natbib=true]{biblatex}
#+LATEX_HEADER: \addbibresource{Housing.bib}
#+LATEX_HEADR: \usepackage[english]{babel}`

I also set the following configuration globally as recommended:

`(setq bibtex-dialect 'biblatex)`

I've also tried other biblatex-styles like apa, authoryear-icomp, and mla. The problem persists.

**Comment by jkitchin** [comment]
Can you copy a small and complete org-file and bib file (one entry is probably sufficient) that doesn't work for you?

**Comment by gpetrini** [comment]
Sorry for the late response. Here is my org-file:

```
#+PROPERTY: :tangle "Housing.bib" 
#+LATEX_CLASS_OPTIONS: [times,11pt]
#+SETUPFILE: Readings.setup
#+LATEX_HEADER: \usepackage[style=abnt, backend=biber, natbib=true]{biblatex}
#+LATEX_HEADER: \addbibresource{Housing.bib}
#+TITLE: Housing Writings
#+AUTHOR: Gabriel Petrini



* Empirical
** \cite{kajuthgerman2020}: The German housing market cycle: Answers to FAQs

#+BEGIN_SRC bib :tangle yes  :exports none
@techreport{kajuthgerman2020,
	title = {The {German} housing market cycle: {Answers} to {FAQs}},
	abstract = {This paper analyses the behaviour of prices and supply on the German housing market taking into account the interaction between prices and quantities. A novel price index for residential property prices covering the whole country going back to 1993 is used in a macroeconomic model to estimate key housing market elasticities for Germany. A decomposition suggests that the land price component of house prices is relatively elastic with respect to income and interest rates, while the construction price component responds to income and the level of construction activity. The decomposition also highlights countervailing house price effects of a supply increase: A dampening effect via land prices and a stimulating effect via construction prices.},
	language = {en},
	number = {20},
	institution = {Deutsche Bundesbank},
	author = {Kajuth, Florian},
	year = {2020},
	pages = {33},
	series = {Deutsche Bundesbank Discussion paper},
	file = {Kajuth - The German housing market cycle Answers to FAQs.pdf:/home/gpetrini/Zotero/storage/T3V6XEJJ/Kajuth - The German housing market cycle Answers to FAQs.pdf:application/pdf}
}
#+END_SRC

- *Background:* German housing market dynamics has been poorly evaluated due to the lack of a long series for aggregate house prices

* References
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  #+LaTeX: \printbibliography[heading=none]
```

**Comment by jkitchin** [comment]
There may be an incompatibility of latex packages, natbib in particular. I think this worked for me which has the default values for the packages. you may have to modify the definition. They are defined in scimax-org-latex.el. I would just copy the code there into your user.el file, and delete this line: `("numbers,super,sort&compress" "natbib" nil)`. I think that might solve it.

```
(let ((org-latex-default-packages-alist '(("AUTO" "inputenc" t ("pdflatex"))
      					  ("T1" "fontenc" t ("pdflatex"))
      					  ("" "graphicx" t)
      					  ("" "grffile" t)
      					  ("" "longtable" nil)
      					  ("" "wrapfig" nil)
      					  ("" "rotating" nil)
      					  ("normalem" "ulem" t)
      					  ("" "amsmath" t)
      					  ("" "textcomp" t)
      					  ("" "amssymb" t)
      					  ("" "capt-of" nil)
      					  ("" "hyperref" nil)))
      (org-latex-pdf-process   '("latexmk -shell-escape -bibtex -pdf %f")))
  (org-open-file (org-latex-export-to-pdf)))
```

**Comment by gpetrini** [comment]
It still doesn't work "/
```
! Package biblatex Error: File 'Housing.bbl' not created by biblatex.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.29 \begin{document}
                     ^^M
? 
! Emergency stop.
 ...                                              
                                                  
l.29 \begin{document}
                     ^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Housing.log.
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Housing.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets

```

I tried to run on scimax deleting the line that you mentioned and the pdf is not produced I got an empty Latex output buffer.

**Comment by jagrg** [comment]
You're missing header-args. It should be: `#+PROPERTY: header-args
:tangle "Housing.bib"`. I think you also have to remove `:tangle yes`
from the block. Then C-c C-v t to create Housing.bib.

**Comment by gpetrini** [comment]
For some reason, I had to delete `natmove` and `minted` from scimax-org-latex.el in order to .tex run on texstudio. Still, I cannot generate the pdf from scimax and still got empty LaTeX output buffer. I am not sure if it changes something, but I'm using flatpak emacs instead of .deb version.
