### ISSUE TITLE
org-ref-get-pdf-filename-function from bibtex not working when sending pdf as email attachment

### ISSUE THREAD

**Issue by npalermo10** [jkitchin/org-ref#760]
setting org-ref-get-pdf-filename-helm to org-ref-get-pdf-filename-helm works for opening PDFs, but doesn't work when trying to send those PDF's as email attachments. 

To add some context: My pdf's are all over the place thanks to Zotero's default organization scheme. All the pdf locations are in each bibtex entry. I need to reference the bibtex entry to open each pdf (this works well) but also to attach the pdf to emails.

Thanks for all the great work! org-ref has been awesome for my work.

**Comment by npalermo10** [comment]
I think this fixes it: 

(defun org-ref-email-bibtex-entry ()
  "Email current bibtex entry at point and pdf if it exists."
  (interactive)

  (save-excursion
    (bibtex-beginning-of-entry)
    (let* ((key (reftex-get-bib-field "=key=" (bibtex-parse-entry t)))
	   pdf)
      ;; when we have org-ref defined we may have pdf to find.
      (when (boundp 'org-ref-pdf-directory)
	(setq pdf (funcall org-ref-get-pdf-filename-function key)))
	;; (setq pdf (expand-file-name 
		   ;; (concat key ".pdf")
		   ;; org-ref-pdf-directory))

	      
      (bibtex-copy-entry-as-kill)
      (compose-mail)
      (message-goto-body)
      (insert (pop bibtex-entry-kill-ring))
      (message-goto-subject)
      (insert key)
      (message "%s exists %s" pdf (file-exists-p pdf))
      (when (file-exists-p pdf)
	(mml-attach-file pdf))
      (message-goto-to))))

**Comment by jkitchin** [comment]
Thanks. I have pushed your suggestion. Feel free to reopen this if it doesn't do what you need.
