### ISSUE TITLE
Mediawiki Support

### ISSUE THREAD

**Issue by pooltoymae** [jkitchin/org-ref#764]
Howdy! I'm trying to use org-ref to write wiki pages for a mediawiki site. I could just copy and paste the html that org-ref can generate, but that doesn't seem to harness the mediawiki cite package. Is there a way to do this already? If not, I'd like to add it as a feature request.

**Comment by jkitchin** [comment]
Probably the best path is to generate a custom exporter, and then add a backend for the org-ref export for the links. That isn't really easy to do generally but if you only need to modify a few cite link types  it wouldn't be too hard.

the export functions are defined by a macro at https://github.com/jkitchin/org-ref/blob/master/org-ref-core.el#L2250
