### ISSUE TITLE
remove doi during export

### ISSUE THREAD

**Issue by cryoguy** [jkitchin/org-ref#765]
Is there a way to remove doi entry during export?

**Comment by jkitchin** [comment]
I don't understand what this means.

**Comment by cryoguy** [comment]
sorry, I mean the doi item in bibliography.

`Saccon, R.A., Bunton-Stasyshyn, R.K.A., Fisher, E.M.C., Fratta, P., 2013. Is
SOD1 loss of function involved in amyotrophic lateral sclerosis? Brain 136,
2342–2358. doi:10.1093/brain/awt097.`

**Comment by jkitchin** [comment]
Pick a different bibliography style. I think unsrtnat puts the doi in, but maybe unsrt does not. In either case this is controlled by the bibliography style.
