### ISSUE TITLE
org-ref-helm-insert-cite-link opens PDF rather than inserting citation

### ISSUE THREAD

**Issue by goyala9079** [jkitchin/org-ref#766]
Org-ref is working perfectly except for when I press C-c ] to add a citation, I am unable to add the citation because the behavior of ENTER within the helm buffer is to try to open the PDF rather than to insert the citation. C-j tries to do the same thing. I used to be able to press '1' to insert the citation from the Helm buffer, but as of today I cannot do that anymore. So now I have to manually type cite:<citekey> within my manuscript. When I do this, the links become clickable and I get the full range of numerical options. C-c ] just doesn't give me those options. 

Interestingly, when I run org-ref and click "insert citation," my citations do not even appear. Instead only the fallback options appear. I'm not sure why "insert citation" would have different behavior from C-c ]

I installed from Melpa and my configuration is literally just (require org-ref') so I'm unsure about sources of this issue. All of the above issues persist when I use Emacs -Q and run then org-ref. 

Any advice would be appreciated. 

Thanks!

**Comment by jkitchin** [comment]
I am not sure why this would happen. org-ref should be rearranging the actions for helm-bibtex. Maybe this could happen if you load helm-bibtex after you load org-ref.

it is stranger though that it used to work, and now doesn't. did something get updated?
