### ISSUE TITLE
org-ref-format-cite wrong-type-argument on markdown export

### ISSUE THREAD

**Issue by myshevchuk** [jkitchin/org-ref#769]
Hi! Org-ref is an indispensable package for scientific writing in Emacs. Thank you very much for your efforts!

#### Description
I've run into `org-ref-format-cite` throwing `wrong-type-argument stringp nil` on markdown export when the BibTeX key is not found in the database [^1] :

```elisp
(org-ref-format-cite "2019-JACS-3153" nil 'md)
```
> 2019-JACS-3153 not found in /path/to/my/references/literature.bib
progn: Wrong type argument: stringp, nil

The source of the error is on lines 2315–2323 of `org-ref-core.el`:

```elisp
  (setq file (catch 'result
	   (cl-loop for file in org-ref-bibliography-files do
	    (if (org-ref-key-in-file-p key (file-truename file))
		(throw 'result file)
		      (message "%s not found in %s"
       key (file-truename file))))))

   (with-temp-buffer
	(insert-file-contents file)
...)
```
If `key` is not found, the value of `file` is nil. Nevertheless, an attempt is made to insert the contents of `file`.

#### Proposed solution
Wrap everything that follows `(setq file ...` in an `if` statement, which would just return some string if `file` is nil.
```elisp
(if file
   (progn 
       (with-temp-buffer ...)
       (replace-regexp-in-string...))
 "Key not found")
```

This obviously affects other format functions generated with `org-ref-make-format-function` macro.

[^1]: when using `ox-hugo` for example

**Comment by jkitchin** [comment]
hm. I feel like an error is appropriate though, as it clearly indicates a problem. you wouldn't want, for example, to get no error and then have "Key not found" in a blog post or message to some one right?  This indicates you aren't using the right bib file(s) I think.

Or am I missing your point?

**Comment by myshevchuk** [comment]
Well, that definitely makes sense on the one hand, but on the other hand, the export process is ungracefully interrupted. It would be great, if it were possible to at least issue a user warning or error, so that the export process does run to the end. Org mode standard export facilities have an option to allow broken links. Maybe `org-ref` could have something similar?

For my personal use case, which perhaps is not very typical, I would prefer broken links. In fact, the files I want to export contain >50% broken links. These files are bibliography notes (for personal use, not for a blog post), which are semi-automatically populated with references from the articles' references sections in the form of `cite:key` cite links.  So if an article contains say 30 references, my bib file would have only a small fraction of them, the rest would be dead links. 

Also, for my personal use, I can easily disable or rewrite this particular piece, so please do not hesitate to close this issue if it's not worth addressing for general usage.

**Comment by jkitchin** [comment]
I think I have added a simple fix for this issue. Let me know if it solves your use case.

**Comment by myshevchuk** [comment]
Yes, the fix resolves the issue. The md exporter handles broken links gracefully,  exactly the way to support my use case.  Thank you very much!
