### ISSUE TITLE
"File was not in list (not removed)" when running `Ctrl c-]`

### ISSUE THREAD

**Issue by GaurangTandon** [jkitchin/org-ref#770]
I have a minimal `/home/gt/.emacs` configuration:

```
(require 'package) ;; You might already have this line
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize) ;; You might already have this line
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (helm-bibtexkey org-ref evil boogie-friends))))

;; unrelated stuff

(setq reftex-default-bibliography '("/home/gt/library.bib"))

;; see org-ref for use of these variables
(setq org-ref-default-bibliography '("/home/gt/library.bib"))

(setq bibtex-completion-bibliography
      '("/home/gt/library.bib"))
```

I open my org file in which I have already written `"bibliography:/home/gt/library.bib` at the end of the file. I press `C-c ]` somewhere in the document, and I get the message: `"File was not in list: <full-file-path> (not removed)"`. Expected result according to the README of this project is some helpful message that lets me insert citations.

I have installed both `helm-bibtex` and `org-ref` from Melpa. I am running Emacs 26.3. Here is my [bibtex](https://pastebin.com/QkLdSQUy)  file. I am using [Evil mode](https://github.com/emacs-evil/evil) in emacs, but I don't think it matters as I tried in both insert and normal mode.

Please let me know if you need any other information. Thank you.

**Comment by jkitchin** [comment]
Can you type: C-h k C-c ]

and see what that key is bound to? I suspect that for some reason it is bound to an org agenda command to remove a file from the agenda. That could be either because org-ref is not loaded, or maybe something redefined the key-binding.

**Comment by GaurangTandon** [comment]
Hi, yes you are right:

```
C-c ] runs the command org-remove-file (found in org-mode-map), which
is an interactive compiled Lisp function in ‘org.el’.

It is bound to C-c ], <menu-bar> <Org> <File List for Agenda> <Remove
Current File from List>.

(org-remove-file &optional FILE)

Remove current file from the list of files in variable ‘org-agenda-files’.
These are the files which are being checked for agenda entries.
Optional argument FILE means use this file instead of the current.
```

What should I do now? `org-ref` and `helm-bibtex` are loaded - or so I believe - because I can access their commands from `M-x org-ref-[TAB]` and `M-x bibtex-[TAB]`.

**Comment by jkitchin** [comment]
That seems odd, does org-mode get loaded after org-ref somehow? Here is the code that is responsible for mapping that key-binding. You could make a mapping of your own, C-c ] is not mandatory, just the default.

```
;; define key for inserting citations
(define-key org-mode-map
  (kbd org-ref-insert-cite-key)
  org-ref-insert-link-function)
```

**Comment by koyafish** [comment]
Can confirm I'm having the same problem, I think that the default keybinding should be changed

**Comment by abdalazizrashid** [comment]
Same problem

**Comment by jkitchin** [comment]
You have to map this in your init file with something like:

`(define-key org-mode-map (kbd "C-c ]") 'org-ref-insert-link)`

or your chosen key-binding. See https://github.com/jkitchin/org-ref#configuration.

**Comment by abdalazizrashid** [comment]
Yeah, I did, but the strange bit is that org-ref is being loaded after org-mode...

**Comment by jkitchin** [comment]
Org-ref does not set this binding anymore.
