### ISSUE TITLE
org-ref-prefer-bracket-links largely ignored

### ISSUE THREAD

**Issue by guraltsev** [jkitchin/org-ref#775]
I am trying to use `org-ref` to write some lecture notes and I am mainly focused on using the label/reference functionality rather than the bibliography one. 

I noticed that there is `org-ref-prefer-bracket-links` that I set to `t` but it largely gets ignored in particular by `org-ref-helm-insert-ref-link`.

I think that there is a case for making `org-ref` links be org style bracketed links. This would make it easy to define an exporter e.g. for HTML.

 I am trying to publish the lecture notes on the course website and I want to avoid students having to download a bunch of PDFs but rather have an organic, hyperlinkable HTML document with math powered by MathJax. I would then define the link exporter to be simply `\\eqref{%s}` or `\\ref{%s}` respectively and let mathjax handle the rest.

Thanks for this fantastic piece of software!

**Comment by guraltsev** [comment]
Ah, sorry. I just realized that if I format the link with `eqref:whateverlabel` it does exactly what I was trying to accomplish. The fact that brackets do not get inserted remains, though. The bug is still valid.

**Comment by jkitchin** [comment]
I think `org-ref-prefer-bracket-links` is only used for cite links. What is the reason for having brackets around eqref or ref links? The only use case I have is for referring to subfigures e.g. [[ref:label]]-a when I have not used subfigures proper (because it is easier not to). I don't recall why I made `org-ref-prefer-bracket-links`, I guess there must be some people who prefer the brackets for some reason.

**Comment by guraltsev** [comment]
The rationale is just to make links conform to the org standard for links. That way they are more interoperable with other org-mode tools.  E.g. 

- Insert a ref link with `org-insert-link`
- Modify a link with `org-insert-link` with the cursor on the link
- Use builtin org-mode machinery to define how ref links are exported when defining a new backend (I know that org-ref provides some convenience functions for defining new exports)
- Possibly extend `ref:` links to provide custom captions e.g. 
```
\begin{equation}
\label{eq:pythagoras}
a^2+b^2=c^2
\end{equation}

MORE RANDOM TEXT

Now we use [[eqref:eq:pythagora][Pythagoras' identity]] to compute
```
For a latex example of this see https://tex.stackexchange.com/questions/70143/cross-reference-with-custom-text.
 - Generally for syntax uniformity in org-mode. 

I appreciate these are not primary issues, and to a certain extent they are a matter of taste. However the variable is there and I don't think it is documented that it affects only ``cite`` links. 

I actually locally modified `org-ref-helm-insert-ref-link` to respect the variable. If you are ok with it I can clean it up and submit a pull request in a couple of days.

**Comment by jkitchin** [comment]
A pull request would be fine for this, if you are still interested.
