### ISSUE TITLE
Viability of org-ref running on either ivy or helm

### ISSUE THREAD

**Issue by stefanv** [jkitchin/org-ref#782]
A few years ago there was an [effort to make org-ref run on Ivy](https://github.com/yyadavalli/org-ref-ivy).

Is this still a potential future direction, or is org-ref tied pretty deeply to helm by now?

I ask, because it seems as though users tend to choose either helm or ivy, but typically not both.

**Comment by jkitchin** [comment]
there are a few options for ivy built in to org-ref. One is the org-ref-ivy-cite backend (this is what I usually use). org-ref doesn't really require helm to work, there is only one helm function left that hasn't been replaced. IT isn't practical to separate out the ivy and helm dependencies though, so at the moment it supports them both, even if you only one one.

**Comment by stefanv** [comment]
Thanks for that explanation, @jkitchin!  I've avoided installing helm so far (it seems pretty heavyweight compared to ivy), but maybe having it around won't hurt (and, will give me org-ref :).
