### ISSUE TITLE
Add / Edit notes pushes citation key in kill ring

### ISSUE THREAD

**Issue by chemmi** [jkitchin/org-ref#790]
Hi!

I'm using org-ref for keeping notes to my references together with helm-bibtex. It happens from time to time that I want to paste content in the kill ring to reference notes briefly. By defaut, the the org-ref notes function pushes the bibtex key to the kill ring when adding/editing notes which is somewhat disruptive for my workflow. In `org-ref-notes-function-one-file` this behavior seems to be wanted explicitly.

https://github.com/jkitchin/org-ref/blob/e94a23e1d44759a946eded7257b475630371fb1c/org-ref-core.el#L2680-L2694

For configuration, I would like to place a switch here, i.e. an optional parameter, to choose if the function pushes the key to the kill ring. This should be quite easy. I can create a PR for that.

My question: Which should be the default behavior? In my opinion, it is the variant without pushing, but I do not know how this is anchored into other peoples workflows.

Thanks for discussion in advance. org-ref is great!

**Comment by jkitchin** [comment]
A switch is fine. I would make the default preserve the current behavior. you can set it the opposite of that to suppress it.

The reason it is there is in the comment: ;; save key to clipboard to make saving pdf later easier by pasting.

When you have to download the pdf by hand, you can just rename it and paste the new name from the clipboard.

**Comment by chemmi** [comment]
Thanks for your answer. I issued a pull request.

In my setup, I use `helm-bibtex` all the time. I integrated according to a snippet found in https://github.com/jkitchin/org-ref/issues/225#issuecomment-221042025 . Using the new switch, the suggested code uses `org-ref-notes-function-one-file` directly and looks like this.

```elisp
(defun my/org-ref-notes-function (candidates)
  (let ((key (helm-marked-candidates)))
    (funcall 'org-ref-notes-function-one-file (car key) t)))

(helm-delete-action-from-source "Edit notes" helm-source-bibtex)
(helm-add-action-to-source "Edit notes" 'my/org-ref-notes-function helm-source-bibtex 7)
```

**Comment by jkitchin** [comment]
I see (this also answers my comment at https://github.com/jkitchin/org-ref/pull/795#issuecomment-694264201)

In this example, the funcall is not necessary, you can call the function directly.
```
(defun my/org-ref-notes-function (candidates)
  (let ((key (helm-marked-candidates)))
    (org-ref-notes-function-one-file (car key) t)))

(helm-delete-action-from-source "Edit notes" helm-source-bibtex)
(helm-add-action-to-source "Edit notes" 'my/org-ref-notes-function helm-source-bibtex 7)
```
