### ISSUE TITLE
org-ref-show-broken-links... could it be better?

### ISSUE THREAD

**Issue by jmburgos** [jkitchin/org-ref#791]
Hi John,

I am wondering if the performance of org-ref when `(setq org-res-show-broken-links t)` could be improved.  I think it is an useful feature.

I though that `org-res-show-broken-links` slowed down emacs only in large files, but I did some tests, and noticed that the performance depends only on the number of citations on the paragraph being edited, and the slow down is noticeable only when the paragraph is larger than 300 characters or so.  This happens even in small files.

For example, in an empty org file I put a single paragraph and started to add bad citations, one by one, like this:

`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. cite:badref1 cite:badref2 cite:badref3 cite:badref4 cite:badref5 cite:badref6 cite:badref7`

The slow down was noticeable after the 5th or 6th reference.   In a paragraph with twice the amount of thext, the slow down is almost immediate.

But if I start a new paragraph, emacs speed goes back to normal.  In a paragraph with little text I added up to 12 bad references and did not noticed any slowdown.  

I am wondering why this is the case.  Checking the validity of the references should only require comparing the citation bein typed against the bib file.  Why the amount of "non citation" text, or the presence of other citations, would make a difference?  Would it be possible to improve this?

**Comment by jkitchin** [comment]
I don't know how to make it any better than it is. The issue may be that (org-ref-find-bibliography) is called on every cite face call. There is always a tension in checking everytime, and caching a result somehow to speed things up, but trying to make sure you update the cache if something changes. There is room for a lot of improvement in org-ref on this, but I don't have time these days to dig that deep.

**Comment by jmburgos** [comment]
I understand, and I hope that my elisp skills were enough so I could contribute some solution myself.  On the great scheme of things is a small issue, though.  I will write a small function to toggle  `org-res-show-broken-links` on and off, so I can turn it off when it slows me down.
