### ISSUE TITLE
[Feature request] Download pdfs from bib url field

### ISSUE THREAD

**Issue by lzmartinico** [jkitchin/org-ref#798]
Some of the biblio.el repositories do not include the doi field. When importing a paper from these sources, adding a PDF requires a manual download. In most cases, the full URL the doi would be pointing to is included as a field: it should then be straightforward to call the appropriate function in _doi-utils-pdf-url-functions_ to fetch it, using the url field rather than _doi-utils-redirect_. I realise it would be a bit weird to have this functionality in doi-utils, so this might need a bit of refactoring.

**Comment by jkitchin** [comment]
I would be happy to see a pull request for this feature. It will be a long time (maybe some months) before I have time to work on it myself.

**Comment by jkitchin** [comment]
Can you put an example of a bibtex entry that would have the field you are talking about here?

**Comment by lzmartinico** [comment]
Sure, I have seen this a lot with entries generated by DBLP. For example:
```
@article{DBLP:journals/iacr/BhatotiaKMT21,
  author    = {Pramod Bhatotia and
               Markulf Kohlweiss and
               Lorenzo Martinico and
               Yiannis Tselekounis},K
               Encryption},
  journal   = {{IACR} Cryptol. ePrint Arch.},
  volume    = {2021},
  pages     = {269},
  year      = {2021},
  url       = {https://eprint.iacr.org/2021/269},
  timestamp = {Wed, 07 Apr 2021 09:35:41 +0200},
  biburl    = {https://dblp.org/rec/journals/iacr/BhatotiaKMT21.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}
```
This has a url for the eprint page rather than a doi. Currently, trying to fetch a PDF  using `doi-utils-get-bibtex-entry-pdf` would fail, even if org-ref had the recipe to turn this URL into a PDF as part of `doi-utils-pdf-url-functions` (which would be trivial to add). What my PR was trying to do is decouple the PDF URL functions from the doi package, so that PDF can be downloaded with either bibtex url format  (`pdf-utils-get-bibtex-entry` tests the url to check if it can translate it to a pdf, or if it's the url to a doi which can then be translated to a pdf).  I agree this could be run as a hook in `org-ref-clean-bibtex-entry-hook`, but I think it would still be nice to provide a general way to get the pdf from the url field. `doi-utils-pdf-url-functions` is a nice resource in itself and it would be nice to make it independent from doi redirection!

**Comment by jkitchin** [comment]
Thanks for this example. I refactored some code in a branch that will eventually become the main branch towards this goal.

This example has some error in the author (and missing title). Other than that, how would you go about getting the pdf here? It is derivable from the url, but you would need some recipe to look up how to do that. This one seems easy, you just add .pdf to it and see if you can download it. How would you generalize that though?

**Comment by lzmartinico** [comment]
Ah I accidentally killed a line somehow, fixed now! 
You are right that this is not generalisable, but my point is that you have already built up an impressive library of URL to PDF recipes with the list of `doi-utils-pdf-url-functions`. This could be refactored outside of the doi package so that it might be easier for people to contribute new recipes
