### ISSUE TITLE
Detect books pdfs given crossref field

### ISSUE THREAD

**Issue by Vtec234** [jkitchin/org-ref#802]
Sometimes you have a paper (or multiple) in a single conference proceedings/journal/book PDF. In such cases, the dblp generally adds a `crossref = {thebook}` entry to the bibtex for those papers. It would be nice if `org-ref` could detect that and provide an `open pdf` prompt in such cases because you might have a PDF for the book containing the paper, even if there is no single PDF for that paper specifically. If I'm not missing something, `org-ref` currently doesn't do this. I could potentially attempt giving this a shot - is this something that [`org-ref-get-pdf-filename`](https://github.com/jkitchin/org-ref/blob/f582e9c53e8e4c5dcc1d3889f1b5c536c9a9b524/org-ref-utils.el#L374) would deal with?

**Comment by jkitchin** [comment]
It is possible to expand what that function does, but it would have to preserve the existing behavior. I think it would be better to write a new function that does what you want, and then setq `org-ref-get-pdf-filename-function` to that function.
