### ISSUE TITLE
Create `gls*` equivalent commands for acronyms: acr, acrpl, Acr and Acrpl

### ISSUE THREAD

**Issue by darcamo** [jkitchin/org-ref#804]
org-ref already supports acronyms, but for acronyms it only has the commands `acrshort`, `acrfull` and `acrlong`. However, these commands means that the acronym expansion in latex is manual, instead of automatic (expand on first use and use short version on subsequent uses).

With the glossaries package in latex, one is expected to use the `gls*` commands (`gls`, `glspl`, `Gsl`, etc) for the automatic expansion with acronyms and this also works just fine in org-ref. That is, something such as `gls:BB` will export to `\gls{BB}` in latex and just `BB` in html.

The only problem with this is that org-ref threads links like `gls:something` as glossary terms, which is intended. It has a specific face and if you click on it it will go to the definition. Except that when the term is actually an acronym the search will fail and we have the wrong face.

One possible improvement is that org-ref could define commands to mimic the `gls*` comands for acronyms, such as `acr`, `acrpl`, `Acr` and `Acrpl`. These would just export as their equivalent `gls*` command, but would use the correct face and when clocked it would search for `newacronym` instead of `newglossaryentry`. The current `acrshort`, `acrfull` and `acrlong` commands can then be used only when the user explicitely wants to control which way the acronym should be shown.

**Comment by jkitchin** [comment]
I don't have the time or need to work on this right now. If you want to try making a pull request, I would certainly consider it.

**Comment by darcamo** [comment]
After having a look at the source code, it turns out that org-ref already does this with the `ac`, `acp`, `Ac` and `Acp` links. They are just not properly documented in `org-ref-help`. I have created a pull request to add the missing information [here](https://github.com/jkitchin/org-ref/pull/805).

I'm closing the issue. Thanks.
