### ISSUE TITLE
Biblatex thesis type support

### ISSUE THREAD

**Issue by sati-bodhi** [jkitchin/org-ref#808]
What's the right way to differentiate between `phd` and `ma` for BibLaTeX generic `thesis` type as opposed to `phdthesis` and `mastersthesis` in BibTeX? With `bibtex-completion-apa-format-reference`, I can do: 

```
(defun thesistype-is-phd ()
  (string-match "phd\\|Ph\.D\.\\|PhD\\|Doctorate\\|博士" (cdr(assoc "type" entry))))

(defun thesistype-is-ma ()
  (string-match "ma\\|M\.A\.\\|MA\\|Master's\\|碩士" (cdr(assoc "type" entry))))

(defun bibtex-completion-apa-format-reference (key)
  (let*
      ((entry (bibtex-completion-get-entry key))
       ;; (author (bibtex-completion-get-value "author" entry))
       (ref (pcase (downcase (bibtex-completion-get-value "=type=" entry))
              ("thesis"
               (cond ((thesistype-is-phd)
                      (s-format
                       "${author} (${date}). ${title} (Doctoral dissertation). ${institution}, ${location}."
                       'bibtex-completion-apa-get-value entry))
                     ((thesistype-is-ma)
                      (s-format
                       "${author} (${year}). ${title} (Masters dissertation). ${institution}, ${location}."
                       'bibtex-completion-apa-get-value entry)))))))))
```

But 

```
(cond ((thesistype-is-phd)
       ("thesis" .
        "${author}, ${title} (Doctoral dissertation) (${year}). ${school}, ${address}."))
      ((thesistype-is-ma)
       ("thesis" .
        "${author}, ${title} (Master's dissertation) (${year}). ${school}, ${address}.")))
```

doesn't seem to work with `org-ref-formatted-citation-formats` (possibly due to the empty `entry` variable).

**Comment by sati-bodhi** [comment]
Other compatibility issues include [`date` vs `year`](https://github.com/retorquere/zotero-better-bibtex/issues/1684#issuecomment-714805795).

**Comment by jkitchin** [comment]
I don't know the answer to this.

**Comment by sati-bodhi** [comment]
> I don't know the answer to this.

Does that mean it is technically impossible with the present `org-ref` architecture to support `Biblatex` reference types and fields?

**Comment by jkitchin** [comment]
I don't think it means that, but I also don't understand what you are trying to do or what problem you are having. If you are having trouble with a non-latex export, the answer might be that it is very hard to provide full support for that.  If the problem is related to tool tips, or something like that, the answer is probably to make org-ref fail more gracefully.

**Comment by sati-bodhi** [comment]
> I don't think it means that, but I also don't understand what you are trying to do or what problem you are having. If you are having trouble with a non-latex export, the answer might be that it is very hard to provide full support for that. If the problem is related to tool tips, or something like that, the answer is probably to make org-ref fail more gracefully.

The problem is simply this: How to make `org-ref` support `biblatex` reference types and fields. I am working with LaTeX exports only. 

As can be seen over here, 

![圖片](https://user-images.githubusercontent.com/7592695/96938106-20d3d600-14fc-11eb-9eaf-498c47f17ab8.png)

`date` fields from `biblatex` are missed out by `org-ref` because it makes reference to the `year` field. This, of course can be easily resolved by changing `${year}` to `${date}` - a local date parser is probably needed to extract the year from the date. 

A more difficult problem is the `@thesis` field in `biblatex`. The original code in `org-ref-formatted-citation-formats` makes use of `bibtex` `@phdthesis` and `@mastersthesis` reference type to differentiate between the two, like so: 

```
("phdthesis" .
        "${author}, ${title} (Doctoral dissertation) (${year}). ${school}, ${address}."))
 ("mastersthesis" .
        "${author}, ${title} (Master's dissertation) (${year}). ${school}, ${address}."))
```

With `biblatex`, which maps both to a single `thesis` type and makes the distinction within the `type` field, it is not as straightforward to format citations to each of these over here.

**Comment by jkitchin** [comment]
None of these are easy to fix, and I think might require a different approach, e.g. a function that computes a string, rather than simply filling in a template. I guess using an external dependency, e.g. if you can get bibtex or biblatex itself to generate the string is the best strategy, or perhaps some other csl tool. Otherwise, you will end up duplicating that feature in elisp to get all those things working. I don't have plans to do that anytime soon.

**Comment by sati-bodhi** [comment]
I am familiar enough with elisp to be able to write functions that manipulate strings on my own. I just need general instructions as to how to best approach the problem, considering `org-ref`'s architecture. I am not familiar enough with LaTeX code to edit or craft a new style on my own. 

I should be working with biblatex only, so backward compatibility with bibtex would probably not be a big issue for me. 

Because I work with bilingual sources (English and Chinese) with different citation formats, even if I leave to minibuffer display as it is, I plan to leverage on `org-ref` and elisp functionality to generate Chinese citation strings for on my own, before feeding the rest into biblatex to format the English citations and bibliography in Chicago footnote style. (But this would be another issue.)

**Comment by jkitchin** [comment]
If `bibtex-completion-apa-format-reference` makes strings the way you like I think you can just use it instead. You can replace it like this

`(advice-add 'org-ref-format-entry :override 'bibtex-completion-apa-format-reference)`

after you load org-ref.
