### ISSUE TITLE
org-ref broken at upgrade to Emacs 27

### ISSUE THREAD

**Issue by thriveth** [jkitchin/org-ref#811]
I have just upgraded to Emacs 27, after which org-ref has stopped working on my system.
It does not export bibliograpgy or citations, and whie the function names are known to Emacs, they do not do anything. 

Is this a known problem?

**Comment by jkitchin** [comment]
It works fine for me on Emacs 27.1. I am not aware of any problems with this.

**Comment by thriveth** [comment]
My bad, something during upgrade had broken my org-contrib packages, as soon as that one was fixed, it worked as expected. 
Apologize for the noise!

**Comment by jkitchin** [comment]
whew! Glad it is working for you!
