### ISSUE TITLE
Pulling PDF absolute path from bibtex before attempting to create one

### ISSUE THREAD

**Issue by jvandoorn** [jkitchin/org-ref#815]
In setting the org-ref-note-title-format for custom notes, I noticed that %F creates an absolute path from concatenating org-ref-pdf-directory, the =key= field in the bibtex entry, and ".pdf". I generate my bibtex files with Zotero, which keeps a =file= key containing the absolute path in the bibtex entry. Right now I have edited org-ref-utils.el to pull the file path from that. But it could be helpful to check if this key with the absolute path exists in the bibtex file before trying to create one.

**Comment by jkitchin** [comment]
see this commit above. I think it is closer to what should happen.
