### ISSUE TITLE
#+NAME: labels are not correctly updated on save 

### ISSUE THREAD

**Issue by czikus** [jkitchin/org-ref#817]
I'm relying on `#+NAME` to define labels. However, after a label is modified, the font lock of the corresponding `ref:` is not updated, even after saving the file. The font locks are updated when I execute this:

```
    (setq-local org-ref-labels nil)
    (org-ref-get-labels)
    (org-restart-font-lock)
```

It would be great if this was done automatically after a file is saved.

**Comment by jkitchin** [comment]
That is a limitation of how font lock works, the region that is refontified is local, and we don't currently keep track of references to be able to update nonlocally. 

Your solution sounds like an application for a hook, e.g. before-save-hook or after-save-hook.

```
(defun org-ref-font-lock-save ()
  (setq-local org-ref-labels nil)
  (org-ref-get-labels)
  (org-restart-font-lock))

(add-hook 'before-save-hook 'org-ref-font-lock-save nil t)
```

I am not sure it is a great idea to enforce this for all users. There are for certain, issues of accuracy with the current font-lock system, and performance with the previous system that relied on org-parsing. For some documents refontifying the whole thing not be a good idea. I think adding the hook above to your personal setup is the right solution for now.

**Comment by czikus** [comment]
Sounds good. Thanks for taking the time to reply.
