### ISSUE TITLE
org-store-link stores file: link for tables and ref: links for images

### ISSUE THREAD

**Issue by czikus** [jkitchin/org-ref#818]
I noticed that `org-store-link` is inconsistent when it comes to labels defined with `#+NAME:`. For example, for images:

```
#+CAPTION: This is an image caption.
#+NAME: fig-1
[[file:example.jpg]]
```

it stores `ref:fig-1`. However, for tables:

```
#+CAPTION: This is a table caption.
#+NAME: tab-1
| Col1 | Col2 | Col3 |
|------+------+------|
|    1 |    2 |    3 |
```

it stores `file:example.org::tab-1`.

It would be great if that behavior was consistent and potentially configurable.

**Comment by jkitchin** [comment]
Thanks for reporting this. I have added some code that I think works much better now for both figures and tables.

**Comment by czikus** [comment]
I'm afraid the problem is still there. What behavior were you specifically aiming for?

**Comment by jkitchin** [comment]
For me, with this commit, If my cursor is anywhere in the table, it stores ref:tab-1, and if it is anywhere in the figure, it stores ref:fig-1.

**Comment by czikus** [comment]
For me, for this table:

```
#+CAPTION: This is a table caption.
#+NAME: tab-foo
| Col1 | Col2 | Col3 |
|------+------+------|
|    1 |    2 |    3 |
```

on the table itself, it does not even store the label, but a link to the heading above. On `#+NAME` it stores a `file:` link.

**Comment by fleimgruber** [comment]
I can reproduce https://github.com/jkitchin/org-ref/issues/818#issuecomment-735287472 with org-ref-20201231.1406 with the MRE below. On any line in the table or table `#+CAPTION` or `#+NAME` a link to the containing `heading` is stored.

```
* heading

#+CAPTION: This is a table caption.
#+NAME: tab-foo
| Col1 | Col2 | Col3 |
|------+------+------|
|    1 |    2 |    3 |

#+CAPTION: This is an image caption.
#+NAME: fig-1
[[file:example.jpg]]
```

**Comment by jkitchin** [comment]
I was also able to reproduce this, and maybe have fixed it in adc37ef.

**Comment by fleimgruber** [comment]
I just checked (MELPA org-ref-20210103.1730) and now the behavior is flipped, i.e. it works on any line in the table or table #+CAPTION or #+NAME, but for the fig it only works on the file: link, on the figure #+NAME or #+CAPTION a link to the containing `heading` is stored.

**Comment by jkitchin** [comment]
hm. For me it works fine today, even correctly storing a link in the equation below.

```
* heading

#+CAPTION: This is a table caption.
#+NAME: tab-foo
| Col1 | Col2 | Col3 |
|------+------+------|
|    1 |    2 |    3 |

#+CAPTION: This is an image caption.
#+NAME: fig-1
[[file:example.jpg]]

\begin{equation}\label{eq-1}
test
\end{equation}
```

**Comment by fleimgruber** [comment]
Storing the link in the equation works. The described behavior is still there for me with org-ref-20210105.1701, I will try to edebug to see what is going on.

**Comment by fleimgruber** [comment]
@jkitchin Could you give me a heads-up on which part of `org-ref-label-store-link` should be hit here if point is on `#+NAME: fig-1`? Am I even on the right track with this function?

**Comment by jkitchin** [comment]
That is the right function. I pushed a commit in f93f2f5 that probably fixes what you are seeing. Here is the relevant section that should be storing that link.

```
     ;; here on a paragraph (eg in a caption of an image). it is a paragraph with a caption
     ;; in a caption, with no name, but maybe a label
     ((equal (org-element-type object) 'paragraph)
      (if (org-element-property :name object)
	  (org-store-link-props
	   :type "ref"
	   :link (concat "ref:" (org-element-property :name object)))
	;; See if it is in the caption name
	(let ((caption (s-join "" (mapcar 'org-no-properties
					  (org-export-get-caption object)))))
	  (when (string-match org-ref-label-re caption)
	    (setq label (match-string 1 caption))
	    (org-store-link-props
	     :type "ref"
	     :link (concat "ref:" label))))))
```

**Comment by fleimgruber** [comment]
I tested the fix manually and it looks good, thanks for the quick action!

**Comment by jkitchin** [comment]
Thanks for your patience in working this out! Storing links is still somewhat confusing for me.
