### ISSUE TITLE
Org-ref html export with numbered citation list

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#819]
Is there a reason that the feature described [here](http://kitchingroup.cheme.cmu.edu/blog/2015/12/03/Exporting-numbered-citations-in-html-with-unsorted-numbered-bibliography/) was never implemented as the default export for citations in html?

**Comment by jkitchin** [comment]
no particular reason. Some other things got prioritized, and it seemed like org-mode was working towards a different solution at the time. That didn't happen so far though. There are some other elisp citation processors around now, and I haven't kept up with this approach (which should mostly still work) or the others. I haven't had much development time these days to support this further.

**Comment by vnckppl** [comment]
Thank you for your prompt answer!
