### ISSUE TITLE
org-insert-link always adds brackets for cite: links 

### ISSUE THREAD

**Issue by czikus** [jkitchin/org-ref#820]
`org-insert-link` adds brackets for `cite:` links, despite `org-ref-prefer-bracket-links` set to nil.

**Comment by jkitchin** [comment]
can you describe more clearly what you did to get this? e.g. where did you store a link? `org-ref-prefer-bracket-links` is really only an internal variable, it can't influence `org-insert-link` I think. But, there might be a way to avoid the brackets depending on the store functions.

**Comment by czikus** [comment]
No link was stored. I simply use `org-insert-link` and since I use helm, org offers me a list of registered link types, including `cite:`. When I select it, org runs `(org-cite-complete-link)` and then inserts the `cite:` link in brackets. 

Now looking closer, the same problem occurs for `ref:`. So, basically everything inserted using `org-insert-link` currently disregards `org-ref-prefer-bracket-links`. As a result, it becomes necessary to use org-ref specific methods, e.g. `org-ref-insert-ref-link` for each type of link, instead of the common `org-insert-link`. 

I just assumed that since it is possible to insert `cite:`, `ref:` etc. using `org-insert-link`, that would be the preferred way to do it.

**Comment by yantar92** [comment]
> I just assumed that since it is possible to insert `cite:`, `ref:` etc. using `org-insert-link`, that would
> be the preferred way to do it.

Inserting bracket link is hard-coded into `org-insert-link`. If one
wants to add an option to insert links without brackets (when no
description is given), it will require sending patch directly to
org-mode developers.

**Comment by czikus** [comment]
I suspected that much. For now, I'll just advise org functions to achieve what I want. Thanks for taking the time to reply.

**Comment by jkitchin** [comment]
advice was going to be my suggestion too.
