### ISSUE TITLE
pubmed-insert-bibtex-from-pmid search failed

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#821]
When I run 

`pubmed-insert-bibtex-from-pmid`

and enter a valid PMID (e.g., 33256581), I receive the following error: 

`pubmed-get-medline: Search failed: "<pre>"`

This is happening for all Pubmed searches. Can anyone replicate this?

**Comment by jkitchin** [comment]
That is happening for me too. It appears maybe pubmed has changed what it returns, so that it doesnt seem to have the medline text anymore. I am not sure what it will take to recover this functionality, probably digging through the pubmed page to figure out how to scrape the info we need out of it.

**Comment by vnckppl** [comment]
Line 169 of https://github.com/jkitchin/org-ref/blob/d62c9a9db447f16a7182fbdddce45539f9fe5f6a/org-ref-pubmed.el reads:

` (format "http://www.ncbi.nlm.nih.gov/pubmed/%s/?report=xml&format=text" pmid))
`

When I run:

`curl http://www.ncbi.nlm.nih.gov/pubmed/28004912/?report=xml&format=text`

I get:

> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>301 Moved Permanently</title>
> </head><body>
> <h1>Moved Permanently</h1>
> <p>The document has moved <a href="https://www.ncbi.nlm.nih.gov/pubmed/28004912/?report=xml">here</a>.</p>
> </body></html>

The new pubmed link format seems to be:

`curl https://pubmed.ncbi.nlm.nih.gov/28004912/?report=xml&format=text`

This does give text output. 

However, the output html does not have a <pre> tag.

**Comment by jkitchin** [comment]
I have probably fixed this for now. Thanks for reporting it.
