### ISSUE TITLE
On-and-off `funcall: Symbol’s function definition is void: nil` after startup, sometimes resolves itself and works as expected

### ISSUE THREAD

**Issue by japhir** [jkitchin/org-ref#823]
Recently, I've been having issues with the `funcall: Symbol’s function definition is void: nil` appearing when I C-c C-o on an org-ref link. Citations are recognized correctly, the minibuffer echos the full cite info when point is over it, but pressing RET or C-c C-o results in the above error.

I've also had sessions where this happens, but somehow starts to work normally again after a while, without me changing anything...
That's what makes it quite hard to debug, but [here's the relevant section of my config](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#org-ref)

**Comment by jkitchin** [comment]
I cannot reproduce this.  something seems very strange. 

Where are your init files and bib files? e.g. are they in any kind of cloud drive (Dropbox, GDrive, etc.)?

I would check *Messages* carefully to see if there is some evidence of an error that is preventing things from completely loading.

**Comment by japhir** [comment]
my init files are in ~/ArchConfigs and symlinked to the correct location. Bib files are local but are synced via owncloud.

I guess I'll close this, haven't had it happen in a while.
