### ISSUE TITLE
org-ref-title-case operates on a fixed set of fields

### ISSUE THREAD

**Issue by czikus** [jkitchin/org-ref#824]
While it is possible to specify `org-ref-title-case-types`, it is not possible to change the fields `org-ref-title-case` affects. This is hardcoded using `(dolist (field '("title" "booktitle"))`. This does not allow for the case when the `title` of `@inproceedings` should be modified, but not its `booktitle`. It would be great if one could specify different fields for each entry type, or at the very least, simply modify the fixed list of fields that should be affected.

**Comment by jkitchin** [comment]
see the commit above. It adds some flexibility where you can specify via a customizable alist which fields are title cased, and which types.

**Comment by czikus** [comment]
Great, thanks!
