### ISSUE TITLE
Can't export org-ref.org

### ISSUE THREAD

**Issue by igajsin** [jkitchin/org-ref#825]
Hi. I installed org-ref via 
``` elisp
     (use-package org-ref
       :ensure t
       :custom
       (reftex-default-bibliography "~/gtd/storage/references/references.bib")
       (org-ref-bibliography-notes "~/gtd/storage/references/notes.org")
       (org-ref-pdf-directory "~/gtd/storage/references/pdfs")
       (bibtex-completion-bibliography reftex-default-bibliography)
       (bibtex-completion-library-path org-ref-pdf-directory)
       (bibtex-completion-notes-path org-ref-bibliography-notes)
       (bibtex-completion-pdf-open-function 'org-open-file))
```

Then I did `M-x org-ref-help` and tried to export the org-ref.org file as usual. 

Unfortunately, emacs complains about the 'Unable to resolve link: "wos-search:alloy and segregation" error.

Not sure is it a bug or I miss some steps.

**Comment by jkitchin** [comment]
you probably are looking for https://github.com/jkitchin/org-ref/blob/master/org-ref.org#other-forms-of-this-document.

**Comment by igajsin** [comment]
Thanks. The `(setq org-export-with-broken-links t)` command helped me with that.
