### ISSUE TITLE
org-open-at-point on cite link uses org-bibtex-goto-citation

### ISSUE THREAD

**Issue by fleimgruber** [jkitchin/org-ref#827]
This came up when I tried to reproduce https://github.com/jkitchin/org-ref/issues/810. Initially, `org-open-at-point` works as expected, i.e. a helm buffer appears and I can e.g. jump to the bib entry. I can't yet reproduce exactly when, but at some point later on when trying again to open the cite link, I get the error "'org-bibtex-file' has not been configured" (traceback below), so it seems that somehow `org-bibtex-goto-citation` from ox-bibtex.el gets registered as the cite link handler when I expect this to be a `helm-*` handler set by org-ref? How to check which handler is registered or how to further debug this? This looks like something outside of org-ref is hijacking the cite link handling though...

```
Debugger entered--Lisp error: (error "‘org-bibtex-file’ has not been configured")
  signal(error ("‘org-bibtex-file’ has not been configured"))
  error("`org-bibtex-file' has not been configured")
  org-bibtex-goto-citation("Hoff17riskProbFrcstRenewFleet_Pat")
  org-link-open((link (:type "cite" :path "Hoff17riskProbFrcstRenewFleet_Pat" :format bracket :raw-link "cite:Hoff17riskProbFrcstRenewFleet_Pat" :application nil :search-option nil :begin 45 :end 124 :contents-begin 87 :contents-end 122 :post-blank 0 :parent (paragraph (:begin 45 :end 126 :contents-begin 45 :contents-end 125 :post-blank 1 :post-affiliated 45 :parent nil)))) nil)
  org-open-at-point(nil)
  funcall-interactively(org-open-at-point nil)
  call-interactively(org-open-at-point nil nil)
  command-execute(org-open-at-point)
```

**Comment by jkitchin** [comment]
I have pushed a new element in `M-x org-ref` that should identify this problem.

**Comment by fleimgruber** [comment]
Thanks for the load order hint and the code change, will check it out once it lands on MELPA.

**Comment by jkitchin** [comment]
@fleimgruber is the problem here that ox-bibtex is loaded after org-ref and it redefines the cite link?

**Comment by fleimgruber** [comment]
Yes, earlier when I said I can't reproduce this I thought ox-bibtex was already loaded. Turns out that I can reproduce this if ox-bibtex is loaded after org-ref and redefines the cite link as you said. `M-x org-ref` contains the relevant parts (a bit mangled though? See below).

So what would your recommendation be here or in these cases in general, i.e. link handling gets overridden by more recently loaded packages. Let the users take care of the load order? This would be the easiest (i.e. nofix) from org-ref perspective and most likely the way to go, right? Just curious about your ideas as to how it might be fixed differently, e.g. is there infrastructure in Org mode to specify which functions should take precedence (user-defined) in such cases?

```
-  org-latex-packages-alist
  ("" "booktabs")
  ("range-phrase=-,range-units=single" "siunitx")
- ox-bibtex loaded = t- ox-bibtex loaded after org-ref = t- cite link definition:
("cite" :follow org-bibtex-goto-citation :export nil :complete org-cite-complete-link :help-echo
 (lambda
   (window object position)
   (when org-ref-show-citation-on-enter
     (save-excursion
       (goto-char position)
       (let
           ((s
             (org-ref-format-entry
              (org-ref-get-bibtex-key-under-cursor))))
         (with-temp-buffer
           (insert s)
           (fill-paragraph)
           (buffer-string))))))
 :face org-ref-cite-link-face-fn :display full :keymap
 (keymap
  (tab lambda nil
       (interactive)
       (funcall org-ref-insert-cite-function))
  (S-up . org-ref-sort-citation-link)
  (S-right lambda nil
           (interactive)
           (org-ref-swap-citation-link 1))
  (S-left lambda nil
          (interactive)
          (org-ref-swap-citation-link -1))
  (C-right . org-ref-next-key)
  (C-left . org-ref-previous-key)
  (16777337 lambda nil "Paste key at point. Assumes the first thing in the killring is a key."
            (interactive)
            (org-ref-insert-key-at-point
             (car kill-ring)))
  (16777303 lambda nil "Copy all the keys at point."
            (interactive)
            (kill-new
             (org-element-property :path
                                   (org-element-context))))
  (16777335 lambda nil
            (interactive)
            (kill-new
             (car
              (org-ref-get-bibtex-key-and-file))))
  (16777318 lambda nil
            (interactive)
            (save-excursion
              (org-ref-open-citation-at-point)
              (kill-new
               (org-ref-format-bibtex-entry-at-point))))
  (16777319 . org-ref-google-scholar-at-point)
  (16777317 lambda nil "Email entry at point"
            (interactive)
            (org-ref-open-citation-at-point)
            (org-ref-email-bibtex-entry))
  (16777315 . org-ref-wos-citing-at-point)
  (16777330 . org-ref-wos-related-at-point)
  (16777326 . org-ref-open-notes-at-point)
  (16777328 . org-ref-open-pdf-at-point)
  (16777333 . org-ref-open-url-at-point)
  (16777314 . org-ref-open-citation-at-point)
  (16777327 . org-ref-cite-hydra/body)
  (follow-link . mouse-face)
  (mouse-3 . org-find-file-at-mouse)
  (mouse-2 . org-open-at-mouse))
 :store org-ref-bibtex-store-link)
```

**Comment by jkitchin** [comment]
I don't see any "right" answer to this other than load them in the order that makes sense, i.e. that leads to the cite link you want to use. org-mode doesn't provide any precedence mechanism, and if it did how would you resolve these two packages both saying their version of the cite link is the "right" one?

In this case, you should load ox-bibtex first, and then org-ref.

I have added some code to org-ref that at least warns you if a link is getting redefined.

**Comment by fleimgruber** [comment]
> how would you resolve these two packages both saying their version of the cite link is the "right" one?

I was just thinking aloud of a user setting e.g. `(setq org-cite-link-handler-packages '(org-ref org-bibtex-goto-citation))` (where order matters) for resolution, but that would of course require the hypothetical infrastructure in org-mode which is now confirmed to be nonexisting.

So load order it is then!
