### ISSUE TITLE
Pre/post text for multiple citations

### ISSUE THREAD

**Issue by lyndondrake** [jkitchin/org-ref#829]
Hi,

Thanks for a great project!

I have found how to cite multiple items with a single citation, e.g. `cite:Dearman1981,Dearman1988` and how to add post text such as a page locator, e.g. `[[cite:Dearman1981][;, 179]]`. What I can't figure out is how to do the first form, with two citations, and a page locator for each of the two, such as page 179 for the first item cited and page 283 for the second. Any thoughts?

BTW if this involves trying out the new citeproc support, I'm keen to help test it as I've used Pandoc quite a bit.

Best,
Lyndon

**Comment by jkitchin** [comment]
I think it is not possible to have multiple page locators in a single cite link. You probably have to write each one out separately.

**Comment by lyndondrake** [comment]
No worries, that works fine (& I think I was confused about what I was trying to do anyway!)
