### ISSUE TITLE
org-ref and org-export to an org file

### ISSUE THREAD

**Issue by lyndondrake** [jkitchin/org-ref#830]
This is a little obscure, perhaps, but if I do `C-c C-e` and export to an org file (which makes the #+INCLUDE directives work so that I can then process with pandoc), the citations all get converted to links. Is this intended behaviour?

**Comment by lyndondrake** [comment]
As an example: `cite:Carroll1981` in the input document gets turned into `[[#Carroll1981][Carroll1981]]` in the exported document. I'd prefer it not to be transformed.

**Comment by jkitchin** [comment]
That is currently intended. You can redefine the export functions if you want like this.

`(org-link-set-parameters "cite" :export #'your-export-function)`

**Comment by lyndondrake** [comment]
Oh cool, I hadn't thought of that. I'll have to brush up (i.e. start!) on my Emacs Lisp programming :-)
