### ISSUE TITLE
simple question on inserting bibliography on document

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#835]
While writing my text with in-text citation, I want to add a references section, as usual, at the end with a list of references. How do I achieve this with org-ref? Couldn't find any insert bibliography function. Thanks!

**Comment by jkitchin** [comment]
It depends on what you mean by insert references. Usually references are put in during the export stage. That way they are always up to date with the document.

You can type M-x org-ref-bibliography which will open a new buffer with the references in them, and you can copy those to your org-buffer if you want. Depending on your bibtex file, this may or may not "look beautiful".

You could use a function like this to automate that.

```
(defun insert-bibliography ()
  (interactive)
  (let ((bibliography (save-window-excursion
			(org-ref-bibliography)
			(buffer-string)) ))
    (insert bibliography)))
```

**Comment by AtomicNess123** [comment]
Thanks for the time, this works great!
I understand from reading this site that in order to get the references formatted (instead of getting them listed with "cite:"), it is possible to have this function to render them formatted in org by using a package such as citeproc?

```
  1. cite:Penrose2006 Penrose, R., The road to reality, The Mathematical Intelligencer, 28(3), 59–61 (2006).  http://dx.doi.org/10.1007/BF02986885

  2. cite:Cun1991 Cun, Y. L., Kanter, I., & Solla, S. A., Eigenvalues of covariance matrices: application to neural-network learning, Physical Review Letters, 66(18),  (1991).  http://dx.doi.org/10.1103/PhysRevLett.66.2396
```

**Comment by jkitchin** [comment]
This is possible, but not that trivial yet. Within org-ref you can look at https://kitchingroup.cheme.cmu.edu/blog/2015/12/11/Introduction-to-a-citation-processor-in-org-ref/. I don't use this code these days but I guess it should still work. I don't know if any of the other citeproc packages eg https://github.com/andras-simonyi/citeproc-org work better or not.

**Comment by AtomicNess123** [comment]
Great resources, thanks.
