### ISSUE TITLE
broken links to bibliography link in the manual

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#836]
In https://github.com/jkitchin/org-ref/blob/master/org-ref.org.

**Comment by jkitchin** [comment]
what links are you talking about?

**Comment by AtomicNess123** [comment]
"org-ref uses the `bibliography link` to determine"

Bibliography link and several of its instances.

**Comment by jkitchin** [comment]
What is broken on it? When I click on it, it jumps to the end where the radio target is defined.

**Comment by AtomicNess123** [comment]
The link is "https://github.com/jkitchin/org-ref/blob/master/bibliography%20link", probably the space between bibliography and link make it broken, at least in my Chrome.

![image](https://user-images.githubusercontent.com/47029233/105404077-3a3b0a00-5c32-11eb-810c-ca22215ff8d8.png)

**Comment by jkitchin** [comment]
I see. That is a bug in github, not org-ref. Github is incorrectly rendering the correctly defined link that points to the radio target in https://github.com/jkitchin/org-ref/blob/master/org-ref.org#references.

**Comment by AtomicNess123** [comment]
Yes, it's a problem of rendering. I thought you may want to fix it since it affects the navigation of the org-ref page.

**Comment by jkitchin** [comment]
It isn't for me to fix, it is Github's error.
