### ISSUE TITLE
unsupported doi

### ISSUE THREAD

**Issue by dlebrecht** [jkitchin/org-ref#84]
i just found a weird doi which is unsupported by org-ref

doi:10.1016/S0896-6273(03)00148-X

http://www.sciencedirect.com/science/article/pii/S089662730300148X

**Comment by jkitchin** [comment]
What do you mean it isn't supported? Parentheses in a raw link are not supported in any org link. For this one you have to wrap it in [[]].

This works for me.

[[doi:10.1016/S0896-6273(03)00148-X]]

**Comment by dlebrecht** [comment]
oh, i see -- never noticed that before

thanks
d
