### ISSUE TITLE
spaces in link to bibliography

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#842]
Quick question:

if my path to bib has spaces, how to express them?

`bibliography:~/Dropbox/{NAME PhD}/papers/manuscript/@mybibliography.bib`

Thanks!

**Comment by jkitchin** [comment]
you might get away with putting the link in double brackets, e.g. `[[bibliography:~/Dropbox/{NAME PhD}/papers/manuscript/@mybibliography.bib`, however spaces can cause problems for bibtex in my experience.
