### ISSUE TITLE
org-ref-helm-insert-cite-link vs org-ref-insert-link

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#843]
I seem to have the keybinding C-c ) binded to org-ref-insert-link. Is it possible to rebind it to org-ref-helm-insert-cite-link?

**Comment by jkitchin** [comment]
I don't know how you could have done that. The variable `org-ref-insert-cite-key ` defines where function defined in `org-ref-insert-link-function` is bound to. Usually it is C-c ], and the value of `org-ref-insert-link-function` is set by the backend library you choose. It should be set to org-ref-helm-insert-cite-link if you have loaded org-ref-helm-bibtex.

**Comment by AtomicNess123** [comment]
Thanks, you are right.
