### ISSUE TITLE
Cite: on point, by searching online (Fallback options?)

### ISSUE THREAD

**Issue by AtomicNess123** [jkitchin/org-ref#844]
I couldn't find this on the manual so I will ask straight away :)
I see there is the possibility of searching on an engine (i.e., Scholar, Pubmed, etc.) on the spot if not finding the reference needed in the bibtex file linked to my manuscript (section Fallback Options). However, I can't seem to be able to jump to that section unless I scroll down (and my bibtex file is veeery long). Is there a way to do this?

**Comment by jkitchin** [comment]
I assume you mean in helm-bibtex.  I am not aware of one, usually your query would have eliminated all possibilities so that is all that is left. I would ask in the helm-bibtex repo though.
