### ISSUE TITLE
org-ref-insert-link/orhc-update-bibfile-cache: Wrong type argument: stringp, 2

### ISSUE THREAD

**Issue by sschob** [jkitchin/org-ref#845]
when calling `org-ref-insert-link`, I get a "Wrong type argument: stringp, 2".  It turns out that the call to `orhc-update-bibfile-cache` returns the error. In particular calling`(orhc-update-bibfile-cache("~/test.bib"))` with the file content shown below leads to the error: 
```
@online{Han_2014,
  title = {Minimax {{Estimation}} of {{Discrete Distributions}} under \$\textbackslash ell\_1\$ {{Loss}}},
  author = {Han, Yanjun and Jiao, Jiantao and Weissman, Tsachy},
  date = {2014-11-05},
  url = {http://arxiv.org/abs/1411.1467},
  urldate = {2014-11-09},
  abstract = {This fails: \$2\$},
  archivePrefix = {arXiv},
  eprint = {1411.1467},
  eprinttype = {arxiv},
  keywords = {Computer Science - Information Theory},
  primaryClass = {cs, math}
}
```

As far I can see, it seems to be the **abstract** key which causes the trouble, for example changing it to `\$5\$` gives me "Wrong type argument: stringp, 5".  Also this does not happen for  `@article` BibTeX entries.

I am on org-ref master:052a176b4cc1c080376c183e5e02ab37cb1f0f0a

**Comment by sschob** [comment]
to reproduce:

```
#+begin_src elisp
(setq foo "@online{Han_2014,\
  title = {Some Title},\
  author = {Han, Yanjun and Jiao, Jiantao and Weissman, Tsachy}, \
  date = {2014-11-05},\
  url = {http://arxiv.org/abs/1411.1467},\
  urldate = {2014-11-09},\
  abstract = {This fails: \\$5\\$},\
  archivePrefix = {arXiv},\
  eprint = {1411.1467},\
  eprinttype = {arxiv},\
  keywords = {Computer Science - Information Theory},\
  primaryClass = {cs, math}\
}")
(write-region foo nil "~/mytest.bib")

(orhc-update-bibfile-cache "~/mytest.bib")
#+end_src
```

**Comment by jkitchin** [comment]
I am not able to reproduce this on 00a5602ccee034bd3d4af7c79c68c2bfbb47b26d, although I also can't think of any reason this would be failing. Why are you escaping the $ signs though?

**Comment by sschob** [comment]
I use Zotero, the database is automatically exported by [better-bibtex ](https://retorque.re/zotero-better-bibtex/). 
Is there any difference between handling **online** and **article**?

**Comment by jkitchin** [comment]
yes, `online` is not a valid entry type for bibtex, only for biblatex I guess. If you don't have the bibtex dialect set correctly, online won't even be recognized as a an entry type. I guess the escape is wrong anyway, unless you literally want to see $5$ in your rendered pdfs.

**Comment by sschob** [comment]
I explored it a little bit more, the lines below (from `orhc-update-bibfile-cache`) lead to the error (unfortunately my elisp knowledge is very limited).

This does not work (I get  **Wrong type argument: stringp, 1**):
```
#+begin_src elisp
;; example entry
(setq entry-type "online")
(setq  entry '(("=key=" . "MY_KEY") ("author" . "Me") ("title" . "All about number $1$")))
;; from orhc-update-bibfile-cache 
(s-format
 (or (cdr (assoc (downcase entry-type) orhc-candidate-formats))
     (format "%s: %s" (cdr (assoc "=key=" entry)) entry))
 'orhc-bibtex-field-formatter
 entry)
#+end_src
```
This does work:
```
#+begin_src elisp
;; example entry
(setq entry-type "article")
(setq  entry '(("=key=" . "MY_KEY") ("author" . "Me") ("title" . "All about number $1$")))
; orhc-update-bibfile-cache:
(s-format
 (or (cdr (assoc (downcase entry-type) orhc-candidate-formats))
     (format "%s: %s" (cdr (assoc "=key=" entry)) entry))
 'orhc-bibtex-field-formatter
 entry)
#+end_src
```
I found that I can build the cache if  I modify `orhc-candidate-formats` to include an entry for **online**, but this does not feel like the solution :-).

**Comment by jkitchin** [comment]
I guess that is the solution. That probably should be a defcustom anyway. Just add it to that list if that solves it.

I think the problem is with s-format, that it is recognizing the $1 as a field to be replaced when there is not a candidate format for it. I moved that out in a commit just now that might fix this issue.

Anyway, as I mentioned, online is not a valid bibtex entry type if you are using a bibtex dialect, and bibtex won't be able to parse it.

**Comment by sschob** [comment]
Thank you, your recent commit did the job, works for me.
