### ISSUE TITLE
How to always use org-ref-bibtex-store-link in .bib files?

### ISSUE THREAD

**Issue by notuntoward** [jkitchin/org-ref#847]
Lately, when I run `org-store-link` in a bib file, the default link store function is `org-git-store-link`.  What do I change to make it always `org-ref-bibtex-store-link`?

`org-git-store-link` being the default function is new but as far as I know, I haven't changed anything related in my config file, except to update emacs packages.

**Comment by jkitchin** [comment]
I don't know why this would have changed. I am not sure exactly what to change, the org-store-link machinery is not that straightforward to me, and it seems to only store the last successful link stored, and not all the successful link stores.

**Comment by notuntoward** [comment]
For posterity, the problem was somehow related to `org-roam`.  

After I uninstalled the `org-roam-`* packages, a call to `org-store-link` again used `org-ref-bibtex-store-link` as the default.
