### ISSUE TITLE
user-error: Before first headline at position 50 in buffer 20210209.org

### ISSUE THREAD

**Issue by borgauf** [jkitchin/org-ref#849]
I got this error

`user-error: Before first headline at position 50 in buffer 20210209.org`

when I tried to create a new entry today Feb 10. This cause the error message above, then it created a 20210210.org with two days' headers at the top: yesterday and today. What I didn't notice was it had completely moved everything out of 20210209.org and into 20210210.org. I absent-mindedly deleted (C-x k) this "wrong" 20210210.org . . . and lost permanently everything from yesterday since 20210209.org now was blank except for TITLE.

I've got "" for `org-journal-carryover-items` and here is my general config

```
(use-package org-journal
  :after org
  :custom
  (org-journal-dir "~/Dropbox/org/journal/")
  ;; (org-journal-date-prefix "#+TITLE: ")
  ;; (org-journal-time-prefix "* ")
  (org-journal-file-format "%Y/%m/%Y%m%d.org")
  ;; (org-journal-date-format "%Y-%m-%dT%H:%M:%S")
  (org-journal-date-format "%a, %Y-%m-%d")
  (org-journal-enable-agenda-integration t)
  :bind
  ("C-c j" . org-journal-new-entry)
  :config
  (add-hook 'org-journal-mode-hook (lambda () (company-mode -1))))

(defun org-journal-file-header-func (time)
  "Custom function to create journal header."
  (concat
    (pcase org-journal-file-type
      (`daily "#+TITLE: Daily Journal\n#+STARTUP: showeverything")
      (`weekly "#+TITLE: Weekly Journal\n#+STARTUP: folded")
      (`monthly "#+TITLE: Monthly Journal\n#+STARTUP: folded")
      (`yearly "#+TITLE: Yearly Journal\n#+STARTUP: folded"))))

(setq org-journal-file-header 'org-journal-file-header-func)
```

I was getting this yesterday while trying C-c j as well. Temp solution was to move the previous days' files out of `.../journal/2021/02/` and have 20210209.org be the only file in the directory. My only guess is something wasn't really right about the `org-journal-carryover-items` which, when I looked at it in my `custom-set-variables` elisp file had

`(org-journal-carryover-items "\"\"")`

possibly from using the customize feature. I wanted it off completely, but maybe it was going rouge?

**Comment by jkitchin** [comment]
I don't see anything about org-ref in the description above. Do you suspect org-ref is doing something here?

**Comment by borgauf** [comment]
I'm so sorry! This was meant for org-journal.

**Comment by jkitchin** [comment]
whew!  I was wondering how we were going to debug that in org-ref!
