### ISSUE TITLE
melpa version: org-ref-get-bibtex-key-and-file error - multiple citations

### ISSUE THREAD

**Issue by miguelazo82** [jkitchin/org-ref#85]
Have just changed to melpa version: 

I can open simple citations as always. But when having several citations like so: 
citep:Bailey-96-Diseasesunderconservation,Sturz-97-reviewplantdisease
I get the error message
org-ref-get-bibtex-key-and-file: Wrong type argument: stringp, nil
when trying to open the link with open org-open-at-point 

Another very minor problem: org-ref is not fully functional at emacs startup. 
I need to load it with (require 'org-ref) to work from the start  (should not be necessary when installed from package management, no?)

**Comment by jkitchin** [comment]
thanks for reporting this. I just pushed a fix for it. It may take 4 hours or more until it shows in melpa.

I think you still have to require org-ref. I am not sure it should always work just because it was installed from package management. At least for me, I also still have to require it.

**Comment by miguelazo82** [comment]
Works again, thank you very much!
