### ISSUE TITLE
Insertion of references using `org-insert-link` always defaults to `ref:`-link

### ISSUE THREAD

**Issue by chemmi** [jkitchin/org-ref#856]
Hi John,

I noticed that the insertion of references using `org-insert-link` always defaults to `ref:`-links. Even if I interactively choose `cref`, `autoref`, etc. This is due to the usage of [`org-ref-complete-link`](https://github.com/jkitchin/org-ref/blob/32803203cc4b01e1d4436f0f65138bf569dad8ad/org-ref-core.el#L1702) as completion function for all these kinds of links, which defaults to a customized default value of the link type. A special case are only equation references.

This can be fixed by changing completion functions for the different link types at the link registration. In the case of `cref`, the link is registered [here](https://github.com/jkitchin/org-ref/blob/32803203cc4b01e1d4436f0f65138bf569dad8ad/org-ref-core.el#L2198).

In my custom configuration, I fixed this issue by defining a generic completion function which takes the link type as argument. Maybe something like this could be implemented in the code base itself. I could write a PR for this, although I do not know in which cases you want to keep the link type inference for equations or default link type.

Here is the code from my configuration which fixes this issue in my local setup after loading `org-ref`.

```lisp
  ;; Fix Link insertion for ref links

  (defun org-ref-generic-complete-link (ref-type &optional arg)
    "Generic completion function for ref links.
Optional argument ARG Does nothing."
    (let ((label))
      (setq label (completing-read "label: " (org-ref-get-labels)))
      (format "%s:%s" ref-type label)))

  (org-ref-link-set-parameters "cref"
    :complete (lambda (&optional arg) (org-ref-generic-complete-link "cref" arg)))

  (org-ref-link-set-parameters "Cref"
    :complete (lambda (&optional arg) (org-ref-generic-complete-link "Cref" arg)))

  (org-ref-link-set-parameters "autoref"
    :complete (lambda (&optional arg) (org-ref-generic-complete-link "autoref" arg)))

  (org-ref-link-set-parameters "nameref"
    :complete (lambda (&optional arg) (org-ref-generic-complete-link "nameref" arg)))

  (org-ref-link-set-parameters "pageref"
    :complete (lambda (&optional arg) (org-ref-generic-complete-link "pageref" arg)))
```

Best regards and stay healthy,
Christian

**Comment by jkitchin** [comment]
I am not sure I understand what you are describing. For me, to insert a ref link, that is say a cref, I do the following:

C-u C-c ]
select a label
C-u return
select the type
return to insert it. This does the right thing.

Are you referring to using C-c C-l to insert a ref? I do see that behavior there, but I have to confess I never insert links this way.

your solution is the only one I see as practical at the moment. The inference function only serves to create an eqref for equations at the moment.

**Comment by chemmi** [comment]
Hi, thanks for the quick reply!

You got it right. I want to insert ref/cref/... links interactively using C-c C-l (org-insert-link). At the moment, this does not work as expected for non-"ref" links. It always inserts the default ref:... instead of e.g. cref:... . This is because the same completion function is registered for all these link types.
Actually for pageref-links there is a different function registered, which [also generates a ref-link](https://github.com/jkitchin/org-ref/blob/32803203cc4b01e1d4436f0f65138bf569dad8ad/org-ref-core.el#L2103). This looks wrong to me.

I will write a PR to register the "hard-coded" link types as in the config snippet above. Since it is required to choose eqref-links and other link types (cref, autoref, nameref, ...) explicitly with org-link-insert, there is no need for type inference. So I would drop the type inference for the org-ref-complete-link, i.e. org-ref-infer-ref-type. org-ref-complete-link is used solely for the org-link registration.
