### ISSUE TITLE
`doi-utils-add-bibtex-entry-from-doi` fails with some doi.

### ISSUE THREAD

**Issue by smallzhan** [jkitchin/org-ref#86]
Nice tool. 
when I fetch a bibtex with doi, it fails with args-out-of-range ...
the problem DOI is "10.1109/WI-IAT.2009.142"

**Comment by jkitchin** [comment]
The problem with that doi is there was no month listed in the json issued date. I just pushed a fix so org-ref ignores that. Thanks for reporting it.

**Comment by smallzhan** [comment]
It works! thank you again for your working.

**Comment by jkitchin** [comment]
You are welcome! Thanks again for reporting the issue.
