### ISSUE TITLE
url of arXiv bibtex entries should not point to specific versions

### ISSUE THREAD

**Issue by JesusTorrado** [jkitchin/org-ref#860]
Hi @jkitchin et al,

The official arXiv API returns url's containing the e-print version, e.g.

    http://arxiv.org/api/query?id_list=2005.05290

returns as `<entry><id>` the url `http://arxiv.org/abs/2005.05290v1`. This points to a particular version of the e-print, but authors usually upload an update at some point later, usually matching the published version. The url pointing always to the last version would be the same one, except for the last `v[number]`, e.g. `http://arxiv.org/abs/2005.05290`.

I guess there is some advantage to pointing to a specific url instead of a redirection in some cases, but for org-ref purposes, I'd say it makes more sense to use in the bibtex the general one, or one risks getting pointed to an obsolete version missing important changes when visiting the url, and so do the people reading a paper whose bibliography has been generated with org-ref (and prints the url as per the bibliography style).

This could be done as simply as: (pardon my beginner's elisp)

    (defun arxiv-url-trim-version (arxiv-url)
        (substring arxiv-url 0 (string-match "v+[0-9]" arxiv-url)))

Is there any chance this could be added upstream (within `arxiv-get-bibtex-entry-via-arxiv-api`)? If so, I can write a PR.

**Comment by jkitchin** [comment]
I guess my preference is to keep the version number in the url, since you don't know in advance what would change in subsequent versions. The changes could be minor or major, even with different data, etc. The risk of pointing only to the most recent one is that the key point you reference may be gone or changed.

**Comment by JesusTorrado** [comment]
Ok, I understand, thanks!

Do you think this is relevant enough to turn it into a customizable option? Or at least setting the url value at https://github.com/jkitchin/org-ref/blob/master/org-ref-arxiv.el#L133 via some trivial function that can be redefined in someone's `init.el` without having to redefine the whole `arxiv-get-bibtex-entry-via-arxiv-api`? (or maybe there is an even easier way that I don't know of...)

**Comment by jkitchin** [comment]
Looking at the function, I don't see a much easier way than just redefining it. These days, what I do is define a new function that does what I want, and then use an override advice to replace it.

see https://github.com/jkitchin/scimax/blob/master/scimax-org-images.el#L175 for an example

**Comment by JesusTorrado** [comment]
Thanks! That's what I am doing at the moment, but it does not get along with updates (though the arXiv API is not expected to change often).

In any case, I guess an alternative upstream would be defining `(defun arxiv-postprocess-url (arxiv-url) arxiv-url)` and then 
changing that line to `(url (arxiv-postprocess-url (nth 2 (assq 'id entry))))`. Would that work/make-sense?

**Comment by jkitchin** [comment]
I think the best approach is to add a hook function to  `org-ref-clean-bibtex-entry-hook` which would clean the url as you want. This would require no modification to org-ref or advice.

**Comment by JesusTorrado** [comment]
Yeah, that sounds like the most reasonable way to do it. Thanks a lot, also for developing and maintaining this amazing package!
