### ISSUE TITLE
org-ref-helm-insert-cite-link fails after upgrading to emacs 28

### ISSUE THREAD

**Issue by uliw** [jkitchin/org-ref#862]
Calling org-ref-helm-insert-cite-link fails with Wrong type argument: stringp, nil

Invoking org-ref shows no apparent problems

subsequent invocation org-ref-helm-insert-cite-link brings up the list of bib entries, however trying to select one by typing the first letter, throws an error

with "Helm issued errors: helm-match-from-candidates in source `Bibtex entries': wrong-type-argument (buffer-or-string-p (=has-pdf= . #) )]

Restarting emacs and 
calling helm-bibtex fails the first time around with Wrong type argument: stringp, nil. After executing org-ref

helm-bibtex works just fine

This problem appeared after upgrading to emacs 28.

**Comment by uliw** [comment]
This was related to @https://github.com/jkitchin/org-ref/issues/606.  Bibtex strings now need to conform to @string{ } rather than @string( ). I though I fixed that long ago

**Comment by AtomicNess123** [comment]
Am I correct that org-ref-helm-insert-cite-link does not exist as a function anymore?

**Comment by jkitchin** [comment]
I guess you are looking for `org-ref-cite-insert-helm` which is for inserting citations.
