### ISSUE TITLE
How to add a bibliography link to export references to PDF with LaTeX?

### ISSUE THREAD

**Issue by j-steinbach** [jkitchin/org-ref#863]
I am trying to export my .org file as Latex-PDF with citation. 

The [documentation](https://github.com/jkitchin/org-ref/blob/master/org-ref.org#citations) says

> org-ref uses the bibliography link to determine which bibtex files to get citations from, and falls back to the bibtex files defined in the variable reftex-default-bibliography or org-ref-default-bibliography if no bibliography link is found. **Note that you must include a bibliography link in your document if you are exporting your document to pdf;** org-ref-default-bibliography is not used by the LaTeX exporter.

The bold part links to [here](https://github.com/jkitchin/org-ref/blob/master/bibliography%20link), which does not exist.

Now I don't know how to add the required _bibliography link_ to correctly export my PDF.

**Comment by jkitchin** [comment]
That link really only works in org-mode; for some reason github cannot render it correctly. It should go to https://github.com/jkitchin/org-ref/blob/master/org-ref.org#references.

you just need something like:
```
bibliographystyle:your-preferred-style
bibliography:your-bibfile.bib
```

**Comment by j-steinbach** [comment]
Great! 

(As this solves my issue I am going to close it)

---

Should I open a new issue for the wrong links in the documentation? But I think it only affects 3-4 links

**Comment by jkitchin** [comment]
I would not open a new issue for the links. The problem is in Github, not the links. They work fine in the org files, but github does not render them correctly. There isn't a way to fix them that also works in the org files.
