### ISSUE TITLE
org-ref-open-notes-at-point not working

### ISSUE THREAD

**Issue by swhalemwo** [jkitchin/org-ref#865]
Hi, thanks for this great piece of software, it has made managing my literature a dream. Recently however I've encountered a bug: I can't run `org-ref-open-notes-at-point` anymore to open an entry's notes. I'm getting the following error: 

```
Debugger entered--Lisp error: (wrong-type-argument listp "some_bibtex_key")
  bibtex-completion-edit-notes-default("some_bibtex_key")
  bibtex-completion-edit-notes("some_bibtex_key")
  org-ref-notes-function-many-files("some_bibtex_key")
  org-ref-open-notes-at-point()
  funcall-interactively(org-ref-open-notes-at-point)
  call-interactively(org-ref-open-notes-at-point nil nil)
  command-execute(org-ref-open-notes-at-point)
```

It seems to me that `bibtex-completion-edit-notes-default` expects a list, but `org-ref-notes-function-many-files` provides the key as a string (I tried encapsulating the key in a list myself, but this only resulted in more errors). I think it's an org-ref issue since I still can open notes of articles in `helm-bibtex` (f9). This is my config: 

```
(use-package bibtex-completion
    :config
    (setq bibtex-completion-bibliography '("/home/myname/Dropbox/references.bib"))
    (setq bibtex-completion-cite-default-as-initial-input t)
    (setq bibtex-completion-format-citation-functions
	  '((org-mode . org-ref-bibtex-completion-format-org)
	  (latex-mode . bibtex-completion-format-citation-cite)
	  (default . bibtex-completion-format-citation-cite)))
    (setq bibtex-completion-library-path '("/home/myname/Dropbox/readings"))
    (setq bibtex-completion-notes-template-multiple-files "* ${author-or-editor} (${year}): ${title}")
    (setq bibtex-completion-pdf-open-function 'helm-open-file-with-default-tool)
    (setq bibtex-completion-notes-path "/home/myname/Dropbox/nootes")
    )

;; *** org-ref
(use-package org-ref
    :ensure t
    :config
    (setq org-ref-notes-directory "/home/myname/Dropbox/nootes")
    (setq org-ref-bibliography-notes  "/home/myname/Dropbox/notes/notes.org")
    (setq org-ref-default-bibliography '("/home/myname/Dropbox/references.bib"))
    (setq org-ref-pdf-directory "/home/myname/Dropbox/readings")
    (setq org-ref-completion-library 'org-ref-helm-bibtex)
    (setq org-ref-notes-function 'org-ref-notes-function-many-files)

    (setq reftex-cite-format
          '((?c . "\\cite[]{%l}")
            (?f . "\\footcite[][]{%l}")
            (?t . "\\textcite[]{%l}")
            (?p . "\\parencite[]{%l}")
            (?o . "\\citepr[]{%l}")
            (?n . "\\nocite{%l}")))
    )
```
Cheers!

**Comment by tshu-w** [comment]
I also encountered this problem, but I changed `org-ref-notes-function-many-files` to pass a list and it worked fine. 

```emacs-lisp
(defun org-ref-notes-function-many-files (thekey)
  "Function to open note belonging to THEKEY.
Set `org-ref-notes-function' to this function if you use one file
for each bib entry."
  (let* ((bibtex-completion-bibliography
          (cdr (org-ref-get-bibtex-key-and-file thekey)))
         (bibtex-completion-notes-path org-ref-notes-directory))
    (bibtex-completion-edit-notes (list thekey))))
```

@swhalemwo here is my [org-ref config](https://github.com/tshu-w/.emacs.d/blob/master/lisp/lang-org.el#L864) for references

**Comment by swhalemwo** [comment]
thanks for the suggestion! with your proposed change it does work for org-ref entries for which I already have notes, but it doesn't work completely for ones where there is no notes file yet. when org-ref was normally working, the note file was created, and the title was inserted when opening it from the org-ref link. Now the note file is opened, but no title is inserted, and I get the following error (the problem to me seems to be that no content is found for the key, which is why the parsing fails): 


    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
      string-match(" and " nil 0)
      split-string(nil " and " t)
      s-split(" and " nil t)
      bibtex-completion-apa-format-editors(nil)
      bibtex-completion-apa-get-value("author-or-editor" (("year" . "")))
      #f(compiled-function (md) #<bytecode 0x1567f8a01069>)("${author-or-editor}")
      replace-regexp-in-string("\\$\\({\\([^}]+\\)}\\|[0-9]+\\)" #f(compiled-function (md) #<bytecode 0x1567f8a01069>) "* ${author-or-editor} (${year}): ${title}" t t)
      s-format("* ${author-or-editor} (${year}): ${title}" bibtex-completion-apa-get-value (("year" . "")))
      bibtex-completion-fill-template((("year" . "")) "* ${author-or-editor} (${year}): ${title}")
      bibtex-completion-edit-notes-default(("some_bibtex_key"))
      bibtex-completion-edit-notes(("some_bibtex_key"))
      (let* ((bibtex-completion-bibliography (cdr (org-ref-get-bibtex-key-and-file thekey))) (bibtex-completion-notes-path org-ref-notes-directory)) (bibtex-completion-edit-notes (list thekey)))
      org-ref-notes-function-many-files("some_bibtex_key")
      funcall(org-ref-notes-function-many-files "some_bibtex_key")
      org-ref-open-notes-at-point()
      eval((org-ref-open-notes-at-point) t)
      eval-expression((org-ref-open-notes-at-point) nil nil 127)
      funcall-interactively(eval-expression (org-ref-open-notes-at-point) nil nil 127)
      call-interactively(eval-expression nil nil)
      command-execute(eval-expression)
    
I have also come up with a "bandaid" that works for me for now:

    (defun org-ref-open-notes-at-point-bandaid ()
        (interactive)
        (bibtex-completion-edit-notes-default (list (org-ref-get-bibtex-key-under-cursor)))
        )

**Comment by tshu-w** [comment]
> with your proposed change it does work for org-ref entries for which I already have notes, but it doesn't work completely for ones where there is no notes file yet.

I didn't have this problem, anyway, glad to see you solved it.

**Comment by jkitchin** [comment]
I have pushed a fix to use a list for the bibtex-completion function.  I guess the last error you are seeing is due to an error in your bibtex entry, perhaps the year or editors is missing?

```
 bibtex-completion-apa-format-editors(nil)
  bibtex-completion-apa-get-value("author-or-editor" (("year" . "")))
```

**Comment by thriveth** [comment]
I found this issue on Google, I have just run into this problem too, seems to have come up in a recent update or something - a week ago or so, it all worked fine, but now, when using the org-ref hydra to get to an article note, I get the following error (from debug-on-error):

``` elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  insert-file-contents(nil)
  org-ref-get-bibtex-entry("chisholm2018a")
  org-ref-notes-function-one-file("chisholm2018a")
  org-ref-open-notes-at-point()
  funcall-interactively(org-ref-open-notes-at-point)
  call-interactively(org-ref-open-notes-at-point)
  hydra--call-interactively-remap-maybe(org-ref-open-notes-at-point)
  org-ref-cite-hydra/org-ref-open-notes-at-point-and-exit()
  funcall-interactively(org-ref-cite-hydra/org-ref-open-notes-at-point-and-exit)
  call-interactively(org-ref-cite-hydra/org-ref-open-notes-at-point-and-exit nil nil)
  command-execute(org-ref-cite-hydra/org-ref-open-notes-at-point-and-exit)
```

I don't really know what I can do about it and I am quite dependent on this feature.
