### ISSUE TITLE
Within the .bib file, open PDF files in child directories (using the Hydra-p).

### ISSUE THREAD

**Issue by jiucenglou** [jkitchin/org-ref#867]
Following the customization shown in #172, one can open the PDF file associated with a citing link even when the PDF file resides in a child directory. However, this trick only works within the citing .org file. Within the .bib file, the `Hydra-p` command, triggered by `C-cj` within a bibtex entry, still cannot pick up PDF from child directories. It looks like `Hydra-p` runs `org-ref-open-bibtex-pdf`, which looks different from `org-ref-open-pdf-at-point`. Could you consider providing a `my/org-ref-open-bibtex-pdf` that functions similarly to `my/org-ref-open-pdf-at-point` in #172, and revise `Hydra-p` to use it ?

The `my/org-ref-open-pdf-at-point` in #172 is shown below

```elisp
(setq org-ref-open-pdf-function              'my/org-ref-open-pdf-at-point)
(defun my/org-ref-open-pdf-at-point ()
"Open the pdf for bibtex key under point if it exists."
   (interactive)
   (let* ((results (org-ref-get-bibtex-key-and-file))
          (key (car results))
          (pdf-file (funcall org-ref-get-pdf-filename-function key))
          (pdf-other (bibtex-completion-find-pdf key)) )
      (cond ((file-exists-p pdf-file) (org-open-file pdf-file))
            (pdf-other                (org-open-file (car pdf-other)) )
            (message "No PDF found for %s" key) ) ) )
```

**Comment by jiucenglou** [comment]
The following code can be used to [open the .pdf file, residing within specified child directories, associated with a bibtex entry within a .bib file with a key binding](https://github.com/tmalsburg/helm-bibtex/issues/365#issuecomment-798834534).

```elisp
   ; [[https://github.com/tmalsburg/helm-bibtex/issues/121][Open PDF for bib entry containing point]] and 
   ; [[https://github.com/tmalsburg/helm-bibtex/issues/169][wrap bibtex-key-in-head with the list function]]
   (defun bibtex-completion-open-pdf-of-entry-at-point ()
      (interactive)
      (save-excursion
         (bibtex-beginning-of-entry)
         (when (looking-at bibtex-entry-maybe-empty-head)
            (bibtex-completion-open-pdf (list (bibtex-key-in-head)) ) ) ) )
   ; [[https://github.com/plantarum/bibtex-utils][bind the function to a key]]
   (eval-after-load 'bibtex
      '(define-key bibtex-mode-map (kbd "H-p") 'bibtex-completion-open-pdf-of-entry-at-point))
```

Could you consider revising `Hydra-p` to use it ?

**Comment by jkitchin** [comment]
in the bibtex file, it looks like you need  `org-ref-get-pdf-filename-function` to be set to a function that can compute the path of the pdf that corresponds to the key for that entry.

`org-ref-open-pdf-function` is only for opening a pdf from a link.
