### ISSUE TITLE
Arxiv add bib entry not accurate and does not include DOI term

### ISSUE THREAD

**Issue by ctian282** [jkitchin/org-ref#869]
For example, if I simply import this arxiv paper https://arxiv.org/abs/hep-th/9503124 through arxiv-add-bibtex-entry, it inserts the following entry

>@article{witten95_strin_theor_dynam_various_dimen,
    author = {Witten, Edward},
    title = {String Theory Dynamics in Various Dimensions},
    journal = {CoRR},
    year = 1995,
    url = {http://arxiv.org/abs/hep-th/9503124v2},
    abstract = {The strong coupling dynamics of string theories in dimension $d\geq 4$ are studied. It is argued, among
                other things, that eleven-dimensional supergravity arises as a low energy limit of the ten-dimensional
                Type IIA superstring, and that a recently conjectured duality between the heterotic string and Type IIA
                superstrings controls the strong coupling dynamics of the heterotic string in five, six, and seven
                dimensions and implies $S$ duality for both heterotic and Type II strings.},
    archiveprefix = {arXiv},
    eprint = {hep-th/9503124},
    primaryclass = {hep-th},
}

It does not give correct journal, and it does not include a DOI. Actually, it would be almost perfect if the org-ref just simply copy-and-paste from BibTeX information given by arxiv directly, which is 
>@article{Witten_1995,
   title={String theory dynamics in various dimensions},
   volume={443},
   ISSN={0550-3213},
   url={http://dx.doi.org/10.1016/0550-3213(95)00158-O},
   DOI={10.1016/0550-3213(95)00158-o},
   number={1-2},
   journal={Nuclear Physics B},
   publisher={Elsevier BV},
   author={Witten, Edward},
   year={1995},
   month={Jun},
   pages={85–126}
}

This entry contains correct journal information, and with a DOI. Another approach could be importing from DOI plus an arxiv entry for published paper from a arxiv link, and keep this way for unpublished paper.

**Comment by jkitchin** [comment]
It does look like this can be improved.  I think the best thing to do is if there is a doi, then use that to retrieve the bibtex entry. I don't know how to get the bibtex entry directly from arxiv though. Many arxiv entries don't have a doi though, so it should fall back to what is currently done I think.
