### ISSUE TITLE
`org-ref-clean-bibtex-entry` fails

### ISSUE THREAD

**Issue by bixuanzju** [jkitchin/org-ref#87]
For the following bibtex entry
```
@inproceedings{dunfield-2012-elabor,
	doi = {10.1145/2364527.2364534},
	url = {http://dx.doi.org/10.1145/2364527.2364534},
	year = 2012,
	publisher = {Association for Computing Machinery ({ACM})},
	author = {Joshua Dunfield},
	title = {Elaborating intersection and union types},
	booktitle = {Proceedings of the 17th {ACM} {SIGPLAN} international conference on Functional programming - {ICFP} {\textquotesingle}12}
}
```
Below is the debugger info
>Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  org-ref-clean-bibtex-entry(nil)
  call-interactively(org-ref-clean-bibtex-entry record nil)
  command-execute(org-ref-clean-bibtex-entry record)
  helm-M-x(nil "org-ref-clean-bibtex-entry")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by jkitchin** [comment]
thanks for reporting this. I have pushed a fix that should address it.

**Comment by bixuanzju** [comment]
Thanks! Confirmed fixed.

**Comment by jkitchin** [comment]
great. Thanks.
