### ISSUE TITLE
Integration with emacs-application-framework

### ISSUE THREAD

**Issue by Jdogzz** [jkitchin/org-ref#870]
It would be nice if org-ref could integrate with the package emacs-application-framework: [https://github.com/manateelazycat/emacs-application-framework](https://github.com/manateelazycat/emacs-application-framework)

I've just started to set up my org-ref install and I noticed that the function org-ref-pdf-to-bibtex errors out when called while a PDF is displayed using emacs-application-framework in a buffer.

**Comment by jkitchin** [comment]
That is not a very helpful report, what is the error?

**Comment by Jdogzz** [comment]
My apologies, I had seen the relevant function was written specific to pdf-tools and just wanted to convey it didn't work directly with EAF as a drop in replacement, very understandable: [https://github.com/jkitchin/org-ref/blob/master/org-ref-pdf.el#L122](https://github.com/jkitchin/org-ref/blob/master/org-ref-pdf.el#L122)

Specifically, the error I experienced was `Wrong type argument: char-or-string-p, nil` and this was the debug log:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  org-ref-pdf-to-bibtex()
  funcall-interactively(org-ref-pdf-to-bibtex)
  call-interactively(org-ref-pdf-to-bibtex record nil)
  command-execute(org-ref-pdf-to-bibtex record)
  execute-extended-command(nil "org-ref-pdf-to-bibtex" nil)
  funcall-interactively(execute-extended-command nil "org-ref-pdf-to-bibtex" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by jkitchin** [comment]
That debug log is weird to me, notably `call-interactively(execute-extended-command nil nil)` which is where I guess the problem is. I don't know what EAF does, or why it would fail like this though.
