### ISSUE TITLE
doi-utils-get-bibtex-entry-pdf bug in new version?

### ISSUE THREAD

**Issue by wxding84** [jkitchin/org-ref#873]
when called, emacs returns something like void symbol org-ref-get-bibtex-pdf-filename
it seems in the doi-utils-get-bibtex-entry-pdf  function, one needs to modify
(setq pdf-file (funcall org-ref-get-bibtex-pdf-filename key)) 
to 
(setq pdf-file (org-ref-get-bibtex-pdf-filename key)) 

to fix the issue

not sure if reproducible for other people. the fix works for me. please verify.

**Comment by jkitchin** [comment]
That is a bug, it should be a variable name there, not the function. It should be fixed in 3fff9da.
