### ISSUE TITLE
org-ref-update-pre-post-text deletes the first following character

### ISSUE THREAD

**Issue by lazzalazza** [jkitchin/org-ref#877]
I'm using org-ref 20210324.1337.

Given this example:

> cite:foobar2009a  ; etc.

whenever i use **org-ref-update-pre-post-text** to complete the reference, the command wrongly deletes the first following punctuation sign (in the example, the semicolumn). I then end up with:

> [[cite:foobar2009a][293-294]] etc.

Maybe there's a reason for this behaviour and I simply don't get it.

**Comment by jkitchin** [comment]
huh. How do you use this function?  I see it in the code, but it is not an interactive function, and doesn't seem to be used anywhere.  I guess that is expected looking at the end of the code,  at the end it deletes punctuation. I don't recall why that makes sense to do though.

**Comment by lazzalazza** [comment]
Well, isn't it called by org-ref-cite-candidates? I use it simply to complete quotations without having to manually add the square brackets, but I can't honestly see why the following punctuation has to be removed...

**Comment by jkitchin** [comment]
you are right, it is called there in the helm bibtex backend.  I pushed a change to remove the last one in that function. There is still another place where punctuation is deleted though, so this commit might not fix the issue completely.

**Comment by lazzalazza** [comment]
thank you so much! let's see if it works this way...
