### ISSUE TITLE
Some links don't display with the abbreviated form

### ISSUE THREAD

**Issue by mohkale** [jkitchin/org-ref#880]
I've found that some org-ref links when inserted through `org-insert-link` in the classic form of `[[link][desc]]` show up as is instead of as only `desc`.

For example in this simple document, the bibliography link shows up as its description, the bibliographystyle link shows up as the link (because it has no description, the label link shows up as plaintext instead of an org link. The cite link isn't inserted as a propper org link (as described above) however when it is it also appears like the label link.

```org
#+TITLE: Hello world

hello cite:71powell-anarchist-cookbook,19eck-understanding-flaky-tests.

#+caption: Another. [[label:blarg][hello]].
| y |
| 4 |
| 5 |

reference [[ref:blarg][blarg]].

[[bibliographystyle:unsrt]]
[[bibliography:.config/emacs/org/bib/archive.bib,.config/emacs/org/bib/unibooks.bib][bibliography]]
```

![Screenshot_20210525_190130](https://user-images.githubusercontent.com/23294780/119546510-e67d3080-bd8b-11eb-8836-3d47c656f91c.png)

**Comment by jkitchin** [comment]
I think only cite links are treated differently when [description] is used. That is because the description is used for pre/post text, unlike other types of links.

**Comment by mohkale** [comment]
@jkitchin 

I see, can you explain why the label link doesn't get abbreviated?

**Comment by jkitchin** [comment]
I guess because it is in the caption. If you put it somewhere else, it shows the same as the other links. you don't need a description for the label link, or for a ref link, why do you want to use them there?

**Comment by mohkale** [comment]
@jkitchin 

You're correct, as for why there's a description I'm just experimenting with org-ref atm and seeing how all the different link types work and are treated by the export system :smile:.

That answers most of my questions and issues. Thank you.
