### ISSUE TITLE
BiBLaTeX 'ids' fields

### ISSUE THREAD

**Issue by spacekitteh** [jkitchin/org-ref#882]
So, recent-ish versions of BibLaTeX support a field "ids", where you list citation key aliases. Org-ref doesn't pick up cite links to those fields. It would be a very nice feature to have!

**Comment by jkitchin** [comment]
I think I am waiting to see how the new org cite syntax works out before making any further changes to org-ref.

**Comment by spacekitteh** [comment]
Fair, plus I suspect it would be something that should go into bibtex.el anyway

**Comment by jkitchin** [comment]
I am going to close this. I am working on a new version of org-ref that uses bibtex-completion for the candidates. That is where all the valid keys will be defined from. If that library supports "ids" as candidates, it will be automatically supported in org-ref.
