### ISSUE TITLE
Org-cite refactor possibilities

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref#883]
@johnrkitchin - I know you're unlikely to get to this for awhile, but I just thought I'd put this issue here for possible later reference, while I'm thinking of the details (I'll likely have to wind down my focus on this very soon).

This picks up the thread started here: https://github.com/jkitchin/org-ref/issues/876#issuecomment-848940765.

## org-cite design

`Org-cite` (OC) is designed around flexible and modular "capabilities"; currently:

- _activate_
- _follow_
- _insert_
- _export_

While still TBD, It is possible one of those capabilities will also be (in-buffer, at-point) _completion_.

One configures those processors like so:

``` elisp
(setq org-cite-activate-processor 'basic)
```

So, for example, in a future in which `org-ref` becomes, say, a "follow processor", one might set it like so:

``` elisp
(setq org-cite-follow-processor 'org-ref)
```

## A modular approach?

The different emacs packages that provides action functions for citations take a list of keys, and do something with them. So this has me wondering: 

Is it feasible to have a "follow" processor that is designed to be modular from the beginning, where users could mix-and-match action functions from different packages (`org-ref`, `bibtex-completion`, etc)?

I know the devil-is-in-the-details here (particularly the UI), but think it's worth considering.

cc @tmalsburg

**Comment by jkitchin** [comment]
I am not sure how you can insert practically without completion. This is modular in org-ref through the variable `org-ref-insert-cite-function`. You set that to what you want, and that function provides the completion if you want it. there are some "backends" in org-ref to choose different functions like revtex, helm-bibtex, a different helm backend and an ivy backend I wrote.

org-ref is modular as described above by setting the `org-ref-cite-onclick-function` variable to be the function you want to run. I use a hydra for that, but you can make it be whatever you want, a transient, some embark function, some bibtex-completion function, etc. The different backends also define defaults for this, but it has always been customizable. It is not sufficient IMO to take a list of keys though, it should take a key which is the one you want to follow (e.g. in a cite with multiple keys I don't usually want to do something on all the keys, just on one). Maybe you could make it take a prefix arg to toggle between the key at point vs the full list.

I am not sure what I see as the future of org-ref in this space now.  I am not going to decide what the future of org-ref is until after oc is integrated into org-mode and I can see what it is capable of. It sounds like most of org-ref will be obsolete, and can be replaced by other packages.

**Comment by bdarcus** [comment]
> I am not sure how you can insert practically without completion.

Sorry; should have been more clear: I meant in-buffer at-point completion. The "insert" function added to `oc-basic` uses `completing-read`.

I'll edit main post.

> It sounds like most of org-ref will be obsolete, and can be replaced by other packages.

That's possible. Then the question would be what functions are uniquely valuable in `org-ref`?

But as you say, a question to think about more later.

**Comment by jkitchin** [comment]
I think most of the cite capability will be obsolete, and would have to be completely rewritten to use the oc syntax. At the moment they all rely on link syntax and machinery to get things. There won't be a need for any of the cite links, font locking, etc. nor a need for any of the insertion mechanisms. Maybe there are some things like using shift arrows to reorganize cites, but these won't work without rewriting completely. some of the functions that act on a key might be valuable, e.g. finding related articles in Scopus/WOS/google scholar, but none are really crucial. 

I don't know how to support that though, it will be a major breaking change for users. Maybe there will be a final stable version tagged for MELPA stable, and a future version 3 or something that uses the new syntax, and that removes most of the backend stuff. It might be more obvious what is valuable when I see what is left.

**Comment by bdarcus** [comment]
From my perspective, it is totally fine for you to close this issue.
It's been superseded by subsequent development.
