### ISSUE TITLE
Wrong type argument: listp with org-ref-cite-candidates on thesis entry type

### ISSUE THREAD

**Issue by ahmed-shariff** [jkitchin/org-ref#886]
This seems to be introduced in #864 (#861)

The `bibtex-completion-bibliography` is treated as a list in `bibtex-completion-bibliography` at: https://github.com/jkitchin/org-ref/blob/8aa2bb45268f660956151547533689d4ec30378d/org-ref-helm-bibtex.el#L448
but according to documentation it's a string?

This causes issues when trying to open some entry types.

**Comment by ahmed-shariff** [comment]
@emacsbliss was there a reason to treat that as a list?

**Comment by jkitchin** [comment]
This is definitely buggy code.  `bibtex-completion-bibliography` can be a string or a list. I think the commit above should fix this.
