### ISSUE TITLE
org-ref-pdf-to-bibtex setting the file field?

### ISSUE THREAD

**Issue by Ieremies** [jkitchin/org-ref#889]
So, I'm trying to set org-ref, but many things are not working as I expect it to do so. That's ok, I'm figuring it out as I go. But one thing I just cannot find any reference on how to do it: when using `org-ref-pdf-to-bibitex` it does add a nice well formatted bibtex entry to my .bib file, but it does not link to the .pdf where I invoked it. Is there a way to do so?

Just to make my problem clear. Lets say I am in a file called "My article - Random Person.pdf" and I want to add it to my bib file. So I do `org-ref-pdf-to-bibtex`, it inserts the correct entry, but it doesn't reference the file it came from, like in the `file` field. So I would like it to also add: `file = {My article - Random Person.pdf}` to the entry. How can I do this?

**Comment by jkitchin** [comment]
It looks like it will only be renamed if it is open using pdf-tools, and it will rename the pdf to key.pdf in the org-ref-pdf-directory. For anything else, you will have to do it manually.

**Comment by Ieremies** [comment]
I understand. It would be really nice to have it done automatically when using `org-ref-pdf-to-bibtex` in pdf-tools.
