### ISSUE TITLE
org-ref-helm-insert-cite-link opens file instead of inserting citation

### ISSUE THREAD

**Issue by inglada** [jkitchin/org-ref#89]
When calling org-ref-helm-insert-cite-link (either with M-x or with C-c ]), after the selection of the item with the helm menu, the citation is not inserted and the pdf file is open instead.

Tested with "emacs -Q -l org-conf.el" where the configuration file contains:

(require 'package)

(setq package-archives
      '(("org" . "http://orgmode.org/elpa/")
	("gnu" . "http://elpa.gnu.org/packages/")
	("melpa" . "http://melpa.org/packages/")))

(package-initialize)

(setq reftex-default-bibliography '("~/stok/Biblio/biblio.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "~/stok/Biblio/biblio-notes.org")
(setq org-ref-default-bibliography '("~/stok/Biblio/biblio.bib"))
(setq org-ref-pdf-directory "~/stok/Biblio/")

(setq helm-bibtex-bibliography "~/stok/Biblio/biblio.bib")
(setq helm-bibtex-library-path "~/stok/Biblio")

(setq helm-bibtex-pdf-open-function 'org-open-file)

(setq helm-bibtex-notes-path "~/stok/Biblio")

(require 'org-ref)
(require 'org-ref-latex)
(require 'org-ref-pdf)
(require 'org-ref-url-utils)

**Comment by jkitchin** [comment]
This suggests that the default action in helm-bibtex is to open the pdf. That is the default action, but org-ref should change that to insert citations. If you press tab, you can see all the actions. The order of actions should be defined here: https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L205

I haven't been able to reproduce your report.

**Comment by inglada** [comment]
I forgot to tell you that I am using the Melpa package.
If I press tab in the helm menu, I don't get the options defined in org-ref-helm-bibtex-actions. I get : open pdf, open url or doi in browser, insert reference, etc. but no insert citation.

Is there a way I can trace/debug what is being called?

Thank you.

**Comment by jkitchin** [comment]
I also tried the Melpa package, and it worked fine. What if you try emacs -q -l org-conf.el?
You may have an old org-ref installed that doesn't have that new rearrangement. You could try M-x find-library and enter org-ref to see which file comes up.

**Comment by inglada** [comment]
M-x find-library points to the melpa package (using the -q -l org-conf.el) and the behaviour is the same. I get the same thing when using the code from the git repo. By the way, I am using emacs built from source using a git checkout I did mid october.

**Comment by inglada** [comment]
I checked the value of helm-source-bibtex which I understand is updated using org-ref-helm-bibtex-actions, but it contains no action coming from org-ref-helm-bibtex-actions.

**Comment by inglada** [comment]
OK. I found something. The loop in https://github.com/jkitchin/org-ref/blob/master/org-ref.el#L225
does nothing in my emacs. If I remove the optional index of helm-add-action-to-source (i) everything's OK.

**Comment by inglada** [comment]
One more thing. If I make the change in org-ref.el, it does not work. I have to copy the loop (without the i) in my emacs configuration so that the actions are added after org-ref is loaded. I am aware that this is not a nice solution, but I don't know enough emacs lisp to understand what is happening.

But it works and it's OK for me. Thank you very much for this wonderful package.

**Comment by jkitchin** [comment]
Thanks for tracking this down! It is very strange. I wonder if this is some
helm issue. There was a time I had to do some hackery to add to a source
this way, but when I try this on what I think is a clean emacs (25+) it
works as expected for me.



John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
Would share exactly how you solved the problem? Thanks,

**Comment by inglada** [comment]
I just added the following lines after (require 'org-ref)

(loop for i from 0 to (length org-ref-helm-bibtex-actions)
      for ccell in org-ref-helm-bibtex-actions
      do
      (helm-delete-action-from-source (car ccell) helm-source-bibtex)
      (helm-add-action-to-source
       (car ccell)
       (cdr ccell)
       helm-source-bibtex
       ))

**Comment by jkitchin** [comment]
thanks!
