### ISSUE TITLE
(use-package org-ref) leads to compilation errors when installing packages

### ISSUE THREAD

**Issue by mlemerre** [jkitchin/org-ref#896]
For some times I had some weird errors when installing packages. I think it prevents .elc files to be produced.
I eventually decided to investigage and discovered that the culprit is a (use-package org-ref) line in my .emacs.

Steps to reproduce (emacs 27.1 started with emacs -q)

;; This does not produce any error
(package-initialize)
(package-install 'counsel) ;; Or reinstall if already installed; this is just one example

(use-package org-ref)

(package-reinstall 'counsel)

;; This produces the following error:
;; In toplevel form:
;; counsel.el:44:1:Error: Symbol's value as variable is void: seq
;; The corresponding line is just (require 'swiper)

Thanks for org-ref!

Matthieu

**Comment by mlemerre** [comment]
PS: I upgraded to org-ref 20210823.27 and the problem is still present; previously I used 202103something

**Comment by jkitchin** [comment]
I am not sure this is an org-ref problem, the error indicates an error in counsel.el right?

What is on line 44 of your counsel.el file?

**Comment by mlemerre** [comment]
The problem is not with counsel, because the problem also happens if I compile other packages.

The corresponding line is a (require 'swiper). Other compilation issues seem to be also (require ') lines.

Somehow loading org-ref with use-package does something that mess with compilation of these (require ) lines.

**Comment by mlemerre** [comment]
Actually it is not a problem of use-package; just (require 'org-ref) also make the problem appear.

**Comment by jkitchin** [comment]
weird. I can't reproduce this locally. Are there any other messages that indicate an error somewhere?

**Comment by mlemerre** [comment]
I tried to narrow the problem, and it happens when I load org-ref-helm. So
maybe helm is actually the culprit here: (require 'helm) also leads to the
error.

**Comment by mlemerre** [comment]
OK, it seems that org-ref loads helm, which calls (async-bytecomp-package-mode 1) at some point, which is the problem. So, probably not an org-ref specific issue (maybe it could avoid requiring helm if not needed)

**Comment by jkitchin** [comment]
I am removing helm in a future release, although if you use the helm backend for org-ref, it won't avoid the problem.

**Comment by averter** [comment]
+1 on this. I had to move all of the configuration from `:config` to `:init` (using use-package) otherwise org-ref does not load properly. My configuration includes `(require 'org-ref-helm)`.
