### ISSUE TITLE
2 ref links separated by en-dash -- impossible combination?

### ISSUE THREAD

**Issue by ebouna** [jkitchin/org-ref#898]
I would like to refer to a range of pages. So I tried to insert two pageref-links separated by an en-dash. This, however, does not work:

![grafik](https://user-images.githubusercontent.com/82314717/133906630-bf8d0737-a172-4728-a3f5-33eefccd526f.png)

Is there a work around? Is this a problem of org-ref? If it is, could it be made possible to make the combination of two pageref-links separated by an en-dash work? Many thanks for you help in advance.

**Comment by jkitchin** [comment]
you probably need to put each one in double brackets, i.e. [[pageref:s:d]]-[[pageref:ed:gb1940]].

**Comment by ebouna** [comment]
Thanks a lot. This works. Can one make enclosing in double brackets the
default behaviour for ref links in org-ref?

Am Sa., 18. Sept. 2021 um 21:49 Uhr schrieb John Kitchin <
***@***.***>:

**Comment by jkitchin** [comment]
I don't think that is a feature in the current branch.  I will look into adding it to org-ref-3 though.

**Comment by ebouna** [comment]
Many thanks for your help.

Am Montag, 20. September 2021 schrieb John Kitchin ***@***.***
