### ISSUE TITLE
Request for working org-ref setup

### ISSUE THREAD

**Issue by icymist** [jkitchin/org-ref#9]
Can I request for an example of a working org-ref setup to be placed on the github org-ref home page.

Thanks!

**Comment by jkitchin** [comment]
I put some comments on this in the README. Let me know if they work for you.

**Comment by FilippoC** [comment]
Is it possible to have installation instruction for raw Emacs 24, without using any startup kit ?
(I'm new to emacs)

Thanks

**Comment by jkitchin** [comment]
Those instructions should work without a startup kit. You have to put that code in your init.el file, there is no other way right now.

**Comment by FilippoC** [comment]
Thanks for your fast reply.
What do I do with the starter-kit-dir const ?

**Comment by jkitchin** [comment]
Put something like this at the top of that code
(setq starter-kit-dir "/absolute/path/to/.emacs.d")

or replace starter-kit-dir with "/absolute/path/to/.emacs.d" where that is the directory where the org-ref directory is.

**Comment by FilippoC** [comment]
I can launch emacs without error, but it don't seems that org-ref is loaded.

**Comment by jkitchin** [comment]
This isn't quite enough information to help you with. What do you have in init.el that you think should be loading org-ref?

**Comment by icymist** [comment]
I get an error (below) using the following orgref config. My org-ref is in `/home/chaitanya/.emacs.d/opt/org-ref`.

```
; orgref also requires helm
(require 'helm-config)
;(helm-mode 1)
(autoload 'helm-bibtex "helm-bibtex" "" t)
;(setq helm-bibtex-bibliography "~/ownCloud/work/mypapers/mynewrefs.bib")

(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt/org-ref")

;; remember this directory
(defconst starter-kit-dir (file-name-directory (or load-file-name (buffer-file-name)))
    "Directory where the starterkit is installed.")

;;;;;;; org path for loadable org-files
(defvar org-load-path
  (list (file-name-as-directory
         (expand-file-name "org" starter-kit-dir)))
  "List of directories to find org-files that `org-babel-load-file' can load code from.")

(defun org-require (feature)
  "Load a FEATURE from an org-file.
FEATURE is a symbol, and it is loaded from an org-file by the name of FEATURE.org, that is in the `org-load-path'.  The FEATURE is loaded from `org-babel-load-file'."
  (let ((org-file (concat (symbol-name feature) ".org"))
        (path))

    ;; find the org-file
    (catch 'result
      (loop for dir in org-load-path do
            (when (file-exists-p
                   (setq path
                         (expand-file-name
                          org-file
                          dir)))
              (throw 'result path))))
    (let ((default-directory (file-name-directory path)))
      (org-babel-load-file path))))

;; https://github.com/jkitchin/org-ref
;; for loading org-files
(add-to-list 'org-load-path
             (expand-file-name "org-ref" starter-kit-dir))

;; for loading emacs-lisp files
(add-to-list 'load-path
             (expand-file-name "org-ref" starter-kit-dir))

(org-require 'org-ref)
(org-require 'doi-utils)
(org-require 'pubmed)
(require 'jmax-bibtex)
```

```
emacs --debug-init
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  load-file(nil)
  org-babel-load-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org")
  (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
  (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
  org-require(org-ref)
  eval-buffer(#<buffer  *load*-55343> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1639
  load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
  load("~/mytools/customizations/emacs/config/orgref-config.el")
  eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
  load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

I have no idea why `/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org` is being searched for org-ref.

**Comment by jkitchin** [comment]
I think you want to change this
(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt/org-ref")

to

(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt/")

Chaitanya Krishna Ande writes:

> I get an error (below) using the following orgref config. My org-ref is in `/home/chaitanya/.emacs.d/opt/org-ref`.
>
> ```
> ; orgref also requires helm
> (require 'helm-config)
> ;(helm-mode 1)
> (autoload 'helm-bibtex "helm-bibtex" "" t)
> ;(setq helm-bibtex-bibliography "~/ownCloud/work/mypapers/mynewrefs.bib")
>
>
>
> ;; remember this directory
> (defconst starter-kit-dir (file-name-directory (or load-file-name (buffer-file-name)))
>     "Directory where the starterkit is installed.")
>
> ;;;;;;; org path for loadable org-files
> (defvar org-load-path
>   (list (file-name-as-directory
>          (expand-file-name "org" starter-kit-dir)))
>   "List of directories to find org-files that `org-babel-load-file' can load code from.")
>
> (defun org-require (feature)
>   "Load a FEATURE from an org-file.
> FEATURE is a symbol, and it is loaded from an org-file by the name of FEATURE.org, that is in the `org-load-path'.  The FEATURE is loaded from `org-babel-load-file'."
>   (let ((org-file (concat (symbol-name feature) ".org"))
>         (path))
>
>     ;; find the org-file
>     (catch 'result
>       (loop for dir in org-load-path do
>             (when (file-exists-p
>                    (setq path
>                          (expand-file-name
>                           org-file
>                           dir)))
>               (throw 'result path))))
>     (let ((default-directory (file-name-directory path)))
>       (org-babel-load-file path))))
>
> ;; https://github.com/jkitchin/org-ref
> ;; for loading org-files
> (add-to-list 'org-load-path
>              (expand-file-name "org-ref" starter-kit-dir))
>
> ;; for loading emacs-lisp files
> (add-to-list 'load-path
>              (expand-file-name "org-ref" starter-kit-dir))
>
> (org-require 'org-ref)
> (org-require 'doi-utils)
> (org-require 'pubmed)
> (require 'jmax-bibtex)
> ```
>
> ```
> emacs --debug-init
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   expand-file-name(nil)
>   load-file(nil)
>   org-babel-load-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org")
>   (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
>   (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
>   org-require(org-ref)
>   eval-buffer(#<buffer  *load*-55343> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1639
>   load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
>   load("~/mytools/customizations/emacs/config/orgref-config.el")
>   eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
>   load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
>   load("~/.emacs" t t)
>   #[0 "\205\262

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by icymist** [comment]
Similar result after the change. Maybe this helps, I only have org-ref in `~/.emacs.d/opt`.

```
chaitanya@winnie:~> ls -d ~/.emacs.d/opt
/home/chaitanya/.emacs.d/opt
```

```
diff --git a/emacs/config/orgref-config.el b/emacs/config/orgref-config.el
index 92c0245..e91e9aa 100644
--- a/emacs/config/orgref-config.el
+++ b/emacs/config/orgref-config.el
@@ -4,7 +4,7 @@
 (autoload 'helm-bibtex "helm-bibtex" "" t)
 ;(setq helm-bibtex-bibliography "~/ownCloud/work/mypapers/mynewrefs.bib")
 
-(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt/org-ref")
+(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt")
 
 ;; remember this directory
 (defconst starter-kit-dir (file-name-directory (or load-file-name (buffer-file-name)))
```

```
Debugger entered--Lisp error: (error "/home/chaitanya/mytools/customizations/emacs/config/org/: no such directory")
  signal(error ("/home/chaitanya/mytools/customizations/emacs/config/org/: no such directory"))
  error("%s: no such directory" "/home/chaitanya/mytools/customizations/emacs/config/org/")
  basic-save-buffer-2()
  basic-save-buffer-1()
  basic-save-buffer()
  save-buffer()
  run-hooks(org-babel-pre-tangle-hook)
  org-babel-tangle(nil "/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.el" "emacs-lisp")
  org-babel-tangle-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org" "/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.el" "emacs-lisp")
  org-babel-load-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org")
  (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
  (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
  org-require(org-ref)
  eval-buffer(#<buffer  *load*-527849> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1631
  load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
  load("~/mytools/customizations/emacs/config/orgref-config.el")
  eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
  load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

**Comment by jkitchin** [comment]
you do not need this line and should delete it.

(defconst starter-kit-dir
(file-name-directory (or load-file-name (buffer-file-name)))



Change
(defvar org-load-path
  (list (file-name-as-directory
         (expand-file-name "org" starter-kit-dir)))
  "List of directories to find org-files that `org-babel-load-file' can
  load code from.")

to

(setq org-load-path '())




Chaitanya Krishna Ande writes:

> Similar result after the change. Maybe this helps, I only have org-ref in `~/.emacs.d/opt`.
>
> ```
> chaitanya@winnie:~> ls -d ~/.emacs.d/opt
> /home/chaitanya/.emacs.d/opt
> ```
>
> ```
> diff --git a/emacs/config/orgref-config.el b/emacs/config/orgref-config.el
> index 92c0245..e91e9aa 100644
> --- a/emacs/config/orgref-config.el
> +++ b/emacs/config/orgref-config.el
> @@ -4,7 +4,7 @@
>  (autoload 'helm-bibtex "helm-bibtex" "" t)
>  ;(setq helm-bibtex-bibliography "~/ownCloud/work/mypapers/mynewrefs.bib")
>
> -(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt/org-ref")
> +(setq starter-kit-dir "/home/chaitanya/.emacs.d/opt")
>
>  ;; remember this directory
>  (defconst starter-kit-dir (file-name-directory (or load-file-name (buffer-file-name)))
> ```
>
> ```
> Debugger entered--Lisp error: (error "/home/chaitanya/mytools/customizations/emacs/config/org/: no such directory")
>   signal(error ("/home/chaitanya/mytools/customizations/emacs/config/org/: no such directory"))
>   error("%s: no such directory" "/home/chaitanya/mytools/customizations/emacs/config/org/")
>   basic-save-buffer-2()
>   basic-save-buffer-1()
>   basic-save-buffer()
>   save-buffer()
>   run-hooks(org-babel-pre-tangle-hook)
>   org-babel-tangle(nil "/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.el" "emacs-lisp")
>   org-babel-tangle-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org" "/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.el" "emacs-lisp")
>   org-babel-load-file("/home/chaitanya/mytools/customizations/emacs/config/org/org-ref.org")
>   (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
>   (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
>   org-require(org-ref)
>   eval-buffer(#<buffer  *load*-527849> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1631
>   load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
>   load("~/mytools/customizations/emacs/config/orgref-config.el")
>   eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
>   load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
>   load("~/.emacs" t t)
>   #[0 "\205\262

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by icymist** [comment]
I implemented the changes you mention above. I also had to add `(require 'json)` to avoid some json related error. I think it almost works. But, now I get some error related to pubmed.el.

```
Debugger entered--Lisp error: (void-function pubmed-get-medline)
  (pubmed-get-medline "23162369")
  eval-buffer(#<buffer  *load*-940802> nil "/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil t)  ; Reading at buffer position 33
  load-with-code-conversion("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" "/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil nil)
  load("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil nil t)
  load-file("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el")
  org-babel-load-file("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.org")
  (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
  (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
  org-require(pubmed)
  eval-buffer(#<buffer  *load*-796437> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1725
  load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
  load("~/mytools/customizations/emacs/config/orgref-config.el")
  eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
  load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

My present org-ref is [here](https://gist.github.com/icymist/eb40a2ffb21d709c4532#file-orgref-config-el).

**Comment by jkitchin** [comment]
Doh. I pushed some fixes to this. you can either update the org-ref git repo to fix this, or don't
load the pubmed code.

Chaitanya Krishna Ande writes:

> I implemented the changes you mention above. I also had to add `(require 'json)` to avoid some json related error. I think it almost works. But, now I get some error related to pubmed.el.
>
> ```
> Debugger entered--Lisp error: (void-function pubmed-get-medline)
>   (pubmed-get-medline "23162369")
>   eval-buffer(#<buffer  *load*-940802> nil "/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil t)  ; Reading at buffer position 33
>   load-with-code-conversion("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" "/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil nil)
>   load("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el" nil nil t)
>   load-file("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.el")
>   org-babel-load-file("/home/chaitanya/.emacs.d/opt/org-ref/pubmed.org")
>   (let ((default-directory (file-name-directory path))) (org-babel-load-file path))
>   (let ((org-file (concat (symbol-name feature) ".org")) (path)) (catch (quote result) (progn (let* ((--cl-var-- org-load-path) (dir nil)) (while (consp --cl-var--) (setq dir (car --cl-var--)) (if (file-exists-p (setq path ...)) (progn (throw ... path))) (setq --cl-var-- (cdr --cl-var--))) nil))) (let ((default-directory (file-name-directory path))) (org-babel-load-file path)))
>   org-require(pubmed)
>   eval-buffer(#<buffer  *load*-796437> nil "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil t)  ; Reading at buffer position 1725
>   load-with-code-conversion("/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" "/home/chaitanya/mytools/customizations/emacs/config/orgref-config.el" nil nil)
>   load("~/mytools/customizations/emacs/config/orgref-config.el")
>   eval-buffer(#<buffer  *load*> nil "/home/chaitanya/.emacs" nil t)  ; Reading at buffer position 344
>   load-with-code-conversion("/home/chaitanya/.emacs" "/home/chaitanya/.emacs" t t)
>   load("~/.emacs" t t)
>   #[0 "\205\262

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by icymist** [comment]
Thank you! :) The setup now works.

But, doi-utils.org does not tangle properly automatically when loading from the git-repo. It does work properly when I tangle it using org-babel-tangle on the file. I will post another issue on this.

**Comment by jkitchin** [comment]
Thanks for reporting this. I really need to get this source moved over to lentic! I have pushed a fix for the doi-utils issue.
