### ISSUE TITLE
org-ref-citation before em-dash

### ISSUE THREAD

**Issue by Perangelot** [jkitchin/org-ref#900]
There are two different styles for using hyphens for digressions in a sentence:

1) Blabla -- blubblub -- blebbleb. (space, endash, space)
2) Blabla---blubblub---blebbleb. (emdash, no spaces)

Now the problem I am facing is that I cannot put an org-ref-citation before an em-dash, because the em-dash is recognized as belonging to the citation. For example:

... also---especially in combination with methods developed in textcite:VanDijcke2021---provides ...

What works is putting the link in double brackets:

... also---especially in combination with methods developed in [[textcite:VanDijcke2021]]---provides ...

I find the brackets quite distracting, though. I have found no variable to change in order to tell org-ref that three dashes in a row end a citation. Have I missed something, or is that something that needs changing?

**Comment by jkitchin** [comment]
The double brackets are the best solution. It might be possible to use a non-breaking space as a separator too, but I haven't tried that. It is legal to have dashes in your key, so some separator is necessary.
