### ISSUE TITLE
Error inserting links with version 3

### ISSUE THREAD

**Issue by deb75** [jkitchin/org-ref#909]
Hello,

Here is a simple `test.org` file : 
```
#+TITLE test

\begin{equation}
\label{eq:1}
a = 2
\end{equation}
```

I would like to reference this equation. For this, I run `org-ref-inser-ref-link`, but i get the error
```
Invalid function: org-with-wide-buffer 
```
The same error also occurs with `org-ref-insert-label-link`.

By the way, are there still some similar helm functions in `org-ref` version 3 ?

Regards

Emacs 29.0.50 natively compiled on windows 10.

**Comment by jkitchin** [comment]
`org-with-wide-buffer` should be defined in org-macs.  If you run M-x load-library org-macs, does the error go away?

if so, it probably means I need to require that library somewhere in org-ref.

**Comment by deb75** [comment]
And yes ... this is the trouble.

Blacklisting all `org-ref` modules in which `org-with-wide-buffer` appears makes this issue disappear.

But there should be a nicer way to fix the issue. I will try to post it to the emacs mailing list.

Regards

**Comment by jkitchin** [comment]
If you add this somewhere (maybe org-ref.el is fine)

`(eval-and-compile (require 'org-macs))` 

does the problem go away?
