### ISSUE TITLE
file missing citeproc in org-ref-20211018.2229

### ISSUE THREAD

**Issue by darosio** [jkitchin/org-ref#910]
After updating to org-ref-20211018.2229 complains not finding citeproc.

No clues, sorry.

Loading package org-ref...
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "citeproc")
  require(citeproc)
  eval-buffer(#<buffer  *load*-976405> nil "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." nil t)  ; Reading at buffer position 2060
  load-with-code-conversion("/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." nil t)
  require(org-ref-export)
  eval-buffer(#<buffer  *load*-215497> nil "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." nil t)  ; Reading at buffer position 1357
  load-with-code-conversion("/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." nil t)
  require(org-ref-core)
  eval-buffer(#<buffer  *load*-516894> nil "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." nil t)  ; Reading at buffer position 1541
  load-with-code-conversion("/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." "/home/dan/.emacs.d/elpa/org-ref-20211018.2229/org-..." t t)
  require(org-ref nil t)
  (not (require 'org-ref nil t))
  (if (not (require 'org-ref nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-ref) :error) (let ((now (current-time))) (message "%s..." "Configuring package org-ref") (prog1 (condition-case err (progn (setq org-ref-completion-library 'org-ref-ivy-cite org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex org-ref-default-bibliography '("~/Sync/biblio/main.bib" "~/Sync/biblio/books.bib" "~/Sync/biblio/mine.bib" "~/Sync/biblio/former.bib" "~/Sync/biblio/MY.bib") reftex-default-bibliography '("~/Sync/biblio/biblio.bib")) (org-ref-ivy-cite-completion) t) ((debug error) (funcall use-package--warning138 :config err))) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package org-ref" elapsed) (message "%s...done" "Configuring package org-ref"))))))
  (prog1 (if (not (require 'org-ref nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-ref) :error) (let ((now (current-time))) (message "%s..." "Configuring package org-ref") (prog1 (condition-case err (progn (setq org-ref-completion-library 'org-ref-ivy-cite org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex org-ref-default-bibliography '... reftex-default-bibliography '...) (org-ref-ivy-cite-completion) t) ((debug error) (funcall use-package--warning138 :config err))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package org-ref" elapsed) (message "%s...done" "Configuring package org-ref")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package org-ref" elapsed) (message "%s...done" "Loading package org-ref"))))
  (let ((now (current-time))) (message "%s..." "Loading package org-ref") (prog1 (if (not (require 'org-ref nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-ref) :error) (let ((now (current-time))) (message "%s..." "Configuring package org-ref") (prog1 (condition-case err (progn (setq org-ref-completion-library ... org-ref-get-pdf-filename-function ... org-ref-default-bibliography ... reftex-default-bibliography ...) (org-ref-ivy-cite-completion) t) ((debug error) (funcall use-package--warning138 :config err))) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package org-ref" elapsed) (message "%s...done" "Configuring package org-ref")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package org-ref" elapsed) (message "%s...done" "Loading package org-ref")))))
  (progn (let ((now (current-time))) (message "%s..." "Loading package org-ref") (prog1 (if (not (require 'org-ref nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-ref) :error) (let ((now ...)) (message "%s..." "Configuring package org-ref") (prog1 (condition-case err ... ...) (let ... ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package org-ref" elapsed) (message "%s...done" "Loading package org-ref"))))) (add-hook 'org-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'bibtex-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'tex-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'markdown-mode-hook #'(lambda nil (require 'org-ref))) (progn (let* ((name "<f14> <menu> la") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'arxiv-add-bibtex-entry)) (let* ((name "<f14> <menu> lA") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'arxiv-get-pdf-add-bibtex-entry)) (let* ((name "<f14> <menu> ld") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'doi-utils-add-bibtex-entry-from-doi)) (let* ((name "<f14> <menu> li") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'isbn-to-bibtex)) (let* ((name "<f14> <menu> lp") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'pubmed-insert-bibtex-from-pmid)) (let* ((name "<f14> <menu> c") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'org-ref-insert-link)) (if (boundp 'bibtex-mode-map) (progn (let* ((name "<f14> <menu> h") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/body)) (let* ((name "<f14> <menu> b") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-in-browser)) (let* ((name "<f14> <menu> n") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-bibtex-notes)) (let* ((name "<f14> <menu> p") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-bibtex-pdf)) (let* ((name "<f14> <menu> h") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/body)) (let* ((name "<f14> <menu> i") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/org-ref-bibtex-new-entry/body-and-exit)) (let* ((name "<f14> <menu> S") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-sort-bibtex-entry)) (let* ((name "C-c l") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-store-bibtex-entry-link))) (eval-after-load 'org-ref #'(lambda nil (progn ... ... ... ... ... ... ... ...))))))
  (condition-case err (progn (let ((now (current-time))) (message "%s..." "Loading package org-ref") (prog1 (if (not (require 'org-ref nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-ref) :error) (let ((now ...)) (message "%s..." "Configuring package org-ref") (prog1 (condition-case err ... ...) (let ... ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package org-ref" elapsed) (message "%s...done" "Loading package org-ref"))))) (add-hook 'org-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'bibtex-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'tex-mode-hook #'(lambda nil (require 'org-ref))) (add-hook 'markdown-mode-hook #'(lambda nil (require 'org-ref))) (progn (let* ((name "<f14> <menu> la") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'arxiv-add-bibtex-entry)) (let* ((name "<f14> <menu> lA") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'arxiv-get-pdf-add-bibtex-entry)) (let* ((name "<f14> <menu> ld") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'doi-utils-add-bibtex-entry-from-doi)) (let* ((name "<f14> <menu> li") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'isbn-to-bibtex)) (let* ((name "<f14> <menu> lp") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'pubmed-insert-bibtex-from-pmid)) (let* ((name "<f14> <menu> c") (key (if (vectorp name) name (read-kbd-macro name))) (kmap (or (if ... ... nil) global-map)) (kdesc (cons (if ... name ...) (if ... nil ...))) (binding (lookup-key kmap key))) (let ((entry (assoc kdesc personal-keybindings)) (details (list ... ...))) (if entry (setcdr entry details) (add-to-list 'personal-keybindings (cons kdesc details)))) (define-key kmap key #'org-ref-insert-link)) (if (boundp 'bibtex-mode-map) (progn (let* ((name "<f14> <menu> h") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/body)) (let* ((name "<f14> <menu> b") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-in-browser)) (let* ((name "<f14> <menu> n") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-bibtex-notes)) (let* ((name "<f14> <menu> p") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-open-bibtex-pdf)) (let* ((name "<f14> <menu> h") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/body)) (let* ((name "<f14> <menu> i") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-bibtex-hydra/org-ref-bibtex-new-entry/body-and-exit)) (let* ((name "<f14> <menu> S") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-sort-bibtex-entry)) (let* ((name "C-c l") (key ...) (kmap ...) (kdesc ...) (binding ...)) (let (... ...) (if entry ... ...)) (define-key kmap key #'org-ref-store-bibtex-entry-link))) (eval-after-load 'org-ref #'(lambda nil (progn ... ... ... ... ... ... ... ...)))))) ((debug error) (funcall use-package--warning138 :catch err)))
  eval-buffer(#<buffer  *load*> nil "/home/dan/.emacs.d/init.el" nil t)  ; Reading at buffer position 135659
  load-with-code-conversion("/home/dan/.emacs.d/init.el" "/home/dan/.emacs.d/init.el" t t)
  load("/home/dan/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x15630777e265>) #f(compiled-function () #<bytecode 0x1563077946d5>) t)
  command-line()
  normal-top-level()

**Comment by deb75** [comment]
I solved that issue by installing `citeproc` from melpa.
