### ISSUE TITLE
org-ref version 3. Link to Configuration is broken

### ISSUE THREAD

**Issue by deb75** [jkitchin/org-ref#912]
Within the `README.org`, the link to the configuration ("*Configuration") for version 3 seems broken (error 404).

Could you provide a configuration example ?

Also, in version 2, the `org-ref-insert-ref-link` used to return the \label{xxx} with the context, usually the equation environment in which was the \label{xxx} statement. This was helpful to select the right label but with version 3, only the xxx are displayed. Is it normal ?

I am furthermore curious to understand how works `org-ref-insert-label-link`, `org-ref-insert-glossary-link` and `òrg-ref-insert-acronym-link`. Could you provide some examples ?

Regards

**Comment by jkitchin** [comment]
The link in the readme is probably a limitation of the github renderer, see https://github.com/jkitchin/org-ref/blob/master/README.org#configuration further down the page.

I added some code that should show the context for each reference label.

For label, it is just C-u C-u C-c ] the way I have it setup, you type a label and press enter.

See https://github.com/jkitchin/org-ref/blob/master/org-ref.org#glossaries-and-acronyms for more info on the glossary and acronyms. Maybe I will make a video on this, probably next week though.

**Comment by deb75** [comment]
Hi,

Currently, it does not seem the label context (mainly the latex environment) is shown. Did the added code was released in latest update ?

Regards
