### ISSUE TITLE
Latex Export Macro w/ Org-Ref

### ISSUE THREAD

**Issue by xxmissingnoxx** [jkitchin/org-ref#913]
I have a macro

```
#+MACRO: color @@html:<span style="color: $1">$2</span>@@@@latex:\textcolor{$1}{$2}@@@@odt:<text:span text:style-name="$1">$2</text:span>@@ 
```

which simply changes the color of the text on export. org-ref has worked until I combined the macro with org-ref.

This
```
Each project launched by
this framework {{{color(red, should have appropriate planning and
oversight (ref:sec:project_planning_and_oversight))}}} .
```
yields the latex code

```
Each project launched by
this framework \textcolor{red}{ should have appropriate planning and oversight (ref:sec:project_planning_and_oversight)} .
```

rather than the the \cref cross reference syntax we'd usually get. 

Is this something that is already handled by org-ref, or is this something about evaluation order in org-mode that might I can tweak?

Any help you could provide would be appreciated. I understand if this also falls outside the the scope of this project.

Thank you for your work on this project.

**Comment by xxmissingnoxx** [comment]
I initially guessed cref would have been replaced before the macro is applied, but I think that's not the evaluation order. I was expecting this:

```
Each project launched by
this framework \textcolor{red}{ should have appropriate planning and oversight (\cref{sec:project_planning_and_oversight})} .
```

**Comment by jkitchin** [comment]
but you are passing ref:sec:project_planning_and_oversight directly in $2 right? How could it get expanded to anything? It should just get used literally.

there isn't any mechanism to replace ref with cref in org-ref.  you should pass  cref:sec:project_planning_and_oversight in the macro if that is what you want.
