### ISSUE TITLE
ivy-current-prefix-arg void variable

### ISSUE THREAD

**Issue by bdarcus** [jkitchin/org-ref#914]
This variable as used currently in effect introduced an ivy dependency.

https://github.com/jkitchin/org-ref/blob/629ba6af438e26436a43914c56d9677b34253df4/org-ref-ref-links.el#L532

I forget the details, but I know there's a simple workaround.

**Comment by deb75** [comment]
When trying to insert some references to previous labels, I run into the error : 
```
﻿Symbol’s value as variable is void: ivy-current-prefix-arg
```

Is it what this issue is about ?

Regards
