### ISSUE TITLE
Tooltip on citation references

### ISSUE THREAD

**Issue by deb75** [jkitchin/org-ref#915]
If I introduce a reference like this : 
```
cite:&mykey2021
```
when I put the cursor or the mouse on it, nothing show up, neither tooltip nor something in the minibuffer.

According to the latest documentation, does something should appear ?

I remember I could at least see the full reference in the minibuffer with `org-ref` version 2.

Regards

Windows 10 - emacs 29.0.50

**Comment by jkitchin** [comment]
You should definitely see tooltips. I see them on my end.  

1. what color is the cite link?
2. if you click on it, do you get the menu?
3. if you turn off native-compiling for all org-ref files, does it work?

**Comment by deb75** [comment]
With the latest `org-ref` (previous issues fixed, thanks :-) ) : 
1. with `doom-solarized-dark` the cite link is yellow/gold
2. yes, clicking on it opens the menu
3. still no tooltips with removing all native compiled org-ref files.

Do you work on Linux or on Windows 10 ?

**Comment by deb75** [comment]
Yes, it is working !

But it still fails, otherwise. The previous issue (":catch:") seems due to native compilation. If I prevent `org-ref` from being natively compiled, this error goes away.

**Comment by deb75** [comment]
> 
> 
> The issue you have is that you don't have tooltips, and M-x org-ref reports them as bad links, right?
> 
> Here is an example org file that might help figure things out. Copy this text into a buffer, with the cite at the very beginning. It should start out red, but when you run the first block it will create test.bib, and then the link should turn green.
> 
> The next block should only find one key, and the last block is the function that calculates the tool tip. Any differences you see here are likely the place where it is not working.
> 
> ```
> [[cite:&xiao-2006-size-effec]]
> 
> #+BEGIN_SRC emacs-lisp :var tangle=(org-babel-tangle)
> (org-ref-find-bibliography)
> #+END_SRC
> 
> #+RESULTS:
> | test.bib |
> 
> #+BEGIN_SRC emacs-lisp
> (org-ref-valid-keys)
> #+END_SRC
> 
> #+RESULTS:
> | xiao-2006-size-effec |
> 
> #+BEGIN_SRC emacs-lisp
> (describe-text-properties 8)
> (with-current-buffer "*Help*" (buffer-string))
> #+END_SRC
> 
> #+RESULTS:
> #+begin_example
> Text content at position 8:
> 
> 
> There are text properties here:
>   cite-key             "xiao-2006-size-effec"
>   face                 org-ref-cite-&-face
>   font-lock-multiline  t
>   fontified            t
>   help-echo            org-ref-cite-tooltip
>   htmlize-link         (:uri "cite:&xiao-2006-size-effec")
>   keymap               [Show]
>   mouse-face           highlight
> 
> [back]
> #+end_example
> 
> 
> 
> #+BEGIN_SRC emacs-lisp
> (org-ref-cite-tooltip nil nil 8)
> #+END_SRC
> 
> #+RESULTS:
> : ⌘ Xiao, S., Hu, W., Luo, W., Wu, Y., Li, X., & Deng, H. (2006). Size effect on alloying ability and phase stability of immiscible bimetallic nanoparticles. The European Physical Journal B, 54(4), 479–484. http://dx.doi.org/10.1140/epjb/e2007-00018-6
> 
> #+BEGIN_SRC emacs-lisp
> (org-ref-bad-cite-candidates)
> #+END_SRC
> 
> #+RESULTS:
> 
> 
> bibliography:test.bib
> 
> 
> #+BEGIN_SRC bibtex :tangle test.bib
> @article{xiao-2006-size-effec,
>   author =	 {S. Xiao and W. Hu and W. Luo and Y. Wu and X. Li and H. Deng},
>   title =	 {Size Effect on Alloying Ability and Phase Stability of
>                   Immiscible Bimetallic Nanoparticles},
>   journal =	 {The European Physical Journal B},
>   volume =	 54,
>   number =	 4,
>   pages =	 {479-484},
>   year =	 2006,
>   keywords = {test, test2},
>   doi =		 {10.1140/epjb/e2007-00018-6},
>   url =		 {http://dx.doi.org/10.1140/epjb/e2007-00018-6},
>   DATE_ADDED =	 {Thu Oct 14 16:45:45 2021},
> }
> #+END_SRC
> ```

I did as you advocated.

First, I do not have the same bib file, it is not `test.bib` but the one settled in my configuration.

Also, when trying to evaluate the last code block, I get the error : 
```
No org-babel-execute function for bibtex!
```

**Comment by jkitchin** [comment]
The first cell should make test.bib, via tangling. The point of using this bib file is it should give the same output as shown above. You don't need to run the bibtex cell.

**Comment by jkitchin** [comment]
I added some tests that suggest tooltips work when org-ref is installed from MELPA.  Those tests don't run with native-compilation, but I can't see a problem with emacs29 and native compilation (I think) locally.  Are you still seeing a problem with tooltips?

**Comment by deb75** [comment]
Hello,

Yes I still have the issue.

I did again the test file you provided me.

Something different appears when executing the third block from beginning : 
```
#+BEGIN_SRC emacs-lisp
(describe-text-properties 8)
(with-current-buffer "*Help*" (buffer-string))
#+END_SRC
```

which gives me this : 
```
#+RESULTS:
: Text content at position 8:
: 
: 
: There are text properties here:
:   face                 org-drawer
:   font-lock-fontified  t
:   fontified            t
: 
: [back]
```

instead of 
```
#+RESULTS:
#+begin_example
Text content at position 8:


There are text properties here:
  cite-key             "xiao-2006-size-effec"
  face                 org-ref-cite-&-face
  font-lock-multiline  t
  fontified            t
  help-echo            org-ref-cite-tooltip
  htmlize-link         (:uri "cite:&xiao-2006-size-effec")
  keymap               [Show]
  mouse-face           highlight

[back]
#+end_example
```

Which version of `emacs` are you working with ? Is it native compilation enabled ? I should perhaps get the same version as you.

Regards

**Comment by jkitchin** [comment]
I am using emacs-28 with native-compilation enabled.

Some is wrong with how your org is parsing that document (assuming you used exactly that document, in a new buffer so that the cite is the first thing there and position 8 is actually in the middle of the cite), there is definitely no drawer there. That shouldn't matter though, even if there was, there should be those properties.

**Comment by deb75** [comment]
Yes, new buffer and first line is `cite:...`

I have emacs 29 (master), I will turn back to emacs-28.

**Comment by jkitchin** [comment]
It works fine for me with GNU Emacs 29.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.5 (Build 20G71)) of 2021-10-26

**Comment by deb75** [comment]
Hello,

I located where comes from this issue, it is from my configuration, the culprit is this line: 
```elisp
(use-package dap-mode :after lsp-mode :config (dap-auto-configure-mode))
```

If I remove it, I can see the tooltip in upper `test.org` file. If I put it again, I do no more see it.

I wonder what is behind this line and why it interacts badly with tooltips.

Regards

**Comment by jkitchin** [comment]
Hm, thanks for doing the detective work to figure that out. I have not heard of dap-mode. I am not sure what it would be doing, maybe it advises or monkeypatches parts of the tool tip / help echo code.  It sounds like we can close this issue.

**Comment by deb75** [comment]
For anyone runnning into this issue, it can be solved on the `dap-mode` side with : 
```elisp
(use-package dap-mode
     :after lsp-mode
     :init
      (setq dap-auto-configure-features '(sessions locals breakpoints expressions controls))
     :config (dap-auto-configure-mode))
```

Original value of `dap-auto-configure-features` is `(sessions locals breakpoints expressions controls tooltip)`

I removed `tooltip` from the list.

But this is only a temporary workaround, I will open an issue to `dap-mode`. So far I understand, there are no reasons for this to last.

Regards

**Comment by Paethon** [comment]
Thanks! I had exactly the same problem because of dap-mode!
