### ISSUE TITLE
Cite links show in red but otherwise work

### ISSUE THREAD

**Issue by ntrocado** [jkitchin/org-ref#918]
All cite links show in red and the tooltip says "Key not found".
They work perfectly though... Clicking the link opens the actions menu and I can open the bibtex file on the correct entry, open pdf, etc...
I don't know if it's related, but calling `M-x org-ref` on a buffer with nothing else than the cite link produces:
```
Wrong type argument: stringp, 47
```
`M-x bibtex-validate` on the .bib file gives no errors.

Emacs version: GNU Emacs 27.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.24) of 2021-09-07
Org version: 9.5
Org-ref version: 3.0

[My config](https://github.com/ntrocado/emacs-config)

**Comment by ntrocado** [comment]
`isbn-to-bibtex`, `doi-utils-add-bibtex-entry-from-doi` (and maybe others?) also expect a list...
I guess a similar change [here](https://github.com/jkitchin/org-ref/blob/e5db441b5fee12c144a0946de56ff2fd9adf3f32/org-ref-core.el#L199) should do the trick.

**Comment by jkitchin** [comment]
what is the error you see? These functions work fine when I use them.
