### ISSUE TITLE
Org to pdf not exporting references [moving from org-ref v2 to v3]

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#927]
I previously had a working version of org-ref, but after updating to v3 and making changes to my init.el, org-ref is not building the .bbl files that should contain the references I have in my document. 

My init file includes the following:
```
(use-package citeproc
  :ensure t)

(use-package ivy-bibtex
  :ensure t)

(use-package org-ref
  :after org
  :ensure t
  :init
  (require 'org-ref-pdf)
  (require 'org-ref-url-utils)
  ;;(require 'org-ref-latex) <- throws an error since org-ref v3
  (require 'org-ref-ivy)

  (setq
   bibtex-completion-bibliography '("/datadisk/references.bib")
   bibtex-completion-library-path '("/datadisk/Lit")
   reftex-default-bibliography    '("/datadisk/references.bib"))

  (setq
   bibtex-completion-notes-template-multiple-files "* ${author-or-editor}, ${title}, ${journal}, (${year}) :${=type=}: \n\nSee [[cite:&${=key=}]]\n")

  (setq
   bibtex-completion-additional-search-fields '(keywords))

  (setq
   bibtex-completion-display-formats
   '((article       . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${journal:40}")
     (inbook        . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
     (incollection  . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
     (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
     (t             . "${=has-pdf=:1}${=has-note=:1} ${year:4} ${author:36} ${title:*}")))

  (setq
   bibtex-completion-pdf-open-function
   (lambda (fpath)
     (call-process "open" nil 0 nil fpath))))

(advice-add 'bibtex-completion-candidates :filter-return 'reverse)

;; Key bindings
(define-key org-mode-map (kbd "C-c ]") 'org-ref-cite-insert-ivy)
```

An test docment that I created looks like this:

```
[[cite:&abe-2008-aging-cns]]
[[cite:&abe-2009-funct-coupl]]

bibliography:/datadisk/references.bib
bibliographystyle:unsrt
```

The error upon export that I receive is:
```
(...truncated...)
(.//test.out) (.//test.out) (.//test.toc)

LaTeX Warning: Citation `abe-2008-aging-cns' on page 1 undefined on input line 
32.


LaTeX Warning: Citation `abe-2009-funct-coupl' on page 1 undefined on input lin
e 33.

No file test.bbl.
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (.//test.aux)

LaTeX Warning: There were undefined references.

 ) </home/vincent/.texlive2019/texmf-var/fonts/pk/ljfour/jknappen/ec/ecbx1095.6
00pk> </home/vincent/.texlive2019/texmf-var/fonts/pk/ljfour/jknappen/ec/ecrm109
5.600pk> </home/vincent/.texlive2019/texmf-var/fonts/pk/ljfour/jknappen/ec/ecbx
1440.600pk>
Output written on .//test.pdf (1 page, 4622 bytes).
Transcript written on .//test.log.
```

Previously, the export command would build a .bbl along the tex file with all references that I selected from references.bib. This file is no longer being created. Perhaps related, but (require 'org-ref-latex) that I had in my org-ref v2 setup is no longer working in my v3 setup. It now throws the error:

```
Debugger entered--Lisp error: (wrong-type-argument listp "bibentry")
```

How can I fix this?

**Comment by jkitchin** [comment]
It looks like the bibentry definition was missing, I added it in the commit above. With that, something like this works for me now.

```
#+latex_header: \usepackage{natbib}
#+latex_header: \usepackage{bibentry}

[[nobibliography*:]]

some text
[[bibentry:&xiao-2006-size-effec]]  

more text


bibliographystyle:unsrt
bibliography:~/Dropbox/emacs/bibliography/references.bib
```

org-ref doesn't change how pdfs are built. It sounds like maybe `org-latex-pdf-process` isn't running bibtex? Can you manually run bibtex on the test.tex file that is created without errors?

If you run M-x org-ref on the test.org file, what is the output?

**Comment by vnckppl** [comment]
Thanks for the support!
I noticed org-ref complaining about biblatex not being installed, so I did a full reinstallation of texlive 202 (which did not resolve this). More information below.

**Comment by jkitchin** [comment]
I believe your issue is:
org-latex-pdf-process is defined as (pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f)

this does not run bibtex anywhere.

**Comment by vnckppl** [comment]
Yes, you are right. I must have removed this line from my org-ref V2 setup when I was building my org-ref V3 setup. Thanks for pointing this out.

**Comment by jkitchin** [comment]
Gad to hear it is working again! org-ref FTW.

**Comment by vnckppl** [comment]
:smile: org-ref all the way!
