### ISSUE TITLE
Permanently reloading the bibliography makes editing very slow

### ISSUE THREAD

**Issue by gdindi** [jkitchin/org-ref#928]
Hi,
I am recently having a very slow editing experience (using the latest MELPA package). I have a message in the minibuffer that appears very often that says "(re)loading bibliography" and Emacs freezes for a couple of seconds.

I have profiled the code and this is what I get.
```

        2011  56% - redisplay_internal (C function)
        1992  56%  - jit-lock-function
        1992  56%   - jit-lock-fontify-now
        1992  56%    - jit-lock--run-functions
        1992  56%     - run-hook-wrapped
        1992  56%      - #<compiled 0x19b68c6e595c08bd>
        1992  56%       - font-lock-fontify-region
        1992  56%        - font-lock-default-fontify-region
        1992  56%         - font-lock-fontify-keywords-region
        1992  56%          - org-activate-links
        1992  56%           - apply
        1992  56%            - edraw-org-advice-activate-links
        1992  56%             - #<subr org-activate-links>
        1992  56%              - org-ref-cite-activate
        1984  55%               + org-ref-valid-keys

```
I have a very large bibtex file, but this had never caused problems before. This seems a regression to me, but I don't know how to debug further. 

Do you have any advice?

Thank you.

**Comment by jkitchin** [comment]
That is a regression, there used to be a cache that is not currently used. Can you try this in your org-file (put it in and run it) and let me know if it helps?

```
#+BEGIN_SRC emacs-lisp
(defun j-org-ref-valid-keys ()
  "Return a list of valid bibtex keys for this buffer.
This is used a lot in `org-ref-cite-activate' so it needs to be
fast, but also up to date."
  
  ;; this seems to be needed, but we don't want to do this every time
  (unless bibtex-completion-display-formats-internal
    (bibtex-completion-init))

  (let ((files (org-ref-find-bibliography)))
    (cl-loop for entry in 
	     (cl-loop
	      for file in files
	      append (cddr (assoc file bibtex-completion-cache)))
	     collect (cdr (assoc "=key=" (cdr entry))))))

(advice-add 'org-ref-valid-keys :override #'j-org-ref-valid-keys)
#+END_SRC
```

**Comment by gdindi** [comment]
Thank you very much for your prompt reply! 
That seems to solve the issue. I am in the middle of writing a paper with lots of references, so I will test it all day long and come back to you if I see other issues.
If there's anything else I can do to help, I am willing to.
Thanks!

**Comment by ngharrison** [comment]
I had the same problem. Your new function seems to have fixed it for me too. Thanks for your work :)
