### ISSUE TITLE
org-ref overrides default org-store-link behavior for lable targets

### ISSUE THREAD

**Issue by oatmealm** [jkitchin/org-ref#929]
When I'm trying to store a link to a label target with `org-ref` loaded, I'm seeing these suggestions and unable to get a "native" default link as you'd expect. I'm using org-mode 9.5.

See attachment. Text in Hebrew but the label is visible (i.e. << .... >>) 

![Screenshot from 2021-11-03 19-45-25](https://user-images.githubusercontent.com/68159077/140174367-f1cc1e1b-f1ad-4a68-b861-5d627580e8a2.png)

**Comment by jkitchin** [comment]
That seems to happen for any link that has a store function. I put a question on the org-mode list to ask about it.

**Comment by jkitchin** [comment]
A cheap and easily reversible way to disable this is with:

#+BEGIN_SRC emacs-lisp
(defun override-org-ref-store-ref ()
  nil)

(advice-add 'org-ref-store-ref :override #'override-org-ref-store-ref)
#+END_SRC

**Comment by oatmealm** [comment]
Thanks so much. It works for me.
