### ISSUE TITLE
Customise indentation done by `org-ref-clean-bibtex-entry`

### ISSUE THREAD

**Issue by mandarm** [jkitchin/org-ref#931]
Just starting to use org-ref, so forgive me if the answer is well-known.

I use org-ref-clean-bibtex-entry frequently, and would like the cleaned bibtex entry to be indented a little differently from what I'm getting now. Specifically, this is what I get:

     url =
     {http://a.very.long/url.here},
     abstract = {A very long and verbose abstract 
     with continuation lines that are unindented wrt
     "abstract = ".

I'd like it to look like:

     url =
       {http://a.very.long/url.here},
     abstract = {A very long and verbose abstract 
       with continuation lines that are unindented wrt
       "abstract = ".
     keywords = {many many keywords
       that should continue on the next line with indentation}

Ideally, the amount of indentation should be `defcustom`-ed (like `python-indent-offset`, for example).

I haven't looked at the source code yet, but if this is easy to do, I can take a shot at it. OTOH, if it involves a (hopefully small) redesign, that's best done after a discussion as suggested by @jkitchin

**Comment by jkitchin** [comment]
No redesign is needed. You can achieve this by adding your own function to `org-ref-clean-bibtex-entry-hook`. I don't know how to make a function that does that, but if you have one, or write one, org-ref already supports using it.
