### ISSUE TITLE
arxiv-get-pdf has undesirable side effect of opening the pdf 

### ISSUE THREAD

**Issue by gcoladon** [jkitchin/org-ref#934]
At the end of arxiv-get-pdf, we check to see if the file is a valid PDF file, and open it if it is, and delete it otherwise.

I would like to skip the 'open it if is is' step. I assume the default functionality is still desired to remain 'open it if it is'. 

If that's the case, would it be reasonable to create a configuration variable like, arxiv-get-pdf-open-pdf, which wraps the call to `(org-open-file pdf)` which is set to true by default, but which I would set to false to suppress the opening?

Naturally I would be happy to implement this if it were considered a welcome alteration.

**Comment by gcoladon** [comment]
#+BEGIN_SRC elisp
(defvar arxiv-get-pdf-open-pdf t
  "Open the PDF after saving it to disk.")
#+END_SRC

and 

#+BEGIN_SRC elisp
        (if arxiv-get-pdf-open-pdf
            (org-open-file pdf))
#+END_SRC

**Comment by gcoladon** [comment]
I assume the above implementation would allow me to set the variable to nil in my startup configuration and it would stay nil after loading org-ref.. I will test to confirm

**Comment by jkitchin** [comment]
I feel like we should just take out the line that opens it. Your solution would be ok, and good for anyone who relies on that behavior though.

**Comment by gcoladon** [comment]
I had assumed you liked it that way :) If not, https://github.com/jkitchin/org-ref/pull/935

If there is wailing and gnashing of teeth about the change, we can add in the configuration variable

**Comment by jkitchin** [comment]
Sounds good. Thanks for the PR.
