### ISSUE TITLE
Latex export in org-ref 3: cite:&mykey exported to \cite{&mykey}

### ISSUE THREAD

**Issue by ffreise** [jkitchin/org-ref#937]
Hello,

when exporting an org-file with the new cite key format (with &) to tex-file with `org-latex-export-to-latex`, `cite:&mykey` is exported to `\cite{&mykey}`. Other cite commands (for example `citet`, `citep` or `nocite`) work as expected and the key is exported without `&` (for example `\citet{mykey}`).

I could reproduce the issue with basic.org from your example files.

Digging a bit deeper into the code, I found the function `org-ref-cite-export` in the file `org-ref-citation-links.el`, which looked like a possible candidate for the issue. I tried

`(apply (apply-partially 'org-ref-cite-export "cite") '("&mykey" "" latex))`

resulting in `\\cite{mykey}`, which seems to be fine. 

Deleting the byte compiled files or reinstallation did not solve the issue.

I am running org-ref 20211109.2359 from Melpa. (Emacs 27.2 on Windows 10 using msys2; Org 9.4.6)

Thank you very much in advance for any advice.

Best regards

Fritjof

PS: Thank you very for the great package.

**Comment by jkitchin** [comment]
I cannot reproduce your issue. I suspect you have another cite link definition from another package. In your org file, please run M-x org-ref and put the output here.

Alternatively, check the output of this src block in an org-file.

```
#+BEGIN_SRC emacs-lisp
(org-link-get-parameter "cite" :export)
#+END_SRC

#+RESULTS:
: #[128 "\302\300\303\301\"\"\207" [org-ref-cite-export ("cite") apply append] 6 "
: 
: (fn &rest ARGS2)"]
```

**Comment by ffreise** [comment]
You were right about another package defining cite: I had an `require(ox-bibtex)` in my init file, which I missed before.
The issue does not occur anymore, without the "require". Problem solved.

Thank you very much for your swift and helpful reply.

PS: For the sake of completeness: evaluating the code block you posted printed the same result as in your post.

**Comment by jkitchin** [comment]
weird. If the right export is being used you should not see this issue. Glad to hear it is working though.
