### ISSUE TITLE
Show citation in minibuffer (as in v2)

### ISSUE THREAD

**Issue by baracunatana** [jkitchin/org-ref#938]
Hi

As far as I can remember, org-ref v2 showed the full citation everytime I placed my cursos in a cite link. Now, in v3, I do see a tooltip (in the minibuffer) by placing my mouse over a citation link, but not with the cursor. Is there a way to activate the tooltip with the cursor?

**Comment by jkitchin** [comment]
That was done with a timer in version 2. I didn't put it in v3 because it seems like a funny way to do it. 

M-x display-local-help is the way to get that. It is bound for me to this ridiculous key binding C-c ! H. Some solutions are:

1. bind that to something reasonable to see it.
2. add a timer like in v2 to your init file so it works for you (https://github.com/jkitchin/org-ref/blob/org-ref-2/org-ref-core.el#L591 is the old definition). I think this is pretty close:

```
#+BEGIN_SRC emacs-lisp
(defvar org-ref-message-timer)

(defun org-ref-link-message ()
  (when (and (eq major-mode 'org-mode)
	     (eq (get-text-property (point) 'help-echo) 'org-ref-cite-tooltip))
    (display-local-help)))

(setq org-ref-message-timer
      (run-with-idle-timer 0.5 t 'org-ref-link-message))
#+END_SRC
```

**Comment by baracunatana** [comment]
Not the most prolific way of doing it, indeed.

I have very limited experience with elisp, so I'm sure there are better ways to do it, but how about

    (defun org-ref-link-message (&optional a1 a2 a3)
      (when (and (eq major-mode 'org-mode)
	   (eq (get-text-property (point) 'help-echo) 'org-ref-cite-tooltip))
      (display-local-help)))

    (advice-add 'right-char :after 'org-ref-link-message)
    (advice-add 'left-char :after 'org-ref-link-message)
    (advice-add 'evil-forward-char :after 'org-ref-link-message)
    (advice-add 'evil-backward-char :after 'org-ref-link-message)

**Comment by jkitchin** [comment]
If that works for you go for it!

**Comment by DiogoFerrari** [comment]
Here is another way to do it

```
(defvar org-ref-message-timer)
(defun org-ref-link-message ()
  (when (and (eq major-mode 'org-mode) (eq (get-text-property (point) 'help-echo) 'org-ref-cite-tooltip))
    (save-excursion (message (bibtex-completion-apa-format-reference (org-ref-get-bibtex-key-under-cursor))))
    )
  )
(setq org-ref-message-timer (run-with-idle-timer 0.5 t 'org-ref-link-message))
```

**Comment by DiogoFerrari** [comment]
Here is a way to do it, and works with [org-ref-prettify](https://github.com/alezost/org-ref-prettify.el) too.
```
(defun org-ref-get-bibtex-key-under-cursor--display ()
  "Return key under the cursor in org-mode.
If not on a key, but on a cite, prompt for key."
  (if-let ((key (get-text-property (point) 'cite-key)))
      ;; Point is on a key, so we get it directly
      key
    ;; point is not on a key, but may still be on a cite link
    (let ((el (org-element-context))
	  data
	  keys)
      (cond
       ;; on a cite-link type
       ((and
	 (eq (org-element-type el) 'link)
	 (assoc (org-element-property :type el) org-ref-cite-types))

	(goto-char (org-element-property :begin el))
	(setq data (org-ref-parse-cite-path (org-element-property :path el))
	      keys (cl-loop for ref in (plist-get data :references)
			    collect (plist-get ref :key)))
	(setq text nil)
	(dolist (key keys)
	  (search-forward key)
	  (goto-char (match-beginning 0))
	  (get-text-property (point) 'cite-key)
	  ;; (message (bibtex-completion-apa-format-reference key))
	  (setq text (concat text "\n" (bibtex-completion-apa-format-reference key)))
	  )
	))
      )
    )
  (message (string-trim-left text))
  )
(defvar org-ref-message-timer)
(defun org-ref-link-message ()
  (when (and (eq major-mode 'org-mode) (eq (get-text-property (point) 'help-echo) 'org-ref-cite-tooltip))
    (save-excursion (org-ref-get-bibtex-key-under-cursor--display))
    )
  )
(setq org-ref-message-timer (run-with-idle-timer 0.5 0 'org-ref-link-message))
```

**Comment by jkitchin** [comment]
What do you think about me adding something like this in a contrib.el file?

**Comment by DiogoFerrari** [comment]
That’ll be great. One caveat is that it won’t work with the old org-ref citation format (e.g., cite:key in older org files) if the cursor is under the bibtex key. I am using a workaround for that case, but it should be easy to fix.

**Comment by jkitchin** [comment]
hm. I adapted it when I added it, maybe I fixed that. I pushed a commit for this a bit ago.
