### ISSUE TITLE
Ubuntu 16.04 make fails,  cask command not found

### ISSUE THREAD

**Issue by ouboub** [jkitchin/org-ref#939]
Hi

I clone the repository and run make

the result is 

rm -f *.elc
cask exec ert-runner
make: cask: Command not found
Makefile:19: recipe for target 'test' failed
make: *** [test] Error 127

any ideas what to do

**Comment by ouboub** [comment]
ok, I cloned 
https://github.com/cask/cask.git
compiled and installed then I could compile.
I recommend to add this information

**Comment by jkitchin** [comment]
I don't actually run org-ref in compiled form. It doesn't seem to offer any advantage (e.g. it doesn't seem faster) and it is harder to debug.
