### ISSUE TITLE
Extra comma in pdf export when there are multiple citations

### ISSUE THREAD

**Issue by ngharrison** [jkitchin/org-ref#940]
When I insert multiple citations in one location (`[[cite:&key1;&key2]]`), the latex file shows up with `\cite[]{key1,key2}` and the pdf shows `[1,2,]`. Removing the empty `[]` in the latex file is a fix. I don't know the internals of the org exporting process well enough to have figured out an elisp workaround yet. I don't know if this is caused by org-ref, but it does seem to happen sometime during conversion of org-ref links to latex citations. I am using the normal org export instead of the org-ref one.

**Comment by jkitchin** [comment]
That is a bug, thanks for reporting it. I have pushed a probable fix for it.
