### ISSUE TITLE
arxiv-get-pdf fails with wrong-type-argument arrayp nil

### ISSUE THREAD

**Issue by gcoladon** [jkitchin/org-ref#941]
Starting around 2 weeks ago, I can no longer capture PDFs from arXiv because of an error that occurs when I execute a function like this one:

(arxiv-get-pdf-add-bibtex-entry "1312.5602" "~/pdfs/references.bib" "~/pdfs/")

Here's the backtrace:

Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  substring(nil 0 0)
  replace-regexp-in-string(":" "" nil)
  (lambda (key) (replace-regexp-in-string ":" "" key))(nil)
  orcb-key()
  #f(compiled-function (x) #<bytecode 0x1ffeafbf696d>)(orcb-key)
  mapc(#f(compiled-function (x) #<bytecode 0x1ffeafbf696d>) (org-ref-bibtex-format-url-if-doi orcb-key-comma org-ref-replace-nonascii orcb-& orcb-% org-ref-title-case-article orcb-clean-year orcb-key orcb-clean-doi orcb-clean-pages orcb-check-journal org-ref-sort-bibtex-entry orcb-fix-spacing orcb-download-pdf))
  org-ref-clean-bibtex-entry()
  arxiv-add-bibtex-entry("1312.5602" "~/pdfs/references.bib")
  arxiv-get-pdf-add-bibtex-entry("1312.5602" "~/pdfs/references.bib" "~/pdfs/")

I looked at all the git diffs to this file (org-ref-bibtex.el) over the last couple of months, and can't find any smoking gun that might explain why this would have broken.

**Comment by jkitchin** [comment]
That seems odd, the command you provided worked fine for me today.

I guess what could be happening is (bibtex-generate-autokey) is generating nil, and triggering that problem. That would have to do with you you setup bibtex autokey stuff I guess.

**Comment by gcoladon** [comment]
OK thanks for the pointer, I will investigate in that direction

**Comment by gcoladon** [comment]
Well I haven't figured out exactly what the problem is yet, but by removing some things from my configuration, the problem is currently in remission, so I will hereby close this issue as it doesn't appear to be an org-ref issue. Thanks again for the negative reproduction.
