### ISSUE TITLE
Ampersand in citation ruins export to latex

### ISSUE THREAD

**Issue by francisco-simoes** [jkitchin/org-ref#942]
When inserting citations using `org-ref-cite-insert-ivy` they appear as `cite:&<articlecodename>` instead of `cite:<articlecodename>`.
This doesn't break any links or anything, but when exporting to latex it exports as `\cite{&<articlecodename>}` instead of `\cite{<articlecodename>}`, which results in a citation error when exporting to PDF.

**Comment by jkitchin** [comment]
You may have some alternate export function on cite links, org-ref does not do that. Can you run M-x org-ref in the buffer where this happens, and paste the output here?

**Comment by francisco-simoes** [comment]
Here is the output:
```
#+title: org-ref report on [[/home/fsimoes/Documents/Notes/Surveys/structure_learning.org][structure_learning.org]]

org-ref called from /home/fsimoes/Documents/Notes/Surveys/structure_learning.org


* Bibliography

- No bibliography style found. This may be ok, if your latex class style sets that up, but if not this is an error. Try adding something like:
    bibliographystyle:unsrt
    at the end of your file.
- [[~/Documents/Library/library.bib]] (dialect = biblatex)

* Miscellaneous

- org-latex-prefer-user-labels = t
- bibtex-dialect = biblatex
- biblatex is not required.
- biblatex is not used.
- emacs-version = GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
 of 2021-01-18, modified by Debian
- org-version = 9.6
- org-ref: Version 3.0
- org-ref.el installed at /home/fsimoes/.emacs.d/.local/straight/build-27.1/org-ref/org-ref.el
- org-ref-insert-cite-function = org-ref-cite-insert-ivy
- org-ref-insert-label-function = org-ref-insert-label-link
- org-ref-insert-ref-function = org-ref-insert-ref-link
- org-ref-cite-onclick-function = (closure (t) (_) (org-ref-citation-hydra/body))
- org-latex-pdf-process is defined as (latexmk -shell-escape -bibtex -f -pdf %f)
- natbib is not required.
- natbib is not in org-latex-default-packages-alist or org-latex-packages-alist.
- cleveref is not required.
- cleveref is not in org-latex-default-packages-alist or org-latex-packages-alist.
- bibtex-completion installed = t
- bibtex-completion loaded = t
- org-latex-default-packages-alist
  ("AUTO" "inputenc" t ("pdflatex"))
  ("T1" "fontenc" t ("pdflatex"))
  ("" "graphicx" t)
  ("" "longtable" nil)
  ("" "wrapfig" nil)
  ("" "rotating" nil)
  ("normalem" "ulem" t)
  ("" "amsmath" t)
  ("" "amssymb" t)
  ("" "capt-of" nil)
  ("" "hyperref" nil)
-  org-latex-packages-alist
  ("" "minted")
- ox-bibtex loaded = t
- ox-bibtex loaded after org-ref = nil
- ebib loaded = nil
- ebib loaded after org-ref = nil
- cite link definition:
("cite" :follow org-ref-cite-follow :export
 #[128 "\302\300\303\301\"\"\207"
       [org-ref-cite-export
        ("cite")
        apply append]
       6 "

(fn &rest ARGS2)"]
 :complete
 #[128 "\302\300\303\301\"\"\207"
       [org-ref-cite-link-complete
        ("cite")
        apply append]
       6 "

(fn &rest ARGS2)"]
 :face org-ref-cite-face :help-echo org-ref-cite-tooltip :activate-func org-ref-cite-activate)

* LaTeX setup

latex is installed at /usr/bin/latex
pdflatex is installed at /usr/bin/pdflatex
bibtex is installed at /usr/bin/bibtex
biblatex is installed at nil
makeindex is installed at /usr/bin/makeindex
makeglossaries is installed at /usr/bin/makeglossaries

* Warnings
- No (org-ref) Warnings found.
* Utilities

- [[elisp:(progn (find-file "/home/fsimoes/Documents/Notes/Surveys/structure_learning.org") (ispell))][Spell check document]]
- [[elisp:(progn (find-file "/home/fsimoes/Documents/Notes/Surveys/structure_learning.org") (org-ref))][recheck document with org-ref]]
```

**Comment by jkitchin** [comment]
Can you change the cite type to something like citet, and see if it exports correctly? If it does, that is an indication something else is exporting the cite link, like ox-bibtex, for example, which seems to be installed.


The only other thing I see is you have not defined a bibliographystyle, and it doesn't appear you are using biblatex for the style. That is not the issue you report but might be an issue after you fix that.

**Comment by francisco-simoes** [comment]
Indeed `citet:&<articlecodename>` is exported correctly... Not sure what to do about it though.
About the bibliographystyle: I noticed that as well, but I am actually defining it with the export option `#+bibliography <path_to_bibtex_file> <style>`, and the bibliography is reproduced correctly in the pdf (and tex file). So I am not sure why it is complaining about the bibliographystyle.

**Comment by jkitchin** [comment]
That means some other function is being used outside of org-ref on export. That is something in your configuration, and probably the ox-bibtex, that is over-writing the org-ref link export for cite.

#+bibliography is not supported in org-ref I think, so if it is working, it is from some other package.

**Comment by francisco-simoes** [comment]
I am using `org-ref-cite-insert-ivy` to insert citations. Would it be possible to select citet or citep types of citations? (Right now this command adds a simple `cite` type of citation). That would both be useful and solve my issue as a workaround.

**Comment by jkitchin** [comment]
You should be able to set `org-ref-default-citation-link` (https://github.com/jkitchin/org-ref/blob/master/org-ref-citation-links.el#L99) to the default of your preference.

**Comment by AtomicNess123** [comment]
Is this ampersand after cite: something added in later versions of org-ref? All my papers have the format cite:REF instead of cite:&REF. Will these not work in new org-ref versions?

**Comment by jkitchin** [comment]
Both versions work in the org-ref v3.  The & is v3 syntax, and cite:REF is v2 syntax. You should even be able to mix them.

**Comment by philohistoria** [comment]
so If I wish to use V2 syntax (lots of old documents are in that format), how can I change the default behavior @jkitchin ? Thanks a lot!

**Comment by jkitchin** [comment]
Old documents should work fine.

You can use `(setq org-ref-cite-insert-version 2)` if you want to set the default insert format though for working in those documents.

**Comment by jkitchin** [comment]
that is right. You should not (and probably cannot) use both at the same time.

**Comment by AtomicNess123** [comment]
Thank you.
