### ISSUE TITLE
Multicites with page numbers

### ISSUE THREAD

**Issue by tsmacdonald** [jkitchin/org-ref#943]
Apologies if this has been answered elsewhere, but searching the project for "multicites" and similar hasn't gotten me very far.

I want to cite multiple sources at once, some of which have page numbers. The desired LaTeX is:

```latex
\autocites[p. 91]{alice}{bob}
```

Which results in a citation (Chicago style) of:

> Alice, *Emacs for Everyone*, p. 91; Bob, *LaTeX for the Lazy*

I have attempted the following without success:

```
[[autocites:&alice p. 91;&bob]]

[[autocites:alice,bob][p. 91]]
```

And a few others too silly to reproduce. What's the correct method?

I'm on org-ref version 1.1.1 and Emacs 27.1 on Linux. I have the following set:

```
(setq org-ref-default-citation-link "autocite")

(setq bibtex-completion-pdf-open-function 'org-open-file)

(setq bibtex-dialect 'biblatex)

(setq org-latex-pdf-process
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	"biber %b"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
```

Thanks!

**Comment by jkitchin** [comment]
For me, [[autocites:&alice p. 91; &bob]]

exports to \autocites[][ p. 91]{alice}{bob}

That looks close, but has the empty prefix in it. Isn't that equivalent to what you want? 

What is going wrong with your export?

**Comment by tsmacdonald** [comment]
@jkitchin Thanks, it's not expanding properly for me. Using real sources:

```
;; .org

Foo [[autocites:&freeman-humanist p. 91; &daiches-paradox]]
```

Expands to

```
%% .tex

\usepackage[notes,backend=biber]{biblatex-chicago}
\addbibresource{../../bibliography/refs-exported.bib}

<snip>

Foo \autocites{&freeman-humanist p. 91; &daiches-paradox}
```

```
%% .pdf
Foo²⁰

-------
20. &freeman-humanist p. 91; &daiches-paradox

```
%% refs-exported.bib

@Book{daiches-paradox,
  author = {David Daiches},
  <snip>
}

@Book{freeman-humanist,
  author = {F. W. Freeman},
  <snip>
}
```

**Comment by jkitchin** [comment]
Are you using the latest org-ref on Melpa?

**Comment by tsmacdonald** [comment]
Oh wow, I feel silly. Upgraded from 1.1.1 to 3.0 and we're off to the races. Glad it wasn't more complicated than that. Many thanks for the help!
