### ISSUE TITLE
Setting reference style for .odt export

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#944]
In my document I have the following line to set the citation format style:

`bibliographystyle:unsrt`

When I export to .pdf with `C-c C-e l p` (export to pdf) the references appear numbered in the text and in the bibliography as expected.

When I export to .odt with `C-c C-e r o`  (org-ref export to odt) the references appear in the text with the first author's last name and publication year and the bibliography list is sorted alphabetically on the first author's last name. 

Is there a way to set the bibliograpy and citation styles for ref-odt export?

**Comment by jkitchin** [comment]
For non-LaTeX export, you have to use the CSL preprocessor. You set the style with a CSL file like this.

#+csl-style: apa-5th-edition.csl

See https://github.com/jkitchin/org-ref/blob/master/examples/basic-csl.org#opendocument for an example.

see https://www.youtube.com/watch?v=Xs59PGTfDC0&list=PL0sMmOaE_gs3E0OjExoI7vlCAVygj6S4I&index=10&t=1s for details.

**Comment by vnckppl** [comment]
Thank you! This worked beautifully.
