### ISSUE TITLE
A key is inserted incorrectly in an existing citation link

### ISSUE THREAD

**Issue by alezost** [jkitchin/org-ref#951]
Hello,

If you insert a key when there is no link at point, it is inserted as "&key".
But when there is a link at point, it is inserted as ",key".

Try the following in an org-mode buffer.

1. ``M-: (org-ref-insert-cite-key "hello")``

   `[[cite:&hello]]` is inserted.

2. ``M-: (progn (insert "[[cite:]]") (backward-char 2) (org-ref-insert-cite-key "hello"))``

   `[[cite:,hello]]` is inserted.

This behavior is problematic because a yasnippet like this one:
``(yas-expand-snippet "[[parencite:`(org-ref-cite-insert-helm)`]]$0")``
inserts `[[parencite:,key]]` link.

**Comment by alezost** [comment]
Would it be appropriate to add the following check to `org-ref-insert-cite-key`?
If ``(org-element-property :path object)`` is empty, then insert "&key" as usual.
I can make a pull request if you wish.

**Comment by jkitchin** [comment]
I think the commit above is a way to handle this. It seems like the snippet approach is the only place this would pop up.

**Comment by Perangelot** [comment]
I'm afraid the commit does not work for me; still able to reproduce the error.

**Comment by jkitchin** [comment]
How did you update? I tried restarting emacs and using this and it worked fine for me.

**Comment by alezost** [comment]
Works for me! Thank you, @jkitchin !

**Comment by Perangelot** [comment]
@jkitchin That was my bad! I tried updating via MELPA but got an error which I did not notice. Now I manually changed the files and the fix works! Great, thank you. From my end, the issue can be closed.
