### ISSUE TITLE
org-ref-pdf-to-bibtex 

### ISSUE THREAD

**Issue by Horsevad** [jkitchin/org-ref#954]
This is my preferde way of adding new citations to my notes 
However with the new hcanges,  org-ref-pdf-to-bibtex   now only adds an entry to my references.bib files, but it does not create an entry in the notes.org. 

Before the was an option, "doi-utils-make-notes " i believe, to create an entry in the notes.org file, is there a reason for this to be removed or can it be reintroduced? 

I am gonna make a pull request in case it should go back

**Comment by jkitchin** [comment]
you can probably add a function to the `org-ref-clean-bibtex-entry-hook` that would create a notes entry.  That function would be run in the bibtex entry, and should get the key for that entry, and then run `(bibtex-completion-edit-notes (list thekey))` to open the notes.
