### ISSUE TITLE
Error with subtree export for method other than latex/pdf

### ISSUE THREAD

**Issue by dkeathley** [jkitchin/org-ref#958]
I see a consistent error on multiple computers when exporting with the scope set to subtree for all methods except for latex.  After tracking it down a bit in the org-ref-export.el file, I feel the issue is in the needed translation step before calling the standard org-export commands.  

Error I obtain is consistently: "user-error: Before first headline at position 1 in buffer FILENAME.org".

**Comment by dkeathley** [comment]
Sure -- no problem.  I've pasted the contents of a minimal org-file below and attached three different ascii .txt exports. Each .txt filename contains the series of keyboard shortcuts used for the export.  

 1. One for the entire file as ascii using org-ref-export
 2. One for the subheading 2.2 with the reference using org-ref-export, and 
 3. One for the same subheading using org-export.  

My cursor was on subheading 2.2 in both subheading export cases.  

Interestingly, with this minimal example (rather than my large file I use for day to day notes where I note the error in the original post) org-ref-export does not error, but consistently exports the incorrect subheading (while I get the correct behavior for plain org-export).  Hopefully this might be illuminating with regard to the problem? 

Note, with entire file exports using org-ref-export to any format, I never see an issue.

**Org-File Contents:**
```
* Heading 1

Test

** Subheading 1.1

Test

* Heading 2

Test

** Subheading 2.1

Test

** Subheading 2.2

This is a test of sub-tree export in org-ref.

[[cite:&zimmermanOpticalPropertiesElectrically2018]]
```






[org-export-subtree-C-c-C-e-C-s-t-a.txt](https://github.com/jkitchin/org-ref/files/7714215/org-export-subtree-C-c-C-e-C-s-t-a.txt)
[org-ref-export-subtree-C-c-C-e-C-s-r-a.txt](https://github.com/jkitchin/org-ref/files/7714216/org-ref-export-subtree-C-c-C-e-C-s-r-a.txt)
[org-ref-export-C-c-C-e-r-a.txt](https://github.com/jkitchin/org-ref/files/7714217/org-ref-export-C-c-C-e-r-a.txt)

**Comment by jkitchin** [comment]
Good news I think. I figured out what the issue was and I think the commit above addresses it. Let me know if it works for you.

**Comment by dkeathley** [comment]
Thanks!  It seems to work fine.  I'll close this issue and report back if I see anything else...  This package has increased my research efficiency immensely -- thanks for all your work on it!

**Comment by dkeathley** [comment]
After some more testing, there is still an issue with the subtree export.

While it now exportes the text and citations correctly within the subtree block, if I include a bibliography link such as `bibliography:ref-lib.bib` it then writes out a bibliography that includes all cite links even outside of the subtree.  

Here is a minimal org-file content and I have attached the odt file that results in C-c-C-e-C-s-r-o when my cursor is inside of subheading 2.2.  

```
* Heading 1

** Subheading 1.1

Test

* Heading 2

Test

** Subheading 2.1

Test

[[cite:&ziminPetahertzscaleNonlinearPhotoconductive2021]]

** Subheading 2.2

This is a test of sub-tree export in org-ref.

[[cite:&zimmermanOpticalPropertiesElectrically2018]]

bibliography:ref-library.bib
```
[test-subtree-export-org-ref.odt](https://github.com/jkitchin/org-ref/files/7741576/test-subtree-export-org-ref.odt)

**Comment by jkitchin** [comment]
Does the commit above resolve this for you?

**Comment by dkeathley** [comment]
Yep -- that did it.  Works like a charm now!
