### ISSUE TITLE
org-ref-clean-bibtex-entry does not abbreviate journal entries in the example org-ref.bib

### ISSUE THREAD

**Issue by cerkut** [jkitchin/org-ref#959]
Each try of `org-ref-clean-bibtex-entry` on each entry of the example org-ref.bib  exists with 
```
"Warning (emacs): Unable to get journal for this entry."
```
`org-ref-bibtex-generate-shorttitles` or `org-ref-bibtex-generate-longtitles` do not generate the corresponding files. Maybe `orcb-check-journal` returns nil or a wrong format, as I get the following backtrace, but I am not sure.

```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  downcase(nil)
  (string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry)))))
  (if (string= "article" (downcase (cdr (assoc "=type=" (bibtex-parse-entry))))) (progn (save-excursion (bibtex-beginning-of-entry) (let* ((entry (bibtex-parse-entry t)) (journal (cdr (assoc "=journal" entry)))) (if (null journal) (progn (warn "Unable to get journal for this entry."))) (if (member journal (-flatten org-ref-bibtex-journal-abbreviations)) nil (message "Journal \"%s\" not found in org-ref-bibtex-journal-a..." journal))))))
  orcb-check-journal()
  funcall-interactively(orcb-check-journal)
  call-interactively(orcb-check-journal record nil)
  command-execute(orcb-check-journal record)
  counsel-M-x-action("orcb-check-journal")
```

**Comment by cerkut** [comment]
Actually longtitles.bib and shorttitles.bib seem to be generated, but they only contain @Strings with Journal key and long/short titles and do not contain any bibtex entries.

**Comment by jkitchin** [comment]
I found a typo in the check-journal code that I fixed.

the longtitles/shorttitles has what I would expect to be in them, which is just string definitions. You have to combine this with `org-ref-stringify-journal-name`, and then use the original bib file, and one of longtitles.bib or shorttitles.bib in your org file, e.g.

bibliography:org-ref.bib,longtitles.bib

That isn't particularly well documented though.

I haven't used this probably since I wrote that code; it hasn't turned out to be that useful to me.

**Comment by cerkut** [comment]
Thanks for the fix. I now understand what `org-ref-stringify-journal-name`and `org-ref-set-journal-string`do. I'll start cultivating my own list of `org-ref-bibtex-journal-abbreviations`based on https://cassi.cas.org., The ability to combine (bibtex-map-entries 'org-ref-stringify-journal-name) will help to edit my bibliography for journals demanding strict abbreviations. I appreciate your time & help, thanks for the wonderful scimax and org-ref. Closing the issue.

**Comment by jkitchin** [comment]
If I had to deal with strict abbreviations, what I would probably do is write the paper, insert references with org-ref as usual, and at the end use `org-ref-extract-bibtex-to-file` to make a new local file with just the paper entries in it. Then I would use those functions above on this file, and not modify the main one. Maybe I am lucky with the journals I usually publish in, using abbreviations hasn't been required so far.
