### ISSUE TITLE
Cross references are not recognized properly by latex export

### ISSUE THREAD

**Issue by Lokdex** [jkitchin/org-ref#960]
As the title says, using `ref:figure1` is not properly mapped by org when exporting to LaTeX, however traditional org links with just the name of the resource works fine.

**Comment by jkitchin** [comment]
Could you show an example of where this fails? They just export as \ref{figure1}. How do you define the label?

**Comment by Lokdex** [comment]
Sure. Also, it is worth noting that it works fine with equations. I have seen the problem in tables, figures, and additional sections created, such as code snippets. During the selection of the cross reference it does list the elements, it is in the export process that somehow it fails.

With traditional org link:
`
It can contain tables as well, with captions, of course, as seen in table [[example-table]].

#+name: example-table
#+caption: Table with a custom caption.
| foo | bar | baz |
|   1 |   2 |   3 |
`

It produces in latex:
`It can contain tables as well, with captions, of course, as seen in table \ref{tab:org15ad105}.

\begin{table}[htbp]
\caption{\label{tab:org15ad105}Table with a custom caption.}
\centering
\begin{tabular}{rrr}
\toprule
foo & bar & baz\\
1 & 2 & 3\\
\bottomrule
\end{tabular}
\end{table}`

With org ref:
`It can contain tables as well, with captions, of course, as seen in table ref:example-table.

#+name: example-table
#+caption: Table with a custom caption.
| foo | bar | baz |
|   1 |   2 |   3 |`

It produces in latex:
`It can contain tables as well, with captions, of course, as seen in table \ref{example-table}.

\begin{table}[htbp]
\caption{\label{tab:org619caf8}Table with a custom caption.}
\centering
\begin{tabular}{rrr}
\toprule
foo & bar & baz\\
1 & 2 & 3\\
\bottomrule
\end{tabular}
\end{table}`

**Comment by jkitchin** [comment]
That is probably because you need to add

`(setq org-latex-prefer-user-labels t)` 

to your init file. There is also an html version of that variable.

**Comment by Lokdex** [comment]
Yes, that was it. I also set the HTML one and works as expected. Thank you for your help!
