### ISSUE TITLE
"No label found" error

### ISSUE THREAD

**Issue by drghirlanda** [jkitchin/org-ref#964]
Hi,

After some editing, I am getting a "No label found" error when exporting to LaTeX. I have been able to trace it to `org-ref-parse-cite-path` but I don't really understand the code enough to see what the able means. I am using v3 and for a good deal of editing this document I had no problem. The `*Messages*` buffer does not indicate where the document the error occurs. I was wondering what exactly can trigger that error... I have tried to "Check org file" from the org-ref menu, which gives the same error but no further hints.

**Comment by jkitchin** [comment]
This happens when there is no match between `org-ref-citation-key-re` and the references in a cite.  it is pretty odd, can you provide an example citation where this happens? Maybe the regexp doesn't match your keys somehow.

**Comment by drghirlanda** [comment]
Thanks! I added a `(message path)` at the beginning of that function to see what the offending citation was, and I had forgotten a `&` character while converting from v2 to v3 style. Maybe it would be useful to change that `error` call to include the offending citation. Maybe I'll put together a pull request for that if I feel I'm not overstepping my meager elisp knowledge.
