### ISSUE TITLE
Citing inside latex export blocks

### ISSUE THREAD

**Issue by Perangelot** [jkitchin/org-ref#968]
It sometimes happens that you need a LaTeX code block in your org-mode document, e. g. to draw a diagram. If you want to refer to a section within this diagram, the org-ref-syntax obviously won't work. Problematically, though, the section labels change every time you export the org-file to a LaTeX-file, so even LaTeX-code like `\hyperref[sec:label]{section x}` fails. What can you do about that? Is there a way to make static section labels?

**Comment by jkitchin** [comment]
Can you provide a small example that illustrates what you want? Maybe you just need to set `org-latex-prefer-user-labels` to `t`, and then put the label you want to use in that section.

**Comment by Perangelot** [comment]
Thanks for the reply. I wasn't aware that this variable exists, and it totally works. What I would appreciate, though, would be if static labels for headings (except those with :noexport: or :ignore: tags) that coincide with LaTeX's Heading Numbering would automatically be created to be used both with the org-ref-machinery and within LaTeX export blocks. An example:

* -> \label{1}
** -> label{1.1}
** :ignore:
** -> label{1.2}
* -> \label{2}

As has already bin shown in section cite:1.2, ...,

#+BEGIN_EXPORT latex
\begin{tabular}{ll}
This & is &
an & example \href{1.2}
\end{tabular}
#+END_EXPORT latex

**Comment by Perangelot** [comment]
Okay, I did not know there wasn't a way to update the existing refs in the LaTeX file. Guess you can close the issue. Thanks for your answer!
