### ISSUE TITLE
How to format notes in org-ref-3?

### ISSUE THREAD

**Issue by wztdream** [jkitchin/org-ref#970]
Hi,
Org-ref is very useful, I see there is a big change in version3. It has some very useful features,that is great. Thank you for your work.

But there is one thing that hinders me from upgrade to version3. In version 2 we can use `org-ref-reftex-format-citation` to insert headings with self defined format, it keep my notes clean,which is very handy. For example I can make heading to be:
```
* TODO  [#A] 1978 - logic for mathematicians - Hamilton
  :PROPERTIES:
  :CUSTOM_ID: a.g.hamilton-1978-logic-for-math
  :CITE: cite:a.g.hamilton-1978-logic-for-math
  :AUTHOR: Hamilton
  :JOURNAL: 
  :YEAR: 1978
  :VOLUME: 
  :PAGES: 
  :DOI: 
  :URL: 
  :END:
```
There are several benefit of this format:
1. the heading is clean and user can define the format
2. the properties can be used for searching, or sorting
3.  we can click the cite link to do lots of things

 But this function seems removed from version3, so is there any substitution for this function in version3? If not, is it possible to keep it as a tool in version3?

**Comment by jkitchin** [comment]
org-ref-3 uses bibtex-completion as much as possible now. It does what you are looking for, and I guess you probably need to look at `bibtex-completion-notes-template-multiple-files`. You can set it up to do this with something like this:
```
(setq bibtex-completion-notes-template-multiple-files
      "* TODO [#A] ${year} - ${title} - ${author-or-editor}
  :PROPERTIES:
  :CUSTOM_ID: ${=key=}
  :CITE: cite:&${=key=}
  :AUTHOR: ${author-or-editor}
  :JOURNAL: ${journal}
  :YEAR: ${year}
  :VOLUME: ${volume}
  :PAGES: ${pages}
  :DOI: ${doi}
  :URL: ${url}
  :END:

")
```

**Comment by wztdream** [comment]
Thank you, it is indeed what I am looking for!
