### ISSUE TITLE
org-ref v3 export handling of #+include files? 

### ISSUE THREAD

**Issue by brittAnderson** [jkitchin/org-ref#971]
I have a file1.org that has a line to `#+include: "file2.org"` Both files have cite links. I expected that the inclusion would precede the processing of citations, but I don't think it does. Exporting to html via `Ctrl-c Ctrl-e r h` I get the citations in file1.org correct, but for file2.org the cite:&some_cite just appear as raw unprocessed links. 

Is this the expected behavior? Is there a work around. I guess I could export file2.org to file2.html and include that as raw html, but then that would not allow the nice recognition of when the same citation is being used in both files to point to the same reference.

**Comment by jkitchin** [comment]
That is a surprise to see. I think I have found a fix for it. Let me know if the commit above works for you.

**Comment by brittAnderson** [comment]
Yes it does. Tested with a "repeated" reference and a new reference in the included file and a single number is given for the identical reference in both files on export, but a new number for the unique ones. Thanks much.
