### ISSUE TITLE
No such file or directory when org-ref updated via MELPA to 20220101.1941

### ISSUE THREAD

**Issue by spencerahill** [jkitchin/org-ref#973]
Maybe related to #925?  Tried updating org-ref via MELPA, which now points to 20220101.1941, and am unable to load it.  I have searched for any stale .elc files and there are none, so that's not the problem.

If others can't replicate this, perhaps you could suggest likely culprits?

```lisp
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "org-ref")
  require(org-ref)
  (progn (require 'org-ref))
  eval((progn (require 'org-ref)) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by spencerahill** [comment]
This was a byproduct of [this bug in 27.2 on MacOS relating to GnuTLS](https://emacs.stackexchange.com/questions/68288/error-retrieving-https-elpa-gnu-org-packages-archive-contents).  It was (silently) preventing org-ref from being properly installed.  With the workaround provided [here](https://emacs.stackexchange.com/a/68568/8818) I no longer have this problem.

**Comment by jkitchin** [comment]
huh. I have had code in scimax to fix that bug for emacs 26. I didn't know it was an issue for later ones too. That kind of issue has been a plague for many years!
