### ISSUE TITLE
Display equation context when making cross references

### ISSUE THREAD

**Issue by deb75** [jkitchin/org-ref#978]
Hello,

When I want to reference a previous label, e.g. an equation, `org-ref` used to display the label context, so that
it was very easy to choose the right label. Otherwise, it becomes tedious with a great number of labels.

With latest `emacs` and `org-ref` I do not see this behavior anymore, only the list of labels is displayed.
Is it normal ?

Regards

**Comment by jkitchin** [comment]
That doesn't sound right. With the latest version I see this:

![image](https://user-images.githubusercontent.com/1610070/149527032-610fd2e2-2c30-4685-ae04-03ecd6c17e85.png)

**Comment by deb75** [comment]
Hello,

I have just tried with latest `org-ref` and emacs 29.0.50. Calling `org-ref-insert-ref-link` does propose the labels but without the context hint. Is it the right function to call ?

Regards

**Comment by jkitchin** [comment]
yes, that is the function that leads to the screenshot above. I dont run anything as modern as emacs 29.  The actual completion is done by `org-ref-select-label`, and the context is provided by a completing read annotation function.

what completion backend are you using?

**Comment by deb75** [comment]
In a `.org` file, the `company-backend` variable is `nil` and `company-backends` is
```
(company-graphviz-dot-backend company-lua company-bbdb company-semantic company-cmake company-capf company-clang company-files
                              (company-dabbrev-code company-gtags company-etags company-keywords)
                              company-oddmuse company-dabbrev)
```

With 
```

\begin{equation}
\label{eq:0}\tag{0}
x^{3}+px +q = 0
\end{equation}

\begin{equation}
\label{eq:1}\tag{1}
x^{3}+px +q = 0
\end{equation}
```

`C-c [ ]` does give me the choice between `eq:1` and `eq:2`
![emacs](https://user-images.githubusercontent.com/19540378/149638337-6e5bcd82-c7b4-42ef-8002-f6bbd847658a.png)

Which completion mechanism/backend shoudl I use ?

Regards

**Comment by jkitchin** [comment]
org-ref does not use company. You should use something like ivy or helm for completion.

**Comment by deb75** [comment]
According to my screenshot, this seems to be `helm`

Here is my config : 
```emacs-lisp
(use-package org-ref)

(define-key bibtex-mode-map (kbd "H-b") 'org-ref-bibtex-hydra/body)
(define-key org-mode-map (kbd "C-c ]") 'org-ref-insert-link)
(define-key org-mode-map (kbd "C-c [") 'org-ref-insert-link-hydra/body)

(use-package org-ref-helm
  :init
  (setq org-ref-insert-link-function 'org-ref-insert-link-hydra/body
            org-ref-insert-cite-function 'org-ref-cite-insert-helm
            org-ref-insert-label-function 'org-ref-insert-label-link
            org-ref-insert-ref-function 'org-ref-insert-ref-link
            org-ref-cite-onclick-function (lambda (_) (org-ref-citation-hydra/body))))
```

The problem seems to lie more in the function providing the context, as you mentioned.
What is your completing-read annotation function ?

Regards

**Comment by jkitchin** [comment]
I use ivy. The annotation is done here https://github.com/jkitchin/org-ref/blob/master/org-ref-ref-links.el#L91, with standard completing read. It works with vanilla completing read and ivy, but appears not to work with helm.

**Comment by deb75** [comment]
I tried ivy instead of hem. It does not work either. Did you mean it works for you with ivy but not with helm ?

Regards

**Comment by jkitchin** [comment]
yes, it works for me in ivy.

**Comment by deb75** [comment]
Hi,

I managed to make it work with ivy.

Regards
