### ISSUE TITLE
How to use org-ref with vertico ?

### ISSUE THREAD

**Issue by aminevsaziz** [jkitchin/org-ref#979]
As title suggest how its possible to use vertico with org-ref v3. The manual is bit ambiguous for emacs newbies!
Furthermore, what is the relation between cigar and org-ref and is it possible to use both?

**Comment by jkitchin** [comment]
vertico should "just work" with org-ref I think. I think you just need to `(require 'org-ref)`. Then, I think you can use M-x org-ref-insert-cite-link and vertico should handle the completion. I have not tested this though.

I guess you mean citar? There is no relationship between these really, citar is for inserting org-cite citations AFAICT, and org-ref is for inserting org-ref citations. They look similar, but org-cite citations are part of org-syntax, and org-ref citations are org-links. You should not mix them in org-documents as they are treated separately and differently.
