### ISSUE TITLE
Wrong type argument: commandp, org-ref-insert-link-hydra

### ISSUE THREAD

**Issue by bdmalsch** [jkitchin/org-ref#982]
Inserting a link doesn't seem to work for me. I've tried looking online if anyone else got this message after using "C-c ]", but couldn't find anything. I'm fairly new to emacs and I'm trying to set it up for academic writing, let me know if you need more info and what I need to do to gather it. I installed org-ref via melpa and have a configuration similar to the one shown in the repo. 

After further investigation, typing "M-x org-ref-hydra/body" seems to do what "C-c ]" is supposed to do. However, when I then type c to insert a citation I get the message "Wrong type argument: commandp, org-ref-helm-insert-cite-link". It seems like emacs can't find some of the functions that are called by org-ref, is this because I'm missing some packages?

Emacs help returns this when looking up the keybind "C-c ]": Symbol’s function definition is void: org-ref-insert-link-hydra.

Thanks in advance.

**Comment by jkitchin** [comment]
You should probably hav e C-c ] set to something like `org-ref-insert-link-hydra\body`.

**Comment by bdmalsch** [comment]
I did so, it still gives me the same error message. Doing "M-x org-ref-hydra/body" also gives me this error message: "Wrong type argument: commandp, org-ref-helm-insert-cite-link".

**Comment by jkitchin** [comment]
That could mean you have not loaded the org-ref-helm library, e.g. `(require 'org-ref-helm)`. It is hard to say without seeing what your setup actually is.

**Comment by bdmalsch** [comment]
I installed org-ref through Melpa so dependencies should (?) be installed, let me know if (and what) I need to install something additionally; I added my dotfile as it currently stands if that helps...
[dotfile.txt](https://github.com/jkitchin/org-ref/files/7936336/dotfile.txt)

**Comment by jkitchin** [comment]
org-ref does not automatically install ivy or helm anymore, those have to be done manually.

You should probably require org-ref-helm before you try binding keys to commands that are defined in org-ref. Maybe move that up higher, to after the package-initialize line. 

Go back to https://github.com/jkitchin/org-ref#configuration, and make sure you are loading those things in the right order.

**Comment by bdmalsch** [comment]
Okay, so I installed ivy now and it still gave me the same message. I also cleaned up my configuration (see file below if necessary). Though, when I use "M-x org-ref-cite-insert-ivy" it seems to work like it should now. I remapped C-c ] to that command instead so I can cite at least. Thank you for helping me get this far so far btw. I can now, through some hoops, insert citations into my document, however a new issue popped up: PDF file produced with warnings: [undefined citation]. This happens with any citation I use...
[dotfile.txt](https://github.com/jkitchin/org-ref/files/7937448/dotfile.txt)

**Comment by jkitchin** [comment]
Undefined references probably mean one of these:
1. you don't have a bibliographystyle and bibliography link in the org file (these are required)
2. the pdf build process does not run bibtex.

**Comment by bdmalsch** [comment]
I added the bibliographstyle and bibliography so it must be the pdf build process. Again I'm fairly new, so how do I change the pdf build process so it uses bibtex? I tried doing something like (setq org-latex-to-pdf-process (list "bibtex")) but I guess that's not how it works.

**Comment by jkitchin** [comment]
See https://github.com/jkitchin/org-ref#latexpdf-export and/or https://github.com/jkitchin/org-ref/blob/master/org-ref.org#latex-export.

**Comment by bdmalsch** [comment]
That works, thank you deeply for taking the time to help me work through it!
