### ISSUE TITLE
Markdown export gone?

### ISSUE THREAD

**Issue by danielfleischer** [jkitchin/org-ref#983]
Hi! I like the package very much, been using it couple of years now. 

I can't seem to find the markdown export option. It's mentioned in the `org-ref.org` and in the main README but it's not in `org-ref-export.el`. 

Thanks!

**Comment by jkitchin** [comment]
that is a good question. I added one, I guess it is close to what was there before in v2.

If you prefer using the regular markdown exporter, you would need to use the pre-processing hook with `org-ref-csl-preprocess-buffer` instead.

**Comment by jkitchin** [comment]
Thanks. I saw the comment, and that transpose is surely a mistake!
