### ISSUE TITLE
Different Rendering of CSL compared to org-cite

### ISSUE THREAD

**Issue by danielfleischer** [jkitchin/org-ref#984]
Hi, I've noticed a difference of rendering between org-ref and org-cite, both using the same CSL file and the `citeproc.el` library. The difference is with spacing after numbers in bibliography, e.g. 1.Einstein vs. 1. Einstein. This in turn impacts HTML export - it adds unnecessary new lines after 1. 2. etc. 

**org-ref** code:

```
#+OPTIONS: toc:nil author:nil

* Papers
#+csl-style: ~/Zotero/styles/nature.csl

See [[cite:&vaswaniAttentionAllYou]]. 

[[bibliography:Library.bib]]
```

**org-cite** code:

```
#+OPTIONS: toc:nil author:nil

* Papers
#+cite_export: csl ~/Zotero/styles/nature.csl
#+bibliography: Library.bib

See [cite:@vaswaniAttentionAllYou].

#+print_bibliography:
```

**org-ref** output:
```
1 Papers
========

  See 1.

  1.Vaswani, A. et al. Attention is All you Need. 11.
```

**org-cite** output:
```
1 Papers
════════

  See ^{1}.

  1. Vaswani, A. /et al./ Attention is All you Need. 11.
```

--------

The `nature.csl` file is partially to blame due to the line `<text variable="citation-number" suffix="."/>`. However it seems org-cite has some extra processing to "normalize" this but I can't seem to find where it does it, to suggest a PR. 

Overall I think in this case org-ref is true to form while org-cite has some extra processing to make things nicer. Just wanted to point that out, if anyone wants to port that nice spacing processing, or not, and trust the CSL file to represent what we want to see.

**Comment by danielfleischer** [comment]
Sure, CSL is from [Zotero/nature](https://www.zotero.org/styles/nature) and here is the bib item:

```
@article{vaswaniAttentionAllYou,
  title = {Attention Is {{All}} You {{Need}}},
  author = {Vaswani, Ashish and Shazeer, Noam and Parmar, Niki and Uszkoreit, Jakob and Jones, Llion and Gomez, Aidan N and Kaiser, {\L}ukasz and Polosukhin, Illia},
  pages = {11},
  abstract = {The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 Englishto-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.0 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature.},
  langid = {english},
  keywords = {No DOI found},
  file = {/Users/dan/papers/Vaswani et al. - Attention is All you Need.pdf}
}
```

Thanks for looking into it!

**Comment by jkitchin** [comment]
This is somehow a CSS styling issue I think. The HTML for the bibentry seems to be the same for each one, but some csl styling is missing from the org-ref output. I don't have a fix for it, and it is HTML specific, so I have to think about the way to add it.

**Comment by jkitchin** [comment]
I think the commit above fixes html export for the nature.csl file (And anything close to it). It does not quite have feature parity with org-cite, but it is not far off for html.

**Comment by danielfleischer** [comment]
Thanks, these commits do improve the rendering for HTML. However they don't affect plain text and markdown which still has the "1.author" or "[1]author" issue which might need some other, non-CSS fix.

**Comment by jkitchin** [comment]
I think the only way to do these is first preprocess the buffer as an org export, and then to the desired format. I don't think it is a good idea to find some way to mogrify the output of citeproc; there are too many edge cases. I think this is basically what oc-csl does. It has a special case for html (which is fixed via css), and latex (fixed by package imports) and otherwise it seems to re-export it from org syntax I think.

Something like this in the file might do it:

```
#+bind: org-export-before-parsing-hook (lambda (_) (org-ref-process-buffer 'org))
# Local Variables:
# org-export-allow-bind-keywords: t
# End:
```
