### ISSUE TITLE
Initialisms and acronyms (capitals) in citations are set to lower case on export

### ISSUE THREAD

**Issue by vnckppl** [jkitchin/org-ref#985]
When I generate a pdf with citations using org-ref export, capital letters, other than that of the first word, are converted to lower case. This also is true for words that consist of all capitals (e.g., NATO become nato). Is there a setting that I can change to make sure that such words won't be converted to lower case?

**Comment by jkitchin** [comment]
This is a bibtex issue, not an org-ref one. It may be that your bibliography style does that automatically. In cases like NATO, you have to wrap that in curly brackets in your bibtex file like {NATO}. This generally works for things you want to preserve captitalization for.
