### ISSUE TITLE
Feature request: syntax for hyperlink/hypertarget

### ISSUE THREAD

**Issue by Perangelot** [jkitchin/org-ref#987]
It sometimes happens that one wants to refer to a specific word or sentence. In LaTeX you can do this using the package `hyperref` by defining  `\hypertarget{label}{word or sentence}` and then refer  to it using  `\hyperlink{label}{hyperlink text}` . As far as I have seen it, this is not covered by `org-ref` yet. Since using an org-ref alternative to this LaTeX syntax would not clutter your org-document with LaTeX-code, I think this is a useful addition. I suggest adding the following syntax:

`[[hypertarget:label&word or sentence]]`, and for a single word `hypertarget:label&word`.
`[[hyperlink:label&hyperlink text]`, and for a single word :`hyperlink:label&word`,

Since the label would always be between `hypertarget` and an ampersand, it would be easy to identify.

**Comment by jkitchin** [comment]
These look like straightforward org-link applications. I think they would look like

[[hypertarget:label][optional word or sentence]] and  later [[hyperlink:label][optional text]]

I think you can already do this with radio targets and fuzzy links though. For <<example>>, see [[example][example]]. This isn't ideal for a whole sentence I guess, but you just need a hyperlink to that location.

**Comment by jkitchin** [comment]
you can make links for this like this.

```
(org-link-set-parameters
 "hypertarget"
 :export (lambda (path description backend)
	   (format "\\textcolor{red}{\\hypertarget{%s}{%s}}" path path)))
(org-link-set-parameters
 "hyperlink"
 :export (lambda (path description backend)
	   (format "\\hyperlink{%s}{%s}" path path)))
```

the red color is optional, I just put it there to make it easy to see. It would take some work to see how this would translate to other backends.

**Comment by Perangelot** [comment]
Works like charm, the only thing is that the second occurrence of "path" should be replaced by "description". Thank you so much!
