### ISSUE TITLE
Google scholar .com instead of .co.uk

### ISSUE THREAD

**Issue by DiogoFerrari** [jkitchin/org-ref#99]
Hi,

When I open google scholar for a citation link that do not exist in my records, it gets to the .uk.co instead of https://scholar.google.com/. My current location is US, though. Is there any way to change it so that is open the https://scholar.google.com/ with my search.

Thanks

**Comment by jkitchin** [comment]
What exactly are you doing? Are you trying to insert a citation from helm bibtex, and there are no matches, so you select Google Scholar and get the uk.co site? That is the default setting in helm bibtex. If you add this to your init file, you can change what the action points to:

`(setf 
 (cdr (assoc "Google Scholar" helm-bibtex-fallback-options))
 "http://scholar.google.com/scholar?q=%s")`

**Comment by DiogoFerrari** [comment]
Perfect, that is exactly it !
