### ISSUE TITLE
How to include references/figures/tables in table of content

### ISSUE THREAD

**Issue by RidaAyed** [jkitchin/org-ref#990]
Looking at `org-ref.org` I saw `@@latex:\renewcommand{\indexname}{}@@` and thus tried `@@latex:\renewcommand{\listoffigures}{}@@` which results in a latex error though.

Did I miss something documented?

![screenshot](https://i.imgur.com/xiLzhbH.png)

**Comment by jkitchin** [comment]
Probably you should add this to the org file.

    #+latex_header: \usepackage{tocbibind}

This adds an entry to the toc like this:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/1610070/157241115-0d96a0c7-2eee-488b-b47e-b82226434041.png">

To get an entry in the section, you might add

    @@latex:\addcontentsline{toc}{subsection}{my list of figures}@@

above the list-of-figures link.

**Comment by RidaAyed** [comment]
Thank you that helps a lot

Any further ideas about the missing `Glossary` in the table of contents?
![screenshot](https://i.imgur.com/n3DEbKv.png)

```org
#+latex_header: \usepackage{tocbibind}
#+latex_header: \usepackage{glossaries}
#+latex_header: \makeglossaries
#+latex_header: \newglossaryentry{computer}{name=computer,description={A machine}}
* first
A gls:computer is good for computing. Gls:computer is capitalized. We can also use a bunch of glspl:computer to make a cluster. Glspl:computer are the wave of the future.
* second
 [[list-of-tables:]]
 [[list-of-figures:]]
 [[printindex:]]
 [[bibliographystyle:authordate1]]
 bibliography:/home/ra/org/basic.bib
 index:glossary
  \glsaddall
  \printglossaries
```
```emacs-lisp
  (setq org-latex-pdf-process
        '("pdflatex -interaction nonstopmode -output-directory %o %f"
	        "bibtex %b"
	        "makeglossaries %b"
	        "makeindex %b"
	        "pdflatex -interaction nonstopmode -output-directory %o %f"
	        "pdflatex -interaction nonstopmode -output-directory %o %f"
          )
        )

**Comment by jkitchin** [comment]
See https://tex.stackexchange.com/questions/98196/include-glossary-in-table-of-contents

    \usepackage[toc,section=section]{glossaries}

might work, although the answer suggests it is for book/report classes.  I haven't tried it on an article.

**Comment by RidaAyed** [comment]
Forgot latex due to `org-ref`'s :rocket: omnipresence in my workflow
