### ISSUE TITLE
Glossary definitions not added to LaTeX header when exporting subtree

### ISSUE THREAD

**Issue by jgbabyn** [jkitchin/org-ref#994]
When exporting a subtree using the newer table style of acronym and glossary definitions when exporting to LaTeX they are not converted to "\newacronym{blah}{BLAH}{Blah blah}" for me and don't appear in the header as expected. When I export the entire document it does work as you'd expect and acronym definitions end up in the header. If I use the old depreciated style used by org-ref adding "#+latex_header_extra:" in front of the definitions I am able to successfully export subtrees with acronym definitions in the header. I'm using org-ref 3.0 with emacs 27.2.

Is there something I'm just possibly missing in my setup? Thanks.

**Comment by jkitchin** [comment]
can you post a short example that illustrates the problem?

**Comment by jgbabyn** [comment]
Sure. I've attached a short org file as an example. Running C-c C-e C-s to select a subtree for export to LaTeX will result in the generated tex file of that subtree not having the necessary \newacronym line added in the header. It doesn't seem to matter if you export any of the subtrees in the file. Exporting the whole file does work.

[test.txt](https://github.com/jkitchin/org-ref/files/8306978/test.txt)

**Comment by jkitchin** [comment]
There was a bug in subtree export as you report. I think it is fixed above.

**Comment by jgbabyn** [comment]
Yes it seems to be! I just tried the new version. Thanks so much!
