### ISSUE TITLE
Hardcoded hook value for pdf export

### ISSUE THREAD

**Issue by wosined** [jkitchin/org-ref#998]
I'm not sure if this is an issue or not but in `org-ref-export.el` the function `org-ref-export-to-pdf` has a hardcoded value for `org-export-before-parsing-hook` making it impossible to add a custom `org-export-before-parsing-hook` to pdf exports.

![image](https://user-images.githubusercontent.com/102751856/161098724-64fb4f47-438c-44dc-aa51-1fcc97752b3b.png)

**Comment by wosined** [comment]
I'd like to add that this brakes the pdf export of references because org-ref-refproc is never used. So I had to comment out the `let`construct to make the references in the pdf export work.

**Comment by jkitchin** [comment]
I pushed a probable fix for this, it only temporarily adds the processor to that hook and its contents.

**Comment by wosined** [comment]
It works now.
